### ISSUE TITLE
__based pointers not working when used in a struct

### ISSUE THREAD

**Issue by pgrAm** [open-watcom/open-watcom-v2#1002]
So I tried to make a simple struct that contains a segment and a pointer based on that segment (this is for 16 bit DOS). However when I try to dereference the pointer p I get an "undefined symbol short unsigned __far S::seg" error

```
struct S {
	__segment seg;
	char __based(seg) *p;
};
```

I believe this is a bug, tested with the latest build

**Comment by jmalak** [comment]
Please, what message you get exactly?
Could you give here compilable sample which exhibit this issue.

**Comment by pgrAm** [comment]
```
#include <i86.h>
#include <stdio.h>

struct S {
    __segment seg;
    char __based(seg) *p;
};

int main()
{
    char c;
    struct S my_struct;
    my_struct.seg = FP_SEG(&c);
    my_struct.p = &c;

    printf("%c", *my_struct.p);

    return 0;
}
```

So I wrote a simple C program, compiled using `wcc main.c -i="C:\WATCOM/h" -w4 -e25 -zq -od -d2 -bt=dos -fo=.obj -ml` and now I am getting this error `main.c(6): Error! E1011: Symbol 'seg' has not been declared`

When I compile the same program using the C++ compiler (renamed to .cpp), the compiler crashes.

**Comment by jmalak** [comment]
Thanks.
I can reproduce it by both OW1.9 and OW 2.0 that it looks like some old bug.

**Comment by pgrAm** [comment]
Yeah the use case above is just a test case to demonstrate the issue, the real reason this would be useful is in a case like this.

```
struct array_data {
	__segment segment;

	Data __based(segment)* beginPtr;
	Data __based(segment)* endPtr;
	Data __based(segment)* maxPtr;
};
```

in this case I have 3 pointers that are all guaranteed to be in the same segment, because they all reference the same data. If they were all far pointers, not only would the structure be much larger, but the compiler would need to generate a lot more instructions to load and unload the segment registers even though they are all the same.

**Comment by jmalak** [comment]
The problem is that you cannot reference variable in prototype as segment.
generaly you can use near pointer instead of based pointer (because both use only offset) and on access data you can retype it for appropriate base pointer to generate correct far pointer to access data.

**Comment by jmalak** [comment]
#1016
