### ISSUE TITLE
c++ win32 abi incompatibility ??

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#1003]
This wavpack plugin for winamp: https://github.com/dbry/WavPack/tree/master/winamp
(see, in particular wasabi/wasabi.cpp in there.)

When built with MSVC or MinGW GCC, it loads and works. However, if built
with watcom, it instantly crashes. (this is the makefile: [Makefile.txt](https://github.com/open-watcom/open-watcom-v2/files/10058410/Makefile.txt))
If the c++ code and its associated functionality removed from the plugin
then the C-only built dll works fine.

Is there some C++ ABI incompatibility Watcom having here?

**Comment by jmalak** [comment]
I don't think that something as C++ ABI is standardized.
Watcom and MSVC C++ is different in many aspect.
I don't know how application is designed with regards to use of DLL entries etc.
It looks like some plug-in that you need to know how should look these DLL entries.
Main differencies are:
- symbol mangling, for compatibility is better use for DLL exported function with "C" linkage
- default calling convention, for compatibility exported function should use WIN32 stdcall or cdecl calling convention

if you describe how it should be then appropriate `**#pragma aux**` for DLL entries can be defined to properly interface plug-in (compiled with OW) with main application.

**Comment by sezero** [comment]
The public functions are not in the c++ code at all: that is not the issue.
What that c++ code does is shortly described by it author here:
https://github.com/dbry/WavPack/issues/146#issuecomment-1321457351
In essence, `Wasabi_Init()` is called, and then the wasabi code is talking
to winamp through some sort of Windows IPC using SendMessage().
I am _guessing_ that the watcom-built dll is _probably_ addressing the
wrong offsets for some c++ class members.

**Comment by sezero** [comment]
(And if you need anything else, such as asm outputs from mingw and watcom
builds, just tell me.)

**Comment by jmalak** [comment]
Thanks for all info. It could be also problem with C++ run-time library initialization in DLL.
Maybe you will need to add some linker directive to ensure proper DLL initialization and relocation.
I will look to documentation what plugin is expected.

**Comment by sezero** [comment]
OK thanks. If you need anything from me, just tell.

**Comment by sezero** [comment]
> One note. FASTCALL in **wavpack_local.h** should be changed for better efficiency with OW
> 
> ```
> #ifndef FASTCALL
> #if defined(__WATCOMC__)
> #define FASTCALL __watcall
> #elif defined(_M_IX86) || defined(__i386__)
> #define FASTCALL __fastcall
> #else /* !x86: */
> #define FASTCALL
> #endif
> #endif /* FASTCALL */
> ```

Thanks. Will suggest it.

**Comment by sezero** [comment]
In case you need: I attached a zip file containing objects from watcom build,
the map file generated by the linker, and `wdis -a` outputs of wasabi.obj from
both watcom and mingw-gcc builds.

[winamp.zip](https://github.com/open-watcom/open-watcom-v2/files/10060810/winamp.zip)

**Comment by jmalak** [comment]
I overlooked that you use -5s compiler option in this case the change to FASTCALL has no sense because it is overwritten by -5s option.

Anyway interface use binary ABI based on MSVC class encodings, that probably it is root cause of the problem.
It is probably different from OW, by example alignment etc. that offsets for members can be different, also order need not be same.

**Comment by sezero** [comment]
> Anyway interface use binary ABI based on MSVC class encodings, that probably it is root cause of the problem. It is probably different from OW, by example alignment etc. that offsets for members can be different, also order need not be same.

That's _exactly_ what I was afraid of. Can you think of a workaround? Or we can close this.

**Comment by jmalak** [comment]
At minimum data segments used by OW is different from MSVC and OW C++ run-time is different.
Main problem is that the interface is not portable.
It is fixed for MS compilers, because it is based on MSVC binary class structure instead of some portable structure.
I don't know if MS ABI documentation for C++ MSVC is available.
