### ISSUE TITLE
Is Open Watcom alive?

### ISSUE THREAD

**Issue by ta0590897** [open-watcom/open-watcom-v2#101]
Is the OW project alive in any flavor or fork? I don't understand where to ask questions. Sorry for spamming "Issues" but I don't understand where to ask a question.

**Comment by ytrezq** [comment]
@ta0590897 Yes it is alive again. Source code development on Perforce [restarted](http://perforce.openwatcom.org:4000/@md=d&cd=//depot/&c=uBY@//depot/?ac=43&mx=50).

**Comment by ArmstrongJ** [comment]
@ytrezq the Perforce server is up, but this fork is drastically further along in regards to the compiler and standard libraries.  The commits appear to be some work towards reverse engineering Open Watcom's `wgml.exe`, which is also a commendable enterprise if it ever reaches feature parity.

**Comment by ytrezq** [comment]
@ArmstrongJ so among the recents bugs fix [during the last week](http://perforce.openwatcom.org:4000/@md=d&cd=//depot/&c=uBY@//depot/?ac=43&mx=50), is there really none which have not been corrected since the time of the fork.

**Comment by ArmstrongJ** [comment]
@ytrezq oh no, that wasn't what I was trying to say.  The commits, like I said, were moving towards implementing a new version of wgml (I think, don't quote me).  Those fixes haven't been pulled into this repo to the best of my knowledge.  The Perforce Open Watcom development is taking a different track, though.

Jiri and developers here have been working on adding support for AMD64, better C99 compliance, additional Windows API updates, and, lately, ARM as a host architecture.  Those changes are not being pulled into the Perforce repo.  The two are effectively separate projects.

**Comment by ytrezq** [comment]
My point was if we can pull intersting changes from Perforce into this fork in the future.

**Comment by jmalak** [comment]
Yes it is possible by git cherry-pick function. It is one of reasons why owp4v1copy repository exists.

**Comment by sparky4** [comment]
oh!!! i have bugs to report ^^ and i have no idea how to compile it! ^^;

**Comment by jmalak** [comment]
Basc description of build process and commands are here https://github.com/open-watcom/open-watcom-v2/wiki/Build
You can also create issue here as bug report with problem description.

**Comment by sparky4** [comment]
Thank you! sorry for late reply~

**Comment by jmalak** [comment]
No problem.
