### ISSUE TITLE
bwasm: Error! E251: Symbol DOSSELTOFLAT is not defined

### ISSUE THREAD

**Issue by doehrm** [open-watcom/open-watcom-v2#1013]
` 15:26:12 /sources/watcom/open-watcom-v2/bld/clib/startup/library/os2.286/ms =
= 15:26:12 /sources/watcom/open-watcom-v2/bld/clib/startup/library/os2.386/mf_r =
bwasm -q -D_BLDVER=1300 -D_CYEAR=2022 ../../../a/tnkcdo32.asm -I"../../../h" -I"../../../../../../bld/clib/h"  -I"../../../../../../bld/watcom/h" -I"../../../../../../bld/lib_misc/h" -I"../../../../../../bld/comp_cfg/h"  -we -cx -fo=.obj -D__MT__ -D__MAKE_DLL_CLIB -D_EXPORT -mf -fpc-w8-e-5r  -bt=os2   -DNDEBUG
../../../a/tnkcdo32.asm(53): Error! E251: Symbol DOSSELTOFLAT is not defined
Error(E42): Last command making (tnkcdo32.obj) returned a bad status
Error(E02): Make execution terminated
non-zero return: 512
Build failed`

**Comment by jmalak** [comment]
Thanks for bug report.
It is fixed now.
