### ISSUE TITLE
failures at runtime since recent changes

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#1014]
Something has significantly changed in a bad way, between this:
`Open Watcom Make Version 2.0 beta Dec 12 2022 00:50:48 (32-bit)`
... and this version of OW:
`Open Watcom Make Version 2.0 beta Dec 14 2022 00:51:45 (32-bit)`

... and because of that, [SDL](https://github.com/libsdl-org/SDL/tree/SDL2)'s test programs, are failing at runtime,
as seen in github actions logs.

I haven't investigated myself yet, but I thought that you should know
as soon as possible.

**Comment by jmalak** [comment]
Please how I can get Makefile.w32 and Makefile.os2 ?

**Comment by sezero** [comment]
They are already in the source tree, but in SDL2 branch, so either do `git checkout SDL2`
or clone the repo like this: `git clone -b SDL2 https://github.com/libsdl-org/SDL.git`

**Comment by jmalak** [comment]
Thanks.
The default branch doesn't contain it. I checkout 3.0 prerelease and it is there.
Build works OK, I have no problem. How I can run all tests?

**Comment by sezero** [comment]
You should actually checkout `SDL2` branch. However that 2.0 prerelease
is an old branch where breaking changes had not yet gone in, so it_should_
build and work but no guarantees: I _do suggest_ checking out SDL2 branch
and working with it.

As to how running the tests: After building with Makefile.w32, do `cd test`
and  build the tests. Then copy SDL2.dll from top level and run a test,
e.g., `testatomic.exe`. For reference, here is how the github actions run
is made along with is failure report: (That `check-quick` thing just sets
environment variable `SDL_TESTS_QUICK=1` )
```
  cd test && wmake -f Makefile.w32 check-quick
  cd ..
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    WATCOM: C:\watcom
Open Watcom Make Version 2.0 beta Dec 14 2022 00:51:45 (32-bit)
Copyright (c) 2002-2022 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
	testatomic.exe
INFO: 
spin lock---------------------------------------

INFO: AtomicLock                   lock=1
INFO: AtomicUnlock                 lock=0
INFO: 
atomic -----------------------------------------

INFO: AtomicSet(10)        tfret=TRUE val=10
INFO: AtomicAdd(10)        tfret=TRUE val=20
INFO: AtomicIncRef()       tfret=TRUE val=1
INFO: AtomicIncRef()       tfret=TRUE val=2
INFO: AtomicDecRef()       tfret=TRUE val=1
INFO: AtomicDecRef()       tfret=TRUE val=0
INFO: AtomicCAS()          tfret=TRUE val=10
INFO: AtomicCAS()          tfret=TRUE val=20
INFO: Not running slower tests
Error(E42): Last command making (check-quick) returned a bad status
Error(E02): Make execution terminated
Error: Process completed with exit code 1.
```

**Comment by sezero** [comment]
One thing to note: If that `Error(E42)` line really means that the test
exited with `42`, then it is _possible_ that it is hitting `SDL_AbortAssertion`
i.e. at around here: https://github.com/libsdl-org/SDL/blob/SDL2/src/SDL_assert.c#L131

**Comment by jmalak** [comment]
My testing go over a few tests, but report a problem.
The problem is probably related to change in code generator to fix aborts pragma for various calling convention.
It looks like somehow wrong code is generated.

**Comment by sezero** [comment]
I see. Some commit around https://github.com/open-watcom/open-watcom-v2/commit/4f9b965b69c6c9bcd3c166f926411078908ebf11 and/or https://github.com/open-watcom/open-watcom-v2/commit/cfb07e6205eb089ce9f041511faf99b290a5aa41, I guess? (but that's just a guess, I have no idea about watcom internals...)

**Comment by sezero** [comment]
I built another project which marks several no-return functions with the `aborts` pragma using that bad ow snapshot. Upon running, when the program flow hits that function it just quits where it really should not.

**Comment by jmalak** [comment]
Thanks for all your info. 
The only change which do real change in code generator is commit 4f9b965b all others are mostly cleanup code commits. There is one change for WASM but it is only new option for full case sensitivity, but it doesn't change original behavior, it is new option.
I will try to check this code generator change and identify what is wrong.

**Comment by jmalak** [comment]
I think I found out source of problem.
Original implementation of NORETURN/ABORT feature suppose to be working on OW code function, because it uses optimization on caller and on function prolog which is not true for external functions if stack is handled by function.
Code generator has no info if it is OW code or external code that always use optimization on both sides.
It was reason that NORETURN/ABORT feature was used only for internal OW code ( C run-time library code ) and not for external functions as by example Windows API function. I will need to think more about it if we are able to get such info about function to switch type of optimization or switch off optimization (temporary solution) and use it for flow control check only.

**Comment by sezero** [comment]
Well, the current situation is utterly broken. I'd suggest reverting https://github.com/open-watcom/open-watcom-v2/commit/4f9b965b69c6c9bcd3c166f926411078908ebf11 (the #1010 fix) to see if things get back to normal but I'm sure you'd find a solution. (CC: @pts)

**Comment by jmalak** [comment]
Yes I am working on proper solution, it requires fix of frame/stack calculation to ensure that external (non-OW function get correct frame/stack pointer independent on calling convention.
I think I located all this stuff that I must change/test it now.
I understand it is not good situation, I will fix it ASAP.

**Comment by jmalak** [comment]
I checked my fix with SDL tests, but not sure if all is OK.
Here is lst1.txt output of "check-quick" and lst2.txt output of "check" 
[test.zip](https://github.com/open-watcom/open-watcom-v2/files/10243761/test.zip)
Please could you check if it is OK or not.

**Comment by sezero** [comment]
They looked OK to me at first glance.

**Comment by jmalak** [comment]
OK.
I will submit my fix.

**Comment by jmalak** [comment]
please check after Release re-build.

**Comment by sezero** [comment]
I took the 'Last-CI-build' (https://github.com/open-watcom/open-watcom-v2/commit/ef873d63b42f3083c1a842a90690292bf3c64009), built quakespasm with it: Unfortunately, the issue I described [above](https://github.com/open-watcom/open-watcom-v2/issues/1014#issuecomment-1352510511) is still there. When there is a 'Current-build' from that commit, I will re-run the failed SDL2 tests in github actions, but from the looks of it the issue is _not_ resolved yet.

**Comment by jmalak** [comment]
I check SDL build and tests by latest Current-Release and it works without problem.
Please give me reference and details for your issue/code to check.

**Comment by sezero** [comment]
SDL test failure isn't happening now in github CI, that part seems to be resolved.

The issue I'm having is elsewhere, will gather details and post to you as soon as I can.

**Comment by jmalak** [comment]
OK. It looks like some optimization is still active under some condition that it need identify.
One of possible problem is following optimization

```
call test1
ret
```
is optimized as
```
jmp test1
```
that if test1 is external function then it could be a issue

**Comment by sezero** [comment]
> The issue I'm having is elsewhere, will gather details and post to you as soon as I can.

I build [quakespasm](https://github.com/sezero/quakespasm) for win32, like:
`wmake -f Makefile.wat WINSOCK2=1 USE_SDL2=1`
The older working OW-2 snapshot I have is from Nov. 16, 2022.

With the current OW-2 build, the game 'quits' when it hits `Host_EndGame`
which is unexpected, but it doesn't 'quit' if it hits `Host_Error` which
is expected. `Host_EndGame` and `Host_Error` are here:
https://github.com/sezero/quakespasm/blob/master/Quake/host.c#L121
.. and both are declared with `aborts` pragma here:
https://github.com/sezero/quakespasm/blob/master/Quake/quakedef.h#L307-L312

Easiest way to make the game hit `Host_EndGame()` is running the game and
waiting: With default settings, the game starts by playing 3 demos, cycling
between them. When a demo ends, a `svc_disconnect` message is issued and
that calls `Host_EndGame`. In case of the old good OW-2 toolchain (or with
any other compiler) the engine moves on to play the next demo in its list.
In case of the new bad OW-2 toolchain, the game 'quits'. I use the quotes
here, because the game _possibly_ crashes, I actually don't know.

Here is the diff between good and bad asm outputs:
```diff
--- host.asm-good
+++ host.asm-bad
@@ -220,13 +220,13 @@
 	add		esp,4
 	ret
 	lea		eax,[eax]
 Host_EndGame:
 	sub		esp,400H
-	lea		eax,404H[esp]
+	lea		eax,408H[esp]
 	push		eax
-	mov		eax,dword ptr 404H[esp]
+	mov		eax,dword ptr 408H[esp]
 	push		eax
 	push		400H
 	lea		eax,0cH[esp]
 	push		eax
 	call		near ptr FLAT:q_vsnprintf
@@ -242,41 +242,42 @@
 	cmp		dword ptr FLAT:cls,0
 	jne		L$4
 	mov		eax,esp
 	push		eax
 	push		offset FLAT:L$130
-	jmp		near ptr FLAT:Sys_Error
+	call		near ptr FLAT:Sys_Error
 L$4:
 	cmp		dword ptr FLAT:cls+804H,0ffffffffH
 	je		L$6
 	cmp		dword ptr FLAT:cls+894H,0
 	jne		L$6
 	call		near ptr FLAT:CL_NextDemo
 	push		1
 	push		offset FLAT:host_abortserver
-	jmp		near ptr FLAT:longjmp
+	call		near ptr FLAT:longjmp
 L$5:
 	push		0
 	call		near ptr FLAT:Host_ShutdownServer
 	add		esp,4
 	jmp		L$3
 L$6:
 	call		near ptr FLAT:CL_Disconnect
 	push		1
 	push		offset FLAT:host_abortserver
-	jmp		near ptr FLAT:longjmp
+	call		near ptr FLAT:longjmp
 	lea		eax,[eax]
 	lea		edx,[edx]
 Host_Error:
+	push		ebp
 	sub		esp,400H
 	cmp		dword ptr FLAT:L$174,0
 	jne		L$8
 	mov		dword ptr FLAT:L$174,1
 	call		near ptr FLAT:SCR_EndLoadingPlaque
-	lea		eax,404H[esp]
+	lea		eax,40cH[esp]
 	push		eax
-	mov		ecx,dword ptr 404H[esp]
+	mov		ecx,dword ptr 40cH[esp]
 	push		ecx
 	push		400H
 	lea		eax,0cH[esp]
 	push		eax
 	call		near ptr FLAT:q_vsnprintf
@@ -299,19 +300,19 @@
 	mov		dword ptr FLAT:cls+804H,0ffffffffH
 	xor		ebp,ebp
 	push		offset FLAT:host_abortserver
 	mov		dword ptr FLAT:cl+224H,ebp
 	mov		dword ptr FLAT:L$174,ebp
-	jmp		near ptr FLAT:longjmp
+	call		near ptr FLAT:longjmp
 L$8:
 	push		offset FLAT:L$131
-	jmp		near ptr FLAT:Sys_Error
+	call		near ptr FLAT:Sys_Error
 L$9:
 	mov		eax,esp
 	push		eax
 	push		offset FLAT:L$132
-	jmp		near ptr FLAT:Sys_Error
+	call		near ptr FLAT:Sys_Error
 L$10:
 	mov		eax,dword ptr FLAT:com_argc
 	dec		eax
 	cmp		ebx,eax
 	je		L$12
@@ -378,10 +379,11 @@
 	add		esp,8
 	pop		esi
 	pop		ebx
 	ret
 	lea		eax,[eax]
+	mov		ecx,ecx
 Host_Version_f:
 	push		3ff170a3H
 	push		0d70a3d71H
 	push		offset FLAT:L$137
 	call		near ptr FLAT:Con_Printf
```

I'm also attaching the asm outputs, here: [asm.zip](https://github.com/open-watcom/open-watcom-v2/files/10248433/asm.zip)

**Comment by jmalak** [comment]
it is strange, what compiler command line you use?

**Comment by sezero** [comment]
Here it is:
`wcc386  -zq -wx -bm -bt=nt -5s -sg -otexan -fp5 -fpi87 -ei -j -zp8 -wcd=303 -DUSE_SDL2 -D_USE_WINSOCK2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS -DUSE_CODEC_MP3 -I../Windows/codecs/include -I../Windows/SDL2/include -fo=host.obj host.c`

**Comment by jmalak** [comment]
I see what problem is.
Assembly sourced ABORTS functions (in CRTL) are optimized for old optimization algorithm (incompatible with external functions) and it supposes that function is jump instead call, don't expect return address on stack.
I will fix CRTL assembly ABORTS functions to be correct then all should be OK.
C functions are OK because compiler generate new stack frame, only assembly source functions are problem as example longjmp function is wrong.

**Comment by jmalak** [comment]
May be we will need two ABORTS pragmas, one for internal use to optimize stack frame (remove return address) and second one for external use with standard stack frame.

**Comment by sezero** [comment]
>  as example longjmp function is wrong.

I see, that makes sense

**Comment by jmalak** [comment]
the commit dc2f837e444c8d895a4c17d4cc43642666e9fad8 should fix this issue.

**Comment by sezero** [comment]
> the commit [dc2f837](https://github.com/open-watcom/open-watcom-v2/commit/dc2f837e444c8d895a4c17d4cc43642666e9fad8) should fix this issue.

OK, will test as soon as a build is available

**Comment by sezero** [comment]
Tested with the latest 'Current-build' from https://github.com/open-watcom/open-watcom-v2/commit/e17a57d41f17307f13c87b49c6f89fdd0c8a7ab6, the issue is fixed. Thanks.  Feel free to close this ticket if there are no other issues.

**Comment by jmalak** [comment]
I did more investigation/tests and found out problem with C++ compiler which use internaly this old format to generate run-time code and also Fortran compiler use it.
Therefore I will change code generator to support two types of functions which not returns.
- **`#pragma aborts`** with old behaviour (without return address on stack)
- **`__declspec(aborts)`** with old behaviour (without return address on stack)
- **`__declspec(noreturn)`** with standard stack frame, compatible with ISO C standard
- **`_Noreturn`** specifier with standard stack frame, compatible with ISO C standard
- ??? may be we can introduce new **`#pragma noreturn`** as counterpart for **`#pragma aborts`**
first two can be used only for OW code (must be used in internal run-time code and by OW standard header files)
second two for OW and ISO C standard code (must be used for external related header files as WIN32 and OS/2 or LINUX etc.)

I will prepare more complex commit which include all previous fixes for new forms and original behavior for old forms.

**Comment by jmalak** [comment]
I submit final fix 12a52272fee09a8a47b6d1f91508d833c93e0f18
It enable use two types of no returning functions, old form `#pragma aborts` or `__declspec(aborts)`  and new form `__declspec(noreturn)` which must be used for external functions (outside OW compiled code) and is portable (compatible with ISO C standard _Noreturn)

Please could you retest your code with new compiler version after it will be re-build in Azure pipelines.

**Comment by sezero** [comment]
I took the 'Last-CI-build' from [this commit](https://github.com/open-watcom/open-watcom-v2/commit/a7192fe02d5db55058ba30608c64cbd10cbb2bf4) and built quakespasm with it. Both `#pragma aborts` and `__declspec(noreturn)` seem to work, thanks. This ticket can be closed, I guess.

P.S.: May I turn your attention back to https://github.com/open-watcom/open-watcom-v2/issues/375: It would be good to have a new preprocessor macro to identify OW-2 fork, maybe along with a build number macro, e.g. to help us decide that 'yes this version of OW has support for `__declspec(noreturn)` if that build number is >= some number.

**Comment by jmalak** [comment]
It is by default __WATCOMC__ macro has value 1300 for OW 2.0
OW 1.9 has value 1290 etc.

**Comment by sezero** [comment]
OK then. 

Closing the ticket.
