### ISSUE TITLE
Build break

### ISSUE THREAD

**Issue by DavidOgilvie** [open-watcom/open-watcom-v2#1019]
System: Windows 10 64-bit
command: build in <ow root> after (inadvertantly) running setvars.bat after a builder clean from <owroot>
I downloaded the latest source tree (tonight) except for wclass, gui and ide, which I am working on, and am using my sersion of those folders.
...
lib clib3s.lib
=========== 23:34:16 f:\ow2.0\bld\clib\process\library\msdos.086\mc ===========
cc abort.obj
cc cenvarg.obj
cc delay.obj
as doexec.obj
cc execaddr.obj
cc exl.obj
cc exle.obj
cc exlp.obj
cc exlpe.obj
cc exv.obj
cc exve.obj
cc exvp.obj
cc exvpe.obj
cc exwc2mb.obj
cc signl.obj
cc sigsy.obj
..\..\..\c\sigsy.c(243): Error! E1011: Symbol 'CTRL_BREAK_INT' has not been declared
..\..\..\c\sigsy.c(304): Error! E1011: Symbol 'CTRL_BREAK_INT' has not been declared
Error(E42): Last command making (sigsy.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 2
Build failed

f:\OW2.0>

Any suggestions would be appreciated!

**Comment by jmalak** [comment]
You are talking about _"I downloaded the latest source tree (tonight) except for wclass, gui and ide..."_
I am not sure how you merge OW sources with your local one, but take into account that you need complete OW sources update.
'CTRL_BREAK_INT' symbol was added in very near past and is located in bld/clib/h/_ctrlc.h
It looks like you have some old CRTL sources or wrong OW configuration script.

Try to review your OW setup script if it is up-to-date and check source file bld/clib/h/_ctrlc.h and bld/clib/process/c/sigsy.c
