### ISSUE TITLE
Local Debug crashes Windows on Win16

### ISSUE THREAD

**Issue by pwroberts** [open-watcom/open-watcom-v2#1020]
- Host platform: Win16 (Windows for Workgroups 3.11), repro'd on real 486 and a VMWare VM
- OW build: 2022-12-01 and 2020-09-08

Steps to reproduce:
- Launch the OpenWatcom IDE from Program Manager
- Open a project (e.g. samples\generic\win16\generic.wpj)
- From the Targets menu, select Local Debug (or press CTRL+D)

The machine crashes back to the DOS prompt (i.e. Windows itself dies) and hangs. OW doesn't try to build the target first; the crash is immediate. I imagine it's crashing when trying to call into the WDEBUG VXD?

Note: I think this is a separate issue from #1018, as it occurs in >=1 month old OW Win16 releases that do not have the "damaged" (Windows' word!) WDEBUG.386.

**Comment by jmalak** [comment]
Debugger requires wdebug.386 VxD driver.
I think it is same issue as #1018
It is fixed now, see details in #1018
