### ISSUE TITLE
DOS Text output vanishing on keyboard input with getch()

### ISSUE THREAD

**Issue by bastetfurry** [open-watcom/open-watcom-v2#1021]
I am writing a game in ANSI text mode and have a problem with text output vanishing when i want to receive input with getch from conio.h. Is that a known bug? Works fine under Linux with GCC. :(
Doing nothing fancy here, in essence just printf() and getch() involved.

Tested with 86box as an IBM XT with CGA running MSDOS 5.0, checked with MS ANSI.SYS and ANSI.COM V1.3l 

Example pictures, the "? (y/n)" should have been there from the start:
![Monitor_1_20230105-194800-85085](https://user-images.githubusercontent.com/3686292/210857576-20372841-ed24-453f-9f2c-48beca1584d0.png)
![Monitor_1_20230105-194906-801801](https://user-images.githubusercontent.com/3686292/210857579-338d2da2-77c6-48bf-9907-d4f45c1dc6b1.png)

**Comment by bastetfurry** [comment]
On the second picture the compass arrow is missing, this was the last element drawn in that screen.

**Comment by jmalak** [comment]
please could you give here compilable sample code which demonstrate an issue.

**Comment by bastetfurry** [comment]
I tried to boil it down with a short snippet that writes tons to the screen and then waits with a getch() but the bug only shows in the game and only with Watcom under DOS. I could send you my games code, don't want it to be open just yet only later, and you could check why Watcom behaves differently then GCC or CLang

I used CMake with `cmake ..  -DCMAKE_SYSTEM_NAME=DOS -DCMAKE_SYSTEM_PROCESSOR=I86 -G "Watcom WMake"`
which then uses these flags: -g -Os -d2

**Comment by jmalak** [comment]
OK, I understand.
But your compiler options are strange and can be a source of problem.
Option -g is very specific option and requires code segment name.
It looks like a problem with CMake configuration.
Could you give me your CMake configuration file?

**Comment by bastetfurry** [comment]
Here you are, this is partly generated by CLion and handedited by me.
[CMakeLists.txt](https://github.com/open-watcom/open-watcom-v2/files/10359355/CMakeLists.txt)

**Comment by jmalak** [comment]
Yes, your CMake configuration file is for GCC compiler not for Open Watcom.
Try to remove following line and check with OW
```
set(CMAKE_C_STANDARD 11)

set(CMAKE_C_FLAGS "-Wall -g -Os")
```

**Comment by jmalak** [comment]
@bastetfurry Any news?

**Comment by bastetfurry** [comment]
As i had developed some further i can't compile the project anymore as Watcom seems to be missing a feature, VLAs, that i would need:

`int SelectBox(int size, int charlen, char list[size][charlen], int preselected, int topoffset);`

I get:

```
/home/bastetfurry/Projekte/RPGEngine/src/helper.h(35): Error! E1011: Symbol 'size' has not been declared
/home/bastetfurry/Projekte/RPGEngine/src/helper.h(35): Error! E1054: Expression must be constant
/home/bastetfurry/Projekte/RPGEngine/src/helper.h(35): Error! E1011: Symbol 'charlen' has not been declared
/home/bastetfurry/Projekte/RPGEngine/src/helper.h(35): Error! E1054: Expression must be constant
```

So now i have to rewrite that function first because OW is not fully C99 compliant yet. -.-

**Comment by bastetfurry** [comment]
Made changes so that it compiles again :)
But the bug still remains.

**Comment by bastetfurry** [comment]
The log function does nothing fancy:
```
void Dungeon_DrawLog()
{
    uint8_t b;

    for (b = 0; b < 6; b++)
    {
        Locate(27, 19 + b);
        Print("                                                   ");
        Locate(27, 19 + b);
        Print("%s", loglines[b]);
    }
}

// And the two functions, nothing fancy:
void Locate(uint8_t x, uint8_t y)
{
    if (x < 1)
        x = 1;

    if (x >= GFX_CELLS_WIDTH)
        x = GFX_CELLS_WIDTH;

    if (y < 1)
        y = 1;

    if (y >= GFX_CELLS_HEIGHT)
        y = GFX_CELLS_HEIGHT;

    printf("\x1b[%d;%dH", y, x);
}

// The idea is that i can later redirect this to some SDL-backed function 
void Print(const char *fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    vfprintf(stdout, fmt, ap);
    va_end(ap);
}
```

**Comment by jmalak** [comment]
Yes, C99 VLA is still not implemented in OW.

**Comment by jmalak** [comment]
It looks like stdout internal buffer flushing problem.

Please could you try to use explicit flush for stdout before getch to check this hypothesis.

**Comment by bastetfurry** [comment]
Not at home, will try later.
A simple fflush(STDOUT); should be enough?

**Comment by jmalak** [comment]
yes exactly.
