### ISSUE TITLE
DOS installer is extremely slow

### ISSUE THREAD

**Issue by volkertb** [open-watcom/open-watcom-v2#1025]
Hi,

The Open Watcom v2 C DOS installer (` open-watcom-2_0-c-dos.exe `) is glacially slow with unpacking and copying all the files to their desination paths.

It takes more than a half an hour, perhaps as much as an hour or even more for a full installation. I noticed this in VM instances under both VirtualBox and QEMU, even with hardware-assisted virtualization through KVM on a Linux host with an SSD.

I noticed something else that is quite inefficient: when installing in a not-yet-existent target directory, for instance the default `C:\WATCOM\`, it first creates the directory and then proceeds to scan that directory for any remnants of a previous installation, which is completely pointless. This should only be done when the target directory already exists, and even then, a quick file count check should be made to determine whether the target directory is empty or not, before scanning the directory for any specific existing files, if there are any already present.

But as inefficient that first step is, it's still (at most) no more than a few minutes. The subsequent unpacking and copying of the files is the part that is really slow and takes way longer than it should. Certainly there has to be a way to speed all of this up considerably.

I wouldn't mind looking into this myself, but the file and directory structure under `bld/setupgui` looks a bit overwhelming. It appears to be a multi-platform installer with a shared code base across target OSes, including DOS. Some advice on where to look first would be nice. In particular, where the file decompression and unpacking code can be found, and where the DOS-specific file writing routines are located.

I wouldn't mind getting my hands dirty with this and hopefully get a Pull Request ready for you to review, if you could point me in the right direction. Thanks. :slightly_smiling_face:

**Comment by volkertb** [comment]
Also interesting: after finally having copied all the files to the target directory, the installer offers to update the `CONFIG.SYS` and `AUTOEXEC.BAT` files for you. I was installing this on FreeDOS, which doesn't have those files by default. (Although it can use those files if they are present, but I digress.) Anyway, even if I answer "no" (or "let me update these files later", or whatever the exact wording is), it still complains about these files not existing and offers the option to newly create those files in `C:\`. Afterwards, the installation finishes, and the `CONFIG.SYS` and `AUTOEXEC.BAT` files it ended up creating are both empty.

This is also a bug. If I choose to update these files myself later, it shouldn't even check for the existence of these files, and also not warn me if it can't find them. This part of the installer should be skipped, unless I've chosen the option to have the installer update these files for me.

Again, I can look into this myself, by searching for the strings `CONFIG.SYS` and `AUTOXEC.BAT` in the source code of this project. But again, should you know more about this, some pointers in the right direction would be welcome. Thanks again.

(I could also create a separate issue for this if you prefer, since it's technically a separate bug.)

**Comment by jmalak** [comment]
Thanks for your problem report.
I will check on my DOS test box.

**Comment by jmalak** [comment]
Anyway in setupgui (installer) project is minimum OS specific code it use ISO C or POSIX C run-time library function.
I suspect the LFN special code. I will try configure setupgui to not use it because it is not necessary for the installer.

**Comment by jmalak** [comment]
I disable LFN in DOS installer by change e8fcd294568943b05b5e966c8faf87bbed33811d
Please could you check new DOS installer tomorrow after rebuild without LFN stuff?

**Comment by volkertb** [comment]
I'll set a reminder to try it and I'll share my findings with you.

Thank you for looking into this so quickly!

**Comment by jmalak** [comment]
I test it on VirtualBox with some FreeDOS image and it is terible slow.
I test it on VirtualBox with MS-DOS 7.1 image and it works as expected. It was installed during 3 minutes.

It looks like FreeDOS issue. Copy of installers from CD to hard drive take long time, it looks some FreeDOS general issue, not problem with OW-V2 installer.

**Comment by pchapin** [comment]
It might be a VirtualBox issue. I notice that applying updates to my Ubuntu Linux system inside VirtualBox is crazy slow... particularly when it writes a large number of files, such as when it is updating the kernel headers package.

I never looked into it, so I'm not sure what is really going on, but it sounds suspecially similar to what is described here.

**Comment by jmalak** [comment]
You are right that it could be due to some interaction between FreeDOS and VirtualBox.
I will try to check it on real hardware, I have one microPC with Celeron CPU that it could work on this.

**Comment by volkertb** [comment]
@jmalak Good idea about trying MS-DOS as well! :+1: The culprit indeed seems to lie with FreeDOS.

And it isn't just on VirtuaBox. QEMU (with KVM acceleration) has the exact same issue: installation is extremely slow when running on FreeDOS 1.3, and fast when running on MS-DOS 7.1. I also tested the installer in [DOSBox Staging](https://github.com/dosbox-staging/dosbox-staging), an optimized fork of DOSBox, and it installed rapidly in that environment as well.

I noticed you disabling LFN support in quite a few files, which makes it seem that you disabled it for the DOS version of Open Watcom entirely, not just the installer. If that is the case, wouldn't it be better to revert commit https://github.com/open-watcom/open-watcom-v2/commit/e8fcd294568943b05b5e966c8faf87bbed33811d, or at least the non-installer parts of it? After all, it doesn't appear to have been the cause of this slowdown after all.

Anyway, thank you for helping me troubleshoot this, and sorry I was premature in laying the blame on the Open Watcom v2 installer.

I'll create a ticket in the [FreeDOS Issue Tracker](https://gitlab.com/groups/FreeDOS/-/issues) about this finding.

**Comment by jmalak** [comment]
The remove LFN support from Installer is temporary because there is problem with LFN stuff in OW run-time library ( issue #1009 ). As soon as it will be fixed then I will return it back.

**Comment by volkertb** [comment]
Got it. This issue can then be closed. Thanks!

**Comment by volkertb** [comment]
For reference, and in case anyone finds this through a search engine, here is the FreeDOS issue I created for this: https://gitlab.com/FreeDOS/issue-reporting/-/issues/42
