### ISSUE TITLE
#pragma aux not preserving bp register with modify [ bp ]

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#1032]
I would like to call a legacy DOS function that modifies `bp`. However when I use modify `[ bp ]` the surrounding C code does not preserve this register. Here is a simplified example:

```C
#pragma aux muck_bp = "xor bp, bp" modify [ bp ]
int muck_bp();

void zero_vec(int vec[3]) {
  vec[0] = vec[1] = vec[2] = 0;
}

void main() {
  int vec[3]; 
  muck_bp();
  zero_vec(vec);
}
```

However when I run this program it crashes. The reason is `main()` allocates `int vec[3]` on the stack with `enter`, but does not preserve the `bp` register so when `leave` is executed the stack pointer is trashed. See the generated code:

```
Segment: _TEXT BYTE USE16 0000000E bytes
0000				main_:
0000  C8 06 00 00			enter		0x0006,0x00
0004  33 ED				xor		bp,bp
0006  8D 46 FA				lea		ax,-0x6[bp]
0009  E8 00 00				call		zero_vec_
000C  C9				leave
000D  C3				ret

Routine Size: 14 bytes,    Routine Base: _TEXT + 0000

No disassembly errors

Segment: _TEXT BYTE USE16 00000012 bytes
0000				zero_vec_:
0000  53				push		bx
0001  89 C3				mov		bx,ax
0003  C7 47 04 00 00			mov		word ptr 0x4[bx],0x0000
0008  8B 47 04				mov		ax,0x4[bx]
000B  89 47 02				mov		0x2[bx],ax
000E  89 07				mov		[bx],ax
0010  5B				pop		bx
0011  C3				ret

Routine Size: 18 bytes,    Routine Base: _TEXT + 0000

No disassembly errors
```

**Comment by rdos314** [comment]
C uses bp as the stack frame pointer, and so you cannot modify it or use it for something else.

**Comment by jmalak** [comment]
please see comment in issue #1033

**Comment by negge** [comment]
I found this comment in the code carried over from the OW 1.9 that builds the modify register mask https://github.com/open-watcom/open-watcom-v2/blob/master/bld/cg/intel/c/x86reg.c#L71

```C
HW_CTurnOff( tmp, HW_xBP ); /* should be able to call routine which modifies [E]BP */
```

**Comment by jmalak** [comment]
It is only possibility but if [E]BP is not available due to CG usage you cannot use it.
It is not simple to know if CG will use it or not. 
All other register has no such problem because CG can use any other register or put data into memory(stack), but [E]BP registr is globaly unique and CG has higher priority then #pragma aux.

**Comment by jmalak** [comment]
what you refere is code for __asm block code which can access data on parent stack or not.
