### ISSUE TITLE
No builtin way to emit an XCHG instruction when swapping two variables.

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#1034]
I am trying to reduce register pressure in a function. There is a place where I want to swap variables if one is less than the other. Here is a simplified example:

swap.c
```C
void thing(int a, int b);

#define SWAP(a, b, t) \
  do { \
    t _tmp; \
    _tmp = (a); \
    (a) = (b); \
    (b) = _tmp; \
  } \
  while (0)

void swap(int a, int b) {
  if (a < b) SWAP(a, b, int);
  thing(a, b);
}
```

Compiling and disassembling:

```
Segment: _TEXT BYTE USE16 00000010 bytes
0000				swap_:
0000  53				push		bx
0001  39 D0				cmp		ax,dx
0003  7D 06				jge		L$1
0005  89 C3				mov		bx,ax
0007  89 D0				mov		ax,dx
0009  89 DA				mov		dx,bx
000B				L$1:
000B  E8 00 00				call		thing_
000E  5B				pop		bx
000F  C3				ret

Routine Size: 16 bytes,    Routine Base: _TEXT + 0000
```

I could not find a WATCOM builtin() way to hint to the compiler that i would like these two variables exchanged with an XCHG instruction. Is there something that exists, or can this be added?

The code I would like to see is:

```
Segment: _TEXT BYTE USE16 0000000C bytes
0000				swap_:
0000  39 D0				cmp		ax,dx
0002  7D 01				jge		L$1
0004  92				xchg		ax,dx
0005				L$1:
0005  E9 00 00				jmp		thing_

Routine Size: 8 bytes,    Routine Base: _TEXT + 0000
```

Which does not modify `BX` and is only 8 bytes in size.

**Comment by jmalak** [comment]
the problem looks simple but it is not.
The title should be change to swaping registers not variables, because variables can be in memory and then it is more complex encoding. this issue is similar to function div(a,b).
you need to return two values from single function therefore you can only do this by using structure as return value.
look on div function implementation to help you. it could looks like:

typedef struct {
     int    a;
    int    b;
} two_num;
```
extern two_num swap_two_num( two_num x );
or
extern two_num swap_two_num( int a, int b );

#pragma aux swap_two_num = \
    "xchg ax,dx" \
    parm [ax dx] value [ax dx]
```

**Comment by jmalak** [comment]
I modify your sample code to

```
typedef struct {
    int a;
    int b;
} two_num;

void thing(int a, int b);

extern two_num swap_two_num( int a, int b );
#pragma aux swap_two_num = \
    "cmp ax,dx" \
    "jge L1" \
    "xchg ax,dx" \
"L1:" \
    parm [ax] [dx] value [ax dx]

void swap(int a, int b) {
  two_num t;
  t = swap_two_num(a, b);
  thing(t.a, t.b);
}
```

disasembled code

```
.387
                PUBLIC  swap_
                EXTRN   thing_:BYTE
                EXTRN   _small_code_:BYTE
DGROUP          GROUP   CONST,CONST2,_DATA
_TEXT           SEGMENT BYTE PUBLIC USE16 'CODE'
                ASSUME CS:_TEXT, DS:DGROUP, SS:DGROUP
swap_:
        cmp             ax,dx
        jge             L$1
        xchg            ax,dx
L$1:
        jmp             near ptr thing_
_TEXT           ENDS
CONST           SEGMENT WORD PUBLIC USE16 'DATA'
CONST           ENDS
CONST2          SEGMENT WORD PUBLIC USE16 'DATA'
CONST2          ENDS
_DATA           SEGMENT WORD PUBLIC USE16 'DATA'
_DATA           ENDS
                END
```

**Comment by negge** [comment]
Hi Jiri,

Yes, I am able to do something similar in this example and write my own inline assembly to manually do the compare and exchange. However this only works because I know what registers the variables are in due to them being passed into the `swap(int a, int b)` function.

In general, a SWAP() operation can be done anywhere in the program, with or without a conditional surrounding it, and may involve any registers. The whole idea of having a _builtin way to indicate this to the C compiler, is to hint that may be able to use an XCHG instruction and does not need to use an extra register. If I have to fix and name the registers in my own helper function, e.g.

```C
void my_swap(int a, int b);
#pragma aux my_swap parm [cx] [dx] modify [cx] [dx] = "xchg cx, dx"
```

then this is even more restrictive and may actually require *two* additional registers to complete the operation (instead of one fewer).

The goal is to help reduce register pressure on the allocator.

**Comment by jmalak** [comment]
The reason to not use xchg instruction is simple such code can not be simply optimized on low level.
I am not sure but I thing xchg instruction is not pairing therefore it has performance penalty in wait state even if it looks that such code is better.
Try other compilers how encode such code. I thing it is not so bad what is generated by OW code generator.
