### ISSUE TITLE
Cannot pass parameters using BP register.

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#1035]
It is not possible to pass parameters using the BP register to legacy API's. Here is a simplified example:

test.c
```C
#pragma aux test parm [bp] value [ax]
int test(int a) {
  return a + 1;
}

#pragma aux main modify [ax bx cx dx si di bp]
int main() {
  return test(1);
}
```

Compiling I get the following compiler error:

```
$ wcc -s test.c
test.c: 10 lines, 0 warnings, 0 errors
test.c(10): Error! E1122: Illegal register modified by 'test' #pragma
test.c(10): Error! E1122: Illegal register modified by 'test' #pragma
Code size: 9
```

Modifying the example to call the legacy API through an inline assembly proxy definition does not work either, but gives a different error:

test2.c
```C
#pragma aux test parm [bp] value [ax]
int test(int a) {
  return a + 1;
}

int test_proxy(int a);
#pragma aux test_proxy parm [bp] value [ax] = "call test"

#pragma aux main modify [ax bx cx dx si di bp]
int main() {
  return test_proxy(1);
}
```

Compiling gives this new program gives a different error about trying to emit an invalid instruction.

```
wcc -s test2.c
test2.c(7): Error! E1156: Assembler error: 'Invalid instruction operands'
test2.c: 13 lines, 0 warnings, 1 errors
```

It seems like you should be able to tell WATCOM to pass values in BP and have it preserve the register if necessary. The legacy API is then responsible for allocating local variables on the stack and unwinding before returning to the caller.

**Comment by jmalak** [comment]
It is C compiler and use C rules for calling convention of C functions which is described in OW documentation.
BP register is privileged for Code generator that you can not allocate it as you want !!!!!
If you do wrong way or in wrong situation some errors are reported and some not therefore you can not expect that Code Generator behave as you thing.  !!!!!! don't use BP register !!!!! I will change compilers to don't enable use BP register for #pragma aux explicitly then no such discusion will never end.
