### ISSUE TITLE
OW prints warnings with "-w" for owcc (csmith 00011)

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1039]
The attached testfile has 15 warnings using owcc with "-w".
That is forwarded to wcc386 as "-w0" 

00011.c(203): Warning! W1178: Type qualifier mismatch
00011.c(227): Warning! W1178: Type qualifier mismatch
00011.c(259): Warning! W1178: Type qualifier mismatch
00011.c(443): Warning! W1178: Type qualifier mismatch
00011.c(490): Warning! W1178: Type qualifier mismatch
00011.c(505): Warning! W1180: Sign specifier mismatch
00011.c(523): Warning! W1178: Type qualifier mismatch
00011.c(540): Warning! W1180: Sign specifier mismatch
00011.c(590): Warning! W1178: Type qualifier mismatch
00011.c(591): Warning! W1180: Sign specifier mismatch
00011.c(594): Warning! W1181: Parameter 2, sign specifier mismatch
00011.c(802): Warning! W1180: Sign specifier mismatch
00011.c(802): Warning! W1180: Sign specifier mismatch
00011.c(821): Warning! W1181: Parameter 1, sign specifier mismatch
00011.c(843): Warning! W1180: Sign specifier mismatch

More details to the 15 warnings in the attached log file: [00011_warnings_with_w.txt](https://github.com/open-watcom/open-watcom-v2/files/10530880/00011_warnings_with_w.txt)

(owcc with "-Wlevel=1" creates 65 failures, so "-w" supressed 50 warnings)

The full source file is also attached (00011.c).
Command line used to compile (needs current csmith installed):
owcc -std=c99 -O0 -g -w -I/usr/include/csmith -v -Wstop-after-errors=999 -fnonconst-initializers 00011.c -o 00011_tst

[00011.c.txt](https://github.com/open-watcom/open-watcom-v2/files/10530796/00011.c.txt)

**Comment by jmalak** [comment]
Please check it with latest CI build. 
It should be fixed by commit d56dd618ae6d754aa2e118c0bce3633afc00d51f .

**Comment by winspool** [comment]
Oh, thanks. I will try tomorrow.

**Comment by winspool** [comment]
Yes, current OW is fixed.
Thanks
