### ISSUE TITLE
Error! E1205: binary operator '&&' missing left operand

### ISSUE THREAD

**Issue by MarekKnapek** [open-watcom/open-watcom-v2#1046]
Steps to reproduce:
 - Download and install (full) latest version (2023-02-06).
 - Run IDE.
 - Menu -> File -> New Project -> Select some file (such as test.wpj) -> Open.
 - Keep target type as is (WinNT/Win95, console).
 - Press insert key to insert new source file, select test.c, close.
 - Press F4 key to build the project.

Expected behavior:
 - Compilation & Linking success, binary produced.
 - Watcom 11 downloaded from winworldpc website behaves as expected.
 - Visual Studio 2022 also behaves as expected.
 - GCC for Windows also behaves as expected.

Actual behavior:
 - Error! E1205: binary operator '&&' missing left operand.

test.c
```c
#if defined __has_builtin && __has_builtin(__builtin_unreachable)
#define my_assert(x) if(!(x)) __builtin_unreachable(); ((void)(0))
#endif

int main()
{
	return 0;
}
```

**Comment by jmalak** [comment]
Thank you for your bug report.

**Comment by jmalak** [comment]
I think it is not supported by C standard that behaviour of OW compiler is correct.
The argument of #if must be preprocessor constant expression, but construct "defined __has_builtin && __has_builtin(__builtin_unreachable)" isn't.

I am not sure but probably it is some gcc extension.

Visual studio 2022 reported
C:\dev\test\preproc>cl -c t1.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31937 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

t1.c
t1.c(1): warning C4067: unexpected tokens following preprocessor directive - expected a newline

**Comment by MarekKnapek** [comment]
OK, sorry, this was my mistake. This code was part of larger if-elif-elif-elif-endif block, I simplified it for bug report and not tested it thoroughly after simplification. According to GCC docs, the recommended usage is quite different than my original usage. https://gcc.gnu.org/onlinedocs/gcc-10.1.0/cpp/_005f_005fhas_005fbuiltin.html Again, I'm sorry for bothering you by a bad bug report.

**Comment by jmalak** [comment]
No problem. I close this issue.
