### ISSUE TITLE
unsigned long long addressing issues in debugger

### ISSUE THREAD

**Issue by DavidOgilvie** [open-watcom/open-watcom-v2#1051]
I am having issues with 64-bit bit setting in OW C.

Here is a screenshot of a debugger page which is showing incorrect addressing of a 64-bit array (shouldbe)... the initial address seems to be off by a word.  I am also not able to change the type for the last element in the array.

![image](https://user-images.githubusercontent.com/50533075/220109012-23b22459-fffc-4ae9-a03e-4def26312f45.png)

The test program also shows that doing << of up to 31 works, but from 32 to 63, the bit is set in the wrong double-word.  If I step through the next line (the fprintf), the program crashes.  Not sure why.

OS: Windows 10 64-bit 22H2
CPU: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz   2.71 GHz
Compile command line:
bwcc -zq -D_BLDVER=1300 -D_CYEAR=2023 -j-we -od -d2 -x-wpx -xx -zam -fo=guilog.obj -fpi -ml -bt=windows   -fh -zu -zw -zW -wx-wce=310-za99 -D_ENABLE_AUTODEPEND  -DSTRICT -DGUI_IS_GUI       -I. -I"../h" -I"../../h" -I"../../../../bld/hlpview/h" -I"../../../../bld/commonui/wini86" -I"../../../../bld/commonui/h" -I"../../../../bld/commonui/res" -I"../../../../bld/wpi/h"  -I"../../../../bld/wres/h"  -I"../../../../bld/hdr/dos/h" -I"../../../../bld/w16api/wini86/h" -I"../../../../bld/trmem" -I"../../../../bld/watcom/h" ..\c\guilog.c

Using open-watcom-2_0-c-win-x64 from Sunday Feb 19th.

Thanks in advance for looking into this.

**Comment by DavidOgilvie** [comment]
Here's a text version of the subroutine in question:

void ullbittest( void )
{
    unsigned long long  bitfield= 0ULL;
    int                 shifted= 13;
    int                 i;
    unsigned long long  shouldbe[4]= {
        0x0000000000002000,
        0x0000000020000000,
        0x0000200000000000,
        0x2000000000000000
    };
    FILE                *fp = NULL ;                // File pointer to filename

    fp= fopen( "ullbittest.log", "w" );
    if( fp != NULL ) {
        fprintf( fp, "64 bit setting test\n\n" );
        fflush( fp );
        for( i = 0; i < 4; i++ ) {
            bitfield|= ( 1ULL << shifted );
            fprintf( fp,
                     "1 << %d bitfield= 0x%016x, shouldbe[%d]= 0x%016x - %s\n",
                     shifted,
                     bitfield,
                     i,
                     shouldbe[i],
                     (( bitfield & shouldbe[ i ] ) != 0 )? "OK" : "failed!" );
            fflush( fp );
            bitfield= 0ULL;
            shifted+= 16;
        }
        fclose( fpDPTR );
    }
}

**Comment by jmalak** [comment]
I checked and it looks like bug in your code.
You use incorrect format specifier for 64-bit numbers output.
if you replace "0x%016x" by "0x%016llx" then it works as expected.

64 bit setting test

1 << 13 bitfield= 0x0000000000002000, shouldbe[0]= 0x0000000000002000 - OK
1 << 29 bitfield= 0x0000000020000000, shouldbe[1]= 0x0000000020000000 - OK
1 << 45 bitfield= 0x0000200000000000, shouldbe[2]= 0x0000200000000000 - OK
1 << 61 bitfield= 0x2000000000000000, shouldbe[3]= 0x2000000000000000 - OK
