### ISSUE TITLE
Invalid DIP file

### ISSUE THREAD

**Issue by JLCRL** [open-watcom/open-watcom-v2#1065]
open-watcom-v2 with installer on win10 64bits
on DosBox last version 0.74-3
\binw\wd failed
error:
Debugging Information processor 'dwarf' load failed: Invalid DIP file

**Comment by jmalak** [comment]
It is not supported on DOSBOX only on MS DOS.

**Comment by JLCRL** [comment]
Sorry I have installed an old version 2.0.2334 (not from github).
With the last one (exe installer from github) 2.0.2560 it works
