### ISSUE TITLE
binl64 folder is significantly bigger than those of other architectures

### ISSUE THREAD

**Issue by madebr** [open-watcom/open-watcom-v2#1070]
Using the latest snapshot (2023-04-11), the linux 64-bit binaries are more then twice as large as the windows binaries.
```
$ du -m -d1 | sort -n -r | head -9
492     .
156     ./binl64
72      ./binw
55      ./binnt
43      ./binp
39      ./lib386
37      ./binnt64
24      ./lib286
23      ./binl
```

Comparing a single binary, e.g. `wipfc`, the difference is bigger:
- `binl/wipfc`: 1,007 KB
- `binl64/wipfc`: 18,880 KB

**Comment by jmalak** [comment]
Take into account that all OW Linux applications are statically linked to C run-time library.
32-bit version use OW CRTL but 64-bit version use GNU CRTL.
Anyway I will check if some wrong option is used or not.

**Comment by pts** [comment]
FYI musl could be used instead of glibc to reduce program file size of `binl64/*`.

**Comment by winspool** [comment]
> FYI [musl](https://www.musl-libc.org/) could be used instead of glibc to make huge reductions in program file size of `binl64/*`.
> 
> An easy way to use _musl_ is using the `zig cc` tool from [Zig](https://ziglang.org/download/), and then running:
> 
> ```
> $ zig cc -target x86_64-linux-musl -W -Wall -s -O2 -o hello hello.c
> ```

For the case, that "zig" is unknown to the reader:

zig is a complete toolchain for the zig language, 
(compiler, linker, build tool, runtime library)
but zig is also a c and c++ cross toolchain based on clang and llvm.

To make cross compilation easy, zig comes with the runtime libraries
(3 tbd files for darwin [11, 12 and 13],
plus source files for musl, glibc, mingw and wasi).
zig compiles and cache the compiled runtime for every used target. 

That's a single 43MB tarball for all targets compared to 
the ~300MB (clang + llvm + a runtime library) for one target 


OpenWatcom is ok for classic systems / OS:
A recent ci tarball is 121 MB, 
includes additional language support for Fortran
includes additional system support for DOS, Win16, Netware and OS/2,
but is otherwise far behind.

**Comment by winspool** [comment]
One cause are the verbose debug informations in binl64 created by gcc.

For binl, most executables have an additional sym file,
but for binl64, the executable include always the verbose debug infos.
```
strip bin*/*
```
Afterwards, directory sizes is better:

> du -m -d1 | sort -n -r | head -8
267	.
51	./binl64
39	./lib386
27	./binnt
25	./binw
25	./binp
24	./lib286
18	./h

but remember, that executables build by ow are static linked,
while the executables in binl64 are dynamic linked,
so the size of the files in binl64 should still be far smaller.

**Comment by winspool** [comment]
## Some options to reduce the file size of the programs in binl64:
Examples might use `objcopy` (from `binutils`) to do some of the work.

### Compress the debug section
   `gcc` supports the commandline option `-gz` to do that during compilation.
    (I did not tested that)
   I used `objcopy` after linking
   ```
   objcopy  --compress-debug-sections=zlib  wcc386
   ```
  More compression options are available in `objcopy`

  More Infos about `gcc` debugging options: 
  https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html


### Keep the debug infos in a separate file
  When using 'gdb' as debugger, the two files need to be conected.
  Either with a `debuglink` or with a `build-id`.
  Default extension is `.debug`, but other examples use `.dbg`.

 `gcc` supports the commandline option `-gsplit-dwarf` to create separate debug files during compilation. 
  I used `objcopy` (and `strip`) after linking:
  ```
  objcopy  --only-keep-debug  wcc386  wcc386.debug
  objcopy  --add-gnu-debuglink=wcc386.debug  wcc386
  strip  -g  wcc386
  # strip can be replaced with objcopy:
  # objcopy  --strip-debug  wcc386
  ``` 

  Example filesize results for wcc386:
  ```
  original:
  6289576  wcc386

  debug infos compressed (zlib) and in a separate file:
  1967416  wcc386
  2100336  wcc386.debug
  ```

  Using the commandline options for `gcc`seems to be easy,
  but the OpenWatcom build system must be updated to copy (and cleanup) the symbol files.

  Mode Infos: 
  https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html

  Another Page with examples:
  https://github.com/GabrielMajeri/separate-symbols

  Infos with examples, how to deal with large symbol files:
https://interrupt.memfault.com/blog/dealing-with-large-symbol-files#compress-debug-info-when-linking

**Comment by winspool** [comment]
I tried to compile with zig, but bootstrap fails in wipfc:
```
In file included from ../cpp/main.cpp:37:
In file included from ../cpp/compiler.hpp:46:
../cpp/ptrops.hpp:35:26: error: unknown template name 'binary_function'
struct ptrEqualTo : std::binary_function< Type, Type, bool > {
                         ^
../cpp/ptrops.hpp:41:23: error: unknown template name 'binary_function'
struct ptrLess : std::binary_function< Type, Type, bool > {
                      ^
../cpp/ptrops.hpp:47:26: error: unknown template name 'binary_function'
struct ptrGreater : std::binary_function< Type, Type, bool > {
                         ^
In file included from ../cpp/main.cpp:37:
../cpp/compiler.hpp:103:10: error: no template named 'auto_ptr' in namespace 'std'
    std::auto_ptr< Lexer >  _lexer;
    ~~~~~^
4 errors generated.
make: *** [Makefile:457: main.o] Error 1
```

Since `auto_ptr` is deprecated, but used a lot in OpenWatcom, i stopped here.


---
Size test for bwcc386 build with zig (musl / static):
```
$ file  bwcc386 
bwcc386: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
$ size bwcc386 
   text	   data	    bss	    dec	    hex	filename
 915932	  43592	  70176	1029700	  fb644	bwcc386
```

Old Size  for bwcc386 build with gcc (glibc / dynamic):
```
$ file  bwcc386 
bwcc386: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=5e321cf197cf9e68ff651c53ba9bdccdbb48f826, for GNU/Linux 3.2.0, with debug_info, not stripped

$ size bwcc386 
   text	   data	    bss	    dec	    hex	filename
 884789	  46944	  66608	 998341	  f3bc5	bwcc386
```

The Exception Handler sections for x86_64 are together ca. 155k, but required by the ABI

**Comment by jmalak** [comment]
I aply build make files changes which should improve situation with distributed binl64 directory by externalize debug info to separate file.
It should also reducing the size of debug information files (.sym) in OW build snapshot.
