### ISSUE TITLE
misleading documentation in readme.txt about setting the INCLUDE variable

### ISSUE THREAD

**Issue by pts** [open-watcom/open-watcom-v2#1071]
The *readme.txt* in the downloaded OpenWatcom binaries (and also the corresponding [readme.sp](https://github.com/open-watcom/open-watcom-v2/blob/047386398d3b538c8ba9792714e6143b1f44f0ca/bld/docstxt/readme.sp) source file) is misleading about how the *INCLUDE* variable should be set. It doesn't clarify the distinction between host and target.

For example, if I'm running the *owcc* tool on Linux, I should set *WATCOM* and *PATH* according to the Linux-specific instructions. So far so good. But if I'm running `owcc -bwin32` on Linux to target Win32, I should set *INCLUDE* according to the *Win32 BAT file* instructions, and change `;` to `:`. This is not obvious at all for new users! **How is a new user supposed to know** that *WATCOM* is host-specific, and *INCLUDE* is target-specific, and sometimes they have to have change `;` to `:` (and sometimes back) in *INCLUDE*?

The incorrect setting of *INCLUDE* because of the lack of documentation and can lead to subtle, expensive-to-diagnose bugs such as the Segmentation fault in https://github.com/open-watcom/open-watcom-v2/issues/1053.

My quick-fix proposal P1 to fix this are the following:

* Change the text

  > INCLUDE - points to directories containing header files used by the C/C++ compilers

  to

  > INCLUDE - points to directories containing the target-specific header files used by the C/C++ compilers. If you are running the compilers on a Linux host, directories should be separated by colon (:), otherwise by semicolon (;). See target-specific INCLUDE values below. Don't forget to change colon to semicolon or back.

  Also, add RDOS somewhere:

  > If you are targeting RDOS, `set INCLUDE=%WATCOM%\RH`.

  Also, add this to *h/stdio.h* etc.:

  ```
  #ifdef __LINUX__
  #error This header doesn't work for Linux, fix your INCLUDE, it should point to lh instead of h.
  #endif
  #ifdef __RDOS__
  #error This header doesn't work for DOS, fix your INCLUDE, int should point to rh instead of h.
  #endif
  ```

My proposal P2 is more convenient and less error-prone for the user, especially for new users:

* The tools *owcc*, *wcl*, *wcc*, *wcc386*, *wpp*, *wpp386* should autodetect the correct value of *INCLUDE*. If *INCLUDE* is missing or empty, then these tools should provide a default: if the command-line flag `-bt=...` or `-bcl=...` or `-b...` is specified, use the target-specific default list, otherwise use the host-specific default list.
* Other tools already ignore *INCLUDE*, no changes are needed.
* *readme.txt* should be updated:
  > INCLUDE - points to directories containing the target-specific header files used by the C/C++ compilers; note that the compilers can autodetect this variable, so just set it to empty, and stop reading. If you are running the compilers on a Linux host, directories should be separated by colon (:), otherwise by semicolon (;). See target-specific INCLUDE values below. Don't forget to change colon to semicolon or back.

**Comment by jmalak** [comment]
You are right it is not explicitly expressed.
But all configuration is default for host.
Please do PR with appropriate change.
Anyway here is detailed description of using OW compilers.
[OW usage](https://github.com/open-watcom/open-watcom-v2/wiki/OW-tools-usage-Overview)

**Comment by rdos314** [comment]
The RDOS target is a bit special since it's half a build-target too. The build process builds the debugger for RDOS host, but not of the compilers or linker. Although I think it is possible to build those too, but the make tool quite likely is not working so it's not possible to build Watcom on a RDOS host.

**Comment by jmalak** [comment]
I added only info for RDOS target setup (cross-compilation), not setup for RDOS host.

**Comment by rdos314** [comment]
This is only an issue when working with makefiles directly. All my projects use the IDE to create projects, and when target RDOS is selected, the default include path suggested is correct.

**Comment by pts** [comment]
FYI I don't use an IDE when writing source code to be compiled by OpenWatcom. I run the OpenWatcom compilers from the command line (with environment variables set up manually) or from a Makefile.
