### ISSUE TITLE
Changes broke OW2  in June 1 2020 release when compiling against Windows GDI DLLs under Fortran

### ISSUE THREAD

**Issue by watfor-mike** [open-watcom/open-watcom-v2#1074]
I have been working several projects and just picked up an older one that was dormant.  The project was last compiled with November 1 2020 version.  I tried to compile the files on the April 2023 release and could not get it to link properly.  typical error is thrown by the linker not finding the symbols such as _GetMessageA.

The Fortran compiler/linker works fine on other Fortran projects that do not link to windows GDI DLLs.

I re-installed the 11/1/2020 release with the same files on the current machine linked correctly.  I then reinstalled the successive releases on the current machine until it broke again.  5/1/2020 linked properly, but 6/1/2020 fails to link.   The only difference on the current machine is the installed OW2 release.  I've prepared the simplest program that illustrates the issue.    All of the files produced are included in the zip file.
[Simple-NT-GUI.zip](https://github.com/open-watcom/open-watcom-v2/files/11368644/Simple-NT-GUI.zip)

Copying the old wlink.exe into the new install did not correct the issue, also the wlib.exe did not change the results.  All of the linker and compiler flags are the same as are the mk1 files.

Any insights would be appreciated.

**Comment by jmalak** [comment]
Thanks for your bug report.
It is related to broken Fortran compiler for Windows __stdcall calling convention.
Compiler upper-case Windows symbols.
I will fix it ASAP

**Comment by watfor-mike** [comment]
Thank you for the quick response

**Comment by jmalak** [comment]
it is fixed now by commit 8453674b2ba5105bc387724910ac3a6a1fd92064

**Comment by watfor-mike** [comment]
Thank you very much!

I'll test over the next week.  I assume it will work perfectly and I'll close now and open a new if needed.

**Comment by watfor-mike** [comment]
Tested the CI build.  Worked fine.  Thanks again for the quick fix.

**Comment by jmalak** [comment]
Thank you for your testing
