### ISSUE TITLE
the current build located in https://github.com/open-watcom/open-watcom-v2/releases/tag/Current-build is near 1 month old

### ISSUE THREAD

**Issue by gfernval** [open-watcom/open-watcom-v2#1076]
Why is not upgraded?

**Comment by jmalak** [comment]
Microsoft disable our build system on Azure Pipelines after a few years without any note.
Now I am in process of build system migration to GitHub Actions.

**Comment by jmalak** [comment]
I finished migration to GitHub Actions workflow and build servers
