### ISSUE TITLE
Cannot install on WSL for windows subsystems

### ISSUE THREAD

**Issue by jwoff78** [open-watcom/open-watcom-v2#1081]
I've been attempting to install on WSL, the installing has 'C' cancel and 'A' I Agree on the installing, all those buttons do is run an endless scroll-down loop for the installer

**Comment by jmalak** [comment]
Please describe in more details you environment.
I don't know how WSL is POSIX compliant etc.
Anyway it is not supported installation, we don't test it.
It is little useless, because you can do native installation on host and cross-compile to any target.
