### ISSUE TITLE
clbr20.dll mt7r20.dll plbr20.dll - system runtime library file does not exist

### ISSUE THREAD

**Issue by SamuelMarks** [open-watcom/open-watcom-v2#1083]
After running:
```batch
[path]\WATCOM\owsetenv.bat
cmake -G "Watcom WMake" -D CMAKE_SYSTEM_NAME=DOS -D CMAKE_SYSTEM_PROCESSOR=I86 ..
```

However it seemed to work:
```
cmake --build .
Open Watcom Make Version 2.0 beta Apr 11 2023 01:35:59 (64-bit)
[… omitted for brevity]
[100%] Built target test_c89stringutils
```

So not sure if the warning is required. Anyway I still need to setup a VM to confirm this actually runs in DOS! - But looking good…

**Comment by jmalak** [comment]
It looks like OW installation issue, but as you note it has not impact on resulting executable.
OW must be installed by default for host system only to work properly with CMake.
If you use CMake on Windows you need to install OW for Windows host and also install support for all targets which you will cross-compile.
With CMake on Linux you need to install OW for Linux host and also install support for all targets which you will cross-compile.
It looks like you are on Windows but OW is not installed correctly for Windows or you have not setup it for Windows target.
CMake handle configuration of OW for various target itself, but you need standard OW installationfor CMake host.
