### ISSUE TITLE
Linux/gcc : /usr/bin/ld: cannot find -lc

### ISSUE THREAD

**Issue by hadjiprocopis** [open-watcom/open-watcom-v2#1091]
Hi there,
I am trying to compile the latest open-watcom-v2's pull (as of today, 22-05-2023) from github but I have encountered a weird error when executing ```clean.sh; build.sh```

```
== 11:54:37 /home/xxx/Downloads/open-watcom-v2/bld/causeway/cwc/linux386 ==
bld_cl ./mkcode.exe
bld_as copystub.obj
bld_link copystub.tmp
./mkcode.exe copystub.gh
bld_as decstub.obj
bld_link decstub.tmp
../../asm/decstub.asm(268): Note! N293: Extending jump
../../asm/decstub.asm(285): Note! N293: Extending jump
../../asm/decstub.asm(268): Note! N293: Extending jump
../../asm/decstub.asm(285): Note! N293: Extending jump
./mkcode.exe decstub.gh
cc cwc.obj
cl cwc.exe
== 11:54:37 /home/xxx/Downloads/open-watcom-v2/bld/causeway/cwc/linuxx64 ==
bld_cl ./mkcode.exe
bld_as copystub.obj
bld_link copystub.tmp
./mkcode.exe copystub.gh
bld_as decstub.obj
bld_link decstub.tmp
../../asm/decstub.asm(268): Note! N293: Extending jump
../../asm/decstub.asm(285): Note! N293: Extending jump
../../asm/decstub.asm(268): Note! N293: Extending jump
../../asm/decstub.asm(285): Note! N293: Extending jump
./mkcode.exe decstub.gh
cc cwc.obj
cl cwc.exe
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Error(E42): Last command making (cwc.exe) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed
```
I  have not managed to debug this because I have no idea which makefile is executed.

Strangely, this exact problem appears when compiling an older version of open-watcom-v2 (pulled on 11--01-2020). And that was compiling OK at the time of the pull. So it must be something in my system which has been updated several times since.

If you have some idea where this problem may be, please tell me to debug it, else please tell me if there is a way to produce a more verbose output from ```build.sh``` to know exactly which makefile is run and where.

My system is ```Linux fedora 6.2.14-100.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC``` (and back in 2020, I think I had fedora33 or 34). GCC version is ```gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)``` and ```ld``` is ```GNU ld version 2.37-37.fc36```.

Thank you (and thank you lots for providing open-watcom!!! I use it to crosscompile from Linux to MSDOS),

bw, a.

**Comment by hadjiprocopis** [comment]
Thank you @jmalak for the perfect diagnosis (not installed gcc static C run-time-library).

I have installed said libraries with: ```dnf install glibc-static libstdc++-static```  (for Fedora Linux) and have now got a successful compilation.

I have one question and one suggestion:

**Question**: How do I install the binaries into /usr/local? (Right now the current OW dir contains a lot of object files etc. and it has a huge size)

**Suggestion**: you told me that there are pre-built versions available. But the file I donwloaded does not have the ZIP extension, https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/open-watcom-2_0-c-linux-x64 which can confuse people on how to deflate. Secondly, the zip file was created without a root, container dir, e.g. ```open-watcom-binaries/...``` and that dump a lot of files in my current dir... (excuse my nitpicking, I am only trying to make this as easy as possible for other users).

**Comment by jmalak** [comment]
You can use installer to install OW. By installer you can select where files are put.
what you are trying to use is installer which has no zip extension because it is executable even if you can UNZIP it because it is ZIP archive. These files are installers (executable) not archive.
There is archive ow-snapshot.tar.xz which you should use as tar archive to restore full OW distribution where you want.

**Comment by hadjiprocopis** [comment]
fine, thanks! I just assumed they were zip files without the extension because I unzipped them just fine (for my Linux). But thanks for the info.

Regarding installing the binaries after compiling from source, I have seen this document:

https://github.com/open-watcom/open-watcom-v2/wiki/Build

which says:

`You may want to run builder cprel from inside the bld directory after successfully building everything to copy the complete system to the release tree rel.`

But the only ```builder``` file I have (after successful compilation with ```clean.sh; build.sh```) is in ```build/binbuild/builder```. So, I tried (from root of open-watcom src dir):
```
cd bld; ../build/binbuild/builder cprel
```
with this result:
```
Could not open '/build/master.ctl': No such file or directory
```
But there exists a ```../build/master.ctl```
thank you

**Comment by hadjiprocopis** [comment]
OK, thanks. I was looking for a builder executable in ```bld``` dir, but I see that it is in ```binbuild``` which is added in the PATH. So, all well. Thank you.

**Comment by jmalak** [comment]
owsetent.sh script is created during installation by installer.
this file is not part of OW distribution.
In root of OW distribution is readme file where is described how you can configure/create such file manually or how you can integrate OW into some setup script for other purposes.
