### ISSUE TITLE
[Low-priority feature request] CWSDPMI support

### ISSUE THREAD

**Issue by cs127** [open-watcom/open-watcom-v2#1096]
I know this will take a lot of effort to implement, but I would like OW to have an option for compiling 32-bit DOS executables to use CWSDPMI instead of DOS/4G(W).

That said, if you think it's not worth the time and effort to implement this, that's totally fine! You can just close this issue if you want.

**Comment by jmalak** [comment]
What's the point of supporting CWSDPMI if OW has support for multiple DOS Extenders?
What is gain against DOS4GW or others supported by OW?

**Comment by cs127** [comment]
> What's the point of supporting CWSDPMI if OW has support for multiple DOS Extenders? What is gain against DOS4GW or others supported by OW?

DOS/4GW tends to be really unstable on my system, and generally I have had better luck with running programs that use CWSDPMI.

I'm aware that implementing CWSDPMI into OW takes a lot of time and effort, so this isn't really a high-priority feature request. I was just wondering if you ever will implement it.
As I said, if you think it's not worth your time, you can close the issue, that's totally fine.

**Comment by cs127** [comment]
I can't really do much to "correct my system". :(
But also, I didn't know OW supports more extenders, I'll give the other extenders a shot.

**Comment by jmalak** [comment]
OW supports DOS4GW, Causeway, Pharlap, DOS/32A, PMODE/W
