### ISSUE TITLE
[DOS] Text functions use incorrect text colour for characters 0x80-0xFF

### ISSUE THREAD

**Issue by cs127** [open-watcom/open-watcom-v2#1101]
`_outtext` and `_outmem` print characters in the upper half of the character set (0x80-0xFF) with a text colour that is one less than intended.

This affects both dark (0-7) and bright (8-15) colours, but only for the text, not the background.

Example code:
```c
#include <stddef.h>
#include <stdlib.h>

#include <conio.h>
#include <graph.h>


int main(int argc, char** argv) {

    char buf [256];
    size_t i;
    short clr = atoi(argv[1]);

    for (i = 0; i < 256; i++) buf[i] = i;

    _outtext("\n");
    _settextcolor(clr);
    _outmem(buf, 256); // characters 128-255 are printed with the incorrect colour
    _outtext("\n");

    return 0;

}
```

results:
![image](https://github.com/open-watcom/open-watcom-v2/assets/56088587/52818be4-4e2a-439b-9879-16f765330a07)

**Comment by jmalak** [comment]
Thanks you for your bug report.

**Comment by jmalak** [comment]
Please recheck with last OW build after rebuild.

**Comment by cs127** [comment]
It's fixed now, thanks!
