### ISSUE TITLE
macro __FILE__ /C++ : a literal __FILE__ is prefixed to the actual source filename

### ISSUE THREAD

**Issue by hadjiprocopis** [open-watcom/open-watcom-v2#1104]
Perhaps I am not using the ```__FILE__``` macro correctly?

Consider this sample C++ program:
```
/*
wpp -fo=main.obj -0 -ml -oh -ok -ot -s -oa -ei -ob -ol+ -wx -xs -oi+ main.cpp
wlink system DOS option stack=4096 option map option eliminate name main.exe file main.obj
*/
#include <stdio.h>
#include <iostream>
using namespace std;
int main(void){
  printf("LINE %d and file '" __FILE__ "' and bye\n", __LINE__);
  cout << "LINE '" << __LINE__ << "' in file " __FILE__ << " and bye" << endl;
  return 0;
}
```
Output has a literal ```__FILE__``` prepended to the actual source filename, so it works correctly except that extra string:
```
LINE 9 and file '__FILE__main.cpp' and bye
LINE 10 and file '__FILE__main.cpp' and bye
```

A similar C program behaves fine and it does not have the literal ```__FILE__``` in the output (just the actual source filename)
(I am just mentioning this behaviour, I can live without a fix :))

**Comment by jmalak** [comment]
Thank you for your bug report.

**Comment by jmalak** [comment]
It should be fixed in git repository and after rebuild it will be available in new build version.

**Comment by hadjiprocopis** [comment]
Great! I Thank you all for all the superb support. Plus, watcom is great too.
