### ISSUE TITLE
wcc

### ISSUE THREAD

**Issue by iojuedioe9rd** [open-watcom/open-watcom-v2#1107]
make[1]: /usr/bin/watcom/binl/wcc: Command not found

**Comment by Count-MHM** [comment]
Can you share your makefile and `$PATH`?
Also, can you describe how you installed Watcom?

**Comment by iojuedioe9rd** [comment]
I just reinstalled it and now it works

**Comment by iojuedioe9rd** [comment]
> Can you share your makefile and `$PATH`? Also, can you describe how you installed Watcom?

I just reinstalled it and now it works
