### ISSUE TITLE
Evaluate Profile-Guided Optimization (PGO)

### ISSUE THREAD

**Issue by zamazan4ik** [open-watcom/open-watcom-v2#1113]
Hi!

Recently I applied Profile-Guided Optimization to multiple projects (including compilers) and got a measurable performance improvement. The results are available [here](https://github.com/zamazan4ik/awesome-pgo/).

Since PGO helps with compilers improvements (e.g. Clang gets from PGO +20% compilation speed) I think PGO could be useful to Open Watcom project as well.

**Comment by zamazan4ik** [comment]
@jmalak Could you please explain, why did you close the issue?

**Comment by winspool** [comment]
I suggest to let this issue open as an enhancement request
to optionally enable this optimization, when building OpenWatcom with gcc/mingw or clang.


Supporting this optimization in OpenWatcom is far to heavy.
