### ISSUE TITLE
OW does not build on mips-linux

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1115]
With the recent portability commits, i tried to build OW on a different machine,
but that failed.

console output with OWVERBOSE=1 and BUILDER_OPT="-v"

================ 14:05:41 /home/..removed../bld/as =================
+++\<set PROJNAME=wasaxp>+++
+++\<set BINTOOL=0>+++
+++\<set PROJDIR=/home/..removed../bld/as/axp>+++
+++\<set LOGFNAME=build>+++
+++\<set LOGEXT=log>+++
+++\<set CPCMD=acopy>+++
+++\<set CCCMD=accopy>+++
+++\<set BLDRULE=>+++
+++\<set CMDEXT=>+++
+++\<set DYEXT=.so>+++
+++\<set BLDRULE=boot>+++
+++\<set LOGFNAME=boot>+++
+++\<echo **** Building the wasaxp bootstrap>+++
**** Building the wasaxp bootstrap
+++<cdsay "/home/..removed../bld/as/axp">+++
============== 14:05:41 /home/..removed../bld/as/axp ===============
+++\<mkdir binbuild>+++
+++\<cdsay binbuild>+++
========== 14:05:41 /home/..removed../bld/as/axp/binbuild ==========
+++\<wmake -h -f ../binmake bootstrap=1>+++
wcpp -D_BLDVER=1300 -D_CYEAR=2023 -zku8 -D__UNIX__ -D__LINUX__ -D__MIPS__ -DNDEBUG -DBOOTSTRAP -D__MIPS__ -Umips  -D__UNIX__ -D__FLAT__ -D__LINUX__ -DAS_ALPHA    -oasi_msg.tmp ../../../../bld/as/h/as.msg
Incorrect optionUsage: wcpp [options] input files
Error(E42): Last command making (asi_msg.grh) returned a bad status
Error(E02): Make execution terminated
non-zero return: 512
Build failed
builder bootstrap build error
Command exited with non-zero status 1

######################

$ gcc --version
gcc (Debian 4.9.2-10+deb8u1) 4.9.2

$ uname -a
Linux ..removed.. 4.1.4 #1 SMP PREEMPT Mon Aug 3 14:22:54 PDT 2015 mips64 GNU/Linux

**Comment by winspool** [comment]
When using BUILDER_OPT=" -v -i ",
similar failures are visible for all risc assembler in the OW tree:


============== 14:33:56 .../bld/as/axp ===============
+++<acopy binbuild/bwasaxp.exe ".../build/binbuild/bwasaxp">+++
Can not open '.../bld/as/axp/binbuild/bwasaxp.exe' for reading: No such file or directory

========== 14:33:56 .../bld/as/mps/binbuild ==========
+++<wmake -h -f ../binmake bootstrap=1>+++
mkdir lib
wcpp -D_BLDVER=1300 -D_CYEAR=2023 -zku8 -D__UNIX__ -D__LINUX__ -D__MIPS__ -DNDEBUG -DBOOTSTRAP -D__MIPS__ -Umips  -D__UNIX__ -D__FLAT__ -D__LINUX__ -DAS_MIPS    -oasi_msg.tmp ../../../../bld/as/h/as.msg
Incorrect optionUsage: wcpp [options] input files
Error(E42): Last command making (asi_msg.grh) returned a bad status
Error(E02): Make execution terminated
non-zero return: 512

============== 14:33:56 .../bld/as/mps ===============
+++<acopy binbuild/bwasmps.exe ".../build/binbuild/bwasmps">+++
Can not open '.../bld/as/mps/binbuild/bwasmps.exe' for reading: No such file or directory



========== 14:33:56 .../bld/as/ppc/binbuild ==========
+++<wmake -h -f ../binmake bootstrap=1>+++
mkdir lib
wcpp -D_BLDVER=1300 -D_CYEAR=2023 -zku8 -D__UNIX__ -D__LINUX__ -D__MIPS__ -DNDEBUG -DBOOTSTRAP -D__MIPS__ -Umips  -D__UNIX__ -D__FLAT__ -D__LINUX__ -DAS_PPC    -oasi_msg.tmp ../../../../bld/as/h/as.msg
Incorrect optionUsage: wcpp [options] input files
Error(E42): Last command making (asi_msg.grh) returned a bad status
Error(E02): Make execution terminated
non-zero return: 512
+++<set BINTOOL=build>+++
+++<set PROJPMAKE=>+++
+++<cdsay ".../bld/as/ppc">+++
============== 14:33:56 .../bld/as/ppc ===============
+++<acopy binbuild/bwasppc.exe ".../build/binbuild/bwasppc">+++
Can not open '.../bld/as/ppc/binbuild/bwasppc.exe' for reading: No such file or directory

**Comment by jmalak** [comment]
Linux for MIPS is not supported platform for OW build system.
