### ISSUE TITLE
OW does not build on ppc-linux

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1116]
**** Building the wpp bootstrap
=========== 14:57:31 /home/.../bld/plusplus/i86 ============
======= 14:57:31 /home/.../bld/plusplus/i86/binbuild =======
gcc -pipe -c -D_BLDVER=1300 -D_CYEAR=2023 -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses  -O -g  -o carve.obj  -DNDEBUG -DBOOTSTRAP -D__PPC__  -D__UNIX__ -D__FLAT__ -D__LINUX__ -DINCL_MSGTEXT -DIDE_PGM       -includecarvecpp.h -I. -I.. -I"../../h" -I"../../../../bld/cg/intel/i86/h" -I"../../../../bld/cg/intel/h" -I"../../../../bld/cg/h" -I"../../../../bld/wasm/h" -I"../../../../bld/cpp/h" -I"../../../../bld/dwarf/dw/h" -I"../../../../bld/cc/h" -I"../../../../bld/comp_cfg/h" -I"../../../../bld/fe_misc/h" -I"../../../../bld/brinfo/h"  -I"../../../../bld/trmem" -I"../../../../bld/watcom/h" ../../../../bld/fe_misc/c/carve.c
In file included from ../../h/carvecpp.h:41,
                 from <command-line>:
../../h/pcheader.h:119:2: error: #error missing host architecture check
  119 | #error missing host architecture check
      |  ^~~~~
Error(E42): Last command making (carve.obj) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 512
Build failed
builder bootstrap build error

There is a check for PowerPC with "_M_PPC". 
Where does this define comes from?

The host compiler has no architecture definitions starting with "_M_*" 
(that's the microsoft compiler style / OW style for architecture definitions)

gcc uses 
```
"__powerpc__" and "__PCC__"
``` 
In addition, OW build system uses a "-D__PPC__" as argument for the host compiler.
Extending the powerpc check "( _M_PPC )" in pcheader.h with
```" || defined( __PPC__ )"```
lets the bootstrap going further (up to the next error PR_XXX).
Is this an acceptable fix?

**Comment by jmalak** [comment]
Linux for PPC is not supported platform for OW build system.
