### ISSUE TITLE
_gcvt undefinded

### ISSUE THREAD

**Issue by MikeyG** [open-watcom/open-watcom-v2#1121]
I was compiling some old source that used _gcvt which results on OS/2 and WinXP as _gcvt being undefined using current snapshot.  Using the equivalent gcvt compiles as expected. Test code:

```
#include <stdio.h>
#include <stdlib.h>

void main() {

    char buffer[80];

    printf( "%s\n", _gcvt( -123.456789, 5, buffer ) );
    printf( "%s\n", _gcvt( 123.456789E+12, 5, buffer ) );
}
```

**Comment by jmalak** [comment]
Thank you for your bug report.

**Comment by jmalak** [comment]
It should be fixed in git repository, after OW rebuild it will be available.

**Comment by MikeyG** [comment]
Confirmed fixed - thanks
