### ISSUE TITLE
The OpenWatcom source can no longer compiled with modern C++ compiler

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1122]
I tried to compile OpenWatcom with `zig`, but bootstrap fails (in wipfc):

```
In file included from ../cpp/main.cpp:37:
In file included from ../cpp/compiler.hpp:46:
../cpp/ptrops.hpp:35:26: error: unknown template name 'binary_function'
struct ptrEqualTo : std::binary_function< Type, Type, bool > {
                         ^
../cpp/ptrops.hpp:41:23: error: unknown template name 'binary_function'
struct ptrLess : std::binary_function< Type, Type, bool > {
                      ^
../cpp/ptrops.hpp:47:26: error: unknown template name 'binary_function'
struct ptrGreater : std::binary_function< Type, Type, bool > {
                         ^
In file included from ../cpp/main.cpp:37:
../cpp/compiler.hpp:103:10: error: no template named 'auto_ptr' in namespace 'std'
    std::auto_ptr< Lexer >  _lexer;
    ~~~~~^
4 errors generated.
make: *** [Makefile:457: main.o] Error 1

```

* `std::binary_function` was deprecated in C++11 and removed in C++17
  Maybe `std::function` can work as a replacement.
  See also: cppreference 
  https://en.cppreference.com/w/cpp/utility/functional/binary_function

* `std::auto_ptr` was deprecated in C++11 and removed in C++17
  cppreference describes `std::unique_ptr` as replacement for some use cases.
  https://en.cppreference.com/w/cpp/memory/auto_ptr

---
When compiling OpenWatcom with `gcc`, I remember to also see many of `deprecated` warnings about `auto_ptr`.

I have no idea, when clang++/libc++ or g++/libstdc++ will drop these features,
but since `zig` is based on clang/llvm and known to be agressive 
to activate clang/llvm features (some sanitizer are activated by default)
or deactivate clang/llvm features, which are no longer in the standard,
it is possible, that clang will do it also in the near future.
Especially during the ongoing development of `libcxx / libc++`.
https://libcxx.llvm.org/

Issue created to made public, what i found out.

**Comment by jmalak** [comment]
I don't see any problem
Clang version 14
GCC version 11, 12
Do you think it is old?

**Comment by winspool** [comment]
> Standard build system is working without problem. It uses Clang version 14 and GCC version 11. On my development box I use Clang 14 and GCC 12 without problems.

My system has gcc 12 and clang 15
(which replaced clang 13 and clang 14 the prev. weekend)
clang 16.0.0 was released 17. March 2023 and clang 17 release is planed for 5. Sep.
Latest gcc release is 13.2

I did my zig tests with a zig 0.11 dev snapshot from 23. Mai (based on clang 16.0.1).
In the meantime, zig 0.11.0 was released (4.Aug.)
The zig snapshot downloaded today is based on clang 16.0.6

zig downloads are available for:
x86 (win, linux)
x86_64 and aarch64 (win, macos, linux)
armv7, riscv64, powerpc64le and powerpc (linux)


> If you use OW bulding system wrong way then don't expect it will work. Your problem is caused by your use, not by OW build system.

No. You should not blame me.
Instead you should thank me,
that i use my time and try something different with OpenWatcom
and make the issues in OpenWatcom public very early.

---
zig is known to be an "early adaptor" to use use more strict features
of clang/llvm by default.

You can't control, which of the available features a packager of a linux distro
or an integrator of a Windows compiler will use by default for a new compiler release.


The given example "auto_ptr" was deprecated in C++11 and removed since C++17.
As long, as you can force a compiler and the c++ runtime to use an older C++ standard,
"auto_ptr" might work or might break,
but forcing the compiler to the old C++98 mode disables a lot of newer optimizations.


Updating OpenWatcom to use "unique_ptr" or "shared_ptr" instead of "auto_ptr"
needs support for "unique_ptr" and "shared_ptr" in OpenWatcom first.


---
Another example from the upcoming clang 17 release note:
* The classes strstreambuf , istrstream, ostrstream, and strstream have been deprecated.
  They have been deprecated in the Standard since C++98, 
  but were never marked as deprecated in libc++.

( https://libcxx.llvm.org/ReleaseNotes/17.html )

Deprecated 25 years ago and still used a lot in OpenWatcom.

According to the clang/llvm release policy, deprecated features are removed after 2 releases, 
so starting with clang 19 in sep. 2024 or clang 20 in march 2025,
there are possible a lot more issues for building OpenWatcom.


I have no idea, when deprecated templates/classes 
will be removed in other compiler / c++ runtimes.

* The Intel Compiler is based on clang, but i don't know, which runtime they use.
* MSVC uses a licensed Drinkumware C/C++ runtime on windows
* The Embarcadero C++ builder (previous: Codegear / Borland) is based on clang 
  and uses a licensed Drinkumware C/C++ runtime on windows,
  but since "BorlandC" is not a supported toolchain for OpenWatcom, that's only an info.

**Comment by winspool** [comment]
Thanks Peter for your detailed answer.
Insider infos are very helpful for me,
since i don't know the OW source base and layout
not good enough yet.

> There actually is a `shared_ptr` implementation in OWSTL, but the person who contributed it didn't provide `unique_ptr`.

Oh, great.

> I feel like there is a deeper question here. If we use C++ 2011 constructs in Open Watcom's implementation, then we would need to limit ourselves to the C++ 2011 features that Open Watcom currently implements, which are very few. It would be cleaner to say that Open Watcom needs to be bootstrapped by a C++ 1998 compiler, at least for now.

How long can OW still be compiled with the prev. OW version?

Btw @jmalak what is your Roadmap / timeline 
for an OpenWatcom 2.0 release?

Or a 1.99 release for the current state?
A release would give OW some attention
[dream on] and maybe new developer [back to real mode].
( Reality check: The llvm discord has 10069 members. 1239 are online)

> 
> I hear you saying that gcc/clang are likely to drop support for C++ 1998 in the near future, making them unable to bootstrap Open Watcom. I find that a little surprising, but not unbelievable. Are you saying the newer compilers no longer honor the `-std=c++98` option?

Not in the source (i hope so), 
but you can't control,  how a packager configures
gcc/clang or a C / C++ runtime,
when building a new toolchain/runtime binary release.

I found the commit for gcc-12, where they added 
missing wanings about some of the features,
which are deprecated or remove from the standard.
In that commit, they stated, that they would let 
support for the old features in the source.

But when a packager configures the compiler to be
more modern, code for supporting old cruft is gone.
clang/llvm have the policy to drop deprecated features
after 2 releases.
I hope for OW, that this is only for the toolcain itself
and for experimental features, 
but not for core language/library features,
(Disclaimer: I don't know clang/llvm good enough)


As another example, ubsan is available a long time,
but the compiler user has to activate it.
How many projects do that?
So when gcc/clang is used as compiler,
undefined behavior bugs in the source are undetected.

zig on the other hand activates ubsan by default
and configures clang/llvm/musl/libstdc++
to leave out old cruft: 
When zig is used as c or c++ compiler for a project, compilation faild (old cruft used, like in OW)
or the compiled result crash (ubsan).


> Obviously, the ideal solution would be to move Open Watcom forward to, say, C++ 2011. However... who is going to do that? The C++ compiler and library hasn't moved in years, as far as I can tell. I wrote a fair chunk of the OWSTL back in the 2005-2010 time frame, but my life has shifted. I'd love to make Open Watcom a retirement project, but that's a few years away, and I have other projects in mind as well. In past years, Christof did a lot of great work inside the compiler adding many missing C++ 1998 features, but he has also moved on to other things.

In addition to my scripts for using csmith and yarpgen,
I also started https://github.com/winspool/stdtests
and I want to do test according the standard.
(latest free available draft).

I also have POSIX API here.
(Release version with a Watermark related to my job).

> Using a different runtime library isn't a good solution because the problem isn't so much the lack of library features as it is missing language features. It's been on my to-do list for years to modernize Open Watcom's IOStreams library. However, a standard IOStreams requires language support for explicit template parameters of template functions, something that is lacking in Open Watcom. This is just one example.

I think, a big performance boost can give move semantics,
but using "-std=c++98" disables that.

> What is needed is a core group of, say, three or maybe four people who can put some quality time into the C++ compiler and library. Open Watcom hasn't had that for at least a decade.

Very hard to get more free people for OW, and only, when those are already like OpenWatcom.
The clang/flang/llvm toolchain is far more attractive
and llvm knowledge is even needed for various job offers.

**Comment by winspool** [comment]
Thanks Peter for your detailed answer.
Insider infos are very helpful for me,
since i don't know the OW source base and layout
not good enough yet.

> There actually is a `shared_ptr` implementation in OWSTL, 

Oh, great

> but the person who contributed it didn't provide `unique_ptr`.

What a pity.

> I feel like there is a deeper question here. If we use C++ 2011 constructs in Open Watcom's implementation, then we would need to limit ourselves to the C++ 2011 features that Open Watcom currently implements, which are very few. It would be cleaner to say that Open Watcom needs to be bootstrapped by a C++ 1998 compiler, at least for now.

How long can OW still be compiled with the prev. OW version?

Btw @jmalak what is your Roadmap / timeline 
for an OpenWatcom 2.0 release?

Or a 1.99 release for the current state?
A release would give OW some attention
[dream on] and maybe new developer [back to real mode].
( Reality check: The llvm discord has 10069 members. 1239 are online)

> 
> I hear you saying that gcc/clang are likely to drop support for C++ 1998 in the near future, making them unable to bootstrap Open Watcom. I find that a little surprising, but not unbelievable. Are you saying the newer compilers no longer honor the `-std=c++98` option?

Not in the source (i hope so), 
but you can't control,  how a packager configures
gcc/clang or a C / C++ runtime,
when building a new toolchain/runtime binary release.

I found the commit for gcc-12, where they added 
missing wanings about some of the features,
which are deprecated or remove from the standard.
In that commit, they stated, that they would let 
support for the old features in the source.

But when a packager configures the compiler to be
more modern, code for supporting old cruft is gone.
clang/llvm have the policy to drop deprecated features
after 2 releases.
I hope for OW, that this is only for the toolcain itself
and for experimental features, 
but not for core language/library features,
(Disclaimer: I don't know clang/llvm good enough)


As another example, ubsan is available a long time,
but the compiler user has to activate it.
How many projects do that?
So when gcc/clang is used as compiler,
undefined behavior bugs in the source are undetected.

zig on the other hand activates ubsan by default
and configures clang/llvm/musl/libstdc++
to leave out old cruft: 
When zig is used as c or c++ compiler for a project, compilation faild (old cruft used, like in OW)
or the compiled result crash (ubsan).


> Obviously, the ideal solution would be to move Open Watcom forward to, say, C++ 2011. However... who is going to do that? The C++ compiler and library hasn't moved in years, as far as I can tell. I wrote a fair chunk of the OWSTL back in the 2005-2010 time frame, but my life has shifted. I'd love to make Open Watcom a retirement project, but that's a few years away, and I have other projects in mind as well. In past years, Christof did a lot of great work inside the compiler adding many missing C++ 1998 features, but he has also moved on to other things.

In addition to my scripts for using csmith and yarpgen,
I also started https://github.com/winspool/stdtests
and I want to do test according the standard.
(latest free available draft).

I also have POSIX API here.
(Release version with a Watermark related to my job).

> Using a different runtime library isn't a good solution because the problem isn't so much the lack of library features as it is missing language features. It's been on my to-do list for years to modernize Open Watcom's IOStreams library. However, a standard IOStreams requires language support for explicit template parameters of template functions, something that is lacking in Open Watcom. This is just one example.

I think, a big performance boost can give move semantics,
but using "-std=c++98" disables that.

> What is needed is a core group of, say, three or maybe four people who can put some quality time into the C++ compiler and library. Open Watcom hasn't had that for at least a decade.

Very hard to get more free people for OW, and only, when those are already like OpenWatcom.
The clang/flang/llvm toolchain is far more attractive
and llvm knowledge is even needed for various job offers.

**Comment by gabriel-angular-bootstra** [comment]
@pchapin https://stackdev.space/questions/is-there-a-way-to-ensure-that-the-template-parameter-type-is-always-signed
