### ISSUE TITLE
OS/2 Includes missing defines

### ISSUE THREAD

**Issue by MikeyG** [open-watcom/open-watcom-v2#1125]
The Open Watcom OS/2 BSEDOS.H header is missing defines present in the OS/2 Toolkit headers for named pipes:

```
   /* defined bits in pipe mode */
   #define NP_NBLK                    0x8000 /* non-blocking read/write */
   #define NP_SERVER                  0x4000 /* set if server end       */
   #define NP_WMESG                   0x0400 /* write messages          */
   #define NP_RMESG                   0x0100 /* read as messages        */
   #define NP_ICOUNT                  0x00FF /* instance count field    */
```
The definitions are in the OW header with different names.  I just suggest adding so OW is compatible with OS/2 doc examples and leaving in the current OW definitions.

**Comment by jmalak** [comment]
Thank you for your bug report.
