### ISSUE TITLE
WIP: Prepare for building wppmps and wppppc on linux

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1130]
Before we start adding new architectures,
we can improve portability by made all possible cross compiler working.

The C++ compiler is build for _INTEL_CPU (wpp and wpp386) and for _AXP (wppaxp),
but the C++ compiler for MIPS targets (wppmps)
and PowerPC targets (wppppc) are missing.

**Comment by winspool** [comment]
In addition to my previous pull request #1129,
i changed more code locations, to allow wppmps and wppppc
to compile (but linking fails).

The changes are probably not correct and more things are missing,
but it is a first step



[0000_compile_wpp_for_RISC_CPU.txt](https://github.com/open-watcom/open-watcom-v2/files/12448647/0000_compile_wpp_for_RISC_CPU.txt)

**Comment by winspool** [comment]
These objects are needed for MIPS and PowerPC

#plusplus_objs_ppc = $(_subdir_)cmdlnppc.obj $(_subdir_)cpragppc.obj $(_subdir_)pragppc.obj
#plusplus_objs_mps = $(_subdir_)cmdlnmps.obj $(_subdir_)cpragmps.obj $(_subdir_)pragmps.obj

**Comment by jmalak** [comment]
Work in progress (WIP) is not build by default, because it has no sense.
You can build it by using extended features of builder and pmake tools or by wmake in appropriate subdirectory.
Look into Wiki and for build documentation how you can selectively compile only single architecture/platform.
By example command
**`builder rel 0 .and cpu_ppc os_linux .and .or`**
build only components for PPC processor and Linux host.

**Comment by jmalak** [comment]
Anyway C++ compiler requires some run-time support for C++ compiler which exists only for Intel and Alpha architecture.
Without it has no sense to build compiler even if it can be compiled, but is not usable without it.

**Comment by jmalak** [comment]
I fixed some issue in existing C++ compiler code which break possible RISC build.
It was mainly wrong preprocessor guard for Intel segmented architecture related code.
Now this Intel segmented architecture code is used only for Intel explicitly.
Rebase your changes to HEAD of OW2 git and fix all RISC related build breaks.

**Comment by winspool** [comment]
> Anyway C++ compiler requires some run-time support for C++ compiler 
> which exists only for Intel and Alpha architecture.
> Without it has no sense to build compiler
> even if it can be compiled, but is not usable without it.

Yes, what i learned so far,
the bootstrap versions of the compilers are used
to cross compile the runtime libraries,
so the recent commits are a required step.
Thanks for that

**Comment by winspool** [comment]
With my patchset, wppmps and wppppc start to produce object files:

'
$ owcc  -march=mps empty.cpp  -c 
...
empty.cpp: 4 lines, no warnings, no errors
Code size: 12

$ file empty.o
empty.o: MIPSEL MIPS-II ECOFF executable - version 0.50
`

Works also for PowerPC
`
$ owcc  -march=ppc empty.cpp  -c 
...
empty.cpp: 4 lines, no warnings, no errors
Code size: 8

$ file empty.o
empty.o: MS Windows COFF PowerPC object file
`

Unfortunately, no ELF object files, but at least better than nothing.

-- 
Regards ... Detlef
