### ISSUE TITLE
`option start=<symbol>` doesn't seem to work

### ISSUE THREAD

**Issue by samizzo** [open-watcom/open-watcom-v2#1131]
I'm trying to generate a .com file without default libs. I thought I would need to set `start=<symbol>` to define my start address but it seems like even if I do that and use `nodefaultlibs` the compiler still inserts a reference to `_cstart_` (and also `_small_code_`) so if I don't define it I get a linker error `_cstart_ is undefined`. The linker still prints out `creating a DOS .COM executable` although it doesn't actually create one.

If I *don't* use `option start=<symbol>` and just try and use `_cstart_` I get `Warning! W1023: no starting address found, using 0000:0000`.

Are these bugs or am I doing something wrong? I've attached a simple sample that demonstrates the problem.
[test.zip](https://github.com/open-watcom/open-watcom-v2/files/12565587/test.zip)

**Comment by jmalak** [comment]
COM cannot use start address. It always start on begining of binary.
Simply ommit any C run-time symbols by using **`-zls`** and default C run-time library by **`-zl`** options.
link it with **`format dos com`** directive, don't use **`sys com`**

**Comment by samizzo** [comment]
Ahh great, ok! Thank you!
