### ISSUE TITLE
Debugging on linux with "wd" does not work

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1135]
Example from current ci build:
```
detlef@i7 [/_v/ow_ci]
$ binl64/wd 
Speicherzugriffsfehler (Speicherabzug geschrieben)
detlef@i7 [/_v/ow_ci]
$ binl/wd 
�*��
```

Yes,  the failure message from binl/wd is broken.
That's a new bug.

My previous unpacked ci-build was from 4.9
and the failure from bin/wd was, that std.trp could not be loaded.

Result from the latest release build (1.9.2023):
```
detlef@i7 [/_v/ow_latest_rel]
$ binl64/wd
Speicherzugriffsfehler (Speicherabzug geschrieben)
detlef@i7 [/_v/ow_latest_rel]
$ binl/wd
Cannot load trap file (/_v/ow_latest_rel/binl/std.trp)
```

**Comment by jmalak** [comment]
wd/wdw requires properly configured OW.

**Comment by winspool** [comment]
> wd/wdw requires properly configured OW.

I unpacked "ow-snapshot.tar.xz", set $WATCOM to point to that directory and expected, that this is enough.

At least, this works for
```
cd $WATCOM
wine binnt/wd.exe
```

**Comment by winspool** [comment]
> I unpacked "ow-snapshot.tar.xz", set $WATCOM to point to that directory and expected, that this is enough.

I forgot to mention, that my PATH also includes the correct directories for this test:
linux:  $WATCOM/binl64:$WATCOM/binl
windows: %WATCOM%\binnt64;%WATCOM%\binnt

**Comment by jmalak** [comment]
I checked and it looks like some mistake in my previous changes related to MAD/DIP/TRAP loader.
I will fix it ASAP.

**Comment by winspool** [comment]
Hi @jmalak 
Thanks for your fixes fron today and
with the comment in bug #1133,
wd is getting better:

$WATCOM/binl/wd hello_owcc

Yeah, the Debugger Windows comes up,
but the window and the text are far too small

My console has a size 129x31 with a fontsize of 11
(or 102x27 with a fontsize of 12)

* For the newly opened debugger window, 
  the size is 80x24 and i guess a fontsize of 8.
*  I can't change the fontsize in the debugger window
   (for the console, it is "ctrl +" or "ctrl -")
* When i increase the debugger window, 
   the debugger does not use the extra space.
* When i decrease the debugger window a bit,
   and increase the size again,
    the content is still unreadable broken
    (And the menu bar of wd is missing)
*  When i make the debugger window really small,
    wd crashes. 50 fields is the killsize
    (51x1: alive, 50x1: crash /  26x2: alive,  25x2: crash /
     17x3: alive, 16x3: crash)




cd helloworld
tcpserv

=> tcpserv starts (from binl)

second shell window:
wd -trap=tcp;   hello_owcc
I get always the message
"Unable to connect to server"
The debugger window is not there, but the program runs.

**Comment by jmalak** [comment]
You should read documentation how use debugger and how you setup Windows size.
Debugger run in text mode not in graphical therefore your expectation is wrong.
If you want such feature then you need to run graphical version of OW debugger.
It is possible on Windows and OS/2 only.
You can use remote debugging from Windows to Linux box.

**Comment by jmalak** [comment]
it should be working again.
