### ISSUE TITLE
Strsafe bug, win32 api

### ISSUE THREAD

**Issue by HnkGitHub** [open-watcom/open-watcom-v2#1142]
Platform Windows 10 64-bit
Target: Win32
Build: 9 29-2023

Getting unwanted results from the StringCchCopyN and the StringCchCatN APIs.

The copy function does not terminate correctly. And the cat function does not limit the count of characters copied determined by parameter 4.

Please, see the attached files.

Thanks,

Henry
[strsf.zip](https://github.com/open-watcom/open-watcom-v2/files/12805640/strsf.zip)

**Comment by jmalak** [comment]
Following definition in your code is wrong, you cannot change calling convention for main function.

int __cdecl _tmain(int argc, TCHAR **argv)

Specify exactly how we can reproduce your problem.

**Comment by HnkGitHub** [comment]
Deleting the __cdecl did not make a difference. At least in this code. But thanks for the tip. I saw that written that way in the MSDN docs in an example they provided.

The StringCchCopyN adds an extra character, instead of just just copying the count requested from parameter 4/  And the StringCchCatN did not limit the characters copied. The same code compiles and behaves as defined tin the APIs with a Visual Studio C compiler.

If you'll just build the strsf exe using wmake and run the exe as follows, you should see the bug in the  functions.

strsf addendum

Desired result:
Destad

Watcom result:
Dest addendum

I attached the code in the first post which--apparently--you've seen. I noticed this in a much larger program, but isolated the problem code in the attached file.

**Comment by jmalak** [comment]
Thanks, I can reproduce your problem.
It looks like implementation bug.

**Comment by HnkGitHub** [comment]
Just pulled latest version. Will check it out and let you know. Please, note the issue also crops up in the UNICODE version. Provided both UNICODE  and ANSI versions in the attached Makefile, but commented out  the UNICODE version in the Makefile.

All you have to do is comment out the CFLAGS line in the Makefile for Ansi and remove the comment '#' from the  UNICODE CFLAGS line and rerun wmake: e.g., wmake -A -h

**Comment by jmalak** [comment]
I am sorry 1.9 is not maintained by us.
I think this version (2.0) of strsafe.h should works with 1.9 that you can replace it by the latest version(2.0).
