### ISSUE TITLE
NetBSD/FreeBSD/OpenBSD/DragonflyBSD support?

### ISSUE THREAD

**Issue by sparky4** [open-watcom/open-watcom-v2#1144]
i got a laptop running NetBSD and FreeDOS

will there be support for NetBSD and the other BSDs?

**Comment by jmalak** [comment]
OW isn't ported to *BSD like system.
But could be build on *BSD like system because OW build system is POSIX compatible.
Anyway it is untested and there could be a problem with some missing definitions or setup for *BSD like host.
OW build on OSX is possible so it could work on *BSD.

**Comment by jmalak** [comment]
I checked OW build system and appropriate definitions are there so it should work on *BSD.

**Comment by sparky4** [comment]
sweet thanks i tested the  linux build and ... well... it works perfectly.
