### ISSUE TITLE
Build on macOSX 12.6 fails (there is no "realpath" command)

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1156]
$ uname -a
Darwin cfarm104.cfarm.net 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64

$ export OWVERBOSE=1
$ time  ./build.sh  rel  2>&1  | tee _log_build_1.txt  
./setvars.sh: line 19: realpath: command not found
./setvars.sh: line 93: /cmnvars.sh: No such file or directory

build/buinbuild was not created yet

#############
machine data:

Mac mini (2020) 	arm64 	Apple M1 	
8 cores/8 threads 16.0 GB RAM
MacOSX 12.6 21.6.0

#############

(I know, that building on MacOSX is not supported,
but since i have access to this machine, i tried it)

-- 
Regards ... Detlef

**Comment by winspool** [comment]
I removed "realpath", and build continues
until it breaks about problems with DOSBOX.
(OWDOCBUILD is 0)


diff --git a/setvars.sh b/setvars.sh
index 81a0614a68..5da261b0ee 100755
--- a/setvars.sh
+++ b/setvars.sh
@@ -16,7 +16,7 @@
 # export "OWROOT=/home/ow/o w"
 #
 
-export OWROOT=$(realpath "`pwd`")
+export OWROOT="`pwd`"
 
 # Set OWTOOLS entry to identify your toolchain used by build process
 # supported values are WATCOM GCC CLANG

**Comment by jmalak** [comment]
Simply create your own copy and setup there OW root as describe in script.
```
#!/bin/sh
# *****************************************************************
# setvars - Linux version
# *****************************************************************
# NOTE: Do not use this script directly, but copy it and
#       modify it as necessary for your own use!!

# Change OWROOT to point your Open Watcom source tree
# Note: '=' sign in path is not allowed (build will fail).
#
# export OWROOT=/home/ow/ow
#
# If space character is used in the path then you must double quote
# this path.
#
# export "OWROOT=/home/ow/o w"
#
```

It will fix this problem.

**Comment by winspool** [comment]
> Simply create your own copy of setvars.sh script
> and setup there OW root as described in script.

That's what i do on my local system.
But since i have remote access to this system and never used a macOS before,
i tried it and reported the issue for running "build.sh"

Example machines:
cfarm103: Mac Mini (Debian)
cfarm104: Mac Mini (MacOS)


> DOSBOX is prerequisity for OW build system.

Oh, when i started with OW, dosbox was optional.
OWDOCBUILD=0 is the default and i did not changed the OWDOCBUILD option.
I have no idea yet, for what DOSBOX is required.

> Anyway even if it is not supported, we check regulary OW build on OSX 12.6.9
> (currently Intel). The ARM 32/64-bit host configuration exists and build should work.
> It is completely depend on contributors with such system.

Access to the gcc compile farm is free for open source developer:
https://portal.cfarm.net/

A list of the machines in the compile farm.
https://portal.cfarm.net/machines/list/

Various OS and Arch are available.

> If you are interested in OW build on OSX ARM then you can improve.

Not yet.

> Some issue was reported for 32-bit OSX ARM WRC, 
> but without debug on real OSX we cannot fix it.

ssh access is possible.
Using ssh as tunnel for the debug interfaces would be a nice feature.
(I didn't try that yet).

**Comment by jmalak** [comment]
> > DOSBOX is prerequisity for OW build system.
> 
> Oh, when i started with OW, dosbox was optional. OWDOCBUILD=0 is the default and i did not changed the OWDOCBUILD option. I have no idea yet, for what DOSBOX is required.
No, in the past it was possible to use DOSEMU on Linux otherwise only DOSBOX.
For problems with DOSEMU this stuff was removed and now only DOSBOX must be used.
If you need only test without DOSBOX then you can use OWNOWGML=1 environment variable. It exclude all WGML dependant projects.
