### ISSUE TITLE
Building with Clang/libc++ 16 fails due to deprecated/removed classes

### ISSUE THREAD

**Issue by OPNA2608** [open-watcom/open-watcom-v2#1157]
On Darwin/macOS (first noticed) & Linux (checked), using Clang 16 with LLVM's libc++ (instead of GCC's libstdc++), bootstrapping fails at the `wipfc` target:

```
make -f Makefile wipfc
clang++ -DHAVE_CONFIG_H -I. -I..   -D __STDC_LIMIT_MACROS -D U_NOEXCEPT= -D U_DISABLE_RENAMING -I../cpp -I../icu/common -I../../watcom/h -D _BLDVER=1300 -D _CYEAR=1980  -pipe -g -Wall -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o `test -f 'cpp/main.cpp' || echo '../'`cpp/main.cpp
In file included from ../cpp/main.cpp:37:
In file included from ../cpp/compiler.hpp:46:
../cpp/ptrops.hpp:35:26: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
struct ptrEqualTo : std::binary_function< Type, Type, bool > {
                    ~~~~~^~~~~~~~~~~~~~~
                         __binary_function
/nix/store/i7ksfq6yclpykcisl39ysyqv540l59hd-libcxx-16.0.6-dev/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from ../cpp/main.cpp:37:
In file included from ../cpp/compiler.hpp:46:
../cpp/ptrops.hpp:41:23: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
struct ptrLess : std::binary_function< Type, Type, bool > {
                 ~~~~~^~~~~~~~~~~~~~~
                      __binary_function
/nix/store/i7ksfq6yclpykcisl39ysyqv540l59hd-libcxx-16.0.6-dev/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from ../cpp/main.cpp:37:
In file included from ../cpp/compiler.hpp:46:
../cpp/ptrops.hpp:47:26: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
struct ptrGreater : std::binary_function< Type, Type, bool > {
                    ~~~~~^~~~~~~~~~~~~~~
                         __binary_function
/nix/store/i7ksfq6yclpykcisl39ysyqv540l59hd-libcxx-16.0.6-dev/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from ../cpp/main.cpp:37:
../cpp/compiler.hpp:103:10: error: no template named 'auto_ptr' in namespace 'std'
    std::auto_ptr< Lexer >  _lexer;
    ~~~~~^
4 errors generated.
```

https://clang.llvm.org/cxx_status.html#cxx17 says Clang 16+ defaults to C++17 standard. [`std::binary_function`](https://en.cppreference.com/w/cpp/utility/functional/binary_function) and [`std::auto_ptr`](https://en.cppreference.com/w/cpp/memory/auto_ptr) were both deprecated with C++11 and removed with C++17, and libc++ is strict enough to make them unavailable in that situation (while libstdc++ keeps them on deprecated).

I suppose an `-std` needs to be introduced to limit the used standard somewhere. The configure script has a commented-out example for this, but I think it would be better to always apply it?
https://github.com/open-watcom/open-watcom-v2/blob/4e0b93434fc970ba8e8972b06cb7e857b50ee923/bld/wipfc/configure.ac#L5-L10

**Comment by pchapin** [comment]
When building using g++ or clang, I agree that we should explicitly specify C++98 mode to avoid issues like this (which are likely to become more common in the future as g++ and clang continue to track ever newer standards).

**Comment by jmalak** [comment]
Yes, the problem was missing C++98 specification in GNU configure.ac.
it should be fixed now.
Please, check.

**Comment by winspool** [comment]
This is a duplicate for my bug #1122 from about 4 Month ago:
https://github.com/open-watcom/open-watcom-v2/issues/1122

At that time, I was blamed, that I use the OW build system the wrong way
and my bug was closed without a fix:
https://github.com/open-watcom/open-watcom-v2/issues/1122#issuecomment-1661069834

Thanks @jmalak for changing your mind and fixing my bug after 4 Month,
when this duplicate came up.

-- 
Regards ... Detlef

**Comment by OPNA2608** [comment]
Checked, works fine on Darwin now. Thanks!

**Comment by winspool** [comment]
> Checked, works fine on Darwin now. Thanks!

Thanks for reporting back
