### ISSUE TITLE
A breakout game fails to compile.

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1161]
I saw this video about a "breakout" game in asm, C and C++
and tried it with OpenWatcom (i used the OpenWatcom CI build from 7.12.2023).

Video: "I made the same game in Assembly, C and C++"
https://www.youtube.com/watch?v=2eeXj-ck9VA

The source:
https://github.com/iris-engine-dev/asm_c_cpp.git

## First try with owcc, similar how it usually works with gcc
```
CC=owcc  CFLAGS=" -v"   CXX=owcc CXXFLAGS=" -v "  cmake  -S ..  2>&1   |  tee  _log_owcc_v1.txt
-- The C compiler identification is OpenWatcom 2.0
-- The ASM compiler identification is unknown
```
That fails, because cmake detects the C compiler as "OpenWatcom 2.0"
and uses the cryptic Watcom style command line options for the posix frontend.
(Using `owcc` and switching cmake to generate `Watcom WMake` output makes no difference).

## Second try with plain cmake and Watcom WMake output
`
cmake -S ..  -G "Watcom WMake"  2>&1  |  tee  _log_wmake_v2.txt 
`

cmake selects "$WATCOM/binl64/wcl386" as compiler frontend, but this fails:
$WATCOM/binl64/wcl386 fails to find the includes
and then the build breaks in the sdl subproject,
`
  *** ERROR: Threads are needed by many SDL subsystems and may not be disabled
`
because pthread support was not detected:

```-- Performing Test HAVE_PTHREADS - Failed```

## Third try with wcl386 and helping OpenWatcom to find the includes
`
CC=wcl386 CFLAGS="-i=$WATCOM/lh"   CXX=wcl386  CXXFLAGS="-i=$WATCOM/lh"  cmake  -S ..  2>&1   |  tee  _log_wcl386_v3.txt     
`

Some headers and some functions are not found (to be checked later),
but the build breaks again in the sdl subproject (pthreads support is not detected):
`
  *** ERROR: Threads are needed by many SDL subsystems and may not be disabled
`

## Summary
I have no Idea, what additional features are missing in the OpenWatcom headers
or in the OpenWatcom C/C++ runtime library to support this game,
but the failure to detect pthread support comes from this commandline:
```
/_v/ow/binl64/wcl386 -zq -d+ -DHAVE_PTHREADS  -i=/_v/ow/lh -w3 -bt=linux -D_REENTRANT -pthread -d2 -foCMakeFiles/cmTC_a783c.dir/src.c.o -c -cc /_s/game/breakout_in_asm_c_and_cpp/_manual/CMakeFiles/CMakeScratch/TryCompile-zRirBN/src.c
Error! E1073: Invalid option '-pthread'
Error: Compiler returned a bad status compiling '/_s/game/breakout_in_asm_c_and_cpp/_manual/CMakeFiles/CMakeScratch/TryCompile-zRirBN/src.c'
```

I have no Idea, if the `-pthread` option is copied unchanged from the sdl source (CheckPTHREAD),
because cmake fails to translate it to a `-bm` option for wcl386,
or if the cmake design is "do not touch flags from the project configuration",
but the result is the same:
OpenWatcom is unable to compile this simple SDL game.

I do not expect, that anybody will follow the previously written requirement,
that every project must be ported to OpenWatcom,
and will invest time and port SDL2 to OpenWatcom.

Adding support for the commandline option `-pthread` is an easy way
to improve OpenWatcom and reduce the requirement to port every project to OpenWatcom.

I already added support for the `-pthread` commandline option to `owcc`
for building a different project with `owcc` without porting,
but the pull request was rejected:
https://github.com/open-watcom/open-watcom-v2/pull/1136

-- 
Regards ... Detlef

**Comment by jmalak** [comment]
We are not supporting CMake. 
If you have a problem with CMake then ask CMake community.
