### ISSUE TITLE
Documentation: ide.doc is outdated

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1162]
When reading `ide.doc` in the root directory (Section: A Quick Tutorial),
the starting of the IDE on MS Windows expects "the IDE icon in the program manager window"
and suggest "16Bit Windows Executable" for a new project on MSWindows.
(The different names for the Windows OS should also be updated)

Similar is the Setup Section (Appendix C) still in the 16 Bit Area of Windows.
(And this file has no Appendex B).

I have no idea, how recent is the rest of ide.doc is,
as i'm not very familar with the Open Watcom IDE.

**Comment by jmalak** [comment]
it is not user documentation.
It is hold here due to description of IDE processing and as documentation for configuration files.
Format of configuration files is up-to-date.
