### ISSUE TITLE
Unable to build on Ubuntu Linux

### ISSUE THREAD

**Issue by pchapin** [open-watcom/open-watcom-v2#1165]
I recently updated my source tree using the latest (as of today) on GitHub. Building on my Unbuntu Linux 22.04 system now fails. Specifically, the builder tool can't be made. I'm using `build.sh` to run the build. The contents of `build/binbuild/bootx.log` ends with:

    Open Watcom Make Version 2.0 beta Dec 15 2023 09:04:45 (32-bit)
    Copyright (c) 2002-2023 The Open Watcom Contributors. All Rights Reserved.
    Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
    Source code is available under the Sybase Open Watcom Public License.
    See https://github.com/open-watcom/open-watcom-v2#readme for details.
    cc builder.obj
    Error! E1073: Invalid option '-wce=C310'
    Error(E42): Last command making (builder.obj) returned a bad status
    Error(E02): Make execution terminated

How can I best get past this problem?

**Comment by jmalak** [comment]
I fixed problem with warning numbers mixing between C and C++ compilers.
Both have the same numbers for different messages that result can be confusing.
Now C compiler use 'C' prefix character and C++ compiler 'P' character prefix for message number that C compiler use Cnnn and C++ use Pnnn. C compiler ignore Pnnn and C++ compiler ignore Cnnn messages.
I changed OW build system to use new message numbers that you need to update OW 2.0 bootstrap compiler to be able build OW 2.0 again by OW 2.0.

I will fix it to use old numbering for bootstrap pass (for compatibility with older versions) and new numbering for build pass when new compilers are used.

For backward compatibility with old message numbers compilers accepts old numbers, but build system use new numbers and old number only for older versions of OW. If you use OW 1.9 then no problem.

**Comment by pchapin** [comment]
I see, thanks. I am using Open Watcom to bootstrap Open Watcom, but I'm using a snapshot from this past August which is obviously not new enough. I understand you're going to tweak the bootstrap build process to better support the older compilers, which is great. I can also update myself with a fresher snapshot for building... although I usually build my own snapshots. Hmm.

**Comment by jmalak** [comment]
I am fixing it now that you need not to update bootstrap compiler.

**Comment by jmalak** [comment]
Now it should be fixed.

**Comment by pchapin** [comment]
I can confirm that it is now working for me. Thanks!
