### ISSUE TITLE
16-bit Windows builds break when Open Watcom omits offset relocation fixups needed for window callback procedures in real-mode Windows

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#1166]
I built the latest version of the Open Watcom system and compiled the DOSLIB project with it.

Apparently the latest version produces binaries which work OK in the standard and enhanced Windows 3.0/3.1 environments, but real-mode Windows builds that once worked crash once RegisterClass/CreateWindow get involved with a window callback function.

When it comes to fixups in the NE header that refer to the Entry table, especially when you have to export the window callback procedure you use with RegisterClass, there's some weird arcane stuff going on with real-mode Windows. The first thing I noticed is that if you use FP_SEG() on the window procedure, the segment value is completely different from the value of CS. In fact, if you bring it up in the DOSBox debugger memory window, you'll notice that the segment isn't even our own code segment, it's a copy of our NE executable header! What...? And the offset relocation that you would assume is the offset of the procedure appears to be an offset in the NE header segment pointing to 5 mystery bytes followed by a JMP FAR and then the address of your window procedure wherever Windows currently placed it!

The older Open Watcom I've been using from 2022 dealt with this just fine because it emits relocations for segment and offset correctly, and when you pass this strange relocation address to MakeProcInstance ( i.e. MakeIntResource(WndProc) ), it all turns out correctly and everything runs properly. However in the newest commits, Watcom appears to emit the segment relocation properly but places the known offset of the window procedure directly in the code segment instead of the offset relocation for the WNDPROC. So then MakeProcInstance gets the Windows NE header segment and an offset that points directly at the NE header and produces a procedure that when CreateWindow() goes out to call it, jumps off into space and crashes Windows. I get why Watcom would do that as a possible optimization, and maybe that makes total sense in 16-bit real mode, but unfortunately, it breaks code given the arcane details of old 16-bit Windows.

To see what i mean, the HELLO.EXE code in DOSLIB compiles where WndProc is in the first segment at offset 0x0000 (0x0001:0x0000 meaning index 0) because it's the first subroutine in the source file. However if you print out the FAR pointer of WndProc, you'll find that Windows fixed up the relocation to (in my tests) 0x11FD:0x00BB. 0x11FD is the segment of the NE header and 0xBB is something related to the entry table. For the window procedure to work correctly in real mode, MakeProcInstance() needs the full 0x11FD:0x00BB address to return a correct function pointer for RegisterClass().

Here's the working generated code in HELLO.EXE surrounding where it calls MakeProcInstance((FARPROC)WndProc) using DOSLIB's tool/decompil utility for NE executables:

    0001:0184 @0x000002D6 68 FF FF                PUSH     <segment of entry WNDPROC ordinal #1 -- segment #1 -- 0x0001>
                 ^ EXE relocation Internal ref addr=SEGMENT
                        Refers to movable segment, entry ordinal #1 'WNDPROC'
                        at +1 bytes (0001:0185)
    0001:0187 @0x000002D9 68 FF FF                PUSH     <offset of entry WNDPROC ordinal #1 -- 0x0000>
                 ^ EXE relocation Internal ref addr=OFFSET
                        Refers to movable segment, entry ordinal #1 'WNDPROC'
                        at +1 bytes (0001:0188)
    0001:018A @0x000002DC FF 76 0E                PUSH     SS:(WORD*)[BP+0xE]
    0001:018D @0x000002DF C7 46 CA 03 00          MOV      SS:(WORD*)[BP-0x36],0x3
    0001:0192 @0x000002E4 9A FF FF 00 00          CALL FAR <module reference #3 'KERNEL', ordinal 51>
                 ^ EXE relocation Import by ordinal addr=FAR_POINTER(16:16)
                        Refers to module reference #3 'KERNEL', ordinal 51
                        at +1 bytes (0001:0193)

Here is the same call to MakeProcInstance() using last night's latest commit, notice the 0x0000 which would make sense anywhere outside Windows:

    0001:018B @0x000002DD 68 FF FF                PUSH     <segment of entry WNDPROC ordinal #1 -- segment #1 -- 0x0001>
                 ^ EXE relocation Internal ref addr=SEGMENT
                        Refers to movable segment, entry ordinal #1 'WNDPROC'
                        at +1 bytes (0001:018c)
    0001:018E @0x000002E0 68 00 00                PUSH     0x0
    0001:0191 @0x000002E3 FF 76 0E                PUSH     SS:(WORD*)[BP+0xE]
    0001:0194 @0x000002E6 C7 46 CC 03 00          MOV      SS:(WORD*)[BP-0x34],0x3
    0001:0199 @0x000002EB 9A FF FF 00 00          CALL FAR <module reference #3 'KERNEL', ordinal 51>
                 ^ EXE relocation Import by ordinal addr=FAR_POINTER(16:16)
                        Refers to module reference #3 'KERNEL', ordinal 51
                        at +1 bytes (0001:019a)

The latter causes a crash when Windows attempts to call the window callback procedure.

**Comment by joncampbell123** [comment]
![image](https://github.com/open-watcom/open-watcom-v2/assets/6245486/25898893-7c23-4db6-9c6e-f1b82bea3fcc)

**Comment by joncampbell123** [comment]
![image](https://github.com/open-watcom/open-watcom-v2/assets/6245486/3ceb5367-3aff-4ef4-9038-023f6b242b4f)

**Comment by joncampbell123** [comment]
![image](https://github.com/open-watcom/open-watcom-v2/assets/6245486/ade75ca2-679b-446c-b90d-bd4156a24add)

**Comment by joncampbell123** [comment]
The above screenshots are HELLO.EXE running under real-mode Windows 3.0.

Windows 2.0 behaves identically, though HELLO.EXE is unable to load it's icon resource but runs fine regardless.

**Comment by joncampbell123** [comment]
On a related note, calling sprintf() in Win16 real mode also causes a crash, possible because of similar relocation fixup issues.

**Comment by joncampbell123** [comment]
I am also investigating why the latest Open Watcom commit breaks the DOSBox-X integrated mouse drivers for Windows 1.x/2.x/3.x in all processor modes for some reason.

**Comment by jmalak** [comment]
Thank you for your bug report. I will review latest changes in C compiler front-end which affected 16-bit Windows target. It looks like OW doesn't generate correctly fat prolog necessary for real-mode.

**Comment by jmalak** [comment]
Please, could you give me your compiler command line options and how you have declared/defined appropriate Windows functions.

**Comment by joncampbell123** [comment]
Certainly:

%write tmp.cmd -fr=nul -fo=win302l/.obj -i.. -i"../.." -e=2 -zq -zu -zw -ml -d0 -s -nt=_TEXT -bt=windows -oilrb -os -wx -2 -dTARGET_MSDOS=16 -dTARGET_WINDOWS=30 -dMSDOS=1 -dTARGET86=286 -DMMODE=l -q -x -i"/usr/src/open-watcom-v2/rel/h;/usr/src/open-watcom-v2/rel/h/win" -D_WINDOWS_16_ -bd helldld1.c
wcc @tmp.cmd
%write tmp.cmd option quiet system windows_dll file win302l/helldld1.obj
%write tmp.cmd option modname='HELLDLD1'
%write tmp.cmd EXPORT HELLOMSG.1
%write tmp.cmd EXPORT HELLODRAW.2
%write tmp.cmd segment TYPE CODE PRELOAD MOVEABLE DISCARDABLE SHARED
%write tmp.cmd segment TYPE DATA PRELOAD MOVEABLE
%write tmp.cmd option impfile=win302l/HELLDLD1.LCF
%write tmp.cmd name win302l/HELLDLD1.DLL
perl lcflib.pl --filter win302l/HELLDLD1.LIB win302l/HELLDLD1.LCF
Running: wlib -q -b -c win302l\/HELLDLD1.LIB ++\'HELLOMSG\'.\'HELLDLD1\'.1
Running: wlib -q -b -c win302l\/HELLDLD1.LIB ++\'HELLODRAW\'.\'HELLDLD1\'.2
../../tool/chgnever.pl 3.0 win302l/HELLDLD1.DLL
Extended header at 128
Old version: v3.0
Patching to: v3.0

See also: https://github.com/joncampbell123/doslib/blob/master/windows/hello/common.mak
See also: https://github.com/joncampbell123/doslib/blob/master/mak/comwn302.mak
See also: https://github.com/joncampbell123/doslib/blob/master/mak/comw3086.mak

**Comment by jmalak** [comment]
I checked compiler generated code and compare it with OW 1.9 version and it is same code.
It looks like linker problem.
I will investigate further.

**Comment by joncampbell123** [comment]
I see a commit that might have resolved the issue, building now.

On a related note, would you be OK if I were to begin submitting pull requests to the Windows headers such that setting WINVER=0x200 reduces the provided functions and defines to only what the Windows 2.x SDK provides?

This will be based on two sources:
- Microsoft Visual C++ 1.5, the Win32 SDK help file normally lists which version of Windows an API function appeared
- The Windows 2.0 SDK, which can be obtained here: https://winworldpc.com/product/windows-sdk-ddk/windows-2x

**Comment by jmalak** [comment]
This commit is unrelated to your issue.
It is a preparation for replacing hand-crafted command line processing code with program-generated code.
It fix some issue related to -zw/zW/zWs options that now it works as documented and macros `__CHEAP_WINDOWS__`, `_WINDOWS` and `__WINDOWS__` are properly generated.

To Windows 2.0 SDK, I don't think it should be integrated to existing SDK because the list of files is very different from Windows NT 4.0 (it is our base), it was similar problem with Windows NT 3.x SDK that is too different from NT 4.0. The run-time support for Windows NT 3.x is still included and linker is able generate Windows NT 3.x executable, we don't plan to remove it. The same situation with Win32s. But SDK for them is not supported. It is possible add it as separate SDK. I think holding minimal version for OW SDK 0x400 is OK.

If you specify what change is necessary to NE header for Windows 2.0 I could add it to linker as new target that you can link directly by OW. I don't think it will be big change.

**Comment by joncampbell123** [comment]
Just for reference, the version of Windows 2.0 that does run in protected mode currently does not work in DOSBox-X for reasons we haven't yet determined, unless you boot into an MS-DOS boot disk and then run it.

**Comment by jmalak** [comment]
Now linker has defined target windows which is 3.0 version.
I don't know if Windows 2.0 requires some special libraries or can use standard 3.0 libraries?
We can add target windows2 which could have prefilled version to 2.0 and other setup is as 3.0.
It is only simple definition in text file of target which define various linker directive etc. that simplify linking.

existing linker windows 3.x setup

```
system begin windows
    option osname='Windows 16-bit'
    libpath '%WATCOM%/lib286'
    libpath '%WATCOM%/lib286/win'
    library windows
    option nocaseexact
    option stack=8k, heapsize=1k
    format windows ^
end
system begin windows_dll
    option osname='Windows 16-bit'
    libpath '%WATCOM%/lib286'
    libpath '%WATCOM%/lib286/win'
    library windows
    option nocaseexact
    option stack=8k, heapsize=1k
    libfile libentry.obj
    format windows dll ^
end
```

we can add new
```
system begin windows2
    option osname='Windows 2.0 16-bit'
    version 2.0
    libpath '%WATCOM%/lib286'
    libpath '%WATCOM%/lib286/win'
    library windows
    option nocaseexact
    option stack=8k, heapsize=1k
    format windows ^
end
system begin windows2_dll
    version 2.0
    option osname='Windows 2.0 16-bit'
    libpath '%WATCOM%/lib286'
    libpath '%WATCOM%/lib286/win'
    library windows
    option nocaseexact
    option stack=8k, heapsize=1k
    libfile libentry.obj
    format windows dll ^
end
```
It can be modified to do what is necessary for Windows 2.0.

**Comment by joncampbell123** [comment]
DOSLIB compiled code for real-mode Windows 3.0 appears to work with Windows 2.0 just fine, so long as the EXE says it needs Windows 2.0 and you don't use Windows API functions that didn't exist at the time (like AppendMenuItem).

The only other requirement for real-mode Windows (3.0 and lower) is that segments are defined as MOVEABLE. In fact real-mode Windows will not run your code if any segment is marked FIXED. Resource functions like LoadIcon(), LoadString(), etc. will also not work unless the resource is marked MOVEABLE. The WINDOWS\HELLO program in DOSLIB was not able to load and render the icon image in Windows 3.0 real mode until I marked the icon MOVEABLE.

There is another difference between Windows 2.0 and Windows 3.0 regarding how resources like icons and menus are encoded that I'll address later when I get around to making a pull request to support it in the resource compiler.
Ref: https://github.com/joncampbell123/doslib/blob/master/hw/dos/exenedmp.c#L449 
Ref: https://github.com/joncampbell123/doslib/blob/master/hw/dos/exenew2x.c#L34

**Comment by jmalak** [comment]
Attributes for segments can be define for linker as user definition it is same as for Windows 3.x.

**Comment by joncampbell123** [comment]
> Attributes for segments can be define for linker as user definition it is same as for Windows 3.x.

Of course! The bits mean the same thing in the NE executable.

**Comment by joncampbell123** [comment]
Looks like this is fixed in the latest commit, despite the issue with quoting. :+1: Thank you for your help.
