### ISSUE TITLE
The viw editor crashes always on win11, after using the Menuitem "System" and closing the newly opened console Window.

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1169]
While trying to check bug #1167 on Win11(64),
i used the Open Watcom Editor `viw`.
(OpenWatcom Installed with the latest win64 package)

When i use the `viw` Menu entry `File` -> `System`,
a console window is opened.
(The editor window is still visible, but is busy / no longer works).
As soon, as i close this console Window,
the `viw` window is also closed.

The same happens, when using the IDE:
Mark a c source file and select `Edit` from the toolbar,
then open a console Window with `System` and close it afterwards:
The `viw` window is also closed.

That seems to be broken.

**Comment by winspool** [comment]
The `viw` Editor crashes with editing a file:
* Use the start menu to start the `viw` text editor
* Use `File` -> `Open ...` to open an example c source file
* Open a console with `File` -> `System`
* Close the console
* `viw` is also closed.


The `viw` Editor also crashes without editing a file:
* Use the start menu to start the `viw` text editor
* Open a console with `File` -> `System`
* Close the console
* `viw` is also closed.


Other Way to crash:
* Open the Windows Explorer and Navigate to the example c file
* Double click an example c source file
* In `viw`, open a console with `File` -> `System`
* Close the console
* `viw` is also closed. 



When `viw` is started from the command line,
opening a console with `File` -> `System`
and closing the new console afterwards works without problems.

**Comment by jmalak** [comment]
Viw uses original code for call system and not fixed mixed 32-bit/64-bit anyway.
Try to check it with 32-bit and 64-bit version of VIW.
