### ISSUE TITLE
Qsort doesn't work with 32-bit compact memory model

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#1173]
I have a problem with qsort doing incorrect swaps of elements in the 32-bit compact memory model but not in the flat memory model. When I pass an array of pointers to qsort, it will correctly sort the pointers in the flat memory model, but with the 32-bit compact memory model, it will try to swap what is pointed to instead of the pointer array, thrashing the first 6 bytes of the pointed to data.

It's the "swap" function that malfunctions. The comparisons are using the correct data.

**Comment by rdos314** [comment]
Fixed by commit https://github.com/open-watcom/open-watcom-v2/commit/fa2ab3ce8d637c339e196d9e11569dd53b1985b2

**Comment by rdos314** [comment]
I notice in the flat memory version of the code to swap that DS and ES are saved and reloaded, something that seems quite wasteful. The 16-bit version also use __BIG_DATA to decide if data pointers are near and far. The same logic probably should be applied to the 32-bit memory models.

**Comment by jmalak** [comment]
I Think we should replace in compilers code all checks for flat memory model by appropriate check for near data/code to support far data/code in 32-bit code. If I remember properly then C++ is more compliant with this that mainly C compiler will need review.

**Comment by rdos314** [comment]
Yes, but are the macros __BIG_DATA and __BIG_CODE properly defined for flat memory model? None of them should be defined. Are they properly defined for 32-bit compact memory model?

**Comment by rdos314** [comment]
I've fixed the issues I've spotted in clib related to incorrect implementation of 32-bit code. In the qsort implementation, I made a special case for flat memory model that doesn't need to load es from ds and doesn't need to save segment registers. This is only needed in the small 32-bit memory model.

As for FS being free for use, this is incorrect. At least 32-bit flat memory model use FS for TLS.

**Comment by jmalak** [comment]
Yes flat model has DS, ES and FS pegged to DGROUP, but compact model not.
By default compact model has DS, ES and FS free for any use.
TLS depends on target OS, if exists and how it is addressed. I don't know if TLS access standardization exists.

**Comment by rdos314** [comment]
32-bit Windows and RDOS both use FS for TLS, and so flat model with those targets does not have FS pegged to DGROUP. OTOH, unlike ES, FS is not implicit in any instruction, and so inline assembly does not need to use FS for addressing, unlike ES which is implicit in string operations. 

Anyway, with these modifications, OpenSSL now works as a device driver in RDOS, and so the major problems with the 32-bit compact memory model seems to be fixed.

**Comment by jmalak** [comment]
It is not a problem.
There are two approach for segment registers in inline assembly code.
- you note code generator about changed registers (modify [exact] specifier)
- you preserve register content which is changed in inline code
second method is safe over memory models (but bigger code), first one is smaller and can be used only for registers which is not pegged
you can combine both.

**Comment by jmalak** [comment]
I little optimized assembly inline code for 32-bit in chk8087.c.
