### ISSUE TITLE
WRC resource compiler does not appear to support #if conditionals

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#1176]
The Watcom resource compiler WRC correctly handles #ifdef but does not appear to support #if conditionals.

If you put in your *.rc file an #if conditional like this:

   #if WINVER >= 0x300
   ...
   #endif

Whatever is in the #if block is *always* included no matter what the value of WINVER actually is.

Even if you add -dWINVER=0x200 to the WRC command line, #if WINVER >= 0x300 is still treated as true.

I just found out from DOSLIB development that if you intend for your dialog resource to appear correctly under Windows 2.x you have to omit the FONT setting from your DIALOG resource to prevent WRC from setting DS_SETFONT in the resource data for that dialog box.

DS_SETFONT signals the presence of additional data fields that Windows 2.x does not understand and attempting to load it there fails or causes a "Divide By Zero" error.

It would be nice at this stage if DOSLIB's *.rc files could wrap the line: 

    FONT 8, "MS Sans Serif"

Like this:

    #ifdef (WINVER >= 0x300)
    FONT 8, "MS Sans Serif"
    #endif

**Comment by joncampbell123** [comment]
DOSLIB's makefiles define NO_DS_SETFONT when compiling for Windows 2.x so the *.rc files can omit FONT using #ifndef NO_DS_SETFONT as a workaround for now.

**Comment by joncampbell123** [comment]
Speaking of resources: Windows 2.x RT_MENU resources use a different format than 3.x and later and it doesn't appear to support sub-menus, meaning you can't have for example a File menu at the top level with a "Recent" submenu. You can't make submenus at runtime either using CreateMenu/ChangeMenu/etc it just silently ignores MF_POPUP there.

**Comment by jmalak** [comment]
It looks like bug in expression proccessing for >= or <= operators, > or < operators work OK
