### ISSUE TITLE
Feature request: inline assembly: generate 16 bit sized code for flat mode

### ISSUE THREAD

**Issue by crazii** [open-watcom/open-watcom-v2#1178]
The inline assembly block ```__asm {
}```
cannot generate 16 bit code.

Assumingly a 32 bit code segment is used for protected flat mode, operating on 16 bit register (e.g. ax) in inline assembly will simple add a ```66h``` aka ```size prefix``` which works as intended.

But there's a chance that a snippet of 16 bit code was created to run from under dos directly (e.g. extra TSR entries code) as real mode code. (e.g. COPY the real mode code into conventional memory and terminate, like the reverse process of a loader). 

Such situation need the code running in real mode (or a 16 bit code segment), so the ```size prefix``` actually make it flipped as 32 bit operations. since in 16 bit code segment the default size is ```ax``` instead of ```eax``` and a ```size prefix``` will make it change to ```eax```.

The problem can be solved by using pure assembly, to define codes in a 16bit segment. 

But for inline assembly, it'll be much better to add such ability to assume the code itself runs in a 16 bit segment already, and no ```size prefix``` is added when operating on 16 bit registers.
A good example is GCC/DJGPP, a '.code16' directive makes this code work as intended:
```
__asm__ {
    ".intel_syntax noprefix\n\t"
    ".code16\n\t"
    "mov xxx, ax" //no 66h prefix is generated
    ".code32\n\t" //remember to set it back!
}
```

**Comment by jmalak** [comment]
You can create extra module with 16-bit code and link it with 32-bit code.
On DOS mix of segments with different bit size is possible, linker should be able.

**Comment by crazii** [comment]
Yes that's another way that will work, for both GCC and OpenWatcom. Still, how about this feature for 32bit code inline assembly?  the whole point is that inline assembly can be written freely without put it in another compile unit, either c or asm. That involves special handling in makefile anyways.

So Is it necessary or will it be planned?

**Comment by jmalak** [comment]
I think it is not simple, because all code generation is based on segment size.
there is also problem with relocations etc. too complex change for no gain.
Anyway such solution is unportable.
Other unportable solution is to use #pragma aux and generate instructions as byte sequences.
#pragma aux use macro expansion that is possible to define such instruction as macro.

**Comment by crazii** [comment]
I ran a fast test with 16 bit compiler (wcc/wpp) it seems it restrict the register set to word size for ```#pragma aux ```,
 ```
#pragma aux TEST = \
"pop eax" \
modify[eax]
```
yields
 ```Invalid register name 'eax' in #pragma``` even when I use -3 or -4 options.
but the ```__asm {
}```
block works.

**Comment by crazii** [comment]
Fair enough. I myself doesn't like too much work for no gain. :)
Hope I can work around another solution.

**Comment by crazii** [comment]
Yes I was mistaking the 16 bit ABI as 32 bit. #pragma aux works indeed.
There's comment in my source when I wrote about some function but I just forgot the details for a moment.
