### ISSUE TITLE
Use of __AHSHIFT in C runtime startup prevents compiled EXEs from running under Windows 1.0

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#1188]
It turns out the changes I've made to target Windows 2.0 work just as well with Windows 1.0, if I change clib/startup/a/cstrtw16.asm to assume a value of 12 instead of using KERNEL symbol __AHSHIFT (ordinal 113) which does not exist in Windows 1.0.

Could the C runtime make a Windows 1.0 specific Windows.086 build? Or perhaps the linker could map __AHSHIFT to an internal hardcoded constant of 12 instead of KERNEL.113 __AHSHIFT if the Linker is asked to target Windows 1.0?

Apparently Windows 1.0 also does not understand the Windows 3.0 style ampersand hotkey scheme.

![win100_001](https://github.com/open-watcom/open-watcom-v2/assets/6245486/1ecc7a7c-bf23-4bee-a29e-23cfd96ab21d)
![win100_002](https://github.com/open-watcom/open-watcom-v2/assets/6245486/bffa5be7-2869-44fb-9500-7e1c39b80ac3)
![win100_009](https://github.com/open-watcom/open-watcom-v2/assets/6245486/4c24bde6-a557-47b5-a9b2-c2c253129be4)

**Comment by joncampbell123** [comment]
On a related note, sprintf() triggers calls to KERNEL.207 which according to Windows 3.11 KRNL386.EXE is the IsLeadDBCSByte function which also does not exist in Windows 1.0.

**Comment by jmalak** [comment]
I think best solution is create specific startup code and use it for linking Windows 1.0 executable.
Anyway we should create windows1 and windows2 linker system to use for linking Windows 1.0 and Windows 2.0 executable and enable use of owcc utility for these targets.

**Comment by jmalak** [comment]
I added appropriate target definition for wlink and owcc based on windows 3.x
I only changed definition of version in NE header
I don't change startup module it must be changed as soon as it will be prepared
DLL definitions use windows 3.x libentry.obj startup module

**Comment by jmalak** [comment]
Please, could you contribute with Windows 1.0 and Windows 2.0 startup code (for application and DLL) changes to be able integrate it into OW compile and link environment.

**Comment by joncampbell123** [comment]
> Please, could you contribute with Windows 1.0 and Windows 2.0 startup code (for application and DLL) changes to be able integrate it into OW compile and link environment.

Would you like the change as an #ifdef or #if for the assembly language file?

I understand why the code is using __AHSHIFT, it's a convenient way to detect if the CPU is in real mode or not instead of all the normal 8086/286/386 EFLAGS test and reading of the machine status word that DOSLIB currently does. All that code needs is an #if conditional so that when targeting Windows 1.0, the reference to __AHSHIFT is replaced by a hard-coded constant 12.

As I understand it that would require a "windows1.086" version of clib, correct?

I know what I need to change, how should I wrap it to compile only for Windows 1.0?

**Comment by jmalak** [comment]
It should be enough If you add #if conditions to existing startup code then we add conditional compilation of the startup module and specify it for linker and add this module to standard distribution of OW.
We add only startup module for Windows 1.0 and Windows 2.0 if they are different.
it will use regular 16-bit Windows library and this new startup module and ignore Windows 3.x startup module in CRTL.

**Comment by joncampbell123** [comment]
Will do.

I've been running a PE EXE dumper in doslib and I just discovered that core system DLLs in Windows 95 are "pre-resolved", meaning if you scan the import address table and expect to find relative virtual addresses pointing to symbol names or ordinals, what you'll find is instead memory addresses of where the DLL symbols will be. Most of these core DLLs reside at memory addresses like 0xBFxxxxxx (though OLE32.DLL resides at 0x7Fxxxxxx) so it's easy to mistake them as very large numbered ordinal imports.

It's kind of a performance cheat in that the core libraries load faster because there is no symbol lookup involved.

Perhaps a patch could be applied to WDUMP to recognize that and handle it better?

Also the 32-bit DLLS in Windows 3.1 Win32s have a PE magic of 0x0000 (not 0x010B) because I guess they hadn't defined that yet at the time.

See: https://github.com/joncampbell123/doslib/blob/master/hw/dos/exepedmp.c

**Comment by jmalak** [comment]
I am working now on complete fix for wlink to support little bit changed fix for Windows 9x and enable specify initial reserved and commit size in header for stack and heap even if it is DLL etc.

**Comment by jmalak** [comment]
> Will do.
> 
> I've been running a PE EXE dumper in doslib and I just discovered that core system DLLs in Windows 95 are "pre-resolved", meaning if you scan the import address table and expect to find relative virtual addresses pointing to symbol names or ordinals, what you'll find is instead memory addresses of where the DLL symbols will be. Most of these core DLLs reside at memory addresses like 0xBFxxxxxx (though OLE32.DLL resides at 0x7Fxxxxxx) so it's easy to mistake them as very large numbered ordinal imports.
> 
> It's kind of a performance cheat in that the core libraries load faster because there is no symbol lookup involved.
> 
> Perhaps a patch could be applied to WDUMP to recognize that and handle it better? It won't resolve an import symbol name of course because that would require looking up the export table of other DLLs to do that, but it could say that it's "pre-resolved symbol address xxxxxxx". This is a future pull request idea, not part of this issue.
> 
> Also the 32-bit DLLS in Windows 3.1 Win32s have a PE magic of 0x0000 (not 0x010B) because I guess they hadn't defined that yet at the time. They're still valid PE headers though.
> 
> See: https://github.com/joncampbell123/doslib/blob/master/hw/dos/exepedmp.c

It should not be a problem to generate pre-located DLL. All OW system DLLs are pre-allocated.
We only need to know start addres of DLL.

```
rtdll_dllbase_winnt_386_mathlib = op offset=0x6ff00000          # mtxxxx.dll    (run-time DLL math library)
rtdll_dllbase_winnt_386_clib    = op offset=0x6fe00000          # clbxxxx.dll   (run-time DLL C library)
rtdll_dllbase_winnt_386_cpplib  = op offset=0x6fd00000          # plbxxxx.dll   (run-time DLL C++ library)
rtdll_dllbase_winnt_386_wrtlib  = op offset=0x6fa00000          # wrtxxxx.dll   (run-time DLL combined C, math and C++ library)
dip_dllbase_nt_386_dwarf        = op offset=0x6ef$(dll_start)   # dwarf.dll     (Debugger DIP)
dip_dllbase_nt_386_watcom       = op offset=0x6ee$(dll_start)   # watcom.dll    (Debugger DIP)
dip_dllbase_nt_386_codeview     = op offset=0x6ed$(dll_start)   # codeview.dll  (Debugger DIP)
dip_dllbase_nt_386_export       = op offset=0x6ec$(dll_start)   # export.dll    (Debugger DIP)
dip_dllbase_nt_386_hllcv        = op offset=0x6eb$(dll_start)   # hllcv.dll     (Debugger DIP)
dip_dllbase_nt_386_mapsym       = op offset=0x6ea$(dll_start)   # mapsym.dll    (Debugger DIP)
dip_dllbase_nt_386_javavm       = op offset=0x6e9$(dll_start)   # javavm.dll    (Debugger DIP)
mad_dllbase_nt_386              = op offset=0x6e8$(dll_start)   # madx86.dll    (Debugger MAD)
trap_dllbase_nt_386             = op offset=0x6e7$(dll_start)   # all trap dlls (Debugger TRAP)
wlib_dllbase_nt_386             = op offset=0x6a000000          # wlibd.dll     (Librarian)
wlink_dllbase_nt_386            = op offset=0x69c00000          # wlinkd.dll    (Linker)
wr_dllbase_nt_386               = op offset=0x69900000          # wr.dll        (Resource library)
wrc_dllbase_nt_386              = op offset=0x69800000          # wrc.dll       (Resource compiler)
wcc_dllbase_nt_386              = op offset=0x69400000          # wccdxxxx.dll  (C compiler)
wpp_dllbase_nt_386              = op offset=0x69000000          # wppdxxxx.dll  (C++ compiler)

```

**Comment by joncampbell123** [comment]
I'm not saying I want pre-located DLLs, I'm just pointing out that perhaps WDUMP should be updated to recognize that as EXEPEDMP.C in DOSLIB had to.

**Comment by joncampbell123** [comment]
How's this?

#define _WINDOWS_10 if targeting Windows 1.0.

            cld                             ; set forward direction
            push    ds                      ; set es=ds
            pop     es                      ; ...
            mov     cx,offset DGROUP:_end   ; end of _BSS segment (start of STACK)
            mov     di,offset DGROUP:_edata ; start of _BSS segment
            sub     cx,di                   ; calc # of bytes in _BSS segment
            xor     al,al                   ; zero the _BSS segment
            rep     stosb                   ; . . .
    if _WINDOWS_10
            mov     ax,12                   ; huge shift value, assume real mode
    else
            mov     ax,offset __AHSHIFT     ; get huge shift value
    endif
            mov     _HShift,al              ; ...
            cmp     al,12                   ; real mode?
            je      notprot                 ; yes, so leave osmode alone
            mov     al,1
            mov     _osmode,al              ; protected mode!
    notprot:

**Comment by joncampbell123** [comment]
I just checked out a disk image of Windows 2000... everything pre-installed on the system including the files in Program Files is full of this pre-located trickery :laughing:

**Comment by joncampbell123** [comment]
Notice they don't do this pre-resolved thing anymore in any part of Windows 10... Address Space Randomization tends to screw that trick up, doesn't it? :)

**Comment by joncampbell123** [comment]
> How's this?
> 
> bld/clib/startup/a/cstrtw16.asm
> 
> and
> 
> bld/clib/startup/a/libentry.asm
> 
> #define _WINDOWS_10 if targeting Windows 1.0.
> 
> ```
>         cld                             ; set forward direction
>         push    ds                      ; set es=ds
>         pop     es                      ; ...
>         mov     cx,offset DGROUP:_end   ; end of _BSS segment (start of STACK)
>         mov     di,offset DGROUP:_edata ; start of _BSS segment
>         sub     cx,di                   ; calc # of bytes in _BSS segment
>         xor     al,al                   ; zero the _BSS segment
>         rep     stosb                   ; . . .
> if _WINDOWS_10
>         mov     ax,12                   ; huge shift value, assume real mode
> else
>         mov     ax,offset __AHSHIFT     ; get huge shift value
> endif
>         mov     _HShift,al              ; ...
>         cmp     al,12                   ; real mode?
>         je      notprot                 ; yes, so leave osmode alone
>         mov     al,1
>         mov     _osmode,al              ; protected mode!
> notprot:
> ```

Please let me know if this is what you're looking for, and then I'll make a pull request.

**Comment by jmalak** [comment]
Thanks for confirmation of this simple change.
It doesn't need to do PR.
I also modified code of DLL startup module.
I will submit complete integration to OW as soon as I finished it and do integration tests.
Because startup module is memory model sensitive I created special library win10<memory model>.lib which will contains appropriate startup module (can contain other modules in the future) and will be added to front of linker library list if WINVER=0x100 only.

**Comment by jmalak** [comment]
I submit all necessary change for Windows 1.0 and update Windows 2.0 definition for owcc utility by 
https://github.com/open-watcom/open-watcom-v2/commit/c74f9a385cd48cac1e77ff2f583ae1d852eb5fc2 .
Please check with new build.
All changes are included in OW distribution that should be available in installers etc.

**Comment by jmalak** [comment]
I added new issue for pre-allocated Windows system DLLs problem.

**Comment by joncampbell123** [comment]
windows\hello\

    bash-5.0# ./make.sh 
    %write tmp.cmd -fr=nul -fo=win100l/.obj -i.. -i"../.." -e=2 -zq -zu -zw -ml -d0 -s -nt=_TEXT -bt=windows -oilrb -os -wx -0 -dTARGET_MSDOS=16 -dTARGET_WINDOWS=10 -dMSDOS=1 -dTARGET86=86 -DMMODE=l -q -x -i"/usr/src/open-watcom-v2-upstream/rel/h;/usr/src/open-watcom-v2-upstream/rel/h/win" -D_WINDOWS_16_ -bg -dWINVER=0x0100 hello.c
    wcc @tmp.cmd
    hello.c(244): Warning! W303: Parameter 'lpCmdLine' has been defined, but not referenced
    wrc -i.. -i"../.." -q -r -10 -bt=windows -x -i"/usr/src/open-watcom-v2-upstream/rel/h;/usr/src/open-watcom-v2-upstream/rel/h/win" -dNO_DS_SETFONT=1 -fo=win100l/hello.res hello.rc
    %write tmp.cmd option quiet system windows1 file win100l/hello.obj
    %write tmp.cmd EXPORT WndProc.1 PRIVATE RESIDENT
    %write tmp.cmd segment TYPE CODE PRELOAD MOVEABLE DISCARDABLE SHARED
    %write tmp.cmd segment TYPE DATA PRELOAD MOVEABLE
    %write tmp.cmd option map=win100l/hello.exe.map
    %write tmp.cmd op resource=win100l/hello.res name win100l/hello.exe
    Error! E3033: system block windows1: directive error near 'version'
    Error(E42): Last command making (win100l/hello.exe) returned a bad status
    Error(E02): Make execution terminated

What exactly is wl/lnk/specs.sp trying to do here?

    system begin windows1
    :segment Pspecs
    ARCH i86 -bt=windows -dWINVER=0x100
    :elsesegment Pwlsystem
    option osname='Windows 1.0'
    version=1.0
    libpath '%WATCOM%/lib286'
    libpath '%WATCOM%/lib286/win'
    library windows
    option nocaseexact
    option stack=8k, heapsize=1k
    format windows ^
    :endsegment
    end

**Comment by joncampbell123** [comment]
I can eliminate the error if I change "version=1.0" to "option version=1.0" which is consistent with the linker manual: https://open-watcom.github.io/open-watcom-v2-wikidocs/lguide.pdf

![image](https://github.com/open-watcom/open-watcom-v2/assets/6245486/fdac92cf-5fcc-42ae-a330-e4dedbb580f5)

However the linker doesn't appear to be paying any attention to OPTION VERSION, the generated executable has an NE header that still says version 3.0.

**Comment by joncampbell123** [comment]
It says version 3.0 regardless whether I use "system windows1" or directly put "option version=1.0" in the DOSLIB makefile windows\exmenus

**Comment by jmalak** [comment]
it should be fixed by e54093698574c2e6754a77836945644002b6643d

**Comment by joncampbell123** [comment]
Nice! I've disabled the NE header patch script for targeting Windows 1.x/2.x in DOSLIB and I see the NE header is set properly.

For some reason "system windows2" results in an NE image where the minimum version field is 0.0 instead of 2.0.

Windows or OS/2 NE header:
    Linker version:               5.1
    Entry table offset:           146 NE-rel (abs=274) bytes
    Entry table length:           22 bytes
    32-bit file CRC:              0x00000000
    EXE content flags:            0x0002
        DGROUP type:              2 MULTIPLEDATA
        Application type:         0 NONE
    AUTODATA segment index:       2
    Initial heap size:            1024
    Initial stack size:           8192
    CS:IP                         segment #1 : 0x028e
    SS:SP                         segment #2 : 0x0000
    Segment table entries:        2
    Module ref. table entries:    3
    Non-resident name table len:  21 bytes
    Segment table offset:         64 NE-rel (abs 192) bytes
    Resource table offset:        80 NE-rel (abs 208) bytes
    Resident name table offset:   104 NE-rel (abs 232) bytes
    Module ref. table offset:     123 NE-rel (abs 251) bytes
    Imported name table offset:   129 NE-rel (abs 257) bytes
    Non-resident name table offset:296 bytes
    Movable entry points:         3
    Sector shift:                 1 (1 sector << 1 = 2 bytes)
    Number of resource segments:  1
    Target OS:                    0x00 None / Windows 2.x or earlier
    Other flags:                  0x0000
    Fastload offset:              0 sectors (0 bytes)
    Fastload length:              0 sectors (0 bytes)
    Minimum code swap area size:  0
    Minimum Windows version:      0.0

**Comment by joncampbell123** [comment]
Hm... but only windows\hello compiles that way.

windows\exmenus produces Windows 2.0 with the proper version 2.0 in the header.

**Comment by joncampbell123** [comment]
Anyway, Windows 1.0 targets compile properly now without using __AHSHIFT, which is what this issue was about in the first place. Thank you for helping me make this work. Happy new year! :+1:
