### ISSUE TITLE
rc, incorrect argument parsing

### ISSUE THREAD

**Issue by adamyg** [open-watcom/open-watcom-v2#1202]
Latest build 2024-01-01 incorrectly parses arguments, treating embedded '-' and '/' as a new arguments.
Note: Change in behavior from previous builds.

Examples:
   rc -DVAR=name-8 name.rc
   rc -DVAR=name/8 name.rc
   
Result:
>   Open Watcom C/C++ RC Clone for 386 Version 2.0 beta Jan  1 2024 02:09:27 (32-bit)
>   Copyright (c) 2002-2024 The Open Watcom Contributors. All Rights Reserved.
>   Portions Copyright (c) 1995-2002 Sybase, Inc. All Rights Reserved.
>   Source code is available under the Sybase Open Watcom Public License.
>   See https://github.com/open-watcom/open-watcom-v2#readme for details.
>   Error! E159: Can't find file "8.rc".
>   Fatal error: Error executing 'wrc'

**Comment by jmalak** [comment]
it is fixed now.
please check with new OW build.

**Comment by adamyg** [comment]
Tested, thanks
