### ISSUE TITLE
DOS: sbrk() not compatible with malloc

### ISSUE THREAD

**Issue by crazii** [open-watcom/open-watcom-v2#1206]
model: tiny/small

# symptom:
Use ```sbrk(0xFFFE-(short)sbrk(0))``` to set brk to max and void further memory allocation from DOS, then
malloc will fail soon.

# cause:
The C lib heap assume the brk value as the end of heap space(open-watcom-v2/bld/clib/heap/c/grownear.c: 418), but they're not necessarily equal; brk value can be set by user via ```sbrk()```.
Need a value to record the heap space end/size, separated from the brk value.

# workaround:
Use ```_heapgrow```
_heapgorw will set the brk to max and also adjust heap size at the same time.

**Comment by jmalak** [comment]
Read carefully documentation for [sbrk](https://open-watcom.github.io/open-watcom-v2-wikidocs/clib.html#sbrk) function.
Anyway sbrk must be used carefully with regards to rounding to _amblksiz and para(16-byte) and stack size which is allocated in near memory.

**Comment by crazii** [comment]
Yes I read that, for multiple times. didn't get much information, maybe I misunderstood.

But just found useful info here:
https://pubs.opengroup.org/onlinepubs/7908799/xsh/brk.html
It also says combine of sbrk with malloc has **_unspecified behavior_**.  

The return of sbrk() is like malloc() and is reserved for client use. Now I understand they two don't have to be "compatible", creating heap from the new brk value is not a bug but makes them internally compatible indeed.

I remembered the brk/sbrk() incorrectly - thought it can reserve space and malloc will use that space - malloc may call sbrk() for new break, but it never reuse the block used by client. damn. my bad.
Sorry if I brought inconvenience.

**Comment by crazii** [comment]
I'll close this issue right now.
BTW is there a detailed doc on wmake? I've searched but didn't find any.
I want to try a GNU equivalent ```XXX = $(shell xxxcmd)``` to get extra infos.
I mean, I don't expect wmake to have the same feature as GNU make, I just need a document/manual.

**Comment by jmalak** [comment]
No problem.
I think wmake can do such thing. You can define if command is run directly or in shell.
the resolution is use prefix character for [command](https://open-watcom.github.io/open-watcom-v2-wikidocs/ctools.html#Command_List_Execution) "!" exclamation character force to use shell with command. there areother command prefixes as "-" to ignore return value for check "@" prefix to no echo.

**Comment by crazii** [comment]
Thanks, the use of wmake is in ctools doc. I believe I saw it before.
