### ISSUE TITLE
wlib failure with latest builds:

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#1208]
Something broke between the `Jan 19 2024 01:51:58` and
`Jan 20 2024 01:49:35` builds of openwatcom, resulting
in lib file generation failure both on linux and win32
hosts. See, e.g.:
https://github.com/libsdl-org/SDL/actions/runs/7592485061/job/20681868191

On a windows host:
```
* Creating LIB file: .\SDL2.lib
	wlib -q -b -n -c -pa -s -t -zld -ii -io .\SDL2 ./SDL2.dll
Error(F38): (.\SDL2.lib) does not exist and cannot be made from existing files
Error(E02): Make execution terminated
```

On a linux host:
```
* Creating LIB file: ./SDL2.lib
	wlib -q -b -n -c -pa -s -t -zld -ii -io ./SDL2 ./SDL2.dll
Error(F38): (./SDL2.lib) does not exist and cannot be made from existing files
Error(E02): Make execution terminated
```

**Comment by jmalak** [comment]
Thanks for your bug report.
It looks like mistake in . path processing related to last changes in librarian command line processing.
I will fix it ASAP.

**Comment by jmalak** [comment]
It should be fixed now. It was a bug in the default file extension processing.

**Comment by sezero** [comment]
Thank you. Will test as soon as a new binary build is available.

**Comment by sezero** [comment]
>  Will test as soon as a new binary build is available.

Current code seems to fail building in github actions, though..

**Comment by sezero** [comment]
Tested the Last-CI-build from 1b9d6193e3d48b457d3b189d0e4349a37d3b81a5, seems to be fixed. Thank you.
