### ISSUE TITLE
Bug in wlib -p=512 option processing

### ISSUE THREAD

**Issue by virgban** [open-watcom/open-watcom-v2#1210]
I downloaded Open Watcom 2.0 to
open-watcom-2_0-c-win-x64.zip
and installed it fully over a previous OW 1.9 installation for my 64 Bit Windows 10 Pro PC 
(echo %PROCESSOR_ARCHITECTURE% produces AMD64)
Trying to learn from examples of code from Open Watcom so I downloaded some example code from
https://github.com/open-watcom/open-watcom-v2I
to open-watcom-v2-master.zip
which contains over 33000 files of C++ code and project support files.
I selected the project
bld/idedemo/src/win32.wpj and compiled the 2nd target (button) with the error
"
  wlib -b -c -n -q -p=512 button.lib @button.lb1
  Error! Invalid command line near '-p=512 button.lib @button.lb1'
"
I removed the "-p=512" from the above command line (in bld/idedemo/src/win32/button.mk1)
Then both targets compiled, linked, and ran ok.
Did I discover a bug or am I doing something wrong?
Is it possible that I used the wrong project for my system?
The possible project selections in bld/idedemo/src/ are
	win32.wpj
	win.wpj
	win386.wpj
I selected the first one but did not have a good reason.
Can anyone provide some guidance for this newbie.

**Comment by jmalak** [comment]
Thanks for bug report.
It is probably related to new wlib command line processing code and some bugs in this new processing which were fixed.
Please try to download latest OW build and check if it is still problem.

**Comment by jmalak** [comment]
the issue should be fixed.
Please download new OW build after regular re-build and re-check.

**Comment by virgban** [comment]
Was the fix in the OW code or the sample project code (bld/idedemo/src)?

**Comment by jmalak** [comment]
It was fix in librarian tool "wlib" not in sample project.

**Comment by virgban** [comment]
Thanks,
I see from sourceforge, the latest update is 5/24/2023 per
https://sourceforge.net/projects/openwatcom/

To get the latest fix, do I need to rebuild Watcom from source or is the
executable available for WIN32 somewhere?

**Comment by jmalak** [comment]
not needed, OW use Github for automatic daily release and CI-build that you need not to rebuild OW from source. You can download OW snapshot which contains full OW and replace existing files with this snapshot.
[see](https://github.com/open-watcom/open-watcom-v2/releases)
