### ISSUE TITLE
Non-functional instruction in "Smart Editing" section

### ISSUE THREAD

**Issue by virgban** [open-watcom/open-watcom-v2#1215]
The OW page
https://open-watcom.github.io/open-watcom-v2-wikidocs/c_readme.html
has an instructions in the "Smart Editing" section:
	"3. Pull down the Options menu and select the Colors item."
In the Open Watcom IDE window, I see no "Colors" item in the Options menu. 
In the Open Watcom Text Editor window, the only "menu" is a set of icons.
Running a 64 Bit Windows 10 Pro PC 
(echo %PROCESSOR_ARCHITECTURE% produces AMD64)
Is there a step missing?

**Comment by jmalak** [comment]
Please read carefully point 2. which you instruct to open source file, it start OW editor and point 3. is related to editor Window not to IDE Window.

**Comment by virgban** [comment]
From
https://open-watcom.github.io/open-watcom-v2-wikidocs/c_readme.html
I read:

1. Double-click on the "draw" source file (i.e., draw???.c) to load the
source file into the editor.
2. Scroll down to line 227 using the keyboard or mouse.  You can also pull
down the* Edit* menu, select* Goto Line...,* and enter 227.  The Open
Watcom Editor makes full use of colors and fonts to achieve syntax
highlighting.   File templates for C, C++, and FORTRAN files are defined to
assist you in distinguishing the components of your code.
3.Pull down the* Options* menu and select the* Colors* item.


In the Open Watcom Text Editor window, the only "menu" is a set of icons as
you can see from the image below.
In my native text editor on my Windows 10 Pro PC, I see menus, but not in
the Open Watcom Text Editor. Also, I see no icons that map to "Options".

**Comment by virgban** [comment]
From
https://open-watcom.github.io/open-watcom-v2-wikidocs/c_readme.html
I read:

1. Double-click on the "draw" source file (i.e., draw???.c) to load the
source file into the editor.
2. Scroll down to line 227 using the keyboard or mouse.  You can also pull
down the* Edit* menu, select* Goto Line...,* and enter 227.  The Open
Watcom Editor makes full use of colors and fonts to achieve syntax
highlighting.   File templates for C, C++, and FORTRAN files are defined to
assist you in distinguishing the components of your code.
3.Pull down the* Options* menu and select the* Colors* item.


In the Open Watcom Text Editor window, the only "menu" is a set of icons as
you can see from the image below.
In my native text editor on my Windows 10 Pro PC, I see menus, but not in
the Open Watcom Text Editor. Also, I see no icons that map to "Options" as
shown below.

**Comment by jmalak** [comment]
Sorry, I don't see any picture.
On my installation I see all appropriate menu items and toolbar (you can switch on/off toolbar).
Do you want to say that you don't see OW editor menus?

**Comment by virgban** [comment]
Yes, I don't see OW editor menus. I tried switching the toolbar on as
follows:
Press the Windows logo key + I to get to Settings. Select
Personalization. Select
Taskbar. Set the hide Automatically hide options to Off.

Unfortunately, there was no "Personalization" to select.
How do I get my toolbar back on Windows 10?
Press the Windows logo key + I to get to Settings. Select
Personalization. Select
Taskbar. Set the hide Automatically hide options to Off.

**Comment by virgban** [comment]
I remove files watcom.ini and weditor.ini as you suggested.
Now I have a toolbar for the OW editor. Thanks.
