### ISSUE TITLE
wlib static issue on Jan 27 build

### ISSUE THREAD

**Issue by bradh352** [open-watcom/open-watcom-v2#1216]
We have a github action building for our project to include openwatcom and it started failing with the Jan 27 build of openwatcom during linking of the static library, the dynamic library appears to be ok:
https://github.com/c-ares/c-ares/actions/runs/7682548593/job/20937046171

Jan 26 build was fine:
https://github.com/c-ares/c-ares/actions/runs/7673704692/job/20916876318

**Comment by jmalak** [comment]
It should be fixed.
Please recheck with new OW build.

**Comment by bradh352** [comment]
same issue in the Jan 28 build: https://github.com/c-ares/c-ares/actions/runs/7685678893/job/20943691053

**Comment by omm** [comment]
Hi,

The same error while compiling [Harbour](https://github.com/harbour/core)
```
C:\WATCOM\binnt64>wcc386.exe -v
Open Watcom C x86 32-bit Optimizing Compiler
Version 2.0 beta Jan 28 2024 02:01:46 (64-bit)
...
hbmk2: Creating static library... ..\lib\win\watcom\minizip.lib
hbmk2: Lib command:
wlib.exe @C:\Users\o2m\AppData\Local\Temp\7pkpo1.lnk
hbmk2: Lib script:
-q  -p=64 ..\lib\win\watcom\minizip.lib -+ ..\lib\win\watcom\.hbmk\minizip\ioapi.obj -+ ..\lib\win\watcom\.hbmk\minizip\zip.obj -+ ..\lib\win\watcom\.hbmk\minizip\unzip.obj
Error! Invalid command line near '-+ ..\lib\win\watcom\.hbmk\minizip\ioapi.obj -+ ..\lib\win\watcom\.hbmk\minizip\zip.obj -+ ..\lib\win\watcom\.hbmk\minizip\unzip.obj'

```

With previous version
Open Watcom C x86 32-bit Optimizing Compiler
Version 2.0 beta Nov 12 2023 02:04:52 (64-bit)
...
all fine.

Thanks

**Comment by jmalak** [comment]
Sorry, you use still old version. fix was submitted 2024-01-28 05:34 UTC. and you use version Version 2.0 beta Jan 28 2024 02:01:46 (64-bit)

**Comment by omm** [comment]
Thanks, waiting for bianry pakages for testing.

**Comment by omm** [comment]
Ok, tested on Version 2.0 beta Jan 29 2024 01:58:16 (64-bit), all fine. Thanks
