### ISSUE TITLE
open watcom win16 not generating EXE file

### ISSUE THREAD

**Issue by ghost** [open-watcom/open-watcom-v2#1219]
Hi

I installed open watcom win16 using winevdm (https://github.com/otya128/winevdm) on windows 10 64 bit. This should run the program fine.
But when doing a targets->make (which says "ready" at the statusbar at bottom) and then targets->run, I get this error

![afbeelding](https://github.com/open-watcom/open-watcom-v2/assets/156975202/44a56341-80a9-40fb-a452-72cc42f15f5d)

Is this a bug or how to correctly compile and run a program? No EXE seems to be built...
Is there a MS-DOS EXE used by open watcom win16 to compile or anything else? I know winevdm can't run DOS EXE files.

I used the following code example of Charles Petzold's book, which should be 100% correct.

[HELLOWIN.zip](https://github.com/open-watcom/open-watcom-v2/files/14087918/HELLOWIN.zip)

**Comment by jmalak** [comment]
I am sorry, but such configuration is not supported. No guarantie that it will work.
I am using on 64-bit Windows Virtual machine with Windows Xp with shared folder (32-bit/64-bit) for 16-bit DOS/windows development.

**Comment by jmalak** [comment]
I am using Oracle VirtualBox due to support for older Operating Systems (DOS, OS/2, 16-bit Windows,..)
