### ISSUE TITLE
Make of button.lib fails. Cannot find btnwin.obj

### ISSUE THREAD

**Issue by virgban** [open-watcom/open-watcom-v2#1221]
I downloaded latest CI watcom executable on Jan 29  at
https://github.com/open-watcom/open-watcom-v2/releases/tag/Current-build
to 
open-watcom-2_0-c-win-x64.ext
I installed then (fully) with changes to environment variables
I opened bld/idedemo/src/win32.wpj

The Make for the button target produces the following message in the log:
	%create button.lb1
	wlib -b -c -n -q -p=512 button.lib @button.lb1
	Error! Cannot find file ''btnwin.obj''

The folder src/win32 has
	button.lb1 has only : "+'btnwin.obj'"
	button.mk1 has (among other lines)
 		*wlib -b -c -n -q -p=512 button.lib @button.lb1
	btnwin.obj
	button.tgt

I got the same result from the Jan 28 build.
Did I find a bug here?

**Comment by jmalak** [comment]
Thank you for your bug report.
I will fix it ASAP.

**Comment by jmalak** [comment]
it was bug introduced previous change in OW librarian and it was related to old single quote filename quoting in IDE scripts that I modify IDE to use standard quoting instead of old quoting.
