### ISSUE TITLE
specify source file to run?

### ISSUE THREAD

**Issue by girl16bit** [open-watcom/open-watcom-v2#1224]
Hi

This is a question about win16 projects.
I edit my source file, save it and then do a 'make'.
But I have sometimes more then 1 source file having a WndProc (so those files are each separate programs) and I want to run a specific source file.
I can't find where in open watcom to specify which code file to run.
See screenshot: it always runs the first code file in the list, here SYSMETS1.C
How to make it run SYSMETS2.C and SYSMETS3.C ?
I don't want to remove/add source files all the time in the list just to be able to run another source file

![afbeelding](https://github.com/open-watcom/open-watcom-v2/assets/156975202/6f5fd1bc-6a13-49ab-9243-85c7b2ee056b)

**Comment by jmalak** [comment]
I think you do it wrong way. 
OW IDE is based on project file.
each project can have multiple target, by example multiple program or multiple platform.
You cannot base IDE project on source any way.
Simply create multiple targets (executable) and add source file to appropriate target.
You can use (share) same source file for multiple targets, you simply add it to appropriate target.

**Comment by jmalak** [comment]
as example of such project try in samples\win\mswin.wpj project

**Comment by jmalak** [comment]
this is link to information about OW [OW info](https://github.com/open-watcom/open-watcom-v2?tab=readme-ov-file#discuss-the-project-on-github-reddit-or-discord) other source is [OW documentation](https://github.com/open-watcom/open-watcom-v2/wiki/Open-Watcom-Documentation) or [OW Wiki](https://github.com/open-watcom/open-watcom-v2/wiki)
