### ISSUE TITLE
feature request: run compiled EXE using a specified program

### ISSUE THREAD

**Issue by ROMmonkey** [open-watcom/open-watcom-v2#1225]
Hi

I would like to run a compiled EXE for MS-DOS by using a DOS emulator like DOSBox, ... or running 16 bit windows EXE by using winevdm, ....
In order to do this, it could be useful to have an option (default turned off) that let you specifiy an external EXE (of the emulator) that will have the compiled EXE as command line argument.
So like this: dosbox.exe compiledexe.exe
With this option, we then can directly run EXEs that are not supported on the host platform by using an emulator.

It only needs to run an external EXE and give the compiled EXE as command line argument.
If we then "run" the EXE, it can automatically pass the compiled EXE to an emulator. 

I would LOVE this feature, since i'm now running the EXE manually (for not supported EXEs on my windows 10).
Are you interested to add this please?

**Comment by winspool** [comment]
Such a feature would also be great for using qemu as starter.

qemu has also support for a debugger interface,
to debug the program in the emulator,
but OpenWatcom does not support this debugger interface.

Wine has also a debugger interface.
winedbg can be used standalone or as a win32 backend for the debugger on the unix host.
but OpenWatcom does not support this debugger interface.
* winedbg can handle i386, x86_64, arm and arm64
* winedbg can act as a replacement for Dr. Watson
* winedbg can do much more..
wine License: LGPL

https://source.winehq.org/git/wine.git/tree/HEAD:/programs/winedbg
or on https://gitlab.winehq.org

**Comment by LowLevelMahn** [comment]
i dont get you both
you want a feature that allows the "compiler" to execute some abritary command line after compilation, or what?

**Comment by LowLevelMahn** [comment]
> > i dont get you both you want a feature that allows the "compiler" to execute some abritary command line after compilation, or what?
> 
> Instead of running the EXE with the operating system, you can choose any tool to run the EXE (e.g. emulator). This can add new ways of working with the EXE all from within open watcom because you can specify how to run the EXE.

still not clear - what tool/exe should call you program?

letting the compiler (executable) itself call an external program is complete waste of time
if you want to compile and run - and like me run even other programs before running to check output etc. - use a batch/shell file around the compilation - why should the compile itself invoke a program, just run your batch file

**Comment by jmalak** [comment]
Take into account that OW IDE is universal framework for handling wmake make files from GUI.
It works with some category of objects and rules (dependencies) all these are completely configurable.
IDE top object is "target" that anything is related to this target.
If you look on toolbar than here are run and debug buttons which handle what is defined by target and host.
If you look into IDE configuration files you will see how IDE is configured. It is strictly dependent model based on target. 

By default for running created executable is defined tool RUN

```
Tool RUN "User Application"
  Family Application
    CSwitch -1, x???d, "", "!Error Cannot run Linux target under DOS$", ON
    CSwitch -1, x???o, "", "!Error Cannot run Linux target under OS/2$", ON
    CSwitch -1, x???l, "", "!Error Cannot run Linux target under Netware$", ON
    CSwitch -1, x???n, "", "!Error Cannot run Linux target under Win32$", ON
    CSwitch -1, x???q, "", "!Error Cannot run Linux target under QNX$", ON
    CSwitch -1, x???w, "", "!Error Cannot run Linux target under Win16$", ON
rem make fullscreen an option where both windowed & fullscreen work
    CSwitch 0, oc?eo, RUN_fullscr, "!Fullscreen", OFF
    CSwitch 0, of?eo, RUN_fullscr, "!Fullscreen", ON
    CSwitch 0, ov?eo, RUN_fullscr, "!Fullscreen", OFF
    CSwitch 0, d??eo, RUN_fullscr, "!Fullscreen", ON
    CSwitch -1, dr2e?, "", $(%watcom)\binw\dos4gw, ON
    CSwitch -1, dw2e?, "", $(%watcom)\binw\cwstub, ON
rem Pharlap run386 must be in your path
    CSwitch -1, dp2e?, "", run386, ON
rem Pharlap TNT run386 must be in your path
    CSwitch -1, dt2e?, "", tnt, ON
    CSwitch -1, w?2eo, "", "!Fullscreen", ON
    CSwitch -1, ???eo, "",, ON
    CSwitch -1, ?????, "", $@, ON
    VSwitch 0, ?????, RUN_parms,,, ONE, REQ, ""
    SwitchText RUN_fullscr, "Fullscreen"
    SwitchText RUN_parms, "Application parameters:"
```
You can see that your requirement is standard functionality of IDE.
Here is define how to run executable for different target on each host.
You can simply define what you need.
For details you can read IDE programer configuration documentation in bld/ide/ide.doc where is basic description of all IDE objects.

**Comment by jmalak** [comment]
to define configuration is used five characters mask 'smpth' where each position is one dependency group.
first character in the mask 's' represent target OS.

By example all definition started with 'd' characters are definition used for DOS target

below is sample of target definitions.

```
rem  System abbreviations used here are five characters 'smpth' where
rem  's' is the target system
rem     d DOS
rem     o OS/2
rem     l Netware NLM
rem     n Windows NT
rem     q QNX
rem     r RDOS
rem     w Windows 3.x
rem     x Linux

```

**Comment by LowLevelMahn** [comment]
> This can add new ways of working with the EXE all from within open watcom because you can specify how to run the EXE.

is still don't know what you mean with "within open watcom" - do you mean the IDE or the compiler exe?
for the IDE this feature would be nice and is default in all other IDEs i know, but having the compiler executing some command is definitly not available in any compiler i know - for a reason, there are make, shell/batch scripts available and only-after-compile execution is only relevant for a very tiny small group of people - which can easily using a script or many other options

are we talking about the compiler exe or the IDE? you opened another Enhancement request for the IDE so i think you talk about the compiler executeable itself

**Comment by jmalak** [comment]
From the context it is clear, we are talking about IDE GUI.
Anyway no change is needed because you can add any switch or edit field or radio button or any hiden text to the RUN tool command line in dependency of for target groups and host system (5 group).

**Comment by LowLevelMahn** [comment]
> From the context it is clear, we are talking about IDE GUI.

so "Compiler" and "Open Watcom" means IDE here

**Comment by jmalak** [comment]
I understand it was not expressed exactly, but it is only OW tool to which can be applied.
Otherwise it has no sense because from command line it can be run by script as you mention before.

**Comment by jmalak** [comment]
If you read comments carefully then you understand that we give you necessary info how you can do it.
It is custom solution because it is specific for you. It is not general solution.

**Comment by ROMmonkey** [comment]
FUCK YOU
