### ISSUE TITLE
question: include files

### ISSUE THREAD

**Issue by ghost** [open-watcom/open-watcom-v2#1231]
Hi

I use open watcom to compile a 16 bit windows program.
Can you tell me where the include files used for 16 bit windows EXE can be found (like windows.h, ...)?

**Comment by jmalak** [comment]
header files for 16/32-bit Windows 3.x application are located in h/win subdirectory (Windows specific).
Standard C/C++ header are in h subdirectory.

**Comment by jmalak** [comment]
For NT target default is version 4.0
```
/* Define default Windows version number. */
#ifndef WINVER
    #define WINVER  0x0400
#endif
```

For 16-bit Windows default is version 3.10
```
/* Define default Windows version number. */
#ifndef WINVER
    #define WINVER  0x030A
#endif
```

If you need different version then you need setup what you want by appropriate Windows macros

**Comment by jmalak** [comment]
OW doesn't contains any Windows API documentation you need to use MS SDK.
