### ISSUE TITLE
feature request: new run button for a target

### ISSUE THREAD

**Issue by ROMmonkey** [open-watcom/open-watcom-v2#1234]
Hi

Is there a way in the current version of OW to click a button that builds the changed code files and runs them?
We now have to do 'make' first and then 'run' but modern compilers combine both in 1 button. For example clicking 'debug' in visual studio compiles all changed code files and runs it.

I would like to request this feature for a OW target.

**Comment by jmalak** [comment]
see issue #1225

**Comment by jmalak** [comment]
If you read comments carefully then you understand that we give you necessary info how you can do it.
It is custom solution because it is specific for you. It is not general solution.

**Comment by ROMmonkey** [comment]
FUCK YOU
