### ISSUE TITLE
When the WATCOM environment variable is set, OpenWatcom should use it for the default Include path

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1237]
It is anoying, that OpenWatcom fails always to find the own includes,
without require the user to set lots of *INCLUDE environment variables.
(I usually use `owcc`, but the same issue exists when i try to use `wcl386`)

Yes, I Know, that I can set LINUX_INCLUDE, (and NT_INCLUDE, and DOS_INCLUDE and ...)
but for building OpenWatcom, i was told to not use these variables,
so i removed them from my system.

Other Compiler work without setting any environment variable.
OpenWatcom can work with setting only $WATCOM, when this issue is fixed.

As a real world example, i used zycore-c with wcl386, but that fails:
```
<somewhere>/zycore-c/include/Zycore/Defines.h(278): Error! E1055: Unable to open 'assert.h'
<somewhere>/zycore-c/include/Zycore/Types.h(214): Error! E1055: Unable to open 'stdint.h'
<somewhere>/zycore-c/include/Zycore/Types.h(215): Error! E1055: Unable to open 'stddef.h'
``'

**Comment by winspool** [comment]
How do you specify the Include search Patch on your machine,
when compiling something with OpenWatcom?
* Do you use NT_INCLUDE and friends?
* or do you you use ' -i=%WATCOM%\h -i=%WATCOM%\h\nt", when compiling with wcl386?
* or do you set WCC386 / WPP386 and degrade OpenWatcom to a single target OS?

As example, when owcc is called with `-blinux' (or on linux without -b),
the result of $WATCOM/lh should be added to the default include search path.

Similar for a linux target using wcl386 with `-bcl=linux`
Or fixing the search path for a NT target using `owcc`: -I$WATCOM/h -I$WATCOM/h/nt#

**Comment by jmalak** [comment]
Sorry these options can have any value that it is nonsense.
What if you need no value?

**Comment by jmalak** [comment]
if you want to modify the behavior of owcc, you can change the specs.owc file as you like, but don't expect we modify OW for your personal needs and break backwards compatibility

**Comment by winspool** [comment]
> Anyway OW is simply setup by batch scripts to my need by WATCOM and INCLUDE environment variable.


You told me last spring, that the use of LINUX_INCLUDE
is the reason, that building of OpenWatcom breaks on my machine,
so i followed your advice and removed all setting of *INCLUDE.

Now you tell me, that you use *INCLUDE yourself.....

OK,  i follow that now and hope for the best.

**Comment by jmalak** [comment]
If you don't read documentation and use environment variables incorrectly then you have incorrect result.
But it is not OW problem as you like to say always if you have a problem.
