### ISSUE TITLE
The documentation has 2 different versions of the trap file interface documentation, both are without Linux infos.

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1238]
The "Open Watcom Debugger Trap File Interface" documentation in trap.pdf is version 17.1,
but the documentation of the "Debugger Trap File Interface" in wddoc.pdf is only version 1.3".

How Trap files work under Linux is missing in both versions.

**Comment by jmalak** [comment]
it is two different documentation therefore they have different number.
Trap file interface is OS independent interface.

**Comment by winspool** [comment]
> it is two different documents therefore they have different number. 

I see, that they are different, that's why i created this issue.
Example from the ToC:
* The number of entries in Section 3.10.* is different.
* In section 4, the dots at the end of the Names have changed

The result of TrapInit and the data for REQ_CONNECT have different documented versions,
but i didn't looked at the details in the documentation of each request yet.


> Trap file interface is OS independent interface. 

There is a short OS specific part in the documentation in section 4,
but there is no OS specific part for Linux.
Since OpenWatcom cannot create shared ELF objects yet and x86_64-linux files build by gcc
are shared ELF objects, what do you think about mark a Linux entry as experimental?


> Anyway trap.pdf is not part of OW that I cannot say what it is.

I can help you here.
trap.pdf (and trap.html) are from the OpenWatcom Online Documentation
(downloaded yesterday, last update was 3 years ago):
https://github.com/open-watcom/open-watcom-v2-wikidocs/blob/master/docs/trap.pdf

I found the documentation without REQ_CAPABILITIES_GET_8B_BP (and REQ_CAPABILITIES_SET_8B_BP) in
https://github.com/open-watcom/open-watcom-v2/blob/master/bld/wv/doc/trap.gml

"wtrap.gml" sets trp_majver to 17 and trp_minver to 1 before including the file "trap"
This might be the way, where trap.pdf/trap.html have been created
(I have only a browser here and no git tree, so a grep is not possible a.t.m.)

"trap.pdf" and "trap.html" are probably old build artefacts.
As one part of fixing this issue, i will send a patch to remove both files,
when i'm back at my OW tree.


> There is difference between documentation version and internal TRAP version.
> Documentation version is 1.3 and current internal version is 18.0.
> Internal version is changed when important fix or change is applied.

Having wrong values in the documentation is strange,
since the internal version is part of TrapInit and REQ_CONNECT
(i have not searched for more locations).

That about splitting trp_majver/trp_minver to
trp_docmajver/trp_docminver and trp_apimajver/trp_apiminver 
(or whatever name you like, probably without the "ver" suffix)?

**Comment by winspool** [comment]
> old incorrect files trap.html and trap.pdf were removed, 

OK, thanks.


> Anyway I don't understand what you want to achieve.

I read the docs to better understand, how everything works
("trap.pdf" was one of the smaller files.)
and found the difference.

> Such info related to OS is only for information but has no big value, formats are not part of specification.

Those infos helps to understand, how OW works.
Short entries for 6 OS are available, but an entry for Linux is missing.

> You can use any executable format which you want and which is supported by TRAP loaders.
> There are loaders for appropriate formats

It's a clever design and i will try to reuse it later.


> This documentation is not for users but for developers which understand OW debugger and TRAP interface and modules.

I want to better understand, how this works.
That's why i fully read the docs.


> I have no time to do it more readable and perfect. You can improve it if you think that it is necessary.
> But without appropriate knowledge it is hard.

I have to study the source deeply to prepare a correct patch.
That will need some time.

> If you are interrested in loading TRAP for each OS see bld/dig proje where is approprate code for DIP/MAD/TRAP module loaders but it has nothing to do with this specification.

Thanks, this info helps me.

**Comment by winspool** [comment]
Thanks for the details.
I need to remember these infos and look at it more often.
