### ISSUE TITLE
strange warning "comparison result always 1" 

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [open-watcom/open-watcom-v2#1240]
this simple test code always gives warning "comparison result always 1" ( version 02/2024 ):

```
#include <stdio.h>

void VDMA_Write( unsigned short port )
{
    if(( port >= 0x00 && port <= 0x07 ) || ( port >= 0xC0 && port <= 0xCE )) {   // <---- warning about this line
       printf("gotcha! port=%X\n", port);
    }
}
int main( int argc, char * *argv )
{
    VDMA_Write( 0 );
    VDMA_Write( 0x20 );
    return 0;
}
```
cmd used to compile
```
\ow20\binnt\wcc386 -q -I\ow20\h vdma.c
```

The generated code is correct, though.

**Comment by jmalak** [comment]
Thanks for your problem report.
I checked compiler processing and it is reported for first condition **`port >= 0`** which is always true.
    if((   -->> port >= 0x00 <<--  && port <= 0x07 ) || ( port >= 0xC0 && port <= 0xCE )) {   // <---- warning about this line
The same is reported by OW 1.9 compiler.
It looks like surprising message but it is correct.

**Comment by Baron-von-Riedesel** [comment]
Ah yes, I see.
with a typecast to a signed short before 'port' I got rid of the warning.
Thanks!
