### ISSUE TITLE
Possibility to suppress a wlink warning?

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [open-watcom/open-watcom-v2#1255]
Hello,

is it somehow possible to suppress a wlink warning? I'd like to suppress warning 1080 ( "xxxx is a 32-bit module") when linking a "format DOS" binary. Since my DOS binary consists almost 100% of 32-bit modules (including modules from clib3s), I get some dozens of those warnings during the link step.

The hack to use the "raw" format instead of "dos" is not feasible in this case, since I need at least one DGROUP segment fixup

The resulting binary is fine, btw.

**Comment by jmalak** [comment]
Yes, it is possible by directive [DISABLE](https://open-watcom.github.io/open-watcom-v2-wikidocs/lguide.html#The_DISABLE_Directive) message_num

**Comment by Baron-von-Riedesel** [comment]
Yes, it works! Thanks!
