### ISSUE TITLE
Incorrectly initialized bit fields in structure

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#1262]
Creating a struct that uses packed bit fields does not match the C specification with differently sized types. For example:

```C
#include <stdio.h>

typedef struct key key;

struct key {
  struct {
    unsigned char type : 2;
    unsigned short row : 12;
  };
};

#define MAX_ROW (4*60*60/8)

typedef enum {
  STEP = 0,
  SMOOTH = 1,
  LINEAR = 2,
  RAMP = 3,
} simp_type;

static char *TYPE_STR[] = {
  "STEP", "SMOOTH", "LINEAR", "RAMP",
};

key keys[] = {
   { .row = MAX_ROW, .type = RAMP },
};

int main() {
  printf("sizeof(key) = %i\r\n", sizeof(key));
  printf("keys[0] = { .row = %3i, .type = %s }\r\n",
   keys[0].row, TYPE_STR[keys[0].type]);
  printf("%04x", *(int *)&keys[0]);
}
```

when built with `Version 2.0 beta Mar  1 2024 01:51:55 (64-bit)` prints the output:

```
sizeof(key) = 4
keys[0] = { .row = 1800, .type = RAMP }
7080003
```

However building with `gcc -m32 keys.c -o keys` gives the following output:

```
$ ./keys
sizeof(key) = 2
keys[0] = { .row = 1800, .type = RAMP }
1c23
```

**Comment by jmalak** [comment]
For which standard?
Do you thing that gcc in default mode follow standard?
Anyway key struct is invalid by C90 standard.
Both compilers are using some extension and default pack size which is not same.
What command line you use for OW compiler and what target.

**Comment by jmalak** [comment]
If you want bits be packed use same type as

struct key {
  struct {
    unsigned short type : 2;
    unsigned short row : 12;
  };
};

**Comment by negge** [comment]
> If you want bits be packed by OW as by gcc then use same type as
> 
> struct key { struct { unsigned short type : 2; unsigned short row : 12; }; };

Thank you, I modified the example for both fields as `short` and the bit layout is now correct. However, I am still seeing strange things in the initializer. Code is now:

```C
#include <stdio.h>

typedef struct key key;

struct key {
  struct {
    unsigned short type : 2;
    unsigned short row : 12;
  };
};

#define MAX_ROW (4*60*60/8)

typedef enum {
  STEP = 0,
  SMOOTH = 1,
  LINEAR = 2,
  RAMP = 3,
} simp_type;

static char *TYPE_STR[] = {
  "STEP", "SMOOTH", "LINEAR", "RAMP",
};

key keys[] = {
   { .row = MAX_ROW, .type = RAMP },
};

int main() {
  printf("sizeof(key) = %i\r\n", sizeof(key));
  printf("keys[0] = { .row = %3i, .type = %s }\r\n",
   keys[0].row, TYPE_STR[keys[0].type]);
  printf("%04x\r\n", *(int *)&keys[0]);
  /* set values again */
  keys[0].row = MAX_ROW;
  keys[0].type = RAMP;
  printf("keys[0] = { .row = %3i, .type = %s }\r\n",
   keys[0].row, TYPE_STR[keys[0].type]);
  printf("%04x", *(int *)&keys[0]);
}
```

Now prints out:

```
sizeof(key) = 2
keys[0] = { .row =   0, .type = RAMP }
0003
keys[0] = { .row = 1800, .type = RAMP }
1c23
```

But `gcc -m32 keys.c -o keys` gives the output:

```
$ ./keys
sizeof(key) = 2
keys[0] = { .row = 1800, .type = RAMP }
1c23
keys[0] = { .row = 1800, .type = RAMP }
1c23
```

**Comment by jmalak** [comment]
It looks like bug in static initialization of bit fields.

**Comment by jmalak** [comment]
#1283

**Comment by jmalak** [comment]
It is bug in internal bitfield processing. 
order of bitfields mismatch during structure definition and initialization.
