### ISSUE TITLE
wrc has trouble compiling resources for OS/2 2.x (cross-build on Linux)

### ISSUE THREAD

**Issue by vain** [open-watcom/open-watcom-v2#1269]
I have a “minimal” reproducer over here:

https://github.com/vain/open-watcom-os2-resource-issue

It’s a short GUI program for OS/2 2.x. It is supposed to show a blank window with a menu bar. When you click the item in the menu bar, it is supposed to show a dialog window:

https://github.com/vain/open-watcom-os2-resource-issue/blob/main/hello.c

Both the menu and the dialog are defined in a resource file:

https://github.com/vain/open-watcom-os2-resource-issue/blob/main/hello.rc

I build the whole thing with two commands on Linux:

```
owcc -Wall -Wextra -bos2v2_pm -o hello.exe hello.c
wrc -bt=os2 -zku8 hello.rc
```

Neither `owcc` nor `wrc` prints warnings or error messages.

Now, I realize that this might be hard to debug or reproduce, because the issue only shows up when you actually run the resulting `hello.exe` under OS/2: The program starts, displays the window including the menu. Upon clicking the menu item, nothing happens under OS/2 Warp 4 (`WinDlgBox()` returns `DID_ERROR`) and the program crashes under OS/2 2.1. Screenshot of the crash in my repo. (I realize that the screenshots are in German. If it is valuable to you, I’ll happily translate them.)

I’m using the [2024-04-01-Build](https://github.com/open-watcom/open-watcom-v2/releases/tag/2024-04-01-Build) on Arch Linux.

* * * *

For comparison: The same resource file (with a minor, hopefully unrelated adjustment) works when using tools from Borland C++ 2.0 for OS/2.

1.  Build `hello.exe` without resources on Linux using Open Watcom, i.e. only run the `owcc …` command.
2.  Remove the `#include <os2.h>` line from `hello.rc`.
3.  Copy everything to an OS/2 box and use Borland’s “Resource Workshop” to attach the resources from `hello.rc` to the `hello.exe` built by Open Watcom.
4.  It works, the dialog shows up.

(Some more details in the `README.md` of my repo.)

My repo includes the binary artifacts (Open Watcom builds, Borland build).

* * * *

Any help is appreciated. It’s quite possible that this is a user error, I’m still new to this.

Thank you!

**Comment by jmalak** [comment]
It looks like bug in wrc.
Please, could you put here hello.res created by OW wrc and hello.res created by Borland C++ resource compiler.

**Comment by jmalak** [comment]
Many Thanks for samples.

I found out one mistake introduced during resource compiler migration to 64-bit compatible code. It is related to OS/2 FONT and FONTDIR resources, it is not fix for your issue.

**Comment by jmalak** [comment]
Definitely it is bug in OW resource compiler in dialog processing, menu resource is unaffected.

**Comment by vain** [comment]
Yep, it works! Tested on OS/2 2.1, Warp 3 and 4.

Thank you very much. :)

**Comment by jmalak** [comment]
You are welcome.
