### ISSUE TITLE
Where to download older OpenWatcom v2 releases?

### ISSUE THREAD

**Issue by pts** [open-watcom/open-watcom-v2#1279]
I the oldest I was able to find is https://github.com/open-watcom/open-watcom-v2/releases/tag/2020-09-08-Build . Is there something earlier available for download? I know about OpenWatcom 1.9 (2010-05-25). Is there something in-between?

I'm asking because I'm testing compilation of some programs, and I'd like to know the earliest OpenWatcom version which can compile them correctly. OpenWatcom 1.9 WLINK produces incorrect output for some of the tests, OpenWatcom v2 2020-09-08 is correct. I'd like to bisect further.

**Comment by jmalak** [comment]
I am affraid no older release is available. You need to compile it from source.
What kind of problem you have?
