### ISSUE TITLE
wmake copy command regression

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#1281]
The command `  @copy "../SDL2.dll" .` in wmake is no longer working
under windows. The following's from one of our github actions runs:

```
The system cannot find the file specified.
        0 file(s) copied.
Error(E42): Last command making (check-quick) returned a bad status
Error(E02): Make execution terminated
```

It used to work before. Changing the command to `@copy ..\SDL2.dll .`
is the only way of making it work for now.

(Is https://github.com/open-watcom/open-watcom-v2/commit/21e47752700a252efabf336525a4ead69265ce3e possibly responsible?)

**Comment by jmalak** [comment]
Please use %copy instead of copy.
It was changed that copy works the same way as with OW 1.9 and OW 2.0 copy was implemented as %copy internal command.
Functionality is exactly same as copy before.
I am sorry for this trouble.

**Comment by sezero** [comment]
OK, updated our makefiles, and `  @%copy "../SDL2.dll" .` does work. Thanks.

Closing this ticket.
