### ISSUE TITLE
Create LST file from wlink

### ISSUE THREAD

**Issue by headscott** [open-watcom/open-watcom-v2#1289]
Hi,
I want to get a .LST file (assembly code used for debugging) from your wlink. But I can't find out how I can do that, or if it is even possible.
Can someone tell me how or if I can do that? Thanks in advance :)

**Comment by jmalak** [comment]
I don't understand what you want to achive.
wlink tool is linker which doesn't know anything about such info, simply link multiple modules together and create executable.
What you mean assembly code for debugging?
Debugger works with executable file in binary form (CPU instructions) not with any list of assembly code.
If you need assembly code then you need disassembly executable.
It is not task for linker but for specialize tools for reverse engineering.

**Comment by headscott** [comment]
See here [IBM - Explanation of List Files](https://www.ibm.com/docs/en/aix/7.2?topic=files-understanding-compiler-list-file)

Maybe I did not fully understand how that works. I thought the Linker can only create LST files, because it knows how the executable will look like. And a LST file is useful for debugging your code (see here: [Stackoverflow - LST File](https://stackoverflow.com/questions/1131228/list-file-in-c-lst). I've seen a .LST file from an old project where all contents of all related files were put together, and could be used by a debugger to see the assembly instruction currently beeing run. So I thought the linker should create it.

**Comment by jmalak** [comment]
Sorry, we are not IBM tools.
Read [documentation for Open Watcom](https://github.com/open-watcom/open-watcom-v2/wiki/Open-Watcom-Documentation)

**Comment by jmalak** [comment]
It looks like you need linker MAP file.
You can get it if you add "opt map" directive to wlink command.

**Comment by headscott** [comment]
Yeah, I think I missunderstood something here. I found out that I can create small .lst files for every single c code and assembly code. Maybe there was an external tool that created the bigger one for debbuging use I found. Sorry for taking your time. I will inquire further

**Comment by jmalak** [comment]
If you want disassembly some compiled module (object file) then you can used wdis tool.
wdis tool dissasembly only single object file to assembler source form but not full executable.

**Comment by headscott** [comment]
I've another idea how I could fix my problem without the need of a .lst file: how do I get wcc386? If I run wcl386.exe for my c-code it says "Error: Unable to find "wcc386.exe""

**Comment by jmalak** [comment]
It looks like you have not installed OW properly.
You need setup WATCOM environment variable to point to path where OW is installed.
next yuo need to add host OW binary subdirectory to PATH. By example you are on Linux then you need to add to PATH
export PATH=$WATCOM/binl:$PATH
next you need to setup INCLUDE environment to point to header files for target platform, by default for Linux target
export INCLUDE=$WATCOM/lh
you can create some script to setup it all togather.
[OW tools usage](https://github.com/open-watcom/open-watcom-v2/wiki/OW-tools-usage-Overview)

**Comment by headscott** [comment]
Okay, I used the wrong installation .exe file for my system... my fault. Now it works fine
