### ISSUE TITLE
Problem with $ in assembly when linking object files

### ISSUE THREAD

**Issue by headscott** [open-watcom/open-watcom-v2#1290]
I wrote some code in Intel assembly notation and used ml to create a object file (until here, there was no problem/error). 

The assembly code contains these lines:

```
...
org 80h
CmdString EQU $
...
```

I am using this to copy a command string to an given adress in the resulting executable. This exact code worked with an very old linker from Phar Laps (386LINK from 1986-91). If I do the same code but link the object files from my compiler with wlink (and the format PHAR EXT flag), it doesn't work like that. Is it a bug from wlink? Or is there a similar way to do that, but without that problem?

**Comment by jmalak** [comment]
you are talking about linker, but it is task for assembler (WASM)
$ is placeholder for current address and it is calculated by WASM if it is used
Why you don't use
CmdString EQU 80h

**Comment by headscott** [comment]
Because I would have to care for multiple lines if I don't use $ and org together. This could lead to more problems. But probably its a bug/false use of options of my assembler ml

**Comment by jmalak** [comment]
I don't think it is bug.
Our assembler works with $ as placeholder for current offset which is evaluated when it is used for instruction generation.

**Comment by jmalak** [comment]
No problem. 
WASM is little specific and is rather as MASM 5 with more features from MASM 6.
It is also specific how EQU is implemented in WASM not fully compatible with MASM.
