### ISSUE TITLE
win-x86 build will not run on NT 4.0 SP6

### ISSUE THREAD

**Issue by HnkGitHub** [open-watcom/open-watcom-v2#1291]
Build: Git build from 5/15/24 built on Windows 10 Pro, 64-bit

All the releases built. The win-x86 installer worked without a 
hitch on Windows NT 4.0 SP6: IBM Aptiva, 256MB, AMD K6-200.

But the command line tools fail to work: "Program too big to fit into
memory." And the 32-bit IDE.exe will not even appear on the screen.

The 64-bit build appears to work in Windows 10 with the command line tools and the
IDE. Just did a few simple tests. Compiled a 32-bit hello, world and a 16-bit
hello, world which ran fine in Dos.

It's just that the tools now fail to work at all on a 32-bit NT4 OS.
This wasn't happening a few months ago.

Regards,

Hank

**Comment by jmalak** [comment]
I am sorry, I understand only that ide.exe is not running on NT 4.0.
Do you build your own version or use installer from Github?
Does other OW tools work on NT 4.0 or compiled executable on NT 4.0 doesn't work?
Did you check OW command line tools as compiler/librarian/linker on NT 4.0?

**Comment by HnkGitHub** [comment]
I built the installer on Windows 10 Pro from Github: win-x86.exe installer. Everything built without
Error on Windows 10. I changed into the bld directory and ran builder rel

Using the selective install option, I chose NT 4.0 as the host. And I chose the targets as DOS,
Windows 32/Win32S/NT.

When the open-watcom-v2 ide wouldn't work in NT 4.0, I did a full installation. And still had the
Same problems.

I tried the ide.exe for win32, wcl386, wcc386, wcl, and wcc. None of these commands ran. I increased
The extended memory by changing the default pif, but still had the same results.

When I ran the ide from the command line the command prompt left an error message stating that
The program was too big to fit into memory.

________________________________

**Comment by jmalak** [comment]
Do you have properly setup environment variables WATCOM, PATH and INCLUDE on NT 4.0 system?

**Comment by HnkGitHub** [comment]
I think the problem is in the Visual C compiler and linker. Just a guess.

But I compiled the full release in wine on Debian Linux 64 using watcom19 to build everything, documentation, distribution binaries, etc...

Using winx86 installer built by openwatcom environment, the installer ran correctly and everything appears to be working.

I think Microsoft has put some code in to prevent their exes from running on older windows versions. They started doing this with Visual Studio 2008, I believe.

Anyway, open-watcom-v2 is alive and running on NT4 SP6.
________________________________

**Comment by jmalak** [comment]
Be careful, on 32-bit host you can use only Open Watcom toolchain (1.9 or 2.0) to build Open Watcom as documented in Wiki.

```
                    building OW for...     building OW for...    prerequisite
build OS            16/32-bit hosts        64-bit hosts          software
------------------------------------------------------------------------------
DOS                 OW                     -                     -
OS/2                OW                     -                     -
Windows 32-bit      OW                     -                     -
Windows 64-bit      OW*                    VC++, Intel           DOSBOX
Linux x86 32-bit    OW                     -                     DOSBOX
Linux x64 64-bit    OW*                    gcc, clang            DOSBOX

Experimental, not supported
POSIX(only build)   gcc, clang             gcc, clang            DOSBOX

* Using 32 bit OW on the 64 bit operating system.
```

Microsoft compilers is used to build 64-bit version only on 64-bit Windows.
The same for Linux.
