### ISSUE TITLE
Trailing vs leading _ when linking object files from wcc386 and microsoft assembler ml

### ISSUE THREAD

**Issue by headscott** [open-watcom/open-watcom-v2#1294]
I've got some object files generated by ml (Microsoft Assembler). And I got some c files which uses functions from the original assembly files, where the pre-generated object files come from. 

So for example in my test. c file there is a line:

`ASM_Test();`

this one is defined as

`extern void ASM_Test();`

at the top of the c file.

Now there is a function in my _test.asm file:

```
PUBLIC _ASM_Test

ASM_Test_:
   RET
```

Because other compilers got the convention to add a leading _ to function calls. If I add object files of my assembly codes and my c codes to wcl386, there are many unresolved symbol/ unresolved reference errors, because wcl386 adds trailing _ to all function calls and would search for "ASM_TEST_" instead of "_ASM_TEST".
Yes, probably I could change my namings inside my assembly files. But this would be very time consuming due to the many files I got. Is there an option in wcc386/wcl386 to add leading _ instead of trailing _ when compling c files?

**Comment by jmalak** [comment]
You need follow rules for [assembly interface with C in OW documentation](https://open-watcom.github.io/open-watcom-v2-wikidocs/cguide.html#16Mbit__Assembly_Language_Considerations)
