### ISSUE TITLE
Pharlap Extender executable .exp file: why is the checksum always 0 and why is at 0x200 position something

### ISSUE THREAD

**Issue by headscott** [open-watcom/open-watcom-v2#1300]
I wondered why the checksum at position 0x0A is always 0 after linking my compiled files with wlink. 

And I found out, that at position 0x200, there is this:

`CC EB FD 90 90 90 90 90 90 90 90 90 90 90 90 90`

is it possible with options that this line is removed? And what is it even for?

Comparing to 386LINK this line doesn't even exist. At 0x200 there is the line which is at 0x210 in your executable file. And the checksum is not 0 there.

**Comment by jmalak** [comment]
The OW linker not calculate checksum, because it is not required value.
The OW linker use [DOS memory layout](https://open-watcom.github.io/open-watcom-v2-wikidocs/lguide.html#DOS__Memory_Layout) by default for executable.
386LINK order segment differently or you use incorrect options.

**Comment by headscott** [comment]
I could not find out anything about it right now. I used `wdump test.exp -q -s | more` to just print up to the first few lines of segments for both executables. But the only information I get is still, that the .exp file created by wlink or wcl386 has the "CC E8 FD 90 90 ..." line, but the .exp file from 386LINK does not have it.

It seems like a placeholder for something, because CC is INT 3 (Interrupt 3) and E8 FD is a jump to a local address and 90 is nop (No operation). Also ifI use the `-"option eliminate"` option, it's still there.

**Comment by headscott** [comment]
I tried this:

```
wcc386 test.c -ob -oc -s -fo=test.obj -zq
wlink file test.obj library C:\WATCOM\lib386\dos\clib3r.lib option ELIMINATE OPTION NOD format PHAR EXT name test.exp option quiet
```

And I tried this:

`wcl386 test.c -bt=dos -l=pharlapext -fe=test.exp -fm=test.map -"option eliminate" -zq -ob -oc -s`

But for the second command I used your recommendation from here: #1295 

And for CC386W I used this command:

`CC386W test,c`

When I link the obj created by wcc386 with the wlink command mentioned, I get the "CC ..." line, if I do the exact same command but with the object file created by CC386W, this line is not inside the executable. 

And yes, the executable from created by Open Watcom does not run in my environment because the program jumps into this CC E8 FD 90 ... loop and stays there forever instead of running my code. The one created by CC386W does work. I am not sure if there is maybe also a problem with the execution environment. Maybe it uses different assumptions on how the executable should look like.

**Comment by jmalak** [comment]
Please I need compare headers of executable files get by wdump utility and next I need *.map files generated by linker in both cases.

**Comment by headscott** [comment]
This is from the test.exp file created by 386LINK:

```
wdump test.exp -s
Open Watcom Executable Image Dump Utility
Version 2.0 beta May 20 2024 02:13:19 (64-bit)
Copyright (c) 2002-2024 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.

                         Pharlap EXE Extended Header
==============================================================================
file format level (1==flat, 2==multi-seg) =     0001H
header size in bytes                      =     0180H
file size in bytes                        = 00000210H
16-bit checksum                           =     74F1H
offset of run-time parameter block        = 00000180H
size of run-time parameter block          = 00000080H
offset of relocation table                = 00000200H
size of relocation table                  = 00000000H
offset of segment information table       = 00000000H
size of segment information table         = 00000000H
size of a seg info table entry            =     0000H
offset of program load image              = 00000200H
size of program load image                = 00000010H
offset of symbol table                    = 00000000H
size of symbol table                      = 00000000H
offset of program GDT in load image       = 00000000H
size of program GDT in load image         = 00000000H
offset of program LDT in load image       = 00000000H
size of program LDT in load image         = 00000000H
offset of program IDT in load image       = 00000000H
size of program IDT in load image         = 00000000H
offset of program TSS in load image       = 00000000H
size of program TSS in load image         = 00000000H
minmum number of extra bytes to allocate  = 00000000H
maxmum number of extra bytes to allocate  = FFFFFFFFH
base offset of program image              = 00000000H
initial ESP                               = 00000000H
initial SS                                =     0000H
initial EIP                               = 00000000H
initial CS                                =     0000H
initial LDT                               =     0000H
initial TSS                               =     0000H
load image flags                          =     0000H
load image memory requirement             = 00000010H

                           Run-time Parameter Block
==============================================================================
-MINREAL   switch value                   =     0000H
-MAXREAL   switch value                   =     0000H
-MINIBUF   switch value                   =     0001H
-MAXIBUF   switch value                   =     0010H
-NISTACK   switch value                   =     0006H
-ISTKSIZE  switch value                   =     0001H
-REALBREAK switch value                   = 00000000H
-CALLBUFS  switch value                   =     0000H
386 DOS extender flags                    =     0000H
unpriviledged flag                        =     0001H


                                   Segments
==============================================================================
0000:  B8 00 00 00 00 C3 8D A4  24 00 00 00 00 8D 49 00            $     I
```

And the content of the map file:

```
386|LINK: 4.1 -- Copyright (C) 1986-91 Phar Lap Software, Inc.
Target CPU is 80386


Command line switches:

@test.lnk
bin\test
-twocase
-fullseg
-mapnames 18
-lib bin\cldosml
-EXE test
-MAP test


Input module(s):

"TEST" from file "bin\test.obj".


Segment map

     Name            Offset
------------        --------
DATA                00000000  
CONST               00000000  
STACK               00000000  
CODEC32             00000000  
  TEST              00000000  


Public symbols

     Name             Value      Module              Segment            Size
------------        --------  ------------        ------------        --------
_main               00000000  TEST                CODEC32             
```

And this is from the test.exp file created by wcc386 and wlink with the options mentioned above. (But I removed option eliminate from wlink, because in this minimal example I created the "CC ..." line was removed, but when I used option eliminate in my bigger project it was still there:

```
wdump test.exp -s
Open Watcom Executable Image Dump Utility
Version 2.0 beta May 20 2024 02:13:19 (64-bit)
Copyright (c) 2002-2024 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.

                         Pharlap EXE Extended Header
==============================================================================
file format level (1==flat, 2==multi-seg) =     0001H
header size in bytes                      =     0180H
file size in bytes                        = 00000778H
16-bit checksum                           =     0000H
offset of run-time parameter block        = 00000180H
size of run-time parameter block          = 00000080H
offset of relocation table                = 00000180H
size of relocation table                  = 00000000H
offset of segment information table       = 00000000H
size of segment information table         = 00000000H
size of a seg info table entry            =     0000H
offset of program load image              = 00000200H
size of program load image                = 00000578H
offset of symbol table                    = 00000000H
size of symbol table                      = 00000000H
offset of program GDT in load image       = 00000000H
size of program GDT in load image         = 00000000H
offset of program LDT in load image       = 00000000H
size of program LDT in load image         = 00000000H
offset of program IDT in load image       = 00000000H
size of program IDT in load image         = 00000000H
offset of program TSS in load image       = 00000000H
size of program TSS in load image         = 00000000H
minmum number of extra bytes to allocate  = 00010008H
maxmum number of extra bytes to allocate  = FFFFFFFFH
base offset of program image              = 00000000H
initial ESP                               = 00010580H
initial SS                                =     0000H
initial EIP                               = 00000014H
initial CS                                =     0000H
initial LDT                               =     0000H
initial TSS                               =     0000H
load image flags                          =     0000H
load image memory requirement             = 00000578H

                           Run-time Parameter Block
==============================================================================
-MINREAL   switch value                   =     0000H
-MAXREAL   switch value                   =     0000H
-MINIBUF   switch value                   =     0001H
-MAXIBUF   switch value                   =     0004H
-NISTACK   switch value                   =     0004H
-ISTKSIZE  switch value                   =     0001H
-REALBREAK switch value                   = 00000000H
-CALLBUFS  switch value                   =     0000H
386 DOS extender flags                    =     0000H
unpriviledged flag                        =     0000H


                                   Segments
==============================================================================
0000:  CC EB FD 90 90 90 90 90  90 90 90 90 90 90 90 90
0010:  31 C0 C3 00 EB 12 57 41  54 43 4F 4D 00 63 6F 6E    1     WATCOM con
0020:  00 0D 0A 90 03 00 00 00  FB 83 E4 FC 8B DC 89 1D
0030:  40 05 00 00 89 1D 2C 05  00 00 66 B8 24 00 66 A3    @     ,   f $ f
..... <and many more lines>
```

And the content of the .map file:
```

Open Watcom Linker Version 2.0 beta May 20 2024 02:01:23 (64-bit)
Copyright (c) 2002-2024 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
Created on:       24/06/03 14:26:28
Executable Image: test.exp
creating a Phar Lap extended executable


                        +------------+
                        |   Groups   |
                        +------------+

Group                           Address              Size
=====                           =======              ====

DGROUP                          00000520             00010060



                        +--------------+
                        |   Segments   |
                        +--------------+

Segment                Class          Group          Address         Size
=======                =====          =====          =======         ====

BEGTEXT                CODE           AUTO           00000000        00000010
_TEXT                  CODE           AUTO           00000010        00000506
_NULL                  BEGDATA        DGROUP         00000520        00000004
_AFTERNULL             BEGDATA        DGROUP         00000524        00000000
CONST                  DATA           DGROUP         00000524        00000000
CONST2                 DATA           DGROUP         00000524        00000000
_DATA                  DATA           DGROUP         00000524        00000054
TIB                    DATA           DGROUP         00000578        00000000
TI                     DATA           DGROUP         00000578        00000000
TIE                    DATA           DGROUP         00000578        00000000
XIB                    DATA           DGROUP         00000578        00000000
XI                     DATA           DGROUP         00000578        00000000
XIE                    DATA           DGROUP         00000578        00000000
YIB                    DATA           DGROUP         00000578        00000000
YI                     DATA           DGROUP         00000578        00000000
YIE                    DATA           DGROUP         00000578        00000000
DATA                   DATA           DGROUP         00000578        00000000
_BSS                   BSS            DGROUP         00000578        00000008
STACK                  STACK          DGROUP         00000580        00010000


                        +----------------+
                        |   Memory Map   |
                        +----------------+

* = unreferenced symbol
+ = symbol only referenced locally

Address        Symbol
=======        ======

Module: test.obj(C:\Users\Workstation\Documents\test.c)
00000010       main_
Module: C:\WATCOM\lib386\dos\clib3r.lib(cstart)
00000003*      ___begtext
00000520*      __nullarea
00000524*      __D16Infoseg
00000526*      __x386_zero_base_selector
00000014       _cstart_
0000020d       __exit_
00000210*      __do_exit_with_msg_
000002d8*      __GETDS
000002d8       ___GETDSStart_
000002e3       ___GETDSEnd_
Module: C:\WATCOM\lib386\dos\clib3r.lib(cmain386.c)
000002f0       __CMain
Module: C:\WATCOM\lib386\dos\clib3r.lib(initrtns.c)
00000340       __InitRtns
00000390       __FiniRtns
Module: C:\WATCOM\lib386\dos\clib3r.lib(dosseg)
00001234       __DOSseg__
Module: C:\WATCOM\lib386\dos\clib3r.lib(crwdata)
00000562       __osmajor
00000563       __osminor
00000530       __LpCmdLine
00000534       __LpPgmName
00000528       __dynend
0000052c       __curbrk
0000054c*      __cbyte
00000550*      __cbyte2
00000554       __child
0000055c       __Envptr
00000538       __psp
00000559       __Extender
0000055a       __ExtenderSubtype
0000055b*      __X32VM
0000053c*      __x386_stacklow
0000053c       __STACKLOW
00000540       __STACKTOP
00000544       __ASTACKSIZ
00000548       __ASTACKPTR
00000558       __no87
00000564       ___FPE_handler
Module: C:\WATCOM\lib386\dos\clib3r.lib(uselfn.c)
00000568       ___uselfn
Module: C:\WATCOM\lib386\dos\clib3r.lib(cinit.c)
000003f0       __CommonInit_
Module: C:\WATCOM\lib386\dos\clib3r.lib(___argc.c)
00000578       ____Argv
0000057c       ____Argc
Module: C:\WATCOM\lib386\dos\clib3r.lib(exit.c)
00000439+      __null_int23_exit_
0000043a       exit_
00000464*      _exit_
0000056c+      ___int23_exit
00000570+      ___FPE_handler_exit
Module: C:\WATCOM\lib386\dos\clib3r.lib(sgdef086)
00000578       __Start_XI
00000578       __End_XI
00000578       __Start_YI
00000578       __End_YI
Module: C:\WATCOM\lib386\dos\clib3r.lib(dpmihost.c)
00000480       __DPMI_hosted_


                        +--------------------+
                        |   Libraries Used   |
                        +--------------------+

C:\WATCOM\lib386\dos\clib3r.lib


                        +-----------------------+
                        |   Linker Statistics   |
                        +-----------------------+

Stack size:  00010000 (65536.)
Memory size:  00010580 (66944.)
Entry point address: 00000014
Link time: 00:00.10

```

**Comment by jmalak** [comment]
Thanks.

1. I don't understand why you want remove 16 byte of normaly unused code, this is part of OW run-time environment, has nothing to do with compiler, it is linked into executable by wlink with regards to OW DOS memory layout (BEGTEXT segment).
2. program entry point is at 0:14h for OW version, see to header value for CS:EIP and into map file that on address 14h is _cstart_ OW standard entry point
3. I suppose that you need to run .exp file under Pharlap Extender somehow, do you use it with OW version, probably Pharlap linker bind extender to executable

**Comment by headscott** [comment]
Thanks too :)

1. because it seems like the execution environment needs to have at position 0x200 what is at 0x210 because of the inserted "CC E8 FD 90 90 ..." . So it does not find it.
2. I will see if this help (unfortunately I won't be able to look at it until wednesday)
3. Okay, I will see
4. I tried a lot already and some combinations, but nothing was really helpful until now.

I have a debugger, but I am not sure if it is still anywhere available. Maybe I can find out more after adding these options:

`RUNTIME UNPRIV, MINIB=1k, MAXIB=16k, NIST=0x6`

**Comment by headscott** [comment]
Problem is: the execution environment searches at 0x200 for a name to put into a table where all executed programs are listed. The older compiler did not add these "Code NULL check" lines, so there was the correct name. Now it is added there, so all contents set by "org" in assembly are shifted by 16 Bytes. Where inside the executable can I see how much is added before the programm?

**Comment by jmalak** [comment]
I am not understanding what you say about execution environment.
Why need change, in executable header is specified start CS:EIP correctly.
Do you want to say that Pharlap loader ignore this and start always on 0x200?
It looks like nonsense because start of executable image start after header + all executable info, including relocation table etc. that need not start on 0x200 but after that.

**Comment by headscott** [comment]
The place where I run the code always looks at 0x200 for extra information which is set there by the "old" compiler/assembler/linker configuration (CC368W Version 2.40.6.0, ML Version 6.15.8803 and 386LINK Version 4.1), but due to the null pointer check it is shifted by 16 Bytes. I am not talking about startup code or location of the main method. And I think reason why there is a null pointer check in the current Watcom version is from compiling, not linking, but I am not sure.

**Comment by jmalak** [comment]
In this case you use you special format of executable image.
I cannot find any information about such Pharlap requirements.

**Comment by headscott** [comment]
But do you know in which compiling/linking process the null pointer check is added? Is it a flag set while compiling or is it set when linking? And why is it not there when I am using object files from gcc?

This is btw my whole test.c code:

```
int main(){
	return 0;
}

```

when I do 

`wcl386 test.c -bt=dos -l=pharlapext`

this is the content of the .exp file:

`50 33 01 00 80 01 .... 44 58 00 00 00 00 01 00 04 00 04 00 01 00 00 00 ... CC EB FD 90 90 90 90 90 90 90 90 90 90 90 90 90 68 04 00 00 00 E8 15 00 00 00 31 C0 C3 00 00 00 ....`

So null pointer check exists.

When I do this:

```
gcc -c test.c -o test.o
wlink file test.o format phar ext
```

`50 33 01 00 80 01 ... 44 58 00 00 00 00 01 00 04 00 04 00 01 00 00 00 ... 55 89 E5 B8 00 00 00 00 5D C3 90 90 90 90 90 90`

So here is no null pointer check, and the result is much smaller. 
Does the linker even support linking object files from gcc? Or is the missing check just due to linking errors/unpredictible behavior when linking these?

**Comment by jmalak** [comment]
You don't understand run-time environment.
Each toolchain has run-time environment and some specific ordering etc.
It is evident that you rely to some of them and expect that you can change it somehow by compiler options.
It is wrong assumption this way it doesn't work.
There can be a problem with segment ordering etc.
First you must specify your image layout because you expected some, but it is evident that it is not compatible with WATCOM layout.
The issue is with linking (linker create layout) and has nothing to do with compiler. I talked to you several times and you don't believe me.
I can not help you if you don't specify your executable image layout.

**Comment by headscott** [comment]
Your are right. I seem not to understand run-time environment here. I am sorry for taking your time, but I think even though I am still not sure exactly what to change, so that it runs again, you helped a lot. Cause I wanted to get away from Pharlap linker, but maybe this is a bad idea or just way harder than I expected. So thank you very much, I should do some extra research.

**Comment by jmalak** [comment]
Anyway you need at minimum special startup code which not include this segment because linker put it always as first in executable image because it must be on offset 0. I thing you use executable image in somehow specific environment, because executable created by OW is running directly under Pharlap extender.

**Comment by jmalak** [comment]
[xstrt386.zip](https://github.com/user-attachments/files/15584790/xstrt386.zip)
I created new specific startup OW run-time module which eliminate use of NULL check code on begining of executable image.
Add it to linker command by directive **`file xstrt386.obj`**.

**Comment by headscott** [comment]
Now the Null Pointer check is not there anymore, yes. But I had something else positioned at 0x200 which isnow at 0x320B0 in my project. Still not what I wanted. Everything can stay the same, just the null pointer check routine should be removed or way later

**Comment by jmalak** [comment]
You need order properly modules on wlink command if you want similar layout.
Try to add main module (what you want on image begining) as first and this special module as last because modules are linked in order as on command line or how is combined by segment attributes. You cannot get exactly same executable by two different run-time systems. It is not portable code which depend on position in executable image because linker relocate addresses in dependency on code location in executable image that it has no meaning. I think you are trying to do never ending story, which is useless because executable is different as soon as you change order of linked modules on command line. You can try it with Pharlap Linker and you will see that each time you change order of modules on command line you get executable with different image.

**Comment by headscott** [comment]
Oh trueee, you are right. I forgot. Sorry, now it looks good. I will try to run it now
