### ISSUE TITLE
Wrong shield for alloca.h

### ISSUE THREAD

**Issue by fafner2000** [open-watcom/open-watcom-v2#1304]
Hello,

I found that the shield for alloca.h (both h and lh directories) is _STRINGS_H_INCLUDED , the same as strings.h . I suppose it should be _ALLOCA_INCLUDED_H ?

Quite expectedly, it causes troubles when including alloca.h after strings.h

https://github.com/open-watcom/open-watcom-v2/blob/master/ci/ow/h/alloca.h

**Comment by jmalak** [comment]
Thanks for your bug report.
