### ISSUE TITLE
Missing atoh function

### ISSUE THREAD

**Issue by MikeyG** [open-watcom/open-watcom-v2#1318]
I was trying to use the atoh() function, but I did not find it in stdlib.h. It is mentioned 1.1.8 Conversion Functions of the C Library Overview, but there is no entry in the text.

**Comment by jmalak** [comment]
Thanks for your report.
It looks like this functions doesn't exists that it is bug in documentation.
I will review if atoh was lost or if it is documentation bug.

**Comment by jmalak** [comment]
I checked in OW and it looks like atoh is QNX specific function.
It is bug in documentation that it was not excluded from current OW documentation.
I correct documentation that atoh is included only into QNX version of documentation, but it is not used.
I think it could not be a problem replace this non-standard function by C standard compliant function, by  example strtol with base 16.
