### ISSUE TITLE
spurious 'pointer or reference truncated' warning from c++ compiler

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#1326]
Test case:

```c
#include <malloc.h>
#include <stdlib.h>

extern void foo(int, float*, int*);

void Sky_ClipPoly (int nump, float *vecs)
{
	const int max_clip_verts = nump + 2;
	const int on_heap = max_clip_verts > 64;
	int	*sides;

	sides = (int *) (on_heap ? malloc(max_clip_verts * sizeof(int)) : alloca(max_clip_verts * sizeof(int)));
	foo(nump, vecs, sides);

	if (on_heap) free(sides);
}
```

If built using wcc386, no warnings.

If built using wpp386, here it is:

```
$ wpp386 -zq -wx -bm -bt=nt -5s -sg -otexan -fp5 -fpi87 -ei -j -zp8 -fo=test.obj test.cc
test.cc(12): Warning! W005: col(110) pointer or reference truncated
```

I don't see an actual issue in the code.

**Comment by jmalak** [comment]
Please what options you used for wcc386 and what is INCLUDE environment variable value?

**Comment by sezero** [comment]
> Please what options you used for wcc386

As I showed above: `-zq -wx -bm -bt=nt -5s -sg -otexan -fp5 -fpi87 -ei -j -zp8`

> and what is INCLUDE environment variable value?

Simply `$WATCOM/h`

**Comment by jmalak** [comment]
Thanks for your info.
The issue is caused by alloca inline function which allocate memory on stack explicitly.
Below is pre-processed code

  extern void __based(__segname("_STACK")) *__doalloca(__w_size_t __size);
     #pragma aux __doalloca = \
            "sub esp,eax"   \
        __parm __nomemory [__eax] \
        __value [__esp] \
        __modify __exact __nomemory [__esp]

        sides = (int *) (on_heap ? malloc(max_clip_verts * sizeof(int)) :  (((((max_clip_verts * sizeof(int))+(sizeof(int)-1))&~(sizeof(int)-1))<stackavail())?(__GRO((((max_clip_verts * sizeof(int))+(sizeof(int)-1))&~(sizeof(int)-1))),__doalloca((((max_clip_verts * sizeof(int))+(sizeof(int)-1))&~(sizeof(int)-1)))): (void *)0) );

C++ compiler for some reason wrongly assume segment is far or is not in FLAT Group even if flat memory model is used.
Maybe it is from ternary operator that incorrectly compare both pointers as incompatible.
I will review C++ compiler and fix the issue.

**Comment by sezero** [comment]
Thanks. I'll be waiting for the fix.

**Comment by jmalak** [comment]
It is confirmed, the issue is with ternary operator.

**Comment by sezero** [comment]
For what it's worth, the issue doesn't exist in ow1.9 or in the builds from the last code from the old p4 repository.

Smaller test case:
```c
#include <malloc.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

extern void foo(int, float*, int*);

void Sky_ClipPoly (int nump, float *vecs)
{
	const int on_heap = nump > 64;
	int *sides =  (int *) (on_heap ? malloc(nump * sizeof(int)) : alloca(nump * sizeof(int)));
	foo(nump, vecs, sides);
	if (on_heap) free(sides);
}

#ifdef __cplusplus
}
#endif
```

Using ow1.9, there is practically no difference between the disassemblies of the created with wcc386 and wpp386.

However, using the latest ow2.0 builds, the disassembly from the c++ build differs a lot from the c-only build.

**Comment by jmalak** [comment]
I am not sure if it is compiler bug, because it is correct warning for all memory models except flat memory model.
I will look on C compiler code why it is not reported because in this case behaviour should be same.
I think that better solution will be to modify header file for flat memory model to not use based pointer for alloca inline code (__doalloca).

**Comment by jmalak** [comment]
It is fixed now in git repository.

**Comment by jmalak** [comment]
alloca.sp is include file and is used by malloc.h and stdlib.h which both declare alloca.

**Comment by jmalak** [comment]
You can check with your options.
Next try to add -zu option then it should report the issue again.
It is correct behaviour -zu option change stack to be far and therefore pointer to stack cannot be assign to near pointer.

**Comment by sezero** [comment]
Tried the CI build: it seems to be good. No asm output difference in C and C++ builds, either.
Therefore, I guess this can be closed.

P.S.: Using the `-zu` option resulted in W005 warning, as expected.
