### ISSUE TITLE
stdc bounds checking extensions: memset_s is missing

### ISSUE THREAD

**Issue by winspool** [open-watcom/open-watcom-v2#1329]
Projekt mbed-tls from github:  https://github.com/Mbed-TLS/mbedtls.git

mbedtls defines `__STDC_WANT_LIB_EXT1__` to activate the bounds checking extensions.

OpenWatcom defines `__STDC_LIB_EXT1__` to mark the extensions as available,
but blames, when `mbedtls` uses `memset_s` in
https://github.com/Mbed-TLS/mbedtls/blob/ddc080073ca665afef4dadebec5b4b1d760a54d7/tf-psa-crypto/drivers/builtin/src/platform_util.c#L109

```
tf-psa-crypto/drivers/builtin/src/platform_util.c(109): Warning! W131: No prototype found for function 'memset_s'
tf-psa-crypto/drivers/builtin/src/platform_util.c(109): Warning! W308: The function 'memset_s' without prototyped parameters called
tf-psa-crypto/drivers/builtin/src/platform_util.c(109): Note! N2002: 'memset_s' defined in: tf-psa-crypto/drivers/builtin/src/platform_util.c(109)
```

Additional failure messages related to `memset_s` are not given,
as the building of the mbedtls project breaks later, before the test programs are linked.

(As a workaround, i changed mbedtls to not define `__STDC_WANT_LIB_EXT1__`
and force mbedtls to use replacement functions.)

**Comment by jmalak** [comment]
OW is fully compliant with TR 24731-1. TR 24731-1 does not contain memset_s.

**Comment by winspool** [comment]
N2176 (C17 Ballout), Appendix K:
* K.3.7.4.1 The memset_s function

N1570 (latest C11 Draft from 12. April 2011), Appendix K:
* K.3.7.4.1 The memset_s function

**Comment by winspool** [comment]
> OW is fully compliant with TR 24731-1. TR 24731-1 does not contain memset_s.

With more searching, i found n2336 (3.Feb.2019)
(Bounds-checking Interfaces: Field Experience and Future Directions),
which has in Section 6 "Implementations"
```
6.2. Open Watcom
Starting with version 1.5, the Open Watcom compiler [23] ships with an implementation of TR 24731-1. Open Watcom Ver-
sion 1.9 defines the __STDC_LIB_EXT1__ macro to 200509L, indicating that it conforms to the final draft of the technical
report [3].
Because the final draft of TR 24731 is essentially identical to the published technical report, which is close to Annex K (alt-
hough not identical because the memset_s function specified by the Annex does not appear in the technical report, the Open
Watcom implementation can be considered a nearly conforming implementation.
```

**Comment by jmalak** [comment]
As usualy you ignore OW supported standards.
Don't reported such stupid things which can not work by principle.
If you want it as extension then ask about extension.
OW doesn't support any of your Standards that it is not bug but your ignorance of what is supported and what can and what cannot work.
If you will continue in your "bug" reporting system then I will definitely block your access.
I don't want read your useless listings about user mistakes, because user don't understand supported standards and report user mistake as OW bug.
