### ISSUE TITLE
make _Bool type available in all C standard modes, not just >= C99

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#1331]
As the title says. And gcc does that already. Otherwise, the following
compile time assert fails without `-za99`, because `(unsigned char)(-1)`
will equal to 0xff: (E1020: Dimension cannot be 0 or negative)
```c
#include <stdbool.h>
typedef int foo[2 * ((bool)(-1) == 1) - 1];
```

**Comment by sezero** [comment]
Maybe something like the following (not tested though, and might be incomplete..)

```diff
diff --git a/bld/cc/c/ctype.c b/bld/cc/c/ctype.c
index bd8d04c..a6fb3dd 100644
--- a/bld/cc/c/ctype.c
+++ b/bld/cc/c/ctype.c
@@ -1353,10 +1353,6 @@ static void CheckBitfieldType( TYPEPTR typ )
     }
     switch( typ->decl_type ) {
     case TYP_BOOL:
-        if( !CompFlags.extensions_enabled && CHECK_STD( < , C99 ) ) {
-            break;
-        }
-        /* fall through */
     case TYP_INT:
     case TYP_UINT:
         /*
diff --git a/bld/hdr/watcom/stdbool.mh b/bld/hdr/watcom/stdbool.mh
index 7c64bbf..6a0ba03 100644
--- a/bld/hdr/watcom/stdbool.mh
+++ b/bld/hdr/watcom/stdbool.mh
@@ -45,9 +45,6 @@
  #define bool _Bool
  #define true  1
  #define false 0
- #if __STDC_VERSION__ < 199901L
-  typedef unsigned char _Bool;
- #endif
 
  #define __bool_true_false_are_defined 1
 
diff --git a/bld/watcom/h/bool.h b/bld/watcom/h/bool.h
index 91e940a..335b022 100644
--- a/bld/watcom/h/bool.h
+++ b/bld/watcom/h/bool.h
@@ -33,7 +33,7 @@
 
 #if !defined( __cplusplus )
   #if !defined( __bool_true_false_are_defined )
-    #if !defined( __STDC_VERSION__ ) || __STDC_VERSION__ < 199901L || defined( __WATCOMC__ ) && __WATCOMC__ < 1300
+    #if defined( __WATCOMC__ ) && __WATCOMC__ < 1300
         /*
          * support for pre C99 compilers
          * fix for OW 1.9 bug in _Bool implementation
diff --git a/ci/ow/h/stdbool.h b/ci/ow/h/stdbool.h
index 192b82a..467e9dc 100644
--- a/ci/ow/h/stdbool.h
+++ b/ci/ow/h/stdbool.h
@@ -23,11 +23,7 @@
 #endif
 
 #ifndef __cplusplus
- #if __STDC_VERSION__ >= 199901L
-  #define bool _Bool
- #else
-  #define bool char
- #endif
+ #define bool _Bool
  #define true  1
  #define false 0
 #endif
diff --git a/ci/ow/lh/stdbool.h b/ci/ow/lh/stdbool.h
index 192b82a..467e9dc 100644
--- a/ci/ow/lh/stdbool.h
+++ b/ci/ow/lh/stdbool.h
@@ -23,11 +23,7 @@
 #endif
 
 #ifndef __cplusplus
- #if __STDC_VERSION__ >= 199901L
-  #define bool _Bool
- #else
-  #define bool char
- #endif
+ #define bool _Bool
  #define true  1
  #define false 0
 #endif
```

**Comment by jmalak** [comment]
I think proper solution is to disable use of stdbool.h .
If we accept that we enable _Bool in C89 mode as OW extension then we can do appropriate changes in stdbool.h that nothing is defined if extension is disabled in C89 mode otherwise it will use _Bool type.
Anyway in watcom/h/bool.h must not be removed check for `__STDC__` because it is here for Microsoft compilers which has strange support for _Bool, some version none some versions partial etc.

**Comment by sezero** [comment]
> I think proper solution is to disable use of stdbool.h .

stdbool.h _is_ needed for using `bool` in C code: it should just define `bool` as `_Bool` as above

(If I understood your wording correctly)

**Comment by jmalak** [comment]
Of cause only if _Bool type is not defined.

**Comment by sezero** [comment]
> Of cause only if _Bool type is not defined.

No: Do not expect all and every people to use _Bool: many will just simply use bool. That's why c99 demands stdbool.h.

**Comment by jmalak** [comment]
Maybe I was not exact if defined _Bool then defined bool and if not defined _Bool then not defined bool.

```
#ifndef _STDBOOL_H_INCLUDED
#define _STDBOOL_H_INCLUDED

#if !defined( _NO_EXT_KEYS ) || __STDC_VERSION__ >= 199901L /* extensions enabled or C99 */
 #define bool _Bool
 #define true  1
 #define false 0

 #define __bool_true_false_are_defined 1
#endif /* extensions enabled */

#endif

```

**Comment by sezero** [comment]
> ```
> #if !defined( _NO_EXT_KEYS ) || __STDC_VERSION__ >= 199901L /* extensions enabled or C99 */
> ```

Ah. But with gcc, `_Bool` is accepted even with switches like `-std=c89 -ansi` 
That's why I proposed the change in this ticket.

**Comment by jmalak** [comment]
I think it is wrong.
It should be available only for C99 and above and when extension is enabled. with pure C89 can not be used.
OW has extension enabled by default but if you swith to pure C89 then it should be unavailable.

**Comment by sezero** [comment]
OK then, the next best thing would be _Bool being available in c89 when extensions are not disabled.

**Comment by jmalak** [comment]
OK, we agreed.

**Comment by jmalak** [comment]
Now C compiler recognize _Bool type in C89 mode with extension enabled and stdbool.h is modified to support this new behaviour.
please check if running as we agreed.

**Comment by sezero** [comment]
OK, will test as soon as a CI build is available.

**Comment by sezero** [comment]
Took CI build from c780e1d295cd6694f7d41f5b47d08046f090c3a4, there is a thinko: if extensions are disabled and we are in c89 mode, bool isn't defined. The following patch fixes it:

```diff
--- stdbool.h~
+++ stdbool.h
@@ -29,15 +29,15 @@
 
 #else /* __cplusplus not defined */
 
-#if !defined( _NO_EXT_KEYS ) || __STDC_VERSION__ >= 199901L /* extensions enabled or C99 */
+#if defined( _NO_EXT_KEYS ) && __STDC_VERSION__ < 199901L /* extensions disabled and C89 */
+ typedef unsigned char _Bool;
+#endif
 
  #define bool _Bool
  #define true  1
  #define false 0
  #define __bool_true_false_are_defined 1
 
-#endif /* extensions enabled */
-
 #endif /* __cplusplus not defined */
 
 #endif

**Comment by jmalak** [comment]
submitted

**Comment by winspool** [comment]
> > I think proper solution is to disable use of stdbool.h .
> 
> stdbool.h _is_ needed for using `bool` in C code: it should just define `bool` as `_Bool` as above
> 
> (If I understood your wording correctly)

That changed in C23:
* `bool`, `true` and `false` are normal C keywords (section 6.4.1 in the latest draft)
* <stdbool.h> contains only the obsolete macro `__bool_true_false_are_defined` with the value `1` (section 7.19)
