### ISSUE TITLE
Variable declaration treated as function declaration after first function call within function

### ISSUE THREAD

**Issue by Pokeman2003** [open-watcom/open-watcom-v2#1336]
I'm not really sure to describe what's going on. The title is made as concisely as I can possibly muster, but it still seems very off. 
This code right here demonstrates the intended behavior: It compiles. There are absolutely zero issues with this code, other than the unused variables.
```c
#include <stdio.h>
void main() {
 int aThirtyTwo = 32;
 void* aPointer = 0;

 printf("Hello world.\n")
 return 0;
}
```
The following code does NOT compile, despite being ANSI compliant(it compiles with GCC and Borland.) The most interesting error it gives is E1077, which is an error that it is missing a closing bracket for the 5th line. This leads me to believe that it's _trying_ to treat aThirtyTwo and any other subsequent variable declarations as function declarations, leading to its collapse, though I could be very wrong as I am not familiar to how OpenWatcom compiles in the slightest.
```c
#include <stdio.h>
void main() {
 printf("Hello world.\n")

 int aThirtyTwo = 32;
 void* aPointer = 0;

 return 0;
}
```

**Comment by jmalak** [comment]
By default OW C compiler is in C89/C90 but your code is for higher C standard.
Add -zastd=c99 option to compiler command line or for backward compatibility with OW 1.9 option -za99
