### ISSUE TITLE
[HowTo] Build OpenWatcom v2 on Fedora or Ubuntu Linux

### ISSUE THREAD

**Issue by LowLevelMahn** [open-watcom/open-watcom-v2#1343]
wrote that on my first journey building Open Watcom v2 on linux - can maybe added to the build instructions - as a easy to follow starter howto

Compile OpenWatcom V2 x64 on Linux

install needed packages on **Fedora** (tested with Fedora 40 - should work exactly like this on older versions)

1. download & install Fedora (https://fedoraproject.org)
2. `sudo dnf update`
3. `sudo dnf groupinstall "Development Tools"` - for gcc and typical build tools
4. `sudo dnf install clang` - for clang (if wanted to build with clang instead of gcc)
5. `sudo dnf install git`
6. `sudo dnf install dosbox`
7. `sudo dnf install glibc-static`
8. `sudo dnf install libstdc++-static`

install needed packages on **Ubuntu** (tested with Ubuntu 24.10 - should work exactly like this on older versions)

1. download & install Ubuntu (https://ubuntu.com)
2. `sudo apt update`
3. `sudo apt install build-essential` - for gcc and typical build tools
4. `sudo apt install g++`
5. `sudo apt install clang` - for clang (if wanted to build with clang instead of gcc)
6. `sudo apt install dosbox`
7. `sudo apt install git`

**building OpenWatcom v2**

1. `cd ~/`
2. `mkdir my_ow_build`
3. `cd my_ow_build`
4. `git https://github.com/open-watcom/open-watcom-v2.git`
5. `cp open-watcom-v2/setvars.sh my_setvars.sh`
open `my_setvars.sh` in editor and change:
`OWROOT` to the absolute path of `my_ow_build/open-watcom-v2`
example: `export OWROOT=/home/test/my_ow_build/open-watcom-v2`
`OWTOOLS` (**only** if you want to build with clang - else gcc is used)
`export OWTOOLS=CLANG`
6. `. ./my_setvars.sh` - the point in front is needed to keep the environment
7. `./build.sh`
8. run tests etc.

**Comment by jmalak** [comment]
Please move it to the Open Watcom Wiki

**Comment by LowLevelMahn** [comment]
added it to the end of https://github.com/open-watcom/open-watcom-v2/wiki/Build

**Comment by jmalak** [comment]
Thanks.
If you have something what you want to share with others then best place is Wiki.

**Comment by LowLevelMahn** [comment]
i also doing a Windows VS2022 (lastest) build currently - switch to dosbox-staging (i know there is a version contained) and found a crashing test-case for dosbox-staging devs :)
