### ISSUE TITLE
DOS stat() pathname separator inconsistency

### ISSUE THREAD

**Issue by dajhorn** [open-watcom/open-watcom-v2#1345]
The DOS runtime recognizes both kinds of slashes as pathname separators, but handles them differently.

Consider this test program:

```cpp
// dirstat.c
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <path>\n", argv[0]);
        return EXIT_FAILURE;
    }

    struct stat st;
    if (stat(argv[1], &st) == 0) {
        if (S_ISDIR(st.st_mode)) {
            printf("%s is a directory.\n", argv[1]);
        } else {
            printf("%s is not a directory.\n", argv[1]);
        }
    } else {
        perror("stat");
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
```
Compile it with:

```batch
wpp386 -bt=dos dirstat.c
wlink system dos32a file dirstat.obj
```

#### Observed `stat()` behavior:

* Trailing forward-slash pathname separators are folded and `stat()` behaves like posix.
* Trailing backward-slash pathname separators return `errno=1` (ENOENT: No such file or directory).

![command_000](https://github.com/user-attachments/assets/673f3a8c-8d95-4b0c-b734-d65ba6734021)

* Except when the pathname resolves to a drive root.  (`X:\` is recognized as a corner case.)

![command_001](https://github.com/user-attachments/assets/9a9a9b7e-7be7-4bc5-9f13-eb59667a429c)
![command_002](https://github.com/user-attachments/assets/a4fa99ff-9aa8-45c1-aeec-594c56c8154e)
![command_003](https://github.com/user-attachments/assets/5ae0801d-6ea9-498c-8a82-e4e92f2c2685)
![command_004](https://github.com/user-attachments/assets/f62238bd-5b1f-492b-8c11-fd3f1165a78e)

* If the `stat()` parameter is a file, then both slashes are folded similarly.

![command_005](https://github.com/user-attachments/assets/e490ab04-62f1-4a57-9d03-cae481321b53)

#### Expected `stat()` behavior:

* The DOS runtime handles both pathname separator characters similarly.
* Trailing backslashes are folded, especially in pathnames that are directories.

**Comment by jmalak** [comment]
What DOS version you are using?

**Comment by dajhorn** [comment]
This happens in:

* MS-DOS 6.22
* FreeDOS T2410
* DOSBox-X 2024.10.01

MS-DOS and FreeDOS have different `/` tail folding than DOSBox-X, so at least some of this `stat()` behavior is platform dependent.

[issue1345.zip](https://github.com/user-attachments/files/17574646/issue1345.zip) is a floppy disk image containing the `dirstat.exe` test program.

**Comment by jmalak** [comment]
Thanks for your bug report.
I will correct ASAP.

**Comment by jmalak** [comment]
There is issue with trailing slash.

**Comment by jmalak** [comment]
It looks like it is correct behaviour, because appropriate DOS function to access directory fails due to trailing slash.
You need to use **`path/last`** or **`path/last/.`** form.
