### ISSUE TITLE
Register parameters from #pragma aux not applied to typedef function pointer

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#1355]
I am writing a JIT for a function that takes parameters with a different calling convention than the WATCOM register convention `eax`, `edx`, `ebx`, `ecx`. It does not seem possible to do this using `#pragma aux` either on a function pointer, or using inline assembly.

```C
void jit_code(unsigned char *jit) {
  // add eax, ebx
  *jit++ = 0x01;
  *jit++ = 0xd8;
  // ret
  *jit = 0xc3;
}

typedef int (*jit_add_func)(int a, int b);
#pragma aux jit_add_func parm [eax] [ebx] value [eax]

unsigned char jit[3];

#pragma aux main modify [eax ebx ecx edx esi edi]
int main() {
  jit_add_func add = (jit_add_func)jit;
  jit_code(jit);
  return add(1, 2);
}

int jit_add(int a, int b);
#pragma aux jit_add parm [eax] [ebx] value [eax] = \
  "call jit"

#pragma aux main2 modify [eax ebx ecx edx esi edi]
int main2() {
  jit_code(jit);
  return jit_add(1, 2);
}
```

Compiling and disassembling:

```
$ wdis bin/jit.o
Module: jit.c

Segment: _BSS DWORD USE32 00000003 bytes
0000				_jit:

BSS Size: 3 bytes

Segment: _TEXT BYTE USE32 0000001B bytes
0000				main2_:
0000  B8 00 00 00 00			mov		eax,offset _jit
0005  E8 00 00 00 00			call		jit_code_
000A  BB 02 00 00 00			mov		ebx,0x00000002
000F  B8 01 00 00 00			mov		eax,0x00000001
0014  FF 15 00 00 00 00			call		dword ptr _jit
001A  C3				ret

Routine Size: 27 bytes,    Routine Base: _TEXT + 0000

No disassembly errors

Segment: _TEXT BYTE USE32 00000019 bytes
0000				main_:
0000  B9 00 00 00 00			mov		ecx,offset _jit
0005  89 C8				mov		eax,ecx
0007  E8 00 00 00 00			call		jit_code_
000C  BA 02 00 00 00			mov		edx,0x00000002
0011  B8 01 00 00 00			mov		eax,0x00000001
0016  FF D1				call		ecx
0018  C3				ret

Routine Size: 25 bytes,    Routine Base: _TEXT + 0000

No disassembly errors

Segment: _TEXT BYTE USE32 0000000A bytes
0000				jit_code_:
0000  66 C7 00 01 D8			mov		word ptr [eax],0xd801
0005  C6 40 02 C3			mov		byte ptr 0x2[eax],0xc3
0009  C3				ret

Routine Size: 10 bytes,    Routine Base: _TEXT + 0000

No disassembly errors
```

There are potentially two bugs here. First, at `000C` of `main_` I was expecting

`BB 02 00 00 00			mov		ebx,0x00000002`

but instead got

`BA 02 00 00 00			mov		edx,0x00000002`

Second, at `0014` of `main2_` I was expecting

`E8 00 00 00 00			call		_jit`

but instead got

`FF 15 00 00 00 00		call		dword ptr _jit`

which will call the address stored at `_jit` and not the address of `_jit`.

**Comment by jmalak** [comment]
#pragma aux has two main usage.
For in-line assembly code and for specification of C symbol properties.
Assembly in-line code doesn't represent C function, it can be only included in C function body because it is always in-lined.
in-line code doesn't know anything as calling convention, you can only define how inline function use registers. It is Code generator low-level description about registers only. Code generator use these information to derive how resters are used by in-line code. Normaly #pragma aux in-line code is defined in header files and instantiated in C code. as Example look for header file bld/watcom/h/tinyio.h it doesn't generate any code if it is included in source file, only what you use in C functions body.
calling convention is term for C functions (it has defined C symbol) . If you have pointer to symbol then you need define attributes of object to which point pointer.

What you expect from C function which has not defined function arguments and you try to assign registers?
It is logical non-sense in your code main and main2 functions.

**Comment by negge** [comment]
Sure, but if you look at just the inline example, something weird is going on. Why does `call jit` become `call [jit]`?

**Comment by jmalak** [comment]
And what you expect from call jit if jit is array?

**Comment by negge** [comment]
OK, I was able to do some hack's to make it work correctly. Instead of declaring `unsigned char jit[3];` in the same jit.c file, instead I put a function declaration `void jit()` and define the `jit_` symbol via assembly in another file. Here is `jit.asm`

```nasm
SEGMENT .bss USE32 CLASS=BSS
GLOBAL jit_
  jit_ resb 3
```

```
$ wdis bin/lib/jit.o 
Module: bin/lib/jit.asm

Segment: bss BYTE USE32 00000003 bytes
0000				jit_:

BSS Size: 3 bytes
```

And this is the updated jit.c file:

```C
void jit_code(unsigned char *jit) {
  // add eax, ebx
  *jit++ = 0x01;
  *jit++ = 0xd8;
  // ret
  *jit = 0xc3;
}

void jit();

int jit_add(int a, int b);
#pragma aux jit_add parm [eax] [ebx] value [eax] = \
  "call jit"

#pragma aux main modify [eax ebx ecx edx esi edi]
int main() {
  jit_code((unsigned char *)jit);
  return jit_add(1, 2);
}
```

```
$ wdis bin/jit.o
Module: src/jit.c

Segment: _TEXT BYTE USE32 0000001A bytes
0000				main_:
0000  B8 00 00 00 00			mov		eax,offset jit_
0005  E8 00 00 00 00			call		jit_code_
000A  BB 02 00 00 00			mov		ebx,0x00000002
000F  B8 01 00 00 00			mov		eax,0x00000001
0014  E8 00 00 00 00			call		jit_
0019  C3				ret

Routine Size: 26 bytes,    Routine Base: _TEXT + 0000

No disassembly errors

Segment: _TEXT BYTE USE32 0000000A bytes
0000				jit_code_:
0000  66 C7 00 01 D8			mov		word ptr [eax],0xd801
0005  C6 40 02 C3			mov		byte ptr 0x2[eax],0xc3
0009  C3				ret

Routine Size: 10 bytes,    Routine Base: _TEXT + 0000

No disassembly errors
```

This compiles and runs correctly, so there is a work around.

**Comment by jmalak** [comment]
Your code use #pragama aux incorrectly therefore you have a trouble.
No "workaround" is needed only use pragma aux as should be.

By example what sense has your pragma aux on main?
I see it in many user code but It looks like that users don't understand pragma aux and copy such code from somewhere.

**Comment by jmalak** [comment]
Give me correct C code which use such construct.

**Comment by jmalak** [comment]
Here is reference to same problem #761

**Comment by jmalak** [comment]
Below is correct use of #pragma aux in your code.

```
typedef int jit_func_type(int a, int b);
#pragma aux jit_func_type parm [eax] [ebx] value [eax]

typedef jit_func_type *jit_add_func;
```

Next you can use this type anywhere.
anyway other constructs with pragma aux is wrong or useless
