### ISSUE TITLE
Build fails on bld/wgml/c/gsbx.c

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#139]
I looks like a commit from a few days ago may have broken the build in `bld/wgml/c/gsbx.c`.  Not sure what the exact problem is.  Full build output available at: 

http://buildbot.approximatrix.com/builders/global_build_rel/builds/382/steps/Global%20Build/logs/stdio

**Comment by jmalak** [comment]
Sorry for this. I must go to UK for a few day and didn't have enough time to submit fix for this problem. I will do on Friday as I return back.

**Comment by ArmstrongJ** [comment]
@jmalak no rush.  I just wanted to make sure you were aware of it.

**Comment by jmalak** [comment]
It is OK

**Comment by ArmstrongJ** [comment]
Forgot to close this.  Everything has been fine for a few days.  Thanks!
