### ISSUE TITLE
__x87id FPU detection routine locks up on 8088 without FPU

### ISSUE THREAD

**Issue by Scalibq** [open-watcom/open-watcom-v2#141]
This code in the __x87id proc in ini87086.asm will lock up on an 8088 without
FPU:
        sub     AX,AX
        push    AX                      ; allocate space for status word
        finit                           ; use default infinity mode
        fstcw   word ptr [BP-2]         ; save control word
        fwait
        pop     AX
        mov     AL,0
        cmp     AH,3
        jnz     nox87

The reason is that the fwaits will wait forever for the FPU to clear the bus.
Instead, I suggest this method to detect an FPU on all systems (based on an
example from Intel):
        fninit
        mov     AX,5A5Ah
        push    AX
        fnstsw  word ptr [BP-2]
        pop     AX
        cmp     AL, 0
        mov     AL, 0
        jnz     nox87

The fninit is a 'bare' finit, without a wait prefix.
If there is no 8087, it will just do nothing.
Then the fnstsw will store the status word, if there is an 8087... Else it does
nothing.
After the finit, the status word should always be 0. So, if the value is now 0,
we have an FPU, else we don't.

**Comment by jmalak** [comment]
Thanks for your bug report.

**Comment by javiergutierrezchamorro** [comment]
May I suggest it to be:

fninit
 mov AX,5A5Ah
 push AX
 fnstsw word ptr [BP-2]
 pop AX
 cmp AL, 0
 xor AL, AL
 jnz nox87

**Comment by Scalibq** [comment]
The xor is not going to work, because it will overwrite the flags of the
cmp al.

**Comment by jmalak** [comment]
I don't see reason why we should use status word instead of control word.
Anyway following code should fix the problem with minimal change

        ; we can not use FWAIT until FPU will be detected
        fninit                          ; use default infinity mode
        fnstcw  word ptr [BP-2]         ; save control word
        mov     AL,[BP-1]               ; delay CPU to sync with FPU if present
        mov     AL,0                    ; assume no coprocessor present
        mov     AH,3                    ; upper byte is 03h if 
        cmp     byte ptr [BP-1],AH      ;   coprocessor is present
        jnz     nox87                   ; exit if no coprocessor present
        ; now we can use FWAIT if necessary because FPU is present

**Comment by Scalibq** [comment]
I'm not sure either... I just got this from some Intel documentation.
Perhaps storing status word does not need the explicit delay... Or perhaps
it's because you can always trust the status word to be 0 after finit,
while here you try to trust that the upper byte of the control word is
always exactly equal to 3.. which may not be the case on every FPU out
there?

**Comment by jmalak** [comment]
The high byte of control word is equal to 3 after finit/fninit (37Fh for full word).
On 8087 and 80287 you must synchronize CPU to FPU FSTCW result in memory (it takes 12-18 cycles) because CPU and FPU is running paralely.
Normaly it is done by FWAIT but it can not be use if FPU is not available.

**Comment by Scalibq** [comment]
On Sat, Feb 28, 2015 at 11:00 PM, Jiří Malák <notifications@github.com>
wrote:

> The high byte of control word is equal to 3 after finit/fninit (37Fh for
> full word).
>
That assumption may not hold for all FPUs in theory.
We know it does now, and there probably won't be any new FPUs... but back
when the code was written, this was not the case (some bits in the control
word are reserved, and back in the 1980s they may have thought that they
might be assigned to new features in future FPUs).
In theory it is safer, because all bits in the status word ARE assigned,
and after an finit they MUST be 0, that's how Intel defined it.

**Comment by jmalak** [comment]
You are right that it could be changed, but x87 is frozen that it is realy constant now.
Anyway this method is used anywhere in OW.

**Comment by Scalibq** [comment]
The 386 code didn't have to be modified. 386+ does not lock up on an fwait, and since you need a 386+ to run any 32-bit code anyway, the issue wasn't there in the first place.

**Comment by jmalak** [comment]
I changed it only for consistency even if fwait has no impact to this problem.
