### ISSUE TITLE
wipfc std error

### ISSUE THREAD

**Issue by revelator** [open-watcom/open-watcom-v2#142]
Error! E2028: near std::vector<char unsigned near,std::allocator<char unsigned n
ear > near >::vector( int unsigned ) is an undefined reference
Error! E2028: near std::vector<short unsigned near,std::allocator<short unsigned
 near > near >::vector( int unsigned ) is an undefined reference
Error! E2028: near std::vector<std::list<Element near * near,std::allocator<Elem
ent near * near > near > near,std::allocator<std::list<Element near * near,std::
allocator<Element near * near > near > near > near >::vector( int unsigned ) is
an undefined reference
file document.obj(F:\open-watcom-v2\bld\wipfc\cpp\document.cpp): undefined symbo
l near std::vector<char unsigned near,std::allocator<char unsigned near > near >
::vector( int unsigned )
file btmpblk.obj(F:\open-watcom-v2\bld\wipfc\cpp\btmpblk.cpp): undefined symbol
near std::vector<char unsigned near,std::allocator<char unsigned near > near >::
vector( int unsigned )
file btmpblk.obj(F:\open-watcom-v2\bld\wipfc\cpp\btmpblk.cpp): undefined symbol
near std::vector<short unsigned near,std::allocator<short unsigned near > near >
::vector( int unsigned )
file table.obj(F:\open-watcom-v2\bld\wipfc\cpp\table.cpp): undefined symbol near
 std::vector<std::list<Element near * near,std::allocator<Element near * near >
near > near,std::allocator<std::list<Element near * near,std::allocator<Element
near * near > near > near > near >::vector( int unsigned )
Error(E42): Last command making (wipfc.exe) returned a bad status
Error(E02): Make execution terminated
<pmake -d build         -h> => non-zero return: 2
Build failed

did a full clean but this one seems to still pop up, where there any changes to the wipfc code lately that might have caused this ?.

**Comment by jmalak** [comment]
I don't see similar problem on my build servers, but I am using OW 1.9 or GCC or MS VC(64-bit).
What compiler you are using to build OW and what platform?
Anyway wipfc code was not changed for long time.

**Comment by revelator** [comment]
Intel Parallel Studio XE 2015 with msvc 2010 or 2013 same error on both msvc though.
intel uses msvc's standard library so im not sure what could be up.

**Comment by jmalak** [comment]
OK. I will check it from scratch with MSVC.

**Comment by jmalak** [comment]
It works on my system.
It looks like linker problem.
Please could you go into bld/wipfc/nt386 and run 
SET OWVERBOSE=1
wmake clean
wmake >lst.txt 2>&1
and send me lst.txt and wipfc.map file.

**Comment by revelator** [comment]
Seems to have been an error in the new intel compiler.
I still had a few leftovers from the old 2013 intel compiler which where doing some odd things to
some sources. Sadly to fix it i had to reinstall windows because the new intel installer is a mess.
works now though so can close this issue.

**Comment by jmalak** [comment]
Thanks for note.
