### ISSUE TITLE
current build contains malware

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#146]
I just received an email purporting to announce the availability of a new release of OW-v2.  It linked to SourceForge, had "jmalak" as the contributor, and it all looked legit.  But when I installed it:

(1) the installation failed at the end.

(2) Avast quarantined a malware file (on my laptop).

(3) I was not able to use Remote Desktop to a virtual server that I had simultaneously updated at the same time that I updated my laptop.  To fix this, I had to restore the server from an image.

**Comment by pchapin** [comment]
I have seen on several occasions anti-virus software complain about certain executables in the Open Watcom distribution. In the cases I saw the complaints were all false alarms. I'm not sure about the failing installer, though.

**Comment by ideafarm** [comment]
My inability to log into my server immediately after installing is the main
suspicious fact.  I immediately restored the server from an image, so now I
have a big chore waiting for me tomorrow.  I have to reinstall Watcom
somehow, so will probably be able to cancel the alarm or confirm it.

--------------------------------
NOTICE:  This is not a private or confidential conversation.  All email to
and from this address resides in the public record and is subject to
publication.  The general business of IdeaFarm (tm) Operations is conducted
transparently.  Pseudo-confidential communication is possible but only by
prior arrangement, and the request itself remains in the public record.
--------------------------------

18 U.S.C. 241: "If two or more persons conspire to injure, oppress,
threaten, or intimidate any person... in the free exercise... of any
right... [t]hey shall be fined... or imprisoned not more than ten years,
... and... if such acts include kidnapping..., they shall be fined... or
imprisoned for any term of years or for life, or both, or may be sentenced
to death."

**Comment by staalmannen** [comment]
There is a text file with md5sums. Did you check md5sum of the binary? (A
malicious uploader could ofcourse have changed this text file too but it is
at least another check). I know that some GNU projects moved off
sourceforge due to crap/adware bundling.
Den 10 mar 2015 02:15 skrev "ideafarm" <notifications@github.com>:

**Comment by ideafarm** [comment]
No, I don't have time to investigate this, especially now that I must deal
with restoring my development machine (the server that I could not log
into).  My intent in raising the alarm is to raise the issue of whether
Jiri released a new build to SourceForge, such that the email that informed
me that a new vesion of OW is available was legit.  Did anyone else get an
email from SoureForge announcing that a new version is available?

--------------------------------
NOTICE:  This is not a private or confidential conversation.  All email to
and from this address resides in the public record and is subject to
publication.  The general business of IdeaFarm (tm) Operations is conducted
transparently.  Pseudo-confidential communication is possible but only by
prior arrangement, and the request itself remains in the public record.
--------------------------------

18 U.S.C. 241: "If two or more persons conspire to injure, oppress,
threaten, or intimidate any person... in the free exercise... of any
right... [t]hey shall be fined... or imprisoned not more than ten years,
... and... if such acts include kidnapping..., they shall be fined... or
imprisoned for any term of years or for life, or both, or may be sentenced
to death."

**Comment by jmalak** [comment]
Similar report has no much value, because it can be only coincidence with user PC state.
I expect that minimum information will be included in report
1. what OS is installed
2. what version of OW is installed
3. what anti-spyware or anti-virus software is used
4. what malware/virus type is reported by anti-spyware/virus software
5. which OW file is source of this issue

**Comment by ideafarm** [comment]
Sorry.  I just don't have time to help you with this, beyond notifying you
that something awful happened to me as my reward for installing the new
build of OW.  My laptop runs Windows 7 32-bit and is protected by Avast.
My server runs Windows 2012-R2 and is not protected.

--------------------------------
NOTICE:  This is not a private or confidential conversation.  All email to
and from this address resides in the public record and is subject to
publication.  The general business of IdeaFarm (tm) Operations is conducted
transparently.  Pseudo-confidential communication is possible but only by
prior arrangement, and the request itself remains in the public record.
--------------------------------

18 U.S.C. 241: "If two or more persons conspire to injure, oppress,
threaten, or intimidate any person... in the free exercise... of any
right... [t]hey shall be fined... or imprisoned not more than ten years,
... and... if such acts include kidnapping..., they shall be fined... or
imprisoned for any term of years or for life, or both, or may be sentenced
to death."

**Comment by jmalak** [comment]
Anyway if you install OW under normal user account you can not crash your system.
It is advance of OW installer that you don't need administrator rights and you can install multiple OW versions on one system.

**Comment by ideafarm** [comment]
Am closing this issue because I've been able to install aok on 64 bit Windows Server 2012 R2, except for the installer crash at the very end, which appears to have no consequence.  I will open a new issue for that.
