### ISSUE TITLE
installer crashes after completing installation

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#148]
The OW V2 C++ 64 bit installer crashes after the user clicks OK on the popup that says, approximately,  "Installation has completed.  You should reboot your computer now."

This occurred when installing onto Windows Server 2012 R2 running on a Rackspace virtual server.
![x owv2 installer crash](https://cloud.githubusercontent.com/assets/3060794/6621779/d6ca871a-c895-11e4-9a62-632cab0e08ae.jpg)

**Comment by jmalak** [comment]
It is bug in installer that crash during final memory deallocation.
I will fix it as soon as possible.

**Comment by jmalak** [comment]
It is fixed by change cb2a5d7a2afbbeed3e93b015fdbd7c8ea56eb7ff in git repository.
