### ISSUE TITLE
_spawnvp

### ISSUE THREAD

**Issue by IVbI4** [open-watcom/open-watcom-v2#150]
Build error:

**** BUILD rule
================= 02:32:11 /opt/open_watcom_2.0/bld/wcl/owcc ==================
============== 02:32:11 /opt/open_watcom_2.0/bld/wcl/owcc/dosi86 ==============
cc owcc.obj
bwlink op q name owcc.exe debug dwarf op nored op symfile op map sys dos lib doslfnl.lib   file {clcommon.obj cmdlhelp.obj owcc.obj getopt.obj quit.obj }
============= 02:32:12 /opt/open_watcom_2.0/bld/wcl/owcc/linux386 =============
cc owcc.obj
bwlink op q name owcc.exe debug dwarf op nored op symfile op map sys linux   file {clcommon.obj cmdlhelp.obj owcc.obj getopt.obj quit.obj }
============= 02:32:12 /opt/open_watcom_2.0/bld/wcl/owcc/linuxx64 =============
cc owcc.obj
../../c/owcc.c: In function ‘tool_exec’:
../../c/owcc.c:1312:5: warning: implicit declaration of function ‘_spawnvp’ [-Wimplicit-function-declaration]
     rc = (int)_spawnvp( P_WAIT, tool->path, (char const *const *)pass_argv );
     ^
gcc -pipe  -O -g -o owcc.exe  -Wl,-Map,owcc.map clcommon.obj cmdlhelp.obj owcc.obj getopt.obj quit.obj  /opt/open_watcom_2.0/bld/watcom/binbuild/clibext.lib  -lsupc++ -lstdc++
owcc.obj: In function `tool_exec':
/opt/open_watcom_2.0/bld/wcl/owcc/linuxx64/../../c/owcc.c:1312: undefined reference to `_spawnvp'
collect2: error: ld returned 1 exit status
Error(E42): Last command making (owcc.exe) returned a bad status
Error(E02): Make execution terminated
<pmake -d build         -h> => non-zero return: 512
Build failed

unama -a:
	Linux andrey-PC 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

gcc --version:
	gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

**Comment by ArmstrongJ** [comment]
I committed the change that caused this error.  It appears that GCC does not implement the ISO standard `_spawnvp` function... I'll see about a patch for this.

**Comment by IVbI4** [comment]
You must use a family of functions exec*() to create processes. http://pubs.opengroup.org/onlinepubs/9699919799/

**Comment by jmalak** [comment]
I already fix it.
For better compatibility don't use any "_...." function even if ISO naming convention should enable it, because many platform don't have "_..." functions in CLIB.
Anyway spawn.. functions are not supported by POSIX that we have implement it in clibext.c as "spawnvp" only.

**Comment by ArmstrongJ** [comment]
@jmalak sorry for the mixup.  I did not have glibc in mind when I made that change (added the underscore) and MSVC has deprecated the non-underscored versions in favor of the ISO standard version.

@IVbI4 `spawn*` might not be POSIX, but Open Watcom implements it.  This problem only manifests itself if you build Open Watcom using glibc (or another POSIX-only runtime library).

**Comment by jmalak** [comment]
I understand.
The next rule which should be used is not to use any features from new standards as C95, C99 and above for core compilers and tools. It ensures better portability for some now not supported platforms.
