### ISSUE TITLE
try catch fails for simple test pgm

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#151]
Conj:  The -xs (enable exceptions) flag results in the stack being corrupted.  The first clue is that the following simple test program does not work.  The second clue is that my production code routinely walks up the stack  to get a reference to an object there, and this code is broken by the -xs option.  The stack walking code that is broken by the -xs option has been rock solid for a decade and is executed for almost every function call.  When I step through the walk, with -xs specified, the walk proceeds normally but then jumps to a stack frame somewhere else in memory that is far below SS.

Another clue is that WDW's call list is truncated and corrupted in a way that seems to confirm what I just described.  IOW, WDW cannot walk the stack either for modules compiled with -xs.

This simple try/catch test program does not work:

#include <stdio.h>

int main( void )
{
    int* pcb = (int*)0x87654321 ;

    try
    {
        *pcb = 1 ;
    }
    catch(...)
    {
        puts( "caught" ) ;
    }

    return 0 ;
}

I have a "full install" with executables dated 20150311 on Windows 7 32-bit.  I built the above with a bat file that contains:

@echo off

wpp386 -d2 -xs 1.cpp
wlink debug all file 1.obj
echo.
echo here we go:
echo.
1

Rather than the expected "caught", the console output was:

The instruction at 0x00401075 referenced memory at 0x87654321.
The memory could not be written.
Exception fielded by 0x00404040
EAX=0x87654321 EBX=0x00000108 ECX=0x0006fe6c EDX=0x00000000
ESI=0x00000000 EDI=0x00000000 EBP=0x0006fe44 ESP=0x0006fdf0
EIP=0x00401075 EFL=0x00010297 CS =0x0000001b SS =0x00000023
DS =0x00000023 ES =0x00000023 FS =0x0000003b GS =0x00000000
Stack dump (SS:ESP)
0x00000000 0x00000108 0x0006fe6c 0x00000000 0x00000000 0x00000000
0x0006fe44 0x0040106a 0x0006fdf0 0x00230023 0x003b001b 0x00230000
0x0006fe28 0x004096e0 0x0006ff74 0x00401144 0x004092f0 0x00000001
0x00002031 0x87654321 0x00000108 0x0006fe60 0x00000000 0x00000000
0x00000000 0x0006fe6c 0x00000108 0x00405274 0x0006ff7c 0x00070000
0x004032f1 0x00033000 0x00000000 0x00000000 0x00000001 0x00000000
0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
0x00000000 0x00000000 0x00000000 0x00000000 0x0006ff74 0x00000000
0x00000000 0x00000002 0xffffffff 0x00000002 0xffffffff 0x00000002
0xc000001d 0x00000002 0xc000013a 0x00000002 0xc0000005 0x00000002
0xc000013a 0x00000002 0xc000013a 0x00000001 0xffffffff 0x00000001

**Comment by pchapin** [comment]
This is not an error. Your program has undefined behavior. The C++ standard does not require an exception to be thrown when invalid memory is accessed. Your expectation that the program will necessarily output "caught" is wrong.

The executable generated from your program by Visual C++ and g++ also crashes in a largely similar way. In no case is "caught" displayed.

**Comment by ideafarm** [comment]
Thank you, Peter.  I just got VCC installed and got the same behavior.  Sorry to bother you and Jiri about this, but I didn't have anyone else to ask.  I will close this.  Perhaps you might be willing to help me with this via email.  I'm in a desperate situation.
