### ISSUE TITLE
Build fails due to PAGE_SIZE redefinitions

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#152]
The build is currently failing due to the new presence of the POSIX-compliant PAGE_SIZE macro in limits.h.  Rather than simply undefining the constant where legacy macros define it (mostly in help viewers), the code using this term should use a more custom value.

I'll get to work on this tomorrow morning properly, but I just left this here as a placeholder.

**Comment by jmalak** [comment]
I would like open discussion about PAGE_SIZE macro.
Status of PAGE_SIZE macro:
1. is not ISO
2. is not POSIX
Similar macro  _SC_PAGESIZE is defined by POSIX.
What is PAGE_SIZE macro?
It is Linux specific and may be some other systems use it, but it is not standard.
Therefore we should not use it in headers, except we need backward compatibility  of some old code.
We have no problem with OW code because we don't have this macro defined before.
If we want to include it for non OW code then we should define it properly.
I think we should define ISO and POSIX macro at first and use alias macro for PAGE_SIZE.
Implementation notes:
If we add POSIX items into ISO header file it should be always guarded by POSIX related macro (extposix.spand extepi.sp files include machinery) if it is platfor specific item then it should by guarded by LINUX related macro (ext.spand extepi.sp files include machinery). If our code use PAGE_SIZE in POSIX meaning then we should use POSIX standard macro _SC_PAGESIZE instead of PAGE_SIZE even if PAGE_SIZE is defined on appropriate platform.

**Comment by ArmstrongJ** [comment]
@jmalak the Open Group defines it here:

http://pubs.opengroup.org/onlinepubs/007908799/xsh/limits.h.html

It is an unfortunate constant name.  In `limit.mh` it is only provided for Linux (surrounded by :segment LINUX) but its presence will still affect compiling the Fortran compiler at the very least and some of the other tools.  

I would argue that it is dangerous for the other tools to be using a constant like PAGE_SIZE simply because it is far too generic and at least potentially defined in `limits.h` on some systems.

**Comment by ArmstrongJ** [comment]
Additionally, if you do have some suggestions for putting sentinels around its declaration (i.e. `#ifdef __POSIX__`), I'm definitely not against it.  I was just trying to provide what appears to be a "needs to be present" constant.

Oddly enough, GNU libc pretty explicitly states that they do _not_ provide this constant.  I see that [musl](http://git.musl-libc.org/cgit/musl/tree/include/limits.h) does provide it.  If you think it should be avoided, I also don't have a problem with it.

**Comment by ArmstrongJ** [comment]
Pull request #153 should resolve the issues associated with this bug.  Whether or not we keep `PAGE_SIZE` in `limits.h` on Linux, we might want to use #153 anyways in case another runtime library defining it is used to build Open Watcom.  

I implemented the changes as a pull request so we can discuss them if necessary.

**Comment by jmalak** [comment]
I have no problem with build fail.
I would like to solve it proper way for future.

We should divide issue to two problems.

First is usage of PAGE_SIZE macro in OW code and second one adding this constant to header file.
Solution of first problem is simple but depend on decision about second problem.
I want discuse second problem.

I want to prevent problems in the future if we add some problematic item in the header file now 
that we must hold it for backward compatibility later. 
We should be careful if we want add to headers anything non coverred by ISO or by POSIX standrds.
It is reason why I am careful.

I am not expert for standards that I don't want to block anything if it has sense for future.

We should answer following questions before we do any decision about it.

What is reason why we should add this constant to limits.h header file?

Have it sense for future?

For me it looks like we don't need it.
It looks like this constant is not widely accepted by POSIX systems.
If we include it then is limits.h right place?
Also it should be defined for all systems for code portability, not only for linux.

**Comment by ArmstrongJ** [comment]
It might surprise you, but I'm not particularly in favor of including the `PAGE_SIZE` (and `PAGESIZE`) macro.  It is far too generic.  It should be included in limits.h if we do keep it based on the [Open Group's definition](http://pubs.opengroup.org/onlinepubs/007908799/xsh/limits.h.html).

However, it is a problematic constant.  It probably changes for 16-bit x86.  It definitely changes for non-x86 chips.  In fact, it can vary on MIPS.

Additionally, how often will people actually want access to this constant?  Because GNU libc doesn't provide it, I'm guessing it is almost never used by software.  

I am in favor of removing it for now (and probably forever).  I can instead define it locally (as `_PAGE_SIZE` most likely) in `sysconf.c` much like it is done for so many other uses in Open Watcom.  The minor change I made to the Fortran compiler should remain.

Have a look at #153, though.  That request should remove the use of that constant from the help tooling.

**Comment by pchapin** [comment]
The Open Group documentation doesn't seem to describe the intended purpose of PAGE_SIZE. I suppose they expect it to be used with the various memory management functions POSIX provides (i.e. for rounding a memory block size up to the nearest PAGE_SIZE bytes before asking the OS to allocate the block).

However, I agree with Jeff that it is officially part of the POSIX standard for <limits.h>. I wonder if there is any information out there on why the glib people have explicitly avoided defining it. Its value is going to be highly hardware dependent and that's awkward for any library that tries to be cross platform.

**Comment by jmalak** [comment]
Oh sorry, I don't search it in SUS. You are right it is defined by POSIX.
I a little google for PAGE_SIZE in glib and it looks like the reason for undefine PAGE_SIZE is that it is kernel configuration parameter and on some platforms memory page size is variable.

**Comment by ArmstrongJ** [comment]
Now that we don't include `PAGE_SIZE` in the headers, I've made commit 3627fb755d8b171b42f816db04e85f42b5ab44d3 that effectively sets `errno` proprely for sysconf requests for PAGE_SIZE and related calls for memory calculations that would use `PAGE_SIZE`.  

In 99.9% of cases on almost all current architectures, the page size is 4KB.  There are rare cases on x86 and x86_64 where someone might have nonsensically requested 2MB page sizes (or 4MB or another size subject to some restrictions).  If we want to be technically correct, we'll need to figure out the page size which would involve requesting the CPU ID, checking if PSE or PSE-36 is available and then taking another assembly-style action to see if a certain bit is set enabling these page size extension features.  However, again, almost nobody ever will...

For now, we'll be "correct" and report "not implemented" if anyone requests this information.

**Comment by jmalak** [comment]
I think we can use the constant value 4096 for Intel architecture as first implementation even if it is not absolutely correct.

**Comment by ArmstrongJ** [comment]
With commit 0008ee35435ef25cdb4309a6a8d0efe1ab90397f everything looks good!  I'm glad we had this discussion about the macro `PAGE_SIZE`.
