### ISSUE TITLE
cannot compile a DOS 16bit program with Linux 'wcl'

### ISSUE THREAD

**Issue by groessler** [open-watcom/open-watcom-v2#157]
Hi,

I'm getting this error:

$ wcl -zq -bcl=dos -fe=hello.exe hello.c
/data/home/chris/tmp/open-watcom/open-watcom-v2/rel/lh/sys/types.h(105): Error! E1091: unknown platform
/data/home/chris/tmp/open-watcom/open-watcom-v2/rel/lh/sys/types.h(112): Error! E1055: Unable to open 'arch//sys/types.h'
/data/home/chris/tmp/open-watcom/open-watcom-v2/rel/lh/stdio.h(390): Error! E1127: Type required in parameter list
/data/home/chris/tmp/open-watcom/open-watcom-v2/rel/lh/stdio.h(390): Error! E1022: Missing or misspelled data type near 'off_t'
/data/home/chris/tmp/open-watcom/open-watcom-v2/rel/lh/stdio.h(391): Error! E1022: Missing or misspelled data type near 'off_t'
Error: Compiler returned a bad status compiling 'hello.c'
$

OpenWatcom was compiled under Linux 64bit. When I'm using the Windows NT version of 'wcl' from the same build, it works (copied the rel/ dir to a Windows machine an ran it there).

**Comment by ArmstrongJ** [comment]
@groessler the compiler appears to be trying to use the headers in the **lh** directory, which are Linux-target-only headers.  You'll need to direct the compiler to use 

`/data/home/chris/tmp/open-watcom/open-watcom-v2/rel/h`

for headers instead.  I usually do this by specifying a "-i=" flag.  I think if you change your command line to:

`wcl -zq -bcl=dos -fe=hello.exe -i=/data/home/chris/tmp/open-watcom/open-watcom-v2/rel/h hello.c`

it should work fine.

**Comment by groessler** [comment]
You're right. My INCLUDE env var looked like this:
$ echo $INCLUDE
/data/home/chris/tmp/open-watcom/open-watcom-v2/rel/lh:/data/home/chris/tmp/open-watcom/open-watcom-v2/rel/h
$

After I reversed the order to look like this:

$ echo $INCLUDE
/data/home/chris/tmp/open-watcom/open-watcom-v2/rel/h:/data/home/chris/tmp/open-watcom/open-watcom-v2/rel/lh
$

it worked.

Thanks.
