### ISSUE TITLE
http://www.openwatcom.org/:  Rewrite landing page to reflect current OW activity

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#171]
I've extracted this action item of @ArmstrongJ to act on it NOW!  Does anyone reading this have the ability to edit the official landing page?

**Comment by jmalak** [comment]
It is git repository https://github.com/open-watcom/open-watcom that you can create pull request with your changes.
If you a little bit study GitHub [`Open Watcom`](https://github.com/open-watcom) organization you will see that we have 3 main repositories.
The owp4v1copy is read only repository it is replicated from OW Perforce (OW 1.9).
The open-watcom-v2 is OW V2 fork repository.
The open-watcom is repository with main WEB site for Open Watcom organization.
We can add any other if we need.

**Comment by pchapin** [comment]
Are we talking about the page at http://www.openwatcom.org or the page at http://open-watcom.github.io/open-watcom/? I suggest this ticket is unclear because I don't know what "landing page" means and it is not defined here.

**Comment by ideafarm** [comment]
@pchapin:  See the title!  (www.openwatcom.org).  I've sent an email to Michal Necasek, but he has not responded yet.  landing page == home page.  The "official" OW homepage totally sucks and needs to be edited ASAP so that it presents OW's current status (alive and well) fairly.  That home page is so damaging and confusing that it might kill OW, notwitstanding Jiri's awesome effort here.

**Comment by pchapin** [comment]
Oh yes, I missed the URL in the title! I suppose since it doesn't fit in grammatically my mind just skipped over it. That's an interesting psychological observation.

Anyway, my feeling is that we should just ignore the official page and let it fizzle... or not... as it will. I don't particularly want to aggravate the people there by doing what might be seen as a hostile takeover attempt.

**Comment by ideafarm** [comment]
The "official" home page proclaims in several ways that OW is dead.  I often say, in connection with my civic activism, that each of us only gets to see a piece of the whole truth.  That's why community is needed.  I am an economist and an entrepreneur, and these aspects of my background, along with my age (60), give me a different perspective on that whole truth.  (I see a different slice of it.)

Mr. Necasek has responded to my email.  I want to move this discussion from here to email, so that it occurs on neutral territory.  Anyone reading this is welcome to participate.  To do so, send me email at ideafarmcity@gmail.com.
