### ISSUE TITLE
GAS syntax support

### ISSUE THREAD

**Issue by ysangkok** [open-watcom/open-watcom-v2#172]
It would be really nice if there were GAS syntax support, since this would allow using the IA16 port of GCC for compiling, and OpenWatcom for assembling and linking: [How do I assemble GAS assembly and link it with the Open Watcom C library?](http://stackoverflow.com/q/30191000)

Thanks for your efforts.

**Comment by jmalak** [comment]
If I understand this correctly then GAS is gcc specific assembler.
We have no plans to do this, because it is useless for OW.
If you want compile by gcc then it is problem of gcc tools.
You need to modify GAS to support 16-bit.

**Comment by pchapin** [comment]
I believe the syntax used by `gas` is AT&T syntax which is not technically `gcc` specific. That said, I agree with Jiri that supporting that syntax in Open Watcom is probably not a priority. For one thing doing it properly would entail also updating the debugger, `wdis`, and maybe some other tools. So it's a more involved change than one might at first suppose. Also it's unclear to me why @ysangkok wants to compile with gcc and yet assemble and link with Open Watcom.

**Comment by ysangkok** [comment]
The reason that I want to do this, is because gcc doesn't have a libc for DOS and can't use OpenWatcoms (can't parse the headers, doesn't know the object format either).

**Comment by jmalak** [comment]
Why you don't use full Open Watcom toolchain, no similar problems, debugging is posible.
I think that 16-bit optimized code from OW could be better or same size/speed then code generated by gcc.

**Comment by maraakate** [comment]
ysangkok: There is a GCC libc for DOS!  It's called DJGPP!
