### ISSUE TITLE
No implementation of strtok_r

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#175]
Not an "issue" per se since it isn't part of any standard, but Open Watcom doesn't appear to have a reentrant implementation of strtok.  Would people be alright if a reentrant version of strtok were added to Open Watcom's runtime library even though it isn't standards-conformant?   I think it could be a nice addition.  The function signature would be:

```char *strtok_r(char *ptr, char *tokens, char **placeholder);```

If this addition would be problematic, I'll close the issue.  I just wanted some input before implementing anything.

**Comment by jmalak** [comment]
I don't think it is a problem add any extension function. Generaly should be implemented to all OW supported platforms if possible. In header files it should be guarded by one of ext...sp

**Comment by pchapin** [comment]
I believe `strtok_r` is an optional part of POSIX. I only mention this to show that the function is, in some sense, standards-conformant after all. Not that it matters! I think it would be a good addition to the library in any case.

**Comment by ArmstrongJ** [comment]
Commit 65329134f7f0230a7bb9f39d5450d08ff3198067 adds ```strtok_r``` and derivatives for multibyte strings and far pointer equivalents.  The changes were rather simple.  Basically, the reentrant functions are the same code that was present before. If you call the non-reentrant version, it simply calls the reentrant versions with the runtime's pointer to the internal state rather than a user-specified pointer.  Tests were added for the new reentrant versions, and everything seems to be passing.

Thanks for the input!

**Comment by ArmstrongJ** [comment]
Sorry for the header file typos in the original release.  It looks like everything is building fine as of df0e321112faeb2b904c1d3146fff7f24bde74af.

**Comment by jmalak** [comment]
Thanks for contribution.
