### ISSUE TITLE
./build.sh: line 47: builder: command not found

### ISSUE THREAD

**Issue by hzy199411** [open-watcom/open-watcom-v2#182]
when I build on linux x86_64 follow the this guide https://github.com/open-watcom/open-watcom-v2/wiki/Build , I get this error, where can I get builder command?

**Comment by jmalak** [comment]
The builder command is created by this script. It looks like builder was not created for some reason.
Look into bootx.log in root of OW directory tree.

**Comment by hzy199411** [comment]
thank you very much.
