### ISSUE TITLE
orl fails building on ARM platform

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#185]
I'm working on a few minor changes for building to work on the Raspberry Pi as a host platform, and I've run into a snag.  When "builder build" is run inside *bld/orl*, I end up with the following error:

```
============ 21:47:01 /home/jeff/Workspace/open-watcom-v2/bld/orl =============
========= 21:47:01 /home/jeff/Workspace/open-watcom-v2/bld/orl/osi386 =========
cc orlentry.obj
cc orlflhnd.obj
cc orlhash.obj
cc omfload.obj
cc omfmunge.obj
cc omfentr.obj
cc omfflhn.obj
cc omfdrctv.obj
cc elfentr.obj
cc elflwlv.obj
cc elfflhn.obj
cc elfload.obj
cc coffentr.obj
cc cofflwlv.obj
cc coffflhn.obj
cc coffload.obj
cc coffimpl.obj
ar crs orl.lib orlentry.obj orlflhnd.obj orlhash.obj omfload.obj omfmunge.obj omfentr.obj omfflhn.obj omfdrctv.obj elfentr.obj elflwlv.obj elfflhn.obj elfload.obj coffentr.obj cofflwlv.obj coffflhn.obj coffload.obj coffimpl.obj
========= 21:47:08 /home/jeff/Workspace/open-watcom-v2/bld/orl/osix64 =========
===== 21:47:08 /home/jeff/Workspace/open-watcom-v2/bld/orl/test/linux386 ======
cl objread.exe
Error! E2152: file /home/jeff/Workspace/open-watcom-v2/bld/orl/osi386/orl.lib: no dictionary found
Error! E2152: file /home/jeff/Workspace/open-watcom-v2/bld/orl/osi386/orl.lib: no dictionary found
... <repeats a lot> ...
Error: Linker returned a bad status
Error(E42): Last command making (objread.exe) returned a bad status
Error(E02): Make execution terminated
<pmake -d build         -h> => non-zero return: 512
Build failed
```

From what I can see, the `orl.lib` file is properly built using native tools, specifically *ar*.  However, *builder* attempts to build a test project, *orlread.exe* using Watcom's *cl*, resulting in the error.  I can't seem to figure out how to either a) force the test to build using the native compiler or b) skip testing if the host is not a supported target.  I thought it might be quicker to ask here rather than try to troubleshoot this any further.

**Comment by ArmstrongJ** [comment]
Out of interest, I tried `builder build` in the *bld/posix* directory and encountered this same error.

**Comment by ArmstrongJ** [comment]
It occurs to me that perhaps Open Watcom's linker cannot read libraries generated by ARM `ar rcs`. There is a relatively good chance that the generated dictionary within the ".a" file is incompatible with Open Watcom.  Additionally, the ARM `ar` might fail entirely on our object files if it can't read them.

Right now I'm attempting to force using MinGW's `ar` under ARM Linux.

**Comment by ArmstrongJ** [comment]
Still not working using `ar` at all.  If we're creating a library using watcom-compiled components, shouldn't wlib be used instead?

**Comment by ArmstrongJ** [comment]
The build seems to proceed if I force `bwlib` (the just-compiled wlib) to generate the library.

**Comment by jmalak** [comment]
I am afraid not all test program builds are platform independent. It is one of them.
It is necessary to rework build make files to work proper way. Because ARM platform is not supported by OW build make file for ARM host therefore it must use ARM host native tool.

**Comment by jmalak** [comment]
Sorry, forgot it. I overlooked that it is problem with second build phase.
This build phase should use only OW tools build during bootstrap phase which are able run on host but for different target (they have "b" prefix).
The linux386 target must use standard OW tools and formats for x86 Linux. Correct is bwlib tools with appropriate options etc. 
Check variable values for bld_os, bld_cpu, host_os and host_cpu.

**Comment by jmalak** [comment]
Bellow is detailed log from orl buildon 64-bit Linux, it show which command shoud be used on ARM.
Unfortunately osix64 is ot build on ARM, but all others should be same.

======================== 08:40:41 /home/ow/ow/bld/orl =========================
===================== 08:40:41 /home/ow/ow/bld/orl/osi386 =====================
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=orlentry.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/c/orlentry.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=orlflhnd.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/c/orlflhnd.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=orlhash.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/c/orlhash.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=omfload.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/omf/c/omfload.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=omfmunge.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/omf/c/omfmunge.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=omfentr.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/omf/c/omfentr.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=omfflhn.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/omf/c/omfflhn.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=omfdrctv.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/omf/c/omfdrctv.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=elfentr.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/elf/c/elfentr.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=elflwlv.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/elf/c/elflwlv.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=elfflhn.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/elf/c/elfflhn.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=elfload.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/elf/c/elfload.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=coffentr.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/coff/c/coffentr.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=cofflwlv.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/coff/c/cofflwlv.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=coffflhn.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/coff/c/coffflhn.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=coffload.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/coff/c/coffload.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=coffimpl.obj -j -fpi -ms -zc -bt=osi      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/hdr/dos"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/coff/c/coffimpl.c
bwlib -q -b-n-pa  -ii     orl.lib orlentry.obj orlflhnd.obj orlhash.obj omfload.obj omfmunge.obj omfentr.obj omfflhn.obj omfdrctv.obj elfentr.obj elflwlv.obj elfflhn.obj elfload.obj coffentr.obj cofflwlv.obj coffflhn.obj coffload.obj coffimpl.obj
===================== 08:40:45 /home/ow/ow/bld/orl/osix64 =====================
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o orlentry.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/c/orlentry.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o orlflhnd.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/c/orlflhnd.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o orlhash.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/c/orlhash.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o omfload.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/omf/c/omfload.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o omfmunge.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/omf/c/omfmunge.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o omfentr.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/omf/c/omfentr.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o omfflhn.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/omf/c/omfflhn.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o omfdrctv.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/omf/c/omfdrctv.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o elfentr.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/elf/c/elfentr.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o elflwlv.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/elf/c/elflwlv.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o elfflhn.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/elf/c/elfflhn.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o elfload.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/elf/c/elfload.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o coffentr.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/coff/c/coffentr.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o cofflwlv.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/coff/c/cofflwlv.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o coffflhn.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/coff/c/coffflhn.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o coffload.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/coff/c/coffload.c
gcc -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o coffimpl.obj -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__LINUX__ -D__UNIX__ -D__FLAT__      -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/orl/omf/h"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/coff/c/coffimpl.c
ar crs orl.lib orlentry.obj orlflhnd.obj orlhash.obj omfload.obj omfmunge.obj omfentr.obj omfflhn.obj omfdrctv.obj elfentr.obj elflwlv.obj elfflhn.obj elfload.obj coffentr.obj cofflwlv.obj coffflhn.obj coffload.obj coffimpl.obj
================= 08:40:57 /home/ow/ow/bld/orl/test/linux386 ==================
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=test.obj -j -fpi -mf -zc -bt=linux      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/watcom/h" -I"/home/ow/ow/bld/trmem"  -I"/home/ow/ow/bld/hdr/linux"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/test/c/test.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=trmemcvr.obj -j -fpi -mf -zc -bt=linux      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/watcom/h" -I"/home/ow/ow/bld/trmem"  -I"/home/ow/ow/bld/hdr/linux"  -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/trmem/trmemcvr.c
bwcl386 -zq -hd -\"op nored\" -x -xx -zam -\"op symf\" -\"op map\" -mf -j -fpi -bt=linux -fe=objread.exe -fm -l=linux  test.obj trmemcvr.obj /home/ow/ow/bld/orl/osi386/orl.lib
=================== 08:40:58 /home/ow/ow/bld/orl/test/nt386 ===================
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=test.obj -j -fpi -mf -zc -bt=nt -DWINVER=0x400 -D_WIN32_IE=0x300      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/watcom/h" -I"/home/ow/ow/bld/trmem"  -I"/home/ow/ow/bld/hdr/dos" -I"/home/ow/ow/bld/w32api/nt" -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/test/c/test.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=trmemcvr.obj -j -fpi -mf -zc -bt=nt -DWINVER=0x400 -D_WIN32_IE=0x300      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/watcom/h" -I"/home/ow/ow/bld/trmem"  -I"/home/ow/ow/bld/hdr/dos" -I"/home/ow/ow/bld/w32api/nt" -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/trmem/trmemcvr.c
bwcl386 -zq -hd -\"op nored\" -x -xx -zam -\"op symf\" -\"op map\" -mf -j -fpi -bt=nt -DWINVER=0x400 -D_WIN32_IE=0x300 -fe=objread.exe -fm -l=nt  test.obj trmemcvr.obj /home/ow/ow/bld/orl/osi386/orl.lib
================== 08:40:59 /home/ow/ow/bld/orl/test/os2386 ===================
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=test.obj -j -fpi -mf -zc -bt=os2      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/watcom/h" -I"/home/ow/ow/bld/trmem"  -I"/home/ow/ow/bld/hdr/dos" -I"/home/ow/ow/bld/os2api/os2386/h" -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/orl/test/c/test.c
bwcc386 -zq -w8 -we -oaxt -d1 -x -xx -zam -fo=trmemcvr.obj -j -fpi -mf -zc -bt=os2      -DNDEBUG        -I"/home/ow/ow/bld/orl/h" -I"/home/ow/ow/bld/orl/elf/h" -I"/home/ow/ow/bld/orl/coff/h" -I"/home/ow/ow/bld/watcom/h" -I"/home/ow/ow/bld/trmem"  -I"/home/ow/ow/bld/hdr/dos" -I"/home/ow/ow/bld/os2api/os2386/h" -I"/home/ow/ow/bld/watcom/h" /home/ow/ow/bld/trmem/trmemcvr.c
bwcl386 -zq -hd -\"op nored\" -x -xx -zam -\"op symf\" -\"op map\" -mf -j -fpi -bt=os2 -fe=objread.exe -fm -l=os2v2  test.obj trmemcvr.obj /home/ow/ow/bld/orl/osi386/orl.lib
=================== 08:40:59 /home/ow/ow/bld/orl/nt386.dll ====================

**Comment by jmalak** [comment]
Anyway if you want create OW release for ARM with Intel target only than you need to go over OW build tree and and add new build subdirectory for arm (linuxarm) where ...x64 subdirectory (...x64) and change makefile to contains following lines on the top.

#pmake: build os_linux cpu_arm

host_os  = linux
host_cpu = arm

....

**Comment by jmalak** [comment]
I fixed a problem in build make files. Now librarian commands should be handled properly.

**Comment by ArmstrongJ** [comment]
Working now, thanks!
