### ISSUE TITLE
Suspicious checks in CPreviewDC::MirrorMappingMode()

### ISSUE THREAD

**Issue by Dmitry-Me** [open-watcom/open-watcom-v2#191]
Cppcheck found the following in CPreviewDC::MirrorMappingMode()

        while( m_sizeWinExt.cx > -20000 && m_sizeWinExt.cx < 20000 &&
               m_sizeVpExt.cx > -20000 && m_sizeWinExt.cx < 20000 ) {
            m_sizeWinExt.cx <<= 1;
            m_sizeVpExt.cx <<= 1;
        }
        while( m_sizeWinExt.cy > -20000 && m_sizeWinExt.cy < 20000 &&
               m_sizeVpExt.cy > -20000 && m_sizeWinExt.cy < 20000 ) {
            m_sizeWinExt.cy <<= 1;
            m_sizeVpExt.cy <<= 1;
        }

The first `while` has `m_sizeWinExt.cx < 20000` checked twice and the second one has `m_sizeWinExt.cy < 20000` checked twice. This makes no sense. Mot likely `m_sizeVpExt.cx` and `m_sizeVpExt.cy` should be used for the last check respectively.

**Comment by jmalak** [comment]
Thanks for bug report.
It is fixed by commit 0e967343c57ea9c3fefc8f28c47b248b12d370cf in git repository.
