### ISSUE TITLE
Suspicious checks in MIPSInsHook()

### ISSUE THREAD

**Issue by Dmitry-Me** [open-watcom/open-watcom-v2#192]
Currently this line https://github.com/open-watcom/open-watcom-v2/blob/master/bld/ndisasm/core/c/dismips.c#L645 reads

    if( ins->op[0].base == DR_MIPS_r0 && ins->op[0].base == DR_MIPS_r0 ) {

Here the same is being checked twice which makes no sense. I have no idea what should have been done here instead. This was found with Cppcheck.

**Comment by jmalak** [comment]
Thanks for bug report.
It is fixed by f0ac8ea46b8f1ca2b3d5bdda042bc8b650ad6260 in git repository.
