### ISSUE TITLE
debugger diarrhea:  it just runs and runs and runs... (ignores breakpoints)

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#195]
just downloaded source zip and built and cprel.  Now debugger is TOTALLY useable.  Jiri, do you do any testing at all?  The debugger is supposed to execute static global constructors and then break execution at the beginning of main().  It does not do this.  Instead, it runs, and there appears to be no way to stop it.  Setting an explicit breakpoint and telling the debugger to restart does not give the desired result; the explicit bp is ignored!

Jiri, I have the same legal problems as before, and now in addition I have a broken neck and cracked skull and am partially paralyzed from a serious bike accident.  Would you PLEASE fix the God Damned debugger so that I can release IPDOS (tm), which has the potential to bring thousands of motivated users and contributors to OW?  Lift a finger for me today and I will be able to change your world for the better tomorrow.

**Comment by ArmstrongJ** [comment]
I'm seeing similar behavior with breakpoints not being caught with a build from yesterday.  I think a minor bug has been introduced.

@ideafarm please try to keep the bug reports at least somewhat civil for everyone's sake.  I'm not the "speech police" or anything, but aggressive bug reports certainly aren't welcoming for any contributors or users.  Please remember that this project is not in a "release" state, and problems like you've reported are bound to pop up for the foreseeable future.

**Comment by ideafarm** [comment]
The real problem here is that I have a broken neck and am swamped with legal, financial, and serious medical problems.  I still hope to adopt wdw and become its champion, tester, and bug fixer.  But with this broken neck and paralysis of my left arm, I can only hope that someone will be motivated to lift a finger to help.  OW is a stunningly beautiful tool, and I don't really have a problem with Jiri's wonderfully productive style of working.  Please, please, will someone please work with me to debug wdw, please?  I'll work with you to test and whatever.  If someone will work with me, I will find some time so that the two of us can restore WDW to its rightful glory.

The release of IPDOS (tm) is just around the corner.  A few helping hands to clean up WDW will bring a major new application of OW out, which could attract many contributors and end users.  Please help.  I've got a huge vision and am one of the most experienced C++ craftsmen alive, but I'm in a real fix and need some people to join me in a "ONE FOR ALL - ALL FOR ONE" effort to deliver this baby.

**Comment by jmalak** [comment]
I am sorry for trouble. I did only basic test with C source that I can go with it.
I will look on this problem and fix it ASAP.
Anyway I did some changes in Dwarf code to become more standard conforming and prepare it for future implementation of Dwarf 3/4/5 specification and features.

**Comment by ideafarm** [comment]
Am building IPDOS (tm) with the latest build even though WDW cannot be used, because I've noticed two very nice improvements: (1) compile is faster, and (2) a compiler or linker bug has been eliminated.  As soon as you have something for me to test, I will rebuild from source and try it.

**Comment by jmalak** [comment]
It is fixed
