### ISSUE TITLE
Unicode Version of "system()" Fails On Vista

### ISSUE THREAD

**Issue by CyberSimian** [open-watcom/open-watcom-v2#199]
I compiled the program below on Windows XP, using "wcl386" with no options specified.  The program runs correctly on WinXP, but fails on Vista with return code -1.  However, the identical program compiled using the Microsoft C compiler in MS SDK7 runs correctly on both WinXP and Vista.  I encountered this problem first with OW 1.9, but OW 2.0 has the same problem.

Edit: I have changed the angle-brackets on the include statements to quotes, otherwise the XML system causes the file names to be omitted.

/\* unitest.c */
# define UNICODE
# include "stdlib.h"
# include "stdio.h"
# include "wchar.h"

int wmain()
{
  int rc;

  rc = _wsystem( L"dir" );
  if ( rc != 0 )
  {
    wprintf( L"shell could not be run, rc=%d\n", rc );
  }

  return(rc);
}

**Comment by jmalak** [comment]
Thanks for your report.
Please, what version of Vista you use 32-bit or 64-bit?

**Comment by CyberSimian** [comment]
I am using the 32-bit version of Vista (and also WinXP).

**Comment by jmalak** [comment]
I am sorry but I have no Vista installation, are you able to crete Virtual box VM image of Vista for me?

**Comment by CyberSimian** [comment]
I regret that I do not know what Virtual Box is, and I do not have time at the moment to learn a new tool.  Sorry about that.

As I have a work-around (i.e. the Microsoft compiler), I would suggest putting this problem "on the back burner", and waiting for another user to raise the same problem.  Hopefully they will be able to help you identify the cause of the problem.

**Comment by jmalak** [comment]
OK, no problem.
I will try to get copy of VirtualBox image for Windows Vista somewhere to be able reproduce the problem and find what incompatibility cause this problem.

**Comment by CyberSimian** [comment]
I have looked at the OW source code to see if I could identify the cause of this problem.  The following code does not look correct (but I may have misunderstood what things mean).  This code resides in the file "...\bld\clib\process\c\dospnwnt.c".  Note: this ridiculous posting system insists on removing leading and trailing underscores, so the macro names shown below will probably not correspond to what is in the source code:

[code]
ifdef __WIDECHAR__
    #if defined(__AXP__) || defined(__PPC__)
        osrc = CreateProcessW( NULL, cmdline, NULL, NULL, TRUE,
                               CREATE_UNICODE_ENVIRONMENT, envp,
                               NULL, &sinfo, &pinfo );
    #else
        osrc = __lib_CreateProcessW( cmdline, TRUE, envp, &pinfo );
    #endif
#else
    osrc = CreateProcessA( NULL, cmdline, NULL, NULL, TRUE, 0,
                           envp, NULL, &sinfo, &pinfo );
#endif
[/code]

There are three paths through this macro logic.  What looks wrong is that the path for AXP and PPC passes through the code for "CreateProcessW".  Now I was under the impression that AXP and PPC are alternatives to Intel.  So Intel takes the path that passes through "_lib_CreateProcessW".  It looks to me as though these should be interchanged:

Unicode AXP and PPC should pass through: "_lib_CreateProcessW".
Unicode Intel should pass through: "CreateProcessW".
ASCII Intel should pass through: "CreateProcessA".

-- from CyberSimian in the UK

**Comment by ArmstrongJ** [comment]
This posting system uses the very common Markdown system.  If you want to post pre-formatted code, you can just use ``` on a line by itself.  

It can even do syntax highlighting if you do \`\`\` followed by the language (```C in this case):

```C
#include <stdio.h>
int main(int argc, char *argv[])
{
```
You just need to close the preformatted section with another \`\`\`.

And I think you're right, shouldn't it just use `CreateProcessW` on x86/x64?

**Comment by jmalak** [comment]
It is fix for Windows 9x UNICODE layer. 
If you look into bld/clib/libwin32/c/crtproc.c the CreateProcessW is used for NT systems (Intel) and for 9x is extra code. It has no sense on AXP and PPC (Windows 9x doesn't exist for these platforms).

**Comment by jmalak** [comment]
Anyway you refere to old OW1.9 CRTL code. Look into our OW 2.0 CRTL code, where it is much transparent.

**Comment by CyberSimian** [comment]
ArmstrongJ: Thank you for explaining how to post source code correctly!

jmalak: Yes, I have returned to using OW 1.9 because OW 2.0 does not pass back the return code correctly when a compilation has warning messages (returns zero instead of non-zero).  That is quite catastrophic for my build system which relies on testing return codes to determine whether there are errors/warnings present.

With regard to the original problem: I have found a programming example on the Microsoft web site; this page:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms682512%28v=vs.85%29.aspx

The example on that page works on Vista when compiled for ASCII (in my tests: using OW 1.9).  But it does not work correctly when compiled for UNICODE.  I have made some changes that allow it to work correctly when compiled for UNICODE (see below).   Of course, this programming example does not deal with the complexity of the general case, so the OW code that implements "system()" and "wsystem()" will obviously be much more complicated.  Nevertheless, it does provide a working example that I (and others) can use until the problem is solved.

-- from CyberSimian in the UK

Compile and link as follows:
ASCII: wcl386 example.c
UNICODE: wcl386 example.c /dUNICODE

'''C
/* added: next 3 lines */
#if defined(UNICODE)
  #define _UNICODE
#endif

#include <windows.h>
#include <stdio.h>
#include <tchar.h>

void _tmain( int argc, TCHAR *argv[] )
{
    STARTUPINFO si;
    PROCESS_INFORMATION pi;

    /* added: next 2 lines */
    _tprintf( __T("This is the %s version.\n"),
      ( sizeof(TCHAR) == 2 ? __T("UNICODE") : __T("ASCII") ) );

    ZeroMemory( &si, sizeof(si) );
    si.cb = sizeof(si);
    ZeroMemory( &pi, sizeof(pi) );

    if( argc != 2 )
    {
        /* changed: printf -> _tprintf; added: __T( ) */
        _tprintf( __T("Usage: %s [cmdline]\n"), argv[0]);
        return;
    }

    // Start the child process.
    if( !CreateProcess( NULL,          /* No module name (use command line)  */
        argv[1],                       /* Command line                       */
        NULL,                          /* Process handle not inheritable     */
        NULL,                          /* Thread handle not inheritable      */
        FALSE,                         /* Set handle inheritance to FALSE    */
        /* changed: 0 -> CREATE_UNICODE_ENVIRONMENT */
        CREATE_UNICODE_ENVIRONMENT,    /* No creation flags                  */
        NULL,                          /* Use parent's environment block     */
        NULL,                          /* Use parent's starting directory    */
        &si,                           /* Pointer to STARTUPINFO structure   */
        &pi )                    /* Pointer to PROCESS_INFORMATION structure */
    )
    {
        /* changed: printf -> _tprintf; added: __T( ) */
        _tprintf( __T("CreateProcess failed (%d).\n"), GetLastError() );
        return;
    }

    // Wait until child process exits.
    WaitForSingleObject( pi.hProcess, INFINITE );

    // Close process and thread handles.
    CloseHandle( pi.hProcess );
    CloseHandle( pi.hThread );
}
'''

**Comment by jmalak** [comment]
Thanks for link to original source.
I am surrprised that you didn't create bug report for compiler problem with incorrect return code. I will check and correct compiler if return wrong walue.

**Comment by CyberSimian** [comment]
I will open a separate bug report (with a test case).

-- from CyberSimian in the UK

**Comment by CyberSimian** [comment]
Before I forget it, I will mention that there are two differences that I noticed between the code in "dospnwnt.c" and the Microsoft programming example:

(1) The MS example sets the byte-count field in the STARTUPINFO structure; OW does not.

(2) The MS example nullifies the PROCESS_INFORMATION structure; OW does not.

I don't know whether either of these differences matters.  But remember that the UNICODE version of "system()" works OK on WinXP; it is Vista (and possibly later versions) where it fails.  Maybe Vista now looks at the byte-count field and/or the contents of PROCESS_INFORMATION whereas earlier versions of Windows did not.

-- from CyberSimian in the UK

**Comment by jmalak** [comment]
You are right, setup of length field for OW 1.9 code is missing, in OW2.0 CRTL it was fixed.
Zeroing of PROCESS_INFORMATION structure is missing in both versions.
Missing setup for length field could be a problem (we fixed it in OW2.0).

**Comment by jmalak** [comment]
It looks like the handling of wFlags and wShowWindow members of STARTUPINFO structure is not correct in some case over all OW.

**Comment by jmalak** [comment]
I reviewed all calling of CreateProcess API function on NT platform in OW2.0 and fix a few issues in git repository 53b63ad2cf5c9f644a3f6d4b3b77206b0cf9cbb0:
- missing setup of length field in STARTUPINFO (1x)
- missing flag STARTF_USESHOWWINDOW for dwFlags member of STARTUPINFO (9x)
It could be useful for you if you want correct OW1.9

**Comment by jmalak** [comment]
Please, do you have any update to this issue after all fixes in C run-time Library and C compiler?

**Comment by CyberSimian** [comment]
jmalak:
Thank you for making the fixes to the compiler to address this issue.  However, I have not tested them as I don't know what to do with your changes (I cannot build the compiler to include your changes).  I was waiting for the next release of OW v2 before trying your changes.

In the meantime, I wrote my own interface function "system_cmd()".  It invokes the OW "system()" for DOS and OS/2, and uses code based on the Microsoft example for 32-bit Windows.  This works correctly on WinXP and Vista, for both ASCII and UNICODE.

-- from CyberSimian in the UK

**Comment by jmalak** [comment]
You can download current version here
[Approximatrix buildbot - Open Watcom V2 builds](http://buildbot.approximatrix.com/releases/)

**Comment by ArmstrongJ** [comment]
Looks like builds have been failing for the last few days, though.   I'm looking at it right now.

**Comment by ArmstrongJ** [comment]
Looks like the builds are proceeding again at [http://buildbot.approximatrix.com/waterfall](the Buildbot server).  They had been failing due to recent changes in environment variables (the server doesn't use `build.sh` directly).

**Comment by CyberSimian** [comment]
I downloaded the build dated 2016-06-22, unzipped it, and used it to replace my current "ow200" directory.  I then set the OW environment variables to use the "ow200" directory (instead of my default "ow190" directory), and recompiled the test program that I included in the very first post.  I did this on WinXP, which is my development system.  The file "unitest.exe" resulting from the compile works correctly on WinXP.  I then moved it to my Vista system and tested it there.  Unfortunately, it still fails.

I recompiled my application using the new "ow200" with my own "system_cmd()" function, and that still works (both on WinXP and Vista).  This is the relevant code from my "system_cmd()" function; you won't be able to compile it, as it uses macros of my own, but you should be able to see what I am doing:

```
    /********************************/
    /* pass cmd to operating system */
    /********************************/

    /* set parms for "CreateProcess()" */
    #if defined(UNICODE)
      create_flags=CREATE_UNICODE_ENVIRONMENT;
    #else
      create_flags=0;
    #endif
    memset(&sinfo,0,BYTES(sinfo));
    sinfo.cb=BYTES(sinfo);
    memset(&pinfo,0,BYTES(pinfo));

    /* start the child process */
    ok=CreateProcess(NULL,             /* no module name (use command line)  */
                     buffer,           /* command line                       */
                     NULL,             /* process handle not inheritable     */
                     NULL,             /* thread handle not inheritable      */
                     FALSE,            /* set handle inheritance to FALSE    */
                     create_flags,     /* creation flags                     */
                     NULL,             /* use parent's environment block     */
                     NULL,             /* use parent's starting directory    */
                     &sinfo,           /* STARTUPINFO structure              */
                     &pinfo);          /* PROCESS_INFORMATION structure      */
    /* check outcome */
    if (!ok)
      RETURN_INT(RC_UNEXPECTED_ERROR);

    /* wait for child process to finish */
    WaitForSingleObject(pinfo.hProcess,INFINITE);
    ok=GetExitCodeProcess(pinfo.hProcess,&rc);
    if (!ok)
      rc=RC_UNEXPECTED_ERROR;

    /* close process and thread handles */
    CloseHandle(pinfo.hProcess);
    CloseHandle(pinfo.hThread);

    RETURN_INT(rc);
```

-- from CyberSimian in the UK

**Comment by jmalak** [comment]
issue #718 was fixed and it looks very similar to this one.
