### ISSUE TITLE
Don't add unreferenced symbols from modules

### ISSUE THREAD

**Issue by TobiasKarnat** [open-watcom/open-watcom-v2#204]
Could the behaviour change so that only required symbols from a module are added by the linker?

**Comment by jmalak** [comment]
Please, be more specific.
What you mean by "only required symbols from module"?

it is debug information issue
It has no much sense minimise symbolic info.
OW linker automaticaly add all referenced symbols (static or global) by default.
You can control it by various OW linker options, a few of them:
DEBUG .. ONLYEXPORTS
DEBUG .. REFERENCED
See OW linker user guide for details

**Comment by TobiasKarnat** [comment]
I mean the symbols or functions which are required for the application from a module.
Using linker option ELIMINATE only removes whole unreferenced modules.
But the linker can't pick single functions from modules?:
```
* = unreferenced symbol

Module: C:\WATCOM\lib386\math387r.lib(atan87.asm)
0001:00019cfa* atan_
0001:00019d06* atan2_
0001:00019cd0* IF@ATAN
0001:00019cd0* IF@DATAN
0001:00019ce5* IF@ATAN2
0001:00019ce5  IF@DATAN2
```

**Comment by TobiasKarnat** [comment]
Could each function from an external library be placed into a separate segment (like option -zm) in order to eliminate the unused?

**Comment by jmalak** [comment]
If you want maximize elimination of unused code then you should combine compilation with -zm option and ELIMINATE option for linking.

**Comment by jmalak** [comment]
Anyway, you can not change structure of code in one module because it is hard to say what is realy dead code, some part of code can be copied to other location etc. If some symbol is not referenced it doesn't mean that code is dead, there can be pointer calculation, etc

**Comment by TobiasKarnat** [comment]
I tried the -zm and ELIMINATE option, but this only has an effect on my own code not on the functions from watcom.
Anyway there are only a few unreferenced functions, it wouldn't probably be worth the effort.

**Comment by jmalak** [comment]
You are right. If some code is not compiled with -zm (by example libraries) then efect of ELIMINATE during linking is minimal.

**Comment by TobiasKarnat** [comment]
Thank you for the clarification.
