### ISSUE TITLE
C code generation

### ISSUE THREAD

**Issue by beketata** [open-watcom/open-watcom-v2#209]
<pre>
I am using wcc.exe as a C compiler to generate code for 80186 embedded system.
Used options for wcc are the next:
-1 -od -zl -ml -s -zu -zdp -bt=rawbin

Here is an example of a fictional C code:

  char fn()
  {
    char ch = 7;
    return ch;
  }

wcc generates the next instructions from the C code above:

  var_4 = byte ptr -4
  var_2 = byte ptr -2

  push    bx
  push    cx
  push    dx
  push    si
  push    di

  <b>push    bp</b>
  <b>mov     bp, sp</b>
  <b>sub     sp, 4</b>

  mov     [bp+var_2], 7
  mov     al, [bp+var_2]
  mov     [bp+var_4], al
  mov     al, [bp+var_4]

  <b>leave</b>

  pop     di
  pop     si
  pop     dx
  pop     cx
  pop     bx

  retf

Instruction <b>leave</b> is present here, but what about <b>enter</b>?
My question is: how to force compiler generate <b>enter</b> instruction instead of

  push    bp
  mov     bp, sp
  sub     sp, 4
</pre>

**Comment by jmalak** [comment]
I think the reason for this is performance. Intel ENTER instruction is very uneficient that code generator doesn't use it for speed optimization. It is used only for 80186 processor and size optimization.
