### ISSUE TITLE
wbind segfaulting on Kubuntu14.04 (but still succeeding)

### ISSUE THREAD

**Issue by ssokolow** [open-watcom/open-watcom-v2#211]
I've tested the following with the 1.9 release, the 2.0 beta on SourceForge, and the [2015-11-16 buildbot build](http://buildbot.approximatrix.com/releases/openwatcom-2015-11-16.zip) 

    wcl386 -q -bt=windows -l=win386 "$SRC_FILE" -fe="$outfile".rex $3
    wbind "$outfile".exe -nq -s "$WATCOM/binw/win386.ext"

...and, in all three cases, it segfaults but still produces a binary which works under Wine 1.7.50.

    Segmentation fault      (core dumped) wbind "$outfile".exe -nq -s "$WATCOM/binw/win386.ext"`

The code in question is available at https://github.com/ssokolow/game_launcher/tree/master/test_exes and uses the `WATCOM` variable to find Open Watcom, defaulting to `~/opt/openwatcom` in case you don't want to modify the system environment.

(That's where I manually `unzip`ed the installers to bypass a `SIGFPE` in `GUIGetRoundScale_`. Judging by the unhelpful gdb output, my best guess is that it doesn't like triple-head 3840x1024 desktops at 85dpi.)

**Comment by jmalak** [comment]
Please, could you try wbind command without -s option.
wbind should find WIN386 extender automaticaly.
-s option has sense if you have non-standard location of WIN386 extender.

**Comment by jmalak** [comment]
I have a question, wbind is command line tool that can not depend on GUI.
Do you run it from OW IDE or from command line?

**Comment by ssokolow** [comment]
> Please, could you try wbind command without -s option.
> wbind should find WIN386 extender automaticaly.

Done. There's no change in wbind's behaviour, but thanks for pointing out something else I can do to simplify my script.

> I have a question, wbind is command line tool that can not depend on GUI.
> Do you run it from OW IDE or from command line?

I don't even know *how* to launch the OW IDE and, given that there's an `ide.exe` in the various non-Linux bin folders but no equivalent binary under `binl`, I don't think I even can.

 I'm running `wbind` from the `build.sh` script in the repository I linked. (A script which began with DJGPP and MinGW cross-compilers and gained Open Watcom later.)

**Comment by jmalak** [comment]
It is bug in wbind utility.
It suppose that you create executable for 16-bit Windows that file name length can be only 8 characters. Your name is much longer that you will have a problem with run under 16-bit Windows (no LFN support).
Anyway now it is fixed in OW git repository, that you can recompile wbind utility.
File name length more then 8 characters are truncated and don't cause any trouble.

**Comment by ssokolow** [comment]
Thanks. Given that the purpose is to generate test data with clean copyright for EXE analysis routines and actually running them on systems restricted to 8.3 isn't planned, not an ideal solution, but it's already special-cased, so using purely 8.3 filenames before a final `mv` call won't be any more bothersome. 

(I try to retain maximum compatibility with the 1.9 and 2.0 beta release builds so I can easily point potential contributors to a known compatible release)
