### ISSUE TITLE
Debugger: loading "setup.dbg" ERROR

### ISSUE THREAD

**Issue by beketata** [open-watcom/open-watcom-v2#214]
1. Start wdw.exe
2. Close "New Program" popup window
3. Open any window, say "Code / Assembly"
3. Save setup via "File / Save Setup" menu with replacement of existing "setup.dbg" file
4. Close wdw and reopen it again
5. ERROR message box appears with the next message:
```
Expecting '<'.
  Error occured near '80'.
  Executing at line 29 in the file 'setup.dbg'.
  Called from line 2 in file 'wd.dbg'.
```
Contents of line 29 of 'setup.dbg'
```
display assembly /open 80,774,1335,2907
```

**Comment by beketata** [comment]
Some time later I figured out it's a bug in the C compiler.
The next simple code simulates **static int GetWord( void )** method from **dbgwalk.c**
It's output to the console **0x0102** instead of expected **0x0201**
```
#include <stdio.h>
#include <conio.h>

typedef unsigned short word;
typedef unsigned char byte;

byte* TblPtr;
byte buf[] = { 1, 2, 3, 4 };

int main()
{
  word iret;
  TblPtr = buf;

  iret = ( (word)( ( *TblPtr++ ) | ( *TblPtr++ << 8 ) ) );

  printf( "0x%04X\n", iret );

  getch();

  return 0;
}
```

**Comment by jmalak** [comment]
Thanks for bug report and your analysis.
It is example of my stupid mistake in coding (undefined behaviour).
It is side-efect of C language expression evaluation.
I checked it with various compilers
gcc result is 0x0201
msvc result is 0x0101
OW result is 0x0102
Anyway I will fix this code to be realy portable.

**Comment by beketata** [comment]
I also checked the latest version of the msvc and got the same error 0x0101.
But using of parentheses should solve the problem with an operations sequence in any case!

**Comment by jmalak** [comment]
Now it is fixed in git repository
