### ISSUE TITLE
wdis -a generates poo

### ISSUE THREAD

**Issue by sparky4** [open-watcom/open-watcom-v2#217]
it made ???? lines

what dose this mean??

also i wish there was an 8088 option

[pee.txt](https://github.com/open-watcom/open-watcom-v2/files/59553/pee.txt)

**Comment by jmalak** [comment]
Line with ??? means wdis is not able disassembly instruction (probably invalid code or some new instructions which is not implemented). In your case it looks like you try disassembly data in segment not code. Normaly OW compilers emit information for OW disassembler to know where is data and where is code in the segment. Probably you disassembly code created by non-OW compilers.
Why you need 8088 option?

**Comment by sparky4** [comment]
to make 8088 assemable code ^^;  anyway thank you!

**Comment by jmalak** [comment]
How is 8088 code different from 8086?

**Comment by sparky4** [comment]
i mean to differentiate it from 386 code ^^;

**Comment by jmalak** [comment]
OK. Segment bitnees is defined by OMF format for each segment that you are able disassembly modules with mixed bitnees.

**Comment by sparky4** [comment]
ok
