### ISSUE TITLE
Can I selective disable warning messages for cl.exe tool?

### ISSUE THREAD

**Issue by Mazdaywik** [open-watcom/open-watcom-v2#218]
When I use option -Wall I got some value warning messages but a lot of junk messages. I want filter it, but cl.exe tool don’t support Visual Studio option /wdXXXX and other option with this sense I not found.

Other tools (native wcl386 and POSIX owcc) has other bugs, I can’t use it.

**Comment by jmalak** [comment]
You can use /passwopts:....... to directly pass OW compilers option.

What problem you have with owcc?

**Comment by Mazdaywik** [comment]
> You can use /passwopts:....... to directly pass OW compilers option.

Thanks! It is works!

> What problem you have with owcc?

#219 only. But I want write [my program][1] with wide compatibility with many different C++ compilers (see [c-plus-plus.conf.bat][2]), and then it will be compile with new Open Watcom 2.0 and original Open Watcom 1.9. In original Watcom 1.9 forward slashes (#220) don't run in owcc and wcl386 both.

--

And can you add option /wdXXXX to `cl.exe` tool according to [principle of least surprise][3]? This feature request can have very low level priority.

[1]: https://github.com/Mazdaywik/simple-refal
[2]: https://github.com/Mazdaywik/simple-refal/blob/master/c-plus-plus.conf.bat
[3]: https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by jmalak** [comment]
Note to /wdXXXX option.
cl is MS VC driver that it should handle only VC command line options.
Message numbers in VC and in OW are not map anyway.
If you need something specific for OW use always /passowopts:  option. Add new option to cl driver  create incompability with previous cl drivers and has no sense if we have /passowopts option.
