### ISSUE TITLE
Not an issue but maybe interesting

### ISSUE THREAD

**Issue by revelator** [open-watcom/open-watcom-v2#22]
http://sourceforge.net/projects/cbadvanced/files/Open%20Watcom/stlport-watcom-2.0.7z/download

My port of STLPORT for Open Watcom. 

32 bit windows target only "like the old one".  

I used static runtime libraries though so this version can be used with later versions of Open Watcom with some adjustments to the config header.

**Comment by abm-1980** [comment]
If it fully supports the STLport, what configurations do I have to make so that the compiler can work perfectly? Which version of STLport can I use? Is it the latest release?

**Comment by revelator** [comment]
watcoms stl supports more functions now than when i last built stlport, 
so it would need some patching to get around those.
Also watcoms stl uses non standard exports, so its not even certain it can be done without rewriting a good part of stlport. 
Clangs libc++ might be the better answer if we one day want a complete stl, it also supports C++11 and OrangeC from ladsoft allready uses it, i might get some ideas from looking at his version.
