### ISSUE TITLE
Compiler error about bool bitfields larger than type

### ISSUE THREAD

**Issue by jrmuizel** [open-watcom/open-watcom-v2#222]
I get the following error when trying to compile:
cc vicomp.obj
In file included from ../../h/vi.h:49:0,
                 from ../../c/vicomp.c:32:
../../h/struct.h:55:5: error: width of ‘spare’ exceeds its type
     bool            spare           : 2;

This seems like a reasonable thing to complain about.

**Comment by jmalak** [comment]
Thanks for bug report.
I will fix it ASAP.

**Comment by jmalak** [comment]
Now it is fixed in git repository by 15ae8541fd22a1ba279e6a84348a6fd51efa797a
