### ISSUE TITLE
Error! E1078: Invalid type for switch expression

### ISSUE THREAD

**Issue by jbailey8** [open-watcom/open-watcom-v2#223]
I was trying to compile nasm with the git version of the open watcom compiler (I compiled it with
the 2015 version of the intel compiler), and I get the error: 

Error! E1078: Invalid type for switch expression

Here's the code in question:

 switch (opsize) {
    case BITS64:
        brcast_num = BITS64 / brsize;
        break;
    default:
        brcast_num = (opsize / BITS128) * (BITS64 / brsize) * 2;
        break;

Anyone know when open watcom (git) will support this?

Thanks!
jbailey8@triad.rr.com

**Comment by jmalak** [comment]
Sorry it is unclear.
What type is opsize. BITS64 is probably constant but what value/type?

**Comment by jbailey8** [comment]
Here's more code:

-----------------------------------

static uint8_t get_broadcast_num(opflags_t opflags, opflags_t brsize)
{
    opflags_t opsize = opflags & SIZE_MASK;
    uint8_t brcast_num;

    /*
     * Due to discontinuity between BITS64 and BITS128 (BITS80),
     * this cannot be a simple arithmetic calculation.
     */
    if (brsize > BITS64)
        errfunc(ERR_FATAL,
            "size of broadcasting element is greater than 64 bits");

    switch (opsize) {
    case BITS64:
        brcast_num = BITS64 / brsize;
        break;
    default:
        brcast_num = (opsize / BITS128) * (BITS64 / brsize) * 2;
        break;
    }

---------------------

Here's the command line output:

wcl386 -c -za99 -zq -6 -ox -wx -ze -fpi  -bt=NT -I"c:\owcurrent/h" -I"c:\owcurrent/h/nt" -I. -I. -DHAVE_CONFIG_H -fo=assemble.obj assemble.c
assemble.c(2122): Error! E1078: Invalid type for switch expression
assemble.c(2123): Error! E106: Constant out of range - truncated
Error: Compiler returned a bad status compiling "assemble.c"

----------------------

In my opinion, it seems the openwatcom doesn't support 64 bit switch expressions, there's no real 
rush on this, I was just wondering if/when this would be supported.

I tried to attach the file in question, but this site won't accept it in any form seemingly, Here's the git
link for nasm, the file file in question is assemble.c.

git://repo.or.cz/nasm.git

**Comment by jmalak** [comment]
github accept only a few extension for files. Simply add .txt extension and you can add any source file.

Yes, OW code generator doesn't support 64-bit switch value.  I have it on to-do list, but priority is not high.

**Comment by jbailey8** [comment]
That's ok, as long as you'll get that added at some point.

Thanks!

**Comment by winspool** [comment]
> Yes, OW code generator doesn't support 64-bit switch value. I have it on to-do list, but priority is not high.

Support for 64 bit switch values is still not implemented.
I got the E1078 Error from `wcc386`, when i tried to build the bootstrap for "zig".
```
<my_zig_checkout>/stage1/InputStream.h(168): Error! E1078: Invalid type for switch expression
<my_zig_checkout>/stage1/wasm2c.c(34): Error! E1078: Invalid type for switch expression
<my_zig_checkout>/stage1/wasm2c.c(386): Error! E1078: Invalid type for switch expression
```
Link to the first error location:
https://github.com/ziglang/zig/blob/master/stage1/InputStream.h#L168
```
        int64_t val_type = InputStream_readLeb128_i64(self);
        switch (val_type) {
```

The c++ compiler `wpp386` produces a different error message:
`stage1/InputStream.h(168): Error! E870: col(17) implementation restriction: cannot use 64-bit value in switch statement`
