### ISSUE TITLE
wcl

### ISSUE THREAD

**Issue by sparky4** [open-watcom/open-watcom-v2#224]
Where is wcl?? when i compile newer versions of open watcom newer versions wcl dose not appear

**Comment by jmalak** [comment]
You should get some error in build log if it is not build for some reason.
wcl exwcutable is located in bld/wcl/i86/.... and appropriate host subdirectory after building.
in release tree it is in appropriate host bin... subdirectory.

**Comment by sparky4** [comment]
ok i will check it out

**Comment by sparky4** [comment]
gcc -pipe -shared  -O -g -o dwarf.so  -Wl,-Map,dwarf.map dipimp.obj dfmisc.obj dfld.obj dfmod.obj dfmodbld.obj dftype.obj dfsym.obj dfaddr.obj dfsegs.obj dfloc.obj dfcue.obj dfline.obj dfaddsym.obj dfscope.obj dfhash.obj demangle.obj /home/sparky4/p/watcom2/bld/dwarf/dr/osix64/dwarfr.lib /home/sparky4/p/watcom2/bld/watcom/binbuild/clibexts.lib
/usr/bin/ld: dfaddr.obj: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Error(E42): Last command making (dwarf.so) returned a bad status
Error(E02): Make execution terminated
<pmake -d build         -h> => non-zero return: 512
Build failed

**Comment by jmalak** [comment]
Did you clean before build?
Try to rebuild dwarf project with clean before build.

**Comment by sparky4** [comment]
i can try

**Comment by jmalak** [comment]
go to bld/dwarf and run "builder clean", next run "builder build".

**Comment by sparky4** [comment]
ok

**Comment by sparky4** [comment]
[21:56:03][~/p/watcom2/bld]
[sparky4@lappy4]$ wcl
Open Watcom C/C++ x86 16-bit Compile and Link Utility
Version 2.0 beta Jan 16 2016 17:42:29 (64-bit)

SWEET IT WORKS!! THANKS!!
