### ISSUE TITLE
Debug build broken?

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#228]
In the 1.9 version, it was possible to build debug versions of components by using the DEBUG_BUILD environment setting, but this doesn't seem to work anymore. I need to build a debug version of wd in order to debug wd, so therefore I need full symbolic information in wd. Any suggestions how to do this?

**Comment by rdos314** [comment]
Apparently, the setting has changed to OWDEBUGBUILD.

**Comment by jmalak** [comment]
All environment variables used by OW build system now start with OW... prefix.
I will create list of environment variables used by OW build system with some comment to be documented.
