### ISSUE TITLE
Update precompiled binaries

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [open-watcom/open-watcom-v2#231]
@jmalak precompiled binaries at Sourceforge, are almost 1 year old.
Are you planning to update them soon?

**Comment by jmalak** [comment]
I am working on debugger now.
As soon as I will have stable version I plan to create new binaries and put them on Sourceforge.

**Comment by sparky4** [comment]
yay!! ^^

**Comment by javiergutierrezchamorro** [comment]
I guess we can close it thanks to the Travis CI integration: https://github.com/open-watcom/travis-ci-ow-builds/tree/master/rel

**Comment by jmalak** [comment]
I agree
