### ISSUE TITLE
C compiler. How to place const data in the CODE seg?

### ISSUE THREAD

**Issue by beketata** [open-watcom/open-watcom-v2#233]
The question is for embedded system.
I want to place all const data in the CODE seg (in ROM). How could I do that?

For example, in the Microchip C compiler there is a **#pragma romdata** for this purpose.

**Comment by jmalak** [comment]
You can use option -zc for compiler.
The "zc" option causes the code generator to place literal strings and const items in the code segment. This option is supported in large data or flat memory models only, or if the item is explicitly
"far".

**Comment by beketata** [comment]
Thank you so much!
