### ISSUE TITLE
linking C objects with assembly objects?

### ISSUE THREAD

**Issue by sparky4** [open-watcom/open-watcom-v2#234]
How is this done in open watcom?

**Comment by Azarien** [comment]
Assemble your .asm files with assembler of your choice, compile your .c files with wcc386, then link all resulting .obj's with wcl386.

**Comment by jmalak** [comment]
If you mix assembly modules with c modules you must properly call function in assembly modules from C and vice-versa. There can be problem with symbol name mangling in C and function parameter passing. For details read OW Open Watcom C/C++ User’s Guide sections 16/32-bit Assembly Language Considerations and section 16/32-bit Pragmas.

**Comment by sparky4** [comment]
thank you~
