### ISSUE TITLE
Odd Inconsistencies in setjmp.h

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#235]
While we are within [POSIX standards](http://pubs.opengroup.org/onlinepubs/7908799/xsh/setjmp.h.html) with the OpenWatcom implementation of setjmp.h, there are a few strange inconsistencies in the header file.  Specifically, a few things bother me:

* We define `_setjmp` and `longjmp` as functions, but `setjmp` as a macro and no `_longjmp`
* We only define `setjmp` if *_SETJMPEX_H_INCLUDED_* is not included, but that macro is not defined anywhere in the Open Watcom source tree
* We define `sigsetjmp` as a macro, but `siglongjmp` as a function

I'm running into some code in an autotools configure script that seems to be confused by the function/macro pairings (as opposed to at least having one setjmp/longjmp pair both defined as functions).  Other than missing `_longjmp` entirely, though, we are within POSIX standards.  I'm just wondering if anyone has any input on why these are defined as described.

**Comment by jmalak** [comment]
I don't think that POSIX define if setjmp is macro then longjmp must be macro too and vice-versa.
In latest POSIX is
The following shall be declared as functions and may also be defined as macros. Function prototypes shall be provided.
void   _longjmp(jmp_buf, int);
void   longjmp(jmp_buf, int);
void   siglongjmp(sigjmp_buf, int);
The following may be declared as functions, or defined as macros, or both. If functions are declared, function prototypes shall be provided.
int    _setjmp(jmp_buf);
int    setjmp(jmp_buf);
int    sigsetjmp(sigjmp_buf, int);

Problem is with tools that they relate to some assumption which is not true in POSIX.
Anyway in OW setjmp is macro to be able redefine setjmp for ALPHA architecture in setjmpex.h.
We must take into account also backward compatibility and compatibility with MS VC.
I am not sure if it is something against POSIX standard.

**Comment by jmalak** [comment]
I did a little investigation about setjmp/longjmp class of functions.

ISO C defines
setjmp as macro
longjmp as function

POSIX defines
setjmp/sigsetjmp undefined what kind it is
longjmp/siglongjmp undefined what kind it is

_setjmp/_longjmp is XSI (X/Open System Interfaces) extension and can be removed in the future
I don't think we should implement it

It looks like OW is ISO C conformant only

**Comment by ArmstrongJ** [comment]
Thanks for investigating this!  I was simply a little confused about what was going on inside that header.  If the *SETJMPEX_H_INCLUDED* is a macro for the Alpha architecture, it should definitely stay.  

Wouldn't we be POSIX-compliant, though, since we do define setjmp/sigsetjmp and longjmp/siglongjmp?  I think we actually do meet that requirement.

The code I'm looking at (GNU Portable Threads) makes some wild and incorrect assumptions about these functions/macros in its autotools scripts, mostly related to all of the above having to be functions in order to be usable.  I don't think we're wrong; I was just looking for some clarification.

**Comment by jmalak** [comment]
setjmpex.h header file is specific for Windows NT and it should define setjmp/longjmp with exception handling support (internal _setjmpex/_longjmpex functions). It is not required on x86 architecture but it will required on x64 architecture and for some reason it is required on ALPHA architecture for NT OS. The macro SETJMPEX_H_INCLUDED is guard for including both setjmp.h and setjmpex.h.
Yes, we should be POSIX compliant that sigsetjmp/siglongjmp should be implemented that it is OK now, Thanks you.

**Comment by ArmstrongJ** [comment]
Thanks for the explanation again!
