### ISSUE TITLE
Unnecessary DS loaded in an interrupt handler's prolog

### ISSUE THREAD

**Issue by guy-david** [open-watcom/open-watcom-v2#243]
Hello,

I am trying to compile a 16-bit interrupt handler in C and the output format is raw binary. The code generator decides to load DS in the prolog of the interrupt handler, which creates a relocation to `seg CONST`. The interrupt no longer loads DS when compiling with `-ml`, however that creates many other relocations through-out the entire code (does not seem that the large memory model fits to my needs)..

I have tracked [these lines of code](https://github.com/open-watcom/open-watcom-v2/blob/master/bld/cg/intel/c/i86proc.c#L851) which decide whether or not to load DS in the interrupt's prolog. How can I direct wcc to not load the DS register, and still compile with `-ms`?

**Comment by jmalak** [comment]
It is not possible, because interrupt handler in C need to know near default data segment to be able access C run-time library near data.
As soon as you use large data memory model then all data is accessed as far.
It mean any pointer initialization needs segment (relocation).
Anyway you need thing about it little more, bacause if you wan't write interrept handler in C, you need to access C run-time library at minimum for installing interrupt handler under your OS.

**Comment by guy-david** [comment]
What if I choose not to link with the C run-time language? I wish to set DS manually.

**Comment by guy-david** [comment]
library*

**Comment by jmalak** [comment]
In this case you need to create interrupt envelope in assemby language and call C code from assembly envelope where you do proper setup of appropriate registers which you need.

**Comment by guy-david** [comment]
In that case the 'interrupt' function modifier is no longer useful to me. I believe the code generator should be altered in a way that would not create a relocation when the output format is raw binary.

**Comment by jmalak** [comment]
Sorry, but you mix linker problem with code generator.
What has raw binary format with code generator generated code?
I don't know any C compiler for segmented architecture which is able to satisfy your requirements.
How you want initialize ds register, how you get value for it?
It is unclear what purpose is for your interrupt handler code which is always far code out of C run-time context. Is it for embeded programing?
If yes then question is about linking and you should read OW linker documentation about ORDER command to do segments assignment to fix address and therefore no problem with any relocation.

**Comment by guy-david** [comment]
It seems the ORDER directive should fit my requirements, but with the following command the linker still fails because of the aforementioned relocation:

`wlink format raw bin file main.obj order clname code clname data segaddr=0x2000`

**Comment by jmalak** [comment]
What message you get exactly?

**Comment by guy-david** [comment]
The same as before: `invalid relocation for flat memory model at 00000009`
That's the location it is referring to:

```
_TEXT:0000                 pusha
_TEXT:0001                 push    ds
_TEXT:0002                 push    es
_TEXT:0003                 push    ax
_TEXT:0004                 push    ax
_TEXT:0005                 mov     bp, sp
_TEXT:0007                 cld
_TEXT:0008                 mov     ax, seg CONST
_TEXT:000B                 mov     ds, ax
```

**Comment by jmalak** [comment]
You should read OW linker guide carefuly. You atempt to link 32-bit flat code but your code is 16-bit segmented. I think proper linker directives are (for real-mode 16-bit code)
wlink format dos output raw  .....

**Comment by jmalak** [comment]
Next posibility is create DOS executable and next use exe2bin utility to convert relocatable code to absolute binary form

**Comment by guy-david** [comment]
I think I will be take advantage of exe2bin (was not familiar with it before). Thanks for your help!
