### ISSUE TITLE
./c/cvvirt.c:125:7: error: conflicting types for ‘VMBlock’

### ISSUE THREAD

**Issue by XVilka** [open-watcom/open-watcom-v2#247]
Compiling on Gentoo x86_64:
```
../c/cvvirt.c:125:7: error: conflicting types for ‘VMBlock’
 void *VMBlock( imp_image_handle *ii, virt_mem start, size_t len )
       ^
In file included from ../c/cvvirt.c:33:0:
../h/cvinfo.h:108:34: note: previous declaration of ‘VMBlock’ was here
 extern void                     *VMBlock( imp_image_handle *, virt_mem, unsigned );
                                  ^
Error(E42): Last command making (cvvirt.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build         -h> => non-zero return: 512
```

Full build log is here http://xvilka.me/openwatcom-2016.log

**Comment by jmalak** [comment]
Thanks for bug report. Primary build system is 32-bit Windows to be able do full testing for 16-bit target. Therefore it doesn't report any problem with this bug which unfortunately is fatal for 64-bit build.

**Comment by XVilka** [comment]
I can setup CI on the Jenkins instance (Linux x86_64), but I advise you to setup Travis-CI - it's very easy.

**Comment by jmalak** [comment]
This is oriented only to GNU automake projects what OW is not.

**Comment by XVilka** [comment]
Nope, it's not. You can run almost every command on those machines - it is using docker.

**Comment by jmalak** [comment]
I am using OW own perl based build/test server which is capable to run on various platforms.

**Comment by XVilka** [comment]
Fixed, thanks! Found another bug, though: https://github.com/open-watcom/open-watcom-v2/issues/249
