### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by XVilka** [open-watcom/open-watcom-v2#248]
My suggestion is to setup Travis CI and AppVeyor, thins will allow to run the tests automatically after the builds, along with the checking pull requests automatically on these PRs.

**Comment by XVilka** [comment]
Added this as a temporary solution - it's Linux x86_64 + GCC 5.3

**Comment by jmalak** [comment]
Thanks. I am sorry but I am not familiare with these products that for me it is hard to do it.
Please do you know some free service which should be able to run tests on Windows 16/32-bit, DOS 16/32-bit and OS/2 32-bit?

**Comment by XVilka** [comment]
AppVeyor can run for Windows 32bit and Windows 64bit. For running DOS you will need to setup your own VM

**Comment by ArmstrongJ** [comment]
AppVeyor is [pretty expensive](http://www.appveyor.com/pricing).  Would it even be able to perform a build of Open Watcom?  Our build system _requires_ a DOS emulator at the very least.

I have a [server performing a nightly build](http://buildbot.approximatrix.com/waterfall) on Linux using Open Watcom as the compiler, but it doesn't currently run any tests.  A full clean/build takes about two hours right now.  It might be more performant if it performed incremental builds, of course.

**Comment by jmalak** [comment]
I don't think OW build system is ready for incremental build.
Now regular way is first clean build tree and next start build from begining.
It is necessary to do it for both phases first is bootstrap tools build and next is OW own build.

**Comment by XVilka** [comment]
@jmalak: AppVeyor is free for opensource projects.

**Comment by jmalak** [comment]
**@XVilka:**  
I tested AppVeyor for build OW, but it can not be used.
There is limitation for job run 60 minutes.
I estimate OW build take on AppVeyor about 2 hours.

Anyway thanks for your info.

**Comment by jmalak** [comment]
I configured OW build on Travis CI [(https://travis-ci.org/open-watcom/open-watcom-v2)]
I must fixed some issue related to limitation on Travis CI, now only dosemu problem for WGML utility remains. Problem is with limitation of output (console) info to 4MB.
It will be necessary to put build log to some external store (maybe to Github repositoty) to be able analyse results if build fails.

**Comment by XVilka** [comment]
I've installed dosemu on my Jenkins machine too http://ci.rada.re/view/Misc/job/openwatcom/23/console - there are still traces of using unix2dos.

**Comment by jmalak** [comment]
It is fixed by 243b26497072cbfe355e1caef73138cd0623b393 .

**Comment by jmalak** [comment]
Travis CI is now working. If build fails then build log is put into GitHub repository [Travis CI build logs](https://github.com/open-watcom/travis-ci-ow-builds)
