### ISSUE TITLE
Results of the Clang scan-build

### ISSUE THREAD

**Issue by XVilka** [open-watcom/open-watcom-v2#250]
Here you can find a few warnings marked as "Logic error" http://xvilka.me/2016-05-15/

**Comment by XVilka** [comment]
For example issues like: http://xvilka.me/2016-05-15/report-779830.html#EndPath or http://xvilka.me/2016-05-15/report-b3333b.html#EndPath or http://xvilka.me/2016-05-15/report-842810.html#EndPath

**Comment by jmalak** [comment]
I don't see any important problem there.
