### ISSUE TITLE
Error compiling with Win XP

### ISSUE THREAD

**Issue by MikeyG** [open-watcom/open-watcom-v2#258]
I have tried to compile OW 2 with a copy of Windows XP running under VirtualBox and I get the following error: 

Also - I am building without docs

============= 07:19:55 c:\open-watcom-v2\bld\causeway\cwc\dosi86 ==============
cp ..\..\cw32\dosi86\cwstub.exe cwstub.exe
reading file ..\..\cw32\dosi86\cwstub.exe (47328 bytes)writing file cwstub.exe                                47328 byte
s, 1 files written in 0.203 seconds (dump 1)
wcl386 -zq -bt=nt -DWINVER=0x400 -D_WIN32_IE=0x300 -l=nt  -I"c:\open-watcom-v2\bld/watcom/h" ..\..\c\mkcode.c -ox-w8-j-f o=.obj -x -fe=.\mkcode.exe
..\..\c\mkcode.c(40): Error! E1055: Unable to open 'stdio.h'
..\..\c\mkcode.c(41): Error! E1055: Unable to open 'stdlib.h'
..\..\c\mkcode.c(42): Error! E1055: Unable to open 'string.h'
..\..\c\mkcode.c(43): Error! E1055: Unable to open 'sys/types.h'
c:\open-watcom-v2\bld\watcom\h\wio.h(35): Error! E1055: Unable to open 'fcntl.h'
c:\open-watcom-v2\bld\watcom\h\wio.h(36): Error! E1055: Unable to open 'sys/stat.h'
c:\open-watcom-v2\bld\watcom\h\wio.h(38): Error! E1055: Unable to open 'unistd.h'
..\..\c\mkcode.c(53): Error! E1011: Symbol 'FILE' has not been declared
..\..\c\mkcode.c(53): Error! E1011: Symbol 'fp' has not been declared
..\..\c\mkcode.c(53): Error! E1011: Symbol 'NULL' has not been declared
..\..\c\mkcode.c(53): Error! E1014: Left operand must be an 'lvalue'
..\..\c\mkcode.c(54): Error! E1077: Missing '}'
..\..\c\mkcode.c(54): Warning! W107: Missing return value for function 'main'
..\..\c\mkcode.c(61): Error! E1099: Statement must be inside function. Probable cause: missing {
..\..\c\mkcode.c(58): Error! E1044: Variable 'bufstat' has incomplete type
..\..\c\mkcode.c(49): Warning! W202: Symbol 'buff' has been defined, but not referenced
Error: Compiler returned a bad status compiling "..\..\c\mkcode.c"
Error(E42): Last command making (.\mkcode.exe) returned a bad status
Error(E02): Make execution terminated
<pmake -d build         -h> => non-zero return: 2
Build failed

**Comment by jmalak** [comment]
Thanks for bug report.
It is fixed by change 575e6fb1e2e807fa7025f6f1e592c59cefbde96e.

**Comment by MikeyG** [comment]
Thanks Jiri
