### ISSUE TITLE
_Pragma() or __pragma() in C99 spec., but missing in open watcom.

### ISSUE THREAD

**Issue by MarkAGr** [open-watcom/open-watcom-v2#263]
I have the need to put "#pragma message(...)" into a macro.
Normally this is done with either _Pragma(...) or __pragma(...).
This appears not to be the case of open watcom c ...
Is there any intention to include either of the above?

**Comment by jmalak** [comment]
OW compilers don't support pragmas as operator for use in macros.
Probably it could be useful to implement it, but it will take some efort to implement it in compilers.

**Comment by jmalak** [comment]
It is implemented now by git commit 20ee32dbd44f6e017a296aeaa547d9d3b789453f

**Comment by jmalak** [comment]
_Pragma() operator is implemented for both C and C++ compilers
