### ISSUE TITLE
wcl gnu/linux executables makes different DOS executables

### ISSUE THREAD

**Issue by sparky4** [open-watcom/open-watcom-v2#268]
I am compiling https://github.com/sparky4/16/ exmmtest.exe which is a memory manager i ported over to watcom C from borland C a year ago.... and the 32 bit linux wcl makes a stable exmmtest.exe but the 64 bit linux wcl makes an unstable exmmtest.exe which is interesting.... they should be the same...

**Comment by jmalak** [comment]
Thanks for bug report.
wcl is only driver for C compiler, WASM and linker.
Please could you check which tool is wrong.
Remove all q or zq option from your wcl command line and add new options -fd and -fm.
You get all tools full command line on screen and linker directives and map file (__wcl__.lnk and ...map in current directory).
Try to check __wcl__.lnk for both version if there is difference.
Try to check MAP file difference.
next try to link your executable by 32-bit version linker.
next try 32-bit version of C compiler and WASM for object files.

**Comment by sparky4** [comment]
ok i will~!

**Comment by sparky4** [comment]
c4 is the 32 bit one and l4 is the 64 bit one 
https://github.com/sparky4/16/blob/master/wcl__.lc4
https://github.com/sparky4/16/blob/master/wcl__.ll4

https://github.com/sparky4/16/blob/master/exmmtest.mc4
https://github.com/sparky4/16/blob/master/exmmtest.ml4

**Comment by jmalak** [comment]
It looks like linker problem, wrong alignment of near code.
Please could you check to link code created by 64-bit C compiler by 32-bit linker.

**Comment by sparky4** [comment]
ok

**Comment by sparky4** [comment]
compile with 64 bit compiler and use 32 bit linker?

**Comment by jmalak** [comment]
Yes

**Comment by sparky4** [comment]
ok i will test soon!

**Comment by sparky4** [comment]
odd.... the program crashes when it terminates....

https://github.com/sparky4/16/ here is the code

**Comment by jmalak** [comment]
Please, I need source code and build make files to be able do some analysis, not executable.

**Comment by sparky4** [comment]
you can clone the repo and to initiate it just do
wmake initlibs
this clones the libraries it uses
and ./wbuild.sh

this compiles
^^

the source of the executable is in src directory
and the non-executable object with library functions are in src/lib/

**Comment by jmalak** [comment]
I must fix makefile to build all from scratch.
I tested on OpenSuse 
Linux linux-4tzc 3.16.7-35-desktop #1 SMP PREEMPT Sun Feb 7 17:32:21 UTC 2016 (832c776) x86_64 x86_64 x86_64 GNU/Linux
I used latest OW 2 build from Travis-CI
https://github.com/open-watcom/travis-ci-ow-builds

I build exmmtest.exe by 32-bit tools (from binl) and by 64-bit tools (from binl64).
I get exactly same exmmtest.exe see enclosed map files from linking process

[exmmtest32.mah.txt](https://github.com/open-watcom/open-watcom-v2/files/344729/exmmtest32.mah.txt)
[exmmtest64.mah.txt](https://github.com/open-watcom/open-watcom-v2/files/344730/exmmtest64.mah.txt)

**Comment by sparky4** [comment]
oh so any idea whats going on? anything on my side ? like the make file is weird?

**Comment by jmalak** [comment]
What all you recompile by each version of OW tools?
What initialization you do before each build exmmtest.exe?
It could be a problem with compilation of some library that is different for each version due to some bug in 64-bit version of tools.

**Comment by sparky4** [comment]
ok i will test when i can

**Comment by sparky4** [comment]
i tried with travis-cl build and it crashed with 64 bit compiler and linker

**Comment by sparky4** [comment]
I am using the 32 bit version of the compilers on the 64 bit system and exmmtest.exe crashed

**Comment by sparky4** [comment]
the compiled travis version gose boom (exmmtest)[both 64 bit and 32 bit]. so i copy my watcom from the machine that has the working build to my 64 bit system and exmmtest works. do you want my open watcom repo clone from the working one?

**Comment by jmalak** [comment]
It looks like you have wrong setup for INCLUDE and LIB environment variablec.
1. INCLUDE variable should not continue all headers directories, only headers directory for target platform, anyway for cross compilation should be header handled by makefiles
2. LIB variable should be blank, libraries are handled by wlink.lnk configuration file and by linker command line, LIB variable can interfere with wlink.lnk configuration

**Comment by jmalak** [comment]
For correct cross-compilation you should use variables
DOS_INCLUDE=
LINUX_INCLUDE=
OS2_INCLUDE=
NT_INCLUDE=
etc.
or handling by make files

**Comment by sparky4** [comment]
oh ok

**Comment by sparky4** [comment]
hey i think it is fixed! ^^

**Comment by jmalak** [comment]
good news.

**Comment by sparky4** [comment]
yes ^^
