### ISSUE TITLE
sem_init() Fails Due to Incorrect System Detection

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#269]
bld/clib/linux/c/sem_init.c contains an assembly routine to detect if a 486 is present, allowing for our new POSIX semaphore implementation to work on Linux.  The routine `is486` seems to fail, however.  I'm not exactly clear on exactly what the expected result should be.

The problem can be isolated to this simple code as well:

```
#include <stdio.h>

extern unsigned is486( void );
/* Try and flip the ID bit in EFlags */
#pragma aux is486 =             \
        ".586"                  \
        "pushfd"                \
        "pushfd"                \
        "pop    eax"            \
        "xor    eax,0x200000"   \
        "push   eax"            \
        "popfd"                 \
        "pushfd"                \
        "pop    ebx"            \
        "popfd"                 \
        "xor    eax,ebx"        \
        "shr    eax,21"         \
        "and    eax,1"          \
    value [eax] modify [ebx]
    
int main(int argc, char *argv[])
{
    if(is486())
        printf("486 or higher!\n");
    else
        printf("386...\n");
    return 0;
}
```

This program will print "386..." on my AMD Athlon (32-bit Linux) every time.

EDIT: removed one line I added while messing around.

**Comment by ArmstrongJ** [comment]
The following assembly does work in my case:

```
#pragma aux is486ish =             \
        ".586"                  \
        "pushfd"                \
        "pushfd"                \
        "pop    eax"            \
        "mov    ebx,eax"        \
        "xor    eax,0x200000"   \
        "push   eax"            \
        "popfd"                 \
        "pushfd"                \
        "pop    eax"            \
        "popfd"                 \
        "xor    eax,ebx"        \
        "shr    eax,21"         \
        "and    eax,1"          \
    value [eax] modify [ebx]
    
```

The big change is storing the original flags in `ebx` prior to attempting the bit 21 flip. I think it may have simply been missing.  Am I correct?

**Comment by jmalak** [comment]
Yes, it is bug and fix is correct.
Interesting, this code is original Watcom, that stay in source code very long time and nobody find this bug.

**Comment by jmalak** [comment]
Please fix also original code in trap/lcl/c/x86cpu.h.

**Comment by jmalak** [comment]
I looked for Intel recomendation for 486 detection routine with following result.
1. not 32-bit
2. is 386 procesor 
3. if not CPUID then 486
4. if CPUID then check 486 by CPUID

**Comment by jmalak** [comment]
Maybe best  code for this issue is
bld/watcom/h/cpuid.h

**Comment by jmalak** [comment]
I did simple fix by 3b65e74bcb1ace6553836d028115ea1627df6353 commit

**Comment by ArmstrongJ** [comment]
Commit 3b65e74 fixes my issue.  Were you going to change code in `trap/lcl/c/x86cpu.h` as well?

I did have a fix pending, but I rushed it and ended up with a bad commit situation.  Thank you for taking care of it in the meantime.

**Comment by jmalak** [comment]
I checked code and it is OK.
Routine is486 detect 486 without CPUID and CPUID get correct return code 4 for 486, 5 for Pentium and 6 for Pentium Pro.
No change is necessary in `trap/lcl/c/x86cpu.h`

**Comment by ArmstrongJ** [comment]
Great, then I think you've fixed this bug!
