### ISSUE TITLE
Error compiling with Win XP

### ISSUE THREAD

**Issue by MikeyG** [open-watcom/open-watcom-v2#270]
I have tried to compile OW 2, without docs, with a copy of Windows XP running under VirtualBox and I get the following error:

Open Watcom Make Version 2.0 beta Apr 27 2014 22:18:35 (32-bit)
Copyright (c) 2002-2014 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
	rm -f *.obj *.gh *.exe *.err
Open Watcom Make Version 2.0 beta Apr 27 2014 22:18:35 (32-bit)
Copyright (c) 2002-2014 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
	wcc386 -zq -bt=nt -DBOOTSTRAP -I. -I"../h" -I"../../watcom/h" -I"../../lib_misc/h" -fo=wsplice.obj c:\open-watcom-v2\bld\builder\c\wsplice.c
	wlink name .\wsplice.exe op q sys nt file {wsplice.obj}
	%write usage.tmp -kIS_RC -kENGLISH -f "{MSG_USAGE_BASE+%#%+, \"%s\"}," ..\h\usage.sp usage.gh
	.\wsplice.exe @usage.tmp
	wcc386 -zq -bt=nt -DBOOTSTRAP -I. -I"../h" -I"../../watcom/h" -I"../../lib_misc/h" -fo=cretype.obj ..\c\cretype.c
	wlink name .\cretype.exe op q sys nt file {cretype.obj}
	.\cretype.exe > isarray.gh
	wcc386 -zq -bt=nt -DBOOTSTRAP -I. -I"../h" -I"../../watcom/h" -I"../../lib_misc/h" -fo=macros.obj ..\c\macros.c
..\h\msg.h(78): Error! E1169: Invalid __declspec declaration
Error(E42): Last command making (macros.obj) returned a bad status
Error(E02): Make execution terminated

**Comment by jmalak** [comment]
It is fixed now by 27439a1e94ad63bbf2cf516b63dc988acc4e4d7f commit.

**Comment by MikeyG** [comment]
That fixed the issue.
