### ISSUE TITLE
resource compiler (wrc) on x86_64 linux can't find resource strings

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#273]
Compiling from https://github.com/joncampbell123/open-watcom-v2 (just merged your latest changes).

bash-4.3# /usr/src/open-watcom-v2/rel/binl/wrc
Error! E065: Resource strings not found

This was built on x86_64 linux using build.sh. This is the wrc made with "builder rel". Whatever your resource system does with Linux ELF binaries it's not putting the resource strings in the resource compiler on release.

**Comment by jmalak** [comment]
Thanks for bug report. 
It is interresting this bug was there for long time. 
I will add some regression tests for wrc tool to regular tests.
Now it is fixed by 47c5fc8a531139326c221dac9196943e6a40f8aa.

**Comment by joncampbell123** [comment]
That worked. Thanks!
