### ISSUE TITLE
VSAWP. ?

### ISSUE THREAD

**Issue by sparky4** [open-watcom/open-watcom-v2#280]
Is there such thing as a VSWAP. FILE in watcom?

also
boolean		PMStarted, MainPresent, EMSPresent, XMSPresent;
keeps getting junk in them when they are in a type def so i am fored to use them as global variables...

https://github.com/sparky4/16/blob/master/src/lib/16_pm.c

the behavior and stuff is here

**Comment by sparky4** [comment]
static variables in main for type def structs i found a work around

**Comment by jmalak** [comment]
I don't understand what problem is.

**Comment by sparky4** [comment]
ah do not worry about it
