### ISSUE TITLE
Cannot build OW anymore

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#282]
I've tried to build OW several times the last couple of months, but it have failed every time. 

This time it emits errors in cmdlnprs.gc (bld/plusplus/386/binbuild, TRUE and FALSE being undefined). I'm using the last version that still worked for RDOS (2014-04-10), 32-bit version on 64-bit Windows 10.

Any ideas why I no longer can build?

**Comment by jmalak** [comment]
Main change is that bool (_Bool) type is now globaly used in OW code.  TRUE/FALSE was replaced by true/false macros defined in stdbool.h. TRUE/FALSE macros is not used now in any part of OW source code. Therefore cmdlnprs.gc must not contain TRUE/FALSE macros, New version of generator is using only true/false macros. It signals old code is used or old version of generator (optencod utility).
Changes were done in build system which was little bit reworked for better portability.
I recommend to recreate your setup script from latest version of setvars.bat and do full cleanup and next new fresh build of bootstrap tools and OW build.
I am building RDOS stuff on Windows and Linux hosts without problem.
If you can send here full build log then I can analyse it.

**Comment by rdos314** [comment]
I checked out the source again, and now it builds.
