### ISSUE TITLE
Separating new/delete from malloc/free

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#288]
I have a request to try to provide help in solving memory leaks in a rather complex application. The problem in the run-time library is that new is in cpplib basically calls malloc (and delete is calling free). Since I use the generic implementation of cpplib, I cannot add conditional stuff in the cpplib without first creating a new rdos target (something I'd rather avoid). I also want to save who is calling these functions, but this will be messed-up because how the C++ functions calls the C functions. When new is called, it will both be recorded from the right position, and as a call to malloc pointing to new.

Would it be acceptable to introduce two new functions, like cpp_malloc and cpp_free instead that are called from new and delete?

Other suggestions for how to solve this are also welcome.

**Comment by jmalak** [comment]
I am not much experienced in C++, I think you could implement your own ::new and ::delete then compile it to some module and use it instead of standard. For new error handling you can specify handler by set_new_handler.

**Comment by jmalak** [comment]
If you need to unchanged development environmet then you can replace modules with ::new and ::delete in C++ run-time library and all should be transparent.

**Comment by rdos314** [comment]
We used the transparent solution, so this is not an issue anymore.
