### ISSUE TITLE
Feature request: 16-bit flat memory model for wcc (for developing .COM executables)

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#289]
https://github.com/joncampbell123/hackers-watcom-v2/blob/master/user/joncampbell123/Hackers%20Watcom%20ideas/wcc%2016-bit%20flat%20memory%20model.txt

I would like to see wcc support a memory model where it can assume code, data, and stack exists within the same 64KB segment, therefore DS = CS. It would allow better development of .COM executables or raw binary executables without needing CSTARTUP.OBJ.

Proposed compiler switch: -mf

Proposed compiler work in this mode:
* DGROUP segment value == CS
* Cannot know segment value in advance
* inline assembly "seg" references remap to CS. "mov ax,seg label" becomes "mov ax,cs" by the compiler.

Proposed linker additions:
* for COM and RAWBIN formats, accept "option offset" if the programmer wants an offset within the segment other than 0x100 or 0x000.

I would be willing to develop this extension in my branch before offering it to this project.

Edit: I wish to clarify that I'm well aware wcc386 has a -mf switch. wcc386 is the 32-bit compiler. I'm referring to wcc here, the 16-bit compiler.

**Comment by jmalak** [comment]
I think it has no sense, because small memory model do what is needed.
What is wrong with small model?
what is wrong with existing tiny startup code?
I thing that existing functionality of linker enable you locate any segment to any value.
I don't understand what is wrong with existing functionality.

**Comment by jmalak** [comment]
Did you tried to put all data into code segment?

**Comment by jmalak** [comment]
Anyway COM format is defined exactly, there is nothing what should be changed.
We can talk about RAW/BINARY formats but all this is about linker, no compiler.
If anything wrong with linker you should specify what exactly is not working.

**Comment by joncampbell123** [comment]
The small memory model if I recall says that code and data are near pointers within a 64KB segment, correct? But I'm not clear if code and data are the same segment value at runtime, or if code and data each have their own 64KB segment.

Second, even in the small memory model, the compiler issues segment references that require the linker to apply segment relocations. That works for EXE which adjusts the segment reference by the EXE's location in memory, but COM executables do not have relocation tables.

Consider the compiled code generated from my DOSLIB device driver:

https://github.com/joncampbell123/doslib/tree/master/dosdrv/hello

ASM code:

    ; var storage
    _dosdrv_req_ptr:
            dd  0

C code:

    DOSDEVICE_INTERRUPT_PROC dosdrv_interrupt(void) {
        switch (dosdrv_req_ptr->command) {
            case dosdrv_request_command_INIT:
                if (dosdrv_req_ptr->request_length < dosdrv_request_init_t_minimum)
                    goto not_long_enough;

compiles to:

Routine Size: 34 bytes,    Routine Base: _TEXT + 0000

    0022                            dosdrv_interrupt_:
    0022  53                                push            bx
    0023  56                                push            si
    0024  1E                                push            ds
    0025  06                                push            es
    0026  B8 00 00                          mov             ax,seg _dosdrv_req_ptr
    0029  8E D8                             mov             ds,ax
    002B  C5 1E 00 00                       lds             bx,dword ptr _dosdrv_req_ptr

mov ax,seg ... cannot produce a valid segment value unless the EXE format is there to provide a relocation table to patch it. My proposal is that the flat 16-bit model would compile it like this:

    0022                            dosdrv_interrupt_:
    0022  53                                push            bx
    0023  56                                push            si
    0024  1E                                push            ds
    0025  06                                push            es
    0026  0E                                push            cs     ; <- don't know segment in advance, use CS
    0029  1F                                pop             ds     ; <- load into DS
    002B  C5 1E 00 00                       lds             bx,dword ptr _dosdrv_req_ptr

The flat model would instruct the compiler to generate memory references ideal for a .COM executable where the program does not know in advance (until it is run) what segment it will be loaded into memory. Memory references would be carried out relative to CS either by using the CS: segment prefix or by loading CS into DS. The goal is to compile so that the OBJ has no segment relocations, only offset relocations. Then the linker patches the offset relocations to produce a binary with no relocations. The compiled code could run from any 64KB segment base, wherever DOS loads it.

**Comment by joncampbell123** [comment]
I would also add that the proposal take:

        mov     si,seg hello_world
        mov     ds,si
        mov     si,offset hello_world

And compile as:

        mov     si,cs
        mov     ds,si
        mov     si,offset hello_world

Code, data, everything would be compiled to run within the same 64KB segment, except (as proposed) the -zu flag would allow the stack to exist elsewhere.

**Comment by jmalak** [comment]
How you can get far pointers in small model for any regular data or code if pointers are only near?

**Comment by joncampbell123** [comment]
If you typecast a near point to far in the proposed flat model, the compiler would copy the contents of "CS" into the segment field.

    void some_function() {
        unsigned int a;
        unsigned char near *ptr = &a; // near address of a
        unsigned char far *fptr = &a; // far address of a: MK_FP(CS,&a)
    }

In the small model as-is, the compiler would fill in the segment field with a reference to DGROUP which the linker converts to a relative segment value, which is then patched by the EXE relocation table when the program is run.

    void some_function() {
        unsigned int a;
        unsigned char near *ptr = &a; // near address of a
        unsigned char far *fptr = &a; // far address of a: MK_FP(seg DGROUP,&a)
    }

All data and code are relative to CS in the proposed -mf model, so if it needs to determine a segment value and it can do so _at runtime_ it just fills in with the contents of CS.

The only restriction is that the compiler cannot provide for cases where variables are initialized or const data is initialized to the FAR address of a symbol or anything that needs to know the segment value at runtime.

**Comment by jmalak** [comment]
Simply "flat memory model" can not work with far pointers, because there can be only near pointers.
You are talking about "flat" model, but it is absurd it can not work this way. Simply you are talking about flat but in reality you means far memory model. What is your problem that you want optimize use of segment registeres in far memory model. Please don't talk about "flat" memory model because it is non-sense. Generated code can not be flat and far, it is simply far model.

**Comment by jmalak** [comment]
You should study based pointers which is something what could help you.
It is "offset" only pointers and segment value is depend on declaration and can be determined on runtime. It can be unknowned on compile time or  can be some predefined value (code or other segment¨, known on compile time).

**Comment by joncampbell123** [comment]
wcc386's flat memory model also has far pointers as well, even if you don't use them. The -mf model does not prevent the use of far pointers, it's just that all code, data, and pointers are 32-bit "near" pointers by default. The 16-bit -mf flat memory model I'm proposing will also not prevent the use of far pointers, it just compiles the code to refer to all symbols (code and data) relative to the CS segment register. All symbols would be "near" relative to CS. You will still be able to declare far pointers, but like the small memory model, pointers are near by default. Understand?

**Comment by jmalak** [comment]
as eample you can use OW overlay manager, which is completely in one segment (code + data) but work with far memory in unknowned segments and most of pointers are near (it uses based pointers). efective far pointers are calculated on runtime, no relocation.

**Comment by joncampbell123** [comment]
From a .COM executable?

**Comment by jmalak** [comment]
if you are using overlay manager it suppose that code under overlay manager control is far. Therefore it can not be COM. But overlay manager code/data is compact in one segment.

**Comment by jmalak** [comment]
Back to your note about flat model. I was not exact you can not use any far pointer which requires relocation.

**Comment by jmalak** [comment]
If you want to have all relative to CS you can define all data in code segment.

**Comment by joncampbell123** [comment]
I don't exactly know how. I do understand there are wcc flags to put const data in the code segment but I don't know how to put non-const data in with the code segment.

**Comment by joncampbell123** [comment]
OK you're correct in that declaring a variable __based( __segname("_CODE") ) causes the compiler to refer to them with the cs: prefix.

Good. Is there a way to tell the compiler to make ALL variables __based( __segname("_CODE") ) in a C source file by default?

Second question: wcc in this case appears to always use the cs: segment override when referring to those variables. Is there anything in the optimization stage of the compiler to group cs: references into a block and load CS into DS to avoid the segment override for that block?

**Comment by groessler** [comment]
I don't understand the problem at all. What's wrong with "-mt"? I've successfully used it to compile and run COM programs.
CS: override is not neccessary, since COM programs start up with all segment registers pointing to the same value. A CS: override would be redundant and just consume time and space.

**Comment by jmalak** [comment]
Yes you need to specify it for each variable if you want it to be in code segment, because default placement is in data segment (DS register). You can define some macro.
Take into acount that placement of variables data into code segment is problematic, mostly you want to put code into ROM and variables into RAM it is why I am talking about small model and tell linker to put code segment to DGROUP and placement segments to appropriate location as separated blocks.
There is only option -zc which put constant data into code segment and is valid only for far models.
It has no sense for variables.

**Comment by jmalak** [comment]
To second question. OW code generator use data reference by DS and code by CS, ES is volatile for any data use (far/near). For big data models is both DS and ES volatile, near data need fill DS with DGROUP. It can not be changed by any compiler option becaused it is by code generator design (80x86 architecture).
Normaly code and data are floating (not related) therefore cs override is necesary for small data models.
Better solution is used small memory model (it does not use segment overides) and your startup code must ensure that ds is set from cs register.

**Comment by joncampbell123** [comment]
I'll try something in my branch as an experiment. I think I can work this out in a way that involves minimal changes to the compiler.

**Comment by joncampbell123** [comment]
Ok: so the way that .COM executables made with Watcom C avoid segment relocations is that you compile .COM targets with -zdp (DS pegged to DGROUP), then you use the linker to make sure everything is part of the DGROUP segment (code, data, etc.) This is what wcl is observed to do when asked to make a tiny target. If you run wcc and wlink manually, then you just have to make sure wcc is run with switches -ms, -zc, -zu, and -zdp and that you use the -g and -nt switches to make sure the _TEXT is type CODE marked as a member of DGROUP. The linker, when everything is DGROUP, effectively makes all references relative to the DGROUP segment which is then relative to CS.

So it looks like I got what I wanted anyway. DOSLIB now has a "hellof" example device driver made in this way using the -ms model as described.
