### ISSUE TITLE
CppCheck

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [open-watcom/open-watcom-v2#290]
I am using CppCheck static analyzer for my developments. Not sure if @jmalak you are aware of it, but may help a lot in detecting tricky situations.

Find attached an example:
[CppCheck.zip](https://github.com/open-watcom/open-watcom-v2/files/582766/CppCheck.zip)

**Comment by jmalak** [comment]
Thanks for info.
For OW I configured CoverityScan and time to time if I have a little free time I improve OW code from CoverityScan report.
[OW Coverity Scan](https://github.com/open-watcom/open-watcom-v2/issues/261)
If you need access to OW CoverityScan info then ask by Coverity request and I will autorize you for access. You can use your GitHub accout to login to Coverity Scan.

**Comment by javiergutierrezchamorro** [comment]
It is fine. Thanks.

**Comment by jmalak** [comment]
I will upload current build results after coverity build finishing may be after two hours

**Comment by jmalak** [comment]
I uploaded it that after a few hours it will be processed by Coverity and results of analysis will be available
