### ISSUE TITLE
64 bit wcc seg faults

### ISSUE THREAD

**Issue by sparky4** [open-watcom/open-watcom-v2#293]
%write tmp.cmd -fr=nul -fo=dos86c/.obj -i=.. -i../.. -e=2 -zu -zq -mc -d0 -bt=dos -oilrtfm -wx -0 -dTARGET_MSDOS=16 -dMSDOS=1 -dTARGET86=86 -DMMODE=c -q cpup3snc.c
wcc @tmp.cmd
Segmentation fault
Error(E42): Last command making (dos86c/cpup3snc.obj) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (src/lib/doslib/hw/cpu/dos86h/cpu.lib) returned a bad status
Error(E02): Make execution terminated

the thing i was trying to compile is https://github.com/joncampbell123/doslib

using 64 bit openwatcom2
the 32 bit one works.

**Comment by jmalak** [comment]
I cannot reproduce it.

**Comment by sparky4** [comment]
hmmm
[wat.txt](https://github.com/open-watcom/open-watcom-v2/files/601115/wat.txt)

should i clean my watcom compile?

**Comment by jmalak** [comment]
Yes, there is many changes which affect bootstrap tools.
Anyway, doslib has hard-coded 32-bit version of OW tools (binl), that probably if you try to use 64-bit version of OW tools it fails. You need correct linux-ow.sh to use binl64 in the PATH variable.
I fixed 64-bit wbind utility that doslib build by 64-bit tools go smothly.

**Comment by sparky4** [comment]
ok i will tesf soon

**Comment by sparky4** [comment]
awesome i think it is fixed

**Comment by sparky4** [comment]
it is~ joncampbell needs to patch it

**Comment by sparky4** [comment]
odd
