### ISSUE TITLE
Relative paths no longer work in debugger

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#296]
When files are compiled with relative paths like ..\dev\somfile.cpp, the debugger will claim it cannot find the file. It works fine for files located in the current directory and for files with absolute paths. This is a recent problem (I think it worked yesterday, but not sure).

**Comment by jmalak** [comment]
I think it is older problem. I will fix it ASAP.

**Comment by jmalak** [comment]
I suppose it is remote debugging with local source files.

**Comment by rdos314** [comment]
Yes, it is remote debugging with local source, but I think it should be the same for local.

**Comment by rdos314** [comment]
I think I know what was wrong. I copied that symbol file from another computer, and the files were located at different drives.
