### ISSUE TITLE
Build fails on linuxarm in bld/setupgui/linuxarm

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#297]
I'm seeing a build error on ARM:
```
= 20:52:44 /media/minerva/RPi/watcom-slave/native_build_rel/git/bld/setupgui/linuxarm =
cc setup.obj
../c/setup.c: In function ‘GUImain’:
../c/setup.c:339:15: warning: ‘state’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             if( *state == DLG_NEXT ) {
               ^
../c/setup.c:406:25: note: ‘state’ was declared here
     dlg_state           state;
                         ^
cc setupfil.obj
cc setupinf.obj
In file included from /media/minerva/RPi/watcom-slave/native_build_rel/git/bld/gui/h/guistr.h:37:0,
                 from ../c/setupinf.c:50:
/media/minerva/RPi/watcom-slave/native_build_rel/git/bld/gui/h/guimsgs.h:35:22: fatal error: guimsgs.gh: No such file or directory
 #include "guimsgs.gh"
                      ^
compilation terminated.
Error(E42): Last command making (setupinf.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build guitool .not .and         -h> => non-zero return: 512
Build failed
```
I have `OWGUINOBUILD=1` if it matters.  The full build log can be found [here](http://buildbot.approximatrix.com/builders/native_build_rel/builds/20/steps/Native%20Build/logs/stdio).  I don't think I'm missing any other environment variables (they're listed at the top of the build log).

**Comment by jmalak** [comment]
It was missing build of gui project for Linux ARM.
It should be fixed by 0104db7f5f31e45129d0d9fd6b371b5f6f415a91 commit.

**Comment by jmalak** [comment]
Next fix by 92fa33a3aa9f2e39e50201d1b66fc27a951bb57b commit.

**Comment by jmalak** [comment]
OW build is OK now. 
Some local problem with creating ZIP archive.
It is up to you.

**Comment by ArmstrongJ** [comment]
Thanks for the quick fix!  There's a problem with zipping the release, but that's a custom task anyways, not OpenWatcom's problem.

**Comment by ArmstrongJ** [comment]
I'm seeing this same bug again show up on Linux builds on ARM.  Full log at: http://buildbot.approximatrix.com/builders/arm_gcc_build_rel/builds/427/steps/Native%20Build/logs/stdio

**Comment by jmalak** [comment]
i will fix it, i changed resource file processing a little bit and probably broke it for arm architecture

**Comment by jmalak** [comment]
Problem is clear, I add build of new installer for 16-bit Window GUI (it uses OW WIN386 extender), but forgot classify it as GUI only build.
Therefore OW build attempt to build on ARM for Windows GUI, it must fail. I will properly classify this build as GUI and problem should dismiss.

**Comment by jmalak** [comment]
It should be fixed now.
try to rebuild after repository sync.

**Comment by ArmstrongJ** [comment]
Looks like everything worked!  Thanks for the quick help!
