### ISSUE TITLE
Dialog box doesn't disappear after GUICloseDialog() for text-mode UI.

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#299]
The async dialog box for debugging RDOS has a callback which closes the dialog box. ( see AsyncNotify() in wv/c/dlgasync.c). This works with the graphics mode debugger but fails both for the text-mode debugger for Windows and for RDOS. In text-mode, the dialog box stays up. If the button is pressed, it closes as it should, but not when it is notified through AsyncNotify(). 

Anybody has an idea why this is so and how to fix it?

**Comment by jmalak** [comment]
I am not sure if ui project is able to handle asynchronous requests.

**Comment by rdos314** [comment]
Neither am I. It seems that when the dialog is closed from itself it will reference a deleted object. I suspect the only safe way to take it down is to simulate an event from the keyboard, either by sending it to the driver, or adding a function that sets a flag and inserts the event as part of new event processing. However, that won't be portable and has to be done per supported system. OTOH, I don't need this to work in the text mode for Windows (no reason to use that).

**Comment by rdos314** [comment]
Yes, simulating an ESC event works to gracefully take down the dialog. I only fixed it for target RDOS, but it should be simple enough to do for other targets as well.
