### ISSUE TITLE
wbind is broken on Linux x86_64

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#300]
I'm getting a build failure with DOSLIB for the win386 target because wbind fails to properly bind the EXE. It appears to open the REX file, copy the REX file to the EXE file without patching, then seek to a file offset way beyond the output EXE's end and write the name of the EXE. The NE header patching script that follows then errors out because the MS-DOS EXE header and NE headers aren't there.

Did anything change in WBIND that would cause this?

I'm seeing this in commit cafa6bec9c9ff0511a966bd528bb10cc50b51333

**Comment by joncampbell123** [comment]
Second issue: The windows code in DOSLIB is erroring out about invalid RES (resource) files.

**Comment by joncampbell123** [comment]
So far, commit fb785fbd2e206c5dd1444877f0ae8181807bedb7 seems to be building normally, so the fault may have occurred somewhere between fb785fbd2e206c5dd1444877f0ae8181807bedb7...cafa6bec9c9ff0511a966bd528bb10cc50b51333

**Comment by jmalak** [comment]
Don't wast your time. I will look on this problem. I am now working on resource library and resource compiler and do minimal checking. anyway wbind utility is calling resource compiler directly that it should report some error if you use -R option.

**Comment by jmalak** [comment]
It should be fixed by 18fc7369bfb95447cbf4b17d5d23d23545ec78b1 commit.

**Comment by joncampbell123** [comment]
Looks good! Thanks!
