### ISSUE TITLE
Resource files no longer work on RDOS

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#302]
The linker complains with: Error! E2823: Error reading RES file "english.res". Unexpected end of file. The file exists and is 64kb. This is a resource file that contains resource strings.

The same error also occurs with resource-only projects.

I know for sure it worked 2016-12-14, but I think it worked yesterday as well.

**Comment by jmalak** [comment]
Thanks for bug report. I will fix it ASAP.

**Comment by jmalak** [comment]
For which target?
Is size of resource file exactly 64kb?

**Comment by jmalak** [comment]
Please, could you give me copy of your resource file.

**Comment by jmalak** [comment]
it should be fixed by 6a77d50fd47cb233f7033be7dabf73781c92cb40 commit

**Comment by rdos314** [comment]
I'm trying to build it. When I first pulled the commit, it failed to build, so I'm doing a complete build just to check.

**Comment by rdos314** [comment]
In case you still need it, here is a very simple rc-file for RDOS:

`
STRINGTABLE
{
1, "Power failure";

}
`
```
You can test it in the IDE by creating a project for an RDOS DLL, and then add this rc-file only. That builds on previous versions.

**Comment by rdos314** [comment]
No, the new commit doesn't build here. I complains in wl/dos386, wlnkmsg.c(212): E1062: Inconsistent return type for function "res_read".

**Comment by jmalak** [comment]
Sorry, my mistake. I submit it from wrong branch. Now build should not fail.

**Comment by jmalak** [comment]
I checked to do RDOS DLL with this simple resource and all is run as expected.

**Comment by rdos314** [comment]
Yes, it builds again. I also checked so both string and binary resources work, and everything seems to be ok now.
