### ISSUE TITLE
Missed opportunity for "small code" optimization with inp/outp/inpw/outpw/etc (low hanging fruit)

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#304]
inp/outp are intrinsic functions in the compiler, which is great.

When compiled, the intrinsic becomes the in/out instruction at the assembly level.

With DOSLIB hw/8042/test.c, I'm seeing an opportunity to optimize for small code.

In the IRQ1 handler, my code does an I/O out to port 0x20 (PIC) to acknowledge the interrupt.

    outp(0x20,0x20);

This is what Watcom C generates:

    0033  B0 20                             mov             al,0x20
    0035  BA 20 00                          mov             dx,0x0020
    0038  EE                                out             dx,al

The issue here is that the compiler is wasting CPU cycles loading DX for a general OUT encoding, when it could save an instruction + 1 additional byte using the short 8-bit OUT form instead.

    mov al,0x20
    out 0x20,al

Smaller code could be generated automatically in this short form if the port parameter is a constant can fit in a byte (port <= 0xFF). If there are known performance loss issues with the short opcode form on 386 or higher, that's OK, that's why I only suggested doing this for "optimize for size" compilation.

I'm not able to locate yet where in the code generator this intrinsic is defined or generated. Any suggestions where to look?

**Comment by joncampbell123** [comment]
Okay, so I see outp/outpw and friends are defined as Common_Functions in bld/cc/i86/dos386/codei86.gh, then referenced in bld/cc/h/pdefni86.h and bld/cc/c/cfeinfo.c.

I don't see a way for that code to conditionally change opcode depending on whether the port number is less than 0x100. If I can figure out how to change the opcode to short form if small code optimization and port < 0x100, I'll submit a patch to include it.

If that's not appropriate, would it be alright to add an intrinsic or define that generates the short form? Something like outpsi, outpwsi, inpsi, inpwsi?

**Comment by rdos314** [comment]
If size and/or speed is a concern for you IRQ, why don't you code it in assembler instead?

I don't see any direct problem with adding size optimized versions of in and out, but I don't think I would use them myself. You could solve it for yourself by defining inline-assembler macros instead.

**Comment by joncampbell123** [comment]
Here's some for the out instruction. Can't figure out the "in" instruction version yet.

    /* NTS: Watcom C doesn't let us use __asm { ... } with \ in the define.
     *      Curly braces give it scope and make it a valid "function" that you can put a semicolon after */
    #define _outpsi(port,val) { \
        __asm mov       al,val  \
        __asm db        0xE6    \
        __asm db        port    \
    }
    
    /* NTS: Watcom C doesn't let us use __asm { ... } with \ in the define.
     *      Curly braces give it scope and make it a valid "function" that you can put a semicolon after */
    #define _outpwsi(port,val) { \
        __asm mov       ax,val  \
        __asm db        0xE7    \
        __asm db        port    \
    }

    0011  B0 20                             mov             al,0x20
    0013  E6 A0                             out             0xa0,al
    0015  B8 34 12                          mov             ax,0x1234
    0018  E7 A0                             out             0xa0,ax

**Comment by jmalak** [comment]
intrinsic functions are handled by compiler front-end.
apprpriate assembly code are in bld/cc/a/code386.asm and bld/cc/a/codei86.asm.

**Comment by jmalak** [comment]
It can not be simply optimize.
Best is to use in-line assembly by #pragma aux or assembly source code.

**Comment by joncampbell123** [comment]
I see that now.

It looks like when the intrinsic functions were added they wrote themselves into a corner. I don't see any easy way to add intrinsics that are more than just "insert this sequence of bytes". So adding an intrinsic for something like CPUID is doable, but not an intrinsic where the parameter becomes one of the opcode bytes or the opcode changes based on parameters. The way it's designed limits intrinsics to a byte sequence, incoming parameters, result, and saved (NOT modified) registers, and that's all it can do.
