### ISSUE TITLE
E1101 error should not be raised for __STDC_LIB_EXT1__

### ISSUE THREAD

**Issue by ak-ambi** [open-watcom/open-watcom-v2#305]
I would like to write my own libc using Open Watcom compiler. The issue I am facing is that the compiler is forcing __STDC_LIB_EXT1__'s value. I believe this definition should be part of libc and not the compiler's engine.

Please remove __STDC_LIB_EXT1__ definition from defines forbidden to undef.

PS: glibc took another approach: it defines all libc-specific defines in stdc-predef.c, which is by default included at the top of each translation unit by gcc 4.8+.

**Comment by jmalak** [comment]
I am not familiar with standard, but I think so this macro should not be defined by compiler.
I will remove it from compilers predefined macros and add this macro to library default header file.

**Comment by jmalak** [comment]
it should be fixed by ecbe29fef5eb98bc0f10eb5b9039e171b5b9b3b5 and 0a02404cb51a3ef91441a9ba2d2202d067175c72 commits

**Comment by ak-ambi** [comment]
Thanks.

This is even more than I asked for. The only little incompatibility with C standard I see introduced is that this macro is now undefined until first system header is included. Should this be fixed before next release?

Solution used in gcc/glibc was discussed here:
https://www.sourceware.org/ml/libc-alpha/2009-04/msg00005.html

**Comment by jmalak** [comment]
It is fixed now by several changes in OW (OW CRTL header file _comdef.h hold this macro definition now).

**Comment by jmalak** [comment]
Thanks for your info.
We will add compiler new feature to use compiler pre-init header file.
We already use _ialias.h file for similar functionality, but this will require some new implicit file name and new compiler option for change this name.

**Comment by rdos314** [comment]
I think this change broke the build. At least I can no longer build the source today.

**Comment by rdos314** [comment]
The build works again when I reinstall the 2014 OW. Might be a problem to build the source with the current compiler.

**Comment by jmalak** [comment]
It should be compilable by latest version of OW tools. I will check.

**Comment by jmalak** [comment]
I build current  OW and next build OW by this latest version and it builds OK.
I do always full cleanup by clean script and next full rebuild by build script.
What part of OW has a problem?

**Comment by jmalak** [comment]
@ak-ambi 
I am working on full feature fix to load _preincl.h header file (if exists on the search path) and new compiler option -fip which can switch of this feature or specify different name.
existing _ialias.h file will be remove and all definitions will be moved to new _preincl.h file and also `__STDC_LIB_EXT1__` macro definition will be in this new file.

**Comment by ak-ambi** [comment]
Great to hear :) I can test it when it's ready.

**Comment by rdos314** [comment]
It might be that my environment was messed-up. If it builds for you with the latest OW, then all should be fine.

**Comment by jmalak** [comment]
Generaly I don't test OW build by latest OW build therefore some problem can appear.
I am running standard OW tests for compilers and CRTL.
I am using OW 19 compilers or native compilers for bootstraping to ensure portability. Time to time I check OW build by latest OW tools.
Sorry, it is hard for me to test it quickly on all host platforms that some combination (compiler/host) can be broken and can fail.

**Comment by jmalak** [comment]
I submit 02e783f486680713b7aa7bae4a959f04ae3c9224 commit which a little bit generalize existing "_ialias.h" file by inclusion more general file "_preincl.h"
doesn't solve any issue how macros is handled in it if it is read-only etc.
Now in "_preincl.h" file is definition specific for standard OW header files and CRTL, both are specific for OW run-time environment but not for compilers.
If you find any other macros specific for run-time implementation then we can move them into this file.

**Comment by jmalak** [comment]
@ak-ambi I finished compilers change that now -fip option control inclusion of header file "_preincl.h" which contains  OW run-time specific definition.
If you use only -fip option then no file is included or you can use -fip=file.h to include your own file.h header file. If this file doesn't exist then no error is reported.

**Comment by ak-ambi** [comment]
Works great :)

**Comment by ak-ambi** [comment]
Oh, sorry, but are you sure that you want to remove old '-na' flag? Watcom seems to raise an error on unknown flag, so this may break some old build systems with "Invalid option" error.

If that's acceptable, just close the issue.

**Comment by jmalak** [comment]
You are right, that -na option can be used in old code. But we can not support it in new environment, it was for -ialias.h file which contains only header name aliases (very specific). Anyway -na option is not used for standard OW environment, only for very specific situation that can be replaced by -fip... option and _preincl.h file content.

**Comment by jmalak** [comment]
Anyway -na option is undocumented.

**Comment by ak-ambi** [comment]
What if compiler could accept more than one preincluded header? Then it would be possible to preinclude _ialias.h and _preincl.h independently. The other option is to add new macro that would be defined when '-na' flag is present. Such macro could be a guard for alias-specific content in _preincl.h file.

**Comment by jmalak** [comment]
It have no sense to enable more pre-include files. It must be always only one file, because it requires very specific processing and this file can contain only limited "things" with regards to use precompiled headers file. Anyway conditional guards work in _preincl.h file.
-na option was introduced in OW 2.0 fork that we can remove it.
