### ISSUE TITLE
CRC field for NE (win16) header?

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#308]
Just a quick question, since nobody on the internet seems to have this info...

Does anyone know the algorithm used to generate the 32-bit CRC field in NE EXE files? Windows 3.0 and higher obviously ignore it, but Windows 1.x and 2.x appear to require a valid value for device drivers.

This matches what I can find on the internet about the NE format, where a later version calls the CRC field "reserved" and the older version calls it a CRC field but does not describe how to compute it.

DOSLIB recently finished a fully functional mouse driver replacement for Windows 3.0 and Windows 3.1 that could theoretically work with Windows 2.x but the setup utility refuses to install the driver file. The design of Windows 2.x is very different from Windows 3.x. You can't just copy a DRV file into the Windows directory and edit SYSTEM.INI because there is no SYTEM.INI, you have to use the SETUP program in Windows 2.x to essentially "recompile" all system and driver files into a large BIN and OVL pair that Windows loads at startup, and SETUP appears to require a valid checksum before it will accept the driver. Windows 2.x SETUP however does recognize the common Windows 3.x OEMSETUP.INF scheme for third party drivers.

It's nice to note that, as far as DLL entry points are concerned, Microsoft uses the same ordinals and name (the same interface, apparently) across Windows 1.x, 2.x, 3.x. Even Windows 95 uses the same interface, though only a stub that passes calls to the VXD driver.

Windows 1.x and 2.x obviously have the same interface because I can give Windows 1.x PS/2 mouse support by copying MOUSE.DRV from Windows 2.x over the Windows 1.x install files Windows 1.x pre-dates the addition of the PS/2 mouse interface and does not have support for it, the original MOUSE.DRV in Windows 1.x only supports bus and serial.

The mouse driver in DOSLIB takes two forms, one for plain PS/2 mice and another a VirtualBox-style "mouse pointer integration" driver for DOSBox-X that sends the user's cursor position in the emulator window as absolute coordinates so the guest and host mouse cursor lines up. Just like VirtualBox, this allows mouse interaction with Windows inside without the emulator needing to "capture" the mouse cursor.

If this information is not available, that's perfectly fine. It would be awesome to have the DOSLIB driver work with Windows 1.x and 2.x but it's really just a curiosity to do it, not a high priority.

I'm asking because I see that Open Watcom's PE linker support has apparently figured out the Win PE CRC algorithm despite any official documentation on how to compute it.

**Comment by joncampbell123** [comment]
The only other thing I can think of is that the MS-DOS and NE headers appear to be aligned to 512-byte offsets in Windows 1.x and Windows 2.x EXE/DLL/DRV files.

**Comment by jmalak** [comment]
I read somwhere it should be 32-bit CRC calculated over all file with CRC field setup to zero.
I don't know if it helps you anyway.

**Comment by joncampbell123** [comment]
That's the same thing I found. But there's no other information about it that I can find.
