### ISSUE TITLE
Clib no longer builds for debug

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#309]
There appears to be a new issue with the debug build of clib. It worked yesterday, but now the compiler crashes on a memory read.

Information:
clib/heap/library/msdos.086/mm:

cc allocseg.obj
..\..\..\c\allocseg.c(147): Error! E1119: Internal compiler error 141
..\..\..\c\allocseg.c(147): Error! E1119: Internal compiler error 141
The instruction at 0x00491a26 references memory at 0x00000004
...

**Comment by jmalak** [comment]
It looks like bug in code generator.
I will look into this.

**Comment by jmalak** [comment]
I tried to do debug build of CRTL on 64-bit Linux with gcc compiler, but it is going OK.
Please, what compiler you use for bootstrap and on which platform you are building.

**Comment by rdos314** [comment]
I used the 32-bit Watcom compiler that I compiled on Friday.

**Comment by rdos314** [comment]
I don't know exactly why, but it works again.
