### ISSUE TITLE
Download link for binaries needs a small fix to be usable

### ISSUE THREAD

**Issue by badsectoracula** [open-watcom/open-watcom-v2#311]
Hi,

The download link for nightly binaries points to a subdirectory of the repository instead of the repository itself. GitHub doesn't provide download links for subdirectories so people cannot download the binaries. Instead it would be better to provide a link to the repository itself:

https://github.com/open-watcom/travis-ci-ow-builds

This adds a green button at the right of the GitHub header that allows people to download a ZIP file with the build. You may also want to add some instructions in the README.md file here saying something like "to install, place the files in the rel directory to C:\WATCOM" or something like that.

**Comment by jmalak** [comment]
I changed it to start download full repository ZIP as first atempt.

**Comment by badsectoracula** [comment]
Looks fine.

**Comment by jmalak** [comment]
Download was reworked.
