### ISSUE TITLE
Dialog Editor (wde.exe) cannot save files

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#314]
The Open Watcom Dialog Editor does not seem to be able to save files on Windows.  It always produces the message "Save failed!" when saving as a resource script (RC), dialog script (DLG), or resource (RES).  To replicate, just run wde.exe on a modern Windows system and immediately attempt to save the default blank dialog.

_EDIT: This may be a long-standing bug.  It appears in a build from August 2016 and in a build from yesterday._

**Comment by jmalak** [comment]
thanks for bug report,, it can be related to portability changes when POSIX file I/O was replaced by ISO C file I/O. I will review and fix it.

**Comment by jmalak** [comment]
it is fixed now

**Comment by sezero** [comment]
Which commit is the fix?

**Comment by jmalak** [comment]
there is no exact fix because it was related to memory corruption due to portability problems
I little reworked code for dialog editor to be more portable (16/32/64-bit Windows and various compilers)
it fixed this problem

**Comment by ArmstrongJ** [comment]
Finally tried it on my machine, and it's working great! Thanks!
