### ISSUE TITLE
_tempnam() & co should accept const parameters

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#317]
At present we have _tempnam(char*,char*) (same for the wide char variant)
which should really be _tempnam(const char*,const char*)
The present form results in warnings when one passes const char* params
to the function.

**Comment by jmalak** [comment]
I agree, we should change it.
There is no compatibility issue with any C standard, because it is Watcom extension.

**Comment by sezero** [comment]
MSVC provides a _tempnam() and it accepts both its params as const,
and same is true for POSIX tempnam(). Therefore, changing it will make
it actually more compatible.

**Comment by sezero** [comment]
The attach patch should do it (you can 'git am' it)

[0001-constify-_tempnam-and-_wtempnam.txt](https://github.com/open-watcom/open-watcom-v2/files/811146/0001-constify-_tempnam-and-_wtempnam.txt)

**Comment by jmalak** [comment]
please create pull request if possible for tracking

**Comment by sezero** [comment]
Done.

**Comment by jmalak** [comment]
Thanks, submited.
