### ISSUE TITLE
Cannot build on Ubuntu 16.10

### ISSUE THREAD

**Issue by bmanga** [open-watcom/open-watcom-v2#320]
Hi, when trying to compile the project, I hit the following error :

[.....]
**** BUILD rule
==== 12:47:01 /home/bruno/Projects/open-watcom/open-watcom-v2/bld/browser =====
== 12:47:01 /home/bruno/Projects/open-watcom/open-watcom-v2/bld/browser/gen ===
= 12:47:01 /home/bruno/Projects/open-watcom/open-watcom-v2/bld/browser/brg/dos386 =
= 12:47:01 /home/bruno/Projects/open-watcom/open-watcom-v2/bld/browser/brg/nt386 ==
= 12:47:01 /home/bruno/Projects/open-watcom/open-watcom-v2/bld/browser/brg/os2386 =
= 12:47:01 /home/bruno/Projects/open-watcom/open-watcom-v2/bld/browser/nt386 ==
dosemu -dumb -quiet wgml.bat
ERROR: unknown window sizes li=0  co=0, setting to 80x25
ERROR: MFS: couldn't find root path /media/CDROM
D:\Projects\open-watcom\open-watcom-v2\docs\nt>lredir w: linux\fs/home/bruno/Projects/open-watcom/open-watcom-v2/docs
W: = LINUX\FS/HOME/BRUNO/PROJECTS/OPEN-WATCOM/OPEN-WATCOM-V2/DOCS attrib = READ/WRITE
D:\Projects\open-watcom\open-watcom-v2\docs\nt>w:\gml\dos\wgml.exe guitool ( file wgmlopts.tmp
*** stack smashing detected ***: /usr/bin/dosemu terminated
Aborted (core dumped)
mv: cannot stat 'tmp.ptf': No such file or directory
Error(E42): Last command making (compile_gml_to_xxx;wbrw.h) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (wbrw) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (/home/bruno/Projects/open-watcom/open-watcom-v2/docs/nt/wbrw.h) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed

Any ideas? Compiler is gcc 6.2, dosemu is 1.4

**Comment by jmalak** [comment]
The problem is dosemu.
try start dos emu from shell a try if some DPMI application is running.
other possibility is to use dosbox.

**Comment by bmanga** [comment]
I could not get dosemu to work, but I swithed to dosbox and had to change a parameter in its config file, and it seems to be compiling at the moment.
May I add a troubleshooting section to the build wiki page?

Thanks!

**Comment by jmalak** [comment]
it is good news.
you can add anything to wiki what you think may be useful for others.
