### ISSUE TITLE
WD fails with "Invalid DIP File" Error

### ISSUE THREAD

**Issue by udovichenkoAlexnder** [open-watcom/open-watcom-v2#332]
Recently I've discovered that wd no longer works on DOS. 
wd fails with error:

>  Debugging Information Processor 'dwarf20' load failed: Invalid DIP file

I tried different DIP files, but all of them were rejected as Invalid DIP file.
It easily reproduces with DOSBOX emulator.
Some time ago it worked. I even tested remote Debugging
Windows <-> DOSBOX and it worked. (with OpenWatcom 1.9 it worked too)

**Comment by jmalak** [comment]
Thank you for bug report.
I will review latest changes in DIP file interface and fix a problem.

**Comment by jmalak** [comment]
it is fixed
