### ISSUE TITLE
build.bat cannot build builder.exe

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#337]
Running build.bat on Windows 2016 Server logs this error:

link builder.exe
Error! E2028: unsetenv_ is an undefined reference
file runit.obj(e:\ow\ow\bld\builder\c\runit.c): undefined symbol unsetenv_

I downloaded the OW zip file only a couple of hours ago, installed in e:\ow\ow, edited setvars.bat minimally, cd to e:\ow\ow, and ran build.

**Comment by ideafarm** [comment]
I worked around this by adding the code below to builder.c.  (This is a modified version of code found elsewhere in the build tree.)


//#include "variety.h"
//#include <stdlib.h>
//#include <env.h>

_WCRTLINK void unsetenv( const char *name )
{
    /* use setenv instead of more eficient __findenv */
    /* because we need sync between SBCS and Wide environment */
    //return( setenv( name, NULL, 1 ) );
    setenv( name, NULL, 1 ) ;
}

**Comment by jmalak** [comment]
It looks like OW build environment misconfiguration.
What tool chain you are using for bootstrap compilation OW or Microsoft?
If you are using Microsoft then this function is located in clibext.c and appropriate clibext.h header file.
If you have properly configured OW build environment then as first step is build clibext.lib/clibexts.lib which contain OW specific function which are used for bootstrap and is not available in appropriate CRTL.
Check top of boot.log file if contains something like

```
Build host: NT
=========================== 07:19:18 c:\dev\ow2\bld ===========================
**** Building the watcom bootstrap
======================= 07:19:18 c:\dev\ow2\bld\watcom ========================
=================== 07:19:18 c:\dev\ow2\bld\watcom\binbuild ===================
cc clibext.obj
clibext.c
lib clibext.lib
mkdir dllobjs
cc dllobjs\clibext.obj
clibext.c
lib clibexts.lib
======================= 07:19:18 c:\dev\ow2\bld\watcom ========================
======================= 07:19:18 c:\dev\ow2\bld\watcom ========================
**** Building the posixutl bootstrap
======================== 07:19:18 c:\dev\ow2\bld\posix ========================
=================== 07:19:18 c:\dev\ow2\bld\posix\binbuild ====================

```

**Comment by jmalak** [comment]
I checked the build with latest version of OW build "WMAKE Version 2.0 beta May 30 2017 05:23:37 (32-bit)" from [Latest OW Travis build](https://github.com/open-watcom/travis-ci-ow-builds)
and didn't observe any similar problem. Please check your OW build configuration.
Try to run wmake command and check version on banner top.

**Comment by ideafarm** [comment]
Build completed with my workaround.  Am using OW to build.  Here's the beginning of boot.log:

Build host: NT
============================ 17:14:20 e:\ow\ow\bld ============================
**** Building the watcom bootstrap
======================== 17:14:20 e:\ow\ow\bld\watcom =========================
==================== 17:14:20 e:\ow\ow\bld\watcom\binbuild ====================
======================== 17:14:20 e:\ow\ow\bld\watcom =========================
======================== 17:14:20 e:\ow\ow\bld\watcom =========================
**** Building the posixutl bootstrap
========================= 17:14:20 e:\ow\ow\bld\posix =========================
==================== 17:14:20 e:\ow\ow\bld\posix\binbuild =====================

**Comment by jmalak** [comment]
something is wrong on your side. 
unsetenv is standard function in OW CRTL for very long time, that if it is missing (unresolved by linker) you should check linker map file to see which OW CRTL was used, it is probably wrong library or there must be another problem
if OW is used as bootstrap compiler then clibext.lib is not used because all clibext functionality is in OW CRTL

**Comment by ideafarm** [comment]
Nothing is wrong on my side.  I just downloaded your zip file, made minor changes to setvars.bat, ran it, and then ran build.bat .  To test my system, I am now building ow1.9 and will post the results.

**Comment by jmalak** [comment]
If it is true then you will not have any trouble.
Build of OW1.9 is irrelevant for build OW2.0 because is completely different.
