### ISSUE TITLE
build fails on Windows 2016 Server when building using Watcom including docs

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#338]
Is anyone doing daily or weekly builds on Windows using OW to boot the build?  I've got some time and a fast server and am willing to help out cleaning up OW so that it will build cleanly.  I'm also willing to configure this server to do daily testing.  What is the current state of OWv2 development?  Would I be duplicating what someone else is doing?  Jiri, are you the only one actively working on OWv2?

=================== 09:28:28 e:\ow\ow20\bld\sdk\drwat\nt386 ===================
cc listbox.obj
cc log.obj
cc stat.obj
cc lognote.obj
cc drwatcom.obj
cc sym.obj
cc profile.obj
cc fault.obj
cc disasm.obj
cc global.obj
cc param.obj
cc procctl.obj
cc memory.obj
cc drproc.obj
cc handler.obj
cc memview.obj
cc proclist.obj
cc thrdctl.obj
cc pefile.obj
cc autoget.obj
cc lddips.obj
cc memwndcd.obj
cc madrtn.obj
cc madsys1.obj
cc regstr.obj
cc reglist.obj
cc bitman.obj
cc strcnv.obj
cc regcrt.obj
cc madman.obj
cc madld.obj
cc i64.obj
cc reg.obj
cc dipman.obj
cc dipld.obj
cc dipcli.obj
cc digcli.obj
link drwatcom.exe
Warning! W1008: cannot open e:\ow\ow\bld/commonui/nt386/commonui.lib : No such file or directory
Error! E2028: SetMonoFont_ is an undefined reference
Error! E2028: GetMonoFont_ is an undefined reference
Error! E2028: MemAlloc_ is an undefined reference
Error! E2028: AllocRCString_ is an undefined reference
Error! E2028: FreeRCString_ is an undefined reference
Error! E2028: MemFree_ is an undefined reference
Error! E2028: RCsprintf_ is an undefined reference
Error! E2028: RCvfprintf_ is an undefined reference
Error! E2028: SrchMsg_ is an undefined reference
Error! E2028: SetDlgMonoFont_ is an undefined reference
Error! E2028: JDialogBoxParam_ is an undefined reference
Error! E2028: RCMessageBox_ is an undefined reference
Error! E2028: CopyRCString_ is an undefined reference
Error! E2028: JDialogBox_ is an undefined reference
Error! E2028: SetDlgCourierFont_ is an undefined reference
Error! E2028: SetInstance_ is an undefined reference
Error! E2028: InitSrchTable_ is an undefined reference
Error! E2028: MemStart_ is an undefined reference
Error! E2028: JDialogInit_ is an undefined reference
Error! E2028: RegMemWndClass_ is an undefined reference
Error! E2028: SetDefMemConfig_ is an undefined reference
Error! E2028: GetMemWndConfig_ is an undefined reference
Error! E2028: SetMemWndConfig_ is an undefined reference
Error! E2028: JDialogFini_ is an undefined reference
Error! E2028: GetConfigFilePath_ is an undefined reference
Error! E2028: InitMonoFont_ is an undefined reference
Error! E2028: SaveMonoFont_ is an undefined reference
Error! E2028: DoAbout_ is an undefined reference
Error! E2028: WWinHelp_ is an undefined reference
Error! E2028: ProcessMark_ is an undefined reference
Error! E2028: SaveListBox_ is an undefined reference
Error! E2028: ChooseMonoFont_ is an undefined reference
Error! E2028: WHtmlHelp_ is an undefined reference
Error! E2028: DestroyMonoFonts_ is an undefined reference
Error! E2028: MemReAlloc_ is an undefined reference
Error! E2028: DispNTMem_ is an undefined reference
file listbox.obj(e:\ow\ow20\bld\sdk\drwat\c\listbox.c): undefined symbol SetMonoFont_
file listbox.obj(e:\ow\ow20\bld\sdk\drwat\c\listbox.c): undefined symbol GetMonoFont_
file listbox.obj(e:\ow\ow20\bld\sdk\drwat\c\listbox.c): undefined symbol MemAlloc_
file listbox.obj(e:\ow\ow20\bld\sdk\drwat\c\listbox.c): undefined symbol AllocRCString_
file listbox.obj(e:\ow\ow20\bld\sdk\drwat\c\listbox.c): undefined symbol FreeRCString_
file listbox.obj(e:\ow\ow20\bld\sdk\drwat\c\listbox.c): undefined symbol MemFree_
file log.obj(e:\ow\ow20\bld\sdk\drwat\nt\log.c): undefined symbol RCsprintf_
file log.obj(e:\ow\ow20\bld\sdk\drwat\nt\log.c): undefined symbol RCvfprintf_
file log.obj(e:\ow\ow20\bld\sdk\drwat\nt\log.c): undefined symbol SrchMsg_
file log.obj(e:\ow\ow20\bld\sdk\drwat\nt\log.c): undefined symbol AllocRCString_
file log.obj(e:\ow\ow20\bld\sdk\drwat\nt\log.c): undefined symbol FreeRCString_
file log.obj(e:\ow\ow20\bld\sdk\drwat\nt\log.c): undefined symbol MemAlloc_
file log.obj(e:\ow\ow20\bld\sdk\drwat\nt\log.c): undefined symbol MemFree_
file log.obj(e:\ow\ow20\bld\sdk\drwat\nt\log.c): undefined symbol SetDlgMonoFont_
file log.obj(e:\ow\ow20\bld\sdk\drwat\nt\log.c): undefined symbol JDialogBoxParam_
file log.obj(e:\ow\ow20\bld\sdk\drwat\nt\log.c): undefined symbol RCMessageBox_
file log.obj(e:\ow\ow20\bld\sdk\drwat\nt\log.c): undefined symbol CopyRCString_
file log.obj(e:\ow\ow20\bld\sdk\drwat\nt\log.c): undefined symbol JDialogBox_
file stat.obj(e:\ow\ow20\bld\sdk\drwat\nt\stat.c): undefined symbol MemAlloc_
file stat.obj(e:\ow\ow20\bld\sdk\drwat\nt\stat.c): undefined symbol RCsprintf_
file stat.obj(e:\ow\ow20\bld\sdk\drwat\nt\stat.c): undefined symbol SetDlgMonoFont_
file stat.obj(e:\ow\ow20\bld\sdk\drwat\nt\stat.c): undefined symbol CopyRCString_
file stat.obj(e:\ow\ow20\bld\sdk\drwat\nt\stat.c): undefined symbol SetDlgCourierFont_
file stat.obj(e:\ow\ow20\bld\sdk\drwat\nt\stat.c): undefined symbol MemFree_
file stat.obj(e:\ow\ow20\bld\sdk\drwat\nt\stat.c): undefined symbol JDialogBox_
file lognote.obj(e:\ow\ow20\bld\sdk\drwat\c\lognote.c): undefined symbol JDialogBoxParam_
file drwatcom.obj(e:\ow\ow20\bld\sdk\drwat\nt\drwatcom.c): undefined symbol SetInstance_
file drwatcom.obj(e:\ow\ow20\bld\sdk\drwat\nt\drwatcom.c): undefined symbol AllocRCString_
file drwatcom.obj(e:\ow\ow20\bld\sdk\drwat\nt\drwatcom.c): undefined symbol InitSrchTable_
file drwatcom.obj(e:\ow\ow20\bld\sdk\drwat\nt\drwatcom.c): undefined symbol MemStart_
file drwatcom.obj(e:\ow\ow20\bld\sdk\drwat\nt\drwatcom.c): undefined symbol JDialogInit_
file drwatcom.obj(e:\ow\ow20\bld\sdk\drwat\nt\drwatcom.c): undefined symbol RegMemWndClass_
file drwatcom.obj(e:\ow\ow20\bld\sdk\drwat\nt\drwatcom.c): undefined symbol SetDefMemConfig_
file drwatcom.obj(e:\ow\ow20\bld\sdk\drwat\nt\drwatcom.c): undefined symbol GetMemWndConfig_
file drwatcom.obj(e:\ow\ow20\bld\sdk\drwat\nt\drwatcom.c): undefined symbol SetMemWndConfig_
file drwatcom.obj(e:\ow\ow20\bld\sdk\drwat\nt\drwatcom.c): undefined symbol JDialogFini_
file sym.obj(e:\ow\ow20\bld\sdk\drwat\nt\sym.c): undefined symbol RCMessageBox_
file sym.obj(e:\ow\ow20\bld\sdk\drwat\nt\sym.c): undefined symbol MemAlloc_
file sym.obj(e:\ow\ow20\bld\sdk\drwat\nt\sym.c): undefined symbol MemFree_
file profile.obj(e:\ow\ow20\bld\sdk\drwat\nt\profile.c): undefined symbol GetConfigFilePath_
file profile.obj(e:\ow\ow20\bld\sdk\drwat\nt\profile.c): undefined symbol InitMonoFont_
file profile.obj(e:\ow\ow20\bld\sdk\drwat\nt\profile.c): undefined symbol SaveMonoFont_
file fault.obj(e:\ow\ow20\bld\sdk\drwat\nt\fault.c): undefined symbol SrchMsg_
file fault.obj(e:\ow\ow20\bld\sdk\drwat\nt\fault.c): undefined symbol RCsprintf_
file fault.obj(e:\ow\ow20\bld\sdk\drwat\nt\fault.c): undefined symbol SetDlgCourierFont_
file fault.obj(e:\ow\ow20\bld\sdk\drwat\nt\fault.c): undefined symbol CopyRCString_
file fault.obj(e:\ow\ow20\bld\sdk\drwat\nt\fault.c): undefined symbol MemFree_
file fault.obj(e:\ow\ow20\bld\sdk\drwat\nt\fault.c): undefined symbol MemAlloc_
file fault.obj(e:\ow\ow20\bld\sdk\drwat\nt\fault.c): undefined symbol RCMessageBox_
file fault.obj(e:\ow\ow20\bld\sdk\drwat\nt\fault.c): undefined symbol JDialogBoxParam_
file disasm.obj(e:\ow\ow20\bld\sdk\drwat\nt\disasm.c): undefined symbol MemAlloc_
file disasm.obj(e:\ow\ow20\bld\sdk\drwat\nt\disasm.c): undefined symbol MemFree_
file param.obj(e:\ow\ow20\bld\sdk\drwat\nt\param.c): undefined symbol RCsprintf_
file param.obj(e:\ow\ow20\bld\sdk\drwat\nt\param.c): undefined symbol MemAlloc_
file procctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\procctl.c): undefined symbol CopyRCString_
file procctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\procctl.c): undefined symbol AllocRCString_
file procctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\procctl.c): undefined symbol FreeRCString_
file procctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\procctl.c): undefined symbol MemAlloc_
file procctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\procctl.c): undefined symbol RCsprintf_
file procctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\procctl.c): undefined symbol MemFree_
file memory.obj(e:\ow\ow20\bld\sdk\drwat\nt\memory.c): undefined symbol RCsprintf_
file memory.obj(e:\ow\ow20\bld\sdk\drwat\nt\memory.c): undefined symbol MemFree_
file memory.obj(e:\ow\ow20\bld\sdk\drwat\nt\memory.c): undefined symbol MemAlloc_
file memory.obj(e:\ow\ow20\bld\sdk\drwat\nt\memory.c): undefined symbol JDialogBoxParam_
file drproc.obj(e:\ow\ow20\bld\sdk\drwat\nt\drproc.c): undefined symbol RCsprintf_
file drproc.obj(e:\ow\ow20\bld\sdk\drwat\nt\drproc.c): undefined symbol JDialogBox_
file drproc.obj(e:\ow\ow20\bld\sdk\drwat\nt\drproc.c): undefined symbol AllocRCString_
file drproc.obj(e:\ow\ow20\bld\sdk\drwat\nt\drproc.c): undefined symbol DoAbout_
file drproc.obj(e:\ow\ow20\bld\sdk\drwat\nt\drproc.c): undefined symbol FreeRCString_
file drproc.obj(e:\ow\ow20\bld\sdk\drwat\nt\drproc.c): undefined symbol WWinHelp_
file drproc.obj(e:\ow\ow20\bld\sdk\drwat\nt\drproc.c): undefined symbol ProcessMark_
file drproc.obj(e:\ow\ow20\bld\sdk\drwat\nt\drproc.c): undefined symbol SaveListBox_
file drproc.obj(e:\ow\ow20\bld\sdk\drwat\nt\drproc.c): undefined symbol ChooseMonoFont_
file drproc.obj(e:\ow\ow20\bld\sdk\drwat\nt\drproc.c): undefined symbol WHtmlHelp_
file drproc.obj(e:\ow\ow20\bld\sdk\drwat\nt\drproc.c): undefined symbol DestroyMonoFonts_
file handler.obj(e:\ow\ow20\bld\sdk\drwat\nt\handler.c): undefined symbol CopyRCString_
file handler.obj(e:\ow\ow20\bld\sdk\drwat\nt\handler.c): undefined symbol MemAlloc_
file handler.obj(e:\ow\ow20\bld\sdk\drwat\nt\handler.c): undefined symbol MemFree_
file memview.obj(e:\ow\ow20\bld\sdk\drwat\nt\memview.c): undefined symbol AllocRCString_
file memview.obj(e:\ow\ow20\bld\sdk\drwat\nt\memview.c): undefined symbol FreeRCString_
file memview.obj(e:\ow\ow20\bld\sdk\drwat\nt\memview.c): undefined symbol MemAlloc_
file memview.obj(e:\ow\ow20\bld\sdk\drwat\nt\memview.c): undefined symbol MemFree_
file memview.obj(e:\ow\ow20\bld\sdk\drwat\nt\memview.c): undefined symbol MemReAlloc_
file memview.obj(e:\ow\ow20\bld\sdk\drwat\nt\memview.c): undefined symbol RCsprintf_
file memview.obj(e:\ow\ow20\bld\sdk\drwat\nt\memview.c): undefined symbol DispNTMem_
file memview.obj(e:\ow\ow20\bld\sdk\drwat\nt\memview.c): undefined symbol RCMessageBox_
file memview.obj(e:\ow\ow20\bld\sdk\drwat\nt\memview.c): undefined symbol SetMonoFont_
file proclist.obj(e:\ow\ow20\bld\sdk\drwat\nt\proclist.c): undefined symbol MemAlloc_
file proclist.obj(e:\ow\ow20\bld\sdk\drwat\nt\proclist.c): undefined symbol MemFree_
file proclist.obj(e:\ow\ow20\bld\sdk\drwat\nt\proclist.c): undefined symbol RCsprintf_
file proclist.obj(e:\ow\ow20\bld\sdk\drwat\nt\proclist.c): undefined symbol AllocRCString_
file proclist.obj(e:\ow\ow20\bld\sdk\drwat\nt\proclist.c): undefined symbol FreeRCString_
file proclist.obj(e:\ow\ow20\bld\sdk\drwat\nt\proclist.c): undefined symbol RCMessageBox_
file proclist.obj(e:\ow\ow20\bld\sdk\drwat\nt\proclist.c): undefined symbol JDialogBoxParam_
file proclist.obj(e:\ow\ow20\bld\sdk\drwat\nt\proclist.c): undefined symbol CopyRCString_
file proclist.obj(e:\ow\ow20\bld\sdk\drwat\nt\proclist.c): undefined symbol JDialogBox_
file thrdctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\thrdctl.c): undefined symbol AllocRCString_
file thrdctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\thrdctl.c): undefined symbol FreeRCString_
file thrdctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\thrdctl.c): undefined symbol RCsprintf_
file thrdctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\thrdctl.c): undefined symbol RCMessageBox_
file thrdctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\thrdctl.c): undefined symbol JDialogBoxParam_
file thrdctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\thrdctl.c): undefined symbol SrchMsg_
file thrdctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\thrdctl.c): undefined symbol MemAlloc_
file thrdctl.obj(e:\ow\ow20\bld\sdk\drwat\nt\thrdctl.c): undefined symbol MemFree_
file pefile.obj(e:\ow\ow20\bld\sdk\drwat\nt\pefile.c): undefined symbol MemAlloc_
file autoget.obj(e:\ow\ow20\bld\sdk\drwat\nt\autoget.c): undefined symbol MemReAlloc_
file lddips.obj(e:\ow\ow20\bld\sdk\drwat\c\lddips.c): undefined symbol MemAlloc_
file lddips.obj(e:\ow\ow20\bld\sdk\drwat\c\lddips.c): undefined symbol SetDlgMonoFont_
file lddips.obj(e:\ow\ow20\bld\sdk\drwat\c\lddips.c): undefined symbol JDialogBox_
file lddips.obj(e:\ow\ow20\bld\sdk\drwat\c\lddips.c): undefined symbol CopyRCString_
file lddips.obj(e:\ow\ow20\bld\sdk\drwat\c\lddips.c): undefined symbol RCMessageBox_
file lddips.obj(e:\ow\ow20\bld\sdk\drwat\c\lddips.c): undefined symbol MemFree_
file madrtn.obj(e:\ow\ow20\bld\sdk\drwat\nt\madrtn.c): undefined symbol SrchMsg_
file madrtn.obj(e:\ow\ow20\bld\sdk\drwat\nt\madrtn.c): undefined symbol MemAlloc_
file madrtn.obj(e:\ow\ow20\bld\sdk\drwat\nt\madrtn.c): undefined symbol MemFree_
file regstr.obj(e:\ow\ow20\bld\sdk\drwat\nt\regstr.c): undefined symbol GetMonoFont_
file regstr.obj(e:\ow\ow20\bld\sdk\drwat\nt\regstr.c): undefined symbol SetMonoFont_
file regstr.obj(e:\ow\ow20\bld\sdk\drwat\nt\regstr.c): undefined symbol JDialogBoxParam_
file reglist.obj(e:\ow\ow20\bld\sdk\drwat\nt\reglist.c): undefined symbol GetMonoFont_
file reglist.obj(e:\ow\ow20\bld\sdk\drwat\nt\reglist.c): undefined symbol MemAlloc_
file reglist.obj(e:\ow\ow20\bld\sdk\drwat\nt\reglist.c): undefined symbol MemFree_
file regcrt.obj(e:\ow\ow20\bld\sdk\drwat\nt\regcrt.c): undefined symbol MemFree_
file regcrt.obj(e:\ow\ow20\bld\sdk\drwat\nt\regcrt.c): undefined symbol MemAlloc_
file reg.obj(e:\ow\ow20\bld\sdk\drwat\nt\reg.c): undefined symbol MemAlloc_
file reg.obj(e:\ow\ow20\bld\sdk\drwat\nt\reg.c): undefined symbol MemFree_
file reg.obj(e:\ow\ow20\bld\sdk\drwat\nt\reg.c): undefined symbol MemReAlloc_
file digcli.obj(e:\ow\ow20\bld\sdk\drwat\nt\digcli.c): undefined symbol MemAlloc_
file digcli.obj(e:\ow\ow20\bld\sdk\drwat\nt\digcli.c): undefined symbol MemReAlloc_
file digcli.obj(e:\ow\ow20\bld\sdk\drwat\nt\digcli.c): undefined symbol MemFree_
Error(E42): Last command making (drwatcom.exe) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 2
Build failed

**Comment by jmalak** [comment]
It has no sense to post here any similar info, until you have proper setup of OW2.0 build environment.

**Comment by jmalak** [comment]
Here are detail info about build system [OW Build](https://github.com/open-watcom/open-watcom-v2/wiki/Build)

**Comment by jmalak** [comment]
```
Open Watcom Build Report (build on win32-x86)
================================================

	Built through change   : 9f71f2f4a5a5565afbbcc257f11a513a1122b1b on 2016-08-07


Compilers and Tools
===================

CLEAN+BOOTSTRAP STARTED    : 2017-05-30, 21:16 UTC
CLEAN+BOOTSTRAP COMPLETED  : 2017-05-30, 21:20 UTC

CLEAN+BUILD STARTED        : 2017-05-30, 21:20 UTC
CLEAN+BUILD COMPLETED      : 2017-05-30, 23:14 UTC

Build Successful

REGRESSION TESTS STARTED   : 2017-05-30, 23:14 UTC
REGRESSION TESTS COMPLETED : 2017-05-31, 03:52 UTC

	Fortran Compiler : Succeeded.
	C Compiler       : Succeeded.
	C++ Compiler     : Failed!
		\dev\ow-v2\bld\plustest\regress\positive	i86/01
		\dev\ow-v2\bld\plustest\regress\positive	i86/03
		\dev\ow-v2\bld\plustest\regress\positive	i86/05
		\dev\ow-v2\bld\plustest\regress\positive	i86/07
	WASM             : Succeeded.
	C run-time libr. : Failed!
		\dev\ow-v2\bld\clibtest\regress\heap2	heap2


Documentation Build
===================

CLEAN+BUILD STARTED        : 2017-05-31, 03:52 UTC
CLEAN+BUILD COMPLETED      : 2017-05-31, 04:45 UTC

Messages Added
--------------


```

**Comment by jmalak** [comment]
Bellow is link to system with daily build OW2.0
[ARM Linux based (Raspberry Pi)](http://buildbot.approximatrix.com/one_line_per_build)
[X64 Travis site (Ubuntu based)](https://travis-ci.org/open-watcom/open-watcom-v2/builds) build is put to GitHub OW2.0 repository [travis-ci-ow-builds](https://github.com/open-watcom/travis-ci-ow-builds.git)

**Comment by ideafarm** [comment]
So you aren't doing daily builds on a Windows system?  Am I understanding correctly that your daily builds run only on Linux?

**Comment by jmalak** [comment]
I am doing daily build internally on Windows server. 
It is not available publicly, because I have limited internet connection bandwidth. Internet load for such public server is really high.
You can run quick daily build (by build script), it is done by both public servers or you can run OW build server (perl based) which do full build including documentation build and OW installers build. It runs also all regression tests. Details about build server setup are in build/server subdirectory of OW tree.

**Comment by rdos314** [comment]
I build it regularly, but the document build is really complicated because it requires some very old tools that are hard to find. Also, you cannot build the installation package without building documentation, and to build the 64-bit version, you need MSC. 

I'd appreciate a newer installation build (including a 64-bit build), because the last build cannot be used for RDOS (debugger problems). Currently, I'm telling developers for RDOS-related projects that they must use the 32-bit version, and then patch it with a newer build I made myself.

**Comment by ideafarm** [comment]
Jiri, the bottom line is that I downloaded the ZIP file from this Github repository, unzipped it, made the required minor changes to setvars.bat, ran it, and then ran build.bat.  IT DID NOT WORK.

Whether it works for you is irrelevant.  It needs to work for everyone who downloads it.

I am willing to make my Windows Server 2016 system available to your project for daily builds and tests.  I am willing to administer it and to do ad hoc regression testing and even fix bugs on request for Windows users.  But I want you or someone else to figure out why your ZIP file won't build on my server.  I am willing to create an administrative account for you or for whoever is willing to help me with this.
