### ISSUE TITLE
No serious support for quality control and assurance for Windows users

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#339]
It seems clear to me that no one is currently ensuring that OW2.0 is useable and ultimately bug free on Windows, both as a target and as a build platform.  I have decided to take on this issue.  My first goal is to set up a Windows Server 2016 machine that I own and run in a colocation NOC, as an automated daily build.  Once that is set up, I will start using those daily builds as I continue to develop IPDOS (tm), which is an OW application that I've been working on for many years.  One of my goals is to eventually have IPDOS (tm) run on Linux as well as Windows, and to use that capability to promote Linux use and to destroy Microsoft's monopoly on desktops and laptops.

This post is appropriate because the lack of QC for Windows is a serious problem and an existential threat to whether OW2.0 is viable.  IMO, it is not enough to support Linux.  I will see whether I can debug the build by myself, but help would be appreciated and would turn months of work into days.

**Comment by ArmstrongJ** [comment]
I use Open Watcom nightlies on Windows 10 on a daily basis, and I haven't encountered any serious issues other than those associated with a project under heavy development.  There are occasional problems, but Open Watcom 2.0 is *not* a finished product, nor does anyone claim it to be.  I would perhaps use a calmer tone, though, as the contributors here are volunteers and obviously care quite a bit about the quality of Open Watcom.  Everyone's trying their best.

**Comment by bmanga** [comment]
Automatic daily builds would be more than welcome, but they are only part of the QA process that this project needs to address. We should have automatic test suites as well (the one available is a bit underwhelming, and not even run by the CI).

**Comment by ArmstrongJ** [comment]
That's true, @bmanga, I wouldn't argue with needing test suites.  It just requires time, effort, and someone willing to do it.  I'm not sure who's up for it.

**Comment by ideafarm** [comment]
Any tone issues are entirely my fault and I apologize.  I am seriously interested in becoming a contributor.  I am very old (62) and suffer from "chemo brain" and maybe from other personal issues.  But I am a very experienced C++ developer, although I feel like an idiot because Github still mystifies me.

I am totally willing to do work such as run test suites.  But I can't get started without some handholding.  Just enough to get me started with this Github thing that is so obvious to you all but so incomprehensible to me.

I've just now installed GitHub Desktop on the Windows Server 2016 machine.  I've cloned your repository and created a "fix build errors" branch.  I've made one change, by creating an x-ideafarm-setvars.bat file.  I can't for the life of me figure out how to make a pull request, which seems to be what I am supposed to do to have you all review and comment on a change.  The next step is for me to spend some time with the Github tutorials.

I AM TOTALLY WILLING TO DO WORK and could start immediately once I get past the Github hurdles.

**Comment by bmanga** [comment]
@ArmstrongJ I'm writing some test cases for the c++11 features I'm implementing. Once I am done with the current (nullptr) am willing to set up a basic framework to run the conformance tests. It would be nice that once that's done people start contributing some test cases.

**Comment by jmalak** [comment]
You need to install the following SW on your server to be able run OW Build Server (do full OW build, create OW installers and run OW regression tests for Windows):

- Perl for Windows (64-bit)
- Visual Studio C++ Community edition
- Microsoft Help Workshop (RTF Help Compiler)
- Microsoft HTML Help Compiler or Free Pascal HTML Help compiler
- DOSBox

I am able to help you with installation through online WebEx session.
Please specify at what time you are available, take into account I am from Central Europe timezone UTC + 2 hours. I could be available between 16:00-22:00 UTC each working day or over weekend.

**Comment by ideafarm** [comment]
Thank you for your offer.  I just need you to be available via this issue dialog or via email.  The next step is for me to work through the Github tutorials and to try to debug the build myself.  I only want to ask for help if I get really stuck and cannot do it on my own.

I've already installed DOSBox and both help compilers.  I don't want to install anything that isn't absolutely required to run the build (without documentation for now), so haven't installed Visual Studio or Perl.  This is because I want to keep the machine as close to virgin as possible and verify that build works.

What do you use Perl for?  Is it required to build OW?

**Comment by jmalak** [comment]
OK. If you will need help then send me e-mail.
OW has its own build server which is written in perl. It generates all scripts for build OW, documentations, OW installers and run standard regression tests. It creates report with all problems found during build and also create file tree for simple WEB site which can publish standard OW installers, full binary build and history of build reports.

It has no impact to OW build system, it prepare only system scripts to do the similar thing as if you build OW manualy and after all scripts are prepared then run them. Next it puts together OW installers etc. simply create standard OW distribution as should be delivered to user.

**Comment by ideafarm** [comment]
Cool!  Now I am really motivated!  Can't wait to get started on that as soon as I've handled some pressing court business that cannot wait.

**Comment by jmalak** [comment]
Only note OW build server and simple readme are in build/server subdirectory.

**Comment by jmalak** [comment]
It is example of OW build server report, but because regression test failed no other steps (OW installers build and WEB download update) were processed.

```
Open Watcom Build Report (build on win32-x86)
================================================

	Built through change   : 9f71f2f4a5a5565afbbcc257f11a513a1122b1b on 2016-08-07


Compilers and Tools
===================

CLEAN+BOOTSTRAP STARTED    : 2017-05-30, 21:16 UTC
CLEAN+BOOTSTRAP COMPLETED  : 2017-05-30, 21:20 UTC

CLEAN+BUILD STARTED        : 2017-05-30, 21:20 UTC
CLEAN+BUILD COMPLETED      : 2017-05-30, 23:14 UTC

Build Successful

REGRESSION TESTS STARTED   : 2017-05-30, 23:14 UTC
REGRESSION TESTS COMPLETED : 2017-05-31, 03:52 UTC

	Fortran Compiler : Succeeded.
	C Compiler       : Succeeded.
	C++ Compiler     : Failed!
		\dev\ow-v2\bld\plustest\regress\positive	i86/01
		\dev\ow-v2\bld\plustest\regress\positive	i86/03
		\dev\ow-v2\bld\plustest\regress\positive	i86/05
		\dev\ow-v2\bld\plustest\regress\positive	i86/07
	WASM             : Succeeded.
	C run-time libr. : Failed!
		\dev\ow-v2\bld\clibtest\regress\heap2	heap2


Documentation Build
===================

CLEAN+BUILD STARTED        : 2017-05-31, 03:52 UTC
CLEAN+BUILD COMPLETED      : 2017-05-31, 04:45 UTC

Messages Added
--------------


```

**Comment by bmanga** [comment]
What about setting up an AppVeyor bot? It can be integrated with github as part of CI.

**Comment by jmalak** [comment]
First problem is with host OS system, most of similar services is limited to some OS or there are some other limitation.
We need system which support DOS, OS/2, WIN32 and Linux OSes as minimum.
Perl is ported to many OSes therefore it is OK to use it to generate OS scripts for all tasks.

Now on Travis-CI is done only build, but I have trouble that time needed for build existing configuration is near permitted maximum. There is no time to run regression test because it run a few hours and Travis-CI has limit about 50 minutes for jobs.

**Comment by ideafarm** [comment]
I'm willing to provide a server with the following capabilities for use doing daily builds and regression testing.  Although my offer is unconditional, my ability and willingness to provide (shared) use of this server and by contributing bug fixes to OW2.0 will be much greater if one or several of you become interested in IPDOS (tm) and my vision for combining IPDOS (tm) with OW and Linux and Windows.

This machine runs Windows Server 2016 has NUMA with 2 nodes of 12 processors each.  It is capable of hosing virtual dedicated hosts:

![factory1 ideafarm cpu information](https://cloud.githubusercontent.com/assets/3060794/26835765/e0e232bc-4a8d-11e7-8b97-a7a082c41256.png)

**Comment by bmanga** [comment]
Could you please give an overview of what IPODS is/does and how you would envision an integration with OW?

**Comment by ideafarm** [comment]
I want to emphasize that my offer is unconditional.  If no one here becomes interested in IPDOS (tm), I will still be motivated to help as much as I can, and will still provide the server.

"IPDOS" stands for "IdeaFarm PIggyback Distributed Operating System".  It is a Windows Service, so is just an ordinary application program.  But it is intended to provide a C++ programming environment that completely replaces the API provided by the base operating system, such as win32 for Windows.  It implements my concept of a good C++ programming environment.  For the C++ programmer, IPDOS provides a very different set of abstractions, including redefining basic concepts such as "character" and "program".

Perhaps its three main philosophical concepts are that it is totally committed to C++, that it wants to be totally platform independent, and that the API should be an intelligently crafted masterpiece rather than the crap that Microsoft puts out.  (I didn't fully achieve any of this, but those were the technical goals.)  The overall main driving goal/motive was, and is, to destroy Microsoft's monopoly and control over personal computing technology.

OW's design objectives fit perfectly with these goals.  OW, more than any other C++ toolset, is architectuarlly committed to multiplatform support, both for target hosts and development hosts.  Even though IPDOS could be built using other tools, I want to ensure that OW survives and thrives by throwing the full weight of IPDOS (tm) behind it, so envision a close partnership between OW and IPDOS development.

IPDOS (tm) is my property, but I intend to release it as "copyrighted open source", where the copyright is controlled by a nonprofit that I am in the process of forming, called Ideafarm Operations, Incorporated.  That corporation is not a technical orgization; its mission is to promote unselfish living.

My ultimate goal or vision is to use IPDOS (tm), OW, and Linux to make it possible for C++ developers to write leading applications that run on both Linux and Windows, that are open source so can be verified to not contain spyware or other malware, and that empower individual human beings and disempower corporations such as Microsoft and Google.

So I have an economic vision, a moral vision, and a technical vision.  Regarding technology, I am a "C++ zealot" who wants to work to establish C++ as the preeminent language, OW as the preeminent compiler for C++, and IPDOS (tm) as the preeminent API for C++ coding.

**Comment by bmanga** [comment]
It seems to me that you are describing some sort of virtual machine. If that's the case, I assume you want to create a new backend for OW?

**Comment by ideafarm** [comment]
IPDOS (tm) is just a Windows application that runs in the background (as a "service").  On the task list, you will see a set of about 5 instances of a particular process image.  The same process image is launched for every process.  Each instance is customized in that it dynamically loads and executes a DLL.  These DLL's are application programs.  To write an IPDOS (tm) application, you build one of these DLL's.

Today, when you install IPDOS (tm), what you get is the "IdeaFarm (tm) Bundle", which is just a small set of these DLL's that run whenever your base os (Windows) is running.  The current "bundle" provides for the administration of Rackspace Cloud Files and for what I call "knowledge tree publishing".  I need these things for my sometimes desperate legal work, and I am still debugging them.

Regarding OW, I don't want to create a backend (whatever you mean by that) or to do any development.  I am only interested in providing QA/QC services, including a daily build and test server, and in contributing bug fixes to completely clean up the debugger, which is currently only barely usable and extremely irritating and frustrating.  I have a huge vision for how OW could be used, but I do not have any vision for enhancing OW.  Jiri's work to add 64 bit support and support for Linux excites me, but I do not expect to ever get involved in that.

Am still scrambling to get court documents filed, with one deadline tonight at midnight and another deadline in a few days.  When I can, I will put some time into working through the Github tutorials, and then I'll take a crack at figuring out why the build fails on my server.
