### ISSUE TITLE
Nonsensical code in fold.c

### ISSUE THREAD

**Issue by bmanga** [open-watcom/open-watcom-v2#340]
I am not sure who to ask, but I have encountered some code that I think is clearly misguided:
https://github.com/open-watcom/open-watcom-v2/blob/a745276efa9d5c7cdb1013a11b48c2c9083bae51/bld/plusplus/c/fold.c#L1172-L1185

``notFoldable`` checks that the expression is not a zero constant, and yet inside the ``if`` the code tries to check if either is zero and to ``makeTrueFalse`` if that's the case.

I think either that part of the code is in the wrong if statement, the if condition is wrong, or the implementation of ``notFoldable`` is wrong. I am not sure which it is.

Any ideas?

**Comment by bmanga** [comment]
based on the rest of the code in fold.c I would assume that it should have been : 
``if( !notFoldable ) .... ``. 
I will create a pull request, but feel free to show me wrong.

**Comment by jmalak** [comment]
I don't see a problem there. 
Generaly nonFoldable should be true if argument is not constant expression, I thing it is OK in existing code. If both operand are non-foldable then it returns without any action.
If one operand is foldable then it is possible to do some optimization. Function should be symetric, the same for each argument if it is foldable.


Anyway line 1171 is wrong, it should be:
has_decoration = has_decoration_left | has_decoration_right;
Nothing danger, it is used only for debugging.

**Comment by bmanga** [comment]
@jmalak that's exactly my point. If execution reaches inside the if statement, then neither ``op1`` nor ``op2`` can be constant expressions.
For example, [this line](https://github.com/open-watcom/open-watcom-v2/blob/a745276efa9d5c7cdb1013a11b48c2c9083bae51/bld/plusplus/c/fold.c#L1180) can never evaluate to true.

I am trying to clean up the file, I will create a pull request sometime soon and we can analyze the code from there.

**Comment by jmalak** [comment]
Sorry I didn't study code in details. Yes, this code looks like dead code.

**Comment by bmanga** [comment]
@jmalak does OW provide any backend code optimization passes?
That is, is it necessary to apply the folding logic on the AST in fold.c or could that be done at a later time?
As it is fold.c seems to only perform some optimization if the lhs is constant:
``1 && X -> X``
but not
``X && 1 -> X``.
I am wondering if those are dealt with at a later phase or it would be useful to add me as part of the refactoring.

**Comment by jmalak** [comment]
I think OW compilers front ends are single pass. It does only simple transparent optimisation.
Most of optimisations are done in Code Generator (it can be multi-pass).

**Comment by bmanga** [comment]
Could you point me to the right file/function which would perform constant folding?

**Comment by jmalak** [comment]
I think main file for folding functions is fold.c.

**Comment by bmanga** [comment]
Thanks, I had found it. It appears to be treefold.c (under the cg project).
