### ISSUE TITLE
feature request: #pragma for -zu option on a per function basis

### ISSUE THREAD

**Issue by pgrAm** [open-watcom/open-watcom-v2#352]
Hi,

I often use the -zu option for specifying the SS register should not be assumed equal to DS, this is very useful for functions called during interrupts where the stack could be somewhere unexpected. I think it would be useful however to be able to optionally specify this on a per function basis as opposed to per compilation unit. Perhaps this could be done with a #pragma? (eg. #pragma aux foo zu, where foo is a function)

great compiler! keep up the good work!

**Comment by jmalak** [comment]
Hi,
I think it could be done, because OW code generator use flag(floating SS register) for local(automatic) variables per function bases. Normally it is used if -zu option or __interrupt modifier are used.
it could be done as new function modifier by example __farss.
Take into account that if it stay as definition in source code you cannot simple change compilation model and optimisation by compiler options for these functions.

**Comment by pgrAm** [comment]
Yes, a function modifier such as __farss would be perfect. I guess I could always selectively enable it using the pre-processor.

**Comment by bmanga** [comment]
I think it would be best to use a more general mechanism than adding ad-hoc
modifiers. Something like c++11's attributes would probably fit the bill.
Something like:
[[wat::farss]] void foo (int a)...

**Comment by sezero** [comment]
A pragma, or __farss as a keyword (and/or as a __declspec modifier?) should be nice for this.

As for a [[wat::farss]], I'd object to...

**Comment by bmanga** [comment]
I don't think a pragma better than an attribute in this case.
Declspec is the name for attribute in the windows world, and the syntax for attributes was standardized in c++11. If ow supports __declspec, then it should support both imo (like what gcc does)

**Comment by jmalak** [comment]
It is function modifier.
Take into account differences between C and C++ language.
Probably better will be to use __declspec construct instead of keyword for function modifier.
__declspec construct is supported by both OW C and C++ compilers.

**Comment by pgrAm** [comment]
Is it possible to support both __declspec and the c++11 attributes? That way it would be available when using C and let C++ users write more portable code. Perhaps implement farss as __declspec then implement the C++11 attributes as aliases for __declspec?

**Comment by jmalak** [comment]
Do you know what plan for standardization of C++ attributes in C ?
Do you know any C compiler which implement this not yet standardized feature?

**Comment by bmanga** [comment]
I think he meant enable c++11 attributes to alias __declspec attributes in
the c++ compiler only, which is what I was also suggesting. Mind you, they
are not implemented yet, but for when we do I think it's a good idea.

**Comment by pchapin** [comment]
For what it's worth, I agree with @bmanga. Let C++ people make use of C++ features where appropriate, but don't impose C++-isms on C programmers. However, if we do this, there are probably a whole raft of other things that could be expressed as C++ attributes as well.

**Comment by jmalak** [comment]
I agree the best solution (for now) will be implement it as declspec (it is common for C and C++ compiler). C++11 attributes will be implemented as new feature to be working parallely with declspec.

**Comment by jmalak** [comment]
it is now implemented for both compilers C and C++ by commit c0fcfcdd6836cae9fc28b0cde42d9976aab0e9d9

**Comment by pgrAm** [comment]
Can confirm, this is excellent, works great! I have already found this very useful.
