### ISSUE TITLE
Compiling 16bit C project with "-d{0,1,1+,2,2~,3,9}" option.

### ISSUE THREAD

**Issue by beketata** [open-watcom/open-watcom-v2#358]
I have a 16bit rawbin embedded project. Optimization is switched off with "-od" option.
When I compile it with any "-dx" option, except of "-d0" the simple functions, as:

```
int _i;
void SetI()
{
	_i = 1;
}
```

produces binary code with unnecessary prolog and epilog:

```
_SetI:
	push		si
	push		di
	push		bp
	mov		bp,sp
	sub		sp,2

	mov		word ptr __i,1

	leave
	pop		di
	pop		si
	ret
```

and "-d0" option only produces binary without it:

```
_SetI:
	mov		word ptr __i,1
	ret
```

How to avoid generating unnecessary prolog and epilog (I am talking not about "optimization" or "naked"!) with any "-dx" options ? And what is the reason for this behavior?

**Comment by jmalak** [comment]
Generaly only -d0, -d1 or -d1+ could be used.
I am not sure if stack frame is necessary for debugger.
I will check why it happen and what is reason for this.
Anyway -d0 or no -dx option should be used for production code.

**Comment by beketata** [comment]
1. What does it mean: "only -d0, -d1 or -d1+ could be used" ?
    I tried to use -d0, -d1, -d2 and -d3. In each case it was different sym file generated.

2. I think the Debugger **Information** options should not affect the binary file generated at all. There are used for kinds of information added to sym file only. Am I Wrong?

**Comment by jmalak** [comment]
only following option should not have impact optimization.
-d0 no any debug info
-d1 line numbers only
-d1+ line numbers only + some type info
as soon as you use -d2.. or -d3.. options then optimization is switch off

I must look on code generator code why -d1.. option change somehow generated code

**Comment by beketata** [comment]
I switched optimization off by "-od" option for debug purposes.

**Comment by beketata** [comment]
I figured out why the code generated with -d0 and others -d... options have a different stack frames.
There is a bug in the **Set_D0** function of **\bld\cc\c\coptions.c** in the next line:
```
    GenSwitches &= ~(NUMBERS | DBG_TYPES | DBG_LOCALS | NO_OPTIMIZATION);
```
Option -d0 forcibly switches optimization on by clearing **NO_OPTIMIZATION** flag.

There is another issue related to this - compiler options order affects its behavior.
**-d3 -ot** is not the same as **-ot -d3** because in the first case optimization will be swithed off by **-d3** but then swithed on by **-ot**.

**Comment by beketata** [comment]
Unnecessary stack frame is generated due to the next piece of code in the **GenProlog** function of **\bld\cg\intel\c\x86proc.c**:
```
    if( CurrProc->state.attr & ROUTINE_WANTS_DEBUGGING ) {
        CurrProc->state.attr |= ROUTINE_NEEDS_PROLOG;
    }
```

**Comment by jmalak** [comment]
Thanks for your analysis.
It is original Watcom behavior, no change in OW.
Probably OW debugger need stack frame to work properly.
