### ISSUE TITLE
"build.bat boot" cannot build under Windows environment

### ISSUE THREAD

**Issue by beketata** [open-watcom/open-watcom-v2#361]
Contents of the "bootx.log" after first try is:

wcc386 -zq -bt=nt -DBOOTSTRAP -I. -I"../h" -I"../../watcom/h" -I"../../lib_misc/h" -fo=wsplice.obj c:\WATCOM\bld\builder\c\wsplice.c
..\..\watcom\h\bool.h(36): Error! E1055: Unable to open 'stdbool.h'
...................

After copying the missing 'stdbool.h' to the header directory, the second try is:

wcc386 -zq -bt=nt -DBOOTSTRAP -I. -I"../h" -I"../../watcom/h" -I"../../lib_misc/h" -fo=wsplice.obj c:\WATCOM\bld\builder\c\wsplice.c
c:\WATCOM\bld\builder\c\wsplice.c(295): Warning! W131: No prototype found for function '_splitpath2'
c:\WATCOM\bld\builder\c\wsplice.c(459): Warning! W131: No prototype found for function 'stricmp'
c:\WATCOM\bld\builder\c\wsplice.c(976): Warning! W131: No prototype found for function 'stat'
c:\WATCOM\bld\builder\c\wsplice.c(977): Error! E1031: Name 'actime' not found in struct/union utimbuf
c:\WATCOM\bld\builder\c\wsplice.c(977): Error! E1031: Name 'st_atime' not found in struct/union stat
c:\WATCOM\bld\builder\c\wsplice.c(978): Error! E1031: Name 'modtime' not found in struct/union utimbuf
c:\WATCOM\bld\builder\c\wsplice.c(978): Error! E1031: Name 'st_mtime' not found in struct/union stat
c:\WATCOM\bld\builder\c\wsplice.c(979): Warning! W131: No prototype found for function 'utime'
c:\WATCOM\bld\builder\c\wsplice.c(810): Error! E1044: Variable 'dest_time' has incomplete type
c:\WATCOM\bld\builder\c\wsplice.c(811): Error! E1044: Variable 'src_time' has incomplete type
Error(E42): Last command making (wsplice.obj) returned a bad status
Error(E02): Make execution terminated

**Comment by jmalak** [comment]
check setup of INCLUDE environment variable.
It should be something like
INCLUDE=C:\dev\ow19\H;C:\dev\ow19\H\NT
check if you have properly setup OW compiler environment before run build boot.

**Comment by beketata** [comment]
Sorry for that!
My last "exercises" with watcom buildind were a few years ago...
