### ISSUE TITLE
Compiling C code with Inline Assembler using "-hd" (DWARF) option.

### ISSUE THREAD

**Issue by beketata** [open-watcom/open-watcom-v2#365]
When I compile C code with Inline Assembler by DEBUG version of compiler, it's cause to **Assertion failed!** message in the **FiniHandles** function of **/bld/dwarf/dw/c/dwhandle.c**
```
    _Assert(  cli->handles.forward == 0 );
```
Any Inline Assembler insertion with **__asm** keyword produces dummy function by **AsmSysMakeInlineAsmFunc** of **/bld/cc/c/cpragx86.c** and then DWARF "marks" it as forward referenced by **dwarfDumpNode** function of **/bld/cc/c/dwarf.c** creating new forward reference handle
```
    dh = DWHandle( Client, DW_ST_NONE );
```
and increments forward counter by **NewHandle** function of **/bld/dwarf/dw/c/dwhandle.c**
```
    ++cli->handles.forward;
```
Unfortunately, since there are no real references to this function, forward counter not decremented back and cause **Assertion failed!** message.

**Comment by jmalak** [comment]
Thanks for your bug report and your analysis.

**Comment by jmalak** [comment]
I can not reproduce.
Please, could you give me sample code and compiler options.

**Comment by beketata** [comment]
I am talking about debug version of C Compiler itself, not about debug version of the project.

**Comment by jmalak** [comment]
I understand, but I can not reproduce.
In my sample code and with my compiler options is always called label creation which decrements cli->handles.forward variable after DW handle creation.
May be it depends on a few factors.
I used bld\ctest\positive\source\asm06.c for checking
```
#include "fail.h"
// bug in parsing numeric constant tokens
int main() {
#ifdef __X86__
    unsigned int    x;

    _asm    mov x, 01e0fh;     // float number 1e0f + h 
    if( x != 0x1e0f ) _fail;
    _asm    mov x, 0e1fh;      // float number 0e1f + h
    if( x != 0x0e1f ) _fail;
    _asm    mov x, 0e1ah;      // float number 0e1 + ah
    if( x != 0x0e1a ) _fail;
    _asm    mov x, 001ah;      // octal number 001 + ah
    if( x != 0x001a ) _fail;
    _asm    mov x, 00e1ah;     // float number 0e1 + ah
    if( x != 0x0e1a ) _fail;
    _asm    mov x, 0070ah;     // octal number 070 + ah
    if( x != 0x070a ) _fail;
    _asm    mov x, 123ah;      // decimal number 123 + ah
    if( x != 0x123a ) _fail;
    _asm    mov x, 1a23h;      // decimal number 1 + a23h
    if( x != 0x1a23 ) _fail;
    _asm    mov x, 00701ah;    // octal number 0701 + ah
    if( x != 0x701a ) _fail;
#endif
    _PASS;
}

```

**Comment by jmalak** [comment]
How you create debug version of C compiler?
I am creating debug version by "builder build debug .or" command run in bld/cc directory
Debug versions for NT are by example in bld\cc\386\nt386.dbg.

**Comment by jmalak** [comment]
No response, closing.
