### ISSUE TITLE
How to add new c file to build system?

### ISSUE THREAD

**Issue by bmanga** [open-watcom/open-watcom-v2#366]
I need to add a new file to the build system for the c++ compiler, but I can't find the place where these files are added. I tried to grep for some other filenames (which I know get compiled) but nothing interesting came up.
When I try to build, I get undefined references to the functions in the new file.

@jmalak , do you have any ideas?

**Comment by jmalak** [comment]
What is included in the project is derived from list of objects defined for this project. 
Mostly make file variable objs contains it.
If you add new source then add new "object" file to this key variable and all will be as you expected.

**Comment by jmalak** [comment]
For C++ compiler it is in ppobjs.mif make file.
Where to put depends on what kind of object it is and if it is for some host or target.
Common objects are in variable common_objs.
