### ISSUE TITLE
Constant string literals.

### ISSUE THREAD

**Issue by beketata** [open-watcom/open-watcom-v2#371]
This question is regarding to the [previous one](https://github.com/open-watcom/open-watcom-v2/issues/233)

I have a function
```
    Log( const char far msg[] )
```
and want to use it as
```
    Log( "test message" );
```
so as to place "test message" string into the CODE seg (in ROM).

This way is works
```
    const char far msg[] = "test message";
    ....
    Log( msg );
```
but this is not
```
    Log( "test message" );
```

**Comment by bmanga** [comment]
This might be related to a change I made, which also results in implicit
conversions from function to boolean  (by decaying to fn ptr first) also
failing. Give me some days to investigate it.

**Comment by jmalak** [comment]
I thing C standard doesn't assume literal string as "const" that you must specify it explicitly.

**Comment by bmanga** [comment]
Is the code being compiled with the c or c++ compiler?

**Comment by beketata** [comment]
C compiler.
