### ISSUE TITLE
Microsoft __declspec(noreturn) is stupid no returning flag for code flow only

### ISSUE THREAD

**Issue by jmalak** [open-watcom/open-watcom-v2#373]
OW __declspec(noreturn) implementation must be reworked to follow Microsoft implementation.
MS use it only as flag to break code flow only.
As example you can see Windows API entries ExitProcess and ExitThread which use __declspec(noreturn) modifier but ExitProcess and ExitThread are function (with regular stack frame, only not returning). These function calls therefore can not be optimized. Modifier __declspec(noreturn) is only flag for compiler control flow, not for any optimization as OW #pragma aux .... aborts done.

**Comment by jmalak** [comment]
I added new __declspec(aborts) modifier which is same as OW #pragma aux ... aborts, do optimization for calee and caller. It is used in C/C++ run-time libraries. Next step is change __declspec(noreturn) to remove OW optimization and use is code flow break only.

**Comment by sparky4** [comment]
/dos/fdos/watcom2/h/stdlib.h(188): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/stdlib.h(224): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/stdlib.h(225): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/stdlib.h(241): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/process.h(138): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/process.h(139): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/process.h(149): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/unistd.h(41): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/stdlib.h(188): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/stdlib.h(224): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/stdlib.h(225): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/stdlib.h(241): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/process.h(138): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/process.h(139): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/process.h(149): Error! E1169: Invalid __declspec declaration
/dos/fdos/watcom2/h/unistd.h(41): Error! E1169: Invalid __declspec declaration

I was wondering what was going on!

**Comment by jmalak** [comment]
It looks like you use different version of header files and C/C++ compiler.
Now compilers support both __declspec(noreturn) and __declspec(aborts) and still have same functionality.
Standard header files now use __declspec(aborts) instead of previous __declspec(noreturn). 
Try to get/recompile latest version of OW.
If this is not your case then I need code sample which exhibit this problem with compiler options.

**Comment by sparky4** [comment]
I found something! It compiles normally on my 64 bit laptop. but none of my 32 bit computers. (which is most of them. some have a 64 bit cpu but run with 32 bit kernel due to being installed on 32 bit system and upgrading to a 64 bit one.)

it was only recent that i started working with my 32 bit machines that i noticed this! ><

**Comment by jmalak** [comment]
Thanks for your info.
I will check it on 32-bit system.

**Comment by sparky4** [comment]
still not working btw

**Comment by jmalak** [comment]
something is wrong on your installation
it is inconsistency between header files and compiler version
check compiler version and compilation date/time

**Comment by sparky4** [comment]
wcl version and compiled time? ok will do

**Comment by sparky4** [comment]
oh fixed! my bad it is fixed! <3

**Comment by sparky4** [comment]
Open Watcom C/C++ x86 16-bit Compile and Link Utility
Version 2.0 beta Aug 26 2016 00:04:26 (32-bit)

**Comment by sparky4** [comment]
http://4ch.mooo.com/4/watcom/wat.sh here is my script file for setting up watcom variables
also i cloned it and compile it from source too! my computers have a 1.9 open watcom also. this is for compatibility reasons since 2.0 is not close to stable release. I can change between the two by changing the watcomver= line

watcomver="2" for open watcom 2.0
watcomver="" for open watcom 1.9

**Comment by sparky4** [comment]
ah i fixed it!! i copied over my working one! and bamn!

**Comment by sparky4** [comment]
deleter broken watcom install and recompile it~ <3

**Comment by sparky4** [comment]
every time i compile it on my main 32 bit machine and copy the rel over the working open watcom. it shows the errors above when i compile with debian... 

http://4ch.mooo.com/4/watcom/compwat2.sh

here is my compilation script!

because running the compile scripts alone in the repo will not allow it to compile at all

**Comment by sparky4** [comment]
`**** Building the owcc bootstrap
================ 10:23:52 /home/sparky4/p/watcom2/bld/wcl/owcc ================
=========== 10:23:52 /home/sparky4/p/watcom2/bld/wcl/owcc/binbuild ============
wsplice owcchelp.gh
sh: 1: wsplice: not found
Error(E14): Cannot execute (wsplice): No such file or directory
Error(E42): Last command making (owcchelp.gh) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 512
Build failed
**** REL rule
Build host: UNIX
==================== 10:23:52 /home/sparky4/p/watcom2/bld =====================
**** REL rule
================== 10:23:52 /home/sparky4/p/watcom2/bld/hdr ===================
================ 10:23:52 /home/sparky4/p/watcom2/bld/hdr/dos =================
wsplice _algmut.h
sh: 1: wsplice: not found
Error(E14): Cannot execute (wsplice): No such file or directory
Error(E42): Last command making (_algmut.h) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed
`

dang it!

**Comment by sparky4** [comment]
>**** Building the wlib bootstrap
================= 10:30:58 /home/sparky4/p/watcom2/bld/nwlib ==================
============= 10:30:58 /home/sparky4/p/watcom2/bld/nwlib/binbuild =============
link bwlib.exe
/usr/bin/ld: wlib.obj: relocation R_X86_64_32 against symbol `Env' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: libio.obj: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: symtable.obj: relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: omfproc.obj: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: writelib.obj: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: wlibutil.obj: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: libwalk.obj: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: symlist.obj: relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: proclib.obj: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: cmdline.obj: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: error.obj: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: implib.obj: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: orlrtns.obj: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: demangle.obj: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: omfutil.obj: relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: coffwrt.obj: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ideentry.obj: relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: orlhash.obj: relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: omfload.obj: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: omfmunge.obj: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: omfflhn.obj: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: elfentr.obj: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: elflwlv.obj: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: elfload.obj: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: coffentr.obj: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: cofflwlv.obj: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: coffload.obj: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: coffimpl.obj: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: maindrv.obj: relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: idedrv.obj: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: idemsgfm.obj: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Error(E42): Last command making (bwlib.exe) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 512
Build failed
builder bootstrap build error

!!!! this is when i run ./build.sh in the $OWROOT directory

**Comment by jmalak** [comment]
Your script is strange. I didn't understand what you are trying to do.
proper full rebuild is simple
```
cd $(OWROOT)
bash ./clean.sh
bash ./build.sh
```
next commands ensure copy of OW bin tree to your location
```
cd bld
builder cprel OWRELROOT=/dos/fdos/watcom2
```

**Comment by sparky4** [comment]
./build.sh fails

**Comment by sparky4** [comment]
when i recompile without clean.sh i get
>**** BUILD rule
================ 11:52:15 /home/sparky4/p/watcom2/bld/causeway ================
========== 11:52:15 /home/sparky4/p/watcom2/bld/causeway/cw32/dos386 ==========
========== 11:52:15 /home/sparky4/p/watcom2/bld/causeway/cwc/dosi86 ===========
bld_cl ./mkcode.exe
bld_as copystub.obj
bld_link copystub.tmp
./mkcode.exe copystub.gh
bld_as decstub.obj
bld_link decstub.tmp
./mkcode.exe decstub.gh

cc cwc.obj
./copystub.gh(65610): Error! E1145: Internal compiler limit exceeded, break module into smaller pieces
Error(E42): Last command making (cwc.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512

**Comment by jmalak** [comment]
you have something wrong, because compiler uses Linux header for DOS build, it is wrong.
Check environment variables as INCLUDE, INCLUDE_DOS, INCLUDE_...
Try to delete bld/causeway tree and get fresh copy by git

**Comment by sparky4** [comment]
my includes
OWDEFINCLUDE=/dos/fdos/watcom2/h:/dos/fdos/watcom2/h/dos:/dos/fdos/watcom2/lh:/dos/fdos/watcom2/h/os2
INCLUDE=/dos/fdos/watcom2/h:/dos/fdos/watcom2/h/dos:/dos/fdos/watcom2/lh:/dos/fdos/watcom2/h/os2

**Comment by sparky4** [comment]
i did what you said and
`../../asm/cw32.asm(4524): Note! N594: Extending jump
link cwstub.exe
bcwc cw32.exe cwstub.exe
as cwdstub.obj
link cwdstub.exe
========== 09:34:02 /home/sparky4/p/watcom2/bld/causeway/cwc/dosi86 ===========
bld_cl ./mkcode.exe
bld_as copystub.obj
bld_link copystub.tmp
./mkcode.exe copystub.gh
bld_as decstub.obj
bld_link decstub.tmp
./mkcode.exe decstub.gh
cc cwc.obj
./copystub.gh(65610): Error! E1145: Internal compiler limit exceeded, break module into smaller pieces
Error(E42): Last command making (cwc.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed`

noo! >.<

**Comment by jmalak** [comment]
Your INCLUDE variable is wrong
It must contains path definition for bootstrap compiler
In your case you use OW Linux version of compiler for bootstrap
In this case INCLUDE must contains only /dos/fdos/watcom2/lh

**Comment by sparky4** [comment]
causeway never compiles when i ran ./clean.sh so i always have to copy over lappy4's (my only 64 bit laptop in service) bld/causeway

**Comment by jmalak** [comment]
You need two setups. One for OW build and second one for your application build.
May be simple solution of your problem, remove INCLUDE variable before you start OW build and after OW build return it back.

**Comment by sparky4** [comment]
I fixed it

`INCLUDE=$watcom/h`

with just this~
