### ISSUE TITLE
Core trying to use "cout" object

### ISSUE THREAD

**Issue by francisco1234** [open-watcom/open-watcom-v2#377]
Hi,

I just downloaded OW binaries and tested this bit of code on windows 7 and linux centos 7:

#include\<map>
#include\<string>
#include\<iostream>

using namespace std;

int main()
{

        map<int, string>m;
        m.insert(pair<int, string>(0, "0"));
        m.insert(pair<int, string>(1, "1"));
        m.insert(pair<int, string>(2, "2"));
        m.insert(pair<int, string>(3, "3"));

        for(map<int, string>::iterator it=m.begin(); it!=m.end(); it++) {
                //printf("key: %i value: %s\n", it->first, it->second.c_str());
                cout << "key: " << it->first << " value: " << it->second.c_str() << endl;
        }

        return 0;
}

Could someone help?
Got this trace:

The instruction at 0x00404f96 referenced memory at 0xfff71645.
The memory could not be read.
Exception fielded by 0x00406a40
EAX=0x00000000 EBX=0x00000005 ECX=0x0040b834 EDX=0x0040b015
ESI=0x0040e038 EDI=0x0040b01b EBP=0xfff7162d ESP=0x0018fc94
EIP=0x00404f96 EFL=0x00010206 CS =0x00000023 SS =0x0000002b
DS =0x0000002b ES =0x0000002b FS =0x00000053 GS =0x0000002b
Stack dump (SS:ESP)
0x00000000 0x0040b015 0x0040e000 0x0040b01b 0x0040e038 0x0040b834
0x00403e17 0x00000000 0x0040b015 0x0040e038 0x00000000 0x00000000
0x00000005 0x00000005 0xfffffffb 0x0018fe60 0x0040b01b 0x0040e038
0x00402193 0x00000000 0x0018fcf4 0x001c0ab0 0x001c0ae8 0x004012a8
0x002b1d10 0x00000000 0x00000004 0x001c0af8 0x001c0ab0 0x001c0b68
0x00000000 0x00000001 0x002b1d18 0x001c0aa0 0x00000001 0x00000008
0x00000000 0x2ea42f65 0x001c0a90 0x00000001 0x00000008 0x00000003
0x002b0000 0x001c0aa0 0x00000001 0x00000008 0x00000002 0x02000002
0x001c0a90 0x00000001 0x00000008 0x00000002 0x00000004 0x001c0aa0
0x00000001 0x00000008 0x00000000 0x00000028 0x001c0aa0 0x00000001
0x00000008 0x00000003 0x00000000 0x001c0a90 0x00000001 0x00000008
0x00000001 0x77937009 0x001c0a90 0x00000001 0x00000008 0x0018ff74

Version used:
Open Watcom C/C++ x86 32-bit Compiler Driver Program
Version 2.0 beta Sep 13 2017 04:58:24 (32-bit)

Thanks, Fran.

**Comment by jmalak** [comment]
Thanks for your bug report.
I will investigated source of problem and fix it.

**Comment by jmalak** [comment]
It should be fixed by commit 82e972bee0137bb978ee8c82a7938847cfff0bec
please check

**Comment by francisco1234** [comment]
It does works now.
Thanks.
