### ISSUE TITLE
16-bit C compiler, unsigned char value in AL with redundant zeroing of AH

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#379]
I just noticed that when compiling the 16-bit target of DOSLIB in hw/sndsb, the sndsb_read_dsp() function has a redundant instruction to clear AH after loading AL.

The code in question:

    register unsigned char c; /* encourage C/C++ optimizer to convert c = inp() ... return c to just return inp() */

            if (!(inp(status_port) & 0x80)) {/* data NOT available? */
                if (--patience == 0U)
                    break;
            }
            else {
                c = inp(read_data_port);
                DEBUG(fprintf(stdout,"sndsb_read_dsp() == 0x%02X\n",c));
                return c;
            }

Assembly in the OBJ file produced by the compiler:

    Segment: _TEXT BYTE USE16 0000007D bytes
    0000                            sndsb_read_dsp_:
    0000  53                                push            bx
    0001  51                                push            cx
    0002  52                                push            dx
    0003  56                                push            si
    0004  57                                push            di
    0005  89 C3                             mov             bx,ax
    0007  8B 77 0A                          mov             si,word ptr 0xa[bx]
    000A  8B 7F 0A                          mov             di,word ptr 0xa[bx]
    000D  BB 05 00                          mov             bx,0x0005
    0010  83 C6 0E                          add             si,0x000e
    0013  83 C7 0A                          add             di,0x000a
    0016  89 F2                             mov             dx,si
    0018                            L$1:
    0018  B9 99 0D                          mov             cx,0x0d99
    001B                            L$2:
    001B  EC                                in              al,dx
    001C  2A E4                             sub             ah,ah
    001E  A8 80                             test            al,0x80
    0020  75 05                             jne             L$3
    0022  49                                dec             cx
    0023  74 0B                             je              L$4
    0025  EB F4                             jmp             L$2
    0027                            L$3:
    0027  89 FA                             mov             dx,di
    0029  EC                                in              al,dx
    002A  2A E4                             sub             ah,ah
    002C  30 E4                             xor             ah,ah
    002E  EB 06                             jmp             L$5
    0030                            L$4:
    0030  4B                                dec             bx
    0031  75 E5                             jne             L$1
    0033  B8 FF FF                          mov             ax,0xffff
    0036                            L$5:
    0036  5F                                pop             di
    0037  5E                                pop             si
    0038  5A                                pop             dx
    0039  59                                pop             cx
    003A  5B                                pop             bx
    003B  C3                                ret

Note the instructions at 002A and 002C that are redundant instructions to zero AH.

**Comment by joncampbell123** [comment]
I'm also curious why the generated assembly loads word ptr 0xa[bx] twice to load SI and DI, when it could optimize for size and speed by loading word ptr 0xa[bx] once into SI and copy to DI.

This is in DOSLIB, hw/sndsb/sbdspio.c

**Comment by jmalak** [comment]
I need to know used compiler options.

**Comment by joncampbell123** [comment]
Here you go:

    -fr=nul -fo=dos86l/.obj -i=.. -i../.. -e=2 -zu -zq -ml -d0  -s -bt=dos -oilrb -os -wx -0 -dTARGET_MSDOS=16 -dMSDOS=1 -dTARGET86=86 -DMMODE=l -q sbdspio.c

**Comment by joncampbell123** [comment]
I'm noticing in fact that bytewise I/O read seems to be followed by sub ah,ah in general even if it's unnecessary. It appears all over the DOSLIB compiled binaries. Something's screwy with the inp() intrinsic function.

**Comment by jmalak** [comment]
The inp.. functions are declared returning "unsigned int" type, therefore high part of output register (AX/EAX) is zeroed as part of intrinsic instruction.
if you want to optimize it out you can define your own function by example
unsigned char inpb( unsigned port );
#pragma aux inpb = "in AL,DX" parm [dx] value [al];

**Comment by joncampbell123** [comment]
When did that happen??

inp() as I understand it has always meant "read an 8-bit I/O port" so why isn't inp() as an intrinsic declared with a return value of unsigned char? If the programmer assigns it to an int or unsigned int then the compiler should generate the XOR/SUB AH,AH as part of the type promotion, otherwise it's unnecessary.

While it doesn't break anything, it adds 2 bytes per I/O read within the code. As 16-bit DOS is limited to the first 640KB of RAM, having excess instructions in the code segment is a bit burdensome.

That also doesn't explain why the 32-bit compiler isn't doing the same thing, when the 16-bit compiler is.

**Comment by jmalak** [comment]
I understand your feeling. 
But inp.. functions were defined this way by Watcom, probably for compatibility with Microsoft C.
See definition in conio.h.
OW compilers implement intrinsic functions same way as #pragma aux function =
it follows prototype for non intrinsic function with 2/4 bytes return value. 
I can review internal prototypes and encodings of inp.. functions if it is possible to use different prototype for "intrinsic" function then regular function and do conversion between types by code generator.

**Comment by jmalak** [comment]
Anyway 32-bit compiler do xor eax,eax before in al,dx (it is also part of intrinsic implementation).

**Comment by jmalak** [comment]
Below is output from disassembler if #pragma aux is used for in al,dx instruction.
```
Segment: _TEXT BYTE USE16 0000002E bytes
0000                            sndsb_read_dsp_:
0000  53                                push            bx
0001  51                                push            cx
0002  52                                push            dx
0003  56                                push            si
0004  57                                push            di
0005  31 FF                             xor             di,di
0007  31 F6                             xor             si,si
0009  B9 05 00                          mov             cx,0x0005
000C                            L$1:
000C  BB 05 00                          mov             bx,0x0005
000F                            L$2:
000F  89 FA                             mov             dx,di
0011  EC                                in              al,dx
0012  A8 80                             test            al,0x80
0014  75 05                             jne             L$3
0016  4B                                dec             bx
0017  74 09                             je              L$4
0019  EB F4                             jmp             L$2
001B                            L$3:
001B  89 F2                             mov             dx,si
001D  EC                                in              al,dx
001E  30 E4                             xor             ah,ah
0020  EB 06                             jmp             L$5
0022                            L$4:
0022  49                                dec             cx
0023  75 E7                             jne             L$1
0025  B8 FF FF                          mov             ax,0xffff
0028                            L$5:
0028  5F                                pop             di
0029  5E                                pop             si
002A  5A                                pop             dx
002B  59                                pop             cx
002C  5B                                pop             bx
002D  C3                                ret

```
used function declaration is
unsigned char inpx( unsigned p );
#pragma aux inpx = "in al,dx" parm [dx] value [al];

**Comment by joncampbell123** [comment]
I can accept this workaround for now but it would be better long term if inp() did not need this zero extension (unless inp() is treated as a normal function call for Microsoft C compatibility as you say).

**Comment by jmalak** [comment]
you must create your implementation including prototype and use macro for redirection inp,...functions to your version, no other way

**Comment by joncampbell123** [comment]
Understood.
