### ISSUE TITLE
inline asm for lrint() family procedures

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#385]
Can any of you guys review the following inline asm of lrint()
procedures for correctness please?  (Yes I know that this v2
fork added them to libc, but I need fast, gcc -ffast-math style
inline versions.) Thanks in advance.

```
extern __inline long long llrint(double);
#pragma aux llrint = \
    "push  eax" \
    "push  edx" \
    "fistp qword ptr [esp]" \
    "pop   edx" \
    "pop   eax" \
    parm [8087] \
    value [eax edx] \
    modify exact [edx eax];

extern __inline long lrint(double);
#pragma aux lrint = \
    "push  eax" \
    "fistp qword ptr [esp]" \
    "pop   eax" \
    parm [8087] \
    value [eax] \
    modify exact [eax];

extern __inline long lrintf(float);
#pragma aux lrintf = \
    "push  eax" \
    "fistp dword ptr [esp]" \
    "pop   eax" \
    parm [8087] \
    value [eax] \
    modify exact [eax];
```

**Comment by jmalak** [comment]
It looks OK for me. 
#pragma aux functions don't require __inline modifier, they are "only" inlined.

**Comment by sezero** [comment]
Thank you.

**Comment by sezero** [comment]
Well, there were issues with the double versions:

- lrint() segfaulted: fixed by sub'ing esp by 4, and adding 4 to it before ret.
- llrint had push/pop eax and edx in reverse order. (also needed esp fix above)

Here are the ones that work for me.  @jmalak: if you can please re-confirm?

```
#pragma aux llrint = \
    "sub esp,4" \
    "push  edx" \
    "push  eax" \
    "fistp qword ptr [esp]" \
    "pop   eax" \
    "pop   edx" \
    "add esp,4" \
    parm [8087] \
    value [eax edx] \
    modify exact [edx eax];

extern long lrint(double);
#pragma aux lrint = \
    "sub esp,4" \
    "push  eax" \
    "fistp qword ptr [esp]" \
    "pop   eax" \
    "add esp,4" \
    parm [8087] \
    value [eax] \
    modify exact [eax];
```

**Comment by jmalak** [comment]
Sorry I overlooked type mismatch.
esp fix is not necessary, it mask only type mismatch in fistp instruction
I think this one is correct
```
extern long long llrint(double);
#pragma aux llrint = \
    "push  eax" \
    "push  eax" \
    "fistp qword ptr [esp]" \
    "pop   eax" \
    "pop   edx" \
    parm [8087] \
    value [eax edx];

extern long lrint(double);
#pragma aux lrint = \
    "push  eax" \
    "fistp dword ptr [esp]" \
    "pop   eax" \
    parm [8087] \
    value [eax];

extern long lrintf(float);
#pragma aux lrintf = \
    "push  eax" \
    "fistp dword ptr [esp]" \
    "pop   eax" \
    parm [8087] \
    value [eax];

```

**Comment by sezero** [comment]
> ```
> extern long long llrint(double);
> #pragma aux llrint = \
>     "push  eax" \
>     "push  eax" \
>     "fistp qword ptr [esp]" \```

First push should be edx, no?

> ```
> extern long lrint(double);
> #pragma aux lrint = \
>     "push  eax" \
>     "fistp dword ptr [esp]" \```

How shall I load a 64 bit double wıth dword?

**Comment by jmalak** [comment]
Floating point value is on FPU stack not on CPU stack.
PUSH-es before FISTP instruction only reserve space for return value, you can use SUB ESP,4/8 instead of PUSH-es, but I think PUSH-es are quicker and shorter instructions.
FISTP instruction load long or long long value onto reserved CPU stack and POP it from FPU stack.
CPU POP-s load return value from CPU stack into CPU registers and correct ESP pointer.
You should allocate only return value size on CPU stack.

**Comment by jmalak** [comment]
here is test code
```
extern long long llrint(double);
#pragma aux llrint = \
    "push  eax" \
    "push  eax" \
    "fistp qword ptr [esp]" \
    "pop   eax" \
    "pop   edx" \
    parm [8087] \
    value [eax edx];

extern long lrint(double);
#pragma aux lrint = \
    "push  eax" \
    "fistp dword ptr [esp]" \
    "pop   eax" \
    parm [8087] \
    value [eax];

extern long lrintf(float);
#pragma aux lrintf = \
    "push  eax" \
    "fistp dword ptr [esp]" \
    "pop   eax" \
    parm [8087] \
    value [eax];

long long t1( double x )
{
    return( llrint( x  ) );
}

long t2( double x )
{
    return( lrint( x  ) );
}

long t3( float x )
{
    return( lrintf( x  ) );
}
```
and disassembler code
```
Segment: _TEXT BYTE USE32 0000005B bytes
0000				t1_:
0000  DD 44 24 04			fld		qword ptr [esp+0x4]
0004  50				push		eax
0005  50				push		eax
0006  DF 3C 24				fistp		qword ptr [esp]
0009  58				pop		eax
000A  5A				pop		edx
000B  C2 08 00				ret		0x0008

Routine Size: 14 bytes,    Routine Base: _TEXT + 0000

000E				t2_:
000E  DD 44 24 04			fld		qword ptr [esp+0x4]
0012  50				push		eax
0013  DB 1C 24				fistp		dword ptr [esp]
0016  58				pop		eax
0017  C2 08 00				ret		0x0008

Routine Size: 12 bytes,    Routine Base: _TEXT + 000E

001A				t3_:
001A  D9 44 24 04			fld		dword ptr [esp+0x4]
001E  50				push		eax
001F  DB 1C 24				fistp		dword ptr [esp]
0022  58				pop		eax
0023  C2 04 00				ret		0x0004

```
In real code input floating-point parameter is load on FPU stack by instruction FLD (added by code generator) and next inline code is used.

**Comment by sezero** [comment]
Ah-ha. Sorry that I got confused. Thanks.

**Comment by jmalak** [comment]
You are welcome.

**Comment by sezero** [comment]
Closing this.

P.S.: Any plans to make these functions to intrinsics?
