### ISSUE TITLE
Seeking information on a internal type

### ISSUE THREAD

**Issue by tomsons26** [open-watcom/open-watcom-v2#386]
Hi im helping a team that is working on reverse engineering some really old Watcom compiled games.
There is a internal structure for classes that helps us find ctor's and dtors,
So far only things i know about it are:
the debug symbol shows as char const operator`__internal'[]
and the structure afict is
struct WatcomTypeInfo
{
  char field_0;
  void *Constructor;
  void *field_5;
  void *Deconstructor;
  int SizeOfClassStruct;
  char field_11;
  char field_12;
  char field_13;
};
field_5 in this game case is afict always __wcpp_2_undefed_cdtor__.
I'm trying to find the actual watcom structure for it or what constructs it.

**Comment by jmalak** [comment]
In the current OW prefix for all internal (run-time) symbols is "__wcpp_4_".
The full symbol name is __wcpp_4_undefed_cdtor is function used by exception handler and display appropriate message and do run-time library fatal exit.
Generaly most run-time library definitions are in bld\cpplib\runtime\h subdirectory.

**Comment by tomsons26** [comment]
hmm
https://github.com/open-watcom/open-watcom-v2/blob/master/bld/cpplib/runtime/h/cpplib.h#L151
https://github.com/open-watcom/open-watcom-v2/blob/787e403ead9968417d9aa2b7ea675b96b9ffb24e/bld/plusplus/c/cgbktsig.c#L255
Appear to be similar but ts_hdr isn't one byte and after the size there's only 3 chars so not enough to make a name PTR, hm unless Watcom 2 only had a flag as byte as the first entry and was bugged and set only 3 chars after the size....

**Comment by jmalak** [comment]
There is rt_type_sig  union that any of rt structure can be used.
Anyway it looks like very old code, may be WATCOM 8 or 9, because OW and WATCOM 11 use number 4 for C++ run-time symbols

**Comment by jmalak** [comment]
Question is how big difference between version 2 and 4 of run-time environment.
We have no any other (older) source code for Watcom, that you will need to take existing code as idea what could be there in old C++ run-time environment.

**Comment by tomsons26** [comment]
Yea it would be really old Watcom, the games range from 1995 to 1998.
Seems this is what i'm looking for then, thanks for the help!
