### ISSUE TITLE
Self-extract snapshot for Linux doesn't work. Why not to provide snapshots in .tar.gz/bz2/tar.xz?

### ISSUE THREAD

**Issue by Wohlstand** [open-watcom/open-watcom-v2#392]
# Non-runnable self-extract archive for Linux
Self-extract executable snapshot doesn't works and always prints me "xterm-256color unknown terminal type" and exits:

![default](https://user-images.githubusercontent.com/6751442/33506316-624e732a-d700-11e7-8b6d-c26cd235b982.png)
Linux Mint 18.3 x64 with kernel:
```
Linux whl-pc-001l 4.10.0-40-lowlatency #44~16.04.1-Ubuntu SMP PREEMPT Thu Nov 9 17:36:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

# Snapshots packed into tar.* for Linux and other UNIX-like distros
Publishing of snapshots in ZIP or 7Z formats does a loss of all UNIX permission bits and all Linux executables included with snapshot are non-runnable until I will manually mark all ELF files as "executable" `+x` by using `chmod` command.

Suggested to provide snapshots in .tar format which is compressed by any of format on your taste: gz, bz2, xz, lzma.

**Comment by jmalak** [comment]
Please what image you mean exactly?

**Comment by Wohlstand** [comment]
`open-watcom-2_0-c-linux-x86` downloaded from SourceForge from this folder: https://sourceforge.net/projects/openwatcom/files/open-watcom-2.0-2017-11-01/

**Comment by jmalak** [comment]
If I remember properly then installer should recover x bit for Linux host.
I will check and fix it.
Unfortunately archive has no attributes, because it is not possible for multiplatform builder.

**Comment by Wohlstand** [comment]
On Windows you are able to use bash from MSYS toolchain to set bits and pack the tarballs by using tar utility

**Comment by jmalak** [comment]
It is unaccepted, because we must be able to create installers for any target on any supported host (now DOS, Windows, OS/2 and Linux).

**Comment by Wohlstand** [comment]
When installer works properly then yeah, but when I'm not able to run it, therefore a regular archive will help in this situation.

**Comment by jmalak** [comment]
Installer works OK, setup x bit as should.
Problem with terminal is due to some limitation/mistake in OW ui project.
It will require some review of terminal support in ui project.

**Comment by vareille** [comment]
this is solved by adding:
export TERMINFO=/lib/terminfo

**Comment by jmalak** [comment]
I submitted fix 9465e4a8aad7d46ed7cf3a4ec7fa57c0cb203715 for OW ncurses implementation.
Installer problem with terminfo should be fixed by this.
You need not add this environment variable anymore.
The fix affect all Open Watcom UI application on linux as debugger, installer etc.
It should also fix problem with various terminal types due to using default setup for any "unknown" terminal. 
Now terminal info is properly read from terminfo database.

**Comment by jmalak** [comment]
I think best solution is to create OW utility for refresh x-bit on UNIX-like platforms.
It should be fork of installer which will be minimise to setup x-bit only for file defined in setup.inf as executable (it is done regulary by installer after copying files).

**Comment by jmalak** [comment]
problem with "xterm-256color" should be resolved, I fixed UI subroject to properly handle new binary format of terminfo (ncurses 6.1) and also fix handling of X terminal at all.

**Comment by jmalak** [comment]
Regular OW build was moved to Microsoft Azure Pipelines and problem with ow-snapshot archive was fixed. Now complete OW build from Linux with all executable flags are archived to tar.gz format that file attributes are not changed.
