### ISSUE TITLE
Open Watcom source compilation on Ubuntu 17.10 fails in browser build

### ISSUE THREAD

**Issue by anwosu** [open-watcom/open-watcom-v2#395]
I am trying to build open-watcom from travis git repository. The build fails with the following message:
================ 23:28:58 /home/gus/watcomv2/bld/browser/nt386 ================
dosemu -dumb -quiet wgml.bat
ERROR: unknown window sizes li=0  co=0, setting to 80x25
ERROR: MFS: couldn't find root path /media/CDROM
D:\watcomv2\docs\nt>lredir w: linux\fs/home/gus/watcomv2/docs
W: = LINUX\FS/HOME/GUS/WATCOMV2/DOCS attrib = READ/WRITE
D:\watcomv2\docs\nt>w:\gml\dos\wgml.exe guitool ( file wgmlopts.tmp
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
mv: cannot stat 'tmp.ptf': No such file or directory
Error(E42): Last command making (compile_gml_to_xxx;wbrw.h) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (wbrw) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (/home/gus/watcomv2/docs/nt/wbrw.h) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed

Any help is appreciated.

**Comment by jmalak** [comment]
If you have problem with DOSEMU then alternative is to install DOSBOX and adding following line to your setup script (or uncomment existing line).
export OWDOSBOX=dosbox

**Comment by anwosu** [comment]
Thank you for your response.
I tried dosbox and I also failed with a different message:
================ 23:04:40 /home/gus/watcomv2/bld/browser/nt386 ================
dosbox -noautoexec -c "mount c /home/gus/watcomv2/docs" -c "mount d ." -c "mount e /home/gus/watcomv2/bld" -c "d:wgml.bat" -noconsole
DOSBox version 0.74
Copyright 2002-2010 DOSBox Team, published under GNU GPL.
---
CONFIG:Loading primary settings from config file /home/gus/.dosbox/dosbox-0.74.conf
MIXER:Got different values from SDL: freq 44100, blocksize 512
ALSA:Can't subscribe to MIDI port (65:0) nor (17:0)
MIDI:Opened device:none
DOSBox switched to max cycles, because of the setting: cycles=auto. If the game runs too fast try a fixed cycles amount in DOSBox's options.
Exit to error: DRC64:Unhandled memory reference

mv: cannot stat 'TMP.PTF': No such file or directory
Error(E42): Last command making (compile_gml_to_xxx;wbrw.h) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (wbrw) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (/home/gus/watcomv2/docs/nt/wbrw.h) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed
=============================================================
Thanks for any help.

**Comment by jmalak** [comment]
It looks like Ubuntu 17.10 problem, because both DOS emulators report some internal problems.
I have test Ubuntu installation 16.04 version and it works OK with both DOSEMU and DOSBOX.
Travis build system uses Ubuntu 14.04 and works with DOSEMU, I checked it with DOSBOX and it is OK too.
Anyway you can check DOSEMU or DOSBOX on your system by some DOS application, to be sure that it is working properly. You can try to apply latest fixes to Ubuntu if it fix your problem or not.

**Comment by anwosu** [comment]
Thank you very much. I will try to look at the failed processes in detail
and let you know. Again, thank you for your help. Much appreciated.

On Dec 11, 2017 11:54 PM, "Jiří Malák" <notifications@github.com> wrote:

It looks like Ubuntu 17.10 problem, because both DOS emulators report some
internal problems.
I have test Ubuntu installation 16.04 version and it works OK with both
DOSEMU and DOSBOX.
Travis build system uses Ubuntu 14.04 and works with DOSEMU, I checked it
with DOSBOX and it is OK too.
Anyway you can check DOSEMU or DOSBOX on your system by some DOS
application, to be sure that it is working properly. You can try to apply
latest fixes to Ubuntu if it fix your problem or not.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/open-watcom/open-watcom-v2/issues/395#issuecomment-350952928>,
or mute the thread

**Comment by jmalak** [comment]
No update, closing.
