### ISSUE TITLE
Build doesn't work with 32-bit Watcom compiler

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#400]
I was about to test a minor change so synced with latest version, but it appears the build is broken. I then downloaded a fresh copy, but still the same error in the build process. I'm using a Watcom version from April 2017 to build.

Log:

**** Building the  bootstrap
Build host: NT
=========================== 00:15:06 c:\new-ow\bld ============================
**** Building the watcom bootstrap
======================== 00:15:06 c:\new-ow\bld\watcom ========================
=================== 00:15:06 c:\new-ow\bld\watcom\binbuild ====================
======================== 00:15:06 c:\new-ow\bld\watcom ========================
======================== 00:15:06 c:\new-ow\bld\watcom ========================
**** Building the posixutl bootstrap
======================== 00:15:06 c:\new-ow\bld\posix =========================
==================== 00:15:06 c:\new-ow\bld\posix\binbuild ====================
cc alloc.obj
lib posix.lib
Error(F38): (cat.obj) does not exist and cannot be made from existing files
Error(E02): Make execution terminated
Error(E42): Last command making (cat) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 2
Build failed

**Comment by jmalak** [comment]
It is strange. I checked on my build box with this OW version and it works.
- try to refresh you build script from latest setvars script
- try to do full cleanup before build by clean script

**Comment by rdos314** [comment]
But I still don't understand how and where I can download a version that can be installed and used to build with. I don't have MSVC or any other compiler for Windows. I don't have Linux either.

**Comment by rdos314** [comment]
A tip is that if people are building under Windows 10,  it is necessary to disable the antimalware protection as it will take almost forever with it enabled. Apparently, Windows scans every executable before running them, and the build process invokes the compiler and other tools many times.

**Comment by rdos314** [comment]
It worked to build with current compiler. IDE also works.

**Comment by jmalak** [comment]
There is still problem with C++ compile for 64-bit Linux which create damaged run-time library.
Building on 64-bit Windows is OK.
Travis use 64-bit Linux therefore this build have damaged C++ compiler + C++ run-time library, this problem is there from beginning, because C++ 64-bit Linux port was never working properly.  I still doesn't identified source of problem.
If you build OW on Windows 32/64 or 32-bit Linux then it is OK.
