### ISSUE TITLE
Debug build of clib doesn't work

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#402]
Setting OWDEBUGBUILD=1, and only rebuilding clib, causes the following error:

============= 14:10:15 C:\ow\bld\clib\time\library\rdos.386\mf_s ==============
============ 14:10:15 C:\ow\bld\clib\time\library\rdosdev.386\mc_r ============
============= 14:10:15 C:\ow\bld\clib\time\library\windows.086\mc =============
============= 14:10:15 C:\ow\bld\clib\time\library\windows.086\ml =============
============= 14:10:15 C:\ow\bld\clib\time\library\windows.086\mm =============
============= 14:10:15 C:\ow\bld\clib\time\library\windows.086\ms =============
============ 14:10:15 C:\ow\bld\clib\time\library\windows.386\mf_r ============
============ 14:10:15 C:\ow\bld\clib\time\library\windows.386\mf_s ============
============= 14:10:15 C:\ow\bld\clib\time\library\winnt.386\mf_r =============
============ 14:10:15 C:\ow\bld\clib\time\library\winnt.386\mf_rd =============
============ 14:10:15 C:\ow\bld\clib\time\library\winnt.386\mf_rp =============
============= 14:10:15 C:\ow\bld\clib\time\library\winnt.386\mf_s =============
=========== 14:10:15 C:\ow\bld\clib\win386\library\windows.386\mf_r ===========
=========== 14:10:15 C:\ow\bld\clib\win386\library\windows.386\mf_s ===========
=============== 14:10:15 C:\ow\bld\clib\library\linux.386\mf_r ================
=============== 14:10:15 C:\ow\bld\clib\library\linux.386\mf_rd ===============
=============== 14:10:15 C:\ow\bld\clib\library\linux.386\mf_s ================
Error(F38): (..\..\..\alias\library\linux.386\mf_sd\clib3s.lib) does not exist and cannot be made from existing files
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 4
Build failed

Apparently, there is something in the Linux build of clib that isn't compatible with building a debug-version of clib.

**Comment by jmalak** [comment]
Only register calling convention debug CRTL is build for development purpose.
It must be done by run `builder build debug .or` in bld/clib folder.
Anyway global build of OW debug version is not supported.

**Comment by rdos314** [comment]
OK, that's fine. 

But surely it must be possible to build debug versions of the debugger and the trap gates too for Windows and RDOS targets? Can this be done in the bld/trap and bld/vw folders with the same command?

**Comment by rdos314** [comment]
I've tried it, but there are still no symbols in the libraries, so I cannot debug the library code at the source level.

**Comment by jmalak** [comment]
There are two approaches to build CRTL C/C++.
1. build debug version of CRTL for distribution, it has different name then standard library
2. build debug version of standard CRTL, it has the same name as standard library
first is build by `builder build debug .or` command and it is located in special subdirectory and needs own makefile
second is build by `builder build OWDEBUGBUILD=1` command and is located in standard subdirectory (replace standard library)
the problem is that OW doesn't handle debug libraries (paralely to standard libraries) by compiler reference and by linker
compilers and linker should select proper library name debug or standard

**Comment by jmalak** [comment]
generaly if you want to build debugger as debug version it depends on projects which are used to whole debugger. You can build only part of debugger with debug symbols.
If you want debugging trap file you compile trap with OWDEBUGBUILD=1 and always wv project with OWDEBUGBUILD=1 other parts will be without symbols info.
It is your decision what part of debugger you wanr debug, by example if you want to debug mad then compile it with OWDEBUGBUILD=1 and also wv with OWDEBUGBUILD=1

**Comment by jmalak** [comment]
I fixed (submit 1a492eb649d1ef18910c03d002c79988847e9cce) the problem with run-time libraries debug version build
now it should be build without problem by both methods

**Comment by rdos314** [comment]
Yes, now it works fine.
