### ISSUE TITLE
dosemu crashes

### ISSUE THREAD

**Issue by andikleen** [open-watcom/open-watcom-v2#404]
I tried to build open-watcom-v2 on my opensuse tumbleweed system again, and it ends with

dosemu -dumb -quiet wgml.bat
ERROR: unknown window sizes li=0  co=0, setting to 80x25
ERROR: MFS: couldn't find root path /media/CDROM
D:\compiler\open-watcom-v2\docs\nt>lredir w: linux\fs/home/andi/compiler/open-watcom-v2/docs
W: = LINUX\FS/HOME/ANDI/COMPILER/OPEN-WATCOM-V2/DOCS attrib = READ/WRITE
D:\compiler\open-watcom-v2\docs\nt>w:\gml\dos\wgml.exe guitool ( file wgmlopts.tmp
DPMI: Unhandled Exception 0e - Terminating Client
It is likely that dosemu is unstable now and should be rebooted
*** stack smashing detected ***: <unknown> terminated
Abort
mv: cannot stat 'tmp.ptf': No such file or directory
Error(E42): Last command making (compile_gml_to_xxx;wbrw.h) returned a bad statu

I understand dosemu is only needed to build the documentation, which I don't really need. is there an easy way to skip this step?

**Comment by andikleen** [comment]
Also this is a 64bit system so it's obvious that dosemu doesn't work

**Comment by andikleen** [comment]
Ok after forcing dosbox it works. perhaps it should do that automatically on 64bit build systems?

**Comment by gbin** [comment]
What do you mean by "forcing dosbox" ? @andikleen

**Comment by jmalak** [comment]
Install DOSBOX on your system and configure approriate environment variable OWDOSBOX in setup script.
For *NIX system 
`export OWDOSBOX=dosbox`
for non-*NIX system
`set OWDOSBOX=<full path to dosbox executable>`
.Look into appropriate setvars... script for host OS comment.

**Comment by hadjiprocopis** [comment]
Thanks jmalak for the clarification. This now works for me (linux fedora 30)
