### ISSUE TITLE
Text version of wd crashes when setting up the menu

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#406]
NumMenus in uimenu.c is 11, but should be 10 as there are only 10 items in the main menu. Things crashes when drawing the menu.  In uimenutitlebar() when menu = 10, menutitle() sends a NULL title string to bstring.

NumMenus is set from uimenucount(), but I'm unsure why it returns one item too much.

**Comment by jmalak** [comment]
I am reworking a ui code little bit to don't mix menu items identification by two indexes
one is 0 based and second is 1 based, now it uses only one 0 based
I fixed it in ui but some fixing is necessary in gui project too.

**Comment by jmalak** [comment]
It should be fixed by latest commits.

**Comment by rdos314** [comment]
Yes, seems to be fixed.
