### ISSUE TITLE
wlib: Error! Unable to replace contents of file 'foobar.lib'. Permission denied

### ISSUE THREAD

**Issue by zoomosis** [open-watcom/open-watcom-v2#407]
Hello,

I cannot get the latest version of wlib from the 2018-02-26 OpenWatcom 2.0 snapshot to append to a .lib file.

OpenWatcom 1.9 works fine.

I'm running Windows 7 32-bit.

wlib is at C:\watcom20\binnt\wlib.exe.

Example:

C:\src\foobar>ver

Microsoft Windows [Version 6.1.7601]

C:\src\foobar>type foo.cpp
void foo() {}

C:\src\foobar>type bar.cpp
void bar() {}

C:\src\foobar>type makefile
TARGET=foobar.lib
OBJS=foo.obj bar.obj

.cpp.obj:
        wcl386 -c $<
        wlib $(TARGET) -+$@

$(TARGET): $(OBJS)

.IGNORE
clean:
        del *.obj
        del $(TARGET)

C:\src\foobar>wmake
Open Watcom Make Version 2.0 beta Feb 25 2018 13:51:31 (32-bit)
Copyright (c) 2002-2018 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
        wcl386 -c foo.cpp
Open Watcom C/C++ x86 32-bit Compile and Link Utility
Version 2.0 beta Feb 25 2018 14:02:36 (32-bit)
Copyright (c) 2002-2018 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
        wpp386 foo.cpp
Open Watcom C++ x86 32-bit Optimizing Compiler
Version 2.0 beta Feb 25 2018 13:57:32 (32-bit)
Copyright (c) 2002-2018 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1989-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
foo.cpp: 99 lines, no warnings, no errors
Code size: 11
        wlib foobar.lib -+foo.obj
Open Watcom Library Manager Version 2.0 beta Feb 25 2018 13:51:05 (32-bit)
Copyright (c) 2002-2018 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
Warning! Cannot open 'foobar.lib' - library will be created
        wcl386 -c bar.cpp
Open Watcom C/C++ x86 32-bit Compile and Link Utility
Version 2.0 beta Feb 25 2018 14:02:36 (32-bit)
Copyright (c) 2002-2018 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
        wpp386 bar.cpp
Open Watcom C++ x86 32-bit Optimizing Compiler
Version 2.0 beta Feb 25 2018 13:57:32 (32-bit)
Copyright (c) 2002-2018 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1989-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
bar.cpp: 99 lines, no warnings, no errors
Code size: 11
        wlib foobar.lib -+bar.obj
Open Watcom Library Manager Version 2.0 beta Feb 25 2018 13:51:05 (32-bit)
Copyright (c) 2002-2018 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
Error! Unable to replace contents of file 'foobar.lib'. Permission denied

C:\src\foobar>dir
 Volume in drive C is Windows 7
 Volume Serial Number is 0452-7A6A

 Directory of C:\src\foobar

2018-02-26  17:19                18 bar.cpp
2018-02-26  17:24               353 bar.obj
2018-02-26  17:19                18 foo.cpp
2018-02-26  17:24               353 foo.obj
2018-02-26  17:24             2,048 foobar.lib
2018-02-26  17:19               160 makefile
2018-02-26  17:24             2,560 _wlib283.$$$
               7 File(s)          5,510 bytes
               2 Dir(s)  22,497,337,344 bytes free

Thanks!

**Comment by jmalak** [comment]
Thanks for bug reporting.
I will fix it ASAP.

**Comment by jmalak** [comment]
it is fixed by ff10f832aea78058c54dba4d062b48675a7dde83 commit

**Comment by zoomosis** [comment]
Confirmed. Thank you.
