### ISSUE TITLE
Inline Assembly Weird Errors

### ISSUE THREAD

**Issue by SeanRamey** [open-watcom/open-watcom-v2#410]
So, I'm having a strange issue that seems to be coming from an inline assembly statement.

The errors I get are:
_src\keyboard.c|99|E1077: Missing '}'|
src\keyboard.c|102|W132: No storage class or type specified|
src\keyboard.c|102|W305: Type 'int' assumed in declaration of 'ppiPortB'|
src\keyboard.c|102|E1129: Type does not agree with previous definition of 'ppiPortB'|
src\keyboard.c|102|N2002: 'ppiPortB' defined in: src\keyboard.c(100)|
src\keyboard.c|102|E1068: Variable 'ppiPortB' already initialized|
src\keyboard.c|102|E1054: Expression must be constant|
src\keyboard.c|103|W132: No storage class or type specified|
src\keyboard.c|103|W305: Type 'int' assumed in declaration of 'scanCode'|
src\keyboard.c|103|E1129: Type does not agree with previous definition of 'scanCode'|
src\keyboard.c|103|N2002: 'scanCode' defined in: src\keyboard.c(99)|
src\keyboard.c|103|E1072: Storage class disagrees with previous definition of 'scanCode'|
src\keyboard.c|103|N2002: 'scanCode' defined in: src\keyboard.c(99)|
src\keyboard.c|103|E1068: Variable 'scanCode' already initialized|
src\keyboard.c|103|E1054: Expression must be constant|
src\keyboard.c|104|E1009: Expecting ')' but found '0x61'|
src\keyboard.c|104|W304: Return type 'int' assumed for function 'outp'|
src\keyboard.c|104|E1062: Inconsistent return type for function 'outp'|
src\keyboard.c|104|N2003: source conversion type is 'int'|
src\keyboard.c|104|N2004: target conversion type is 'unsigned int'|
src\keyboard.c|104|N2002: 'outp' defined in: C:\OpenWatcom\h\conio.h(74)|
src\keyboard.c|104|E1026: Invalid declarator|
src\keyboard.c|104|E1009: Expecting ',' but found '0x61'|
src\keyboard.c|104|E1026: Invalid declarator|
src\keyboard.c|104|E1024: Declared symbol 'ppiPortB' is not in parameter list|
src\keyboard.c|104|E1009: Expecting ',' but found '|'|
src\keyboard.c|104|E1026: Invalid declarator|
src\keyboard.c|104|E1009: Expecting ',' but found '0x80'|
src\keyboard.c|104|E1026: Invalid declarator|
src\keyboard.c|104|E1009: Expecting ',' but found ')'|
src\keyboard.c|104|E1026: Invalid declarator|
src\keyboard.c|105|E1147: Too many errors: compilation aborted|_

I've put comments around the _asm statement that is causing the issue.
If I remove that particular _asm statement, then the file compiles just fine.
I know that this code should work fine, because it compiles and works perfectly with Digital Mars C.
Note that an extremely similar _asm statement at the end of the function compiles without an issue.

```
void interrupt far KeyboardIsr()
{
/* THIS IS THE PROBLEM CODE */
    _asm {
        cli // disable interrupts
    };
/**********************************/

    static unsigned char scanCode = 0;
    unsigned char ppiPortB = 0;

    ppiPortB = inp(PPI_PORT_B); // get the current settings in PPI port B
    scanCode = inp(KEYBOARD_CONTROLLER_OUTPUT_BUFFER); // get the scancode waiting in the output buffer
    outp(PPI_PORT_B, ppiPortB | 0x80); // set the 7th bit of PPI port B (clear keyboard)
    outp(PPI_PORT_B, ppiPortB); // clear the 7th bit of the PPI (enable keyboard)

    // Log scancode
    keyCodeLog[keyCodeLogPosition] = scanCode;
    if(keyCodeLogPosition < 255)
    {
        ++keyCodeLogPosition;
    }


    // Check to see what the code was.
    // Note that we have to process the scan code one byte at a time.
    // This is because we can't get another scan code until the current
    // interrupt is finished.
    switch(scanCode)
    {
    case 0xE0:
        // Extended scancode
        isPreviousCodeExtended = 1;
        break;
    default:
        // Regular scancode
        // Check the high bit, if set, then it's a break code.
        if(isPreviousCodeExtended)
        {
            isPreviousCodeExtended = 0;
            if(scanCode & 0x80)
            {
                scanCode &= 0x7F;
                keyStates[scanCode + 0x7F] = KEY_RELEASED;
            }
            else
            {
                keyStates[scanCode + 0x7F] = KEY_PRESSED;
            }
        }
        else if(scanCode & 0x80)
        {
            scanCode &= 0x7F;
            keyStates[scanCode] = KEY_RELEASED;
        }
        else
        {
            keyStates[scanCode] = KEY_PRESSED;
        }
        break;
    }

    // Send a "Non Specific End of Interrupt" command to the PIC.
    // See Intel 8259A datasheet for details.
    outp(PIC_OPERATION_COMMAND_PORT, 0x20);

    _asm
    {
        sti // enable interrupts
    };
}
```

**Comment by jmalak** [comment]
I am sorry, but I need compilable source code sample which demonstrate your problem.
This fragment is useless because doesn't contain real source code (missing header files reference, missing macros definitions).

**Comment by jmalak** [comment]
Anyway, it is not valid C code.
It is only valid for C++ compiler.
To be valid C code you must move _asm statement after local variables definition.

**Comment by SeanRamey** [comment]
OH, Thank you, that was my problem. I didn't know that you had to put the _asm after local variable definitions. (It is definitions, and not declarations right?) Anyways, it works perfectly now. Maybe this could be a feature request to give better error messages when something is not C compliant, instead of random strange stuff? That's probably asking a lot...

**Comment by jmalak** [comment]
any statement must be after local definition in C block.
You are right that the diagnostics for this issue should be improved.
