### ISSUE TITLE
union REGS issue, missing operand?

### ISSUE THREAD

**Issue by SeanRamey** [open-watcom/open-watcom-v2#411]
Ok, so I'm hesitant to post this on here, seeing as my last question amounted to me not knowing that the C standard requires that you put _asm statements after declaring local variables, but I've searched all over for the proper way to declare a new variable of a union, and I can't see anything wrong with my code. I even copied the example code in the clib.pdf documentation included with OpenWatcom. It just doesn't work (won't compile).

This is my actual code:
```
#include <i86.h>
void VideoInit()
{
    union REGS regs; // The error points here, "src\video.c|16|E1063: Missing operand|"
    regs.w.cx = 0;
    regs.w.dx = 0x1850;
    regs.h.bh = 7;
    regs.w.ax = 0x0600;

    int86(0x10, &regs, &regs);
}
```

This is the example code from the "int86()" documentation in "clib.pdf" from OpenWatcom.
```
/*
* This example clears the screen on DOS
*/
#include <i86.h>
void main()
{
union REGS regs;
regs.w.cx = 0;
regs.w.dx = 0x1850;
regs.h.bh = 7;
regs.w.ax = 0x0600;
#if defined(__386__) && defined(__DOS__)
int386( 0x10, &regs, &regs );
#else
int86( 0x10, &regs, &regs );
#endif
}
```

**Comment by jmalak** [comment]
I didn't see any problem, code compile without errors.
please, put here the full compiler command

**Comment by jmalak** [comment]
closed, no response

**Comment by DenisSalem** [comment]
For those strugling with similar issue:

 Compiling with wcl386 and not wcl solved the issue.

wcl386 bcl=dos <your source.c here>

**Comment by DenisSalem** [comment]
For those struggling with similar issue.
 
Using the following command might help.

wcl -bcl=dos <your source.c here>
