### ISSUE TITLE
How would I go about adding improvements to the optimizer?

### ISSUE THREAD

**Issue by pgrAm** [open-watcom/open-watcom-v2#413]
I've noticed some sequences produced by the compiler for 16bit x86 that could be simplified. I figure these could be addressed by the peephole optimizer.

eg.

the compiler gave me this:

```
    jne             L$36
    jmp             L$40
L$36:
```

though it can be simplified to:

```
    je             L$40
L$36:
```

leaving the label in place in case it is referenced somewhere else. While I've learned a ton about compilers in the last couple months, I'm still not clear about the architecture of OW. Is there a peephole optimizer? Which files are responsible for this and how would I go about adding new productions?

**Comment by jmalak** [comment]
Unfortunately OW code generator has peephole optimizer ( bld/cg/c/peepopt.c file ).
I think a problem could be in another CG part, in branch optimization ( bld/cg/c/opt.....c files ).

**Comment by jmalak** [comment]
For high level view there is CG API description¨you can create pdf version by run wmake hbook=cgdoc in docs/pdf directory.
Any other documentation doesn't exist.
If you want to debug CG then simply create debug version of cg + compiler by command builder debug in bld/cg and bld/cc (for C compiler) or bld/plusplus (for C++ compiler).
In bld/cg/doc is script vc.dbg for debugger which you can use to display CG internal structures in human readable form. dump functions start with Dump... and is available only in debug version of CG
I am not much familiar with OW CG, but if you will have some question try to ask.
If I know then I will help you.

**Comment by jmalak** [comment]
current version of CG documentation is also available from Wiki page
[CG Documentation](https://github.com/open-watcom/travis-ci-ow-builds/blob/master/docs/cgdoc.pdf)
