### ISSUE TITLE
Ndisasm and posix_write

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#416]
It seems like wdis doesn't replace LF with CR LF when outputting results for RDOS. It does seem to work on Win32. It uses posix_write to output results, which is mapped to the write function. Is it really correct that the write function should replace LF with CR LF?  I thought it was supposed to output its data as binary?

Also, there is no such problem for the compiler tools or the linker.

**Comment by jmalak** [comment]
Anyway OW core tools as compilers, librarian, linker use DLL driver or static driver which handle any output in driver code, not in DLL code (core). The handling is very different from simple output used by disassembler.

**Comment by jmalak** [comment]
```
if( ListFileName != NULL ) {
    OutputDest = open( ListFileName, O_WRONLY | O_CREAT | O_TRUNC, PMODE_RW );
    if( OutputDest == -1 )
        openError( ListFileName );
    ChangePrintDest( OutputDest );
}

```

**Comment by jmalak** [comment]
```
if( ListFileName != NULL ) {
    OutputDest = open( ListFileName, O_WRONLY | O_CREAT | O_TRUNC, PMODE_RW );
    if( OutputDest == -1 )
        openError( ListFileName );
    ChangePrintDest( OutputDest );
}
```

**Comment by rdos314** [comment]
I've searched a bit on it, and it appears that if a file is not opened with O_BINARY, then it is a text file and LF should be translated to CR LF. However, I think this will create portability issues since a lot of our code uses "\r\n" as a line terminator instead of "\n", so I'll need to check if a LF is already preceded with a CR before inserting one.

Some articles also claim that text files are 7-bit, but what about UTF-8? Aren't those text files too?

**Comment by jmalak** [comment]
I don't think that use of "\r\n" is current in OW code. Mostly I remove it, if possible.
It is used mainly in Windows specific code where file is open as Binary file and hold text or for clipboard etc.
Anyway bootstrap tools are using "\n" as line end to be portable.

ISO C/C++ define character as 8-bit minimum.
7-bit can be used only with pure ASCII character set (0-127), it is little bit archaic nowdays.
UTF-8 is standard 8-bit characters stream, that no problem with it. 
It doesn't presume anything about LF/CRLF it is OS dependent.

**Comment by jmalak** [comment]
LF/CRLF is transparent, if you need handling CRLF you must open file in "text" mode what is default for all DOS-ish platforms where it is used.
I don't know what is default end-of-line on RDOS.
If it is CR LF then CRTL must be checked for default file open mode "text" otherwise it can be "binary" mode. In OW distribution is file (binmode.obj in library subdirectories) which can switch this behaviour, that if include it to application then default file open mode is "binary" for DOS-ish platforms.

**Comment by rdos314** [comment]
It's code written for RDOS that uses "\r\n" instead of just "\n". Since I'm porting tools, and will also port some UNIX-tools in the future, I need to handle this in a reasonable way. I think I will need to default files to binary, and only do translations if they are explicitly opened as text. Then I'll set the console to text. I hope that will fix the problem so OW tools outputs texts correctly.

I've seen that Win32 does these translations in clib, but I'll do them in kernel instead. 

There is no default end-of-line in RDOS, but I typically transfer files created on RDOS to Windows, and I think the default for Windows is CR LF, so that's what I'll use. Actually, I had hoped to be able to ignore this issue and treat all file-IO as binary, but that is a too simplistic approach it seems.

**Comment by jmalak** [comment]
In this case OW run-time-library for RDOS must have file "text" mode as default for open file.
Files opened in "text" must handled "CRLF" <-> "LF" translation for data read/write.

General rule for OW source code is:
By default in source code should be used in strings "\n" as end-of-line.
Only in platform dependent code can be used "\r\n" or if file is open in binary mode then application must handle "\r\n" and "\n" translation.

**Comment by jmalak** [comment]
None of OS differ between "text" and "binary" mode. It is only run-time library mode which define how data from/to file is processed before passing it to OS or after getting it from OS. OS doesn't know something as file "text" mode.

**Comment by jmalak** [comment]
Anyway I think you should used only "\n" and CRTL can switch between text and binary mode and ensure proper translation "\n" <-> "\r\n" if you need;

**Comment by rdos314** [comment]
Because of the aim of RDOS to be multi-API, and not constrained to a specific native API, part of what is normally in the run-time library has been moved to kernel. That's because when new processes are created they inherit file handles, and this is how input and output are redirected. So the file handles and their modes (including text or binary) are in a kernel driver. I suppose it would have been possible to retain text processing in the library, but that would have increased the number of syscalls.

**Comment by jmalak** [comment]
it could be enough for CRTL to have possibility to check some "mode" flag on handle by calling kernel API

**Comment by jmalak** [comment]
Anyway CRTL hold table of opened handles and attributes that if you fork or execute CRTL should be able duplicate this info or cache them. But I am not familiare with RDOS that you must decide what is best.
What eol is used by RDOS Console CRLF or LF only?

**Comment by rdos314** [comment]
There is a function to get the mode (it's used for reporting the mode through a C function). The problem is that it does a syscall. The Win32 implementation of text files also allocates additional buffers with new, which is also a time-consuming operation. 

About fork. If you fork a 32-bit flat application, and then exec() a DOS or 64-bit application, then the CRTLs are not compatible and the inherited handles will not be available. If they are kept in kernel then they work the same way regardless of how the CRTL decide to implement it.

Anyway, I decided to use text as default after all. It doesn't seem to be a problem since little of the code uses the standard libc, rather uses RDOS specific file-IO and console output, which only supports binary data.
