### ISSUE TITLE
bld/vi/c/grep.c:685]: (error) Resource leak: f

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#422]
Source code is

        if( RegExpError != ERR_NO_ERR ) {
            StaticFree( buff );
            return( RegExpError );
        }

Other error exits have a call to fclose(f), but not this one.

**Comment by jmalak** [comment]
Please, do pull request to simplify processing.
You can use github Web interface or git pull request.

**Comment by jmalak** [comment]
fixed
