### ISSUE TITLE
bld/sdk/imgedit/c/iesave.c: 2 * resource leak ?

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#425]
bld/sdk/imgedit/c/iesave.c:1212]: (error) Resource leak: fp
/bld/sdk/imgedit/c/iesave.c:1217]: (error) Resource leak: fp

fclose on standard return, but no fclose on these two error returns.

**Comment by jmalak** [comment]
fixed by commit 57c0fbccc60b559bee70b3c99cb7cedadcd31b26
