### ISSUE TITLE
10 * Mismatching allocation and deallocation

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#439]
[trunk/bld/browser/brg/cpp/mrline.cpp:272]: (error) Mismatching allocation and deallocation: standard_opcode_lengths
[trunk/bld/cpplib/iostream/cpp/iofoutfl.cpp:154]: (error) Mismatching allocation and deallocation: x
[trunk/bld/cvpack/cpp/cvpack.cpp:348]: (error) Mismatching allocation and deallocation: buffer2
[trunk/bld/ide/ide/cpp/vfilelst.cpp:280]: (error) Mismatching allocation and deallocation: buf
[trunk/bld/ide/ide/cpp/vfilelst.cpp:281]: (error) Mismatching allocation and deallocation: buf
[trunk/bld/src/cplbexam/contain/alloctor.cpp:75]: (error) Mismatching allocation and deallocation: BlockAlloc::curr_block
[trunk/bld/src/cplbexam/fstream/fstream/handbuf.cpp:20]: (error) Mismatching allocation and deallocation: bp
[trunk/bld/src/cplbexam/fstream/ifstream/handbuf.cpp:20]: (error) Mismatching allocation and deallocation: bp
[trunk/bld/src/cplbexam/fstream/ofstream/handbuf.cpp:21]: (error) Mismatching allocation and deallocation: bp
[trunk/bld/src/cplbexam/ios/width.cpp:16]: (error) Mismatching allocation and deallocation: bp

Where something is allocated with array new, it has to be deleted with array delete.

**Comment by jmalak** [comment]
It should be fixed by eec6f788cfc59965c6697e7026a5ebf7dc343bbe commit

**Comment by jmalak** [comment]
rest by 192021257c767c0675b74c3b98df625e7d9aec6f
