### ISSUE TITLE
Second batch of mismatching allocations 

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#440]
[trunk/bld/src/cplbexam/iostream/istream/gcount.cpp:12]: (error) Mismatching allocation and deallocation: bp
[trunk/bld/src/cplbexam/iostream/istream/getinbuf.cpp:12]: (error) Mismatching allocation and deallocation: bp
[trunk/bld/src/cplbexam/iostream/istream/getline.cpp:15]: (error) Mismatching allocation and deallocation: bp
[trunk/bld/src/cplbexam/iostream/istream/read.cpp:13]: (error) Mismatching allocation and deallocation: bp
[trunk/bld/src/cplbexam/iostream/istream/rshchbuf.cpp:16]: (error) Mismatching allocation and deallocation: bp
[trunk/bld/src/cplbexam/strstrea/ostrstre/charlen.cpp:19]: (error) Mismatching allocation and deallocation: pch
[trunk/bld/src/cplbexam/strstrea/ostrstre/pcount.cpp:30]: (error) Mismatching allocation and deallocation: pch
[trunk/bld/src/cplbexam/strstrea/strstre/charlen.cpp:18]: (error) Mismatching allocation and deallocation: pch
[trunk/bld/wclass/win/cpp/wserver.cpp:127]: (error) Mismatching allocation and deallocation: request
[trunk/docs/doc/cpplib/alloctor.cpp:75]: (error) Mismatching allocation and deallocation: BlockAlloc::curr_block

**Comment by jmalak** [comment]
fixed by 192021257c767c0675b74c3b98df625e7d9aec6f and c345641d3de27156c9f97ac250f27781c998d170 commits
