### ISSUE TITLE
Third batch of mismatch allocations 

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#441]
[trunk/bld/plustest/dcmat/svdcmp.cpp:284]: (error) Mismatching allocation and deallocation: rv1
[trunk/bld/plustest/dcmat/doubmat.cpp:1383]: (error) Mismatching allocation and deallocation: uu
[trunk/bld/plustest/dcmat/doubmat.cpp:1384]: (error) Mismatching allocation and deallocation: vv
[trunk/bld/plustest/dcmat/doubmat.cpp:1380]: (error) Mismatching allocation and deallocation: w
[trunk/bld/plustest/dcmat/doubmat.cpp:1381]: (error) Mismatching allocation and deallocation: u
[trunk/bld/plustest/dcmat/doubmat.cpp:1382]: (error) Mismatching allocation and deallocation: v
[trunk/bld/plustest/nih/string.cpp:200]: (error) Mismatching allocation and deallocation: srcbuf
[trunk/bld/plustest/positive/source/new04.cpp:76]: (error) Mismatching allocation and deallocation: p0
[trunk/bld/plustest/re2c/dfa.cpp:170]: (error) Mismatching allocation and deallocation: work
[trunk/bld/plustest/re2c/dfa.cpp:171]: (error) Mismatching allocation and deallocation: goTo

**Comment by jmalak** [comment]
it is test code, out of scope
