### ISSUE TITLE
Fourth batch of mismatching allocations

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#442]
[trunk/bld/plustest/re2c/dfa.cpp:172]: (error) Mismatching allocation and deallo
cation: span
[trunk/bld/plustest/re2c/code.cpp:167]: (error) Mismatching allocation and deall
ocation: sP
[trunk/bld/plustest/re2c/code.cpp:466]: (error) Mismatching allocation and deall
ocation: saves
[trunk/bld/plustest/re2c/code.cpp:467]: (error) Mismatching allocation and deall
ocation: rules
[trunk/bld/plustest/re2c/code.cpp:452]: (error) Mismatching allocation and deall
ocation: span
[trunk/bld/plustest/re2c/parser.cpp:656]: (error) Mismatching allocation and dea
llocation: ins
[trunk/bld/plustest/re2c05/code.cpp:320]: (error) Mismatching allocation and dea
llocation: sP
[trunk/bld/plustest/re2c05/memchk.cpp:274]: (error) Mismatching allocation and d
eallocation: p3
[trunk/bld/plustest/wclass/wvlist.cpp:58]: (error) Mismatching allocation and de
allocation: WVList::_set

**Comment by jmalak** [comment]
it is test code, out of scope
