### ISSUE TITLE
trunk/bld/cg/risc/c/rscver.c:167: dodgy expression ?

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#445]
bld/cg/risc/c/rscver.c:167]: (style) Boolean result is used in bitwise operation. Clarify expression with parentheses.

Source code is

           if( op->i.constant & 0x07 < actual ) {

Maybe better code

           if( (op->i.constant & 0x07) < actual ) {

**Comment by jmalak** [comment]
it is fixed by ef7e90d27d6b1d217e078ca96caf1bfe5bfa85e0 commit
