### ISSUE TITLE
plusplus/386/linuxx64/ytab.c:4302: statement in wrong place ?

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#461]
trunk/bld/plusplus/386/linuxx64/ytab.c:4302]: (style) Statements following return, break, continue, goto or throw will never be executed.

Source code is

           case LK_NAMESPACE:
                return( Y_SCOPED_NAMESPACE_NAME );
            DbgDefault( "unknown lexical category" );
            }
            return( Y_IMPOSSIBLE );

Maybe better code:

           case LK_NAMESPACE:
                return( Y_SCOPED_NAMESPACE_NAME );
           }
            DbgDefault( "unknown lexical category" );
            return( Y_IMPOSSIBLE );

**Comment by jmalak** [comment]
Sorry for my English.
Macro DbgDefault is defined as

```
#ifndef NDEBUG
   #define DbgDefault( msg )   default: CFatal( msg __location )
#else
    #define DbgDefault( msg )
#endif
```
