### ISSUE TITLE
bld/as/mps/c/mipsfmt.c:821: bad compare ?

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#463]
bld/as/mps/c/mipsfmt.c:821:22: warning: self-comparison always evaluates to true [-Wtautological-compare]

Source code is

        op1 = ins->operands[1];
        if( op0->reg == op0->reg ) {

maybe better code
        op1 = ins->operands[1];
        if( op0->reg == op1->reg ) {

**Comment by jmalak** [comment]
Thanks for bug report.
