### ISSUE TITLE
bld/plusplus/ppact/ppact.cpp:1923]: (style) Same expression on both sides of '||'.

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#470]
Source code is

    if( chr == '('
     || chr == ','
     || chr == ')'
     || chr == ','
      ) {

Suggest new code

    if( chr == '('
     || chr == ')'
     || chr == ','
      ) {

**Comment by jmalak** [comment]
Thanks for bug report,it is fixed in git repository now
