### ISSUE TITLE
Feature request: get int86, intr, intdos, etc. to load flag(s) before calling interrupt

### ISSUE THREAD

**Issue by tkchia** [open-watcom/open-watcom-v2#472]
Hello,

May I know if it will be possible, in the next version of Open Watcom, to arrange for routines such as `int86`, `intr`, `intdos`, etc. to load the carry flag (and possibly other flags) from their input `union REGPACK` or `union REGS` structures, just before invoking the actual interrupt?

This should make it easier to write programs to work around certain BIOS or DOS versions which do not properly update the carry flag in some cases.

Thank you!

**Comment by jmalak** [comment]
For backward compatibility clear Carry bit could be done before raising interrupt.
Otherwise new functions must be added to C run-time library

**Comment by jmalak** [comment]
It should include all interrupt related functions which use REGPACK or REGS unions on entry 

"flags" (REGPACK):
`intr`

"cflag" (REGS):
`int86, int86x, int386, int386x, intdos, intdosx`

If flags is used then all relevant CPU flags should be changed.
If cflag is used then only carry flag should be changed and all other bits should be reset.

**Comment by jmalak** [comment]
intrf was re-implemented + Documentation update by commits
7e59f751eb48dd4d642d601d7082c776e9483593
0368c07057b60341c9fdfd66f69d971ecf87e325
fa467258ca786a89c5853e8bd2d62a1eeedf1f23

There is main change in intrf against intr to use "flags" structure member for CPU flags setting.
