### ISSUE TITLE
Compiler cannot find include files in openssl project

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#476]
A file is referenced like this:
#include "internal/asn1_int.h"

The file exists at this path: crypto/include/internal/asn1_int.h
The include path is the following: ".;crypto/include;include;crypto/include/internal"

If the internal part is removed it works, and also if the full path "crypto/include/internal/asn1_int.h" is used.

There are other relative paths that seem to work. I think the problem is related to internal being present at two different locations in the project dir:
crypto/include/internal
include/internal

If the other internal is removed, the compiler no longer complains about not finding the include file (but instead complains about files in the other directory).

**Comment by jmalak** [comment]
Thanks for bug report.
Could you check if problem is related to last item on include path by adding include on the end of list.

**Comment by jmalak** [comment]
Please could you give me compiler command line.
What setup for INCLUDE environment variable.

**Comment by jmalak** [comment]
Now it should be fixed in git repository

**Comment by rdos314** [comment]
Seems to work.
