### ISSUE TITLE
bld/f77/wfc/386/linuxx64/../../c/browscli.c:304: suggest avoid use of tmpnam()

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#477]
bld/f77/wfc/386/linuxx64/../../c/browscli.c:304: warning: the use of `tmpnam' is dangerous, better use `mkstemp'

man tmpnam says

DESCRIPTION
       Note:  avoid  using  these  functions;  use  mkstemp(3)  or  tmpfile(3)
       instead.

**Comment by jmalak** [comment]
it is fixed now in git repository
