### ISSUE TITLE
Where would socket.h for RDOS be put?

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#478]
I'll work on implementing a unix-compatible socket interface. One possibility is to add the code to Open Watcom, and the other is to provide it as a library to the OS distribution. Since some tools in the project use sockets, the best is probably to put it here.

The problem I can see is with how the header files are implemented. RDOS relies on the DOS/Windows header files, and not the unix style. For DOS, wattcp is a bit external to the project, while Windows has it's own socket interface which is also external. However, for RDOS, there are APIs related to sockets that are not compatible with the usual socket interface, and so providing this interface would be a compatibility layer that would need to be exported in OW.

Thoughts?

**Comment by jmalak** [comment]
I think that RDOS stuff should be a little changed in OW
- add new header sub-directory rdos under hdr project (similary as qnx) there could be all RDOS specific header files as rdos.h etc which will be distributed with OW
- create new project rdos and there create tcpip sub-directory, there necessary distribution library will be created and included to standard OW distribution for RDOS

**Comment by jmalak** [comment]
I am not sure how header files for CRTL, WIN32, RDOS is ordered to build RDOS native application.
Could you specify?

**Comment by rdos314** [comment]
First, rdos.h is "work in progress", and so should not be exported from OW. There is a snap-shot in OW to allow for building clib that I synchronize from time to time. I think this should be kept as I don't want to build new OW versions when I add new functions.

Second, it would be best to have the socket interface as part of clib. That way it would not be necessary to add more libraries to the linker. Alternatively, I suppose more standard libs might be added to the linker, which would solve this too. 

As for how the header files are ordered, I don't know. There doesn't seem to be a special set of include files for RDOS, rather it seems they are shared with DOS and WIN32.

**Comment by rdos314** [comment]
I've looked at the hdr project, and I think it is the "segment DOS" and "segment LINUX" code in the *.mh files that generates different header files for Linux and DOS/WIN32. I think by adding RDOS to all DOS segments it should be possible to make a copy of the include files for RDOS. Then functions that are not supported should be removed from the RDOS headers, as well as some of the conditional __RDOS__ code in the generated headers themselves.

However, it doesn't seem like the qnx headers are generated, and just adding RDOS to some segments won't create the RDOS header subdir. There has to be something that controls which headers to generate. Any idea about this?

**Comment by jmalak** [comment]
OK, RDOS header files not need to be included.
May be that we could review CRTL network stuff, now it is fragmentated between Linux and POSIX.
integrate network functionality.
If you plan to implement POSIX network interface we could do it common for Linux/WIndows/RDOS/QNX and separate it into POSIX part of CRTL..

Anyway hdr project has configuration file hfile.mif where is defined what header files are created for appropriate target. That we can add rdos target. These subdirectories are created dynamicaly and configuration is in master.mif make file.

**Comment by rdos314** [comment]
Yes, I plan to implement the POSIX network interface. I also plan to implement other POSIX features, like pthreads. With separated include files that would be a lot easier to do.

**Comment by jmalak** [comment]
I can add rdos target to hdr project with no build files now and you can add what you need later.

**Comment by jmalak** [comment]
you can use pthread Linux implementation as start point for RDOS.
In the future it could be extended for Windows target too.

**Comment by rdos314** [comment]
OK. I'll look more at it tomorrow. Please do add rdos target to hdr project.

**Comment by jmalak** [comment]
OK. I will do.

**Comment by jmalak** [comment]
It is done. 
If you need to add RDOS header file then create bld/hdr/watcom/rdos directory and put there *.mh source.
Add the required header file to hfiles.mif configuration file (hrdos macro in inject command).
Appropriate header file will be created in bld/hdr/rdos directory.

**Comment by jmalak** [comment]
I don't think that full set of header files must be build.
I supposed you add only RDOS specific header files there.
But generaly full set of header files can be created, but it is duplicit if you use standard DOS/WINDOWS executable because you can simply setup include=h;h\rdos

**Comment by rdos314** [comment]
I think this is the best solution. Some tools will check the availability of different headers, and decide based on that if a function exists or not. There are many functions in DOS that are not relevant for RDOS, and these should not have headers and possible to reference. This is also how the Linux headers work. They are included with lh instead h. For RDOS, the headers would be in rh.

**Comment by rdos314** [comment]
For a start, I only excluded some obvious headers that are not relevant for RDOS. There is a lot more to do with this.

**Comment by jmalak** [comment]
General rule is shared as much as possible for simple maintenance.
You must decide what is suitable for RDOS native executables.
I have no problem with this solution,

**Comment by jmalak** [comment]
I disabled MBCS stuff in C/C++ compiler for RDOS, to be buildable.
I don't know if RDOS natively supports any MBCS encoding.
If yes then change it back and add appropriate header files to hdr project.

**Comment by jmalak** [comment]
Next problem is unistd.h header file. For non-UNIX platforms it is redirection to io.h header file.
I added io.h to RDOS header to fix OW build.

**Comment by jmalak** [comment]
I checked definition of _MAX_PATH for RDOS and it looks little strange.
Now it is defined as _MAX_PATH  144.
I don't know if it is intention or ommision.

**Comment by rdos314** [comment]
I think MBCS should be disabled for RDOS. I use UTF-8, but that's transparent to the operating system. I certainly don't want the wide character set support. 

Not sure about MAX_PATH. I don't think there is any limit, but 144 should be ok for the moment.

Adding io.h in unistd.h seems ok. 

I suppose that the new configuration now builds the tools with the new header files. If the new headers also are used for external code I'd like to check that my code & libraries still build, and make fixes if they don't. After that, I'll go more into detail of what exactly should be in the include files to match what actually is available.

I didn't have any time for this today, and won't have time during the weekend either, but will look more at it on Monday.

**Comment by jmalak** [comment]
It is clear.
I did only changes which was absolutely necessary to do OW building.
Next changes don't hurry, because now OW is building again.

**Comment by jmalak** [comment]
OW v2 works always with new headers, that all is build with new headers and new CRTL.

**Comment by rdos314** [comment]
This is more or less done now by exporting the socket-related headers, and implementing the functions, so I'll close this.
