### ISSUE TITLE
Problem with build

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#481]
I download the current source and then I use the compiler from 2018-09-10 as bootstrap. I modify setvars, run it and then build.

In  bld/wclass/binbuild I get the following errors:
c++ wfilenam.obj
e:\ow\rel\H\stdint.h(53): Error! E926: col(12) syntax error: 'std::intptr_t' has not been declared as a member
e:\ow\rel\H\stdint.h(53): Note! N393: col(12)  included from e:\ow\bld\wclass\cpp\wfilenam.cpp(38)
e:\ow\bld\wclass\cpp\wfilenam.cpp(51): Error! E121: col(2) syntax error
Error(E42): Last command makingn (wfilenam.obj) returned bad status
Error(E02):  Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 2

**Comment by jmalak** [comment]
it is bug in stdint.h (fixed 30.9.2018), that all older versions can be affected too.
use of intptr_t in latest header version did it visible.
You can fix it by using latest stdint.h with your bootstrap compiler version.

**Comment by rdos314** [comment]
That seems to work
