### ISSUE TITLE
Socket functions with include declarations that are not implemented for Linux

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#492]
I've found that several socket related functions are part of the Linux interface, but then are not implemented. These include the following:

inet_aton
inet_lnaof
inet_makeaddr
inet_network
inet_netof

In the socket interface, at least the following are missing:

recvmsg
sendmsg

I've implemented the inet_xx functions for RDOS, but did not export them for Linux. As for the socket functions, I don't plan to implement them, so I'd rather not have them exported for RDOS.

I think somebody should look into this for the Linux target, and either implement that functions or remove the declarations.

**Comment by ArmstrongJ** [comment]
I'd be happy to have a look at them this week.  I think you'll find a large number of declared but not implemented functions in the Linux library.  I ran into this quite a bit in the past.  They should be implemented, not removed.

**Comment by ArmstrongJ** [comment]
Commit 253822319a758f08ecfdfdd57021a2df71e2c8f1 implements _sendmsg_ and _recvmsg_ (along with necessary vector definitions and functions).   I'll have a look at the other missing network functions next, but I'm guessing much of the RDOS code can be used as-is.

**Comment by ArmstrongJ** [comment]
Haven't forgotten about this.  I'll see about getting these done this coming week, though a lot of the RDOS code looks like it can be used at first glance.

**Comment by ArmstrongJ** [comment]
The inet functions by @rdos314 compile fine with Linux, so I've added them to the Linux build in 6b636c44.  The only changes to the code was marking the files for "RDOS _and Linux_."  We probably do need some tests, but the entire POSIX portion of the runtime is not formally tested in the bld/clib/qa directory.  I might look at adding some.
