### ISSUE TITLE
Debug build fails for bld\clib\heap\library\msdos.086\mm at "cc growseg.obj"

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#496]
Possibly the same issue as #334.  Note that a read is attempted of a DWORD at 0xdfdfe003, which suggests that the DWORD pointer value begins with the last WORD of memory that has been freed.

Host: Windows 10, building with recent release of OWv2.

======= 07:45:00 t:\github.clones\iw\bld\clib\heap\library\msdos.086\mm =======
cc chksize.obj
cc _expand.obj
cc allocseg.obj
cc ambsptr.obj
cc amblksiz.obj
cc bcalloc.obj
cc bexpand.obj
cc bfree.obj
cc bfreeseg.obj
cc bheapchk.obj
cc bheapmin.obj
cc bheapseg.obj
cc bheapset.obj
cc bheapwal.obj
cc bmalloc.obj
cc bmsize.obj
cc brealloc.obj
cc calloc.obj
cc fcalloc.obj
cc fexpand.obj
cc ffree.obj
cc fheapchk.obj
cc fheapmin.obj
cc fheapset.obj
cc fheapwal.obj
cc fmalloc.obj
cc fmemneed.obj
cc fmsize.obj
cc frealloc.obj
cc freect.obj
cc freeseg.obj
cc grownear.obj
cc growseg.obj
The instruction at 0x004e1024 referenced memory at 0xdfdfe003.
The memory could not be read.
Exception fielded by 0x004b24c0
EAX=0xdfdfdfdf EBX=0xc000dc00 ECX=0x00000000 EDX=0x0077fd20
ESI=0x023cd270 EDI=0x0051df1c EBP=0x0019f520 ESP=0x0019f4d4
EIP=0x004e1024 EFL=0x00010283 CS =0x00000023 SS =0x0000002b
DS =0x0000002b ES =0x0000002b FS =0x00000053 GS =0x0000002b
Stack dump (SS:ESP)
0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
0x0019f520 0x0051df1c 0x023cd270 0x0077fea0 0x023e1080 0x0077ddd0
0xdfdfdfdf 0x00000000 0x0077fe60 0x004bfb04 0x023e24b0 0xfffffffc
0xc000dc00 0x0019f58c 0x0051df1c 0x023cd270 0x0077fd20 0x00000000
0xc000dc00 0x004e15c4 0x00000001 0x0077fd20 0x004d242b 0x0077fd20
0x023e1080 0x0077fd20 0xc000dc00 0x0051df1c 0x023cd270 0x0077fea0
0x00000001 0x00000001 0x004d2607 0x023e1080 0x00000001 0xfffffffc
0xc000dc00 0x0019f528 0x00470a53 0x00000000 0x0019f5b8 0x0051df1c
0x023cd270 0x004e1c6c 0x0019f5b4 0x023e1080 0x023cd270 0x023e2ba0
0x0077fd20 0x0077e910 0x0019f500 0x0019f5e8 0x0051df1c 0x023cd270
0x00000001 0x0077e910 0x004e1f99 0x00000000 0x023e1080 0x023e2ba0
0x00000001 0xfffffffc 0x0077e900 0x0019f61c 0x0051df1c 0x023cd270
Error(E14): Cannot execute (bwcc): No error
Error(E42): Last command making (growseg.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 2
Build failed

**Comment by ideafarm** [comment]
I intend to systematically debug all of the failures that occur when attempting to do a debug build of all projects.  Was planning to work on that today, but am dealing with hardware problems on the rackmount that I use for OW work.  Before attacking this bug, I need to get WDW or WD to work on the boot C compiler.  Both debuggers currently die silently while loading the compiler image.

This project of mine will likely take several months, with my primary goal being to become familiar with the code.

**Comment by jmalak** [comment]
Take into acount that "full debug" mode is not supported and will not be supported because it is very problematic. Generated code is very different from production (optimized) code that there can be another problems not existing in production code.
It is reason why -d1 option is used for production build, to be able identify location where problem happen and do next investigation.

**Comment by ideafarm** [comment]
That is helpful.  The more problematic a debug build of the full system is, the more I will learn about the code.  If -d2 really cannot be supported, I will learn why.  I'm looking forward to this.  I will minimize the burden on you of my "independent study", but don't hesitate to pass useful nuggets of information and suggestions along to me as I proceed.

I have four colocated rackmount computers.  The one that I allocated for OW work is down, likely with a RAID controller card failure.  I will work around this by setting OW build up on another of the rackmounts.  As always, many demands on my time, so...

**Comment by jmalak** [comment]
-d2 option is fully supported, but full debug OW build is not supported.
It is two different things

**Comment by ideafarm** [comment]
If you know, what prevents all projects, without exception, to be built with debug information.  I would expect full symbols (-d2) to possibly prevent building 16 bit executables due to segment overflow.  Is there some other obstacle to building at least all of the C and C++ code with -d2?  If there are a few projects that cannot be built with -d2, why not just change the makefiles so that those projects are built using -d1?

Any information or ideas about this (from anyone) will be helpful.  My OW build just completed, so can now get back to exploring this.

**Comment by jmalak** [comment]
It is simple.
- full debug version is imposible
- You can not implicate quality of release code from debug version
- all testing must be done on release version

What is purpose of debugging?
Why we should block -d2 option usage for some projects?
OW projects are not "Hello World" type project, they are complex, they use several sub-project. 
You need debug release code because there is a problem.
First step is debug pure release version (only line numbers and in assembly code) to identif what part of code cause a problem.
Debug version can not exhibit a problem.
I can create debug version that most of sub-projects are release version and only one is debug version. Behaviour of resulting program is relatively similar as release version.
Therefore full debug version is useless only selective debug version has sense.
Debugging is simple for simple program, but most of OW tools are complex, that simple debugging is impossible especialy 16-bit projects. 
You must decide what will be debug version, sometime it is only one module, it depend on problem.

**Comment by ideafarm** [comment]
Thanks, Mr. Malak.  I'll have more questions once I get into the code.

**Comment by ideafarm** [comment]
Test: full build (no docs) with OWDEBUGBUILD=1 on Windows 10 Pro, using a build that includes debug info for project WV.  Then run "WDW WDW".  Then specify "bwcc" for the image to debug.

Offending function: "static bool CheckLoadDebuglnfo( image_entry *image, file_handle fh, dip_priority start, dip_priority end )"

Offending line:  "*(image_entry **)DIPImageEx:tra( image->dip_handle )
= image;"

Bug:  DIPImageEx:tra can return null.  But the offending line dereferences without checking for null.

Effect:  WDW dies silently while loading the executable image to be debugged.  This bug prevents full build with debug on.

**Comment by jmalak** [comment]
I don't understand what problem is.
You are talking about possibility and next you talk about unspecified bug.
Missing check can not cause bug.
How it can prevend build, if problem can happen on run-time only?

**Comment by jmalak** [comment]
Anyway as soon as DIPLoadInfo succeded then DIPImageExtra can not return NULL.
Therefore test is useless.

**Comment by jmalak** [comment]
Please don't mix various problem into one issue, simply add new one.
Now is issue title irrelevant to last content.

**Comment by ideafarm** [comment]
Yes, I confused the two bugs.  Will repost as new bug and respond to your comments there.

**Comment by jmalak** [comment]
I tried to analyse why it happen and it looks like bug in debug version of code generator.

**Comment by rdos314** [comment]
Reproduced with compiler from 2018-11-27, happening to build from scratch with OWDEBUGBUILD=1. Not something you should do, but still should work.
