### ISSUE TITLE
wcc.exe is missing

### ISSUE THREAD

**Issue by Zero3K** [open-watcom/open-watcom-v2#498]
I'm trying to compile a small program using it. When running its build.bat, I get an error that states that it can't find wcc.exe. I looked in its binary folders and also cannot find it. I am using the latest version of it that is available on SourceForge.

**Comment by jmalak** [comment]
I don't know how you try to find wcc.exe.
it is in appropriate directory for host platform in ow-snapshot.7z archive file.
For which host platform it is missing?

**Comment by Zero3K** [comment]
I managed to find the proper installer. Now I am running into it complaining of not being able to allocate memory when its compiled as a 32-bit application. Its source can be found at https://pastebin.com/jgaBcWad.

**Comment by jmalak** [comment]
You must select proper installer by your host operating system and install OW for your target platform.
I don't know what OS you are using and for which OS you are compiling.
If you use incorrect version then program could be compiled for different OS and then don't work properly.

**Comment by Zero3K** [comment]
I am using the 32-bit compiler. I tried the resulting exe on both 32 and 64-bit OSes. It showed that error on both of them. The 16-bit version isn't filling all of the available free space in Windows Server 2003 (32-bit). It only filled half of the 1.09 GB that is free space.

**Comment by jmalak** [comment]
What error? What target OS?
For which compiler is build.bat?

**Comment by ArmstrongJ** [comment]
> I managed to find the proper installer. Now I am running into it complaining of not being able to allocate memory when its compiled as a 32-bit application. Its source can be found at https://pastebin.com/jgaBcWad.

Just glancing at your code, I can see you're attempting to allocate INT_MAX bytes of memory, aka 2^31 bytes (2GB).  Windows does not allow any single 32-bit process to allocate more than about 1.5GB in an ideal situation, so the allocation properly fails.  The Open Watcom runtime is working perfectly in this case.

**Comment by zoomosis** [comment]
Even if Windows allowed you to malloc(INT_MAX), your program would thrash the swapfile on PCs (or virtual machines) with less than 2 GB RAM, completely working against you.

It's unlikely you'll be able malloc() more than 64 MB in 32-bit DOS unless you use a DOS extender that supports XMS 3.0. (DOS/4GW doesn't.)

But you shouldn't be allocating any memory at all just to zero-fill a disk.

You're also erroneously checking for free disk space. On a multitasking system, free space can change drastically in the background.

Essentially all you need to do is just use an fwrite() loop then stop the loop when fwrite() fails.
