### ISSUE TITLE
WDW dies while loading BWCC because DIPImageEx:tra returns null.

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#500]
Test: full build (no docs) with OWDEBUGBUILD=1 on Windows 10 Pro, using a build that includes debug info for project WV.  Then run "WDW WDW".  Then specify "bwcc" for the image to debug.

Offending function: "static bool CheckLoadDebuglnfo( image_entry *image, file_handle fh, dip_priority start, dip_priority end )"

Offending line:  "*(image_entry **)DIPImageEx:tra( image->dip_handle )
= image;"

Bug:  DIPImageEx:tra can return null.  But the offending line dereferences without checking for null.

Effect:  WDW dies silently while loading the executable image to be debugged.

>>  @jmalak:  Anyway as soon as DIPLoadInfo succeded then DIPImageExtra can not return NULL.
Therefore test is useless.

This seems to illustrate your lack of understanding of the ART of coding.  One basic rule of the art is that if a function, as coded, can return a null pointer, then all callers should check for that occurrance.  That rule is part of "defensive coding", which should almost always be done.  (The small exception is for code fragments that execute so frequently that the cost of a conditional jump instruction is too high.)  It also illustrates the difficulty that I have obtaining your cooperation.  You say that the function cannot return NULL.  But as coded, the function clearly can return NULL, and I have seen it do so while running it in WDW, using the method described above.

Rather than respond to me disrespectfully, please give me your thoughts on where the defect is likely to be.  Does the FACT that I've seen the function return null mean that an error has already occurred, since it should never return null?  Or, does it mean that the calling code should check for NULL and handle that occurance gracefully?

I want you to cooperate with me respectfully by using my requests for information as an opportunity for you to display your presumably deep understanding and familiarity with the code.  That will make you look good.  It will enable me to draw that knowledge out of you so that I can study the code more efficiently.  And it will enable me to begin to be of value to you as a tester and bug fixer.

I am one of the most experienced C++ developers alive today.  The condescending, critical, and unresponsive character of your posts to me is frustrating because I need your full cooperation in order to contribute value to OW.

**Comment by jmalak** [comment]
Not real problem

**Comment by ideafarm** [comment]
Here is the technical reason why this is a bug worth fixing:  The code is clearly, indisputably wrong, in that the called function explicitly returns null conditionally, while the caller does not check for NULL before dereferencing.  When WDW WDW is run with executable BWCC, the inner WDW fails every time due to this null dereference.  This appears to be why the full build fails.  It also might be why production code fails, with the same symptoms, when I try to use WDW to debug production IPDOS (tm) code, which for this purpose is just another testbed.  There is something wrong with production WDW, and the instant reported bug might be the same bug or useful in analyzing the production bug.

Here is the interpersonal reason for helping me as requested:  I am here to contribute to OWV2.  My 1/2 million line C++ application (IPDOS (tm)) could be marketed to complement OWV2, with each driving user base growth in the other by making IPDOS (tm)  with OWV2 the best available C++ development and target environment.

Here is the political reason for helpng me:  I don't really need you to help me.  Without your help, it will just take me longer to get up to speed with this code.  But without your involvement, it is more likely that the code fixes that I produce will not be high quality, that you will reject them, that no spirit of cooperation and friendship develops between us, and that I will be forced to fork in order to get an OW, including the debugger, that runs flawlessly.

Finally, here is your personal stake in displaying a spirit of cooperation and friendliness:  No matter how exciting and wonderful your development of the OW code asset is, it has no future if you limit it to your "one man show" vision, especially if, as I suspect, you are coder at heart rather than a marketing or a general management visionary.
