### ISSUE TITLE
Fortran 2018 support

### ISSUE THREAD

**Issue by XVilka** [open-watcom/open-watcom-v2#502]
https://isotc.iso.org/livelink/livelink?func=ll&objId=19913983&objAction=Open

**Comment by ArmstrongJ** [comment]
Open Watcom doesn't even support Fortran 90 or free-format Fortran syntax.  We've missed a whole bunch of intermediate standards (95, 2003, 2008).  Fortran 2018 support probably isn't going to happen.

**Comment by XVilka** [comment]
Yes, I understand. Just wanted a clarification.
