### ISSUE TITLE
No way to disable generation of ret in function

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#506]
When generating very small DOS COM files, sometimes you want to avoid stdlib and will implement parts of the API yourself.  For example:

```
static void exit(unsigned char error);
#pragma aux exit parm [ al ] = \
  "mov ah, 0x4c" \
  "int 0x21"

void main() {
  exit(1);
}
```

compiled as `wcc -s main.c` produces` the following assembly:

```
0000				main_:
0000  B0 01				mov		al,0x01
0002  B4 4C				mov		ah,0x4c
0004  CD 21				int		0x21
0006  C3				ret
```

Is there a #pragma to tell the C compiler not to emit the ret statement for a certain function?  I have tried adding `void __declspec(naked) main() {`, but then it ignores the parameter (and also messes up other calls in the function):

```
0000				main_:
0000  B4 4C				mov		ah,0x4c
0002  CD 21				int		0x21
```

**Comment by jmalak** [comment]
It is possible. Add "aborts" to pragma aux.
#pragma aux exit aborts parm [ al ] = \
  "mov ah, 0x4c" \
  "int 0x21"

Compile to
```
Segment: _TEXT BYTE USE16 00000006 bytes
0000                            main_:
0000  B0 01                             mov             al,0x01
0002  B4 4C                             mov             ah,0x4c
0004  CD 21                             int             0x21

Routine Size: 6 bytes,    Routine Base: _TEXT + 0000

```

**Comment by negge** [comment]
Wow, that is very cool.  With watcom-1.9.0 the `aborts` needs to be on `main` but with watcom-2.0 it can be on `exit` and it will propagate.

I will close the issue.
