### ISSUE TITLE
Compiling with wcc does not allow 32-bit registers in pragma

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#507]
I am trying to use wcc to create some USE16 segments based on shared code base also used for 32-bit programming.  I have am getting the error:

`Error! E1185: Invalid register name 'edx' in #pragma`

when compiling with:

`wcc -3`

It seems that if I am allowing 386 instructions, it should be fine to pass parameters in 32-bit registers.

Obviously, this is generating 16-bit code for the USE16 segment so it will have the operand-size prefix (as should all of the code in the in-line assembly).  More importantly, if it tries to make a call from 16-bit code into an external 32-bit function, it will fail at run-time so I can understand the error.  However, if I am not calling the function with the 32-bit register in the pragma it should be fine.

My goal is to reuse data structures between the 16-bit and 32-bit code.  Is it possible to disable this error, or turn it into a warning?

**Comment by negge** [comment]
I did some grepping through the source, it looks like what I want is:

`#ifdef __386__`

**Comment by jmalak** [comment]
there is another possibility used by example for privileged 286 instruction. 
It enable also use of 32 bit instruction in 16-bit segment.
You can add in-line assembler directive on beginning of in-line code
#pragma aux GetMSW = \
        ".286p"       \
        "smsw ax"    \
        value [ax]
But it doesn't change bitnees of generated code segment

**Comment by jmalak** [comment]
Take into account that C/C++ in-line assembler is not replacement for standalone assmbler.
Passing parameter to in-line assembly code is control by code generator which is control by selected architecture not by any directive in in-line assembly code. Therefore for 16-bit segment only 16-bit register set can be used. Option -3 for 16-bit compilers only enable code generator to use some 32 instructions.
