### ISSUE TITLE
Very slow document creation

### ISSUE THREAD

**Issue by revelator** [open-watcom/open-watcom-v2#510]
I thought the fix you presented would allow for faster document creation, but im now at 3 days plus building cguide. At first i thought it might be my version of dosbox that was at fault (LFN support version) but even with the original its still slow as molasses. So i tried upping the priority of the dosbox executable but alas to no avail. Not really sure whats going on but i dont remember it being that slow in the past even though it was not exactly fast it atleast allowed me to complete a build in half a day not 3 days +.

**Comment by jmalak** [comment]
It is strange.
I will check it on my 64-bit Windows box with DOSBOX emulator how long take build of full documentation.

**Comment by jmalak** [comment]
On my box it take 2.5 hours to build complete documentation for all platforms (I am using DOSBOX for WGML utility).

**Comment by revelator** [comment]
still running here same file cguide Oo does not seem to hang and uses very little cpu so its rather weird.

**Comment by jmalak** [comment]
Try to use standard DOSBOX without any configuration changes.
OW configure it by command line parameters.

**Comment by jmalak** [comment]
Try to go to docs/ps subdirectory and run wmake hbook=trap
It should take about 1/2 minute, on this you can try to identify why DOSBOX is so slow.

**Comment by revelator** [comment]
i am using standard dosbox, no change unfortunatly.
I will try what you suggest and see what happens, but im away for some days on cristmas so ill post back after.

**Comment by jmalak** [comment]
OK
