### ISSUE TITLE
wdis incorrectly decoding aam instruction

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#511]
The aam instruction (ASCII Adjust AX After Multiply) actually allows you to create two unpacked digits of any base.  When disassembling an OMF file that uses aam in this way (e.g., to put the high nibble of AL into the low nibble) it is not detected correctly.

Base 10 example:

```
0018  D4 0A				aam
```

Base 16 example:

```
0018  D4				????
0019  10 C1				adc		cl,al
```

**Comment by jmalak** [comment]
instruction aam is defined for base 10.
What you are refering is undocumented functionality not guarantie by Intel and it doesn't have defined instruction id.

**Comment by negge** [comment]
I am afraid that is just not true.  Please see the description of AAM instruction on page 124 of this Intel instruction manual:

https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf

Specifically:

_The generalized version of this instruction allows adjustment of the contents of the AX to create two unpacked digits of any number base (see the “Operation” section below). Here, the imm8 byte is set to the selected number base (for example, 08H for octal, 0AH for decimal, or 0CH for base 12 numbers)._ 

You can generate an OMF file that uses this op code using the command `nasm test.asm -f obj -o test.o` with the listing below:

```
CPU 386
BITS 32

GLOBAL print_hex4
GLOBAL print_hex8

SEGMENT _TEXT USE32 CLASS=CODE

; Print a 4-bit hexadecimal number
;  AL = number
print_hex4:
  pusha
  mov ah, 2
  mov dl, al
  and dl, 0xf
  add dl, 0x30
  cmp dl, 0x39
  jle .L1
  add dl, 7
.L1:
  int 0x21
  popa
  ret

; Print an 8-bit hexadecimal number
;  AL = number
print_hex8:
  push eax
  aam 16
  call print_hex4
  pop eax
  call print_hex4
  ret
```

Using the `wdis` included with `open-watcom-2_0-c-linux-x86` I get:

```
$ wdis test.o 
Module: test.asm

Segment: _TEXT BYTE USE32 00000026 bytes
0000				print_hex4:
0000  60				pushad
0001  B4 02				mov		ah,0x02
0003  88 C2				mov		dl,al
0005  80 E2 0F				and		dl,0x0f
0008  80 C2 30				add		dl,0x30
000B  80 FA 39				cmp		dl,0x39
000E  7E 03				jle		L$1
0010  80 C2 07				add		dl,0x07
0013				L$1:
0013  CD 21				int		0x21
0015  61				popad
0016  C3				ret

Routine Size: 23 bytes,    Routine Base: _TEXT + 0000

0017				print_hex8:
0017  50				push		eax
0018  D4				????
0019  10 E8				adc		al,ch
001B  E1                                              .
001C				L$2:
001C  FF FF FF 58                                     DD	L$2
0020  E8 DB FF FF FF			call		0x00000000
0025  C3				ret

Routine Size: 15 bytes,    Routine Base: _TEXT + 0017

No disassembly errors
```

**Comment by jmalak** [comment]
Yes it is documnted for 64-bit processor, but not documnted for 8086 - 80386.
Appropriate assemblers don't supported this form of instruction.
It si not a problem decode it, but wdis will not generate source compatible with WASM etc.

**Comment by jmalak** [comment]
In Intel documentation is next note for AAM

The generalized version of this instruction allows adjustment of the contents of the AX to create two unpacked
digits of any number base (see the “Operation” section below). Here, the imm8 byte is set to the selected number
base (for example, 08H for octal, 0AH for decimal, or 0CH for base 12 numbers). The AAM mnemonic is interpreted
by all assemblers to mean adjust to ASCII (base 10) values. To adjust to values in another number base, the
instruction must be hand coded in machine code (D4 imm8).

**Comment by jmalak** [comment]
I extended WASM assembler to recognize AAM instruction in the form "AAM uint8" where operand is 0-255 - commit 1e4e285fe3f3151ebb94534545159c5e31439435
extend WDIS disassembler to decode AAM instruction if operand is not 10 in the form "AAM uint8" - commit a3b0f0c8584660a558b8a563d2fde27423dac58f
it is backward compatible with any existing wasm code
this form of AAM instruction is also working with C/C++ in-line assembler

**Comment by negge** [comment]
Great, thank you very much!

**Comment by jmalak** [comment]
You are welcome
