### ISSUE TITLE
bld/plustest/positive/source/dtor07.cpp:80]: (error) Dead pointer usage

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#516]
[trunk/bld/plustest/positive/source/dtor07.cpp:80]: (error) Dead pointer usage. Pointer 'a_a' is dead if it has been assigned '&e' at line 74.
[trunk/bld/plustest/positive/source/dtor07.cpp:81]: (error) Dead pointer usage. Pointer 'a_d' is dead if it has been assigned '&e' at line 75.
trunk/bld/plustest/positive/source/dtor07.cpp:82]: (error) Dead pointer usage. Pointer 'a_e' is dead if it has been assigned '&e' at line 73.

Source code is

    {
        E e;
        a_e = &e;
        a_a = (A*)&e;
        a_d = (D*)&e;
    }
    chk( c_a, d_a );
    chk( c_d, d_d );
    chk( c_e, d_e );
    chk( a_a, d_a );
    chk( a_d, d_d );
    chk( a_e, d_e );

**Comment by jmalak** [comment]
thanks for your info

**Comment by jmalak** [comment]
it is test case, it should stay as is
