### ISSUE TITLE
bld/browser/cpp/gbvlist.cpp:397]: (style) Exception should be caught by reference.

### ISSUE THREAD

**Issue by dcb314** [open-watcom/open-watcom-v2#517]
Source code is

  } catch( CauseOfDeath cause ) {

Maybe better code

  } catch( const CauseOfDeath & cause ) {

**Comment by jmalak** [comment]
Thanks for your info

**Comment by jmalak** [comment]
it hasn't sense to change.
CauseOfDeath is enum type similar as Errors.
