### ISSUE TITLE
[Questions] Removing unused parts in objects + extending conio + docs only in PDF?

### ISSUE THREAD

**Issue by spacerace** [open-watcom/open-watcom-v2#518]
Hi there,

I started with watcom on a linux host as a dos cross compiler a few weeks ago and I am really excited about it so far. 
There are just a few things I had to get used to, differences from other toolchains. Mostly the command line usage looks weird to gcc-aware-people, but with some documentation reading it works.
This brings me to my first question:

Q1: **Are your docs only available in the PDF files in your binary distribution?**
While these PDFs cover everything it looks, they are not really user friendly. 
There is a page offset of about 20 pages in the c library doc and there are no bookmarks/links embedded in the PDF. 
Example:
I want to go to function XXX which is on page 526. I type 526 in my PDF reader, but book page it jumps to is ~20 less. So I have to scroll down until I find the function I'm looking for.
This makes it a pain to hop between different functions, particularly if you look up more than one function.

It would be **really** great to have clickable links in book's index. 
How would one start to add links to existing PDFs like your documentation?

I found these two pages which have some old, but clickable online documentation:
http://www.ousob.com/ng/wclr/
http://www.ousob.com/ng/wcpp/index.php
https://users.pja.edu.pl/~jms/qnx/help/watcom/clibref/clibover.html
Even though the second page is for QNX only, it provides documentation for a large set of functions.

Do you know of more places with stuff like this?

Q2: **My code is bloatet by dead stuff - how to optimize unused code automatically away?**
When I write code and change a lot it happens often that I have a lot of functions in a file where I only use 1 or 2 functions of them. I copy these files from project to project.
For example basic windowing stuff in textmode. Brings a lot of functions like "draw_button_xxx..." and so on. My resulting binary with openwatcom is really big, because of the functions still present.
I verified this by commenting out the unused functions. 
This is kind of annoying, because when testing for space savings I can't just comment out the call to the code, I have to comment out the code itself. At least double work.
From gcc I am used to a behaviour which kicks out everything unused. Is it possible with watcom too? If so - I didn't find - sorry.

Q3: **conio is very limited**
Compared to other conio implementations conio from openwatcom looks very poor. Is it because of historical reasons? Because watcom never had anything else?
The most extensive and great conio I've seen is DJGPP's one.
If I would come up with patches that add some functionality to watcom's conio, is there a chance to get it into watcom? 
If not, I don't want to take that effort. In this case I'd rather stick to my "library files" like described in 2).

I already wrote two conio implementation for dev86/bcc - One of these two conio-implementations uses int21 and BIOS, one uses only BIOS.

These are still on my disk, because work on bcc is stalled. Some small patches of me made it into bcc, but I think their manpower does not go into bcc anymore.
linux8086/elks is moving to gcc-ia16, I don't know if my patches would ever made it to bcc. For long time now I wanted to do my own dos-hosted bcc fork with my conio, but I have concerns about usability and I didn't figure out yet how to compile bcc as a native 16bit DOS application, no extenders, ...

Thanks for reading and I hope for response :)
Nils

**Comment by jmalak** [comment]
Hi Nils,
I understand you, but Watcom home was OS/2, DOS, Windows in the past, next extended to Novell, QNX.
Linux was introduced as new platform by Open Watcom.
You can not expect that Open Watcom is gcc centric. 
It uses very different philosophy for cross-compilation etc.
But we have Compile and Link driver like gcc "owcc" which use same or similar syntax as gcc.

A1:
OW uses one documentation source and you can generate various documentation/on-line help format.
Travis build create only part of PDF documentation which is available in [Wiki](https://github.com/open-watcom/open-watcom-v2/wiki/Open-Watcom-Documentation) to save resources.
OW Installers include all types of documentation.
If you need different format you can build it or I can compile it for you on my build server.

Available formats are PS, PDF, html, Windows hlp, OS/2 inf, OW on-line text, Windows html Help

A2:
use linker directive "ELIMINATE" which do this work for you.

A3:
you are welcome to improve OW
It is not a problem to add anything to OW distribution, but you must follow some rules.
- backward compatibility with existing distribution, it meens existing functions must have same interface and must follow documented behaviour
- new function should be design for long term use with fixed prototype and must be documented in appropriate part of documentation
it should be implemented for all supported platforms (if possible)
- coding styles

**Comment by spacerace** [comment]
> ... owcc ....
Yeah, I tried this first, but this way I never get used to the "real" watcom compiler. I have a bunch of Makefiles now for my desired targets and walked all the way through the compiler switch documentation a few times. Getting better, but stil a big new world ;)

> ELIMINATE 
Thanks!! I have missed this.

> ... help  formats ...
Thanks again, I will look at the installer/self building and will see if there is something, 

> different targets
Ok, this would involve a lot of testing I assume. I think, I should set up a VM for each target with the corresponding OS (OS2, Win32, DOS, ...) and check if every works, right?
Which Versions should I choose?
Windows 2000, Windows XP, any later?
OS2 4.x or earlier?

> fixed prototype + keep existing
The idea is to look at other, well known and long existing, implementations for prototypes, pick functions and write them for watcom.
This would fit these requirements.

**Comment by jmalak** [comment]
I forgot answer your question about version of Windows.
OW C run-time library support any 32-bit Windows from version 3.1 it include NT 3.1, 3.5, 4.0 etc.
Because we use Windows native WIN32 API only the executable should work on any version of Windows.
Unfortunately you can run 32-bit executable on any 64-bit version too. It is hard to test on all version. By example I combine test on Windows XP and Windows 10.

**Comment by jmalak** [comment]
Now html type documentation is available on
https://github.com/open-watcom/open-watcom-v2/wiki/Open-Watcom-Documentation-(html)

**Comment by jmalak** [comment]
It was good idea from you to have something similar in wiki to quick access.
I only did simple job.

To conio:
- I don't know how many functions you plan to add to CRTL, primarily look what is available in OW
- do implementation with maximum granularity that use of -zm option and ELIMINATE option for application is not necessary
- if you will need some help or information then simply ask here, somebody who know help you or give you some reference or info
- OW has it's graphics library, it is located in bld/graphlib sub-project. there is lot of code related to VGA etc.
- good source is also UI sub-project bld/ui, it is text interface used by all OW text application with ui
- all sub-projects are multi-target that you can look how it is handled on various hosts OS-es

**Comment by jmalak** [comment]
sorry I forgot. 
You should be familiare with OW building system.
We have a few core utilities which traverse OW bld tree and run wmake in appropriate directories
It is not necssary to create new make files.
You will do mainly changes to CRTL, it is clib sub-project located in bld/clib
there is special make files objects.mif which handle what is build to which target.

**Comment by spacerace** [comment]
Hummm...
I took me quite a while to add a dummy-function to libc to figure out how to do it. To be honest - I should have written down my steps - I dont remember em all...
I think I was too enthusiastic when thinking about extending the libc. As you said, I have to get familiar to build system etc.
I close this now, because it is more an issue of my abilities rather than Watcom ;)

I hope I get all this knowledge quickly to go on with this plan. But for now it is stalled.

Thank you very much!

**Comment by jmalak** [comment]
If you have any problem then simply ask here and you get help, explanation etc.
