### ISSUE TITLE
AppCrash in vi.exe on windows

### ISSUE THREAD

**Issue by Gavin-Holt** [open-watcom/open-watcom-v2#519]
Hi

I have been exploring the console text GUI version of vi.exe from your precompiled distribution for windows. If I call the read command from the menu, or as a colon command, I get an AppCrash. This happens on various windows machines and from one I got an AppCrash message:

  Problem signature:
    Problem Event Name:	APPCRASH
    Application Name:	vi64.exe
    Application Version:	2.0.23034.12075
    Application Timestamp:	59fa2f2b
    Fault Module Name:	vi64.exe
    Fault Module Version:	2.0.23034.12075
    Fault Module Timestamp:	59fa2f2b
    Exception Code:	c0000005
    Exception Offset:	00000000000107f0
    OS Version:	6.1.7601.2.1.0.768.3
    Locale ID:	2057
    Additional Information 1:	bd91
    Additional Information 2:	bd913df78ed7d75cbc156e98ec712459
    Additional Information 3:	49ce
    Additional Information 4:	49ce8197030ca2333d630f4d0cc7d811

I have tried different settings for my windows console and cannot fix the problem. This problem is also present in every binary console version of Watcom vi.exe (32 and 64) I have downloaded. 

It occurred to me that "in the great tradition of unix" vi may be looking for cat to read in a stream of characters? If this is the problem which cat for windows should I get?

Another explanation may be that M$ have changed the windows console environment and once good code is now failing?

I find this console based version with the customizable text GUI very attractive, I don't want to use the windows GUI version, nor do I want the weight of vim.

Many thanks in advance

Gavin

**Comment by jmalak** [comment]
Thanks for bug report.
We will fix it ASAP

**Comment by jmalak** [comment]
it should be fixed now by commit c65b93a46da939c2948c495ddb246ccdfa42a79e
