### ISSUE TITLE
open-watcom-2_0-c-linux-x86 debugger doesn't work properly in Manjaro Linux

### ISSUE THREAD

**Issue by abm-1980** [open-watcom/open-watcom-v2#522]
I'm unable to operate properly the debugger as I cannot activate any of its
menus to select an option and not even the mouse works on this. For example, if
I try to pull down the file menu using the ALT and F key combination or by a
mouse, the menu doesn't come out. The same problem is also present with the
rest of the menus and pop-up dialogs. For the pop-up dialogs, only the TAB key
works in selecting OK or CANCEL or any other buttons on it. I already executed
the command "export TERM=xterm" prior to running the debugger but it doesn't
help.

However, some of the shortcut keys like F10 to trace the program is working.

For your information, Manjaro is based on Arch Linux. The debugger file is wd
in Linux environment.

For Debian-based distros, I'm not having the same kind of problems mentioned
above as the debugger works perfectly in Debian-based distros. However, I still need
to execute the command "export TERM=xterm" before running the debugger.

**Comment by abm-1980** [comment]
I also cannot scroll the debugger window using a mouse. Only the arrow keys work on this. For Debian-based distros, the mouse works perfectly. It is more convenient to use mouse for navigating on source files currently loaded on the debugger rather than scrolling through keyboard.

**Comment by jmalak** [comment]
OW has minimal support for terminals and there are some problems with it.
Nobody is involved to improve support for terminals.
You export TERM=xterm but the type of your terminal can be different.
Generaly OW suport ANSI terminal and xterm. Also unicode support is not tested and sometime is not working. There is some hack working for Latin-1 base character where Unicode character is zero extension of single byte etc.

**Comment by abm-1980** [comment]
On my Manjaro machine, I have also tried to run the debugger directly inside the xterm but still, the same problem persists. I'm running the 64-bit Manjaro. Could it be that there were some modifications made in the xterm code that keeps the OW debugger from working properly?

Also, as you have mentioned that **"Nobody is involved to improve support for terminals"**, does it follow that the debugger issue I'm encountering won't be fixed?

Is there any other symbolic debugger I can use in place of the OW debugger? I have tried the gdb but it cannot read the debugging information in OW executables.

**Comment by jmalak** [comment]
OW is Open Source project with a few contributors, which improve it if they want and have a time.
The Manjaro distribution is not current Linux installation that I think nobody will have interest to fix it.
Anyway OW uses Dwarf V2 for debug info with some extensions for 16-bit segmented architecture.

**Comment by jmalak** [comment]
Anyway you can try latest version of OW debugger from daily build which contains latest fixes
[Daily build](https://github.com/open-watcom/travis-ci-ow-builds)

**Comment by abm-1980** [comment]
I have tried the latest version but I got the following errors:

Debugging Information Processor 'dwarf' load failed: Invalid version of DIP file

**Comment by jmalak** [comment]
copy full "binl" subdirectory to some directory and try to run wd executable from this directory.
There are more files used by debugger.

**Comment by abm-1980** [comment]
I see. Thanks again. I'll give it a try.

**Comment by abm-1980** [comment]
I have tried it just now and I still encountered the same problem.

**Comment by jmalak** [comment]
I will check why wd report
"Debugging Information Processor 'dwarf' load failed: Invalid version of DIP file"

**Comment by jmalak** [comment]
I tested it on Ubuntu without problem.
It looks like compatibility issue with Manjaro Linux.

**Comment by jmalak** [comment]
Please check it without any OW setup.
simply go into "binl" copy directory and run ./wd

**Comment by abm-1980** [comment]
> I tested it on Ubuntu without problem.
> It looks like compatibility issue with Manjaro Linux.

As expected, it will work on Ubuntu which is also a Debian-based distro.

**Comment by abm-1980** [comment]
> Please check it without any OW setup.
> simply go into "binl" copy directory and run ./wd

I tried just now and still, I'm encountering the same problems.

**Comment by jmalak** [comment]
other possibility is to try to use remote debugging.
start tcpserv on Manjaro and debug it from Windows or other Linux distribution

**Comment by jmalak** [comment]
I installed Manjaro Linux on VM and I try debug it by GDB.
It looks like some bugs in OW ncurses that I will fix it.

**Comment by jmalak** [comment]
The problem is that Manjaro Linux uses ncurses 6.1 which use extended binary format of terminfo database.
I must implement terminfo reader for new binary format.

**Comment by abm-1980** [comment]
Thank you so much for your effort. I appreciate it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jmalak** [comment]
Now terminfo is read correctly, xterm-256color is recognized and read properly.
Still problem with mouse support.

**Comment by jmalak** [comment]
I fixed ui mouse support that UI application like vi, wprof are working.
The problem with debugger is now related to the problem to start debugger xterm session.
I will do more investigation.

**Comment by jmalak** [comment]
You need to install xterm to debugger works properly.

**Comment by abm-1980** [comment]
Thanks for all your effort. The xterm is pre-installed in Manjaro. Upon successful installation of Manjaro to hard disk, almost everything needed for development are already installed including the xterm.

**Comment by abm-1980** [comment]
Other distros like Ubuntu doesn't have xterm installed and you have to install it either via Synaptic Package Manager or by executing apt-get on the terminal window.

**Comment by jmalak** [comment]
I installed XFCE environment and it has not installed xterm (X11).
The OW debugger starts xterm (X11) in forked process and wait for xterm process.
It was waiting for while because xterm can not be started.
Anyway I will try to handle this situation when xterm is not available on host for local debugging.
Simply some message which report that xterm (X11) is not available instead of infinity blocking wait.

**Comment by jmalak** [comment]
the latest build should be OK to work on Manjaro.

**Comment by abm-1980** [comment]
I see. For my computer, I have installed the latest Manjaro KDE Plasma live cd and it has xterm installed. I also noticed that the OW debugger starts inside the xterm even if I execute it within the Konsole terminal.

**Comment by jmalak** [comment]
It is hard to get info about local X terminal emulator executable.
If we know executable name and options then we can run it instead of default xterm (X11).

**Comment by jmalak** [comment]
I add check for xterm executable and message if not found on the PATH.

**Comment by abm-1980** [comment]
Thank you once again. I have tried the latest build on my Manjaro machine and it worked. I can now use the mouse on the OW debugger without any problems.

I'll look forward to see this bug fix include in the next official release of Open Watcom.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
