### ISSUE TITLE
Linker misaligns section in 16-bit RAW

### ISSUE THREAD

**Issue by chibicitiberiu** [open-watcom/open-watcom-v2#523]
Hello,
I am trying to create a raw binary which is basically the 2nd stage of a bootloader. I am using the following linker script:

```
FORMAT RAW BIN 
OPTION QUIET,
       NODEFAULTLIBS,
       START=entry, 
       VERBOSE,
       OFFSET=0,
       STACK=0x200
ORDER
    CLNAME CODE
        SEGMENT _ENTRY
        SEGMENT _TEXT
    CLNAME DATA
```

The C files are compiled with `wcc -3 -d3 -s -wx -ms -zl -zq`, and the assembly code with NASM. I am using the 2.0 release from the sourceforge page, and compiling from latest 64-bit Ubuntu.

The problem I'm having is this:

```
Segment                Class          Group          Address         Size
=======                =====          =====          =======         ====

_ENTRY                 CODE           AUTO           00000000        00000013
_TEXT                  CODE           AUTO           00000013        00000b8c
CONST                  DATA           DGROUP         00000ba0        00000134
CONST2                 DATA           DGROUP         00000cd4        00000004
_DATA                  DATA           DGROUP         00000cd8        00000000
_BSS                   BSS            DGROUP         00000cd8        00000005
```

The address where the CONST section begins is wrong, 0x13 + 0xb8c = 0xb9f, not 0xba0. In the emitted binary, the beginning address of the CONST section is indeed 0xb9f, but all the references to the constants are shifted by 1 byte. 

For example, when calling `puts("Hello world")`, I get the output `ello world`. Adding 1 byte to the '_ENTRY' section (which is coded in assembly), seems to temporarily 'fix' the problem. Also, making small changes in code does that, such as adding a variable, or making a variable from int8 to int16.

**Comment by jmalak** [comment]
Thanks for problem report.
Could you check with latest build version linker from [Latest build](https://github.com/open-watcom/travis-ci-ow-builds).
could you add here all *.object file with linker command to be able analyse where problem is.

**Comment by jmalak** [comment]
I think that 0x0ba0 could be OK because it is start of DGROUP and if some segments in dgroup is of type WORD or higher then dgroup is align to appropriate value.
Anyway what is strange is wrong offset as you reported.

**Comment by chibicitiberiu** [comment]
I tested using latest build, and the problem still appears. 

I added everything, including the wlink command args in the zip:
[stage2.zip](https://github.com/open-watcom/open-watcom-v2/files/2873015/stage2.zip)

If you open the output binary (stage2.bin) in a hex editor, you can actually see that the CONST section as mentioned in the "map" file begins with a 1 byte offset (the first constant should be the "012345679ABCDEF" string, but according to the map file, the CONST section begins at the '1' character)

**Comment by jmalak** [comment]
Thanks. I will analyse a problem.

**Comment by jmalak** [comment]
DGROUP is WORD aligned that linker map is OK
It is mised emiting of padding byte after CODE class. 
I will fix it.

**Comment by jmalak** [comment]
it is fixed by commit dcd360abbd84da6124d78e0ed8f2e3762b0b8894
try new version after building, it can take about 1 hour.

**Comment by jmalak** [comment]
I found out second problem in RAW HEX format, wrong address calculation if padding is necessary.
I will fix it too.

**Comment by chibicitiberiu** [comment]
I tested, and I can confirm it is fixed :+1: 
Thank you very much for the help.

**Comment by jmalak** [comment]
You are welcome

**Comment by Athaphian** [comment]
I thought, I had found the exact same bug in one of the latest versions of watcom (lastrev.txt: Change 38993 on 2025/12/05 by MichalN@MICHALN_RYZEN).

So I checked out the revision this bug was fixed in, and my problem went away. My code compiles cleanly, and works.
However, the map files produced by both versions are exactly the same, so it must be a different bug altogether. AI was able to tell me that the linker has two separate pipelines? one for generating the map file and one for generating the output stream (sounds plausible). If that is the case, the bug might be in the output stream.

The symptoms are exactly the same as the original poster of this bug describes. I could share my code if that is useful. Perhaps the stage2.zip from [chibicitiberiu](https://github.com/chibicitiberiu) shows the same problem on the new version of watcom.

**Comment by jmalak** [comment]
I am sorry, what you are reporting?
Do you have any trouble with Open Watcom 2.0 fork ?
We don't have lastrev.txt and what you referencing is not our.

**Comment by Athaphian** [comment]
Oh hmm. I had downloaded the open watcom from http://openwatcom.org/ is that not the official website? I guess not :o. I just downloaded the latest release from this github repo and that seems to work as well. Thanks for your reply and sorry to have wasted your time!

Edit: I have read up a bit on the difference between the two. So this is actually a port of the official one with many improvements. Thanks for your effort!

**Comment by jmalak** [comment]
No problem.
Now it is clear, we are not official Open Watcom, but we hold compatibility with official Open Watcom 1.9 and improve C99 standard compatibility and other enhancements, more POSIX compatibility.
You need differ between official version which is very old and our version with many enhancement and bug fixes.
Also we build Open Watcom for 64-bit hosts ( Linux, Windows and OSX and x64 and ARM64 CPU).
