### ISSUE TITLE
Running from Vim (CWSDPMI conflict?)

### ISSUE THREAD

**Issue by osen** [open-watcom/open-watcom-v2#529]
When attempting to utilise the tools (i.e wcl) from within Vim, it exits with errors such as "Memory Allocation Failed".

I suspect that the DJGPP DMPI manager (CWSDPMI) is colliding with the OpenWatcom one(DOS 4g/w)?

if I exit out of Vim and run the same command it works no problem. However this is not really ideal because I lose my Vim session, etc.

Is this something that can be fixed? Are there any workarounds?

**Comment by jmalak** [comment]
It looks like problem of Vim with CWSDPMI that is not able to properly run other extender or serve appropriate services. If I remember properly CWSDPMI has limited DPMI services and is only working with DJGPP. OW doesn't support CWSDPMI extender.

Do you tried some other application with different DOS Extender/DPMI to work with Vim?

**Comment by osen** [comment]
Ah missed this (your closing it just flagged it up in my email).
I have not managed to find another compatible DPMI to work with Vim which is a bit of a shame.
For now I have been able to use good ol' DESQview with Watcom C in one session and Vim in the other. This way they do not seem to conflict.

I will keep this updated in case I find a more elegant solution.

**Comment by osen** [comment]
I have found a working solution. Basically PMODE/DJ is a drop in replacement for CWSDPMI.

http://www.mirrorservice.org/sites/ftp.delorie.com/pub/djgpp/current/v2misc/pmode13b.zip

Basically rename PMODETSR.EXE from the above zip to CWSDPMI.EXE and use as normal.
Alternatively you can do a binary merge of Vim (after converting to COFF) and the PMODESTUB.EXE from the same zip.

This then works fine with the current OpenWatcom :)
