### ISSUE TITLE
Compiling/Linking using wcl386 and DOS/4GW - "Cannot load DOS/4G(W)"

### ISSUE THREAD

**Issue by dajoho** [open-watcom/open-watcom-v2#531]
Hello,

I'm using open-watcom-v2 on archlinux. I am attempting to compile a 32-bit DOS/4GW binary and have tried both the git version and the latest travis release.

I'm not sure if I'm just being stupid and don't understand something, but I am trying to compile a simple hello world cpp file using wcl386 and have run into problems. 

My compile/linking string is `wcl386 test.cpp -bt=dos -l=dos4g`.

My problem is: compiling and linking seem to work correctly and wcl386 produces a `test.exe` correctly, but when I try to run it in DOSbox, I get the error `Cannot load DOS/4G(W)`. It seems that my compiler/linker is somehow not finding the DOS/4G stub loader and thus my binary _requires_ an external DOS4GW.EXE. As far as I can tell, OpenWatcom is supposed to automagically link `wstub` and my exes should not require any external DPMI loaders. 

If I compile WITHIN DOSbox (albeit with OpenWatcom 1.9), I get a correct DOS/4GW binary with an included stub.

Am I doing something wrong? Is linux even capable of linking the DOS/4G stub?

Thanks and regards

Dave

**Comment by jmalak** [comment]
I am not sure if I understand your problem correctly.
It looks like you mixed two problem, linking DOS4GW stub into executable and run-time problem with loading DOS4GW.
first problem you can check by adding `-fm` option to wcl386 command and look into created map file if stub is found and which one.
second problem can be that you don't have DOS4GW on the PATH and therefore it is not loaded on run-time, DOS4GW executable is located in OW `binw` subdirectory.
Please check it.

**Comment by jmalak** [comment]
Solution could be to add DOS4GW.EXE on DOSBOX disk to directory which is included in PATH and you don't need copy it anymore.

**Comment by dajoho** [comment]
Hi @jmalak,

Thanks for the reply. It turns out that I was just being a bit thick. I was under the assumption that wstub _contained_ a small version of DOS/4GW. This is not the case and the stub only worked on my 1.9 installation as DOS4/GW was in the %PATH% of my DOSbox environment. It was not, however, in the environment where I tested the exe created using my Linux installation.

Thanks again. I'll close the issue. 😄
