### ISSUE TITLE
__cdecl or -ecc can't be used for main() ?

### ISSUE THREAD

**Issue by jeroenjacobs1205** [open-watcom/open-watcom-v2#532]
Hi,

It seems that neither the -ecc commandline parameter for wcc, or the __decl keyword work for the main() function.

Is there a way to force wcc to generate __cdecl compatible main() function? I'm using custom startup code for a DOS project, that requires C-style calling convention for main().

**Comment by jeroenjacobs1205** [comment]
To illustrate the fact, I compiled a simple program and specified the -ecc parameter. After disassembly, you can see all  functions follow C-style calling functions (__cdecl), except for the main():
```
.387
                PUBLIC  _buildNodeDir
                PUBLIC  _strcicmp
                PUBLIC  _createDoor32
                PUBLIC  _removeDoor32
                PUBLIC  main_
```

**Comment by jmalak** [comment]
You can not change main calling convention it is fixed because it is C entry point and must correspond with calling from run-time startup code.
There is only one possibility for 32-bit compiler to use stack-based calling convention with -3s option.
It uses stack-based calling convention for main. For 16-bit code it is always register-based calling convention.

**Comment by jmalak** [comment]
you can add thunk code for main which convert call between __cdecl and __watcall and link it with your application. What is reason to have main __cdecl?

**Comment by jmalak** [comment]
Anyway I checked to change main calling convention by #pragma aux and it works.
C sample code
```
#pragma aux (__cdecl) main

int test_watcom_func( int argc, char *argv[] );

int main( int argc, char *argv[] )
{
    return( test_watcom_func( argc, argv ) );
}
```
Disassembled code
```
                PUBLIC  _main
                EXTRN   test_watcom_func_:BYTE
                EXTRN   __argc:BYTE
                EXTRN   _big_code_:BYTE
                EXTRN   _cstart_:BYTE
DGROUP          GROUP   CONST,CONST2,_DATA
t1_TEXT         SEGMENT BYTE PUBLIC USE16 'CODE'
                ASSUME CS:t1_TEXT, DS:DGROUP, SS:DGROUP
_main:
        push            bp
        mov             bp,sp
        mov             ax,word ptr 6[bp]
        mov             bx,word ptr 8[bp]
        mov             cx,word ptr 0aH[bp]
        call            far ptr test_watcom_func_
        pop             bp
        retf
t1_TEXT         ENDS
```
The solution is include line 
#pragma aux (__cdecl) main
in C code with main

**Comment by jeroenjacobs1205** [comment]
Thanks! That seems to work perfectly :-)
