### ISSUE TITLE
Implicit declaration of function `strupr'

### ISSUE THREAD

**Issue by JL2210** [open-watcom/open-watcom-v2#534]
Partial build log:

```
../c/cmd16m.c: In function 'ProcExpName':
../c/cmd16m.c:267:5: warning: implicit declaration of function 'strupr'; did you mean 'strstr'? [-Wimplicit-function-declaration]
     strupr( FmtData.u.d16m.exp_name );
     ^~~~~~
     strstr
```

This is invalid in C11.

I suggest using the ANSI C `toupper()` function instead.

**Comment by jmalak** [comment]
Thanks for bug report. It is part of clibext library (non-ISO C functions).
It is fixed by commit b40dffca651dbccb653c46a8e4f7307ab0aaa601
