### ISSUE TITLE
Feature request: C/C++ block declaration to surround code with PUSHF/CLI .... POPF for code that needs to disable interrupts temporarily

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#536]
I have an implementation in DOSLIB that might be a good reference, but it would help to have it built into the compiler since it affects the stack pointer.

https://github.com/joncampbell123/doslib/blob/master/hw/cpu/cpu.h#L188

In practical use:

https://github.com/joncampbell123/doslib/blob/master/hw/8254/8254.h#L160

The goal is to enable C/C++ blocks that are the equivalent of:

    PUSHF
    CLI
    ; DO SOMETHING WITH INTERRUPTS DISABLED
    POPF

It is for code that cannot assume interrupts are enabled, but needs to temporarily disable them.

**Comment by joncampbell123** [comment]
If not built into the compiler, then at least some sort of intrinsic the compiler can provide that would *aid* this feature would be perfectly OK.

**Comment by joncampbell123** [comment]
I would be perfectly OK with restrictions on the feature, such as forbidding "goto", setjmp, or C++ exception throwing from within such a block.

**Comment by jmalak** [comment]
I think the problem is that you don't inform code generator about stack change.
If you do it then code generator should use EBP/BP register to access local variables on the stack.
Try to define appropriate pragmas with modify word for stack register
#pragama aux ....=.... parm [..] modify [esp/sp]

**Comment by jmalak** [comment]
Be carefull OW code generator doesn't preserve CPU flags over generated code.

**Comment by joncampbell123** [comment]
That seems to have worked, thanks!
