### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by stevecheckoway** [open-watcom/open-watcom-v2#542]
Running `./build.sh` on macOS fails after a while with the error

```
========= 12:09:58 /Users/steve/research/open-watcom-v2/bld/vi/osxx64 =========
cc spawn.obj
/Users/steve/research/open-watcom-v2/bld/vi/unix/spawn.c:35:10: fatal error: 'uiextrn.h' file not found
#include "uiextrn.h"
         ^~~~~~~~~~~
1 error generated.
Error(E42): Last command making (spawn.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed
```

Presumably the header include paths aren't set up appropriately, but I'm unfamiliar with the build system so I'm not sure where to look.

System:

```
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

**Comment by jmalak** [comment]
Thanks for your bug report.
it is fixed in git repository now.
Anyway, it is strange because OSX build on Travis doesn't report this problem, I must review Travis OSX build environment.

**Comment by stevecheckoway** [comment]
Thanks. The build passes that spot now.
