### ISSUE TITLE
Reformat all files within one style

### ISSUE THREAD

**Issue by XVilka** [open-watcom/open-watcom-v2#548]
Using clang-format. See the corresponding documentation:
- https://clang.llvm.org/docs/ClangFormat.html
- https://clang.llvm.org/docs/ClangFormatStyleOptions.html

See the examples from the various projects:
- Linux Kernel https://www.kernel.org/doc/html/latest/process/clang-format.html
- Mozilla projects https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style/Formatting_C++_Code_With_clang-format

**Comment by jmalak** [comment]
In OW Wiki is [recommended formatting](https://github.com/open-watcom/open-watcom-v2/wiki/Source-Code-Style-Guidelines) for Open Watcom project.
This should be used for new codding and for reformatting of existing code mainly for very old pieces of OW codeline.
