### ISSUE TITLE
Win64 OpenWatcom installer crashes on completion

### ISSUE THREAD

**Issue by KScottDB** [open-watcom/open-watcom-v2#553]
when the installer completes, it crashes for me on Windows 7 Ultimate x64.
debugging the program in VS gives me the following information:

![Exception](http://uploads.kscott.cf/sharex/ij8rrhRM5R.png)

![Call Stack](http://uploads.kscott.cf/sharex/devenv_LuASXXFwyj.png)

i don't have the proper .pdbs on my system to give any more information on it.

**Comment by jmalak** [comment]
I will review setup for build 64-bit installer by MS Visual Studion.
Probably it is default to Windows 8 or Windows 10 that problem on Windows 7 can occure.

**Comment by jmalak** [comment]
I setup Windows minimal version for 64-bit OW tools to Windows 7 
by 085460aa0a12a023807f1679f8523538745c25a2 commit and fix 64-bit build break 
by 1e1fc514919daf607b565902d03256439831732a commit.
Please try latest 64-bit installer after rebuilding.

**Comment by jmalak** [comment]
it is fixed now by following commits
baa8651606fdb9818a6439df84d94b12df7f71b0
56a7e1bc73e7aef064c21269de6af361a6b455f8

**Comment by jmalak** [comment]
Checked on Win7 borrowed box and it works now.
