### ISSUE TITLE
wlink does not detect stack segment if segments comming from multiple files, different alignment

### ISSUE THREAD

**Issue by LowLevelMahn** [open-watcom/open-watcom-v2#555]
i try to split a single asm file, medium model with multiple segments, dos 16bit into serveral segment files and create an binary identical executable (its a tiny reverse engineering prototype for testing strategies for a much larger project) - **binary identical** is a must and single.asm needs to left untouched (because that file is normaly comming from IDA Pro)

using latest release versions of:
UASM v2.49, Jun 21 2019 (also tested with current MASM: Microsoft (R) Macro Assembler Version 14.16.27034.0)
Open Watcom Linker Version 2.0 beta Sep 13 2019 01:44:55 (64-bit)
for compare tests:
link.exe: Microsoft (R) Segmented Executable Linker  Version 5.60.339 Dec  5 1994 (latest 16bit able version)
optlink.exe: OPTLINK (R) for Win32  Release 8.00.17 (from the dmd package: dmd.2.088.0.windows)

**single.asm**
```
.model medium
.386

seg000 segment para public use16 
text db 'Hello World!',0ah,0dh,'$'
seg000 ends

seg001 segment para public use16 

start proc
  mov ax,seg seg000
  mov ds,ax
  push ax
  pop ax
  call print
  mov ax,4c00h
  int 21h
start endp

seg001 ends

seg002 segment para public use16

print proc far
  mov dx,offset text
  mov ah,09h
  int 21h
  retf
print endp

seg002 ends

seg003 segment para use16 stack
  db 256 dup (?)
seg003 ends

end start
```

**build with**
```
uasm64.exe single.asm
wlink.exe name single.exe format dos file single.obj
```

and the splitted version - which should produce the very same exe as the single.asm

**segment.inc**

```
seg000 segment para public use16
seg000 ends

seg001 segment para public use16
seg001 ends

seg002 segment para public use16
seg002 ends

seg003 segment para use16 stack
seg003 ends
```
**seg000.asm**
```
.model medium
.386
include segments.inc

public text

seg000 segment
  text db 'Hello World!',0ah,0dh,'$'
seg000 ends

end
```

**seg001.asm**
```
.model medium
.386
include segments.inc

extern print:FAR

seg001 segment

start proc
  mov ax, seg000
  mov ds,ax
  push ax
  pop ax
  call print
  mov ax,4c00h
  int 21h
start endp

seg001 ends

end start
```

**seg002.asm**
```
.model medium
.386
include segments.inc

extern text:BYTE

seg002 segment

print proc far
  mov dx,offset text
  mov ah,09h
  int 21h
  retf
print endp

seg002 ends

end
```

**seg003.asm**
```
.model medium
.386
include segments.inc

seg003 segment
  db 256 dup (?)
seg003 ends

end
```

**build with**
```
uasm64.exe seg000.asm
uasm64.exe seg001.asm
uasm64.exe seg002.asm
uasm64.exe seg003.asm
wlink.exe name multi.exe format dos file seg000.obj, seg001.obj, seg002.obj, seg003.obj
```

i do not use the segment classes ('DATA','CODE','STACK') to just have equal ordering in the resulting multi.exe

the single.exe and multi.exe are nearly identical - except:
-8 bytes alignment at the end of multi.exe
-stack segment is not correctly set in multi.exe header

**single.exe**
```
signature: MZ
bytes_in_last_block: 0x0068
blocks_in_file: 0x0001
num_relocs: 0x0001
header_paragraphs: 0x0003
min_extra_paragraphs: 0x0101 ???
max_extra_paragraphs: 0xffff
ss:sp: 0x0000:0x1040
checksum: 0x0000
cs:ip: 0x0000:0x0010
reloc_table_offset: 0x0020
overlay_number: 0x0000
```

**multi.exe**
```
signature: MZ
bytes_in_last_block: 0x0070
blocks_in_file: 0x0001
num_relocs: 0x0001
header_paragraphs: 0x0003
min_extra_paragraphs: 0x0010 ???
max_extra_paragraphs: 0xffff
ss:sp: 0x0000:0x0000 <========
checksum: 0x0000
cs:ip: 0x0000:0x0010
reloc_table_offset: 0x0020
overlay_number: 0x0000
```
**single.map**
```
Open Watcom Linker Version 2.0 beta Sep 13 2019 01:44:55 (64-bit)
Copyright (c) 2002-2019 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
Created on:       19/09/13 09:26:34
Executable Image: single.exe
creating a DOS executable


                        +------------+
                        |   Groups   |
                        +------------+

Group                           Address              Size
=====                           =======              ====

DGROUP                          0000:0000            00000000



                        +--------------+
                        |   Segments   |
                        +--------------+

Segment                Class          Group          Address         Size
=======                =====          =====          =======         ====

SINGLE_TEXT            CODE           AUTO           0000:0000       00000000
_DATA                  DATA           DGROUP         0000:0000       00000000
SEG000                                AUTO           0000:0000       0000000f
SEG001                                AUTO           0000:0010       00000011
SEG002                                AUTO           0000:0030       00000008
SEG003                 STACK          AUTO           0000:0040       00001000


                        +----------------+
                        |   Memory Map   |
                        +----------------+

* = unreferenced symbol
+ = symbol only referenced locally

Address        Symbol
=======        ======

Module: single.obj(..\single.asm)
0000:0010*     start
0000:0030*     print


                        +-----------------------+
                        |   Linker Statistics   |
                        +-----------------------+

Stack size:  1000 (4096.)
Memory size:  1040 (4160.)
Entry point address: 0000:0010
Link time: 00:00.06
```

**multi.map**
```
Open Watcom Linker Version 2.0 beta Sep 13 2019 01:44:55 (64-bit)
Copyright (c) 2002-2019 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
Created on:       19/09/13 09:26:37
Executable Image: multi.exe
creating a DOS executable


                        +------------+
                        |   Groups   |
                        +------------+

Group                           Address              Size
=====                           =======              ====

DGROUP                          0000:0000            00000000



                        +--------------+
                        |   Segments   |
                        +--------------+

Segment                Class          Group          Address         Size
=======                =====          =====          =======         ====

SEG000_TEXT            CODE           AUTO           0000:0000       00000000
SEG001_TEXT            CODE           AUTO           0000:0000       00000000
SEG002_TEXT            CODE           AUTO           0000:0000       00000000
SEG003_TEXT            CODE           AUTO           0000:0000       00000000
_DATA                  DATA           DGROUP         0000:0000       00000000
SEG000                                AUTO           0000:0000       00000010
SEG001                                AUTO           0000:0010       00000020
SEG002                                AUTO           0000:0030       00000010
SEG003                                AUTO           0000:0040       00000100


                        +----------------+
                        |   Memory Map   |
                        +----------------+

* = unreferenced symbol
+ = symbol only referenced locally

Address        Symbol
=======        ======

Module: seg000.obj(..\seg000.asm)
0000:0000      text
Module: seg001.obj(..\seg001.asm)
0000:0010*     start
Module: seg002.obj(..\seg002.asm)
0000:0030      print
Warning! W1014: stack segment not found


                        +-----------------------+
                        |   Linker Statistics   |
                        +-----------------------+

Stack size:  1000 (4096.)
Memory size:  0140 (320.)
Entry point address: 0000:0010
Link time: 00:00.06
```

according to the map files the Stack size is equal, the Memory size differs and the segment sizes are also different

building a working single.exe works without any problem, exe header ss:sp is correct

problems when building multi.exe
1. "Warning! W1014: stack segment not found" - and the resulting exe header ss:sp is 0:0
2. there is a alingment difference between the seg002 and seg003 (the multi.exe is 8 bytes larger then single.exe)
in multi.exe the alignment is part of the image in single.exe the alignment is part of the uninitzialised data area before the stack segment (which itself is in uninitzialized data area)

question:
1. why do wlink find the stack segment in single.asm but not in the splitted segment multi version? (ms linker, optlink do not fail here) - it works if i add 'STACK' but i don't want to change the segment order - i've got examples where the stack segment is in the exe image and code segement comes after
2. why is the alignment differently materialized by the linker? (ms linker behaves equal to wlink, optlink creates identical executables)

thanks for your/any help

**Comment by jmalak** [comment]
The sample code has a few minor mistakes that I fixed it (missing "end start" in single.asm and "public print" in asm002.asm).
It looks like some problem with segment ordering if native order is used.
'STACK' class is used to define main stack used for executable. 
You can have multiple independent stacks.
May be we can add feature if stack segment in 'STACK' class is not found then try to search first segment with stack attribute even if use different class.
I will investigate a problem and return back as soon as I get some results.

**Comment by LowLevelMahn** [comment]
> missing "end start" in single.asm
copy & paste mistake

> public print
i've read that procs are public per default - and the source assembles correct

> May be we can add feature if stack segment in 'STACK' class is not found then try to search first segment with stack attribute even if use different class.

the question is why wlink is able to find the stack-segment in the single.obj but not in the combined seg00x.objs? even the stack size in the map is correct

**Comment by jmalak** [comment]
On my box the same problem for both (single and multi), but I am using wasm.
It looks like you forgot remove 'STACK' class from segment.
wlink find only class 'STACK' for stack segment.

**Comment by LowLevelMahn** [comment]
> It looks like you forgot remove 'STACK' class from segment.
> wlink find only class 'STACK' for stack segment.

happend while testing all wild combinations :(

**Comment by LowLevelMahn** [comment]
your answers reducing my questions down to

why is a alingment difference between the seg002 and seg003 (the multi.exe is 8 bytes larger then single.exe)
 in multi.exe the alignment is part of the image in single.exe the alignment is part of the uninitzialised data area before the stack segment (which itself is in uninitzialized data area)

**Comment by jmalak** [comment]
I don't see any problem with alignment, all segments has para 16 bytes.

**Comment by LowLevelMahn** [comment]
> I don't see any problem with alignment

there is no functional "problem" with the alignment its just differently "materialized" in the two executables - breaking my 100% binary identical goal, i don't want to introduce any difference in the splitting, its easy enough to introduce new bugs while reversing code

im currently working on an IDA script that splits up analyzed 16 bit dos programs into segments and eases the process to get to an identical re-assembled exe

**Comment by jmalak** [comment]
For stack info in wlink map file, the size is size defined by application or by wlink.
for DOS target default size is 4kB and minimum size is 512 bytes.
It is not reset if stack segment is not defined.

**Comment by jmalak** [comment]
executable size difference can be due to segment reordering or another problem with last segment attributes handling that executable image is full fill on alignment boundary for some reason.
The wlink is complex because it supports multiple executable formats with different requirement that there can be some hidden problem.

**Comment by LowLevelMahn** [comment]
alignment "materilization" of different linkers:

mslink = wlink
   single.exe (part of uninitialized area before stack), multi.exe (8 bytes at end of image)
ulink = optlink: 
  in both exes part of uninitialized area before stack

UniLink v1.11 [beta] (build 11.27) from ftp://ftp.styx.cabel.net/pub/UniLink/

**Comment by LowLevelMahn** [comment]
your partial fix works!

**Comment by LowLevelMahn** [comment]
still open is the behavior of adding the 8 bytes alignment to the end of the multi.exe

**Comment by jmalak** [comment]
I am working on this problem because there are multiple related problem. By example in map file segment size is displayed as aligned value. If segments are in separate file, if it is in one file then size is displayed correctly unaligned etc.
It will needs more deaper review of wlink code.
I will return back as soon as it will be corrected.

**Comment by LowLevelMahn** [comment]
thanks for all your help

**Comment by jmalak** [comment]
Now it should be fully fixed.

**Comment by LowLevelMahn** [comment]
i've tested with: Open Watcom Linker Version 2.0 beta Sep 15 2019 02:07:44 (64-bit)
the alignment bytes materialization is fixed! single.exe and multi.exe are equal now and map files differ only correctly in ordering helper segments

thank you very much
