### ISSUE TITLE
Current-build open-watcom-2_0-c-linux-x64 installer segfaults

### ISSUE THREAD

**Issue by klei1984** [open-watcom/open-watcom-v2#556]
Since a couple of days the open-watcom-2_0-c-linux-x64 artifact from [current builds](https://github.com/open-watcom/open-watcom-v2/releases) segfaults.

OS: Ubuntu 19.04 (Disco)
File access permissions: 775 (-rwxrwx-r-x)
Installer is run from terminal. After segfault, mouse hoover over terminal captured by the terminal window and characters are printed on screen on mouse move, mouse wheel does not work, but otherwise terminal is responding to keyboard and commands.

Segfault message says a core dump had been created, but actually ubuntu's apport rejects dump creation. Attached is a valgrind log which might or might not be useful. [log.zip](https://github.com/open-watcom/open-watcom-v2/files/3623508/log.zip)

A couple of weeks ago the current-builds were working on an ubuntu 18.x something.

**Comment by jmalak** [comment]
Thanks for bug report.
I will check and fix it.

**Comment by klei1984** [comment]
As addition confirmation the open-watcom-2_0-c-linux-x86 variant does not crash.

**Comment by jmalak** [comment]
It looks like Intel current instruction set problem.
I will add some option to restrict compiler to use some minimal instruction set which is available on all X64 processors, now it uses default compiler setup (probably what is available on build machine).

**Comment by klei1984** [comment]
Interesting. I attached the CPU info for reference. What I also forgot to mention is that I am running on a virtual machine actually. The guest is ubuntu while the host is windows 10 home 64 bit maybe that also has some side effects.

[cpuinfo.zip](https://github.com/open-watcom/open-watcom-v2/files/3624632/cpuinfo.zip)

CPU model: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (ubuntu recognizes my hardware correctly).

**Comment by jmalak** [comment]
I will test it on Ubuntu after recompilation with changed compiler options.
It could be also some memory issue. 
In near past it was similar problem with 64-bit installer on Windows 7 on other version it worked. But luckily it was a problem during memory deallocation after installing OW.
I will return back as soon as it will be fixed.

**Comment by jmalak** [comment]
I investigate this problem and it looks like glibc bug or gcc and glibc combination bug.
glibc from some version uses automatic CPU feature detection and use various code in dependency of available CPU instructions etc.
For some reason avx version of memmove function fails. 
I am not able determine the reason for it.
It looks like rather memory alignment problem for avx instruction then memory buffer underflow/overflow. I am not able to switch off using avx code in glibc.
Afected is only 64-bit Linux version which uses glibc.
all other platforms are OK.

**Comment by jmalak** [comment]
It should be fixed by commit 2de74b9c62b337b7c276abc425732c793a689459

**Comment by jmalak** [comment]
I checked it on Ubuntu and it works OK now.

**Comment by klei1984** [comment]
I can confirm that installation finished successfully, thanks for help!

Just so that I also learn something from you, how did unsigned to int and ORD to int help in this issue? Is ORD a custom type or macro replacement to something 32 bit fixed width?

**Comment by jmalak** [comment]
It is one of discrepancies in UI project. 
ORD is unsigned for most platforms but for RDOS it is signed.
Size is also platform dependant. I introduce some other macros to minimise use of ORD macro, but it still requires some effort to analyse code and replace ORD by some fixed prototype on all platforms.

Back to problem, it was problem with mixing signed and unsigned values in multiply operation. 
Result was in some cases unsigned instead of signed, which is expected for position calculation if frame mode of virtual screen is used.
Coordinates of virtual vindow is 0,0 based that all user coordinates is only unsigned values.
If virtual screen uses frame then frame is map to -1,-1 coordinates.
It was reason to correct all parameters which are used for position calculation to be signed.

**Comment by mgarcia-org** [comment]
open-watcom-f77-linux-1.9
open-watcom-c-linux-1.9

Both crashed on me with the same error: Floating point exception (core dumped)
Maybe me, Linux desktop 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I build from src okay

**Comment by jmalak** [comment]
Open Watcom 1.9 has a few bugs to not work properly on new Linux distros.
Try to install it by OW 2.0 installer.
If you run OW2.0 installer and put OW1.9 installer name as parameter then it could work to install OW 1.9 by OW2.0 installer on your Linux Distro.

**Comment by mgarcia-org** [comment]
Thanks for the reply, I downloaded the current build and ./open-watcom-2_0-c-linux-x64 just worked as expected, many thanks! :+1:
