### ISSUE TITLE
doesn't support wlink blanks in libp parameter?

### ISSUE THREAD

**Issue by LowLevelMahn** [open-watcom/open-watcom-v2#559]
related to my open question how to build a pe exe with wasm/wlink

https://www.reddit.com/r/OpenWatcom/comments/d90ees/how_to_buildlink_this_super_small_windows_program/

its seems that wlink don't like the "" path quotation

btw: what is the best place to ask watcom wasm/wlink related questions?

**Comment by jmalak** [comment]
We don't have specific place. If you are ask it here I think it is best place. Especialy if it is related to OW 2 version. If it is related to OW 1.9 or older version then you can ask also here or Official Open Watcom News server.

Anyway wlink uses single quote instead of double quote.

**Comment by LowLevelMahn** [comment]
> Especialy if it is related to OW 2 version

always and only OW 2 :)

`wlink.exe name pe.small.exe format windows nt file pe.small.obj libp 'C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x86' library kernel32.lib, user32.lib`

thx, works in console, but not in a batch file, due to the **'**, but thats not a problem of OW

**pe.small.asm:**
```
.686
.model flat, stdcall

EXTERN MessageBoxA@16 : proc
EXTERN ExitProcess@4 : proc

.const
msgText db 'Windows assembly language lives!', 0
msgCaption db 'Hello World', 0

.code
Main:
push 0
push offset msgCaption
push offset msgText
push 0
call MessageBoxA@16
push eax
call ExitProcess@4

End Main
```

second question:

how to assemble with wasm?

masm: ml.exe /coff /c /Cp pe.small.asm
uasm: uasm.exe -coff -c -Cp pe.small.asm
wasm: wasm.exe ???

**Comment by jmalak** [comment]
for your example
wasm pe.small.asm
is basic use

**Comment by jmalak** [comment]
Anyway problem with Main is strange.
May be related to coff file format.
I will try why it happen.

**Comment by jmalak** [comment]
if I do
wasm pe.small.asm
wlink sys nt opt map file pe.small.obj

It is linked without error.
It is related to coff format or section names.
I will check with masm

**Comment by jmalak** [comment]
It is problem with Microsoft coff format symbol names.
the Main is in enter:Main directive, but public symbol is _Main that wlink cannot find Main symbol.
It looks like MS use some mangling of symbol Main but wlink not use this mangling.
I will try to look for MS COFF symbol mangling to implement it for coff modules.

**Comment by jmalak** [comment]
it is fixed now in git by following commits
c51430f6f16ea4df52298da2016b590306a21dce
40c6bfbac5dada17a4d189e2bc8828b7342e1f4d

**Comment by jmalak** [comment]
Generaly you should use directive "system ..." instead of "format ..."  for wlink.
Format is low level directive if you need something specific not cover by system directive.
system directive contains full wlink setup including library and libraries path and CRTL startup code etc.
If you use format directive you nedd specify all exactly.
In your case use of "system nt" simplify wlink command, you can not specify any standard windows library.

**Comment by LowLevelMahn** [comment]
warning is gone and using ^ for escaping fixes my batch files

`wlink.exe name pe.small.exe format windows nt file pe.small.obj libp ^'C:\Program Files ^(x86^)\Windows Kits\8.1\Lib\winv6.3\um\x86^' library kernel32.lib, user32.lib`

but using only nt as system type gives me an error:

```
..\open-watcom-2_0-c-win-x64\binnt64\wlink.exe sys nt opt map file pe.small.obj
Open Watcom Linker Version 2.0 beta Sep 27 2019 01:45:45 (64-bit)
Copyright (c) 2002-2019 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
Warning! W1107: undefined system name: nt
loading object files
Error! E3002: ** internal ** - format not decided
```

**Comment by jmalak** [comment]
It looks like you have not setup OW environment variable WATCOM etc. or you not have setup PATH properly that wlink can not find wlink.lnk file.
Looks into OW root for configuration instructions.
