### ISSUE TITLE
About macro redefinition during preprocessing

### ISSUE THREAD

**Issue by NovaRain** [open-watcom/open-watcom-v2#561]
I'm not sure if this is also valid for generic C source code.
The SSL scripts of cRPG Fallout 2 require a C preprocessor for the compiler to work, but for some reason Watcom doesn't give any warning on macro redefinition like this:
```
// a simple header file, mydefine.h
#define MACROX (99)

// the script, myscript.ssl
#include "mydefine.h"

#define MACROX (1) // macro redefinition

procedure start begin
   variable var1 := MACROX;
   display_msg("Var1: " + var1);
end
```
The preprocessed result from `wcc386 myscript.ssl -p -w4` is:
```
procedure start begin
   variable var1 := (99);
   display_msg("Var1: " + var1);
end
```
There's no warning in cmd, and it seems Watcom just ignored the redefinition. Using other C compilers/preprocessors like [mcpp](http://mcpp.sourceforge.net/), GCC, and Orange C all give `variable var1 := (1);` after preprocessing (and usually warning about macro redefinition). Is there any switch I missed, or the behavior is intended for Watcom?

**Comment by jmalak** [comment]
Thanks for bug report

**Comment by jmalak** [comment]
Behaviour of C and C++ compiler is different.
C++ select last value.
Anyway if preprocessing is active then OW compilers suppress any warning/error messages.
It should be changed, but it must be backward compatible.
Warning/error messages should be send to stderr or writen to error file.

**Comment by NovaRain** [comment]
> We could change type of this exception from error to warning for C compiler

Judging from other C compilers, I suppose this should be a more logical solution? Also I never thought C compiler would treat macro redefinition as error instead of warning, but I guess it's just me not having enough experience on various compilers.

**Comment by jmalak** [comment]
Thanks this behaviour we found out mistake in curl project.
Programers tend to ignore warnings.
But probably best solution will be to change C compiler behaviour for it to be reported as warning with highest severity.
Anyway output warning/error during preprocessing must be fixed.

**Comment by burner1024** [comment]
> Anyway if preprocessing is active then OW compilers suppress any warning/error messages.
> It is confusing and could be changed, but it must be backward compatible.

Is there a way to un-suppress it? Some switch?
Also, generally, if there's an error, it's expected that a non-zero exit code is returned. Is that also suppresed?

**Comment by jmalak** [comment]
Errorrs can not be suppressed only warnings.
options -wcd=<num> (disable warning) and -wce=<num> (enable warning)
Unfortunately errors change compiler return code.
Warning changes compilers return code only if -we option is used, then warning is treated as error.

**Comment by jmalak** [comment]
I changed C compiler error ERR_MACRO_DEFN_NOT_IDENTICAL to be warning (level 1) and to be relaxed by redefinition of macro. It changes behaviour to be same as C++ compiler.

**Comment by jmalak** [comment]
C compiler is now fixed by commits
42114a394402477cd037255bb694a37cd90b424c
d1e07e2746183a3f8a15f1d19fe0493a4f6aae89
2fbd78aab8bb51d39f52257bd40dd8afab6fa2bb

now compiler output errors/warnings to the error output or error file for all platforms.
Precompiled output is passed to standard output or output file for all platforms

**Comment by jmalak** [comment]
C++ compiler is fixed too

now compiler output errors/warnings to the error output or error file for all platforms.
Precompiled output is passed to standard output or output file for all platforms

**Comment by NovaRain** [comment]
Thank you for the fixes. Now wcc works in the same way as other compilers/preprocessors. :D
