### ISSUE TITLE
IDE in the latest build will crash when pressed any key on ArcaOS(aka OS/2)

### ISSUE THREAD

**Issue by Frozen-Tofu** [open-watcom/open-watcom-v2#563]

**Comment by jmalak** [comment]
Thanks for bug report.
It looks like bug in gui subroject.
Character mode tools work OK.
OW 2.0 was not tested on OS/2 for very long period due to missing interest from OS/2 comunity.
You are first from time OW 2.0 was lauched.

**Comment by Frozen-Tofu** [comment]
I've tested the old OW 1.9, it didn't appear to have this bug.

**Comment by jmalak** [comment]
Yes, it is bug in OW 2.0.
in OW 2.0 is many code change to ensure portability for 64-bit platforms, that something was broken on OS/2.
The problem is same for all OS/2 GUI applications.

**Comment by Frozen-Tofu** [comment]
I’m new to OS/2 application development, I wonder if I can do something to fix this issue.

发自我的iPhone

**Comment by jmalak** [comment]
No problem.
I will fix it, but it take me some time to install Virtual machine with OS/2 and debug it, because I am not using OS/2 regulary.

**Comment by jmalak** [comment]
#583

**Comment by jmalak** [comment]
It is fixed now.
Several fixes for OS/2 was done for mistakes done during migration code to be compatible with 64-bit .
OS/2 installer and all GUI tools are working again.

**Comment by Frozen-Tofu** [comment]
Thanks!
