### ISSUE TITLE
whelp segfaults when ALT+S command is issued to initiate Search

### ISSUE THREAD

**Issue by klei1984** [open-watcom/open-watcom-v2#564]
The whelp utility in Current-build open-watcom-2_0-c-linux-x64 (Last updated 2019-10-16 01:47:07) segfaults when I try to use the Search feature. I tried with an earlier version as well and whelp behaved the same way. I also tried with an earlier x32 version from binl folder and it also behaved the same way.

OS: Ubuntu 19.04 (Disco)

The other buttons or controls seem to work. I can navigate within the help file, enter chapters and resume, etc. I run whelp from a terminal.

Valgrind chokes on whelp with unrecognized opcodes and I could not figure out how to make Ubuntu save the crash dumps.

**Comment by jmalak** [comment]
Thanks for your bug report.

**Comment by jmalak** [comment]
I tested it and it crashes if I select some item in search dialog.
Is this problem on other places in whelp?

**Comment by jmalak** [comment]
It should be fixed now.
All platforms were affected, but it has random character due to wrong item list termination.

**Comment by klei1984** [comment]
Thanks for the update! I downloaded the Last-CI-build which stands on this commit and I can confirm that both Linux and DOS whelp tools work now.
