### ISSUE TITLE
Cannot find "trunc"

### ISSUE THREAD

**Issue by shawnpringle** [open-watcom/open-watcom-v2#565]
The watcom linker cannot find trunc.  How do I link it in?

**Comment by jmalak** [comment]
Sorry, what is trunc? module, library, symbol?
at minimum linker command should be enclosed.
*.map file could help to identify what happen, it can be generated by linker directive "option map"

**Comment by shawnpringle** [comment]
trunc gives the integer part of a double.

trunc(3.14.159) is 3.

**Comment by shawnpringle** [comment]
wlink SYS nt op maxe=25 op q op symf op el @$(BUILDDIR)\$(OBJDIR)\euiw.lbc name $(BUILDDIR)\eui.exe

**Comment by jmalak** [comment]
What is exact error output?
Could you add attach map file?

**Comment by shawnpringle** [comment]
`        wmake -h D:\Source\euphoria\source\build2\intobj\main-.c EX="d:\Source\euphoria\source\build\eui.exe" EU_TARGET=eui. OBJDIR=intobj DEBUG= MANAGED_MEM=1 CONFIG=config.wat DEBUG= MANAGED_MEM=1
        wmake -h objlist OBJDIR=intobj DEBUG= MANAGED_MEM=1 CONFIG=config.wat EU_NAME_OBJECT=EU_INTERPRETER_OBJECTS
wmake -h DEBUG= MANAGED_MEM=1 CONFIG=config.wat OS=WINDOWS EU_NAME_OBJECT=EU_INTERPRETER_OBJECTS OBJDIR=intobj D:\Source\euphoria\source\build2\intobj.wat EX="d:\Source\euphoria\source\build\eui.exe"
        wmake -h D:\Source\euphoria\source\build2\eui.exe EX="d:\Source\euphoria\source\build\eui.exe" EU_TARGET=eui. OBJDIR=intobj DEBUG= MANAGED_MEM=1 CONFIG=config.wat DEBUG= MANAGED_MEM=1
wlink   SYS nt op maxe=25 op q op symf op el @D:\Source\euphoria\source\build2\intobj\euiw.lbc name D:\Source\euphoria\source\build2\eui.exe
Warning! W1008: cannot open graph.lib : No such file or directory
Error! E2028: trunc_ is an undefined reference
file D:\Source\euphoria\source\build2\intobj\back\be_execute.obj(D:\Source\euphoria\source\be_execute.c): undefined symbol trunc_
Error(E42): Last command making (D:\Source\euphoria\source\build2\eui.exe) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (D:\Source\euphoria\source\build2\eui.exe) returned a bad status
Error(E02): Make execution terminated`

**Comment by jmalak** [comment]
It is strange because graph.lib is referenced, but it can not be used for WIN32 application, it is DOS library.
Symbol trunc_ should be in math library which should be normaly referenced and linker should automaticaly include it.
Please check map file for used libraries, it looks like some mismatch between OS used for modules compilation and linking target OS (WIN32).

**Comment by shawnpringle** [comment]
It was originally a DOS program.  It does include a header with a similar name to graph.  It is time I removed those lines. 😊 Sincerely, Shawn Pringle From: Jiří MalákSent: October 22, 2019 8:23 AMTo: open-watcom/open-watcom-v2Cc: Shawn Pringle; AuthorSubject: Re: [open-watcom/open-watcom-v2] Cannot find "trunc" (#565) It is strange because graph.lib is referenced, but it can not be used for WIN32 application, it is DOS library.Symbol trunc_ should be in math library which should be normaly referenced and linker should automaticaly include it.Please check map file for used libraries, it looks like some mismatch between OS used for modules compilation and linking target OS (WIN32).—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jmalak** [comment]
Is it working now or some problem still exists?

**Comment by shawnpringle** [comment]
I implemented a trunc function and am not very invested in solving this
issue.

**Comment by jmalak** [comment]
OK. But it looks like you have missing reference to math library in object files for some reason and therefore trunc symbol is not found.
