### ISSUE TITLE
Bugs in RDOS target in Nov 11 release

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#567]
1. Missing include files for rdos:
sys/socket.h
netinet/tcp.h
netdb.h

2. C device driver startup code faults trying to reference through es register when it is zero., It's possible this is caused by adding multithreaded flag to the rdosdev target. Multithreading is not supported here. (https://github.com/open-watcom/open-watcom-v2/blob/master/bld/clib/rdosdev/library/rdosdev.386/mc_r/makefile)

3. Debug traps when doing remote debugging doesn't work. Windows side returns "incorrect trap file version" before even trying to connect to server (wdw -tr=tcp;x.x.x.x). RDOS-based wd works and windows based wd and wdw works with local debugging.

**Comment by rdos314** [comment]
While I don't know the exact position, the fault happens somewhere in the initrtns.c file.
I think it might be these changes in initrtns.c that causes the crash in RDOS device driver startup code (https://github.com/open-watcom/open-watcom-v2/commit/f4a0e7b835424ba7795834f5b6fe62a579d77955#diff-17d50b19b03130a4fe75fd60e5a03ad4), Seems like there are near/far pointer conversions there. RDOS device drivers use a 48-bit memory model.

**Comment by jmalak** [comment]
Sorry, my mistake.
I will review macro FAR2I86NEAR definition for RDOS driver code which is far code.

**Comment by jmalak** [comment]
The problem was wrong implementation of callit function.
There was parameter mismatch, pointer to structure rt_init is near (it is located in DGROUP) but for RDOS device driver code it was far pointer.
Now all implementations of callit use near pointer for rt_init structure properly.

**Comment by rdos314** [comment]
Yes, this seems to solve the issue with faults in device driver initialization. I'll check the missing files when the next release is built, but I assume it's solved too. 

The debugger problem is still there, but I'll create a new issue on it since it is not related to RDOS target specifically.
