### ISSUE TITLE
The tcp remote debug trap doesn't work

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#568]
Do this on the command-line:
wdw -tr=tcp;1.1.1.1 test.
I'll get a popup like this: Incorrect trap file version.
Doing this gives the same error:
wdw -tr=ser test
Using the character-based debugger gives the same error too.

This error is present both in the generated rel tree after building source and in the installation.

**Comment by jmalak** [comment]
It is bug related to remote trap file. 
It looks live inproper trap version is read from remote server and passed back.

**Comment by rdos314** [comment]
I think it is in the traps themselves because the remote server doesn't need to be present for this error to appear.

**Comment by rdos314** [comment]
I compared the list of trap functions, and I cannot see any difference from before, so it seems like it's not because something has happened to the traps themselves.

**Comment by jmalak** [comment]
Thanks for info. Then it must be in trap initialization code.

**Comment by rdos314** [comment]
It's a bit strange because it doesn't seem like the trap functions themselves have changed. Also, if I switch my path to a 2018-12-07 build (a year ago) and run wdw there against the new tcpserv.exe, then everything works as expected.

Can you reproduce this error too, or is it something only I experience? As I noted, you don't need to have a remote server, and so you can just type it on the Windows command line.

**Comment by rdos314** [comment]
It seems like the error occurs before the version is even checked.

It's this line 124 (?) in dig/c/nt/trpld.c that cause the error:
      && TRAPENTRY_PTR_NAME( InfoFunction ) != NULL ) {

**Comment by rdos314** [comment]
If I just remove this additional test then everything works fine, so DLL entry 4 doesn't seem to be used anymore. I let you decide if the test should be removed or fixed in some other way. Note that this is part of other the trpld.c files too.

**Comment by jmalak** [comment]
I accidentally submited work in progress.
I will fix it.

**Comment by rdos314** [comment]
Seems to work now.
