### ISSUE TITLE
Platform WIN32, Windows 7 - lib.exe is not properly working

### ISSUE THREAD

**Issue by stkozlowski** [open-watcom/open-watcom-v2#571]
File shrtest.def:

LIBRARY shrtest
;Functions are linked from DLL to EXE by ordinal numbers marked with @.
;This removes confusion in function names.
EXPORTS ShrAlloc@8 @1
        ShrLock@4 @2
        ShrUnlock@4 @3
        ShrFree@4 @4
        ShrGetLastError@0 @5
       ShrSetLastError@4 @6

When using lib.exe
lib -nologo -def:shrtest.def
lib.exe gives bogus error message about error near  @ 

When comment lines from shrtest.def are removed lib.exe hangs itself indefinitely.
In WATCOM 1.9 everything is OK.

**Comment by jmalak** [comment]
I am not sure if I understand you.
what OW tool problem is reporting?
is it "ms2wlink" or "wlink" or OW clone for Microsoft "lib" or OW "wlib" ?

**Comment by jmalak** [comment]
Sorry, you mean OW clone for Microsoft "lib".
It is stupid mistake during migration code to 64-bit.
I will fix it ASAP.

**Comment by jmalak** [comment]
it is fixed now in git repository

**Comment by jmalak** [comment]
There were a similar problem with other MS tools OW clone. Now fixed.
