### ISSUE TITLE
current build won't build

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#572]
The build fails right away, using Watcom to build the bootstrap.  (See below.)  It also fails right away, with different details, using Visual C++.  I'm looking into this, but would appreciate help.  I've done builds successfully years ago and am now trying to resume working on OW so that I can contribute some bug fixes for the debugger and compiler running hosted by Windows 10 targeting Windows.

This output is from executing "build" for the current build zip file made a few hours ago by OW Azure:

=================== 21:33:13 D:\github\ow\bld\yacc\binbuild ===================
cc bitsets.obj
cc buildpro.obj
cc default.obj
cc defshift.obj
cc dont_opt.obj
cc elimunit.obj
cc fpopen.obj
..\c\fpopen.c(51): Warning! W131: No prototype found for function 'alloca'
..\c\fpopen.c(51): Warning! W102: Type mismatch (warning)
..\c\fpopen.c(51): Note! N2003: source conversion type is 'int'
..\c\fpopen.c(51): Note! N2004: target conversion type is 'char *'
Error(E42): Last command making (fpopen.obj) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 2
Build failed

**Comment by ideafarm** [comment]
What I see is that alloca() is a function available on Linux.  (The man page for it says that its use is discouraged, which is a separate issue.)  (http://man7.org/linux/man-pages/man3/alloca.3.html) What this seems to indicate is that the daily builds are done on Linux and that builds hosted by Windows are not done.  If this is true, it appears that OWV2 can no longer be built on a Windows host.  This defeats the whole multiplatform vision that led to the creation of OW and that makes OW unique and valuable!

Am I right that the daily build does not verify that OW can be built on a Windows host?

**Comment by jmalak** [comment]
OW is build regulary on Windows, Linux Ubuntu and OSX by appropriate host compilers after each change in repository.
You can look on appropriate [build results](https://dev.azure.com/open-watcom/open-watcom-v2/_build).

**Comment by jmalak** [comment]
below is schema of regular OW build with appropriate build platform.
![azure-build](https://user-images.githubusercontent.com/2017260/72930369-15c8fb00-3d5c-11ea-9a29-143f4b9ae7c0.png)

**Comment by jmalak** [comment]
[Azure Pipelines Agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)

**We are using following Agents configurations:**

Windows Server 2016 + VS2017 compiler
Ubuntu 18.04 + gcc compiler
OSX 10.14 + clang compiler

**Comment by ideafarm** [comment]
Thanks, Jiri.  I also have a Windows Server 2016 machine, so I will be able to study this.  Don't hold your breath, though.  I'm going to take my time and focus on getting myself up to speed with GitHub, including Agents.  I've had some serious medical issues as well as a bad case of PTSD, but am recovering from both and think that I will now be able to finally figure out GitHub and become an OW contributor.

**Comment by ideafarm** [comment]
Fixed by bootstrapping using VS and hiding the WATCOM folder by renaming it.
