### ISSUE TITLE
Error! E1190: message number ?

### ISSUE THREAD

**Issue by omm** [open-watcom/open-watcom-v2#574]
Hi!

I'm trying to build https://github.com/harbour/core with OW Version 2.0 beta Jan 31 2020 00:39:28 (32-bit) and got errors:
```
wcc386   -zq -bt=nt -bm -w1 -wcd201 -wcd367 -wcd368 -wcd124 -wcd136 -6s -fp6 -onaehtr -s -ei -zp4 -zt0 -oi -i. -i..\..\..\..\..\..\include  -DUNICODE -IE:\dev\core\src\3rd\zlib -DPNG_NO_STDIO  -fo=png.obj   ..\..\..\png.c
Error! E1190: message number '367' is invalid
Error! E1190: message number '368' is invalid

```
I have OW Version 2.0 beta Aug 20 2019 08:41:38 (32-bit) and with it i can build without errors.
What has changed and where i can read about switches

Thanks

**Comment by jmalak** [comment]
Message handling was changed to report discrepancies for message numbers.
Do you know what these messages 367 and 368 should represent.

**Comment by alcz** [comment]
Possibly this:
Warning W367 // Conditional expression in if statement is always true
Warning W368 // Conditional expression in if statement is always false

Even if those switches are going to be deprecated, it'll be good if such value doesn't yield hard error.

**Comment by jmalak** [comment]
It is backward compatibility issue.
It looks like old watcom message which doesn't exist in OW.
I will change this error (message E1190) to warning only to not stop compiler if wrong message number is used.
Simply it will report warning and message will be ignored.

**Comment by jmalak** [comment]
I don't understand who is author of these compiler options, but it is bad.
All these -wcd options are valid only for OW C++ compiler messages but they are used for OW C compiler.
C and C++ compiler each uses separate set of message numbers with totaly different meaning.
If you are involved in this project then it should be fixed.

**Comment by jmalak** [comment]
It is fixed in git repository now.
The errors 1190 and 1191 was changed to warning 141 and 142 that now any mistake in message number or warning level will be reported as warning and C compiler will continue without any change in warning message/level setup.

**Comment by jmalak** [comment]
You can use next CI build or wait for full installers build to next day( build after midnight 0:0:0 UTC).

**Comment by omm** [comment]
Tnanks a lot.
