### ISSUE TITLE
wattcp: setsockopt(SOL_SOCKET) does not work

### ISSUE THREAD

**Issue by mittorn** [open-watcom/open-watcom-v2#575]
https://github.com/open-watcom/open-watcom-v2/blob/master/bld/wattcp/src/sockopt.c#L81
opt casted to WORD, but SOL_SOCKET is -1:
https://github.com/open-watcom/open-watcom-v2/blob/master/bld/wattcp/inc/sys/socket.h#L127

**Comment by jmalak** [comment]
Thanks for bug report.
It is fixed now in repository.
