### ISSUE TITLE
wattcp: FNBIO ioctl does not work for SUCK_DGRAM in BSD sockets implementation

### ISSUE THREAD

**Issue by mittorn** [open-watcom/open-watcom-v2#576]
https://github.com/open-watcom/open-watcom-v2/blob/master/bld/wattcp/src/ioctl.c#L88
non-blocking IO supported in UDP recv implementation, so it seems must be `if (socket->so_type != SOCK_STREAM && socket->so_type != SOCK_DGRAM)`

**Comment by jmalak** [comment]
Thanks for bug report.
It is fixed in git repository now.
