### ISSUE TITLE
wcc defaults to placing const data in the code segment (-zc)

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#579]
There is a compilation flag on the 16-bit wcc compiler:
`-zc             place const data into the code segment`
which should include all CONST data inside the code segment that uses it.

Consider the example code:
```$ echo test.c
#pragma aux test modify [ ax bx cx dx si di bp ]
int test(unsigned char c) {
  int i;
  switch (c) {
    case 'a' : {
      i = 1;
      break;
    }
    case 'b' : {
      i = 2;
      break;
    }
    case 'c' : {
      i = 3;
      break;
    }
    case 'd' : {
      i = 4;
      break;
    }
  }
  return i;
}
```
When I compile it without the -zc command line parameter:
`wcc -s test.c`
and then disassemble it:
```$ wdis test.o
Module: test.c
GROUP: 'DGROUP' CONST,CONST2,_DATA

Segment: _TEXT BYTE USE16 00000031 bytes
0000				L$1:
0000  19 00                                           DW	offset L$2
0002  1F 00                                           DW	offset L$3
0004  25 00                                           DW	offset L$4
0006  2B 00                                           DW	offset L$5

Routine Size: 8 bytes,    Routine Base: _TEXT + 0000

0008				test_:
0008  2C 61				sub		al,0x61
000A  3C 03				cmp		al,0x03
000C  77 20				ja		L$6
000E  30 E4				xor		ah,ah
0010  89 C3				mov		bx,ax
0012  D1 E3				shl		bx,0x01
0014  2E FF A7 00 00			jmp		word ptr cs:L$1[bx]
0019				L$2:
0019  BA 01 00				mov		dx,0x0001
001C  89 D0				mov		ax,dx
001E  C3				ret
001F				L$3:
001F  BA 02 00				mov		dx,0x0002
0022  89 D0				mov		ax,dx
0024  C3				ret
0025				L$4:
0025  BA 03 00				mov		dx,0x0003
0028  89 D0				mov		ax,dx
002A  C3				ret
002B				L$5:
002B  BA 04 00				mov		dx,0x0004
002E				L$6:
002E  89 D0				mov		ax,dx
0030  C3				ret

Routine Size: 41 bytes,    Routine Base: _TEXT + 0008

No disassembly errors

Segment: CONST WORD USE16 00000000 bytes

Segment: CONST2 WORD USE16 00000000 bytes

Segment: _DATA WORD USE16 00000000 bytes
```
The CONST data **is** included in the _TEXT segment.  This should only happen if compiled with -zc.

**Comment by jmalak** [comment]
Sorry you didn't define any const data.
Compiler internal data is compiler decision where it put.
switch statement is mostly optimized to jump table, which is automaticaly put in code segment.
You can not dictate compiler where put data, you can only say where you want to put your data.
If it is possible then compiler do it, but if it is not possible then is irrelevant what you want.
By example -zc option has sense in 16-bit big data (far) in small data it is not put in code segment.

**Comment by negge** [comment]
Thank you for the explanation.  I understand what you are saying and this does not seem related to -zc option.  Instead, can you have the compiler internal data go after the function definition?

The current implementation is fine generally.  However, the problem I am running into is that when using the compiled object files (.o) with a different linker to build a MS-DOS COM program, the assumption is that the segment that contains main_ has the main() function as the first bytes in the segment (it assumes that when laying out segments into the COM file structure, the one with main can go first).

In the example above, the issue is that it is trying to execute the jump table because it comes first.

Since this is compiler internal data and up to the compiler, can you change the implementation so that this data goes after the body of the function that generates it?

**Comment by jmalak** [comment]
Sorry it it optimizing compiler and it is little out of scope.
If you need to create COM format you can define auxiliar main and jump to real "main".

**Comment by jmalak** [comment]
below is example
```
#pragma aborts test;
int test(unsigned char c);

void  test1( void )
{
    test( 'A' );
}

int test(unsigned char c) {
  int i;
  switch (c) {
    case 'a' : {
      i = 1;
      break;
    }
    case 'b' : {
      i = 2;
      break;
    }
    case 'c' : {
      i = 3;
      break;
    }
    case 'd' : {
      i = 4;
      break;
    }
  }
  return i;
}
```
and disassembled code
```
.387
                PUBLIC  test1_
                PUBLIC  test_
                EXTRN   _small_code_:BYTE
DGROUP          GROUP   CONST,CONST2,_DATA
_TEXT           SEGMENT BYTE PUBLIC USE16 'CODE'
                ASSUME CS:_TEXT, DS:DGROUP, SS:DGROUP
test1_:
        mov             ax,41H
        jmp             test_
        cld
L$1:
    DW  offset L$2
    DW  offset L$3
    DW  offset L$4
    DW  offset L$5
test_:
        push            bx
        push            dx
        sub             al,61H
        cmp             al,3
        ja              L$6
        xor             ah,ah
        mov             bx,ax
        shl             bx,1
        jmp             word ptr cs:[bx+L$1]
L$2:
        mov             dx,1
        jmp             L$6
L$3:
        mov             dx,2
        jmp             L$6
L$4:
        mov             dx,3
        jmp             L$6
L$5:
        mov             dx,4
L$6:
        mov             ax,dx
        pop             dx
        pop             bx
        ret
_TEXT           ENDS
CONST           SEGMENT WORD PUBLIC USE16 'DATA'
CONST           ENDS
CONST2          SEGMENT WORD PUBLIC USE16 'DATA'
CONST2          ENDS
_DATA           SEGMENT WORD PUBLIC USE16 'DATA'
_DATA           ENDS
                END
```
and C source

**Comment by negge** [comment]
Yes, I understand how most of the linkers for COM programs typically work.  I ended up writing my own compressing linker (https://github.com/negge/xlink) because I compete in size coding contests where the target size is 1024, 512 or even 256 bytes and would like to avoid the unnecessary jump.

I have updated my linker to detect when main() is not at offset 0x0000 of the _TEXT segment that contains it so I can at least print a linker error.  Is it really too difficult to put jump table after the function that needs it?  All off the offsets (both of the jump location and the addresses in the jump table) are relative to the segment (thus easy to modify) and cannot be output in a single pass anyway.

Are you aware of any other instances where the WATCOM compiler inserts compiler specific data before the function that generates it?

**Comment by jmalak** [comment]
If you need smallest size then probably assembler is best.
I don't know in details how OW optimize it, that sometimes it can be before, sometime it is in midle or after function body. It depend on jumps distances etc. 
generaly in assembler you can define start entry point that linker can add jump on begining of binary code if necessary.

**Comment by negge** [comment]
Yes, I understand the issues around using a short jmp instruction and why the jump table might be located in any of those three places.

If you can point me to where in the code this table is emitted, I'll have a look and see if I can improve the size optimization of that code so it does not place it in a sub-optimal way.

**Comment by jmalak** [comment]
It is mainly about optimization which is done on generated code it is relatively complex piece of code that no simple place to point you. processing of switch statement encodding is simpler.
There is called initial funtion with variable to check, next it is called for each case or default and end of switch statement.
Here is details about High level code genarator functions [OW Code generator Documentation](https://open-watcom.github.io/open-watcom-v2-wikidocs/cgdoc.html)
It is functions
CGSelInit
CGSelCase
CGSelRange
CGSelOther
CGSelect
CGSelectRestricted
