### ISSUE TITLE
__DATE__ macro produces truncated date (last year digit) 2020 -> 202

### ISSUE THREAD

**Issue by hadjiprocopis** [open-watcom/open-watcom-v2#580]
Hi there and thank you for providing open-watcom. It's a great project and enables me to cross-compile C++ code for MSDOS (v6) using my Linux machine. Thanks!

The issue is minor, the following code outputs incorrect date, the last year digit (0 for the year 2020) is truncated when compiling for MSDOS:

```
// wpp a.c && wlink system dos option stack=4096 option map option eliminate name a.exe file a.o
// result is
//     DATE: 'Feb 17 202'
// last year digit is truncated

#include <stdio.h>

int main(void){
	printf("DATE: '" __DATE__ "'\n");
}

```

when the produced executable ```a.exe``` is run on my emulated MSDOS box (either via VirtualBox or dosbox) from Linux host, it produces

```DATE: 'Feb 17 202'```

(I am sure the following info is superfluous but maybe it can point you faster to the problem: 
```
./bld/cc/h/cvars.h:global char         __Date[12];         /* "MMM DD YYYY" for __DATE__ macro */
./bld/cpp/c/preproc.c:char                PP__DATE__[14];                 // value for __DATE__ macro

./bld/cpp/c/preproc.c:    sprintf( PP__DATE__, "\"%3s %2d %d\"", Months[tod->tm_mon], tod->tm_mday, tod->tm_year + 1900 );
```

Many Thanks,

Andreas

**Comment by jmalak** [comment]
Hi,
Thanks for bug report, I am able to reproduce it.
I will fix it ASAP.

**Comment by hadjiprocopis** [comment]
++!
it just occured to me to check ```__TIME__``` too. And yes, it needs fixing too. Last digit is truncated on my system.

Thanks for the quick response.

**Comment by hadjiprocopis** [comment]
btw, I don't understand why because the size of ```__Date[12]``` allows for ```Feb 18 2020``` and has space for a terminating null.

**Comment by jmalak** [comment]
Yes, it is bug in C++ compiler, it is general issue not related only to __DATE__ macro.
There is some special handling for "STRING" macros that length of string is including terminating zero and there are mismatch somewhere in real length calculation (decrement length).  Special macros __DATE__ and __TIME__ has wrong length (without terminating null character). I must review code and remove all exceptions if possible or fix the intenal length __DATE__ and __TIME__ of special macros.

**Comment by jmalak** [comment]
It is fixed now in git repository (commit 8c76f2f2161c00d2b801eca441cd977b5971a271).

**Comment by hadjiprocopis** [comment]
thank you

**Comment by jmalak** [comment]
There was one build mistake, that one additional fix was necessary.
