### ISSUE TITLE
No symbol records for local variables in obj files when using -hc -d2 with wcc

### ISSUE THREAD

**Issue by bluewaysw** [open-watcom/open-watcom-v2#581]
When I use the 16 bit compiler wcc with the option -hc to generate codeview style symbolic information and -d2 to include globals but also local variable symbols, there are no records of type "(0x0100) BP Relative 16:16" in the resulting obj file.

Is this by intention or mya we consider this a bug? Maybe I missed some option to enable the required output?

**Comment by ideafarm** [comment]
This might be related to the problem I have with the windowed debugger not always being able to display the value of local automatic (stack) variables.  AFAIK that bug has not been reported but has been a problem for me for several years.  (Host: Windows 10 32 bit; Target: Windows 10 32 bit.)

**Comment by jmalak** [comment]
Probably it is bug, because there was a lot of changes and developments in Codeview debug format to support higher version of CV format and for 64-bit host support (during Open Watcom era). It is also not tested much because OW preffered format is DWARF. Please try to used OW objdump utility on generated *.obj files to display debug info included.
Do you using CV debug info format with OW debugger or external debugger?

**Comment by bluewaysw** [comment]
Is there a windows binary of dipdump somewhere?

The CV debug info is used indirectly by an external debugger, swat in my case as result of constructing a replacement toolchain for the FreeGEOS project: https://github.com/bluewaysw/pcgeos. Glue is the linker that reads CV based objf files and creates proprietary sym files.

The key problem with this is that it seems the obj files produced by WCC currently doesn't contain the required records.

**Comment by jmalak** [comment]
I enclose Windows 32-bit version of dipdump utility
[dipdump.zip](https://github.com/open-watcom/open-watcom-v2/files/4238832/dipdump.zip)
It works on any OW executable with debug info or on appropriate *.sym file.
I enclosed all DIPs that you can check various formats not only CodeView.
Anyway this utility is located in source tree `bld/dip/dipdump`.

**Comment by jmalak** [comment]
I looked little in the code generator code and it should works (bprel records should be generated).
Anyway it is bug.

**Comment by jmalak** [comment]
Please, identify if it is missing bprel record or wrong format of bprel record or not meet some expectation of freeGeos linker.
It should be vissible in dipdump output.
Anyway I am not sure if it is correct but 16 bit symbol names are not align to 4-byte boundary.

**Comment by bluewaysw** [comment]
dipdump wasn't working for watcom and didn't print any local vars or function parameter symbols for dwarf or codeview. But I figured out using dmpobj which option prevents bprel records to be create for codeview. If I remove the -os option the records are created as required. Not sure if this is by any intention, we probably can live without -os for now.

I think it is correct that (depending on other compiler option) symbols are not 4-byte-boundary aligned.

Thank you for your support!

**Comment by jmalak** [comment]
Oh sorry, it looks like you have wrong order of compiler options.
options for debugging must be after options for optimization or you must use option for optimization disable -od. There is dependency between options for optimization and for debugging.
If you have debugging options as last you will have no problems.

**Comment by jmalak** [comment]
It could be useful to generate some message if optimization and debug options affected each other and  add this message on some high warning level (4) to warn user about this problem.
