### ISSUE TITLE
Watcom can't be built under Linux.

### ISSUE THREAD

**Issue by jirkakunze** [open-watcom/open-watcom-v2#582]
I have made the following changes to setvars.sh:

`export OWDISTRBUILD=1`
and
`export OWDOSBOX=dosbox`

I get the following message:

Error(E42): Last command making (../bin/open-watcom-2_0-c-dos.exe) returned a bad status
Error(E02): Make execution terminated
<pmake -d build         -h> => non-zero return: 512
Build failed

Do you have any hints for me where the problem is?

**Comment by jmalak** [comment]
I have a question. Previous build of all OW tools was succesful or not?

**Comment by jmalak** [comment]
I think I know why it happen. The full build including installers required to build full set of documentation in all formats. The main problem is Microsoft Windows Help compilers.
They are not available for Linux OS that full documentation ca not be build on Linux.
I tested in the past to install Microsoft Windows Help compilers in Wine but I didn't succed.

If you want to build installers then best is to do build on Windows or do build manualy with some limitation.
If you want to do it manualy then don't use OWDISTRBUILD environment variable.
First you do full OW build, next you build documentation on Windows and copy it to Linux box and last you run build installers manualy. There is test option to build installers without Documentation.
It creates all documentation files with zero size and next run build installers.
