### ISSUE TITLE
os2386 ide crash 

### ISSUE THREAD

**Issue by HnkGitHub** [open-watcom/open-watcom-v2#583]
OS: OS/2 Warp with fixpack15

IDE.EXE crashes when accessing new folders: using the toolbar, and using the menu option.

![Warp 4 Registers](https://user-images.githubusercontent.com/38794884/75077770-5174f300-54c9-11ea-8027-313e20da5f7e.png)

I think this has been an issue for years with the v2 build. Been about 4 years since I messed with open-watcom-v2. Had the same problem. 

Can build a debug version and step through it, if you'd like. Would like to get this fixed. Will help what I can with your guidance and assistance.

Regards

Henry

**Comment by jmalak** [comment]
I am sorry, but OS/2 was not tested for very long time. I need to install OS/2 on Virtual Machine.
Do you know if somewhere VirtualBox image with installed OS/2 is available?

**Comment by HnkGitHub** [comment]
You can find OS/2 Warp 4 on WinWorldPC. There’s a zipped up copy of an iso image. You then need to install the fixpack 15 available from hobbes NMSU as WATCOM
Will not run unless the fixpack is installed. Watcom 19 built the whole distribution with a few bugs which you can work around:
Mkdir -p Is not supported on OS/2 Warp 4. You can just create the directories manually when you see the error and restart the build process.
Took about 16 hours. I just build it on Windows 10 now. Thought it would build better natively. It doesn’t. Does the same.

https://winworldpc.com/product/os-2-warp-4/os-2-warp-40
https://hobbes.nmsu.edu/download/pub/os2/system/patches/fixpack/warp_4/fp15.zip


You might be better off with 4.52. I didn’t try it. After the fixpack, you’re at 4.51 I think.
The IDE works fine with WATCOM 1.9  in OS/2.

I have it installed on Virtual Box

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jmalak** [comment]
Thanks for your info about OS/2 installation. 
I will try to install it and do work to fix OS/2 version.
Probably there will be more broken things. 
I will see after regression tests run.

**Comment by jmalak** [comment]
#563

**Comment by jmalak** [comment]
It is fixed now.
Several fixes for OS/2 was done for mistakes done during migration code to be compatible with 64-bit .
OS/2 installer and all GUI tools are working again.
