### ISSUE TITLE
Latest Git Pull Hangs, VISUALC X64

### ISSUE THREAD

**Issue by HnkGitHub** [open-watcom/open-watcom-v2#584]
OS2 Build Environment: 
   Windows 10
   VISUALC 2019, x64

Hangs consistently at this point here in the build process on the compilation of the alphains.c file:

> c:\ow\ow20\bld\as\c\asdrectv.c(92): warning C4244: '=': conversion from 'int_32' to 'uint_8', possible loss of data
> c:\ow\ow20\bld\as\c\asdrectv.c(444): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
> cc asdirop.obj
> asdirop.c
> cc asnumlab.obj
> asnumlab.c
> cc ashash.obj
> ashash.c
> cc asmsg.obj
> asmsg.c
> cc alphafmt.obj
> alphafmt.c
> cc alphains.obj
> alphains.c
> 
![HangVS2019](https://user-images.githubusercontent.com/38794884/75091965-a7cd4a80-5538-11ea-96f9-4c1a30c37f05.PNG)

**Comment by jmalak** [comment]
Standard build is done in Pipelines on Windows 2016 Server with VS 2017 and it works without problem.
I will check it with VS 2019 on Windows 2012.

**Comment by jmalak** [comment]
anyway try to look into task manager and check if some "zombie" process with OW tools exists (bwcc386, bwpp386, bwlink, wmake, .....).
If yes then kill all and try again.

**Comment by HnkGitHub** [comment]
I’m guessing that the parallel compilation is hanging the build process.
Where does the user set the cflags for the general compile build process?

I think the CFLAG /MP could be set to  /MP1 to just use one CPU.
I have a dual core multithreaded system. And I believe the default flag for  /MP is
Total number of threads on the system.

Just a temporary fix, if it works. Would like to leave the /MP flag at default to use all the threads possible.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jmalak** [comment]
The problem is related to using external Visual studio compiler.
The definition of VS Compiler common flags are in appropriate section in build/mif/local.mif
common_flags_rel=...
common_flags_dbg=...
where you put some global VS compiler options

**Comment by jmalak** [comment]
My test box has 2 CPU and build OW without problem.
I am using VS 2019 compiler version 
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64
and UCRT version 10.0.18362.0

**Comment by HnkGitHub** [comment]
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x64
UCRT 10.0.18362.0

It appears that sed.exe is caught in a continuous loop. When I end it’s task in task manager it quits:
==================== 00:32:02 c:\owvc\bld\as\axp\binbuild =====================
cpp asi_msg.gh
awk asi_msg.gh
cc asexpr.obj
asexpr.c
cc asopernd.obj
asopernd.c
cc asmem.obj
asmem.c
cc asutils.obj
asutils.c
cc asregs.obj
asregs.c
cc assymbol.obj
assymbol.c
cc asdrectv.obj
asdrectv.c
c:\owvc\bld\as\c\asdrectv.c(92): warning C4244: '=': conversion from 'int_32' to 'uint_8', possible loss of data
c:\owvc\bld\as\c\asdrectv.c(444): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
cc asdirop.obj
asdirop.c
cc asnumlab.obj
asnumlab.c
cc ashash.obj
ashash.c
cc asmsg.obj
asmsg.c
cc alphafmt.obj
alphafmt.c
cc alphains.obj
alphains.c
Error(E42): Last command making (asi_in.y) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 2
Build failed




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jmalak** [comment]
Only for sure, try to check end-of-line characters in source files it should be CR + LF.
Anyway sed should but need not ignore various EOL.

**Comment by jmalak** [comment]
Try to check content of intermediate file asi_in.tmp.

**Comment by HnkGitHub** [comment]
Ran find -name \*.c -exec unix2dos \{} \;  from to root directory.
Didn’t help
This is the output when I hit Ctrl^C and say no to terminate the batch file.
Don’t know if this will help
==================== 12:05:17 c:\owvc\bld\as\axp\binbuild =====================
yacc asiytab.c
Error(E42): Last command making (asiytab.c) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 2
Build failed

Then I could not find the asiytab.c file.
c:\owvc>dir asiytab.c /s
Volume in drive C has no label.
Volume Serial Number is 8A16-6995
File Not Found

c:\owvc>

Here’s the asi_in.tmp: I don’t know what to look for.

%{
#include "as.h"
#include "lexyacc.h"
#include "asparser.h"

typedef uint_16         YYACTIONBASETYPE;
typedef uint_16         YYACTIONTYPE;
typedef uint_16         YYBITBASETYPE;
typedef uint_8          YYBITTYPE;
typedef uint_8          YYPLENTYPE;
typedef uint_16         YYPLHSTYPE;

instruction             *AsCurrIns;

static directive_t      *AsCurrDir;

%}

%union {
    char            *str;
    void            *null;
    int_32          val;
    double          fval;
    sym_handle      sym;
    reg             reg;
    expr_tree       *tree;      /* node in an expression tree */
    instruction     *ins;
    ins_operand     *op;
    asm_reloc_type  rtype;
    directive_t     *dir;
}


%token  <sym>   T_DIRECTIVE
%token  <str>   T_DIRECTIVE_OPERAND
%token  <sym>   T_OPCODE
%token  <sym>   T_IDENTIFIER

/* registers */
%token  <reg>   T_REGISTER

/* manifest constants */

%token  <val>   T_INTEGER_CONST
%token  <str>   T_STRING_CONST
%token  <fval>  T_FLOAT_CONST

/* punctuation and special symbols */

%token          T_COMMA
%token          T_COLON
%token          T_SEMICOLON
%token          T_LEFT_PAREN
%token          T_RIGHT_PAREN
%token  <rtype> T_RELOC_MODIFIER
%token  <val>   T_NUMERIC_LABEL
%token  <val>   T_NUMLABEL_REF

/* arithmetic stuff */

%left   <tree>  T_OR
%left   <tree>  T_XOR
%left   <tree>  T_AND
%left   <tree>  T_SHIFT_LEFT T_SHIFT_RIGHT
%left   <tree>  T_PLUS T_MINUS
%left   <tree>  T_TIMES T_DIV T_MOD
%nonassoc <tree> T_UNARY_MINUS T_NOT T_UNARY_PLUS

%type   <null>  asm_line
%type   <sym>   label
%type   <null>  statement
%type   <null>  directive
%type   <dir>   dir_name
%type   <null>  dir_operands
%type   <null>  dir_op_tail
%type   <null>  dir_op
%type   <null>  dir_ident
%type   <tree>  plus_minus_num_expr
%type   <tree>  num_expr_plus
%type   <null>  dir_ident
%type   <tree>  num_expr
%type   <ins>   instruction
%type   <null>  operand_list
%type   <null>  operand_tail
%type   <op>    operand
%type   <tree>  expression
%type   <reg>   reg_indirect
%type   <op>    mem_reference
%type   <ins>   opcode
%type   <op>    ins_operand
%type   <sym>   identifier

%%

asm_line        : label statement more_stmts                    { }
                ;

label           : /* nothing */                                 { }
                | T_IDENTIFIER T_COLON label                    { ObjEmitLabel( $1 ); }
                | T_NUMERIC_LABEL label                         { ObjEmitNumericLabel( $1 ); }
                ;

statement       : /* nothing */                                 { }
                | directive                                     { }
                | instruction                                   { }
                ;

more_stmts      : /* nothing */                                 { }
                | T_SEMICOLON label statement more_stmts        { }
                ;

directive       : dir_name dir_operands                         {
                                                                    bool okay;

                                                                    okay = DirParse( $1 );
                                                                    DirDestroy( $1 );
                                                                    AsCurrDir = NULL;
                                                                    if( !okay ) YYABORT;
                                                                }
                ;
dir_name        : T_DIRECTIVE                                   { $$ = DirCreate( $1 ); AsCurrDir = $$; }
                ;

dir_operands    : /* nothing */                                 { }
                | dir_op dir_op_tail                            { }
                ;

dir_op_tail     : /* nothing */                                 { }
                | T_COMMA dir_op dir_op_tail                    { }
                ;

num_expr_plus   : /* nothing */                                 { $$ = ETConst( 0 ); }
                | num_expr T_PLUS                               { $$ = $1; }
                ;

plus_minus_num_expr : /* nothing */                             { $$ = ETConst( 0 ); }
                | T_PLUS num_expr                               { $$ = $2; }
                | T_MINUS num_expr                              { $$ = ETUnary( ET_UNARY_MINUS, $2 ); }
                ;

dir_ident       : num_expr_plus identifier plus_minus_num_expr  { DirAddOperand( AsCurrDir, DirOpIdentifier( ASM_RELOC_UNSPECIFIED, $2, ETBinary( ET_PLUS, $1, $3 ), 1 ) ); }
                | num_expr_plus T_RELOC_MODIFIER identifier plus_minus_num_expr
                                                                { DirAddOperand( AsCurrDir, DirOpIdentifier( $2, $3, ETBinary( ET_PLUS, $1, $4 ), 1 ) ); }
                | num_expr_plus T_NUMLABEL_REF plus_minus_num_expr
                                                                { DirAddOperand( AsCurrDir, DirOpNumLabelRef( ASM_RELOC_UNSPECIFIED, $2, ETBinary( ET_PLUS, $1, $3 ), 1 ) ); }
                | num_expr_plus T_RELOC_MODIFIER T_NUMLABEL_REF plus_minus_num_expr
                                                                { DirAddOperand( AsCurrDir, DirOpNumLabelRef( $2, $3, ETBinary( ET_PLUS, $1, $4 ), 1 ) ); }
                ;

dir_op          : num_expr                                      { DirAddOperand( AsCurrDir, DirOpNumber( $1 ) ); }
                | T_DIRECTIVE_OPERAND                           { DirAddOperand( AsCurrDir, DirOpLine( $1 ) ); }
                | dir_ident                                     { }
                | T_STRING_CONST                                { DirAddOperand( AsCurrDir, DirOpString( $1 ) ); }
                | num_expr T_COLON num_expr                     { DirAddOperand( AsCurrDir, DirOpRepeat( $1, $3 ) ); }
                ;

num_expr        : num_expr T_TIMES num_expr                     { $$ = ETBinary( ET_TIMES, $1, $3 ); }
                | num_expr T_DIV num_expr                       { $$ = ETBinary( ET_DIV, $1, $3 ); }
                | num_expr T_MOD num_expr                       { $$ = ETBinary( ET_MOD, $1, $3 ); }
                | num_expr T_PLUS num_expr                      { $$ = ETBinary( ET_PLUS, $1, $3 ); }
                | num_expr T_MINUS num_expr                     { $$ = ETBinary( ET_MINUS, $1, $3 ); }
                | num_expr T_SHIFT_LEFT num_expr                { $$ = ETBinary( ET_SHIFT_L, $1, $3 ); }
                | num_expr T_SHIFT_RIGHT num_expr               { $$ = ETBinary( ET_SHIFT_R, $1, $3 ); }
                | num_expr T_AND num_expr                       { $$ = ETBinary( ET_AND, $1, $3 ); }
                | num_expr T_OR num_expr                        { $$ = ETBinary( ET_OR, $1, $3 ); }
                | num_expr T_XOR num_expr                       { $$ = ETBinary( ET_XOR, $1, $3 ); }
                | num_expr error                                { /* Pass this on so that DirOpXXX will free the memory */ }
                | T_MINUS %prec T_UNARY_MINUS num_expr          { $$ = ETUnary( ET_UNARY_MINUS, $2 ); }
                | T_PLUS %prec T_UNARY_PLUS num_expr            { $$ = $2; }
                | T_NOT num_expr                                { $$ = ETUnary( ET_NOT, $2 ); }
                | T_LEFT_PAREN num_expr T_RIGHT_PAREN           { $$ = ETUnary( ET_PARENS, $2 ); }
                | T_INTEGER_CONST                               { $$ = ETConst( $1 ); }
                | T_FLOAT_CONST                                 { $$ = ETFPConst( $1 ); }
                ;

instruction     : opcode operand_list                           { InsEmit( $1 ); InsDestroy( $1 ); AsCurrIns = NULL; }
                ;

opcode          : T_OPCODE                                      {
                                                                    $$ = InsCreate( $1 );
                                                                    if( AsCurrIns ) InsDestroy( AsCurrIns );
                                                                    AsCurrIns = $$;
                                                                }
                ;

operand_list    : /* nothing */                                 { }
                | ins_operand operand_tail                      { }
                ;

operand_tail    : /* nothing */                                 { }
                | T_COMMA ins_operand operand_tail              { }
                ;

ins_operand     : operand                                       { InsAddOperand( AsCurrIns, $1 ); }
                ;

operand         : expression                                    { $$ = OpImmed( $1 ); }
                | T_REGISTER                                    { $$ = OpRegister( $1 ); }
                | mem_reference                                 { $$ = $1; }
                ;

mem_reference   : expression reg_indirect                       { $$ = OpRegIndirect( $2, $1 ); }
                | reg_indirect                                  { $$ = OpRegIndirect( $1, NULL ); }
                ;


reg_indirect    : T_LEFT_PAREN T_REGISTER T_RIGHT_PAREN         { $$ = $2; }
                ;

expression      : expression T_TIMES expression                 { $$ = ETBinary( ET_TIMES, $1, $3 ); }
                | expression T_DIV expression                   { $$ = ETBinary( ET_DIV, $1, $3 ); }
                | expression T_MOD expression                   { $$ = ETBinary( ET_MOD, $1, $3 ); }
                | expression T_PLUS expression                  { $$ = ETBinary( ET_PLUS, $1, $3 ); }
                | expression T_MINUS expression                 { $$ = ETBinary( ET_MINUS, $1, $3 ); }
                | expression T_SHIFT_LEFT expression            { $$ = ETBinary( ET_SHIFT_L, $1, $3 ); }
                | expression T_SHIFT_RIGHT expression           { $$ = ETBinary( ET_SHIFT_R, $1, $3 ); }
                | expression T_AND expression                   { $$ = ETBinary( ET_AND, $1, $3 ); }
                | expression T_OR expression                    { $$ = ETBinary( ET_OR, $1, $3 ); }
                | expression T_XOR expression                   { $$ = ETBinary( ET_XOR, $1, $3 ); }
                | expression error                              { /* Pass this on so that OpXXX will free the memory */ }
                | T_MINUS %prec T_UNARY_MINUS expression        { $$ = ETUnary( ET_UNARY_MINUS, $2 ); }
                | T_PLUS %prec T_UNARY_PLUS expression          { $$ = $2; }
                | T_NOT expression                              { $$ = ETUnary( ET_NOT, $2 ); }
                | T_LEFT_PAREN expression T_RIGHT_PAREN         { $$ = ETUnary( ET_PARENS, $2 ); }
                | T_INTEGER_CONST                               { $$ = ETConst( $1 ); }
                | T_RELOC_MODIFIER identifier                   { $$ = ETReloc( $1, $2 ); }
                | identifier                                    { $$ = ETReloc( ASM_RELOC_UNSPECIFIED, $1 ); }
                | T_RELOC_MODIFIER T_NUMLABEL_REF               { $$ = ETNumLabelReloc( $1, $2 ); };
                | T_NUMLABEL_REF                                { $$ = ETNumLabelReloc( ASM_RELOC_UNSPECIFIED, $1 ); };
                ;

identifier      : T_IDENTIFIER                                  { $$ = $1; }
                ;
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jmalak** [comment]
It is strange.
Check what sed is used by command `which sed`.

**Comment by ideafarm** [comment]
This appears to be caused by sed, which is spinning the cpu and doing nothing.  I have analyzed this and found that the problem is that sed is built with -Ox (small code size), which for some reason causes no code to be emitted for the loop in getimpline() that gets each input line.  I have reproduced this behavior in Visual Studio.  When sed is built with -Od (optimizations disabled), sed operates as expected and plenty of code is emitted for the loop in getimpline().  See attached photos.

I do not know why Jiri's CI builds aok using VISUALC, but the above findings suggest that there is something different in the Azure execution environment that is causing -Od to be used rather than the -Ox that is specified in the makefiles.

Another puzzle is why -Ox causes all of the code to be omitted for this loop.  Since the bug can be reproduced in Visual Studio, it should be easy and fun to solve both of these puzzles.

Proposal:  Eliminate the use of -Ox by migrating to the use of -Od.  This would be a workaround to solve the build problems.  Then start a project to migrate back to -Ox that would thoroughly analyze and test for correct function.
![sed getinpline disassembly good plenty of code when not optimized](https://user-images.githubusercontent.com/3060794/75395638-a5a41c80-58a7-11ea-9d4e-8537e46736df.png)
![sed getinpline disassembly bad no code when optimized](https://user-images.githubusercontent.com/3060794/75395640-a63cb300-58a7-11ea-9c57-35a7520404da.png)

**Comment by ideafarm** [comment]
BTW, while studying this I noticed that simple changes such as the addition of a printf line would cause the problem to go away.  Another change that had this effect was to use two separate if() statements to test *buf and prev.  I see only one directory containing a sed.c file, and I used the source in that directory to reproduce the problem.

**Comment by jmalak** [comment]
I removed all used register keywords which are useless nowdays and could confuse compiler.

**Comment by jmalak** [comment]
I little changed sed code by 084ef813fee2e7b5199b180e18f9fa44c982d677 commit.
Please, cloud you check now.

**Comment by jmalak** [comment]
I improve 64-bit Windows compatibility by using dynamically linked UCRT (commit 5e60332f828e03b7c5753aa112d39ea8ee2ba6da)
up to now UCRT was statically linked into executable, now it uses dynamic link that OW tools always use UCRT which is current on system and doesn't use what is configured in VS
VS runtime libraries are statically linked to executable that no other component is required to run OW tools

**Comment by jmalak** [comment]
I updated VS C++ Compiler to version 19.24.28316 for x64 and test build.
Build is going smoothly with this compiler on my box, no problem.

**Comment by jmalak** [comment]
It is VS C++ compiler bug and rewriten code in getinpline function for loop fix this problem.

**Comment by HnkGitHub** [comment]
Yeah, that fixed the problem. I suspected it was an optimization problem.

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jmalak** [comment]
Good news, thanks.
