### ISSUE TITLE
Visual Studio optimization sucks and must not be used for VISUALC builds.

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#586]
The three attached screenshots document a simple C program that Visual Studio screws up unless -Od (optimizations disabled) is used.  OWv2 builds using VISUALC tools use -Ox to build sed.exe, which results in sed.exe hanging, which results from cl failing to emit any code for a for loop that inputs each new input line.

I am opening this as a Visual Studio issue rather than posting these pics in the "build hangs" thread because the question here is whether the entire OWv2 build tree should be migrated from -Ox to -Od for VISUALC builds.

BTW, I checked to see whether building sed.exe using WATCOM has the same issue.  It does not.  sed.exe builds and runs correctly when built using WATCOM tools.
![issue visualstudio optimization sucks 3 disassembly with no optimization](https://user-images.githubusercontent.com/3060794/75404656-11927f00-58c0-11ea-9f10-133dbaec5c3b.png)
![issue visualstudio optimization sucks 2 disassembly](https://user-images.githubusercontent.com/3060794/75404659-122b1580-58c0-11ea-8a57-21e065d7f9da.png)
![issue visualstudio optimization sucks 1 source](https://user-images.githubusercontent.com/3060794/75404661-122b1580-58c0-11ea-8e7e-c550cf1a3e1e.png)

**Comment by jmalak** [comment]
What exact version of Visual studio compiler you use (from banner)?
It looks like VS C++ compiler bug, because I have several various version of VS C++ compilers and all are OK.
I don't have latest version of VS C++ compiler.
Anyway thanks for your investigation.
It is only problem with VS C++ compiler (probably some latest version). I don't think that sed code uses any special construct or hacks to confuse compiler.

**Comment by ideafarm** [comment]
I will test your changes in the next few days, possibly today.  But even if the symptom goes away, the defect remains.  Further research has revealed that /Ox is equivalent to /Ob2 /Og /Oi /Ot /Oy and that /Og has been deprecated and "will be removed in a future release".  /Og includes "loop optimization".  It is clear from Microsoft's documentation on /Og that they know that it doesn't work correctly.  We also know from my tests that it doesn't work in a simple test program.  If the test program is compiled within Visual Studio using /Ob2 /Oi /Ot /Oy (omitting /Og), the code is correct.  So, IMO, OWv2 should be migrated away from using /Ox to using /Ob2 /Oi /Ot /Oy.

I have other business to attend to today and tomorrow, but plan to continue to work on this and to send you a pull request.  Feel free to just fix this yourself rather than wait for me, but I should have this pull request to you within a few days.

**Comment by ideafarm** [comment]
I will test your changes in the next few days, possibly today.  But even if the symptom goes away, the defect remains.  Further research has revealed that /Ox is equivalent to /Ob2 /Og /Oi /Ot /Oy and that /Og has been deprecated and "will be removed in a future release".  /Og includes "loop optimization".  It is clear from Microsoft's documentation on /Og that they know that it doesn't work correctly.  We also know from my tests that it doesn't work in a simple test program.  If the test program is compiled within Visual Studio using /Ob2 /Oi /Ot /Oy (omitting /Og), the code is correct.  So, IMO, OWv2 should be migrated away from using /Ox to using /Ob2 /Oi /Ot /Oy.

I have other business to attend to today and tomorrow, but plan to continue to work on this and to send you a pull request.  Feel free to just fix this yourself rather than wait for me, but I should have this pull request to you within a few days.

**Comment by ideafarm** [comment]
I will test your changes in the next few days, possibly today.  But even if the symptom goes away, the defect remains.  Further research has revealed that /Ox is equivalent to /Ob2 /Og /Oi /Ot /Oy and that /Og has been deprecated and "will be removed in a future release".  /Og includes "loop optimization".  It is clear from Microsoft's documentation on /Og that they know that it doesn't work correctly.  We also know from my tests that it doesn't work in a simple test program.  If the test program is compiled within Visual Studio using /Ob2 /Oi /Ot /Oy (omitting /Og), the code is correct.  So, IMO, OWv2 should be migrated away from using /Ox to using /Ob2 /Oi /Ot /Oy.

I have other business to attend to today and tomorrow, but plan to continue to work on this and to send you a pull request.  Feel free to just fix this yourself rather than wait for me, but I should have this pull request to you within a few days.

**Comment by ideafarm** [comment]
Here is the source code.  Build it using Visual Studio Community:
[sed.c.txt](https://github.com/open-watcom/open-watcom-v2/files/4262405/sed.c.txt)

**Comment by jmalak** [comment]
I don't want to change standard compiler option due to MS problem.
I am using VS C++ compiler 19.23.28106.4 and older and no problem with it. It looks like you use problematic version of compiler 19.24.28316  which optimize out simple program. Option -Ox is standard recommended  safe option and works correctly with all previous versions without problem.
If it doesn't work then compiler is unusable because option -O2 has probably same problem. It is not first problem with Microsoft tools. They have bugs in UCRT too. I had to fix it with code over UCRT in OW. In the past I must rewrite some code to overcome VS C++ compiler bugs in optimization. No such problems with other compilers. If it is not working then it should be reported to Microsoft to fix it. I will mark this version of compiler as unsupported.

**Comment by jmalak** [comment]
As I suppose it is bug in Microsoft compiler.
It doesn't work for standard option -O1, -O2 and -Ox.
You should report it to Microsoft.
Rewriten code is compiled correctly with any optimization option.

**Comment by ideafarm** [comment]
I disagree with your decision.  IMO, the best course is to migrate OWv2 from its use of the deprecated, and known dysfunctional, optimization /Og, which is a part of /Ox.  Microsoft isn't going to fix a deprecated feature.  My plan is to migrate the ideafarm/open-watcom-v2 fork to use  /Ob2 /Oi /Ot /Oy and to then create a pull request for you.  This will be part of a larger effort by me to completely clean up OWv2 builds on Windows hosts.  (Are you aware that this is not the only failure when building with VISUALC tools, and that building with WATCOM tools also fails?)

Now that I have some time, I plan to debug builds and then to debug the debugger.  In doing this, I will avoid making any unnecessary changes to the source tree, in the hope that you will accept my pull requests so that open-watcom/open-watcom-v2 can continue to be the fork that Windows-hosted users use.  But regardless of your decisions, I intend to make ideafarm/open-watcom/v2 a rock solid and completely bug free toolchain for Windows-hosted users.

**Comment by jmalak** [comment]
Nobody reported any similar problem.
Build by OW 1.9 is also working OK.
If you use some old version of OW 2.0 then it is no guarantie to work with current source tree.
