### ISSUE TITLE
VISUALC build fails on Windows 10 (causeway:  Expecting comma but found open paren)

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#589]
============= 16:06:58 D:\open-watcom-v2\bld\causeway\cwc\dosi86 ==============
bld_cl .\mkcode.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\vcruntime.h(93): Error! E1009: Expecting ',' but found '('

Host and tools:  Visual Studio Community edition on Windows 10 Professional.

**Comment by jmalak** [comment]
Sorry not happen on any of my Windows build system (32-bit or 64-bit), it also doesn't happen on OW build Pipeline.
You must include more information as minimum. 
You should add here code part where it is reported, snipet from vcruntime.h file.

**Comment by jmalak** [comment]
give here full cl command line for mkcode.exe build, it looks like you have something wrong.
you get it if you go into `.../bld/causeway/cwc` directory and run `builder clean` and next run `builder OWVERBOSE=1` commands

**Comment by ideafarm** [comment]
I just got a VISUALC build to complete aok.  What was happening is that the Watcom compiler was not finding <stdio.h> until it searched Visual Studio Community's headers, so it was using stdio.h from Visual Studio.  That header contains code that requires the VC compiler.  To work around this, I added -I options to various mif files as needed, which turned out to be for about a dozen projects.  Those hardcoded -I options all point to the stdio.h file for DOS that is in the OW tree.

Although I plan to do further testing, I will send these changes to you as a pull request so that you can see what had to be done to get the build to work.  This is just a workaround; a polished fix would (1) put the hardcoded value into an environment variable somewhere, and (2) once there is no longer a need for the VISUALC tools, its environment settings should be removed to prevent the newly built watcom tools from getting include and other files from the VISUALC tree.

**Comment by jmalak** [comment]
You must have damaged build environments, it is not possible.
Build environments have its own setup of include path list, which always include system header files path. It is switch between OW internal, external Compiler and OW external compiler during build process and it depends on target platfom too. 

You always write that this and this is not working in OW, but it is your problem with damaged build environment not with OW itself. OW build system is working properly on 3 host platforms with 3 different compilers in Azure Pipelines also I have several installation for 32-bit and 64-bit host systems. No any problem with it.

Setup of OW build system is simple and require setup of a few environment variables in one special script file and configuration of host compiler, nothing more.


You always say OW is buggy etc. I want improve it, but it is lost of time because up to now you don't fix anything and you are talking and talking how poor OW is.
You don't understand OW build system but always say it is buggy.
You don't read OW build documentation.

You only want to direct others how it should be by you, without appropriate knowledge about OW build environment. It is complex multi-platform cross compiling environment not Windows oriented. What is good for Windows need not be good for other host and targets, OW is Windows independent.

I lost lot of my time to help you but nothing changed on your side, only elemental problems with your useless changes in OW build environment which damage build environment and next you report it as OW bug not as your problem.

**Comment by jmalak** [comment]
We can abandom Windows as build platform any time and nothing happen.
We need Windos only for build 64-bit Windows version of OW and for building some parts of Documentation which use Microsoft Help Compilers.

**Comment by jmalak** [comment]
Below is sample of batch file from my development box that you can study it.
There is my customization, by example I switch on some C compilers warnings which is disabled by default. There is commented out various configuration as use OW 1.9 compiler for build OW etc.
But all other is standard OW as it is in repository.
```
@echo off
REM *****************************************************************
REM SETVARS.BAT - Windows NT/DOS version
REM *****************************************************************
REM NOTE: Do not use this batch file directly, but copy it and
REM       modify it as necessary for your own use!!

REM Change this to point your Open Watcom source tree
set OWROOT=D:\dev\blb

REM Set this entry to identify your toolchain used by build process
REM supported values are WATCOM VISUALC INTEL
set OWTOOLS=VISUALC
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
REM set OWTOOLS=WATCOM
REM SET WATCOM=D:\dev\ow2017
REM SET PATH=%WATCOM%\BINNT;%WATCOM%\BINW;%PATH%
REM SET INCLUDE=%WATCOM%\H;%WATCOM%\H\NT;%WATCOM%\H\NT\DIRECTX;%WATCOM%\H\NT\DDK;%INCLUDE%
REM SET EDPATH=%WATCOM%\EDDAT
REM SET WHTMLHELP=%WATCOM%\BINNT\HELP
REM SET WIPFC=%WATCOM%\WIPFC

SET WCC=-wce=303 -wce=308 -wce=309 -wce=110
SET WCC386=-wce=303 -wce=308 -wce=309 -wce=110

REM Build control related variables
REM ###############################

REM Set this variable to 0 to suppress documentation build
set OWDOCBUILD=0

REM Set this variable to 1 to suppress tools GUI version build
REM If it is used then only tools character mode version is build
REM set OWGUINOBUILD=1

REM Set this variable to list of OW projects to suppress their build
REM Example set OWNOBUILD=ide browser dlgprs
REM set OWNOBUILD=

REM Documentation related variables
REM ###############################

REM Change this to the PATH required by GhostScript for PDF creation on used host OS (optional)
set OWGHOSTSCRIPTPATH=%OWROOT%\ci\ntx64

REM Change these variables to point Windows help compilers which you have installed
set OWWIN95HC=%OWROOT%\ci\nt386\hcrtf
set OWHHC=%OWROOT%\ci\nt386\hhc

if not '%OS%' == 'Windows_NT' goto common_setup
REM build process requires WGML utility which is available only as DOS executable
REM on Windows platforms which don't have NTVDM or if WGML doesn't work under NTVDM
REM DOSBOX emulator must be installed and OWDOSBOX variable must be set
REM It is necessary for all 64-bit Windows and Windows 7 32-bit
REM Uncoment and set OWDOSBOX variable bellow to point to DOSBOX emulator executable
REM path must not include any spaces

set OWDOSBOX=%OWROOT%\ci\nt386\dosbox.exe

:common_setup

REM ###############################

REM Subdirectory to be used for building OW build tools
set OWOBJDIR=vs64

REM DOS4GW 1.97 
set DOS4G=QUIET
REM DOS4GW 2.0x 
REM set DOS4G=STARTUPBANNER:1

REM Invoke the batch file for the common environment
call %OWROOT%\cmnvars.bat

REM Change the default command prompt
if not '%OS%' == 'Windows_NT' prompt $p$g

cd %OWROOT%

set OW_QNX_QLIB=1

```

**Comment by ideafarm** [comment]
Some of your criticisms of me are warranted, and I apologize and will improve.  I have more time now and intend to focus on getting OWv2 to build properly and then to focus on debugging the debugger and the compiler failures that I see regularly while building and debugging IPDOS (tm).  AFAIK from testing so far, your fork simply does not build correctly on a newly installed Windows 10 Pro system with the current version of Visual Studio Community.

I intend to keep ideafarm/open-watcom-v2 as nearly identical as possible with open-watcom/open-watcom-v2, making the minimum changes that are necessary to get it to work.  I will provide these changes to you via pull requests.  I will also attempt to discover why you are not seeing the errors.  You've said that you are using VS 2016; that might be the reason.

It is clear to me that you and I have different QA/QC approaches and different priorities.  That's more than OK; it is a good thing.  My policy will be to keep my fork as close as possible to yours while ensuring that my fork works flawlessly when hosted on Windows 10.

**Comment by jmalak** [comment]
Build system is OK, you use buggy tools and do incorrect local changes without understanding how it works.
I close this issue, because it is not real issue with OW, only your local issue.
