### ISSUE TITLE
Current OW build doesn't install in DOSbox

### ISSUE THREAD

**Issue by tbullock** [open-watcom/open-watcom-v2#592]
Running the installer inside a current dosbox doesn't function, the program complains it cannot run the DOS/4GW environment.

![image](https://user-images.githubusercontent.com/1172997/78135117-8fc1d400-73de-11ea-81ef-30922bcca6e6.png)

**Comment by jmalak** [comment]
Thanks for bug report. 
It is mistake that installer uses DOS4GW extender.
Installer must use bind Causeway extender.
I will fix it ASAP.

**Comment by jmalak** [comment]
It is fixed now in git repository.
Please download new version of DOS installer after midnight full build.

**Comment by tbullock** [comment]
Ok progress,

The installer launchers but crashes within 10-15 seconds of execution when the license dialogue is shown.

![image](https://user-images.githubusercontent.com/1172997/78242935-1e4a5a00-74a0-11ea-914d-a31f9bf66ac9.png)

Attached the causeway error dump as well.
[CW.zip](https://github.com/open-watcom/open-watcom-v2/files/4420588/CW.zip)

**Comment by jmalak** [comment]
Thanks. I will review it.

**Comment by jmalak** [comment]
It should be working again.
