### ISSUE TITLE
Open Watcom compiler with CMake "is not able to compile a simple test program".

### ISSUE THREAD

**Issue by volkertb** [open-watcom/open-watcom-v2#594]
Hi there. First of all, thanks for breathing new life into the Open Watcom compiler suite! 😃

Anyway, I'm trying to use the Open Watcom v2 16-bit DOS compiler in a CMake project in Linux. The reason why I'm using CMake is because this is required for proper integration with CLion, which I'd like to use for C development, since I have a preference working with JetBrains IDEs.

However, I can't get this to work. I've added the `-G "Watcom WMake"` parameter to tell CMake to use the Watcom WMake generator instead of the standard Unix Makefile generator. Also I've explicitly selected the 16-bit DOS `wcc` and `wpp`compiler variants in the compiler settings in the CLion project, as well as in the `CMakeLists.txt` file.

CLion then runs CMake on the project, which in turn tries to compile and run an auto-generated test as a sanity check on the toolchain, which consistently fails with the message `[..] is not able to compile a simple test program` and the following underlying errors:

```log
    Error! E1074: Invalid optimization option ''
    Error! E1073: Invalid option '-c'
    Error! E1139: Command line contains more than one file to compile
```

I've experienced this with today's daily snapshot (2020-04-12) on a Fedora 31 x86_64 Linux system, but I've written a Dockerfile that automatically reproduces the exact same problem in an Ubuntu 20.04 environment as well:

```Dockerfile
FROM ubuntu:20.04
RUN apt -y update
RUN apt -y install wget
WORKDIR /tmp
RUN wget https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.gz
RUN mkdir /opt/watcom
WORKDIR /opt/watcom
RUN tar -zxvf /tmp/ow-snapshot.tar.gz
RUN ls -lh

# The environment variables usually set by sourcing the owsetenv.sh provided by the installer.
ENV PATH /opt/watcom/binl:$PATH
ENV INCLUDE /opt/watcom/lh:$INCLUDE
ENV WATCOM /opt/watcom
ENV EDPATH /opt/watcom/eddat
ENV WIPFC /opt/watcom/wipfc

RUN which wcc

ARG DEBIAN_FRONTEND=noninteractive
RUN apt -y install cmake
RUN cmake --version

RUN rm /tmp/ow-snapshot.tar.gz

RUN mkdir -p /src/hello-world
WORKDIR /src/hello-world

RUN touch hello-world.c
RUN echo "#include <stdio.h>" >> hello-world.c
RUN echo "int main() {" >> hello-world.c
RUN echo "  printf(\"Hello, World!\");" >> hello-world.c
RUN echo "  return 0;" >> hello-world.c
RUN echo "}" >> hello-world.c
RUN cat hello-world.c

RUN touch CMakeLists.txt
RUN echo "cmake_minimum_required(VERSION 3.15)" >> CMakeLists.txt
RUN echo "project(hello-world)" >> CMakeLists.txt
RUN echo "set(CMAKE_C_STANDARD 99)" >> CMakeLists.txt
RUN echo "set(CMAKE_C_COMPILER \"/opt/watcom/binl/wcc\")" >> CMakeLists.txt
RUN echo "set(CMAKE_CXX_COMPILER \"/opt/watcom/binl/wpp\")" >> CMakeLists.txt
RUN echo "add_executable(hello.com hello-world.c)" >> CMakeLists.txt
RUN cat CMakeLists.txt

# This command ignores the CMAKE_C_COMPILER and CMAKE_CXX_COMPILER parameter set above and uses the 32-bit variants anyway, and fails *one* error: E1074.
#RUN cmake -DCMAKE_BUILD_TYPE=Debug -G "Watcom WMake" .

# This command forces the 16-bit C and C++ compiler variants, and fails with errors E1074, E1073 and E1139.
RUN cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/opt/watcom/binl/wcc -DCMAKE_CXX_COMPILER=/opt/watcom/binl/wpp -G "Watcom WMake" .

```

Am I doing anything wrong here, or is this a bug or limitation, either in CMake or in Open Watcom or any of its command-line executables?

Googling for this issue didn't yield anything resembling my problem, except for a mention on the Arch Linux wiki that CMake's generator for WMake wasn't yet supported on Linux. But from what I've read elsewhere, WMake support in native Linux was added to CMake later. Also, if that had been the case, I would expect CMake to explicitly tell me that the "Watcom WMake" generator wasn't available on my platform, right?

I'd really like to get into some retro DOS coding as a hobby, but I would like to do that with the creature comforts of a fully-featured modern IDE that I'm familiar with. I hope someone here can help me.

Regardless though: thank you, and a Happy Easter and/or Passover to those of you who celebrate it! ☺️

**Comment by jmalak** [comment]
Please do you have already working CMAKE with Open Watcom for any target or not?
Is your problem only with autodetection?
Are Open Watcom supported by CMake on your platform?
Could you give me sample make file generated by CMake if it is avvailable.

**Comment by jmalak** [comment]
Anyway I am not much familiare with CMake.
It looks like you need to create CMake configuration file yourself because in CMake only implicit configuration for Linux and Windows exists and is used.
as workaround you can try to add following command into CMake file
set(CMAKE_C_FLAGS "-bt=dos")
set(CMAKE_CXX_FLAGS "-bt=dos")
set(CMAKE_MODULE_LINKER_FLAGS "system dos")

**Comment by jmalak** [comment]
I install CMake on my test box and do little investigation of a problem.
It is due to missing cross-compile configuration for Open Watcom.
I will do some work to add missing cross-compilation configuration for Open Watcom into CMake.
I plan to add support to cross-compile on Linux and Windows host (32/64-bit) for targets DOS 16/32-bit, OS2 16/32-bit, Windows 32-bit and Linux 32-bit.
Without this configuration you need to create your own CMake script for each target manualy.

**Comment by claunia** [comment]
I used CLion and OpenWatcom extensively it would be really helpful to have this working.

**Comment by jmalak** [comment]
I am now i process of contribution to CMake to work as cross-compiler on Linux and Windows. It take some time.

**Comment by volkertb** [comment]
Thanks everyone, and sorry for the late reply!

In the meantime, I managed to get a bit further by configuring `owcc` as both the C and C++ compiler, combined with CMake's standard GNU Makefile generator. owcc is referred to in the manual (ctools.pdf) as the "Open Watcom C/C++ POSIX-like Compiler Driver".

Thanks again to the [Open Watcom page on the Arch Linux wiki](https://wiki.archlinux.org/index.php/Open_Watcom) for mentioning this option. I'm not even using Arch Linux, but that page has the best documentation on using Open Watcom in Linux that I've found anywhere on-line so far.

Sp basically, owcc (one of the compiler binaries provided with Open Watcom) provides "POSIX compatibility", meaning that it can be used with regular makefiles in Linux and other UNIX-like operating systems.

The good news is that this works well with CMake. The bad news is that it still doesn't properly work in CLion, since CLion is not able to collect compiler information from owcc. :disappointed: This results in IDE features such as code highlighting not working properly. I'll open a separate issue for this, since that's related to owcc and not WMake.

**Comment by volkertb** [comment]
Separate issue #596 created.

**Comment by jmalak** [comment]
Anyway it is rather discussion for CMake development forum then for OpenWatcom, because it is CMake tool problems. We can help you with OpenWatcom toolchain information or explanation of OpenWatcom functionality, but CMake tool must be fixed by CMake developpers to support appropriate features for OpenWatcom.

We shloud move this discussion to CMake development forum.
I think it is relevant for this problem.

**Comment by jmalak** [comment]
Today I submit several changes to CMake to support OpenWatcom cross-compilation to 16-bit and 32-bit DOS.
After passing all CMake procedure you can be able to use it for DOS target with OpenWatcom natively.

**Comment by jmalak** [comment]
CMake version 3.18 will have full native and cross-compilation support for Open Watcom.
CMake will support Open Watcom on Windows 32-bit/64-bit and Linux 32-bit/64-bit hosts.
Supported targets (native or cross-compiled) on all hosts will be
Windows 32-bit
Linux 32-bit
DOS 16-bit/32-bit
OS2 16-bit/32-bit

**Comment by jmalak** [comment]
Below is example how will use DOS target
16-bit
`cmake -G "Watcom WMake" -S ... -B ... -D CMAKE_SYSTEM_NAME:STRING=DOS -D CMAKE_SYSTEM_PROCESSOR:STRING=I86`
32-bit
`cmake -G "Watcom WMake" -S ... -B ... -D CMAKE_SYSTEM_NAME:STRING=DOS`

**Comment by jmalak** [comment]
Last CMake development version night build contains all changes necessary to cross-compile
from Linux to DOS, OS/2 and Windows NT
from Windows NT to DOS, OS/2 and Linux

**Comment by volkertb** [comment]
@jmalak @claunia

I've been banging my head trying to get this to work with CLion 2021.3 EAP.

Just getting it to work on the command line took me hours of finicking. To prevent others from spending so much time on this as well, I'm sharing another Dockerfile, this time one that verifies that this actually works, at least from the command line.

It installs CMake and Open Watcom (versions are configurable at the top of the file), cross-compiles a "Hello World" DOS executable and even runs it in [dosemu2](https://github.com/dosemu2/dosemu2) and checks the output.

This way, there is a reference of a "working configuration" that people can use as a basis for their own local configuration and project setup.

It might also be prove useful for regression testing.

```Dockerfile
FROM ubuntu:21.10

ARG CMAKE_VERSION_TO_TEST_WITH=3.18.0
ARG OPEN_WATCOM_BUILD_DATE_TO_TEST_WITH=2021-10-02

RUN apt -y update
RUN apt -y install wget
WORKDIR /tmp
RUN wget https://github.com/open-watcom/open-watcom-v2/releases/download/${OPEN_WATCOM_BUILD_DATE_TO_TEST_WITH}-Build/ow-snapshot.tar.gz
RUN mkdir /opt/watcom
WORKDIR /opt/watcom
RUN tar -zxvf /tmp/ow-snapshot.tar.gz
RUN ls -lh

# The environment variables usually set by sourcing the owsetenv.sh provided by the installer.
ENV PATH /opt/watcom/binl64:$PATH
ENV INCLUDE /opt/watcom/lh:$INCLUDE
ENV WATCOM /opt/watcom
ENV EDPATH /opt/watcom/eddat
ENV WIPFC /opt/watcom/wipfc

RUN which wcc

ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /tmp
RUN wget https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION_TO_TEST_WITH/cmake-$CMAKE_VERSION_TO_TEST_WITH-linux-x86_64.tar.gz
RUN tar -zxvf cmake-$CMAKE_VERSION_TO_TEST_WITH-linux-x86_64.tar.gz
# NOTE: in more recent versions of CMake, the `Linux` part of the directory name will no longer be capitalized, so update that accordingly. 
WORKDIR /tmp/cmake-$CMAKE_VERSION_TO_TEST_WITH-Linux-x86_64
RUN rm -rf man
RUN cp -rf * /usr/local
WORKDIR /tmp
RUN rm -rf ./cmake*
RUN cmake --version

RUN rm /tmp/ow-snapshot.tar.gz

RUN mkdir -p /src/hello-world
WORKDIR /src/hello-world

RUN touch hello-world.c
RUN echo "#include <stdio.h>" >> hello-world.c
RUN echo "int main() {" >> hello-world.c
RUN echo "  printf(\"Hello, World!\");" >> hello-world.c
RUN echo "  return 0;" >> hello-world.c
RUN echo "}" >> hello-world.c
RUN cat hello-world.c

RUN touch CMakeLists.txt
RUN echo "cmake_minimum_required(VERSION $CMAKE_VERSION_TO_TEST_WITH)" >> CMakeLists.txt
RUN echo "project(hello-world)" >> CMakeLists.txt
RUN echo "set(CMAKE_C_STANDARD 99)" >> CMakeLists.txt
# NOTE: don't append `.exe` or `.com` to the executable name. This will already be done automatically.
RUN echo "add_executable(hello hello-world.c)" >> CMakeLists.txt
RUN cat CMakeLists.txt

# Based on Jmalak's instructions in GitHub thread:
RUN cmake -G "Watcom WMake" -S . -B . -D CMAKE_SYSTEM_NAME=DOS -D CMAKE_SYSTEM_PROCESSOR=I86
RUN wmake all

# The following part is just to prove/test that the resulting MS-DOS executable is actually working.
RUN apt -y install software-properties-common
RUN add-apt-repository ppa:dosemu2/ppa
RUN apt update
RUN apt -y install dosemu2
RUN useradd -ms /bin/bash dosemu_user
RUN chown dosemu_user hello.exe
USER dosemu_user
RUN dosemu --version
RUN mkdir -p ~/.dosemu/drive_c/
RUN cp hello.exe ~/.dosemu/drive_c/
RUN dosemu -dumb -E "hello.exe > stdout.log"
RUN cp ~/.dosemu/drive_c/stdout.log /tmp
WORKDIR /tmp
RUN cat stdout.log
RUN echo "dffd6021bb2bd5b0af676290809ec3a53191dd81c7f70a4b28688a362182986f  stdout.log"|sha256sum -c - 
```
