### ISSUE TITLE
CLion cannot collect compiler information from owcc

### ISSUE THREAD

**Issue by volkertb** [open-watcom/open-watcom-v2#596]
The `owcc` executable in the Open Watcom suite is the "Open Watcom C/C++ POSIX-like Compiler
Driver", as the Open Watcom C/C++ Tools User’s Guide (ctools.pdf) describes it.

As I understand it, it's basically a wrapper that makes Open Watcom more compatible with the traditional software development toolchains in POSIX environments, such as GNU Make, etc.

owcc works well with CMake in combination with its default GNU Makefile generator in Linux. With owcc, WMake doesn't seem necessary for cross-platrform C/C++ development in Linux environments.

This is useful to me, since I've been trying to get Open Watcom to work with the CLion IDE from JetBrains. CLion supports only CMake projects.

Unfortunately, although I've got the CMake part working with owcc, CLion performs an additional step after building and testing the code with CMake, namely the "collection of compiler information". This works properly with the specific C/C++ compilers that CMake supports, namely GCC, Clang and I believe also the Microsoft compilers from Visual Studio in Windows environments.

As far as I could figure out, CLion performs this step to determine the default include paths of things like stdio.h, as well as the byte size of standard data types.

It seems like owcc is not sufficiently compatible with GCC and CLang.

the error that CLion shows in the console is this:

```
Cannot get compiler information:
	Compiler exited with error code 1: /opt/watcom/binl64/owcc -xc -bdos -fpch-preprocess -v -dD -E
```

By the way, the `-bdos` parameter was included by CLion here, because I specified it in `CMakeLists.txt` with the line `set(CMAKE_C_FLAGS "-bdos")`. If that line is omitted, it will not be included. But that doesn't matter w.r.t. the compiler information collection step, since owcc apparently fails with the other parameters as well.

owcc doesn't like the `-dD` parameter in particular. According to [the GCC manpage](https://linux.die.net/man/1/gcc), this parameter should do the following:

> Dump all macro definitions, at the end of preprocessing, in addition to normal output.

After I wrote a wrapper script that strips the `-dD` parameter from the response file that CLion supplies to the compiler when it tries to collect compiler information, it would still fail:

```
Problems were encountered while collecting compiler information:
	Unexpected compiler output. This compiler might be unsupported.
	If you are using GCC/Clang, please report the bug in https://youtrack.jetbrains.com/issues/CPP.
```

I don't think it's just the `-dD` parameter, though. I suspect that owcc currently doesn't properly process the other parameters from CLion, such as `-xc` and `-fpch-preprocess`, either. Or at least it doesn't result in the same behavior and console output that CLion is looking for.

Apparently, CLion assumes a high level of compatibility with GCC command-line parameters, although CLang appears to work fine with those same parameters. It seems that CLion has to implement custom support for any other compilers and toolchains. For instance, in the just very recently released version 2020.1 of CLion, support for the IAR Toolchain (a commercial product for embedded software development) was announced:

> If you use the IAR compiler/toolchain in your embedded projects, you can now do so in CLion. **Collecting compiler information no longer fails**, which means projects using the IAR toolchain load successfully and work in CLion.

(Emphasis mine)

By the way, so far I've tried this with versions `2019.3.5` and `2020.1` of CLion, with the same (failing) results.

So debugging this further (again, by writing a wrapper script and configuring it as the compiler executable), I discovered that CLion does the following under the hood when it tries to "collect the compiler information":

* It creates two temporary files, one `/tmp/response-file[RANDOM_NUMBER].txt` and the other `/tmp/compiler-file[A_DIFFERENT_RANDOM_NUMBER]` (with actual numbers in the place of those bracketed placeholders)
* It runs `owcc @/tmp/response-file[RANDOM_NUMBER].txt /tmp/compiler-file[A_DIFFERENT_RANDOM_NUMBER]` (with the numeric parts differing on each invocation, likely the current timestamp)
* CLion deletes those temporary files (I used the wrapper script to copy them to another location for analysis)

The response file is a standard mechanism for providing a higher number of arguments than the current platform may support on the command-line. The file contains the following parameters:

```
-xc -bdos -fpch-preprocess -v -dD -E -D___CIDR_DEFINITIONS_END
```

Again, the `-bdos` argument (for cross-compiling 16-bit DOS code) will only be there if specified as a custom C compiler parameter in the CMake lists file. The compiler information collection will fail eitherway.

The source file it feeds to the compiler as the second argument has the following contents:

[compiler-file.txt](https://github.com/open-watcom/open-watcom-v2/files/4496899/compiler-file.txt)

The response that owcc throws out on the console is the following:

```
Result:
Error! E1073: Invalid option '-xc'
Error! E1073: Invalid option '-bdos'
Error! E1073: Invalid option '-fpch'
Error! E1073: Invalid option '-preprocess'
Error! E1147: Too many errors: compilation aborted
Error: Compiler returned a bad status compiling '@/tmp/response-file510283241670491082.txt'
Error! Unable to open '/tmp/compiler-file16295087320389008726.c'
Error: Compiler returned a bad status compiling '/tmp/compiler-file16295087320389008726'
```

As you can see, owcc suffixed a `.c` extension to the compiler-file without asking.

Strangely enough, the owcc compiler would return an exit code 0 here, causing CLion to simply complain about unexpected compiler output, instead of showing the actual errors. (I made the wrapper script log this to a separate file, to get these erors.)

Also, equally weirdly, owcc is complaining about the `-bdos` parameter here, which it most definitely should support.

After enhancing the wrapper script to automatically create a symlink to the compiler-file with the same name, but with the .c extension, the compiler would instead complain about the file not containing proper C code.

Long story short, owcc doesn't support the collection of compiler information in the way that CLion attempts it, which apparently does work well with gcc and clang.

As a result of this step failing, CLion is unable to determine things like include path resolution, which results in errors in the IDE like this:

![Screenshot from 2020-04-18 17-30-27](https://user-images.githubusercontent.com/518023/79641876-7cfb1d80-819a-11ea-8321-da43b568deed.png)

Proper code highlighting and contextual support are exactly the reason why I wanted to use CLion in the first place. :disappointed:

Is this a known issue? And how easy would this be to fix? So that owcc would correctly process these parameters and input files that CLion supplies when it tries to collect compiler information from it, and then respond with the output that CLion would expect and would need to correctly configure the project?

Thank you for the hard work you've been doing to maintain Open Watcom for all us hobbyists and legacy software developers! :slightly_smiling_face:

**Comment by jmalak** [comment]
Take into acount that owcc is driver which emulate posix-like command line not all feature.
OW is natively cross-compiler and is rather similar to clang native mode then gcc or gcc-emulation.
But this cross-compile features are not based on any prefix or suffix for some path.
Also not all options behave the same way as in gcc or clang, OW uses totaly different aproach.
If CLion has some expectation you must specify what is realy sending to owcc and what is expected to get back. Without these info I can not do anything.

**Comment by jmalak** [comment]
only way to use OW with CMake is real cross-compile stuff for OW in CMake.
CLion must use OW possibility not gcc or clang if want to get any info.
It is something like you want to use Visual studio by gcc or clang stuff, it is simply impossible.

**Comment by jmalak** [comment]
anyway command line like
`-xc -bdos -fpch-preprocess -v -dD -E -D___CIDR_DEFINITIONS_END`
is wrong because owcc use POSIX rules that correct should be
`-x c -b dos -f pch-preprocess -v -d D -E -D ___CIDR_DEFINITIONS_END`

**Comment by volkertb** [comment]
> Also not all options behave the same way as in gcc or clang, OW uses totaly different aproach.

That's what I was afraid of.

> If CLion has some expectation you must specify what is realy sending to owcc and what is expected to get back.

I can try to save a dump  of what gcc and clang send back when CLion queries those compilers for compiler information like it tries to do with owcc.

> Is CLion communication with OW directly or only with CMake?

So CLion appears to be performing two steps here. The first step is to tell CMake to compile a test program, to make sure the toolchain is sane. That was the part that failed when I tried to use the WMake generator of CMake, which led me t open issue #594. With owcc and the default generator (instead of wcc and the WMake generator), this part succeeds.

The second step is the "collecting of compiler information", which CLion attempts by sending the compiler some parameters and input directly (apparently without going through CMake) and by parsing the output it gets bvack from the compiler. This is the part that fails here, since owcc does not accept all the parameters/arguments that CLion sends to it.

> We have no plan to follow clang or gcc any way. OW is independent and has no sense to do anything like gcc or clang that you can not relate to any internal gcc and clang features.

Looks like there's no easy solution to get owcc working seamlessly with CLion, then. :disappointed: 

> anyway command line like
> `-xc -bdos -fpch-preprocess -v -dD -E -D___CIDR_DEFINITIONS_END`
> is wrong because owcc uses POSIX rules that correct should be
> `-x c -b dos -f pch-preprocess -v -d D -E -D ___CIDR_DEFINITIONS_END`

I tried that, but it still complains about `Invalid option 'd'`. And even when I remove the `-d D` part, it doesn't seem to process the other parameters as intended either.

**Comment by jmalak** [comment]
I think all misunderstanding is that owcc is gcc emulator. No it is wrong expectation.
owcc is POSIX cc compatible. If CMake and CLion support POSIX cc then it could work.
You can not relate to gcc or clang compiler feature because owcc is not emulator of them.

**Comment by jmalak** [comment]
Anyway owcc doesn't support -d option (non-POSIX) that the message is correct.
options supported by owcc and syntax can be displayed by command `owcc -?`

**Comment by claunia** [comment]
@jmalak should it be possible to make owcc accept the parameters and generate the output clion sends/expect as gcc and clang do?

**Comment by jmalak** [comment]
I think it is CMake functionality that CMake must support this for OW toolchain.
We don't plan to do any emulation for gcc or clang features. 
If CLion use CMake then it is about CMake support for OW toolchain and it requires to use OW tools possibility not over gcc or clang emulation. We don't want to develop another gcc or clang clone.
It is necessary to know what CMake features is used by CLion to be able implement it in CMake for OW toolchain.

**Comment by jmalak** [comment]
Anyway it is rather discussion for CMake development forum then for OpenWatcom, because it is CMake tool problems. We can help you with OpenWatcom toolchain information or explanation of OpenWatcom functionality, but CMake tool must be fixed by CMake developpers to support appropriate features for OpenWatcom.

**Comment by jmalak** [comment]
We shloud move this discussion to CMake development forum.
I think it is relevant for this problem.

**Comment by volkertb** [comment]
No, this part is not CMake-related. It's the "collecting compiler information" phase in which CLion tries to invoke the compiler correctly.

**Comment by jmalak** [comment]
In this case it is problem of CLion not OW, CLion expect something what is not true.
What is problem exactly, what is wrong with C/C++ compiler?
You say that OW is wrong, but not specify what is wrong exactly.

**Comment by volkertb** [comment]
I guess I was hoping that the command-line arguments and compiler outputs that CLion's "collecting compiler information" depended on would all be standard generic POSIX compiler behavior. Apparently that's not the case.

Indeed, this probably means that CLion would have to add specific support for the Open Watcom compiler. If only there were a more standardized way for IDEs to interact with compilers to query their functionality and platform-dependent properties. :disappointed: 

I guess there's not much else to do that to open a feature request at JetBrains for adding Open Watcom (or at least owcc) support to CLion.

Does anybody else here have any suggestions? Perhaps for some kind of workaround? Or shall I just close this issue, then?

**Comment by volkertb** [comment]
Hmmm... This guy has been working on a workaround for a similar problem with another unsupported compiler: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003275680-How-to-make-CLion-recognise-my-fake-compiler-in-compilation-database-

Apparently he wasn't successful yet, but maybe his work could form a basis for a more generic solution that could eventually perhaps also benefit Open Watcom.

Anyway, that's outside the scope of this issue, which indeed is not the responsibility of the Open Watcom developers to solve. So I'm closing this issue.

Nevertheless, thanks for all your feedback and clarifications!

**Comment by jmalak** [comment]
CMake has some support for compilers feature. If it is used by CLion then it could be fixed by adding this feature support for OW to CMake. 
I think it is not only problem with compilers it could be a problem with debugger too.
CLion support only GDB and LLDB, that it can not works with OW debugger.
You should use some debugger format used by supported Debuggers. OW support Dwarf V2 and CodeView V4 which could be compatible with some supported debuggers, but I am not sure how these debuggers refere to GNU specific things etc.

**Comment by volkertb** [comment]
Debugger support would be a nice second step, but to begin with, I would like to have a functional IDE with working code highlighting, auto-completion and basic refactoring (renaming, etc) working. But yeah, a standardized cross-platform and vendor-independent way to determine compiler and debugging features would be the key here.

I wonder why CLion doesn't use CMake for collecting the necessary "compiler information". Apparently CMake's functionality in that regard is inadequate.

I don't have experience with other modern popular cross-platform C/C++ IDEs. Do any of you know how those handle this? And how well those work with Open Watcom? I mean IDEs like Eclipse, NetBeans, Visual Studio Code, etc?

**Comment by volkertb** [comment]
Cool! I was thinking about opening an issue in JetBrains YouTrack, but you beat me to it, @jmalak . Good job. :sweat_smile: 

https://youtrack.jetbrains.com/issue/CPP-20108

**Comment by volkertb** [comment]
@jmalak Perhaps you could also upvote this issue? Thanks. :slightly_smiling_face:  https://youtrack.jetbrains.com/issue/CPP-20109

**Comment by jmalak** [comment]
I think that the main problem is with multi-platform and cross-platfom difference.
Most of such tools are only multi-platform for host not for target. pure cros-platform tools requires remote debugging for toolchain. OW is very different than GNU like tools. OW is by nature cross-platform and don't need similar configuration/installation as GNU tools with some prefixes and suffixes. Only OW compilers is one architecture that you need call correct compiler for architecture , but all is available on all host system by default. librarian, linker and other tools supports all platforms by nature. OW can be switch by a few environment variables to any supported target. All OW tools are native doesn't require any emulation of POSIX layer or UNIX like environment as by example CygWin etc.

**Comment by claunia** [comment]
Wouldn't just this fix the problem?:

```patch
diff --git a/bld/wcl/c/owcc.c b/bld/wcl/c/owcc.c
index 3552391c3..cac13dc0d 100644
--- a/bld/wcl/c/owcc.c
+++ b/bld/wcl/c/owcc.c
@@ -684,11 +684,11 @@ static  int  ParseArgs( int argc, char **argv )
     AltOptChar = '-'; /* Suppress '/' as option herald */
     while( (i = GetOpt( &argc, argv,
 #if 0
-                        "b:Cc::D:Ef:g::"
+                        "b:Cc::dD:Ef:g::"
                         "HI:i::L:l:M::m:"
                         "O::o:P::QSs::U:vW::wx:yz::",
 #else
-                        "b:CcD:Ef:g::"
+                        "b:CcdD:Ef:g::"
                         "HI:i::L:l:M::m:"
                         "O::o:P::QSs::U:vW::wx::yz::",
 #endif
```

Just ignoring the -dD suffices to make CLion relatively happy.

**Comment by claunia** [comment]
Not wanting to resurrect a zombie but:
https://blog.jetbrains.com/clion/2021/10/clion-2021-3-eap-custom-compiler/

and a first try, can be made better, here:
https://github.com/JetBrains/clion-custom-defined-compiler-examples/issues/2

**Comment by volkertb** [comment]
Good to see that this feature will finally be included in Clion 2021.3. :relaxed:

And thanks for creating Open Watcom yaml files for it, @claunia!

I'll try some of them out, and I'll share my findings with you.

**Comment by volkertb** [comment]
@jmalak Oh, sorry, forget my previous comment. You already fixed CMake and WMake to be able to work together for cross-compiling DOS executables from Linux, a while back. as you mentioned [here](https://github.com/open-watcom/open-watcom-v2/issues/594#issuecomment-625777287).

Looks like the Arch Linux wiki is just not updated with this new information yet.

So I have it working with CMake on the command-line now. It's just that I keep getting errors when I want to get this working in CLion 2021.3 EAP (Early Access Preview) as well. @claunia already got it working.

**Comment by jmalak** [comment]
OK. I will add page to OW Wiki with simple description of using OW with CMake for cross-compilation, to be useful for other OW users.

**Comment by volkertb** [comment]
@claunia Can you maybe share with us exactly what you have configured in `Build, Execution, Deployment -> Toolchains`?

It seems that whatever I specify, I always get a warning icon with the message "Test CMake finished with errors", with a "more..." link I could click on, which would lead to an console log with errors that don't seem to show a clear cause.

What values did you enter for the following:

- `Make:`
- `C Compiler:`
- `C++ Compiler:`

Additoinally, did you configure any environment variables anywhere in CLion? (`WATCOM`, `INCLUDE`, additions to the `PATH`, etc)?

Also, with `-G "Unix Makefiles" -DCMAKE_SYSTEM_NAME=DOS` you are using the Unix Makefile generator as opposed to the (Open) Watcom Wmake generator. And you're using it with `wcc` and `wpp`, seemingly? I never got that to work.

At least from the command-line, either I could make it work with the WMake generator combined with `wcc` and `wpp`, or with the Unix Makefile generator combined with `owcc`.

But in CLion, so far, I've gotten neither of the two to work.

Your help is appreciated!

**Comment by claunia** [comment]
Yeah this has nothing to do with CLion:
```
claunia@zeus ~/Development/Aaru/fstester/setter $ cmake -DCMAKE_C_COMPILER=/opt/watcom/binl64/wcc -DCMAKE_CXX_COMPILER=/opt/watcom/binl64/wpp .
CMake Deprecation Warning at CMakeLists.txt:25 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is OpenWatcom 2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /opt/watcom/binl64/wcc
-- Check for working C compiler: /opt/watcom/binl64/wcc - broken
CMake Error at /usr/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/opt/watcom/binl64/wcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/claunia/Development/Aaru/fstester/setter/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_d4f5b/fast && /usr/bin/make  -f CMakeFiles/cmTC_d4f5b.dir/build.make CMakeFiles/cmTC_d4f5b.dir/build
    make[1]: se entra en el directorio '/home/claunia/Development/Aaru/fstester/setter/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_d4f5b.dir/testCCompiler.c.o
    /opt/watcom/binl64/wcc -zq -d+   -w3 -bt=linux  -d2 -foCMakeFiles/cmTC_d4f5b.dir/testCCompiler.c.o -c -cc /home/claunia/Development/Aaru/fstester/setter/CMakeFiles/CMakeTmp/testCCompiler.c
    Error! E1073: Invalid option '-c'
    Error! E1073: Invalid option '-cc'
    make[1]: *** [CMakeFiles/cmTC_d4f5b.dir/build.make:78: CMakeFiles/cmTC_d4f5b.dir/testCCompiler.c.o] Error 1
    make[1]: se sale del directorio '/home/claunia/Development/Aaru/fstester/setter/CMakeFiles/CMakeTmp'
    make: *** [Makefile:127: cmTC_d4f5b/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:27 (project)


-- Configuring incomplete, errors occurred!
See also "/home/claunia/Development/Aaru/fstester/setter/CMakeFiles/CMakeOutput.log".
See also "/home/claunia/Development/Aaru/fstester/setter/CMakeFiles/CMakeError.log".
```

**Comment by jmalak** [comment]
Please don't setup compiler executable. I don't understand why you want to do this, it is the source of problems?

**Comment by claunia** [comment]
You MUST setup the compiler because if you leave it empty, CLion still sets it up to a default, and fails.

What works when cmake is invoked alone doesn't necessarily work when cmake is invoked by clion.
If we remove the environment variables from CLion configuration things break: `Warning! W1115: system block dos: environment name WATCOM not found`.

With those instructions everything I tested works perfectly, and the only things missing are:
- How to tell CMake to compile 16-bit Windows (I have not even tried it).
- How to tell CMake to compile NetWare (doesn't seem to be a Novell-OpenWatcom.cmake file).
- How to compile QNX, Alpha, MIPS or PowerPC at all (I know C libraries are missing but people may want to compile without it).

**Comment by volkertb** [comment]
Yeah, I initially missed the system-wide PATH step. It wasn't until after I figured that out that I noticed that at the top of your instructions.

By the way, it wasn't my test that failed. It's the sanity test that CLion performs automatically whenever you configure a toolchain.  It's just the sanity test that fails, though. Other than that, everything works fine.

Aren't you getting the same error?

See this screenshot, particularly the error right below the `C++ Compiler:` field:

![Screenshot from 2021-10-19 23-59-40](https://user-images.githubusercontent.com/518023/137996740-8055776e-b0c0-4da1-98a0-1e30fd46f2ae.png)

And when you click on `more...`, this is the error log that is shown:

```
  The C compiler

    "/opt/watcom/binl64/wcl"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /tmp/cmake_check_environment/_build16533429417646465354/CMakeFiles/CMakeTmp
    
    Run Build Command(s):wmake -f Makefile cmTC_a7dae/fast && Open Watcom Make Version 2.0 beta Oct 17 2021 00:52:40 (64-bit)
    Copyright (c) 2002-2021 The Open Watcom Contributors. All Rights Reserved.
    Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
    Source code is available under the Sybase Open Watcom Public License.
    See http://www.openwatcom.org/ for details.
    Makefile(6): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(9): Error(E21): Extension(s) (.NOTPARALLEL) not defined
    Makefile(18): Warning(W18): Unrecognized or out of place character ','
    Makefile(24): Warning(W18): Unrecognized or out of place character ','
    Makefile(38): Warning(W18): Unrecognized or out of place character '='
    Makefile(45): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(75): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(79): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(85): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(89): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(96): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(101): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(105): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(110): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(115): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(123): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(128): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(131): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(136): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(139): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(144): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(147): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(152): Error(E21): Extension(s) (.PHONY) not defined
    Makefile(165): Error(E21): Extension(s) (.PHONY) not defined
    Error(E02): Make execution terminated
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "/tmp/cmake_check_environment/_build16533429417646465354/CMakeFiles/CMakeOutput.log".
See also "/tmp/cmake_check_environment/_build16533429417646465354/CMakeFiles/CMakeError.log".

Error code: 1
```

**Comment by volkertb** [comment]
If you mean the `CMake options:` under `Build, Execution, Deployment > CMake`: yes. I have that set to `-DCMAKE_SYSTEM_NAME=DOS -DCMAKE_SYSTEM_PROCESSOR=I86 -G "Watcom WMake"`, as you instructed, and my project doesn't build without it.

But the "single test program" that is generated and (re)run whenever I change anything in `Build, Execution, Deployment > Toolchains` is apparently still being built with the default (non-wmake) generator. Did you specify an environment file in the toolchain? I've left that field empty.

**Comment by claunia** [comment]
No, I didn't, and neither did I set up wmake for CLion, that's only needed in Windows where there's no default make:

![image](https://user-images.githubusercontent.com/1234569/137999735-d64c7e32-b064-47c0-bab1-09be3cf8dc58.png)
![image](https://user-images.githubusercontent.com/1234569/137999861-b93b24dd-09ef-41c7-a0c4-5d3ddb5b03ce.png)

Possibly CLion is trying to do something with make, even if it's not used, CMake knows it needs to call wmake.

**Comment by volkertb** [comment]
That's it! Leaving the `Make:` field empty in the Toolchain configuration made the error disappear for me as well.

Thanks again! :slightly_smiling_face:

**Comment by claunia** [comment]
Enjoy your DOS coding!

**Comment by jmalak** [comment]
I have a few notes to existing definitions for OW.
Do you use it only for OW 2 or for older version?

| Open Watcom Version | `__WATCOMC__` Macro Value |
| --- | --- |
| 2.0 | 1300 |
| 1.9 | 1290 |
| 1.8 | 1280 |
| ... | ... |

Next is for class of macros `__WINDOWS__` and  `__WINDOWS_386__`
Both are for application hosted by 16-bit Windows 3.x.
OW has 32-bit Extender for 16-bit Windows 3.x that you can compile 32-bit application.
For OW 32-bit extender is defined `__WINDOWS_386__` macro.
Don't mix with Win32s product which emulate WIN32 API on 16-bit Windows.
`__WINDOWS__` macro is defined by OW for both pure 16-bit Windows 3.x code or for OW 32-bit Extender code.
Replace all ocurence of `__WINDOWS_386__` in your definitions by proper `__NT_386__` macro.

**Comment by jmalak** [comment]
I think so that definition for OW 2.0 or OW 1.9 has sense.
It can be the same because no significant change in options etc.
Generaly OW control target OS by -bt or -bcl or -l.
Each OS can be identified by simple macro

| target OS | OW` Macro |
| --- | --- |
| DOS | `__DOS__` |
| WIndows 3.x | `__WINDOWS__` |
| WIN32 platforms | `__NT__` |
| OS/2 | `__OS2__` |
| Linux | `__LINUX__` |
| Netware Novel | `__NETWARE__` |

For Architecture it define following macros.

| target Architecture | OW` Macro | Alternative Macros |
| --- | --- | --- |
| 16-bit Intel | `_M_I86` | `__I86__` |
| 32-bit Intel | `_M_I386` | `__386__` |
| Alpha | `__AXP__` |  `__ALPHA__` `_M_ALPHA` |
| PowerPC | `__PPC__` |  `_M_PPC` `__POWERPC__` |
| Mips | `__MIPS__` |  `_M_MRX000` |

Each of OS macros has variants for 32-bit architecture if it has sense. 

| target OS | Intel | Alpha | PowerPC | Mips |
| --- | --- | --- | --- | --- |
| DOS | | | | |
| WIndows 3.x | `__WINDOWS_386__` | | | |
| WIN32 | `__NT_386__` | `__NT_AXP__` | `__NT_PPC__` | `__NT_MIPS__` |
| OS/2 | `__OS2_386__` | | `__OS2_PPC__` | |
| Linux | `__LINUX_386__` | `__LINUX_AXP__` | `__LINUX_PPC__` | `__LINUX_MIPS__` |
| Netware Novel | `__NETWARE_386__` | | | |

It is currently preferred macros (ISO compliant names), but there exists also some old non-ISO compliant versions without leading underscore. These old macros exist for backward compatibility and can be switch off by -zam compiler option.
For OS and Architecture related macros it is:
`M_I86` `M_I386` `M_ALPHA` `M_PPC`

**Comment by madebr** [comment]
If anybody is interested, this is how I configured Watcom inside CLion.
I used an [env script for this](https://www.jetbrains.com/help/clion/how-to-create-toolchain-in-clion.html#env-scripts).
Combined with a CMake toolchain file, this does everything I want.

![image](https://user-images.githubusercontent.com/4138939/181912984-66fbe20b-8c83-4cd1-acf2-23856ad300bd.png)

For targeting Watcom OS/2, the env script looks like:
```sh
#!/bin/bassh

envfile="$BASH_SOURCE"
WATCOM_TOOLCHAIN_DIR="$(dirname "$(realpath "$envfile")")"

export WATCOM=~/owatcom2

export EDPATH="$WATCOM/eddat"
export WIPFC="$WATCOM/wipfc"

export INCLUDE="$WATCOM/h:$WATCOM/h/os2"
export PATH="$WATCOM/binl:$PATH"

export CC=wcl386
export CXX=wcl386

export CMAKE_TOOLCHAIN_FILE="$WATCOM_TOOLCHAIN_DIR/watcom-os2.cmake"
```

The corresponding CMake toolchain file looks like:
```cmake
set(WATCOM 1)
set(OS2 1)
set(CMAKE_SYSTEM_NAME "OS2")

set(WATCOM_ROOT CACHE PATH "$ENV{WATCOM}" "Root of Watcom compiler")
mark_as_advanced(WATCOM_ROOT)
if(NOT WATCOM_ROOT)
    message(FATAL_ERROR "WATCOM environment variable not set (saved in WATCOM_ROOT CMake variable)")
endif()

list(APPEND CMAKE_INCLUDE_PATH "${WATCOM_ROOT}/h;${WATCOM_ROOT}/h/os2")
list(APPEND CMAKE_LIBRARY_PATH "${WATCOM_ROOT}/lib386;${WATCOM_ROOT}/lib386/os2")

# search for programs in the build host directories
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

if(OVERRIDE_FIND_ROOT_PATH_MODE OR "$ENV{OVERRIDE_FIND_ROOT_PATH_MODE}")
    set(_OVERRIDE_FIND_ROOT_PATH_MODE BOTH)
else()
    set(_OVERRIDE_FIND_ROOT_PATH_MODE ONLY)
endif()
# for libraries and headers in the target directories
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ${_OVERRIDE_FIND_ROOT_PATH_MODE})
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${_OVERRIDE_FIND_ROOT_PATH_MODE})
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ${_OVERRIDE_FIND_ROOT_PATH_MODE})
```

Using the above files, for each CMake project I simply need to point to the Watcom toolchain:
![image](https://user-images.githubusercontent.com/4138939/181912590-a1781ceb-3d19-4c49-9063-f68782e391c9.png)
