### ISSUE TITLE
New Error with OW Editor

### ISSUE THREAD

**Issue by watfor-mike** [open-watcom/open-watcom-v2#597]
OW was working yesterday, but today an error in the IDE has occurred in both C and Fortran projects;

        Unable to connect to editor

Double clicking files .for or .cpp files in explorer also does not work.

Uninstalled and reinstalled version working yesterday, error persists.
Uninstallled and installed latest build downloaded today, error persists.
Uninstalled and reinstalled version working yesterday again, error persists.

IDE compiles and runs source.

OW V2  64 bit Mar 27, 2020 01:15:08

Hardware Dell Precision M4600
RAM 8.00 GB
Intel Core i&-2860QM CPU @ 2.50 GHz

OS Win 10  pro  
Version  1903
OS Build  18362.778

**Comment by jmalak** [comment]
It looks like problem with DDE between IDE and viw editor.
There is configuration of DLL, that it could be damaged somehow.
In IDE go to menu File -> Set Text Editor ... -> there should be setup weditviw and type should be DDL.

**Comment by jmalak** [comment]
I tried download latest OW build from 2-nd May and install it on My Windows 10 and it works OK with fortran and c++ source files. 
Problem could be damaged configuration file for viw editor. 
Try delete file weditor.ini in C:\Users\..your profile name ..\AppData\Roaming\Open Watcom.
The file will be recreated during next start of viw.

**Comment by watfor-mike** [comment]
Deleting the uni file corrected the issue.

Thanks for the unbelievely quick and correct info.😀😀😀
On Saturday, May 2, 2020 Jiří Malák <reply@reply.github.com> wrote:



I tried download latest OW build from 2-nd May and install it on My Windows 10 and it works OK with fortran and c++ source files.
Problem could be damaged configuration file for viw editor.
Try delete file weditor.ini in C:\Users..your profile name ..\AppData\Roaming\Open Watcom.
The file will be recreated during next start of viw.

**Comment by jmalak** [comment]
Good news that it is resolved.
You have a lucky that I am on-line just now. Normaly I response in one or two days.
