### ISSUE TITLE
Error! Cannot find file

### ISSUE THREAD

**Issue by jwinarske** [open-watcom/open-watcom-v2#599]
I'm hitting this on Linux 64.  Win 64 is fine.

```
 wlib -c -n -b libpdcurses.a CMakeFiles/os2_pdcursesstatic.dir/pdcclip.c.o CMakeFiles/os2_pdcursesstatic.dir/pdcdisp.c.o CMakeFiles/os2_pdcursesstatic.dir/pdcgetsc.c.o CMakeFiles/os2_pdcursesstatic.dir/pdckbd.c.o CMakeFiles/os2_pdcursesstatic.dir/pdcscrn.c.o CMakeFiles/os2_pdcursesstatic.dir/pdcsetsc.c.o CMakeFiles/os2_pdcursesstatic.dir/pdcutil.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/addch.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/addchstr.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/addstr.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/attr.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/beep.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/bkgd.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/border.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/clear.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/color.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/debug.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/delch.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/deleteln.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/getch.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/getstr.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/getyx.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/inch.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/inchstr.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/initscr.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/inopts.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/insch.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/insstr.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/instr.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/kernel.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/keyname.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/mouse.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/move.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/outopts.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/overlay.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/pad.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/panel.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/printw.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/refresh.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/scanw.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/scr_dump.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/scroll.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/slk.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/termattr.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/touch.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/util.c.o CMakeFiles/os2_pdcursesstatic.dir/__/pdcurses/window.c.o
Open Watcom Library Manager Version 2.0 beta May 17 2020 00:21:59 (32-bit)
Copyright (c) 2002-2020 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
Error! Cannot find file 'CMakeFiles/os2_pdcursesstatic.dir/pdcclip.c.o'
```
The file is there.
```
 ls -la CMakeFiles/os2_pdcursesstatic.dir/pdcclip.c.o
-rw-r--r-- 1 joel joel 1979 May 17 10:05 CMakeFiles/os2_pdcursesstatic.dir/pdcclip.c.o
```

Also what happened to the date?

**Comment by jmalak** [comment]
What version of cmake you are using?
How you have configured OpenWatcom in CMake?
Is it possible to get build example or reference to more details about hoe to build?
I need to identify source of problem. If it is command line issue or object name issue.
Anyway do you tested it with OW 1.9? What is result?

**Comment by jwinarske** [comment]
cmake version 3.17.2

I'm working out of this branch: https://github.com/jwinarske/PDCurses/tree/joWi_watcom_fixes

Let me know if you want the cmake command line I'm using.

Things broke a while back with 1.9 and 2.0.  This is the error for that:
```
[ 75%] Linking C executable ptest.exe
cd C:\projects\pdcurses\build\dos
wlink   system dos name ptest.exe  debug watcom all file {'CMakeFiles\dos_ptest.dir\__\demos\ptest.c.obj' }  librarypdcursesstatic.lib
Open Watcom Linker Version 1.9
Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
Error! E3033: directive error near 'librarypdcursesstatic.lib'
Error(E42): Last command making (dos\ptest.exe) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (dos\CMakeFiles\dos_ptest.dir\all) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (all) returned a bad status
Error(E02): Make execution terminated

```

**Comment by jmalak** [comment]
I push correction of CMake OW configuration.
Main problem is incorrect OS target options for C/C++ compilers.
Anyway latest development version of CMake has full cross-compilation support for OW.
It will be available in CMake 3.18.

**Comment by jmalak** [comment]
Below are cross-compilation commands fro CMake 3.18 (run on Linux or Windows, suppose configured OW for host, PATH, INCLUDE and WATCOM environment variables)

16-bit DOS cmake command
cmake -G "Watcom WMake" -S <src dir> -B <bin dir> -D CMAKE_SYSTEM_NAME=DOS -D CMAKE_SYSTEM_PROCESSOR=I86

32-bit DOS cmake command
cmake -G "Watcom WMake" -S <src dir> -B <bin dir> -D CMAKE_SYSTEM_NAME=DOS

16-bit OS2 cmake command
cmake -G "Watcom WMake" -S <src dir> -B <bin dir> -D CMAKE_SYSTEM_NAME=OS2 -D CMAKE_SYSTEM_PROCESSOR=I86

32-bit OS2 cmake command
cmake -G "Watcom WMake" -S <src dir> -B <bin dir> -D CMAKE_SYSTEM_NAME=OS2

**Comment by jmalak** [comment]
Please check your build and note me about results.

**Comment by jmalak** [comment]
I tested it with cross-compilation support in nightly-build CMake and it works.
But your CMake configuration files need to be more changed, because the existing CMake OW support is only for Windows, that most of parameters must be overwrite not append.

**Comment by jwinarske** [comment]
That fixed the issue.  The linking problem still exists.

Is this what you're referring to?

`string(APPEND LINK_LIBRARIES_PATH "${WATCOM_TOOLCHAIN_DIR}/lib386;${WATCOM_TOOLCHAIN_DIR}/lib386/dos")`

-to- 

`set(LINK_LIBRARIES_PATH "${WATCOM_TOOLCHAIN_DIR}/lib386;${WATCOM_TOOLCHAIN_DIR}/lib386/dos")`

**Comment by jmalak** [comment]
I added next fix. I hope it resolve issue.
I cannot test fully because I can not connect to SDL site.
[patch-2](https://github.com/Bill-Gray/PDCurses/pull/125)

**Comment by jwinarske** [comment]
@jmalak Can you point me to the CI logs where it's passing?  I just tried your recent change and it's failing to id the compiler.  https://ci.appveyor.com/project/jwinarske/pdcurses-21dj3

**Comment by jmalak** [comment]
Sorry I test it on my box by CMake, I am not able to test it on Appveyor.

Anyway main problem is that you have not configured OW for host OS (Windows), but for target OS (DOS or OS2).
It is necessary to configure OW for Windows or Linux host. Appropriate setup for target is in CMake TOOLCHAIN files.

**Comment by jmalak** [comment]
The problem is that I use CMake 3.17.2 which support DOS and OS/2 targets.
But your CMake 3.16.2 doesn't.

I modified CMake files to be working on older versions of CMake.

**Comment by jwinarske** [comment]
If I remove set(CMAKE_SYSTEM_NAME OS2) from latest patch, and specify the compiler either via CC variable, or hard code it, it fails at linking.  Then link fails with same error I mentioned at the start of this issue.  These scripts worked fine two years ago when I originally wrote them.  Something changed with the compiler, which is why I opened the issue.

**Comment by jmalak** [comment]
Just now.

**Comment by jmalak** [comment]
The same happen on OW 1.9 and it was not changed for years.
it is evident configuration issue.

The problem is probably with cmake auto detection feature.
It will require completely manual setup of OW and suppress any CMake intervention.

OW must be always fully setup to target platform with regards to host then it will works.
It is stupid that CMake is not capable to use cross-compile nature of OW.

I will rework CMake scripts completely to be one per each host and each target and each architecture then it will works.

**Comment by jmalak** [comment]
I submit next fix for file extensions, now properly use .exe for executable and .lib for static libraries.
Missing extension for executable caused reported problem with "file not found" even if file was created .
OW use default extension for executable with .exe suffix, but wmake worked with file name without extension.

**Comment by jmalak** [comment]
Tested on Ubuntu and now it cross-compile for all targets DOS 16/32-bit and OS/2 32-bit.

**Comment by jwinarske** [comment]
Does it build with the same appveyor command find in the appveyor yaml file?  What are you invoking the build with?

**Comment by jmalak** [comment]
I have simple script which setup OW and run CMAKE to create make file and run make file by wmake.
Below is example for 16-bit DOS on Windows.

```
SET WATCOM=C:\dev\ow19
SET PATH=%WATCOM%\BINNT;%WATCOM%\BINW;%PATH%
SET INCLUDE=%WATCOM%\H;%INCLUDE%
cd PDCurses-bin-dos16
C:\CMake\bin\cmake --debug-trycompile -G "Watcom WMake" ../PDCurses-jm -DCMAKE_TOOLCHAIN_FILE=../PDCurses-jm/cmake/watcom_open_dos16_toolchain.cmake -DPDC_DOS_BUILD=ON -DPDC_BUILD_SHARED=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF
```

**Comment by jwinarske** [comment]
I just confirmed the Appveyor Watcom [builds are back](https://ci.appveyor.com/project/jwinarske/pdcurses-21dj3).  I appreciate the help. :1st_place_medal: 

Feel free to expand the travis build matrix for Linux Watcom.  That was on my todo list a long time ago!
