### ISSUE TITLE
Unable to find bwasm during Windows build.

### ISSUE THREAD

**Issue by pchapin** [open-watcom/open-watcom-v2#600]
I'm trying to build Open Watcom on my Windows 10 system. I'm using VISUALC for the bootstrap. I get to here:

    ========= 20:30:21 C:\Projects\OW\bld\clib\cgsupp\library\os2.286\mm ==========
    as fdmth086.obj
    Error(E14): Cannot execute (bwasm): No such file or directory
    Error(E42): Last command making (fdmth086.obj) returned a bad status
    Error(E02): Make execution terminated
    <pmake -d build          -h> => non-zero return: 2
    Build failed

The file `build\binbuild\bwasm.exe` exists. My setvars includes

    set OWOBJDIR=binbuild

(if that matters)

Thoughts?

**Comment by jmalak** [comment]
If some undetermined error appears then you get this little confusing message from builder.
Try to run bwasm from command line if it is workable.
anyway try to do full build cleanup.

**Comment by pchapin** [comment]
Hi Jiri,

I had done the build from a pristine copy of the source. I just scrubbed the source tree again, and retried and got the same result. Curiously it does find bwasm when assembling some earlier files. Here is the result I got on a first run after cleaning the source tree:

    ========= 18:52:54 C:\Projects\OW\bld\clib\cgsupp\library\os2.286\mm ==========
    as 7fu8086.obj
    as 7u8f086.obj
    as fdc086.obj
    as fdfs086.obj
    as fdi4086.obj
    as fdi8086.obj
    as fdmth086.obj
    Error(E14): Cannot execute (bwasm): No such file or directory
    Error(E42): Last command making (fdmth086.obj) returned a bad status
    Error(E02): Make execution terminated
    <pmake -d build          -h> => non-zero return: 2
    Build failed

When I try to execute bwasm manually in the same window, it is found and executes fine (displaying the help information). I suppose it is having trouble finding fdmth086.asm, but the file does exist in my source tree as expected. The file appears to be normal (readable, not obviously corrupt).

I speculated that this might be related somehow to my virus and malware scanning program, so I created an exclusion that stops it from scanning in the entire OW hierarchy (at least I think I did), but that didn't help.

I do not see this issue on my Ubuntu 18.04 system, where everything builds fine (I get a segment violation on that system while building documentation, which is new, but is probably a different issue... related to recently changes to the documentation files, perhaps?).

Anyway, I'm at a loss as to what is happening here. I think the message is misleading since it successfully assembles earlier files. I suppose bwasm is crashing?

**Comment by jmalak** [comment]
Yes, message is misleading, it signal that bwasm failed for some unknown reason.
What Visual C version you use?

**Comment by pchapin** [comment]
Sorry about the delay getting back to this...

I'm using Visual Studio 2017. The version reported by cl /? is: 19.16.27039. Should I be using the compiler that generates 64 bit executables or the one that generates 32 bit executables?

**Comment by pchapin** [comment]
Thanks! That explained it. I switched to the 64 bit native tools and this problem went away.
