### ISSUE TITLE
[Documentation] Could a link be added to installer/installation?

### ISSUE THREAD

**Issue by rubyFeedback** [open-watcom/open-watcom-v2#601]
Hey guys,

I just git cloned the project, assuming that source virtualbox needed it.

But now I am confused because I have .exe files. ;-)

Would it be possible to perhaps exlpain whether this can work on
linux too; and, perhaps an INSTALL subsection or a separate
.md file that just briefly explains how to build it? Does not have
anything long really, just a headstart to get going. Thanks!

**Comment by jmalak** [comment]
First you don't need to build OW from sources.
You can download [OW installer](https://github.com/open-watcom/open-watcom-v2/releases/tag/Current-build) (full distribution) for your host system and run it or you can download complete [OW binary build](https://github.com/open-watcom/open-watcom-v2/releases/download/Last-CI-build/ow-snapshot.tar.gz) and configure it manualy.
Anyway in installation root is readme file which describes steps for manual OW configuration.
If you want to build it from sources then here is [build instructions](https://github.com/open-watcom/open-watcom-v2/wiki/Build) in OW Wiki.

**Comment by jmalak** [comment]
I added two new sections, `OpenWatcom Installation` and `OpenWatcom Building` to github readme 
It is url links to OW documentation and to OW Wiki as you proposed.
