### ISSUE TITLE
Build failed with a lot of warnings and strange errors on OW 2.0b Jun 11 2020 32bit

### ISSUE THREAD

**Issue by wadim-al** [open-watcom/open-watcom-v2#605]
Problem: too many strange warnings and errors while building different programs.
OW:  2.0b Jun 11 2020 32bit
OS/ENV: Windows 95 OSR2
PC: Pentium4 1600, 128 MB RAM
Target: DOS 32: DOS4GW

Steps:
1. Install OW on Windows 95 OSR2
2. Create a default project, configure target as DOS 32: DOS4GW
3. Add c file (see attachments). File should use some code from <stdlib.h>
4. Try compiling.

Expected: warnings and errors should be clear and correspond with the actual source code errors.

Actual: warnings and errors are very strange. For example:
graph1.c(14): Error! E1077: Missing '}'
graph1.c(14): Warning! W107: Missing return value for function 'main'
The brackets are all ok in source, and there is a return value for the main function.

[LOG noname.txt](https://github.com/open-watcom/open-watcom-v2/files/4765203/noname.txt)
[EXAMPLE SOURCE graph1.c.txt](https://github.com/open-watcom/open-watcom-v2/files/4765208/graph1.c.txt)

**Comment by jmalak** [comment]
I think the problem is that you use source code compliant with C99 standard but OW needs to use switch -za99 for such source code.
Try to compile with -za99 option.

**Comment by wadim-al** [comment]
GUI doesn't support -za99 option or I haven't found it yet. Anyways, errors were fixed by reordering all variables declarations to the top of the function. Thanks!

**Comment by jmalak** [comment]
No, OW compiler are supporting C90 and some features from C99 (switch on by -za99) it is reason why  it is not in IDE, you can add it as additional option to your configuration if you want to use it.
