### ISSUE TITLE
empty Win32 C program depends on USER32.DLL

### ISSUE THREAD

**Issue by pts** [open-watcom/open-watcom-v2#608]
When I try to build `int main(void) { return 0; }` with `owcc -bwin32 -o prog.exe prog.c`, the resulting `prog.exe` depends on USER32.DLL, calling the Win32 API function CharUpperA.

How do I get rid of this dependency, so that `prog.exe` depends only on KERNEL32.DLL? Is there a quick workaround, e.g. can I add my own implementation of CharUpperA to prog.c? (I wasn't able to make it work after several attempts, USER32.DLL ended up linked in.)

It would be awesome if this change was made default, so that OpenWatcom would be able to build smaller Win32 .exe files, with fewer dependencies. I'm planning to use the .exe files in a restricted Win32 emulation environment, and omitting the emulation of USER32.DLL would make it the environment smaller and simpler.

**Comment by jmalak** [comment]
If you want only dependency on KERNEL32.DLL then you will need to create special version of OW CRTL which will be limited only to use KERNEL32.DLL.
Take into account that some Windows function from USER32.DLL are loaded dynamicaly by OW CRTL.

**Comment by pts** [comment]
FYI if I add my own implementation of `_mbctoupper`, then the dependency on USER32.DLL goes away:

```
unsigned int _mbctoupper(unsigned int c) {
  return (c - 'a' + 0U <= 'z' - 'a' + 0U)  ? c + 'A' - 'a' : c;
}
```

**Comment by jmalak** [comment]
There are following statically linked entries in CRTL (except KERNEL32.DLL)
```
CharLower                       USER32.DLL
CharUpper                       USER32.DLL
MessageBox                      USER32.DLL
AdjustTokenPrivileges           ADVAPI32.DLL
OpenProcessToken                ADVAPI32.DLL
LookupPrivilegeValue            ADVAPI32.DLL
GetActiveWindow                 USER32.DLL
```
