### ISSUE TITLE
PE .exe files don't work on Windows NT 3.1

### ISSUE THREAD

**Issue by pts** [open-watcom/open-watcom-v2#610]
A PE .exe file generated by `owcc -bwin32  -Wl,runtime -Wl,console=4.0 -o hello.exe hello.c` doesn't work on Windows NT 3.1. The error message when I try to run *hello.exe* is `C:\hello.exe is not a valid Windows NT appication.`. The same *hello.exe* works on Windows 95. *hello.c* looks like:

```C
#include <stdio.h>
int main(void) {
  printf("Hello, World!\n");
  return 0;
}
```

FYI Windows NT 3.1 was the first operating system released which implements the Win32 API. It has the KERNEL32.DLL and USER32.DLL files needed to run `hello.exe`.

**Comment by pts** [comment]
FYI Compiling `hello.c` like this solves the problem for Windows NT 3.1: `owcc -bwin32 -Wl,runtime -Wl,console=3.10 -o hello.exe hello.c`.

**Comment by jmalak** [comment]
It looks like Windows NT 3.1 loader requires version of console subsystem to be setup to 3.10.
We use OW default version 4.0 for Windows NT 4.0 and above even if CRTL should support Windows Win32s, NT 3.1, 3.5, 4.0 etc.
I don't know what impact of this version is to Load process on newer Windows OS-es.

**Comment by pts** [comment]
FYI The *hello.exe* generated by `owcc -bwin32 -Wl,runtime -Wl,console=3.10 -o hello.exe hello.c` works on Windows NT 3.1, Windows 95 and Windows 10 64-bit. By interpolation, I predict that it works on all Win32 systems.

**Comment by jmalak** [comment]
Please could you try to change your `wlink.lnk` file that you remove version specification from linker script file and try on NT 3.1 with command
```
owcc -bwin32 -o hello.exe hello.c
```
Remove version from runtime definition lines like
```
    runtime console=4.0
    runtime windows=4.0
```
to be
```
    runtime console
    runtime windows
```
