### ISSUE TITLE
Error while trying to assemble TASM code with WASM, even with "-zcm=tasm"

### ISSUE THREAD

**Issue by volkertb** [open-watcom/open-watcom-v2#612]
Hi,

I'm trying to assemble the following source file, using WASM from open-watcom-v2:

https://github.com/volkertb/temu-vsb/blob/master/sbemu/vsb.asm

It's assembly code written in the TASM dialect. (IDEAL mode, I believe.) The project contains a lot more assembly sources, but I'm first trying to get this separate file to build.

I'm building this code on a Linux 64-bit system, but the target platform is of course DOS.

WASM is complaining about two errors here. The first one is an `E032: Syntax error`, because it doesn't recognize the `SMART` directive on line 11. This error disappears when I comment that line out.

However, the second error is quite a bit more puzzling. It seems that the following code (on line 35) is the culprit:

```
lea     ax,[di+offset @@nextInstr - offset Start]
```

This results in an `E083: Label is expected` error, and I have no idea how to work around this. I tried renaming the labels, removing the `@@` prefix (which I believe identifies them as local labels in TASM, right?), suffixing the label references in the instruction with double colons, but none of that helped, and it all resulted in the same error.

Also, the `-zcm=tasm` parameter has no effect here, and doesn't really seem to do anything, since I get exactly the same errors (and no warnings either way) whether I include that parameter or not. Also, if I specify `-zcm=blabla`, WASM doesn't complain and gives the exact same result. Placing this parameter behind the file name instead of before it didn't make any difference either.

Now I have to clarify that I am not an assembly language wizard myself. I dabble in it a little, but I'm no expert. Maybe I'm missing something obvious.

Am I doing anything wrong here? Is this a compatibility issue between WASM? Perhaps that unsupported `SMART` directive is exactly what is needed for the assembler to figure out how to parse this? Is this easy to fix, and is there perhaps a workaround you can suggest in the meantime?

Thank you kindly for any help you can provide here.

**Comment by jmalak** [comment]
I think the labels @@.... are not yet supported.
WASM is not 100 % compatible with TASM.
I can look on @@ labels support, but it take some time.

**Comment by volkertb** [comment]
It's not the `@@` labels, apparently. I just figured out a workaround that allows WASM to build this code. I assigned the calculated value to a symbolic name using the  `equ` statement and then referred to that in the `lea` instruction, like so:

```
theoffset equ offset @@nextInstr - offset Start
lea     ax,[di+theoffset]
```

That worked without any errors or warnings. It seems like a limitation in WASM that prevents it from parsing this when the calculation is inlined. Is this easy to fix, you think?

Also, I found information about that `SMART` directive that I had to comment out earlier:

```
  SMART/NOSMART
  -------------
  The SMART/NOSMART directives control the generation of optimized object code.
  These are the areas that the SMART  and NOSMART directives apply to:

    1) OR, AND, or XOR of a signed immediate byte
    2) PUSH <constant>
    3) PUSH <large pointer>
       POP <large pointer>
    4) CALL <far address in same segment>
    5) JMP <far address in same segment>
    6) LEA <constant effective address>

  The default condition is SMART enabled. When SMART is enabled, a qualifying
  FAR jump will be replaced by a NEAR or a SHORT jump. Also, when SMART is 
  enabled, a qualifying FAR call will be replaced by a PUSH CS instruction 
  and a NEAR call. 

  When NOSMART is  selected, the following code generation changes occur:
 
    a) AND, OR, XOR of an immediate word value are no longer done using the 
       signed-extended immediate byte version of these instructions where 
       possible, but rather the longer immediate word version that MASM uses.
 
    b) PUSH of a constant value on the 8086 processor using the special 
       10-byte code sequence (which preserves all registers and flags) is 
       not allowed.
 
    c) PUSH and POP of a DWORD memory variable (or PWORD variable on a 386) 
      are not allowed.
 
    d) Far JMPs and CALLs within the same segment are no longer optimized by 
       replacing the FAR JMP or CALL with the NEAR version.

    e) LEA instructions that refer to a constant effective address will no 
       longer be converted to the equivalent MOV operations.

  For maximum MASM compatibility, you must select NOSMART and QUIRKS.
```
Source: https://bytepointer.com/tasm/tasm2.01_update.htm

**Comment by jmalak** [comment]
Wasm uses something like SMART by default.

Wasm has a problem with expression on the line
`                lea     ax,[di + offset nextInstr - offset Start]`

it can be fixed by
`                lea     ax,[di + nextInstr - Start]`

**Comment by jmalak** [comment]
Probably problem is that nextInstr is unknown symbol for wasm.
If you use @@ prefix then it is local code label that no problem in TASM but wasm doesn't know @@ prefix as local code labels.
If I put nextInstr before LEA then it works OK.

**Comment by jmalak** [comment]
I added SMART directive to be recognized for TASM mode, but it is skipped.
That no error for this directive.

**Comment by jmalak** [comment]
Now your code is assembled without errors.
Try latest version of WASM from CI build or install new version of installer build.

**Comment by volkertb** [comment]
Sorry for the late reply. I just confirmed this. WASM now indeed assembles `vsb.asm` without any errors or warnings. :+1:
