### ISSUE TITLE
Instrumentation - Disassembling and Assembling

### ISSUE THREAD

**Issue by KendalYaman** [open-watcom/open-watcom-v2#613]
I'm currently trying to instrument a C program (let's call hello) running under dosbox. For this, I would like to use open watcom to retrieve the hello assembler code and insert additional assembly instructions allowing me to measure the code coverage.

I am using open watcom in DOSBox and would like to know if there is a command to directly get an assembler file.

Because, for now, I'm doing it this way:
```
#include <unistd.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
   printf("Hello World\n"); 
   return 0;
}
```

1.`wcl program.c` -> program.OBJ & program.EXE
or
`wcc program.c` -> program.OBJ

2.`wdis -l = TOTO.asm -a program.OBJ` -> TOTO.asm

3.`wasm TOTO.asm` -> TOTO.OBJ

4.`wlink file TOTO.OBJ`

Open Watcom Linker Version 1.9
Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
loading object files
Error! E2028: __STK is an undefined reference
Error! E2028: printf_ is an undefined reference
Error! E2028: __argc is an undefined reference
Error! E2028: _small_code_ is an undefined reference
Error! E2028: _cstart_ is an undefined reference
Warning! W1014: stack segment not found
Warning! W1023: no starting address found, using 0000:0000
creating a DOS executable
file TOTO.OBJ(C:\TMP\TEST\TOTO.ASM): undefined symbol __STK
file TOTO.OBJ(C:\TMP\TEST\TOTO.ASM): undefined symbol printf_

So, I would like to know if there is a reliable way of disassembling and assembling again from obj files.

**Comment by jmalak** [comment]
I have no problem, I used following commands
1. `wcc -s hello.c`
2. `wdis -a -l=todo.asm hello.obj`
3. `wasm todo.asm`
below is disassembled hello.obj
```
.387
                PUBLIC  main_
                EXTRN   printf_:BYTE
                EXTRN   __argc:BYTE
                EXTRN   _small_code_:BYTE
                EXTRN   _cstart_:BYTE
DGROUP          GROUP   CONST,CONST2,_DATA
_TEXT           SEGMENT BYTE PUBLIC USE16 'CODE'
                ASSUME CS:_TEXT, DS:DGROUP, SS:DGROUP
main_:
        mov             ax,offset DGROUP:L$1
        push            ax
        call            near ptr printf_
        add             sp,2
        xor             ax,ax
        ret
_TEXT           ENDS
CONST           SEGMENT WORD PUBLIC USE16 'DATA'
L$1:
    DB  48H, 65H, 6cH, 6cH, 6fH, 20H, 57H, 6fH
    DB  72H, 6cH, 64H, 0aH, 0

CONST           ENDS
CONST2          SEGMENT WORD PUBLIC USE16 'DATA'
CONST2          ENDS
_DATA           SEGMENT WORD PUBLIC USE16 'DATA'
_DATA           ENDS
                END
```

Unfortunalely if you want to create executable (to run), you must link it with appropriate version of CRTL

**Comment by KendalYaman** [comment]
Thank you, it works !

I hadn't thought of including `lib clibs.lib` in the command.

**Comment by KendalYaman** [comment]
Which library I have to use if I use `wcc386` ?

**Comment by jmalak** [comment]
It depends on target for which you want to create executable.
Unfortunately you must also use proper target for compiler, option `-bt=.....`. Details you can find in [compilers guide](https://open-watcom.github.io/open-watcom-v2-wikidocs/cguide.html).
Normally if you want to link for some system then use linker directive `system ....`  which automatically include appropriate C run-time  libraries.
For example if you want link for 32-bit Windows GUI then include `system nt_win` for 32-bit Windows Console it is `system nt`.
Details you can find in [linker guide](https://open-watcom.github.io/open-watcom-v2-wikidocs/lguide.html)

**Comment by KendalYaman** [comment]
Thank you for your answer. I found another solution:
`wlink name todo.exe sys dos file todo.obj lib clib3s.lib`

This command works if I use library clib3s.lib for 32 bit.

Just a last question: I try to use execv() function in process.h header. Here's my program:

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <process.h>
#include <stddef.h>



int main(int argc, char *argv[]) {
	
	char *arr[] = {"wcc386" ,"toto.c", NULL};
	execv("wcc386", arr);
    
	printf("Error");
	return 0;	
}
```
Trying to compile this code on DOSBox, `wcc386 executer.c`

 I get this output:

```
Open Watcom C32 Optimizing Compiler Version 1.9
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
OW-INST.C(12): Warning! E1179: Parameter 2, type qualifier mismatch
OW-INST.C(12): Note! I2003: source conversion type is 'char **'
OW-INST.C(12): Note! I2004: target conversion type is 'char const *[]'
OW-INST.C(12): Note! I2002: 'execv' defined in: C:\WATCOM\H\process.h(48)
OW-INST.C: 14 lines, included 2303, 1 warnings, 0 errors
Code size: 62
```
Do you know what is the issue, because I correctly used `execv()` function (I think) ?

**Comment by jmalak** [comment]
You should use OW tools properly.
Your wlink command is wrong.
You link for 16-bit dos and override CRTL by wrong  32-bit stack based version library.
You have big mismatch. 
Also you use wrong installation of OW tools, at minimum INCLUDE variable etc.
You are trying to be clevver than OW tools.
I you are beginner use wcl/wcl386 tools and do proper OW setup for dos.
SET WATCOM=.....location where OW is installed
SET PATH=%WATCOM%\binw;%PATH%
SET INCLUDE=%WATCOM%\H

Read readme in root of OW installation to proper OW setup.

**Comment by jmalak** [comment]
Look on prototype for this function defined in OW, in POSIX and in Visual Studio
OW          _WCRTLINK extern int    execv( const char *__path, const char *const __argv[] );
POSIX      int execv(const char *path, char *const argv[]);
MS VS      intptr_t _execv(  const char *cmdname,  const char *const *argv);

OW follow Miscrosoft declaration for execv, therefore you get this message. C standard requires message for this type of pointers mismatch.

**Comment by jmalak** [comment]
You are right that diagnostic message is not correct about target prototype.
I will look on this and fix it to display correct prototype.
Anyway message is OK, because there is type mismatch.
I fixed reported prototype for arrays, now you should get somethig as
t2.c(5): Warning! W1179: Parameter 2, type qualifier mismatch
t2.c(5): Note! N2003: source conversion type is 'char *[]'
t2.c(5): Note! N2004: target conversion type is 'char const *const []'
t2.c(5): Note! N2002: 'execv' defined in: t2.c(1)
t2.c: 7 lines, included 48, 1 warnings, 0 errors
