### ISSUE TITLE
WASM does not infer proc name when processing endp

### ISSUE THREAD

**Issue by volkertb** [open-watcom/open-watcom-v2#616]
So I'm trying to compile the TASM source file https://github.com/volkertb/temu-vsb/blob/master/sbemu/vsb_qemm.asm, and I'm opening separate issues for the different errors types I'm encountering. I used the WASM version from the latest current installer build (Linux x64).

One issue I've noticed is the fact that TASM code (at least the TASM code in the temu-vsb project) often uses bare `endp` directives to denote the end of a `proc` block. Apparently TASM (at least in IDEAL mode) is intelligent enough to infer the proc name when it's not explicitly specified in the corresponding `endp` directive.

For example:

```
; AL = 1 - enable; 0 - disable DMA
EnableDMA       proc    near
                push    bx
                mov     bx,word ptr PatchData1
                or      al,al
                je      @@Off
                cmp     SBcounter,0FFFFh
                jne     @@1
                inc     SBcounter
@@1:            cmp     DMAcounter,0FFFFh
                jne     @@2
                inc     DMAcounter
@@2:            mov     bx,word ptr PatchData2
@@Off:          mov     word ptr EnablePatch,bx
                pop     bx
                ret
                endp
```

This results in the following error:

```
vsb_qemm.asm(240): Error! E535: Procedure must have a name
```

(Note: there are also other unrelated errors in this code block, but I'll open separate issues for those.)

So I actually have to put `EnableDMA` in front of the `endp` directive in order to resolve this issue. But why shouldn't an assembler be smart enough to infer this? It always corresponds to the last preceding `proc`, right?

Thanks for considering this.

**Comment by volkertb** [comment]
@jmalak By the way, do you prefer I open separate issues for each separate error type, or would it perhaps be more practical for you and other maintainers here if I just opened a central issue at the file level? For instance: "Errors when trying to build vsb_qemm.asm with WASM"? Thanks.

**Comment by jmalak** [comment]
WASM is mostly MASM 5 compatible and include some features from MASM 6.
TASM mode was added by contributors but it is not complete. I don't know how much.
WASM is not copy of TASM and doesn't do such things if MASM doesn't do this.
If you define what is wrong in TASM emulation in WASM I can fix it in WASM.
I don't use TASM therefore I am not able to define what important TASM features to be implemented by WASM.

**Comment by jmalak** [comment]
Please always specify if it is global TASM feature or only IDEAL mode feature to properly add it in WASM if possible,

**Comment by jmalak** [comment]
I enabled ENDP without name for TASM emulation mode by commit f76464a78ef1fb9bb5d0ccf1555dd549898f82f3

**Comment by volkertb** [comment]
> I enabled ENDP without name for TASM emulation mode by commit [f76464a](https://github.com/open-watcom/open-watcom-v2/commit/f76464a78ef1fb9bb5d0ccf1555dd549898f82f3)

I just tested this with the latest installer build and indeed no more errors are flagged on the bare `endp` directives. Thanks. :+1:

There are still other errors showing up when trying to build this source file with the WASM version from the latest installer build as of 2020-08-17, but I'll open separate issues for those.

Closing this issue.

**Comment by volkertb** [comment]
> WASM is mostly MASM 5 compatible and include some features from MASM 6.
> TASM mode was added by contributors but it is not complete. I don't know how much.
> WASM is not copy of TASM and doesn't do such things if MASM doesn't do this.
> If you define what is wrong in TASM emulation in WASM I can fix it in WASM.
> I don't use TASM therefore I am not able to define what important TASM features to be implemented by WASM.

I understand. I'm grateful for your efforts to improve TASM compatibility, even though WASM wasn't initially intended to be a TASM replacement. Like I said in the other issue, my assembly language programming skills are limited, but I'm willing to learn and help out where I can.
