### ISSUE TITLE
add optional use of `WATCOM_INCLUDE` as an alternate for `INCLUDE`

### ISSUE THREAD

**Issue by rivy** [open-watcom/open-watcom-v2#619]
The environment variable `INCLUDE` is used by other applications.
To minimize interference with other installed apps, allow the `WATCOM_INCLUDE` environment variable to be used as an optional replacement.

**Comment by jmalak** [comment]
I am not sure what you want to resolve by this additional environment variable.
Installer doesn't remove existing INCLUDE environment variable contents only add OW part to it.
I don't thing the additional environment variable has sense and solve the issue.
Only full replace of INCLUDE by WATCOM_INCLUDE or by other mechanism can resolve this.
To be independent on existing environment variables you can use -x compilers options.

**Comment by rivy** [comment]
Thanks, again, for the quick reply.

The issue is that the order of directories in `INCLUDE` generally matters.

When a compiler encounters another compiler's headers first, it generally causes "undefined" behavior (generally, failed compiles; *very* commonly for Windows compilers). IMO, I think it's best to avoid that kind of cross-talk when possible. In general, I think that all applications which use environment variables should attempt to segregate their variables and avoid use of "common" overlapping variables.

Hence, using `WATCOM_INCLUDE`. It would be optional, and used instead of `INCLUDE` only if defined. When it's missing, `INCLUDE` would be used as usual.

It's a win for anyone using multiple compilers.

**Comment by jmalak** [comment]
There are many such feature requests but nobody want contribute anything.
It is nice task for new contribution.

**Comment by rivy** [comment]
If you're open to the change, I'll be happy to look at it and submit a PR.

**Comment by jmalak** [comment]
Any contribution is welcome.
You can submit PR or we can discus code changes in this issue. 
It depend on what you prefer.

OW cross-compile multi-platform build system to resolve problem with various systems and configuration use -x option for all compilers. 
All target headers include path is add by -I options. It is totally independent on any environment variables and enable simple switch of target architecture and platform by make files.
Unfortunately if you use OW compiler for bootstrap then you need regularly configured OW compiler.

**Comment by rivy** [comment]
I've done a preliminary exploration of the code and have an initial draft plan for the PR. But I'm running into a blocker when compiling the project (#625). Once I get past that, I'll construct the PR for this issue.

**Comment by negge** [comment]
This will break all of the existing build files for people who use WATCOM in their projects.  I would strongly recommend against this change.

**Comment by rivy** [comment]
@negge , I don't understand you objection, please explain.

In general, I don't see how adding an optional `WATCOM_INCLUDE` environment variable would have much of any effect on current build recipes. Are you saying that the variable is already commonly used in some way?

**Comment by jmalak** [comment]
I don't think that adding WATCOM_INCLUDE we get something useful.
Nothing will be simpler.
Handling INCLUDE environment variable is general rule how it is handled on any platforms.
If you want to be independent on INCLUDE environment variable you have -x option for OW tools.

**Comment by rivy** [comment]
As I previously mentioned, specifically for Windows which doesn't really have any standard usage of `INCLUDE`, using `INCLUDE` for multiple compilers causes problems. Whichever compiler's header files are earlier in the INCLUDE list will cause the other compiler to fall over with un-parsable headers and broken compiles.

By placing the OpenWatcom specific header file paths into their own location `WATCOM_INCLUDE`, other compilers can be used contemporaneously without compiler errors. Since it's an optional override, it shouldn't have any effect on currently working build processes, including the compiler build process itself. It *can* be used in the future to make the compilation process more robust, but it's not any kind of requirement.

This has been a stumbling block when I'm trying to add support for this compiler for building other utilities (eg, [`less`](https://github.com/rivy/less)).

I can build that robustness into my own installation and build procedures (in this manner or maybe by somehow using the `-x` option?), but I thought the community would benefit if something like this was codified in the OpenWatcom compiler project. 

If you believe this to be of no utility, I'll close the issue without spending any more time creating a PR.

**Comment by jmalak** [comment]
All Windows compilers need some configuration.
Most of them use INCLUDE, PATH and some others environment variables that your solution is only partial.
If you want to use various compilers together then you need reconfigure them before use each compiler.
Mostly it is done by some batch script. 
I think it is impossible by design, because compiler vendors doesn't expect such use. Simple question why?
For INCLUDE collision OW has -x option.
Only this can be used for OW because it ignores all ...INCLUDE... environment variables (OW use multiple such variables).
If -x option is used then OW is independent on such environment variables and has no such problem at all.
Anyway it doesn't solve PATH issue.

**Comment by rivy** [comment]
Yes, I agree, all of the compilers need some configuration. PATH is generally not an issue as `which wpp` can be used to locate the base binary open watcom directory where all of the build-compatible binaries are located. `INCLUDE` is a bit different as the OpenWatcom headers are not identifiable separately from, say, MSVC's entries. So, a batch script must just guess at the correct directories. If the `INCLUDE` directory list is placed in an alternate known location such as `WATCOM_INCLUDE`, the information can be used directly either by the compiler or batch scripts. It appears that `WATCOM` is already used in a similar way as an alternate for `LIB`.

I've been the recipient of odd, surprising compiler errors because the header files were jumbled together in a random fashion with another compiler's header files. I'm successfully using `clang`, `gcc`, djgpp, MSVC, `bcc32`, and `embcc` contemporaneously because they can be configured relatively orthogonally to each other, without clashing. And again, I can design an installation and build framework that gets around this issue. But, I thought this would be a useful step to help use the Open Watcom compiler even when other compilers are also configured without extra steps.

Thanks for the information about `-x`, that might help in some build script corner cases.

**Comment by jmalak** [comment]
Open Watcom is very different from Miscrosoft compiler because OW compilers are cross-compiler by nature.
You must handle INCLUDE variable or -I... options or <target_os>_INCLUDE variables it depends on what you want to do.
Basic (default) setup is only for situation when <target_os>=<host_os>.
Anyway cross-compilation suppose some makefile to handle multiple target architectures or target OS-es.

**Comment by jmalak** [comment]
We are using -x option for build system when part of OW build (bootstrap or some tools) are compiled by bootstrap compiler (64-bit or OW unsupported architecture). It is realy paralel compilation by two various compilers.
Bootstrap compiler is configured by its standard configuration way and after building bootstrap compiler then makefiles switch to OW environment.
But it is special case and it is handled by makefiles and wmake and special build tools.

**Comment by jmalak** [comment]
Statement `I'm successfully using clang, gcc, djgpp, MSVC, bcc32, and embcc contemporaneously because they can be configured relatively orthogonally to each other, without clashing.` is irrelevant and is missleading. If you understand all these toolchains then you know that they was not designed to such use. Maybe some newer is designed to emulate GNU and coexist with GNU or is designed for POSIX environment therefore can coexists. But older is not designed this way.
Anyway you should use toolchain the way as it was designed.

**Comment by rivy** [comment]
Your opinion is noted.
👋
