### ISSUE TITLE
Tag significant "releases" here on github

### ISSUE THREAD

**Issue by rivy** [open-watcom/open-watcom-v2#620]
It would be helpful if some "significant" releases were tagged here on GitHub (eg, as `2.0-2020-08-23`).
It would allow an alternate (and one-stop) download location for point-in-time releases with minimal extra effort.
It would also likely help keep more current as the last sourceforge point-in-time release was back in [November 2017](https://sourceforge.net/projects/openwatcom/files/open-watcom-2.0-2017-11-01).

**Comment by jmalak** [comment]
In the past it was done manualy therefore it was permanent.
Now it is done automaticaly each day if any change in code.
For saving disk space it is build as one updated copy.
One release take over 1 GB of disk space.
If you propose some efective algorithm how to do some permanent copies without big disk space grow then it can be integrated to automated build. Or you can contribute to this part of Azure Pipelines script.
The logic of handling Releases is in ci/release.yml, relevant part of code is below
```
    - bash: echo "##vso[task.setvariable variable=owtagstamp;]`date +'%Y-%m-%d %H:%M:%S'`"
      displayName: "Get current timestamp"
    - bash: echo "##vso[task.setvariable variable=owgitstamp;]`git ls-remote --tags . | sed -n -e \"s:\([0-9a-z]*\) *refs/tags/${{ variables.owtag }}^{}:\1:p\"`"
      displayName: "Get 'Current-build' tag commit"
    - script: |
        if [ ! "$OWGITSTAMP" = "$BUILD_SOURCEVERSION" ]; then
          git tag -d $OWTAG
          git push --delete origin $OWTAG
          git tag -a -m "$OWTAGSTAMP" $OWTAG $BUILD_SOURCEVERSION
          git push $(owgitverbose) origin $OWTAG
        else
          echo "##vso[task.setvariable variable=owtagstamp;]`git tag -l --format='%(contents)' $OWTAG`"
        fi
      displayName: "Recreate 'Current-build' tag"
    - task: GitHubRelease@0
      name: releasedel
      displayName: "Delete Release"
      continueOnError: true
      inputs:
        gitHubConnection: 'open-watcom-v2-releases'
        action: 'delete'
        tag: '$(owtag)'
    - task: GitHubRelease@0
      name: releaseadd
      displayName: "Add Release"
      condition: succeededOrFailed()
      inputs:
        gitHubConnection: 'open-watcom-v2-releases'
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'manual'
        tag: '$(owtag)'
        title: '$(owtag)'
        releaseNotesSource: 'input'
        releaseNotes: 'Last updated $(owtagstamp)'
        ${{ if eq(parameters.arch, 'nt') }}:
          assets: |
            distrib\ow\bin\open-watcom-*
            distrib\ow\bin\ow-snapshot.tar.gz
        ${{ if in(parameters.arch, 'lnx', 'osx') }}:
          assets: |
            distrib/ow/bin/open-watcom-*
            distrib/ow/bin/ow-snapshot.tar.gz
        isPreRelease: true
        addChangeLog: false
```

**Comment by rivy** [comment]
I think that doing an occasional manual addition of a version tag to a CI release would be easy and convenient. It could be done ad-hoc every few months or as a "release". A gigabyte worth of artifacts a couple of times per year shouldn't strain GitHub at all. And that would give some stable points for users.

**Comment by jmalak** [comment]
I have no much free time and each human have different kind of "significant release", that it must be automated somehow.
By example one release per month or each two month....

**Comment by rivy** [comment]
I'll look at it.
I've not done any work with Azure Pipelines, but my initial quick look through the documentation showed that a possible solution might be created via [scheduled triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers).

**Comment by rivy** [comment]
Ok, if "Current-Release" is already scheduled daily, I'll try to piggy-back off of it to save a tag on the first of each month.

**Comment by jmalak** [comment]
Below is current schedule for "release" pipeline. It is scheduled for each day but only if there is some change.
![Current-release-run](https://user-images.githubusercontent.com/2017260/92263819-8c76cb00-eedd-11ea-9c68-ec35df557688.png)
It will require to check if release was already created for current month.

**Comment by jmalak** [comment]
I already done it.
Now first change in the month will be initiate such permanent release in the form YYYY-MM-DD-Build.
Date of such build can be any date when some change trigger Current-Release build.

**Comment by rivy** [comment]
That sounds like a great solution.
Thanks for implementing it!
