### ISSUE TITLE
General Protection Fault when trying to build Allegro 4.2.3 library

### ISSUE THREAD

**Issue by cantbothertoshave** [open-watcom/open-watcom-v2#623]
Hello!

In the early 2000's I have been using Watcom 11 briefly. And now discovering the existence of Open Watcom, specifically your fork of v2, while playing with DOXBox and attempting to make programs that run in it.

I found this: [Compiling MS-DOS games with Allegro 4 in 2019](https://www.mrdictionary.net/allegro/)
I took the VirtualBox image provided there, of FreeDOS with with DJGPP build tool chain and Allegro preinstalled - the former of which is still needed to build Allegro for Watcom, as [described here](http://mirror.bwpow.eu/pub/manuals/allegro/4.2.2/build/watcom.html).

So I made a ISO image with the DOS exe installer for OpenWatcom v2.0c, mounted it in VBox & successfully installed Watcom for DOS host & target there.

When attempting to "make" allegro, it goes through a bunch of files until wcl386 chokes on a file called "asmdef.c" with:
_General Protection Fault at eip=26abb; flags=3002_.

I tried to repeat that, both with a win32 installation on win7 32, and a DOS-host installation accessed from DOSBox, all failed, although I'm not sure it was exactly the same problems (was late, couldn't sleep, so what better to do than this sorta thing ;) But I shut down without making screencaps)

Now I do not know what to expect of this v2 fork, how much it's experimental or early or whatever, and I don't have experience with how much the original Watcom used to crash on bigger projects.
Can someone give me some pointers?

[[OT]]
Now maybe this is not the right forum for this, although, where would that be today...
But: Could it even make sense to run Watcom 11 (must have it lying around *somewhere*) on a 32bit Windows?

The reason why I'm not just conveniently using DJGPP, readily set up at that link above, to build my tinker projects, is that 1) they're floating point heavy & the DJGPP page says itself that Watcom is way better at optimizing that, and 2) The Watcom IDE is actually somewhat usable & interacts well with Windows, unlike RHIDE for DJGPP which looks like a Borland C++ 2.0 clone in text mode. (sure I could try to set things up with some open IDE, but the debugging stuff seems to work well enough in Watcom)

**Comment by jmalak** [comment]
Compilers should be stable.
Anyway the crash is not OK.
To analyse we need more info, best if you can give here sample code which demonstrate a problem.
Reference to some project compiled by OW is hard to resolve issue, no any knowledge about such project/application.
You can try OW 1.9 last official version.
