### ISSUE TITLE
Windows (Windows 10.0.18363.959, MSVC 19.15.26730 for x64) build error ("Unsupported 16-bit application")

### ISSUE THREAD

**Issue by rivy** [open-watcom/open-watcom-v2#625]
I'm running into a blocker when trying to build the project.

After some lengthy success building a large part of the project, I'm blocked by an error...

```text
...
**** BUILD rule
===== 09:36:12 C:\Users\Roy\OneDrive\Projects\openwatcom\repo\bld\browser =====
=== 09:36:12 C:\Users\Roy\OneDrive\Projects\openwatcom\repo\bld\browser\gen ===
= 09:36:12 C:\Users\Roy\OneDrive\Projects\openwatcom\repo\bld\browser\brg\dos386 ==
= 09:36:12 C:\Users\Roy\OneDrive\Projects\openwatcom\repo\bld\browser\brg\nt386 =
= 09:36:12 C:\Users\Roy\OneDrive\Projects\openwatcom\repo\bld\browser\brg\os2386 ==
== 09:36:12 C:\Users\Roy\OneDrive\Projects\openwatcom\repo\bld\browser\nt386 ==
wgml wbrw.h
This version of C:\Users\Roy\OneDrive\Projects\openwatcom\repo\docs\gml\dos\wgml.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
Error(E42): Last command making (compile_gml_to_xxx;wbrw.h) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (C:\Users\Roy\OneDrive\Projects\openwatcom\repo\docs\nt\wbrw.h) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 2
```

The file "C:\Users\Roy\OneDrive\Projects\openwatcom\repo\docs\gml\dos\wgml.exe" is a 16-bit MS-DOS executable which isn't supported on Windows 10 anymore.

I'm currently re-attempting a build using OpenWatcom v2.0.

... Nope, the same exact problem exists when compiling using OpenWatcom.

**Comment by jmalak** [comment]
In OW build setup script is notes about it. 
On 64-bit Windows you need DOS emulator.
OW support only DOSBOX. See comment in setvars.* scripts.

**Comment by rivy** [comment]
Yep, it's buried in the `setvars` comments. When installed and configured within `setvars`, the build now completes.
Thanks for the attention.
