### ISSUE TITLE
wlib in ar mode tries to parse AR environment variable

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#631]
When *wlib* is used in *ar* mode, the executable will look for an environment variable *AR* and attempt to parse it as options to the library manager.  This processing occurs at bld/nwlib/c/cmdline.c:703.  It appears that this behavior is inherited from the non-*ar* mode using the *WLIB* environment variable to pass options from the IDE to the library manager (or at least that's the most common behavior).

This behavior in *ar* mode leads to problems with makefiles that will often use *AR* as an environment variable to define the command needed to execute the library manager.  The library manager will then fail with a ridiculous error such as:

```
Error! Invalid option '-/'
```

when the full path to Open Watcom's library manager is set as *AR* in the makefile.  

I feel like the *AR* environment variable should *not* be parsed by the library manager.  If others agree, I'll change it.

**Comment by jmalak** [comment]
I don't know if anybody use wlib tool in ar mode and if it was working.
Maybe best solution is remove ar mode at all.
If necessary then we can create ar driver for wlib with well defined behavior.

**Comment by ArmstrongJ** [comment]
I use it, but I feel like processing an environment variable in AR mode is not desired behavior.  I honestly can't think of a use case.  I'm not sure why this "feature" was ever added as it breaks so many Unix-like Makefiles.

However, providing an ar mode for *wlib* is pretty valuable if you're trying to build DOS software in a POSIX environment.  Modifying Makefiles that expect an ar-like syntax simply won't work with wlib's old Microsoft-workalike syntax, so the ar mode is quite valuable.

I am currently using the POSIX driver (*owcc*) and *wlib* in ar mode to work with a DOS port of Lua.  Other than this bug, it actually works great in that use case because I just need to redefine CC, AR, and CFLAGS to work with Open Watcom's tools rather than build a custom Makefile or fire up the IDE.  

Again, this bug breaks ar mode in a large number of cases, but *wlib* does, in fact, work well in ar mode.

**Comment by ArmstrongJ** [comment]
I've created pull request #632 that basically fixes the current faulty behavior.  If *wlib*'s ar mode is so rarely used, I honestly doubt anyone was passing flags to *wlib* via the AR environment variable.  Thoughts?

**Comment by jmalak** [comment]
OK. It has sense.

**Comment by jmalak** [comment]
Maybe better to rename this variable to some useful name and document it instead of removing it at all.
We could use something like "WAR" or "AROPTS" or "ARWLIB".
All OW tools use environment variable with same name as tool name to specify cmdl options.

**Comment by jmalak** [comment]
Maybe we could change tool name to WAR and then no problem with variable name.
For make file AR environment variable should be defined to point to WAR tool.

**Comment by ArmstrongJ** [comment]
I was about to suggest that *owcc* doesn't use an *OWCC* environment variable, but apparently it does.  Maybe the best option would be to actually parse the environment variable *WLIB* in ar mode regardless.  It's doubtful anyone would be defining *WLIB* with non-ar-mode options when using *wlib* in ar mode.  Additionally, I personally just define *WLIB_AR* to put *wlib* into ar mode so I don't need to rename anything, so the tool is still technically "*wlib*," not "*ar*."

Quick note, though: I don't think we should use *WLIB_AR* or the older *WLIB$AR* to define options since that does, in fact, break existing behavior.  Those two should remain as simply indicators that *wlib* should run in ar mode; otherwise, they'll need to define some sort of dummy option since most cases would just involve passing arguments on the command line.

**Comment by ArmstrongJ** [comment]
> 
> 
> Maybe we could change tool name to WAR and then no problem with variable name.
> For make file AR environment variable should be defined to point to WAR tool.

Or possibly *owar* to match *owcc*...  Either way, I like this idea.

**Comment by jmalak** [comment]
yes, owar is more transparent.

**Comment by ArmstrongJ** [comment]
I'll close #632 and set up a new pull request.

**Comment by ArmstrongJ** [comment]
I haven't looked at this bug or #633 in a few days, to be honest.  However, today I was thinking that much of the issue would disappear as-is if wlib only parsed the *AR* environment variable if and only if *wlib* was renamed *ar*.  In other words, if you simply use the environment variable trick to force ar mode, the executable, still named *wlib*, wouldn't look for an environment variable *AR* since there wasn't a program named *ar* that was run.  In fact, it could look at the *WLIB* environment variable still.  

It was just a thought and might be simpler to implement.  I feel like it would stick to the premise that these utilities will read environment variables named after them.  If there isn't a program named *ar* being run, there's no reason to read the *AR* environment variable.

Otherwise, we can proceed with the *owar* solution from #633.

**Comment by jmalak** [comment]
I think existing solution with AR is necessary for backward compatibility.
There is one problem which is not visible, all message text is in resources attached to executable, that we need to know executable object name. There are two names "run" name from which is derived mode and second name is file name which is used for load resources. If you use symbolic link then both name are different and if you rename file then both are the same.
Solution must work with both configurations. For me is better to create new executable with no "ar" name which replace wlib in "ar" mode.

**Comment by jmalak** [comment]
Can I close this issue as resolved and close appropriate pull request #639 ?

**Comment by ArmstrongJ** [comment]
I suppose so.  So does *owar* work and only read the **OWAR** environment variable?

**Comment by jmalak** [comment]
If you rename wlib to owar or create symbolic link owar to wlib then only **OWAR** variable should be read.

**Comment by jmalak** [comment]
fixed
