### ISSUE TITLE
Using #pragma aux to specify parameters not working for 8-bit registers

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#634]
When I use `#pragma aux` to specify what parameters should be passed in which registers to an externally defined assembly routine, if any of the parameters are 8-bit values (with corresponding 8-bit registers) then the compiler silently defaults to passing by parameters on the stack.

See the following example:

```nasm
BITS 16

SEGMENT .code USE16 CLASS=CODE

GLOBAL putchar_asm_
GLOBAL putchar_asm2_

putchar_asm_:
  mov ah, 0x2
  int 0x21
  ret

putchar_asm2_:
  mov ah, 0x2
  int 0x21
  ret
```

```c
void putchar_asm(char ch);
#pragma aux putchar_asm parm [ dl ]

void putchar_asm2(char ch);
#pragma aux putchar_asm2 parm [ dx ]

static void putchar(char ch);
#pragma aux putchar parm [ dl ] = \
  "mov ah, 2h" \
  "int 21h" \
  modify [ ax ];

#pragma aux main modify [ ax bx cx dx di si bp ]
void main() {
  putchar('.');
  putchar_asm('.');
  putchar_asm2('.');
}
```

Compiling with `wcc -3 -s print.c` and then disassembling with `wdis print.o` gives:

```
Segment: _TEXT BYTE USE16 00000011 bytes
0000				main_:
0000  B2 2E				mov		dl,0x2e
0002  B4 02				mov		ah,0x02
0004  CD 21				int		0x21
0006  6A 2E				push		0x002e
0008  E8 00 00				call		putchar_asm_
000B  BA 2E 00				mov		dx,0x002e
000E  E9 00 00				jmp		putchar_asm2_

Routine Size: 17 bytes,    Routine Base: _TEXT + 0000
```

This output fails to work with the first pure assembly implementation.  The correct thing to do would be to emit `mov dl, 0x2e` in place of `push 0x002e`.

**Comment by jmalak** [comment]
You should read carefuly [description of register allocation for C function](https://open-watcom.github.io/open-watcom-v2-wikidocs/cguide.html#16Mbit__Calling_Conventions_for_NonM80x87_Applications).
If you declare some external function then you can not change anything there are some rules defined in code generator that can not be overide by #pragma aux, by example parameters allocation rules. You can not do some changes if you do it then result is unexpected results. By example for function putchar_asm you broke this rule for register allocation that code generator select to use passing by stack. Your function must use C rule for parameter passing, you can not define your parameter how you want and expect that code generator will use them.
Take into account that you are trying to use external assembly function which is C (code generator with use C rules), but you are trying to overide code generator rules. As result is code generator is not able allocate any register and therefore  changes to use stack as last possibility.

**Comment by jmalak** [comment]
following code is rewritten your code to work properly with #pragma aux.

```
void putchar_asm(char ch);
#pragma aux putchar_asm = \
  "mov ah, 0x2" \
  "int 0x21" \
  parm [ dl ] modify [ax]

void putchar_asm2(char ch);
#pragma aux putchar_asm2 = \
  "mov ah, 0x2" \
  "int 0x21" \
  parm [ dl ] modify [ax]

static void putchar(char ch);
#pragma aux putchar = \
  "mov ah, 2h" \
  "int 21h" \
  parm [ dl ] modify [ ax ];

#pragma aux main modify [ ax bx cx dx di si bp ]
void main() {
  putchar('.');
  putchar_asm('.');
  putchar_asm2('.');
}
```
and disassembled code
```
_TEXT           SEGMENT BYTE PUBLIC USE16 'CODE'
                ASSUME CS:_TEXT, DS:DGROUP, SS:DGROUP
main_:
        mov             dl,2eH
        mov             ah,2
        int             21H
        mov             dl,2eH
        mov             ah,2
        int             21H
        mov             dl,2eH
        mov             ah,2
        int             21H
        ret
_TEXT           ENDS

```

**Comment by jmalak** [comment]
anyway what is purpose of this construct ?
```
#pragma aux main modify [ ax bx cx dx di si bp ]
void main()
....

```

**Comment by negge** [comment]
> following code is rewritten your code to work properly with #pragma aux.

Right, I already had included an example that used `#pragma aux` with the assembly inline.  This bug was about `#pragma aux` treating external assembly functions different from the inline ones, despite accepting the same syntax.

I am familiar with the `__watcall` register calling convention.  However, the `#pragma aux parm` allows for overriding the registers used in this calling convention.  I don't see how it is inconsistent to specify an 8-bit register for an 8-bit parameters when doing this overriding, particularly when using 8-bit registers for inline assembly definitions works with the register allocator just fine.

**Comment by negge** [comment]
> #pragma aux main modify [ ax bx cx dx di si bp ]

This is being used to tell the compiler that none of the register need to be preserved in the main() function.  A minor optimization for just the entry point of the program, but when size coding this can save a dozen bytes or so.

**Comment by jmalak** [comment]
Sorry it is not bug because what is difference between external function declared as C? it can be write in any language but must follow C calling convention.
#pragma aux is not something which can use beginner because it directly interact with code generator.
You have wrong expectaition about #pragma aux. this functionality is defined by code generator not by what you want and what you thing.

If you read properly what I wrote before the definition of main is something related to run-time environment that if you are using OW C run-time library then you do something what can only do problems.
Don't try to use #pragma aux for thing which you don't understand.

**Comment by jmalak** [comment]
There is big difference in register allocation for in-line and external function.
in-line function must have defined registers if you don't use standard allocation rule.
external function use different allocation mechanism it use function type definition which contains rules for register allocation for parameters. You cannot use any registers but only some and compiler try allocate by defined order. If you break logic of allocation then it is possible that code generator put parameter on stack.
your assumption that no difference between in-line assembly and externally defined function is absolutely wrong.

**Comment by negge** [comment]
> Sorry it is not bug because what is difference between external function declared as C? it can be writen in any language but must follow C calling convention.

I guess I am confused.  When you use `#pragma aux` to override the register calling convention, we are no longer in the realm of interfacing with another standard C compiler.  The point of this compiler feature is to give the user the ability to interface with externally defined functions from any language right?

> #pragma aux is not something which can be used by beginner because it directly interact with code generator.

I am certainly not a beginner.  I've written plenty of C and assembly code before (among other languages) and even wrote my own 16 and 32 bit linker for OMF object files.  I was able to quickly debug what wcc was doing here and why it did not my (and others) expectations.

> You have wrong expectaition about #pragma aux. this functionality is defined by code generator not by what you want and what you thing. May be documentation is not clear about all aspects of #pragma aux.

I understand that `#pragma aux` does one thing and what I am asking for is another.  That was the point of filing this bug.  I think reading the example above, the user intent (what the programmer asked for) is clear and fully specified.

> If you read properly what I wrote before the definition of main is something related to run-time environment that if you are using OW C run-time library then you do something what can only do problems.

Again, I have my own linker which I am using and so I do understand what I am doing here.

> Don't try to use #pragma aux for things which you don't understand.

Thanks for the vote of confidence.

**Comment by jmalak** [comment]
Below is sample how to use properly #pragma aux for external function
```
void putchar_asm1(char ch);
#pragma aux putchar_asm1 \
  parm [ dx ]

void putchar_asm2(char ch);
#pragma aux putchar_asm2 \
  parm [ bx ]

void putchar_asm3(char ch);
#pragma aux putchar_asm2 \
  parm [ cx ]

extern void putchar(char ch);
#pragma aux putchar = \
  "mov ah, 2h" \
  "int 21h" \
  parm [ dl ] modify [ ax ];

#pragma aux main modify [ ax bx cx dx di si bp ]
void main() {
  putchar_asm1('.');
  putchar_asm2('.');
  putchar_asm3('.');
  putchar_asm4('.');
  putchar('.');
}

```

```
_TEXT           SEGMENT BYTE PUBLIC USE16 'CODE'
                ASSUME CS:_TEXT, DS:DGROUP, SS:DGROUP
main_:
        mov             dx,2eH
        call            near ptr putchar_asm1_
        mov             cx,2eH
        call            near ptr putchar_asm2_
        mov             ax,2eH
        call            near ptr putchar_asm3_
        mov             ax,2eH
        call            near ptr putchar_asm4_
        mov             dl,2eH
        mov             ah,2
        int             21H
        ret
_TEXT           ENDS
```

**Comment by negge** [comment]
> Below is sample how to use properly #pragma aux for external function
> 
> ```
> void putchar_asm1(char ch);
> #pragma aux putchar_asm1 \
>   parm [ dx ]
> 
> void putchar_asm2(char ch);
> #pragma aux putchar_asm2 \
>   parm [ bx ]
> 
> void putchar_asm3(char ch);
> #pragma aux putchar_asm2 \
>   parm [ cx ]
> 
> extern void putchar(char ch);
> #pragma aux putchar = \
>   "mov ah, 2h" \
>   "int 21h" \
>   parm [ dl ] modify [ ax ];
> 
> #pragma aux main modify [ ax bx cx dx di si bp ]
> void main() {
>   putchar_asm1('.');
>   putchar_asm2('.');
>   putchar_asm3('.');
>   putchar_asm4('.');
>   putchar('.');
> }
> ```
> 
> ```
> _TEXT           SEGMENT BYTE PUBLIC USE16 'CODE'
>                 ASSUME CS:_TEXT, DS:DGROUP, SS:DGROUP
> main_:
>         mov             dx,2eH
>         call            near ptr putchar_asm1_
>         mov             cx,2eH
>         call            near ptr putchar_asm2_
>         mov             ax,2eH
>         call            near ptr putchar_asm3_
>         mov             ax,2eH
>         call            near ptr putchar_asm4_
>         mov             dl,2eH
>         mov             ah,2
>         int             21H
>         ret
> _TEXT           ENDS
> ```

Note that the call to putchar_asm2_ is passing with cx and not bx as specified because you have a typo in the example where you redefine the parameters passed to putchar_asm2() below the definition of putchar_asm3().  This is why both putchar_asm3() and putchar_asm4() are passing by ax (because they have no #pragam aux defined).

**Comment by jmalak** [comment]
it is copy and past mistake. I updated sample above to be correct.
I hope that now you understand where you did mistake.

**Comment by negge** [comment]
> I hope that now you understand where you did mistake.

There is still a gap here right?  Your example also shows this.  It is not possible to use 8-bit registers to pass 8-bit values using #pragma aux on an external function, despite it being perfectly fine for an inline function.  The compiler has the information, the register allocator just needs to do the same thing in the former case as it does in the later.

Can you point me at the source code where this happens?  I can try to submit a patch to fix this.

**Comment by jmalak** [comment]
No it is standard documented functionality. As I noted you must read documentation carefully.
below is link [16-bit:  Passing Arguments in Registers](https://open-watcom.github.io/open-watcom-v2-wikidocs/cguide.html#16Mbit__Passing_Arguments_in_Registers)

......
char
Arguments whose size is 1 byte (e.g., arguments of type char) are promoted to 2 bytes and are then assigned registers as if they were 2-byte arguments.
......
