### ISSUE TITLE
The file setup.inf cannot be found

### ISSUE THREAD

**Issue by carverh** [open-watcom/open-watcom-v2#655]
Error when running open-watcom-2_0-c-linux-x86.
OS: Ubuntu 20.04
![image](https://user-images.githubusercontent.com/7690997/102120728-ce29e280-3df7-11eb-92e8-326ae5acaf27.png)

**Comment by jmalak** [comment]
Please what is your PATH environment variable contents?

**Comment by carverh** [comment]
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
adding . does not help.

**Comment by jmalak** [comment]
Thanks for your info. 
It looks like some problem with accessing installer file which contains setup.inf configuration file.
I am using Ubuntu 18.04 for testing installers and latest version of both 32 and 64-bit installers from Github works OK.
I will try to install Ubuntu 20.x on Virtual Machine and try to reproduce.

**Comment by jmalak** [comment]
Did you tried open-watcom-2_0-c-linux-x64 (64-bit installer)?

**Comment by jmalak** [comment]
I checked latest installers 32 and 64-bit on Ubuntu 20.04 and both are working.
I am not able to reproduce your problem on Ubuntu 20.04.
I run installers from command line in terminal window.
