### ISSUE TITLE
Problems with 32bit tools on AMD Ryzen?

### ISSUE THREAD

**Issue by jirkakunze** [open-watcom/open-watcom-v2#659]
When I set the PATH environment variable to WATCOM/binl on my notebook with AMD Ryzen 7 4700U I get the following error message when building a project:

```
jkunze@3of4:~/development/pcgeos/Tools/pmake/pmake$ wmake install
Open Watcom Make Version 2.0 beta Nov  1 2020 00:20:20 (32-bit)
Copyright (c) 2002-2020 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
Error(F38): (arch.obj) does not exist and cannot be made from existing files
Error(E02): Make execution terminated
```

If I set the environment variable to WATCOM/binl64 the project can be built without problems.

On my desktop computer with Intel i7 both variants work.

**Comment by jmalak** [comment]
what `wmake install` command mean?

**Comment by jmalak** [comment]
I have no AMD Ryzen processor available, that I can not test it on this processor.
But OW doesn't use anything specific for Intel or AMD processor that 32-bit code should be compatible with both.

I did a test on Intel i5 processor by latest 'Current Build' 32-bit Linux installer and by building full OW source tree by this OW 2.0 Linux 32-bit compiler version with following OW build setvars.sh copy setup.
```
export OWTOOLS=WATCOM
export WATCOM=/home/jiri/ow20-32
export PATH=$WATCOM/binl:$PATH
export EDPATH=$WATCOM/eddat
export INCLUDE=$WATCOM/lh
```
No any problems.
I don't know how you have configured OW 2.0 32-bit Linux compiler, I am using following setup for any build on Linux (32-bit tools version).
```
export WATCOM=/home/jiri/ow20-32
export PATH=$WATCOM/binl:$PATH
export EDPATH=$WATCOM/eddat
export INCLUDE=$WATCOM/lh
```
wmake banner
```
Open Watcom Make Version 2.0 beta Jan  3 2021 14:38:23 (32-bit)
Copyright (c) 2002-2021 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
```
wcc386 banner
```
Open Watcom C x86 32-bit Optimizing Compiler
Version 2.0 beta Jan  3 2021 00:24:21 (32-bit)
Copyright (c) 2002-2021 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
```

**Comment by jmalak** [comment]
try command `wmake -sn install` to get details about executed commands

**Comment by rdos314** [comment]
I've run both RDOS device drivers and applications built with OpenWatcom on Ryzen & thread ripper, and it works as it should. Thus, I don't think the problem is with Ryzen specifically.

OTOH, I usually don't use the optimization switches..

**Comment by jmalak** [comment]
Leif, thanks for confirmation Ryzen compatibility.
it could be some configuration or make file issue.

**Comment by jirkakunze** [comment]
I experimented a little more. Under various Ubuntu versions and under Linux Mint, I can reproduce the problem described. Under OpenSuse everything works so far.

This is obviously a problem for the Ubuntu team.
