### ISSUE TITLE
Error! E1058: Cannot use typedef 'Db' as a variable, sqlite

### ISSUE THREAD

**Issue by omm** [open-watcom/open-watcom-v2#661]
I'm got an error while test fresh open watcom build **(Version 2.0 beta Jan 13 2021 00:34:51 (32-bit))** with [harbour](https://github.com/harbour/core)
```
3rd\sqlite3\sqlite3.c(98421): Error! E1058: Cannot use typedef 'Db' as a variable
3rd\sqlite3\sqlite3.c(112141): Warning! W1069: String literal not terminated before end of line
```
You can download sqlite3 from [sqlite3.c](http://sqlite.org/2013/sqlite-amalgamation-3080200.zip) and try to compile it, and result is
```
sqlite3.c(98432): Error! E1058: Cannot use typedef 'Db' as a variable
sqlite3.c(112154): Warning! W1069: String literal not terminated before end of line
Error: Compiler returned a bad status compiling "sqlite3.c"
```

Tested with open watcom (Version 2.0 beta Nov 13 2020 00:32:52 (32-bit)) it's all ok.

Can you review it?

Thanks and regards.

**Comment by jmalak** [comment]
Could you give here more info as compiler command and relevant code fragment for this issue.

**Comment by omm** [comment]
I'm just unzip [sqlite3.c](sqlite.org/2013/sqlite-amalgamation-3080200.zip) and the command is 
```
call c:\watcom\owsetenv.bat
wcc386 sqlite3.c
```

**Comment by jmalak** [comment]
Thanks, I see.
I will fix it ASAP, probably related to changes for C99 compatibility.

**Comment by omm** [comment]
Ok, under harbour the next output (command and options)
```
C:\Dev\test2\sqlite3>call c:\watcom\owsetenv.bat
Open Watcom Build Environment
hbmk2: Compiling...
sqlite3.c(98421): Error! E1058: Cannot use typedef 'Db' as a variable
sqlite3.c(112141): Warning! W1069: String literal not terminated before end of line
hbmk2[sqlite3]: Error: Running C/C++ compiler. 1
wcc386.exe -6s -fp6 -onaehtr -s -ei -zp4 -zt0 -oi -zq -bt=nt  -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_OM
T_DEPRECATED -DSQLITE_ENABLE_COLUMN_METADATA -w1 -wcd124 -wcd136 -wcd201 -bc -DUNICODE -ic:\dev\harbour\include sqlite3.c -fo=.
\lib\win\watcom\.hbmk\sqlite3\sqlite3.obj
hbmk2[sqlite3]: Exit status: 6: failed in compilation (Harbour, C compiler, Resource compiler)
```

**Comment by jmalak** [comment]
it is fixed now.

**Comment by omm** [comment]
Thanks, i will test.

**Comment by omm** [comment]
Ok, tested on **Version 2.0 beta Jan 16 2021 00:24:03 (32-bit)** and all works fine.

Thanks and best regards.
