### ISSUE TITLE
Build error at wmake on FreeBSD

### ISSUE THREAD

**Issue by yamori813** [open-watcom/open-watcom-v2#666]
Hi

I build OW on FreeBSD/i386 12.2R.

I have build error on wmake. I seem bld/wmake/postmake is not compatible BSD make.

% ./build.sh
Open Watcom build environment (CLANG version=10, CYEAR=2021)
cc -g -O2 -I. -I../h -I../../watcom/h -I../../lib_misc/h -D__BSD__ -D__UNIX__ -DBOOTSTRAP -D_BLDVER=1300 -D_CYEAR=2021 -c ../../builder/c/wsplice.c
cc -g -O2 -I. -I../h -I../../watcom/h -I../../lib_misc/h -D__BSD__ -D__UNIX__ -DBOOTSTRAP -D_BLDVER=1300 -D_CYEAR=2021 -c ../../watcom/c/clibext.c
cc -g wsplice.o clibext.o -o wsplice.exe
./wsplice.exe -kENGLISH -f 'pick((MSG_USAGE_BASE+%#%+), "%s", "")' ../h/usage.sp usage.gh
cc -I../../watcom/h -o cretype.exe 
cc: error: no input files
*** Error code 1

Stop.
make: stopped in /usr/home/hiroki/ow/ow2/bld/wmake/binbuild
wmake bootstrap build error

**Comment by jmalak** [comment]
It is strange.
Please could you get more verbosed output from make on freeBSD?
It should be command line option like "-d A"
It looks like problem with $< macro that is blank for some reason to build cretype.exe.

**Comment by jmalak** [comment]
It seems I find out source of problem.
It looks like $< macro is defined only for implicit rules.
I replace it by $? even if it is not the same, but for our make file with only 1 dependent it works properly (it contains all dependent = only source file).
Please check it on FreeBSD.

**Comment by yamori813** [comment]
This is work fine. But I don't know why. I don't detailed Makefile macro. sorry.

```
--- a/bld/wmake/posmake
+++ b/bld/wmake/posmake
@@ -81,7 +81,7 @@ usage.gh : ../h/usage.sp wsplice.exe
        ./wsplice.exe -kENGLISH -f 'pick((MSG_USAGE_BASE+%#%+), "%s", "")' ../h/usage.sp $@
 
 cretype.exe : ../c/cretype.c
-       $(CC) -I../../watcom/h -o $@ $<
+       $(CC) -I../../watcom/h -o $@ ../c/cretype.c
 
 isarray.gh : cretype.exe
        ./cretype.exe $@
```

**Comment by jmalak** [comment]
It looks like freeBSD make is not fully POSIX compliant.
Now wmake build make file uses POSIX construct working with freeBSD make.
It should be working in the future when freeBSD will be fully POSIX compliant.

**Comment by jmalak** [comment]
I add .POSIX directive which is required by stabndard.
I don't know if this fix your problem.

**Comment by jmalak** [comment]
I rework the wmake code a little bit to use POSIX setenv instead of putenv, commit 54a05bd6ea3a4e7dd7914e7f4021862c708c831f .
I also set POSIX compliance version 200112L and setup make file to use POSIX standard by directive .POSIX:.
Please, check if a problems continue or if it is fixed.
