### ISSUE TITLE
__saveregs keyword means 3 different things in 3 different places?

### ISSUE THREAD

**Issue by tkchia** [open-watcom/open-watcom-v2#667]
Good day,

I have been trying to use Open Watcom's `__saveregs` keyword, but I am confused about what it is supposed to do.

The _User's Guide_ (`cguide.pdf`) says

> Open Watcom C/C++ recognizes the `__saveregs` keyword which is an attribute used by C/C++ compilers to describe a function that must save and restore all registers.

while the _Language Reference_ (`clr.pdf`) says

> The `__saveregs` keyword may be used with functions.  It is provided for compatibility with Microsoft C, and has no effect in Open Watcom Cⁱ⁶ and C³².

Meanwhile, for the actual _implementation_ of `__saveregs` (as of 2.0 beta May 17 2020), it seems the compiler does add some code to save registers --- but only the segment registers.

I think it will be good to clear up what the "correct" intended meaning of `__saveregs` really is.

Thank you!

**Comment by jmalak** [comment]
Thanks for this report.
It is really wrong in "Language reference" guide.
__saveregs means to save all segment registers.

**Comment by tkchia** [comment]
Hello @jmalak,

Is `__saveregs` supposed to save other registers too --- e.g. the general purpose registers and flags register?

Thank you!

**Comment by jmalak** [comment]
No it is only for segment register.
If you want to save all registers and flags then you can specify function with __interrupt modifier.

**Comment by tkchia** [comment]
Hello @jmalak,

Thanks for the clarification!
