### ISSUE TITLE
_lineto under dos not working

### ISSUE THREAD

**Issue by MohammadKhashashneh** [open-watcom/open-watcom-v2#670]
Hi,
There seems to be an issue with _**_lineto**_ (graph.h) under dos.
I was trying a sample similar to the docs but the executable keeps crashing, and sometimes crashes dosbox along with it.
I'm not sure if this is related to dosbox or not, but I doubt the function works as intended since I'm trying to draw a tilted line e.x. (50, 50) to (100, 100) but draws a horizontal line instead! _**_putpixel**_ works fine by the way.

sample code
```
// line.c
#include <conio.h>
#include <graph.h>

int  main(void) {
        _setvideomode(_VRES16COLOR);
        _setcolor(5);
        _moveto(50, 50);
        _lineto(100, 100);
        getch();
        _setvideomode(_DEFAULTMODE);
        return 0;
}
```
I'm using the latest release (March/15th) and compiling with `wcl -mm -fe=line line.c`

thanks
Moh. K.
![lineto01](https://user-images.githubusercontent.com/11486174/111229280-50d85e80-85ee-11eb-9850-4518b2c469fe.png)

**Comment by jmalak** [comment]
Thanks for bug report.
I will fix it.
Anyway I tested it with _MAXRESMODE and it works.
It looks like mode switching support problem.

**Comment by MohammadKhashashneh** [comment]
Thank you for the reply and your effort.
I did some more testing and tried all the other modes including _MAXRESMODE but faced the same issue when using _lineto.
Only mode 19 (_MRES265COLOR) do not crash, but still, the line does not render correctly.
Modes do switch and allow drawing pixels fine when using _setpixel.

I will try to dig into it more after I successfully build from source under dosbox.

Thanks again

**Comment by jmalak** [comment]
I compile it with `wcl -bcl=dos line.c` for 16-bit DOS application

**Comment by MohammadKhashashneh** [comment]
I tried with -bcl=dos but didn't work either.
I tried both from dosbox and cross compiling on linux with the same result.

I would like to help debugging the issue but couldn't build the ow master branch neither from linux nor from dosbox even after setting up the setvars.sh and setvars.bat according to my environment. 
On linux I tried with gcc and clang and both complained about `/usr/bin/ld: cannot find -lc` 
On dosbox, the error is `Error(F38): (usage.gh) does not exist and cannot be made from existing files` For some reason `bld/wmake/h/usage.sp` becomes empty right after issuing the build command. Should I open separate issues for those?

Next I will try to use an older working ow installation to build the app, and maybe build ow on Linux using wcc instead.

**Comment by jmalak** [comment]
It is strange, because `bld/wmake/h/usage.sp` is source file.
If it is blank then you have incorrect sources and next errors are result of missing content of this file.
`usage.gh` is created from `bld/wmake/h/usage.sp` file by `wsplice` utility.

**Comment by MohammadKhashashneh** [comment]
@jmalak  this is now fixed.
I tested after building on linux with the assist #751
thanks
