### ISSUE TITLE
Question: DOS 16 bit without C library nor DOS access code

### ISSUE THREAD

**Issue by cocus** [open-watcom/open-watcom-v2#675]
Hi!
I'm tinkering with an old 80c186, which doesn't run DOS. I've been using smlrc targetting the "small" memory model, with a custom loader (copies .text to the bottom, then .data after it, CS, SS, ES, DS are equal). The binary ends up at the bottom of the memory (0x00000) and seems to work fine. However, smlrc has a lot of limitations and I can't move forward with them. I want to give OW a try. However I haven't found a way to create an EXE from the commandline that comply to the above limitations. If this is possible, do you mind providing example commands?
In that regard, I have a .asm file to initialize the segments in ram, which then jumps to the C code; and one or multiple C files linked into the same EXE.

Thanks!

**Comment by jmalak** [comment]
if you modify your startup code to be usable with OW then standard commands could help you.
first look on the OW startup code
bld/clib/startup/a/cstrt086.asm

most important is segment order, it is how OW use it
```
if _MODEL and _TINY
DGROUP group _TEXT,CONST,STRINGS,_DATA,DATA,XIB,XI,XIE,YIB,YI,YIE,_BSS
else
DGROUP group _NULL,_AFTERNULL,CONST,STRINGS,_DATA,DATA,XIB,XI,XIE,YIB,YI,YIE,_BSS,STACK
endif
```
You need to modify it for your memory model and your segment names if you use different from OW default names.
Next important thing is to place entry point to beginning of code.
OW uses `_cstart_` symbol.
Start of code looks like
```
        assume  nothing
        public  _cstart_

        assume  cs:_TEXT

if _MODEL and _TINY
        org     0100h
endif

_cstart_ proc near
        jmp     around
```

**Comment by jmalak** [comment]
You can link to DOS exe format and next use EXE2BIN utility to convert it to binary format without relocation.
Ther is also "bin" or "raw" linker output which could create you binary image directly.
If you have a problem with linking then put here linker map file which help us to understand your problem.

**Comment by jmalak** [comment]
To your question about commands. 
You should add following compiler options for C compiler (16-bit, DOS target and small memory model)

`wcc -bt=dos -ms`

For linker you should add

`wlink sys dos libfile <your startup code module>`

After linking you should use

`exe2bin <exe file name> <output binary file>`

**Comment by cocus** [comment]
Thanks for your reply!
I've installed open-watcom-2_0-c-linux-x64 on my linux machine, and I've created a "work in progress" loader (which by the looks of it, doesn't load anything, but I just wanted to make it build. Hopefully I can copy the initialization routines I'm already using on smlrc later on).

This is my crt.asm:
```

include mdef.inc
include xinit.inc


.286p

        name    cstart

        assume  nothing


if _MODEL and _TINY
 DGROUP group _TEXT,CONST,STRINGS,_DATA,DATA,XIB,XI,XIE,YIB,YI,YIE,_BSS
else
 DGROUP group _NULL,_AFTERNULL,CONST,STRINGS,_DATA,DATA,XIB,XI,XIE,YIB,YI,YIE,_BSS,STACK
endif

_TEXT   segment word public 'CODE'

        extrn   __CMain                 : proc
        assume  ds:DGROUP

        INIT_VAL        equ 0101h
        NUM_VAL         equ 16

_NULL   segment para public 'BEGDATA'
__nullarea label word
        dw      NUM_VAL dup(INIT_VAL)
        public  __nullarea
_NULL   ends

_AFTERNULL segment word public 'BEGDATA'
        dw      0                       ; nullchar for string at address 0
_AFTERNULL ends

CONST   segment word public 'DATA'
CONST   ends

STRINGS segment word public 'DATA'
STRINGS ends

_DATA   segment word public 'DATA'
_DATA   ends


DATA    segment word public 'DATA'
DATA    ends

_BSS    segment word public 'BSS'

        extrn   _edata                  : byte  ; end of DATA (start of BSS)
        extrn   _end                    : byte  ; end of BSS (start of STACK)

_BSS    ends

STACK_SIZE      equ     800h

STACK   segment para stack 'STACK'
        db      (STACK_SIZE) dup(?)
STACK   ends


        assume  nothing
        public  _cstart_

        assume  cs:_TEXT

_cstart_ proc near
        call    __CMain
_cstart_ endp
_TEXT   ends

        end     _cstart_
```
Note: I've taken most of the code from cstrt086.asm, probably removed important things, but I'm not well versed in these things.

My main.c:
```
int main(void)
{
    return 0;
}
```

Then I ran:
```
$ wcc -bt=dos -ms main.c
$ file main.o
main.o: 8086 relocatable (Microsoft), "/home/cocus/mystuff/80c188/ow-80188/main.c"
$ wasm crt -i=/usr/bin/watcom/src/startup/ -bt=DOS -ms -1
$ wlink sys dos libfile crt file main
Open Watcom Linker Version 2.0 beta Apr  4 2021 00:22:54 (32-bit)
Copyright (c) 2002-2021 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
Warning! W1115: system block dos: environment name WATCOM not found
Warning! W1115: system block dos: environment name WATCOM not found
loading object files
searching libraries
Warning! W1008: cannot open emu87.lib : No such file or directory
Warning! W1008: cannot open math87s.lib : No such file or directory
Warning! W1008: cannot open clibs.lib : No such file or directory
Error! E2028: __CMain is an undefined reference
Error! E2028: __STK is an undefined reference
Error! E2028: _small_code_ is an undefined reference
creating a DOS executable
file crt.o(cstart): undefined symbol __CMain
file main.o(/home/cocus/mystuff/80c188/ow-80188/main.c): undefined symbol __STK
```
Now, I think __CMain should've defined on the main.o object file, but doesn't look like it is, or there's something weird on the linking phase.
Also, why is the main.o looking for an __STK symbol/region? Could it be said symbol was declared in one of the .inc files (namely langenv.inc and exitwmsg.inc) I didn't include (since they were missing on my OW install)?

Please note that I'm completely oblivious to a lot of the core concepts here, since I'm a newcomer to OW and 8086 code.

Thanks!

**Comment by jmalak** [comment]
`_cstart_` should contain only your startup code which cáll C `main` function after initialization.
Probably you use `int main( void )` prototype, no command line.
__STK is stack check routine, you can implement as function do nothing in your startup code or you can use C compiler option `-s` (suppress stack check __STK routine call).
If you don't want OW run-time libraries then `-zl` compiler option remove these referencies to OW run-time libraries.

**Comment by cocus** [comment]
Great, by using `-s` I got rid of the __STK reference error. However, from the ASM code, I can't access the "main" function on the C code. I've tried referencing it as `_main`, `__main`, `main` and no dice.
Besides that, the linker is complaining about the `_small_code_` reference, which I haven't seen it on the original cstrt086.asm, so I'm pretty sure I didn't forget about it. Maybe it's defined elsewhere?

Thanks!

**Comment by jmalak** [comment]
I think proper symbol for `C main` and 16-bit code is `main_`.
_small_code_ symbol is using for checking code memory model mismatch.
You can define if in your startup code if it is fixed model or you can use `-zls` option to suppress emitting such OW symbols.
