### ISSUE TITLE
Build Test Issues

### ISSUE THREAD

**Issue by joegittingherdone** [open-watcom/open-watcom-v2#676]
I got an error when I was doing the testing steps documented here:

[https://github.com/open-watcom/open-watcom-v2/wiki/Build](https://github.com/open-watcom/open-watcom-v2/wiki/Build)

Although I've been programming for 40 years (and first bought Watcom C/C++ in the 1990s at a brick and mortar store!), I've never dealt with an open open source project before.  Are these issues worth reporting here?  I was using 64-bit Windows 7 when the command "builder test" gives me an error.  I think there are bugs in at least "bf01.c" ("u1" should be "u" on line 42) and "sizeof02.c" (parentheses are needed for line 15), but I wanted someone else to confirm that I'm doing this correctly first.

I originally executed build.bat and it worked, making a "rel" directory.  I then used a a .CMD file to set the environment to point at "rel", and then executed "builder test".

**Comment by jmalak** [comment]
Sorry, but some of tests on some platforms are not working, still not fully migrated.
Take into account some of tests are diagnostics test therefore if must fail, it can be a bug in handling such failures.
Some tests use strange construct to test some specific bug.
Also Language standard is important, C compiler is by default C89 etc.
If you give here some log fragment we can discus why it is not working.

**Comment by joegittingherdone** [comment]
I guess that is my main question: Is this worth your effort?  I don't want to waste your time because you are probably working on more important parts of this project. 

**_I_** don't care if this testing part works; I was only following the documentation to get started.  _My_ goal is to attempt to fix Watcom's text editor.

**Comment by jmalak** [comment]
Generally tests should succeed on DOS, OS/2 and WIN32 platforms.
On Linux some tests are failing due to missing Multi-byte support.

Anyway test should be working to get status of Current OW build and eliminate some regressions.

**Comment by joegittingherdone** [comment]
Okay; for starters, can you confirm the issues I found in the two files that I mentioned above ("bf01.c" and "sizeof02.c")?

**Comment by jmalak** [comment]
bf01.c and sizeof02.c are positive tests that they should not fail.

**Comment by joegittingherdone** [comment]
Does line 15 have valid C syntax:

[https://github.com/open-watcom/open-watcom-v2/blob/master/bld/ctest/positive/source/sizeof02.c](https://github.com/open-watcom/open-watcom-v2/blob/master/bld/ctest/positive/source/sizeof02.c)

**Comment by jmalak** [comment]
Yes, it is valid C syntax.

**Comment by joegittingherdone** [comment]
> What host platform you are using for testing?

I mentioned 64-bit Windows 7 above; is that what you're asking?  It is an Intel-based machine that had OW _installed_ years ago.   I _recently_ downloaded the OW source from here into a different directory (so I now have both on the same machine).  I successfully built that source code using the [instructions](https://github.com/open-watcom/open-watcom-v2/wiki/Build) here. 

> Be carefull if you run builder test then it supposes you have installed new (builded) version of OW.
If you want to check currently build version (without installation) then run command builder buildtest.

Ah!  This is not clear in the Testing section of the [Build documentation](https://github.com/open-watcom/open-watcom-v2/wiki/Build).  May I make a minor edit to that page, or does someone else maintain that?  

I tried running `builder buildtest`, but it kept displaying dozens of DOS 16-bit incompatibility error dialog boxes and each one required me to click an OK button.  Eventually, I cancelled the test and will probably skip the test for now because it's the OW editor I'm interested in.

**Comment by jmalak** [comment]
Oh sorry, you can run test on host which is capable to handle it.
You can not run 16-bit tests on 64-bit host, it is not supported.
You can run  only 32-bit tests on 64-bit host if support 32-bit application.
By default only 32-bit tests are run, you must have something wrong on your box if it runs 16-bit tests.
I am using old Windows XP VM to run 16/32-bit tests.

**Comment by joegittingherdone** [comment]
I see.  Thank you for your help.
