### ISSUE TITLE
Win32 Image editor (latest git) lines only

### ISSUE THREAD

**Issue by HnkGitHub** [open-watcom/open-watcom-v2#678]
Platform: Windows 2K

The image editor only outputs lines when using the shape tools.e.g. the rectangle tool draws a line when it should draw a rectangle. Same for other shapes.

**Comment by jmalak** [comment]
thanks for bug report
It should be fixed by [commit](https://github.com/open-watcom/open-watcom-v2/commit/253ec7797a7d5d5a200067875e8fb5c802567130)

**Comment by HnkGitHub** [comment]
It works. Thanks!

**Comment by jmalak** [comment]
You are welcome
