### ISSUE TITLE
linux build failure

### ISSUE THREAD

**Issue by HnkGitHub** [open-watcom/open-watcom-v2#679]
Platform Debian 10 x86
GCC - 8.4

It's been about a year since linux could successfully complete a build of open-watcom-v2 git.
It's been the same error. A message about not being able to find wcl386 and it happens when building the causeway files. Just attached the relevant portion of the log before it crashed causing the shell to disappear completely off the screen.

[rel.log.txt](https://github.com/open-watcom/open-watcom-v2/files/6305827/rel.log.txt)

**Comment by jmalak** [comment]
sorry I don't understand your problem.
Linux build is normally working (see below)
[Azure pipeline build Win/Linux/OSX](https://dev.azure.com/open-watcom/open-watcom-v2/_build/results?buildId=4947&view=results)

**Comment by HnkGitHub** [comment]
Not building open-watcom-v2 on a windows box. Building on a Linux box, as stated: **Debian 10, x86**

The _build_ environment is Linux, using the gnu gcc 8.4 compiler to bootstrap

I included the last lines of the rel.log which show a build failure. It's strange. When I enter the open-watcom-v2/bld/wcl/386/linux386 and use wmake to build the wcl386 linux file, it builds it. But it names the executable as wcl386.exe, not wcl386. Apparently, the mif file has been altered and it's not copying the executable to the binbuild directory, either. Hence, the build process complains about not finding the wcl386 file.  

On a windows machine the windows build environment successfully builds the linux files, os2, windows, etc and successfully completes the build, including the documentation and the distribution files. 

This is not an isolated bug on this machine. It does the same on a Linux x64 machine, failing at the same point.

**Comment by jmalak** [comment]
it looks like configuration bug.
wcl386 can not be called on system which is configured to use gcc bootstrap compiler.
during bootstrap is build only bwcl386 and it is used for regular OW build.
It looks like you have missconfigured it with OW compiler, only if you use OW compiler as bootstrap then wcl386 is used during bootstrap.

**Comment by jmalak** [comment]
below is verbosed output for Linux build for reference

```
../../asm/cw32.asm(975): Note! N594: Extending jump
../../asm/cw32.asm(4511): Note! N594: Extending jump
../../asm/cw32.asm(4520): Note! N594: Extending jump
../../asm/cw32.asm(4522): Note! N594: Extending jump
../../asm/cw32.asm(4524): Note! N594: Extending jump
%write cw32.lnk debug dwarf op nored op symfile op map sys dos lib doslfnl.lib  op verbose, statics disable 1080
bwlink op q name cw32.exe @cw32.lnk
bcwc cw32.exe cwstub.exe
bwasm -q -D_BLDVER=1300 -D_CYEAR=2021 -we -d1 -DNDEBUG -fo=cwdstub.obj -w8 -bt=dos -DENGLISH=1 -I"../../inc"       -I"/home/jiri/ow-v2/bld/hdr/dos"   -I"/home/jiri/ow-v2/bld/watcom/h" ../../asm/cwdstub.asm
%write cwdstub.lnk debug dwarf op nored op symfile op map sys dos lib doslfnl.lib  op verbose, statics disable 1014
bwlink op q name cwdstub.exe @cwdstub.lnk
============== 07:25:43 /home/jiri/ow-v2/bld/causeway/cwc/dosi86 ==============
gcc -pipe -D_BLDVER=1300 -D_CYEAR=2021 -fno-asm -fno-common -fsigned-char   -I"/home/jiri/ow-v2/bld/watcom/h" ../../c/mkcode.c -D__UNIX__ -D__FLAT__ -D__LINUX__ -D_M_X64 -D__LINUX_X64__ -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o ./mkcode.exe  -Wl,-Map,mkcode.map /home/jiri/ow-v2/bld/watcom/binbuild/clibext.lib
bwasm -zq -fo=copystub.obj ../../asm/copystub.asm
bwlink system bin op quiet file copystub.obj name copystub.tmp
./mkcode.exe copystub.tmp copystub.gh
bwasm -zq -fo=decstub.obj ../../asm/decstub.asm
bwlink system bin op quiet file decstub.obj name decstub.tmp
./mkcode.exe decstub.tmp decstub.gh
bwcc -zq -D_BLDVER=1300 -D_CYEAR=2021 -j-we -s-oaxt -d1 -x-wpx -xx -zam -fo=cwc.obj -fpi -mc -bt=dos      -wx-wce=310-za99 -DNDEBUG -D_ENABLE_AUTODEPEND  -D__WATCOM_LFN__        -I.  -I"/home/jiri/ow-v2/bld/hdr/dos"   -I"/home/jiri/ow-v2/bld/watcom/h" ../../c/cwc.c
%write cwc.lnk debug dwarf op nored op symfile op map sys dos lib doslfnc.lib
bwlink op q name cwc.exe @cwc.lnk
============= 07:25:44 /home/jiri/ow-v2/bld/causeway/cwc/linux386 =============
gcc -pipe -D_BLDVER=1300 -D_CYEAR=2021 -fno-asm -fno-common -fsigned-char   -I"/home/jiri/ow-v2/bld/watcom/h" ../../c/mkcode.c -D__UNIX__ -D__FLAT__ -D__LINUX__ -D_M_X64 -D__LINUX_X64__ -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o ./mkcode.exe  -Wl,-Map,mkcode.map /home/jiri/ow-v2/bld/watcom/binbuild/clibext.lib
bwasm -zq -fo=copystub.obj ../../asm/copystub.asm
bwlink system bin op quiet file copystub.obj name copystub.tmp
./mkcode.exe copystub.tmp copystub.gh
bwasm -zq -fo=decstub.obj ../../asm/decstub.asm
bwlink system bin op quiet file decstub.obj name decstub.tmp
./mkcode.exe decstub.tmp decstub.gh
bwcc386 -zq -D_BLDVER=1300 -D_CYEAR=2021 -j-we -s-oaxt -d1 -x-wpx -xx -zam -fo=cwc.obj -fpi -mf -zc -bt=linux      -wx-wce=310-za99 -DNDEBUG -D_ENABLE_AUTODEPEND          -I.  -I"/home/jiri/ow-v2/bld/hdr/linux"   -I"/home/jiri/ow-v2/bld/watcom/h" ../../c/cwc.c
%write cwc.lnk debug dwarf op nored op symfile op map sys linux
bwlink op q name cwc.exe @cwc.lnk
============= 07:25:44 /home/jiri/ow-v2/bld/causeway/cwc/linuxx64 =============
gcc -pipe -D_BLDVER=1300 -D_CYEAR=2021 -fno-asm -fno-common -fsigned-char   -I"/home/jiri/ow-v2/bld/watcom/h" ../../c/mkcode.c -D__UNIX__ -D__FLAT__ -D__LINUX__ -D_M_X64 -D__LINUX_X64__ -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o ./mkcode.exe  -Wl,-Map,mkcode.map /home/jiri/ow-v2/bld/watcom/binbuild/clibext.lib
bwasm -zq -fo=copystub.obj ../../asm/copystub.asm
bwlink system bin op quiet file copystub.obj name copystub.tmp
./mkcode.exe copystub.tmp copystub.gh
bwasm -zq -fo=decstub.obj ../../asm/decstub.asm
bwlink system bin op quiet file decstub.obj name decstub.tmp
./mkcode.exe decstub.tmp decstub.gh
gcc -pipe -c -D_BLDVER=1300 -D_CYEAR=2021 -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -march=core2 -msse2 -O -g -static -o cwc.obj  -DNDEBUG -D_M_X64 -D__LINUX_X64__ -D__UNIX__ -D__FLAT__ -D__LINUX__        -I.   -I"/home/jiri/ow-v2/bld/watcom/h" ../../c/cwc.c
../../c/cwc.c: In function ‘ProcessEXE’:
../../c/cwc.c:525:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread( &exe_header, 1, sizeof( exe_header ), f );
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -pipe -D_BLDVER=1300 -D_CYEAR=2021 -static  -O -g -o cwc.exe  -Wl,-Map,cwc.map cwc.obj  /home/jiri/ow-v2/bld/watcom/linuxx64/clibext.lib

```

**Comment by jmalak** [comment]
try to update your configuration script from current setvars.sh

**Comment by HnkGitHub** [comment]
Debian stable (buster) 
arch = i386 
Thsi is the output which appears immediately after running ". ./myvars.sh" in the root directory:
Open Watcom build environment (GCC version=8, CYEAR=2021)

I checked the builder.ctl files. I don't think the exe is a mistake. According to the builder.ctl file, It originally compiles the output as an .exe and then copies the executable file to the binbuild directory without the .exe extrension. And I ran the compiled file with the .exe extension in the linux386 directory and it runs fine as a linux executable.

I'm using wine for the hcrtf and hhc compilers
And dosemu for the DOS environment for the wgml utility. 

If the build system is actually using the bwcl386 file, for building the files, why doesn't the error message say the it can't find bwcl386 instead of saying wcl386?


[relcut.log](https://github.com/open-watcom/open-watcom-v2/files/6330011/relcut.log)

**Comment by jmalak** [comment]
As I write before it must be wrong configuration on your system.
!!!! OW build with gcc can not call wcl386 only bwcl386 (it is build by bootstrap) !!!!
Check your path, it must be something like

`/home/jiri/ow-v2/build/binbuild:/home/jiri/ow-v2/build:/home/jiri/bin:/home/jiri/.local/bin:/usr/local/sbin:/usr/local/bin:....
`

**Comment by jmalak** [comment]
What is important to not have any version of OW on the PATH.
Only possible if you use OW compiler for bootstrap and have configured it by OWTOOLS=WATCOM.
The main decision about configuration is done in `makeinit` file in `build` subdirectory.

```
# setup non-WATCOM tools macros
!ifeq %OWTOOLS VISUALC
__MSVC_TOOLS__ = $+$(%OWTOOLSVER)$-
!else ifeq %OWTOOLS GCC
__GCC_TOOLS__ = $+$(%OWTOOLSVER)$-
!else ifeq %OWTOOLS CLANG
__CLANG_TOOLS__ = $+$(%OWTOOLSVER)$-
!else ifeq %OWTOOLS INTEL
__INTEL_TOOLS__ = $+$(%OWTOOLSVER)$-
!else
# if WATCOM or not defined or unknow value, default to WATCOM
__WATCOM_TOOLS__ = 0
!endif

# setup WATCOM tools version
bld_watcom_ver = 0
!ifndef bootstrap
# if it is not bootstrap then use current build version
__WATCOM_TOOLS__ = $(bld_ver_tool)
!else ifeq %OWTOOLS WATCOM
# if bootstrap and WATCOM tools then use tools version
bld_watcom_ver = $+$(%OWTOOLSVER)$-
__WATCOM_TOOLS__ = $(bld_watcom_ver)
!endif
```

next configuration decision is done in `build/mif/local.mif` for non-WATCOM compilers
by example there are guards as 

```
##############################################################################
#
# definitions for VISUALC and INTEL toolchains
#
##############################################################################
!if defined("__MSVC_TOOLS__") || defined("__INTEL_TOOLS__")

!if defined("__NT__")

!if !defined( "__WATCOM_TOOLS__" ) || "$(bld_cpu)" == "x64"
```

Anyway `bld_cl` macro must contains currently used compile and link utility.

For bootstrap phase it contains
`gcc` for gcc tools based build
`wcl386` for WATCOM tools based build

For regular build it contains
`gcc` for gcc tools based build
`bwcl386` for WATCOM tools based build

**Comment by jmalak** [comment]
Maybe I overlooked, are you using 32-bit or 64-bit version of Debian?
If you are using 32-bit version of Debian than only WATCOM tools can be used for OW build.

**Comment by HnkGitHub** [comment]
32 bit. I'll check it on a64 bit system.

**Comment by jmalak** [comment]
!!! On 32-bit system you must use OW compilers as bootstrap compiler !!!
You can use OpenWatcom 1.9 or OpenWatcom 2.0.
You must configure your build setup for WATCOM compilers.
You can create Linux installer, but it is more complex task.
You can also download Linux installer from Github Releases.

**Comment by HnkGitHub** [comment]
OK. Thanks for the advice. Using the latest Linux release (linux386) everything builds, documentation, compilers, ide, etc. using an i386 environment.
