### ISSUE TITLE
Resource compiler WRC can't find a file (Error! E159: Can't find file)

### ISSUE THREAD

**Issue by omm** [open-watcom/open-watcom-v2#680]
Hi!

I got error while building [Harbour](https://github.com/harbour/core):
```
wrc -q -r  -i..\include -zm hbrun\..\..\utils\hbmk2\harbour.rc -fo=..\bin\win\watcom\.hbmk\hbrun\harbour.res -bt=nt
Error! E159: Can't find file "../../package/harbour.ico".
Error! E159: Can't find file "../../package/harbour.mft".
Error! E123: Error reading temporary file "Temporary file 1 (res)": .
```
To reproduce the error try the attached example in [watcom_wrc.zip](https://github.com/open-watcom/open-watcom-v2/files/6306180/watcom_wrc.zip)

Thanks.

**Comment by jmalak** [comment]
what host OS you are using?

**Comment by omm** [comment]
windows 10 x64.

**Comment by jmalak** [comment]
It looks like wrc is not able to handle `core/contrib/hbrun/../../utils/hbmk2/../../package` search path.

**Comment by jmalak** [comment]
The problem is with wrong handling of include binary files path.
I will fix it.

**Comment by jmalak** [comment]
#747

**Comment by jmalak** [comment]
It should be fixed now

**Comment by omm** [comment]
Hi, i'm compiled the harbour now without errors. Many thanks for your job.
