### ISSUE TITLE
C and system libraries not linked (plus strange warning) when compiling with CMake

### ISSUE THREAD

**Issue by claunia** [open-watcom/open-watcom-v2#687]
CMake toolchain file:
```
if(NOT ${CMAKE_HOST_SYSTEM_NAME} MATCHES "Linux|Windows")
    message(FATAL_ERROR "Unsupported system")
endif()

if(NOT ${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "x86_64|i386")
    message(FATAL_ERROR "Unsupported architecture")
endif()

if("$ENV{WATCOM}" STREQUAL "")
    if(${CMAKE_HOST_SYSTEM_NAME} MATCHES "Linux")
        set(ENV{WATCOM} "/opt/watcom")
    else()
        set(ENV{WATCOM} "C:\\WATCOM")
    endif()
endif()

if(${CMAKE_HOST_SYSTEM_NAME} MATCHES "Linux")
    if(${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "x86_64")
        set(WATCOM_BIN_PATH "$ENV{WATCOM}/binl64/")
        set(ENV{PATH} "$ENV{WATCOM}/binl64:$ENV{WATCOM}/binl:$ENV{PATH}")
    else()
        set(WATCOM_BIN_PATH "$ENV{WATCOM}/binl/")
        set(ENV{PATH} "$ENV{WATCOM}/binl:$ENV{PATH}")
    endif()

    set(ENV{EDPATH} "$ENV{WATCOM}/eddat")
    set(ENV{WIPFC} "$ENV{WATCOM}/wipfc")
else()
    if(${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "x86_64")
        set(WATCOM_BIN_PATH "$ENV{WATCOM}\\binnt64\\")
        set(ENV{PATH} "$ENV{WATCOM}\\binnt64;$ENV{WATCOM}/binnt;$ENV{PATH}")
    else()
        set(ENV{PATH} "$ENV{WATCOM}\\binnt;$ENV{PATH}")
        set(WATCOM_BIN_PATH "$ENV{WATCOM}\\binnt\\")
    endif()

    set(ENV{EDPATH} "$ENV{WATCOM}\\eddat")
    set(ENV{WIPFC} "$ENV{WATCOM}\\wipfc")
endif()

add_compile_options(-3r)
add_compile_options(-mf)
add_compile_options(-l=os2v2)
set(CMAKE_SYSTEM_NAME OS2)
set(CMAKE_SYSTEM_PROCESSOR i386)
set(CMAKE_C_COMPILER "${WATCOM_BIN_PATH}wcl386")
```

Output error:
```
[100%] Linking C executable fssetter32.exe
Error! E2028: __CHK is an undefined reference
Error! E2028: DosQuerySysInfo is an undefined reference
Error! E2028: time_ is an undefined reference
Error! E2028: fopen_ is an undefined reference
Error! E2028: __get_errno_ptr_ is an undefined reference
Error! E2028: ___iob is an undefined reference
Error! E2028: fprintf_ is an undefined reference
Error! E2028: gmtime_ is an undefined reference
Error! E2028: asctime_ is an undefined reference
Error! E2028: fflush_ is an undefined reference
Error! E2028: vfprintf_ is an undefined reference
Error! E2028: vprintf_ is an undefined reference
Error! E2028: fclose_ is an undefined reference
Warning! W1014: stack segment not found
Warning! W1023: no starting address found, using 0001:00000000
```

**Comment by jmalak** [comment]
Sorry it is rather problem with CMake use.
Anyway if I remember properly OW cross-compile support for `DOS, OS/2, Linux and Windows` were added to CMake a year ago that you need not to use toolchain file.
You can use following setup of variables on command line to simply cross-compile from Windows or Linux to other targets

by example for 16-bit DOS
```
CMAKE_SYSTEM_NAME      DOS
CMAKE_SYSTEM_PROCESSOR X86
```
by example for 32-bit OS/2
```
CMAKE_SYSTEM_NAME      OS2
CMAKE_SYSTEM_PROCESSOR 386
```

But it requires properly configured WATCOM environment variable and PATH before run CMake for your host OS Linux or Windows.

If you are interested in CMake OW cross-compile stuff then appropriate specific configurations are in CMAke Modules/Platform subdirectory.

**Comment by jmalak** [comment]
If you want to use your toolchain file for 32-bit OS/2 executable then it should looks like below.
But use of only two variables on command line is much simpler and all relevant checks for Open Watcom is done by CMake.

```
if(NOT ${CMAKE_HOST_SYSTEM_NAME} MATCHES "Linux|Windows")
    message(FATAL_ERROR "Unsupported system")
endif()

if(NOT ${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "x86_64|i386")
    message(FATAL_ERROR "Unsupported architecture")
endif()

if("$ENV{WATCOM}" STREQUAL "")
    if(${CMAKE_HOST_SYSTEM_NAME} MATCHES "Linux")
        set(ENV{WATCOM} "/opt/watcom")
    else()
        set(ENV{WATCOM} "C:\\WATCOM")
    endif()
endif()

if(${CMAKE_HOST_SYSTEM_NAME} MATCHES "Linux")
    if(${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "x86_64")
        set(WATCOM_BIN_PATH "$ENV{WATCOM}/binl64/")
        set(ENV{PATH} "$ENV{WATCOM}/binl64:$ENV{WATCOM}/binl:$ENV{PATH}")
    else()
        set(WATCOM_BIN_PATH "$ENV{WATCOM}/binl/")
        set(ENV{PATH} "$ENV{WATCOM}/binl:$ENV{PATH}")
    endif()

    set(ENV{EDPATH} "$ENV{WATCOM}/eddat")
    set(ENV{WIPFC} "$ENV{WATCOM}/wipfc")
else()
    if(${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "x86_64")
        set(WATCOM_BIN_PATH "$ENV{WATCOM}\\binnt64\\")
        set(ENV{PATH} "$ENV{WATCOM}\\binnt64;$ENV{WATCOM}/binnt;$ENV{PATH}")
    else()
        set(ENV{PATH} "$ENV{WATCOM}\\binnt;$ENV{PATH}")
        set(WATCOM_BIN_PATH "$ENV{WATCOM}\\binnt\\")
    endif()

    set(ENV{EDPATH} "$ENV{WATCOM}\\eddat")
    set(ENV{WIPFC} "$ENV{WATCOM}\\wipfc")
endif()

set(CMAKE_SYSTEM_NAME OS2)
set(CMAKE_SYSTEM_PROCESSOR X86)
```

**Comment by claunia** [comment]
Hi @jmalak,

My toolchain file is to setup the environment variables so I do not have to set them previously, my cmake includes your platform modules.

If I just do as you say, it defaults to GCC:
```
claunia@zeus ~/Development/Aaru/fstester/setter $ source /opt/watcom/owsetenv.sh
claunia@zeus ~/Development/Aaru/fstester/setter $ cmake -DCMAKE_SYSTEM_NAME=OS2 -DCMAKE_SYSTEM_PROCESSOR=X86 .
-- The C compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
Detected system name: OS2
Detected system processor: X86
-- Configuring done
-- Generating done
-- Build files have been written to: /home/claunia/Development/Aaru/fstester/setter
claunia@zeus ~/Development/Aaru/fstester/setter $ echo $WATCOM
/opt/watcom
claunia@zeus ~/Development/Aaru/fstester/setter $ wcl386
Open Watcom C/C++ x86 32-bit Compile and Link Utility
```

that's why I created the toolchain file.

**Comment by claunia** [comment]
P.S.: The whole project is at https://github.com/aaru-dps/fstester/tree/master/setter

**Comment by jmalak** [comment]
It is because CMake default to GNU.
You must say that you realy want to use Watcom even if GNU is available.
It suppose that you use Wmake make file generator not GNU make.
That correct command line is 
cmake -G "WATCOM WMake"  -DCMAKE_SYSTEM_NAME=OS2 -DCMAKE_SYSTEM_PROCESSOR=X86

**Comment by jmalak** [comment]
In case that you want to use POSIX like environment configured by CC then you need to use owcc POSIX like driver. It explicitly disable GNU and OW driver owcc is used. But what I described is for Watcom native environment.
The same is if you use by example Miscrosoft Visual studio or Borland toolchain you you have to kill GNU some way.
For OW it is -G "Watcom WMake".

**Comment by jmalak** [comment]
I am not much familiar with CMake but combination OW with GNU make is possible.
You need to say CMake that you use make generator (I think it is default) and preferred toolchain is WATCOM then it will generate GNU make make files but for OW toolchain.
But it is useless to use GNU make if OW has native wmake with feature to speedup compilation etc.

**Comment by jmalak** [comment]
I tested it with OW 2.0 and it works properly

```
C:\dev\fstester\setter>cmake -S . -B bin -G "Watcom WMake" -DCMAKE_SYSTEM_NAME=OS2 -DCMAKE_SYSTEM_PROCESSOR=X86
-- The C compiler identification is OpenWatcom 2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/dev/ow2/rel/binnt/wcl386.exe - skipped
Detected system name: OS2
Detected system processor: X86
-- Configuring done
-- Generating done
-- Build files have been written to: C:/dev/fstester/setter/bin

C:\dev\fstester\setter>cd bin

C:\dev\fstester\setter\bin>wmake
Open Watcom Make Version 2.0 beta Dec 29 2020 13:10:27 (32-bit)
Copyright (c) 2002-2020 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
Scanning dependencies of target core
[ 33%] Building C object src/CMakeFiles/core.dir/main.c.obj
[ 66%] Building C object src/CMakeFiles/core.dir/log.c.obj
[100%] Linking C static library core.lib
[100%] Built target core

C:\dev\fstester\setter\bin>
```

**Comment by jmalak** [comment]
I tested cross-compile for Linux from Windows, but it fails due to some unportable code in setter

```
C:\dev\fstester\setter>cmake -S . -B bin -G "Watcom WMake" -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=X86
-- The C compiler identification is OpenWatcom 2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/dev/ow2/rel/binnt/wcl386.exe - skipped
Detected system name: Linux
Detected system processor: X86
-- Looking for statfs
-- Looking for statfs - not found
-- Looking for statfs
-- Looking for statfs - not found
-- Looking for statvfs
-- Looking for statvfs - not found
-- Configuring done
-- Generating done
-- Build files have been written to: C:/dev/fstester/setter/bin

C:\dev\fstester\setter>cd bin

C:\dev\fstester\setter\bin>wmake
Open Watcom Make Version 2.0 beta Dec 29 2020 13:10:27 (32-bit)
Copyright (c) 2002-2020 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
Scanning dependencies of target core
[  4%] Building C object src/CMakeFiles/core.dir/main.c.o
[  8%] Building C object src/CMakeFiles/core.dir/log.c.o
[ 13%] Linking C static library libcore.a
[ 13%] Built target core
Scanning dependencies of target unix
[ 17%] Building C object src/unix/CMakeFiles/unix.dir/attr.c.o
C:\dev\fstester\setter\src\unix\linux\linux.h(33): Error! E1009: Expecting ',' but found 'flags'
C:\dev\fstester\setter\src\unix\linux\linux.h(33): Error! E1116: An id list not allowed except for function definition
Error: Compiler returned a bad status compiling "C:\dev\fstester\setter\src\unix\attr.c"
Error(E42): Last command making (src\unix\CMakeFiles\unix.dir\attr.c.o) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (src\unix\CMakeFiles\unix.dir\all) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (all) returned a bad status
Error(E02): Make execution terminated

C:\dev\fstester\setter\bin>
```

**Comment by claunia** [comment]
@jmalak seems I forgot to push my changes so the version on github was not correct, please update.

The first cmake builds core.lib (that contains main() and log_*), then `os2/` compiles platform.lib that contains all code except os.c and xattr.c, and the `32bit/` compiles those two and links the .exe.

As for Linux yeah I never checked what are the differences between GNUisms and Watcom, as all other (clang, ICC) compilers in Linux usually implement the GNUisms, we can ignore that for now, it's a fix on my side.

And about wmake and make, I tried both, same result, gnumake and bsdmake are just script engines, they execute whatever cmake has told them to do, and cmake is telling them to use wcl386 and wlink.

This is the exact command line invoked to compile:
`/opt/watcom/binl64/wcl386 -zq -d+  -I/opt/watcom/h -I/opt/watcom/h/os2 -w3 -bt=os2 -d2 -3r -mf -l=os2v2 -foCMakeFiles/platform.dir/attr.c.obj -c -cc /home/claunia/Development/Aaru/fstester/setter/src/os2/attr.c`

and this is the command line invoked to link:
```
wlink option quiet name fssetter32.exe opt map system os2v2 debug all file {CMakeFiles/fssetter32.dir/os.c.obj CMakeFiles/fssetter32.dir/xattr.c.obj}  library ../../core.lib library ../platform.lib
```

**Comment by jmalak** [comment]
Your division to two libraries is strange and source of link problem.
Mainly put main.obj to library is mistake.
Linking process is to search undefined symbols from your objects .modules which are explicit links in list of libraries.
Because main module is in library it is not link into executable and it is not working any way.
Why you don't compile and link all modules together?
anyway main.obj module must be explicitly link to executable, can not be in library.
It ensures to properly link with C run-time library startup code which is referenced from main.obj module.
Other posibility is to refere _cstar_ symbol and C run-time library form other modules, but it is not standard and can introduce other issues.

**Comment by claunia** [comment]
Because I did not find a way to pass sources to subfolders in CMake. I would certainly prefer to not do that libs thing.

I have to check more the CMake syntax, lemme do some tests shortly.

**Comment by jmalak** [comment]
You can fix it by adding following lines to begining of setter/src/os2/CMakeLists.txt

if(WATCOM)
set(CMAKE_C_LINK_EXECUTABLE
 "wlink ${CMAKE_WLINK_QUIET} name <TARGET> <LINK_FLAGS> file {<OBJECTS>} <LINK_LIBRARIES> reference main_")
endif()

**Comment by claunia** [comment]
@jmalak I changed the whole CMakeLists so to not use intermediary libraries and that makes it work, thanks for the help.
