### ISSUE TITLE
Can you resurrect an old WLINK feature? Allowing the mixing of 16/32-bit code in DOS executables

### ISSUE THREAD

**Issue by volkertb** [open-watcom/open-watcom-v2#688]
WLINK has an option called `MIXED1632` that allows the mixing of 16-bit and 32-bit assembly code within the same executable. Currently, this feature only works when building for a 32-bit target, such as OS/2 or DOS/4GW.

After some searching, I found an old usenet discussion that implied that WLINK actually used to support this for DOS targets as well, at least up until version 1.2. Apparently the feature was removed, because it was considered unsafe: https://openwatcom.contributors.narkive.com/nIdTZWQ6/combining-of-16-and-32-bit-segment

The reason why I'm asking for this feature to be made available again, is because I've been porting an old DOS TSR (a Sound Blaster emulator) from TASM dialect to WASM dialect, and this source code actually mixes 16-bit and 32-bit code within a tiny memory model (DOS COM file target). I believe the reason behind this is because it makes use of an API of QEMM386 to trap I/O port access, and it needs to provide the port trapping routines to QEMM in 32-bit form. At least that's how I've interpreted it from the code with my (still limited) assembly language skills.

I managed to get WASM to assemble the code into an object file (without the need for TASM or IDEAL compatibility mode), but WLINK refuses to link the resulting object file due to it containing mixed 16-bit and 32-bit code.

The code I'm trying to build can be found in this branch and subdirectory: https://github.com/volkertb/temu-vsb/tree/port-vsb-qemm-to-wasm/sbemu

Specifically, you can find the changes I made to make it assemble with WASM in this commit: https://github.com/volkertb/temu-vsb/commit/4a6e22ca08a52981bf34701d66fea22794fc2ed0

In that subdirectory, I've added a `Makefile`. You can try assembling the code with the command `make vsb_qemm.com`

WLINK fails with the following error (shown twice):

```
Error! E2064: cannot combine 32-bit segments (Code32) with 16-bit segments (Acode16)
Error! E2064: cannot combine 32-bit segments (Code32) with 16-bit segments (Zcode16)
```

If I add `option MIXED1632` to the WLINK parameters in the Makefile, the following warning will also be shown before the aforementioned errors:

```
Warning! W1058: mixed1632 option not valid for a DOS .COM executable
```

It's also interesting to check out chapter 3.58 of the Open Watcom Linker User’s Guide at ftp://ftp.openwatcom.org/manuals/current/lguide.pdf (link to the PDF is an FTP URL, might not open in some newer browsers). That (short) chapter briefly describes the `MIXED1632` option, ending with this paragraph:

> This option is useful certain specialized applications, such as OS/2 physical device drivers. In most cases,
mixing of 16-bit and 32-bit segments should be avoided.

By the way, the chapter implies that the feature is exclusive to the OS/2 target, but that information is apparently outdated, since the `MIXED1632` option [now also works with the DOS/4GW target](https://gist.github.com/FlyingJester/4cffbf32577e95c526db59cda53d394e), and possibly with other 32-bit targets as well.

Anyway, how feasible would it be to restore this functionality? Only if the `MIXED1632` option is explicitly specified, of course.

Perhaps it's as easy as removing or modifying a simple check in the WLINK source code?

Thank you kindly for considering this. :slightly_smiling_face:

**Comment by jmalak** [comment]
I think it has two aspects. First mixing two different segments (16 and 32-bit) into executable and second combine two segments (16 and 32-bit) into one segment group.
I think OW linker support first cause, but not second one. But you want second cause and also you want the resulting code to be 16-bit. Anyway this is segment combine rule violation.

The difference is in terms "mixing" and "combine". I am not sure if we understand this the same way.
Anyway I can look on linker code if it is possible somehow, but I am skeptic to it because it means to block many rules to be possible and also will need to add some checks for combined segment length etc.

**Comment by jmalak** [comment]
Why you don't create 16-bit segment with 32-bit code and link it together?

**Comment by jmalak** [comment]
I check OW link current code. MIXED1632 option works only for OS2FLAT group targets. It is 32-bit executable and enable mixing not combine 16 and 32-bit segments. DOS4GW use LX (OS2FLAT) format therefore it is possible to mix 16 and 32-bit segments in executable.
I looked also on original Watcom code and there is not enabled "combine" 16 and 32-bit segments too even if MIXED1632 option is not available

I search for introduction of MIXED1632 option and there is comment from source repository.
> Description: ChangeList: The linker now supports a MIXED1632 option to allow mixing of 16- and 32-bit logical segments into a single physical segment in OS/2 LX/LE executables.

It means combine is possible but only for 32-bit executable and OS2FLAT group of formats.

**Comment by jmalak** [comment]
anyway here is uptodate [documentation for OW 2.0](https://github.com/open-watcom/open-watcom-v2/wiki/Open-Watcom-Documentation)

**Comment by jmalak** [comment]
Next possibility is to use raw binary format output, because raw format enable such combination of segments.
`wlink format raw bin option offset=...`

**Comment by volkertb** [comment]
Sorry for the late reply.

Anyway, that seems to have done the trick, @jmalak! :partying_face:

By the way, before your aforementioned commit, I managed to get the linker to produce something with offset 0x100 by using some different combinations of arguments, including `option MIXED1632`, but the resulting .COM file didn't work.

On the other hand, with your suggested command, and yesterday's build of the Open Watcom v2 distro, the build indeed yielded a properly running .com file. :relaxed: At least, the expected error message was shown due to QEMM386 not being detected by the TSR.

```
D:\>vsb_qemm
■─[ VSB ]──────────────────────────[ Error ]─■
│Incompatible memory manager - QEMM v7.0+ req│
■────────────────────────────────────────────■
D:\>
```

WLINK did show a `Warning! W1014: stack segment not found`, but if I remember correctly, TASM would show a very similar stack-related warning when building the original code.

I'll need to test the resulting build of the emulator more thoroughly to be sure that it's completely working, and that my "porting" work of the assembly code from TASM to WASM didn't introduce any errors.

Thank you so much for your help! So cool that this code can be built with an open source assembler now. :slightly_smiling_face:

**Comment by jmalak** [comment]
To disable this warning use wlink directive 
`disable 1014`
on command line
