### ISSUE TITLE
DOS - whelp not helping

### ISSUE THREAD

**Issue by HnkGitHub** [open-watcom/open-watcom-v2#689]
whelp has been nonfunctional for about a month on the Git builds. 
![dos](https://user-images.githubusercontent.com/38794884/116409375-65b52e00-a7f9-11eb-88d3-cf51a066ba7b.png)

**Comment by jmalak** [comment]
Thanks for bug report.

**Comment by jmalak** [comment]
now it is fixed by commits b8a2b0c9868d11b60dd235628ffe60296b89da40 and e40bcf053453246bf1e1a402eab59c426598e816
