### ISSUE TITLE
Mini-Issue: #pragma message creates a warning

### ISSUE THREAD

**Issue by LowLevelMahn** [open-watcom/open-watcom-v2#691]
using this code

test.cpp
```
#ifdef MYFLAG
#pragma message ( "A MESSAGE" );
#endif
```

release
`Last updated 2021-06-03 01:47:19`

```
Open Watcom C++ x86 16-bit Optimizing Compiler
Version 2.0 beta Jun  3 2021 00:46:44 (64-bit)
```

and this command line

`open-watcom-2_0-c-win-x64\binnt64\wpp.exe test.cpp -2 -zl -zls -s -dMYFLAG`

gives this warning

```
..\test.cpp(2): Warning! W725: col(31) "A MESSAGE"
..\test.cpp: 4 lines, 1 warning, no errors
```

shouldn't just the message be printed?

**Comment by jmalak** [comment]
Thanks for bug report.
It is mistake in C++ compiler.
C compiler works OK.
I will fix it.

**Comment by LowLevelMahn** [comment]
works!
