### ISSUE TITLE
Control date inserted into build results

### ISSUE THREAD

**Issue by OPNA2608** [open-watcom/open-watcom-v2#694]
I noticed that the build date and year is embedded into all the tools and libraries. I'd like to control those values. Some Linux distributions / package managers care alot about reproducibility - building a project twice with the same inputs should produce the same byte-exact output. Such build-specific dates are usually the first things that get patched away or standardised to a fixed value (i.e. `Jan  1 1980 00:00:00`)

Is it possible to either use [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) or have a custom build option to override the automatic values? If not, could you let me know which parts of the code are responsible for detecting the date so I can patch them in our package?

**Comment by jmalak** [comment]
It is pickup from standard pre-processor macros as help for development.
If you have multiple versions of OW tool on system it identifies which one you use and also it is useful for bug reports.
It was not mention as something for regular releases.
Regular release have a number as example 2.0 that compile timestamp has no sense and will not included in executable, only build date will be there.
Full timestamp is used only by beta releases.

Anyway configuration is in bld/watcom/h/banner.h

#ifdef _BETAVER                                                                                                         
#define _BANEXTRA           __DATE__ " " __TIME__ STR_BITNESS                                                           
#else                                                                                                                   
#define _BANEXTRA           __DATE__                                                                                    
#endif
