### ISSUE TITLE
wcc command line arguments invalid

### ISSUE THREAD

**Issue by PerditionC** [open-watcom/open-watcom-v2#701]
FreeCOM uses the latest versions and sometime in the last week, something changed that causes wcc on Linux to not support _-options_ anymore.  I just found the issue this morning, so haven't done much except also test  on a local Linux computer.  I have not yet tested if it is all options or only some options.  The easiest way to reproduce is run `wcc -h` which produces `Error! E1073: Invalid option '-h'`

From FreeCOM ci_build.sh it downloads the latest snapshot:

> # Get Watcom compiler
>if [ ! -d _watcom ] ; then
>  if [ ! -f ow-snapshot.tar.gz ] ; then
>    echo "Downloading OpenWatcom compiler snaphot"
>    wget --quiet https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.gz
>  fi
>  echo "Extracting OpenWatcom compiler snaphot"  mkdir _watcom  tar -C _watcom -xf ow-snapshot.tar.gz
>fi
>export PATH=$CI_BUILD_DIR/bin:$PATH:$CI_BUILD_DIR/_watcom/binl64
>export WATCOM=$CI_BUILD_DIR/_watcom<br class="Apple-interchange-newline">

The build results from last night, which builds fine with GCC-ia16 and an older snapshot I use on Windows: 
 https://github.com/FDOS/freecom/runs/2844659039

> ...
>/home/runner/work/freecom/freecom/_watcom/binl/wcc -zq -fo=.obj -I.. addu.c -bt=dos @watcomc.cfg
>Error! E1073: Invalid option '-'
> ...

watcomc.cfg contains
>-os-s-wx
>-I/home/runner/work/freecom/freecom/_watcom/h -I../suppl
>-ms
>-UDEBUG -DNDEBUG -DXMS_SWAP

Testing on a local Ubuntu Linux VM, same ci_build.sh script, so latest published snapshot as of this morning:
>jeremyd@ub.fdos.org:~/freecom$ ./_watcom/binl/wcc -h
>Open Watcom C x86 16-bit Optimizing Compiler
>Version 2.0 beta Jun 17 2021 00:23:24 (32-bit)
>Copyright (c) 2002-2021 The Open Watcom Contributors. All Rights Reserved.
>Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
>Source code is available under the Sybase Open Watcom Public License.
>See http://www.openwatcom.org/ for details.
>Error! E1073: Invalid option '-h'
>Error! E1138: Filename required on command line

Please let me know if any additional information or testing is required.

**Comment by jmalak** [comment]
Thanks for bug reports.
I will check and fix.

**Comment by jmalak** [comment]
Problem with -h option is unrelated to your problem.
Option -h is no longer supported by OW 2.0 C/C++ compilers that message about it is correct.
It was removed for overall OW consistency, but I forgot remove it from usage text for C compiler.
I will continue with your problem investigation.

**Comment by PerditionC** [comment]
I thought that might be the case after looking that it's error is a bit different, sorry about that.

**Comment by PerditionC** [comment]
thank you for the fix
