### ISSUE TITLE
"#pragma error" does not work

### ISSUE THREAD

**Issue by LowLevelMahn** [open-watcom/open-watcom-v2#702]
pragma_error.c
#pragma error "does nothing"

Win7 x64
wcc.exe Version 2.0 beta Jun 16 2021 00:39:05 (64-bit)

wcc.exe pragma_error.c -2 -zl -zls -s

the pragma does nothing - no warning, no message

**Comment by jmalak** [comment]
Thanks for bug report.
The "#pragma error" was newer implemented in C compiler, it is only in C++ compiler.
It will be implemented for consistency with C++ compiler.

**Comment by jmalak** [comment]
It will not be implemented, see note in documentation.
You should use standard "#error" pre-processor directive instead of "#pragma error".
Documentation was updated for "#pragma error" as "C++ only".

**Comment by LowLevelMahn** [comment]
ok, thanks for the info
