### ISSUE TITLE
Wrong warning: Comparison result always 1

### ISSUE THREAD

**Issue by LowLevelMahn** [open-watcom/open-watcom-v2#703]
Open Watcom C x86 16-bit Optimizing Compiler
Version 2.0 beta Jun 16 2021 00:39:05 (64-bit)

always1.c
```
void test()
{
  __int8 dh = 0;
  for(dh = 15; dh >= 0; --dh )
  {
    // something
  }
}

```

i get the warning:  always1.c(4): Warning! W124: Comparison result always 1

but that isn't true as long as __int8 is signed

**Comment by jmalak** [comment]
thanks for your bug report.
It is OW 1.9 bug in __int8 implementation.
It is implemented as `plain char` instead of `signed char`.
Because `plain char` is by default `unsigned char` compiler report this error.
I will fix it ASAP.

**Comment by LowLevelMahn** [comment]
"char" is also interpreted as plain char 

char or __int8 --> Warning

**Comment by jmalak** [comment]
char is OK.
You have 3 types of character type defined by ISO C
```
signed char         signed
unsigned char       unsigned
char                (it is implementation defined, OW default is unsigned, but OW can change it by -j option to signed)
```
I suppose __int8 is not character type but integer type then it is different, it doesn't have plain type as character
```
signed __int8       signed
unsigned __int8     unsigned
__int8              signed
```
see Microsoft specification for __int8 type (it is Microsoft type, not ISO C)
similar problem with int8_t ISO C type, it is signed type against char which is not.

**Comment by LowLevelMahn** [comment]
thank you for the detail explanation

**Comment by jmalak** [comment]
it is fixed now

That following is OK
```
void test()
{
  __int8 dh = 0;
  for(dh = 15; dh >= 0; --dh )
  {
    // something
  }
}
```
but this get message, until you use `-j` compiler option, which switch `char` to `signed char`
```
void test()
{
  char dh = 0;
  for(dh = 15; dh >= 0; --dh )
  {
    // something
  }
}
```

**Comment by jmalak** [comment]
I did test on MSVC for __int8 type and it confirms that __int8 is alias for char type.
Therefore I reverted previous change which supposed __int8 is signed type.
