### ISSUE TITLE
owcc on Linux ignores -shared/-static flags

### ISSUE THREAD

**Issue by denis-shienkov** [open-watcom/open-watcom-v2#705]
Hi all.

I want to use the OWCC driver (GCC wrapper) to create the shared/static libraries on Linux using OpenWatcom v2.
When I pass the '-static' or '-shared' flags, then nothing happens, the resulting binary is an executable.  

For example, I use the following commands to compile the objects and to build them into the static library:
```
/opt/watcom/binl64/owcc -g3 -O0 -Wall -Wextra -blinux -xc++ -fno-rtti -o /home/denis/Downloads/qbs-git/demo/helloworld-minimal/build/default/HelloWorld-minimal.0a1619e1/3a52ce780950d4d9/main.cpp.obj -c /home/denis/Downloads/qbs-git/demo/helloworld-minimal/main.cpp
/opt/watcom/binl64/owcc -blinux -static -o /home/denis/Downloads/qbs-git/demo/helloworld-minimal/build/default/HelloWorld-minimal.0a1619e1/HelloWorld-minimal /home/denis/Downloads/qbs-git/demo/helloworld-minimal/build/default/HelloWorld-minimal.0a1619e1/3a52ce780950d4d9/main.cpp.obj
```
But the generated file is not a library, it is executable, because I can run it.

**Comment by jmalak** [comment]
owcc is POSIX like C/C++ compiler driver only, not GCC wrapper.
see documentation for owcc.
if you want to create static library you must create all object files by owcc and next run librarian "wlib".
shared libraries are not yet supported by OW.

**Comment by denis-shienkov** [comment]
> shared libraries are not yet supported by OW.

Does this means, than even on Windows I can't create a shared (dll) libraries?

**Comment by jmalak** [comment]
> > see documentation for owcc.
> 
> Could you please point me on that documentation URL?

[Documentation for owcc options](https://open-watcom.github.io/open-watcom-v2-wikidocs/ctools.html#owcc_Options_Summary)

> > shared libraries are not yet supported by OW.
> 
> Does this means, than even on Windows I can't create a shared (dll) libraries?

Sorry, shared libraries `for Linux OS` is `not supported`.
DLLs for other OSes is supported by option `-shared`.

> > owcc is POSIX like C/C++ compiler driver only, not GCC wrapper.
>
> It would be nice, if OWCC will support that options to create the static and shared (so + dll) libraries. 

owcc is compile and link utility to follow POSIX `cc` command therefore only DLL can be created,  see above

**Comment by denis-shienkov** [comment]
Ok, many thanks

**Comment by guy-rouillier** [comment]
Has this situation changed with Open Watcom V2 on Linux?  I'm also trying to generate and use a shared object (.so) using Open Watcom V2 and not having success.  I've done some searching and I'm not finding many hits, which is why I'm commenting on this one.

Thank you.

**Comment by jmalak** [comment]
Only note.
**`cc`** **`POSIX`** utility doesn't support such options, if you wan't create any static library you must use librarian utility **`wlib`**.
When dynamic library (DLL) then you must use linker utility **`wlink`** with appropriate directive/option.

Anyway OW still not support shared libraries on Linux.

**Comment by guy-rouillier** [comment]
@jmalak Thank you for confirming that OW does not support SOs on Linux.  You've saved me countless hours of hopeless trial and error.
