### ISSUE TITLE
OWCC ignores path to linking import library specified as -l <path/to/lib> and wants only *.a extension

### ISSUE THREAD

**Issue by denis-shienkov** [open-watcom/open-watcom-v2#707]
Hi all.

I want to use the OWCC driver to link my application with the shared DLL library. My shared library contains two files `my-dlib.dll` and `my-dlib.lib` files (where `my-dlib.lib` is an import library).

When I try to specify the path to this import libraty to link with:

```
C:\WATCOM\BINNT64\owcc.exe -g3 -O0 -Wall -Wextra -bnt_dll -xc++ -feh -fno-rtti -DLIBRARY_NAME_SOURCE -o E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-dlib.ed0fa862/3a52ce780950d4d9/foo.cpp.obj -c E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/foo.cpp
C:\WATCOM\BINNT64\owcc.exe -g3 -O0 -Wall -Wextra -bnt -xc++ -feh -fno-rtti -o E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-app.431cf07b/3a52ce780950d4d9/main.cpp.obj -c E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/main.cpp
C:\WATCOM\BINNT64\owcc.exe -bnt_dll -shared "-Wl, option implib=E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-dlib.ed0fa862/my-dlib.lib" -o E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-dlib.ed0fa862/my-dlib.dll E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-dlib.ed0fa862/3a52ce780950d4d9/foo.cpp.obj
C:\WATCOM\BINNT64\owcc.exe -bnt -mconsole "-fm=E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-app.431cf07b/my-app.map" -lE:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-dlib.ed0fa862/my-dlib.lib -o E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-app.431cf07b/my-app.exe E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-app.431cf07b/3a52ce780950d4d9/main.cpp.obj
```
I got the following error:

```
ERROR: C:\WATCOM\BINNT64\owcc.exe -bnt -mconsole "-fm=E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-app.431cf07b/my-app.map" -lE:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-dlib.ed0fa862/my-dlib.lib -o E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-app.431cf07b/my-app.exe E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-app.431cf07b/3a52ce780950d4d9/main.cpp.obj
Warning! W1008: cannot open E:\git\ng\git\123\qbs-git\tests\hello-world-watcom\build\default\my-dlib.ed0fa862\my-dlib.lib.a : No such file or directory
Error! E2028: int __near foo() is an undefined reference
file E:\git\ng\git\123\qbs-git\tests\hello-world-watcom\build\default\my-app.431cf07b\3a52ce780950d4d9\main.cpp.obj(E:\git\ng\git\123\qbs-git\tests\hello-world-watcom\main.cpp): undefined symbol int __near foo()
Error: Linker returned a bad status
```

I see that OWCC wants the import file name as `my-dlib.lib.a`, but I passed to the linker the file `my-dlib.lib`.

**Comment by jmalak** [comment]
thanks you for your bug report.
in owcc is bug, it could recognize .lib and .a extensions for library but it add .a extension for .lib too.
I will fix it ASAP.

**Comment by jmalak** [comment]
as workaround you can add library in list of files instead of use -l option.
it should recognize library by .lib or .a extensions.

**Comment by denis-shienkov** [comment]
> as workaround you can add library in list of files instead of use -l option.

could you please provide a minimal example (or maybe a documentation) how to use that workaround?

UPD: Can I try to pass the libraries using the `-Wl` option and then use the `libfile` flag, e.g.: `-Wl, libfile file1,file2,fileN` ?

**Comment by jmalak** [comment]
last command should be
C:\WATCOM\BINNT64\owcc.exe -bnt -mconsole "-fm=E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-app.431cf07b/my-app.map" E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-dlib.ed0fa862/my-dlib.lib -o E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-app.431cf07b/my-app.exe E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-app.431cf07b/3a52ce780950d4d9/main.cpp.obj E:/git/ng/git/123/qbs-git/tests/hello-world-watcom/build/default/my-dlib.ed0fa862/my-dlib.lib

**Comment by jmalak** [comment]
It looks like OW is correct, but you use -l option incorrectly.
POSIX standard specify -l option as

-l <**library**>
(The letter ell.) Search the library named:
lib<**library**>.a

**Comment by jmalak** [comment]
if you want add any library you can add it to owcc command
owcc ....options.... <file list>
where <file list> can contains any `source file` or `compiled object module files` or any `library files`
owcc pass it correctly to compiler if source file or linker if compiled files or libraries file.

**Comment by denis-shienkov** [comment]
ahh, yes, sorry, many thanks

**Comment by denis-shienkov** [comment]
No, sorry, it does not work even when I pass the library name, for both static and dynamic libraries with `lib` suffix:

I tried to pass the library names as a base names (without of a suffixes):
```
 C:\WATCOM\BINNT64\owcc.exe -bnt -o app.exe -mwindows -Llibs main.c.obj -llib-b -llib-a
Warning! W1008: cannot open lib-b.a : No such file or directory
Warning! W1008: cannot open lib-a.a : No such file or directory
Error! E2028: b_ is an undefined reference
```

Also with a suffixes:
```
 C:\WATCOM\BINNT64\owcc.exe -bnt -o app.exe -mwindows -Llibs main.c.obj -llib-b.lib -llib-a.lib
Warning! W1008: cannot open lib-b.lib.a : No such file or directory
Warning! W1008: cannot open lib-a.lib.a : No such file or directory
Error! E2028: b_ is an undefined reference
```

The reason is that it is impossible to rename the library name suffixes from *.lib to *.a, because I want to use and the system libraries e.g. from the `c:\WATCOM\lib386\` directory.

In this case the OWCC is completelly unusable when I don't know about a full path to the library. In this case I can't use the `-l` and '-L` command line options on Windows.

**Comment by jmalak** [comment]
Your conclusion is fantastic.
What about OW documentation?
Nice cross compile guide for begginer is [here](https://wiki.archlinux.org/title/Open_Watcom)

**Comment by denis-shienkov** [comment]
> Your conclusion is fantastic.

My conclusion is OK. How you will link the current *.lib libraries using OWCC driver? 

F.e. MinGW use *.a extension for static libraries, and *.dll.a for dynamic import libraries.. But there are all OK, because initially are used that extensions.

But, the OWCC it is a new feature for watcom compiler, and here not thought out about using the *.lib extension.

**Comment by jmalak** [comment]
For me it is working.
Any library add on command line as file name without any option will be linked.
Stop to use -l option, because you don't understand how it works.
If you use -L option you can specify additional path to search any library, it has nothing to do with -l option

You are trying to use OW your own way, don't expect that it will be working.¨
If anything is not working how you think then you report it  immediately as bug.
It is due to missing knowledge about OW.
Stop report your own bug as OW bugs.

**Comment by denis-shienkov** [comment]
> Any library add on command line as file name without any option will be linked.

Do you understand, that in some cases it is impossible to use a full path to the library (or even to use the library names)?  

F.e. If I want to use the OWCC on both Windows && Linux, then I expect, that if I need to use e.g. the `math` library, then I want to use it as: `owcc -lmath` ... I don't care about the library prefix, or the library suffix. I expect that the compiler automatically will resolve it as `libmath.a` on Linux, or as `math.lib` on Windows.

 > Stop report your own bug as OW bugs.

Stop write nonsence, please.
