### ISSUE TITLE
installer error on freebsd linux emuration

### ISSUE THREAD

**Issue by yamori813** [open-watcom/open-watcom-v2#711]
I use open watcom v2 on freebsd linux emuration. I can't do install. Because of this error.

linux: jid 6 pid 3143 (open-watcom-2_0-c-l): linux_ioctl_fallback fd=0, cmd=0x541c ('T',28) is not implemented

I seem case of installer use TIOCLINUX ioctl in ck_shift_state() at  bld/uii/unix/c/ctkeyb.c.

Do you have idea on this problem ?

Thanks

**Comment by jmalak** [comment]
It looks like problem with reading from terminal keyboard in FreeBSD Linux emulation.
I am not familiar with FreeBSD and Linux emulation.
I which phase of installation you have this problem?
Do you get licence window?

**Comment by jmalak** [comment]
If you want to install OW manualy then you can download [release binary package](https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.gz) and do manual setup.

**Comment by yamori813** [comment]
OK. I use snapshot file.

Thanks
