### ISSUE TITLE
Broken _wsystem, _wspawn*

### ISSUE THREAD

**Issue by plzombie** [open-watcom/open-watcom-v2#718]
I found what **_wsystem** and **_wspawn** not working (at least in Win10 64bit).
I found in source code what **_wsystem** and all **_wspawn** calls **_wspawnve** internally.
**_wspawnve** calls **__wcenvarg** to get environment string, when **_wsplitpath2** to get drive, directory et c., **_wmakepath** to concatenate data from **_wsplitpath2** and finally calls **_wdospawn**.
I called **_wsplitpath2**, **_wmakepath**, **_wdospawn** the same way they called in sources and all works fine.
When I add **__wcenvarg** and found what output string differs from **__cenvarg**.
For **__cenvarg** first 4 variables was:
- =::=::\
- =C:=c:\Windows\System32
- =F:=f:\NonOfYourBusiness\MyBusiness\MyProjects\test_wspawn
- ALLUSERSPROFILE=C:\ProgramData
- APPDATA=C:\Users\misha\AppData\Roaming

For **__wcenvarg** they was:
- ↑
- ?
- APPDATA=C:\Users\misha\AppData\Roaming

"↑" and "?" are not correct environment variables (they must have "=" to separate name from value), so **_wdospawn(CreateProcessW)** fails.
I also checked variables **environ(_RWD_environ)** and **_wenviron(_RWD_wenviron)** and they have same issue.
There might be some error in **__create_wide_environment** (or underlying **__wputenv**) functions used to create widechar environment variables **environ** and **_wenviron**.

Here is a [sources](https://gist.github.com/plzombie/139e5c3f6450fe06679b789e886de279) I used for testing

**Comment by jmalak** [comment]
Many thanks for your bug report and problem analysis.
I confirm it as bug and will fix it ASAP.

**Comment by jmalak** [comment]
there were a few issues with wide/narrow environments.
Now your sample code is working without problems.

**Comment by jmalak** [comment]
#199

**Comment by plzombie** [comment]
All works, thanks
