### ISSUE TITLE
New issue while building \bld\gui\ui\dos386

### ISSUE THREAD

**Issue by DavidOgilvie** [open-watcom/open-watcom-v2#719]
Since around Aug 6, I've been having the following issue when building on Windows 10 platform.  I have been working in GUI\WIN\C, so this is preventing me from doing testing of the GUI library.  Any thoughts?

===================== 15:57:45 f:\OW2.0\bld\gui\ui\dos386 =====================
cc guipick.obj
..\..\c\guipick.c(61): Warning! W111: Meaningless use of an expression
..\..\c\guipick.c(61): Warning! W111: Meaningless use of an expression
..\..\c\guipick.c(61): Warning! W111: Meaningless use of an expression
..\..\c\guipick.c(61): Warning! W102: Type mismatch (warning)
..\..\c\guipick.c(61): Note! N2003: source conversion type is 'void *'
..\..\c\guipick.c(61): Note! N2004: target conversion type is 'int'
..\..\c\guipick.c(61): Warning! W101: Non-portable pointer conversion
..\..\c\guipick.c(61): Note! N2003: source conversion type is 'int'
..\..\c\guipick.c(61): Note! N2004: target conversion type is 'struct gui_window *'
..\..\c\guipick.c(61): Warning! W111: Meaningless use of an expression
..\..\c\guipick.c(61): Warning! W111: Meaningless use of an expression
..\..\c\guipick.c(61): Warning! W111: Meaningless use of an expression
..\..\c\guipick.c(61): Warning! W102: Type mismatch (warning)
..\..\c\guipick.c(61): Note! N2003: source conversion type is 'void *'
..\..\c\guipick.c(61): Note! N2004: target conversion type is 'int'
..\..\c\guipick.c(61): Warning! W101: Non-portable pointer conversion
..\..\c\guipick.c(61): Note! N2003: source conversion type is 'int'
..\..\c\guipick.c(61): Note! N2004: target conversion type is 'struct gui_window *'
Error(E42): Last command making (guipick.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 2
Build failed

**Comment by jmalak** [comment]
It looks like some mismatch of your source code with current one in repository.
Probably problem is guidlg.h header file containing character mode dialog macros which were significantly changed.
Try check this.
