### ISSUE TITLE
IDE.EXE starts just showing the max/min/close box, but no window

### ISSUE THREAD

**Issue by DavidOgilvie** [open-watcom/open-watcom-v2#720]
I've been having this issue for about a month, and assumed it was a problem caused by my work in the \bld\gui folder, so I downloaded the source files for the master branch and did a full build on the master.  When I ran IDE generated by the master branch source tree, I got the same issue.  I then downloaded the install file and installed the 64-bit version of OW over my old version of WATCOM.  When I executed the IDE.EXE file from the WATCOM installation, I get the same issue.  This issue appears to have started at about the same time the GUI was revised to have the routine types changed to include the GUIAPI type modifier on routines and prototypes.  I installed the 32-bit installer of WATCOM and got the same result.

I am running Windows 10 version 21H1 (64-bit).

Any suggestions?

Thanks in advance!

**Comment by jmalak** [comment]
Thanks for your bug report I will review.
Anyway 32-bit version seems OK.

**Comment by jmalak** [comment]
The status of IDE window is saved in your OW profile file which is not removed by re-installation.
It is file "C:\Users\jmala\AppData\Roaming\Open Watcom\watcom.ini", you can delete only section [OPEN_WATCOM_IDE].
Try to remove it and check if it is still a problem.
