### ISSUE TITLE
IDE Scrolling Problem sometime after version 2021-07-01 Windows 64

### ISSUE THREAD

**Issue by real-iacoder** [open-watcom/open-watcom-v2#721]
The ide project window does not seem to scroll properly on versions after 2021-07-01 when the list of files exceeds the size of window. The list scrolls properly with the mouse wheel on the 2021-07-01 version and before. It seems that the window is not being updated properly and does not see the mouse. Resizing the window causes even more confusion.

Not a big deal, but the copy files progress bar in the install updates the percentage but not the bar also after the 2021-07-01 version.

I'm running the latest version of Windows 10 64-bit with a 1920x1080 screen and a Microsoft mouse. I have both c and fortran installed.

**Comment by DavidOgilvie** [comment]
I have the same configuration as you, Windows 10 21H1, and Microsoft Mouse, and have the same issue.  It partly is a mouse handling issue, but If I click on a filename, then scroll down with the keyboard, I get unexpected results when the current line goes off the bottom of the screen.  Also, the scroll bar produces unexpected results when I click below the location box in the scrollbar.  Very strange!

**Comment by jmalak** [comment]
Thanks for your bug report.
I will review it.

**Comment by nathanpc** [comment]
I'm running 2021-10-18 and the same bug is present under Windows 10 21H1 x64 and also Windows XP x32. Every `ListBox` control that scrolls in any of the Open Watcom applications are affected by it.

**Comment by jmalak** [comment]
It is bug in introduced by changes related to handling text coordinates for dialog resources.
I will fix it ASAP.

**Comment by jmalak** [comment]
#769

**Comment by real-iacoder** [comment]
This problem was reported 2021-08-17. It's been a while. I'm still using version 2021-07-01. Will this be fixed or should I be looking for an alternative IDE?

**Comment by jmalak** [comment]
I have it on to-do list as second item.
