### ISSUE TITLE
wlink producing broken binary with GLOBAL nasm symbol

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#722]
I am running into an issue where adding a library to a working program at link time is producing a binary that stops working correctly. I was able to track the problem down to the wlib produced library including an OBJ file output by nasm with a GLOBAL symbol.

```nasm
CPU 386

SEGMENT .code USE32 CLASS=CODE

%ifdef break
GLOBAL rand_
%endif

rand_:
  ret

SEGMENT .bss USE32 CLASS=BSS
  seed: resd 1
```

If I compile and link my program without the GLOBAL symbol it works:

```
nasm -f obj -o stdlib.o stdlib.asm
wlib -b -n -q std.lib stdlib.o
wlink name main.exe option map,eliminate,quiet system dos32a file main.o,std.lib
```

However, if I compile and link my program with the GLOBAL symbol, it runs but does not produce the right output:

```
nasm -f obj -Dbreak -o stdlib.o stdlib.asm
wlib -b -n -q std.lib stdlib.o
wlink name main_bad.exe option map,eliminate,quiet system dos32a file main.o,std.lib
```

As an added hint, I get this error in the debug console running `main_bad.exe` under dosbox:

```
DOSBox switched to max cycles, because of the setting: cycles=auto. If the game runs too fast try a fixed cycles amount in DOSBox's options.
Illegal write to 64721000, CS:IP      838:  130051
Illegal write to 64721140, CS:IP      838:  130051
Illegal write to 64721280, CS:IP      838:  130051
Illegal write to 64721280, CS:IP      838:  130051
Illegal write to 647213c0, CS:IP      838:  130051
```

I am using the latest released open-watcom-v2

```
Open Watcom C x86 32-bit Optimizing Compiler
Version 2.0 beta Aug  1 2021 00:27:36 (32-bit)
```

The full example and produced binaries can be found [here](http://dgql.org/~nathan/broken.tar.gz)

**Comment by jmalak** [comment]
I am not sure if I understand of your problem fully.

There is a few problems.
- you use wlink directive `file main.o,std.lib`, it is non-standard use of library, correct is `file main.o library std.lib`
- you use eliminate directive after including full library with highest priority

Try it with directive `file main.o library std.lib` instead of `file main.o, std.lib`

**Comment by negge** [comment]
Hi @jmalak, doing what you suggested and changing my directives did fix the problem.

```
$ git diff Makefile 
 $(BIN)/%.exe: $(BIN)/%.o $(OBJS) $(LIBS)
        $(guard)
-       PATH=$(WPATH) WATCOM=$(WATCOM) $(LD) name $@ $(LDFLAGS) file $(subst $(SPACE),$(COMMA),$^)
+       PATH=$(WPATH) WATCOM=$(WATCOM) $(LD) name $@ $(LDFLAGS) \
+        file $(subst $(SPACE),$(COMMA),$(filter %.o,$^)) \
+        library $(subst $(SPACE),$(COMMA),$(filter %.lib,$^))
        @mv $*.map $(BIN)
```

Silently producing an invalid EXE file is not great. Is there any chance you can fix the non-standard method so it has the same behavior? It is easy to detect if a file is a library or just an individual obj file. I do it in my linker XLINK here https://github.com/negge/xlink/blob/master/src/xlink.c#L2445

If the first byte of the OMF file is `OMF_THEADR = 0x80` or `OMF_LHEADR = 0x82` it is an OBJ file, if it is `OMF_LIBHDR = 0xF0` then it is a library file.

```
typedef enum {
  OMF_THEADR  = 0x80,  // Translator Header Record
  OMF_LHEADR  = 0x82,  // Library Module Header Record
  ..
  OMF_LIBHDR  = 0xF0,  // Library Header Record
} xlink_omf_record_type;

**Comment by jmalak** [comment]
The problem is that what you do is valid, you can link full library as object files.
But it need to understand what it will cause.
Anyway there is other problem with your BSS segment.
OW has memory model that any BSS segment must be part of DGROUP and OW standard name is _BSS.
Therefore your bss segment is outside of DGROUP.

You should use in your asm file something like

group dgroup data bss

**Comment by negge** [comment]
Thanks again @jmalak, I added a DGROUP for those segments and it worked. I am curious, why does a 32-bit library with a flat memory model need a DGROUP?

Also, why is the open watcom convention that uninitialized segments (bss) must be named BSS all upper case? This is a problem if you want to separate uninitialized data so only related fields are in the same BSS segment. Otherwise, nasm will put them all in the same segment.

My linker uses the CLASS field of the OMF segment and uses CODE, DATA and BSS to indicate which of those three types it is. Why use a naming convention or a DGROUP which unfortunately forces you to include everything, even unused fields?

**Comment by jmalak** [comment]
OW linker use all segments attributes to group segments together not only CLASS.
Segments must be compatible then it can be grouped together. wlink is capable use multiple data groups.
I understand you expect simplified handling for flat memory model, but OW linker use flat as one special case for generally segmented code/data with combined far/near data/code.
OW wlink is linker for 16/32-bit segmented data/code not only for flat where only near data/code are used.

**Comment by negge** [comment]
Does the DGROUP just associate the segments, or does it also specify an ordering for the data segments?

One reason I am being careful about how I group the fields in my data and bss segments is my linker XLINK goes out of its way to remove any segments that are not referenced by the program anywhere. I'm trying to understand what are the minimum requirements to get it working with WLINK so I can organize data appropriately.

Note, for some reason using the eliminate option does not do this for data segments that are unreferenced. I don't know if this is the case for BSS segments.

**Comment by jmalak** [comment]
All is about memory layout and segment ordering.
Below is segment ordering used by OW.

1. all segments not belonging to group "DGROUP" with class "CODE"¨
2. all other segments not belonging to group "DGROUP"
3. all segments belonging to group "DGROUP" with class "BEGDATA"
4. all segments belonging to group "DGROUP" not with class "BEGDATA", "BSS" or "STACK"
5. all segments belonging to group "DGROUP" with class "BSS"
6. all segments belonging to group "DGROUP" with class "STACK"

**Comment by negge** [comment]
So it is not clear to me why adding a DGROUP fixed the issue I first reported. There were basically two fixes you showed:

1) Passing all *.lib to the library directive and all *.o to the file directive
2) Adding a DGROUP

What was WLINK doing before without a DGROUP that was breaking the EXE file? It seems like that is still a bug.

**Comment by jmalak** [comment]
First to use same terminilogy.
EXE file format was OK, OS could load it.
Problem is that your expectation was different then wlink did.
wlink is "segmented" linker (near/far segments) therefore not work as "flat" linker which can automatically put all segments together.
wlink do full segmented processing with segments as they are near/far and decide if it is near or far segment.
If you do some mistake which cause segment is recognized as far by wlink then wlink process it regularly and result is undefined.
wlink can combine near/far segments therefore wlink is not able to report it as error.
