### ISSUE TITLE
Initialization of aggregate types failure

### ISSUE THREAD

**Issue by jmalak** [open-watcom/open-watcom-v2#728]
### Discussed in https://github.com/open-watcom/open-watcom-v2/discussions/727

<div type='discussions-op-text'>

<sup>Originally posted by **FredEckert** September  9, 2021</sup>
Hi, I am trying to use wcl386 with the -za99 and -aa compiler switches on some C99 code:

-aa : enable non-constant initializers for local aggregates or unions (#33, #34)
[-za99 : enable partial C99 compliance ](https://web.archive.org/web/20150503232909/http://openwatcom.org/index.php/C99_Compliance)

Example test.c program showing problem:
```
#include <stdio.h>
//Open Watcom C/C++ x86 32-bit Compile and Link Utility Version 2.0 beta Aug  1 2021 01:13:02 (64-bit)
//compile: wcl386 -d2 -w3 -za99 test.c          fails with E1054 on line 19
//compile: wcl386 -aa -d2 -w3 -za99 test.c      fails with E1063 on line 14

struct color_t{
        unsigned char red;
        unsigned char green;
        unsigned char blue;
};

int main(void) {
        //test.c(14): Error! E1063: Missing operand (-aa switch breaks this)
        const struct color_t C = { .red = 0x96, .green = 0x4B };
        printf("C.red=%x\nC.green=%x\nC.blue=%x\n", C.red, C.green, C.blue);

        //test.c(19): Error! E1054: Expression must be constant (-aa switch makes this work)
        unsigned char line = 1;
        const unsigned char position[] = {0xFE, 'H', 0xFE, 'G', 0, line};
        printf("%c\n", line);
        printf("%s\n", position);

        return 0;
}
```
I was hoping someone could explain the best way to resolve this situation.

Thank you,
Fred Eckert
</div>

**Comment by jmalak** [comment]
The Designated Initializers doesn't work properly with non-constant initializers (-aa option).
Compiler code for handling non-constant initializers with designated initializers need fixing.
Non-constant initializers works only without designated initializers.

**Comment by jmalak** [comment]
It is now fixed, that -aa option doesn't broke designated initializers.
Please check it with new OW "Current build" created after midnight.

**Comment by FredEckert** [comment]
I checked this fix with current build "Last updated 2021-09-13 01:42:15". The fix worked for the above test.c program using both the windows x64 and the DOS wcl386 builds. I was also able to successfully compile and run a large c99 project with the fix.

**Comment by jmalak** [comment]
Thanks for check.
OW is still not fully C99 compatible, but most of significant features should work.
If you will have any problem with OW then raise a bug issue, please.

**Comment by Fuerst2718** [comment]
Hint:
Compiling the following (senseless) code gives E1054 if you uncomment the line in the struct-declaration
// int Privileges[10]; /* uncomment line -> E1054 */

`/*
wcc386 ..\test.c -i="C:\WCC/h;C:\WCC/h/nt" -w4 -zastd=c99 -aa -od -d2 -6r -bt=nt -fo=.obj -mf
Open Watcom C x86 32-bit Optimizing Compiler
Version 2.0 beta Apr 10 2024 01:46:53 (32-bit)
*/

#include <stdio.h>

typedef struct _TOKEN_PRIVILEGES {
    int PrivilegeCount;
    // int Privileges[10]; /* uncomment line -> E1054 */
} TOKEN_PRIVILEGES;

int main(void) {
  
  int exampleLuid=22;

  TOKEN_PRIVILEGES tokenPriv = {
    .PrivilegeCount = exampleLuid,
  };

  printf("N=%d\n", tokenPriv.PrivilegeCount); // Prevent warning

  return 0;
}`

**Comment by jmalak** [comment]
You are right, there are several other problems with C99 agrregate variables initialization.
I have it on to-do list with higher priority.

**Comment by roytam1** [comment]
Trying to compile floating IPS v1.31 with openwatcom, and I'm using a fairly new ow2 build:

```
C:\devel\flips>wcl386 -aa -bt=nt -l=win95 -ox -D_WINDOWS -D_WIN32 -DWIN32 -D_NO_OLDNAMES flips.cpp
Open Watcom C/C++ x86 32-bit Compile and Link Utility
Version 2.0 beta May  3 2025 02:34:48 (32-bit)
Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.
        wpp386 flips.cpp  -aa -bt=nt -ox -D_WINDOWS -D_WIN32 -DWIN32 -D_NO_OLDNAMES
Open Watcom C++ x86 32-bit Optimizing Compiler
Version 2.0 beta May  3 2025 02:33:14 (32-bit)
Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1989-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.
Error! E068: invalid option
Note! N746: processing command line, switch: -aa
flips.cpp(531): Error! E400: col(53) cannot convert right expression for initialization
flips.cpp(531): Note! N630: col(53) source conversion type is 'mem'
flips.cpp(531): Note! N631: col(53) target conversion type is 'unsigned char *'
flips.cpp(553): Error! E400: col(53) cannot convert right expression for initialization
flips.cpp(553): Note! N630: col(53) source conversion type is 'mem'
flips.cpp(553): Note! N631: col(53) target conversion type is 'unsigned char *'
flips.cpp: 917 lines, included 107979, no warnings, 3 errors
Error: Unable to invoke "I:\WATCOM\BINNT\wpp386.exe"
```

flips.cpp line 531 is:
```
		struct mem rommem[2]={ roms[0]->read(), roms[1]->read() };
```

and that struct has a function read():
```
struct mem file::read()
{
	struct mem out;
	out.len = len();
	out.ptr = (uint8_t*)malloc(out.len);
	if (!read(out.ptr, 0, out.len))
	{
		free(out.ptr);
		struct mem err = {NULL, 0};
		return err;
	}
	return out;
}
```

**Comment by jmalak** [comment]
You have source code for C99 and above, but OW default mode is C89.
Use -za99 or -zastd=c99 option.

**Comment by roytam1** [comment]
> You have source code for C99 and above, but OW default mode is C89. Use -za99 or -zastd=c99 option.

adding `-za99` just producing more errors?

```
C:\devel\flips>wcl386 -aa -za99 -bt=nt -l=win95 -ox -D_WINDOWS -D_WIN32 -DWIN32 -D_NO_OLDNAMES flips.cpp
Open Watcom C/C++ x86 32-bit Compile and Link Utility
Version 2.0 beta May  3 2025 02:34:48 (32-bit)
Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.
        wpp386 flips.cpp  -aa -za99 -bt=nt -ox -D_WINDOWS -D_WIN32 -DWIN32 -D_NO_OLDNAMES
Open Watcom C++ x86 32-bit Optimizing Compiler
Version 2.0 beta May  3 2025 02:33:14 (32-bit)
Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1989-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.
Error! E068: invalid option
Note! N746: processing command line, switch: -aa
Compiling: flips.cpp
flips.cpp(218): Error! E029: col(20) symbol '_wcsdup' has not been declared
flips.cpp(432): Error! E029: col(19) symbol '_wcsicmp' has not been declared
flips.cpp(531): Error! E400: col(53) cannot convert right expression for initialization
flips.cpp(531): Note! N630: col(53) source conversion type is 'mem'
flips.cpp(531): Note! N631: col(53) target conversion type is 'unsigned char *'
flips.cpp(553): Error! E400: col(53) cannot convert right expression for initialization
flips.cpp(553): Note! N630: col(53) source conversion type is 'mem'
flips.cpp(553): Note! N631: col(53) target conversion type is 'unsigned char *'
flips.cpp(799): Error! E029: col(43) symbol '_wcsicmp' has not been declared
flips.cpp: 917 lines, included 107979, no warnings, 6 errors
Error: Unable to invoke "I:\WATCOM\BINNT\wpp386.exe"
```

**Comment by jmalak** [comment]
It looks like you have not setup OW correctly.
The message about missing function prototypes is clear.
You need properly setup INCLUDE environment variable or use -I... compiler option to define header files search path for your target.
You probably cross compile then it is absolutely necessary to setup it because each target has its own header files.
[Details about OW use](https://github.com/open-watcom/open-watcom-v2/wiki/OW-tools-usage-Overview)
You need to setup properly WATCOM, PATH and INCLUDE environment variables.

Next problem is -aa option which is invalid for wcl.. tool, you need to pass it to C compiler.
Sorry you use C++ source that C++ compiler doesn't use -aa option it is valid only for C compiler.
Anyway it can be namespace issue because these symbols are Microsoft extension I think.
For C++ compiler -za99 has no sense I think there are different standards.
OW C++ compiler support only 98 standard and some newer features, but C language interface is defined by C++ standard not by C standard.

If it is C source then you should use C compiler instead of C++ compiler, you can specify option -cc for wcl... because .cpp extension is by default indicated as C++ source and wcl call C++ compiler instead of C one. Best practice is to use .c extension for C code and .cpp for C++ code.

**Comment by crazii** [comment]
I found -za99 -aa works for simple structs.
But there are some cases not working:

1. bitfields members of a struct
2. array members, e.g. char xxx[n];
3. members of a another struct type.

Those are encountered in my project, which is not yet made public.

Apparently those problem does not exist in wpp/wpp386, as std C++ allows it. Previously I changed the .c to .cpp and used wpp/wpp386 to workaround this problem, but it seems "weird" because it is total C source. Now I don't use wpp but setup memeber manually.

**Comment by jmalak** [comment]
@crazii Thanks for your information.
It is in my todo list for next development to review C aggregate types initialization including non static arrays initialization and checking uninitialized fields.
Please could you add code sample with structure and its initialization code to have more test samples.
It can be obfuscated.
