### ISSUE TITLE
Error compiling with GCC

### ISSUE THREAD

**Issue by MikeyG** [open-watcom/open-watcom-v2#730]
I was compiling the git sources (pulled 13 Sep) and I get the following error:
   
buildrel
   
`%make prepare_gendev_tmp_batch
gendev mono01.cop
Segmentation fault
Error(E42): Last command making (gencop;mono01.cop) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (/home/mgreene/owbuild/pass1src/docs/nt/wbrw.gh) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed`
   
GCC version:
   
`Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/10.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-10.3.0-r2/work/gcc-10.3.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/10.3.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/10.3.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/10.3.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/10.3.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/10.3.0/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --disable-libunwind-exceptions --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 10.3.0-r2 p3' --disable-esp --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libssp --disable-libada --disable-systemtap --disable-vtable-verify --disable-libvtv --without-zstd --enable-lto --without-isl --enable-default-pie --enable-default-ssp
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.3.0 (Gentoo 10.3.0-r2 p3)`

**Comment by jmalak** [comment]
Do you have DOSBOX installed on your host system?

**Comment by MikeyG** [comment]
I had DOSBOX installed, but the system is headless. I added:

export SDL_VIDEODRIVER=dummy

Everything seems okay now - I'll close this.

**Comment by jmalak** [comment]
setting SDL_VIDEODRIVER=dummy is part of script to handle wgml DOSBOX call.
It is included in build/mif/wgmlcmd.mif which generate batch file for DOSBOX.
It should work without extra setup.

**Comment by MikeyG** [comment]
That's odd, the only other thing I did was put the complete path to dosbox in the config rather than just having dosbox.

**Comment by jmalak** [comment]
May be it is problem with DOSBOX installation.
OW repository contains DOSBOX for Continuous Integration build, it is in ci/nt386 subdirectory for Windows host.
I am thinking to preconfigure it for regular build by Windows users.
But for Linux it supposes to be install from standard package that dosbox command should be available without path.
