### ISSUE TITLE
WCL DOS Build does not function with CPP or OBJ files properly in DOSBox

### ISSUE THREAD

**Issue by doctorjei** [open-watcom/open-watcom-v2#735]
**How to reproduce**
Use wcl to build a simple CPP file (tested with "int main() { return 0; }") `wcl simple.cpp`

**Expected results**
Program will build

**Actual results (output)**
Open Watcom C/C++ x86 16-bit Compile and Link Utility
Version 2.0 beta Sep 18 2021 00:35:13 (16-bit)
Copyright (c) 2002-2021 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
	wpp CPP 
DOS/4G Protected Mode Run-time  Version 2.01a
Copyright (c) Tenberry Software, Inc. 1996
Open Watcom C++ x86 16-bit Optimizing Compiler
Version 2.0 beta Sep 18 2021 00:29:23 (32-bit)
Copyright (c) 2002-2021 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1989-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
Error! E059: unable to open 'CPP'
CPP: no lines, no warnings, 1 error
Error: Compiler returned a bad status compiling "CPP"

I have tested with:
DOSBox 0.74-3
DOSBox-x 0.83.17

File can be compiled with "wcc" to create object file, but then wcl yields similar results if trying to build from OBJ.

The command appears to work fine when compiling 16-bit executables from the Win64 versions of the build tools.

**Comment by jmalak** [comment]
Thanks for your bug report.
There is some bug in DOS implementation of LFN version of opendir CRTL function.
I will fix it ASAP.

**Comment by jmalak** [comment]
It should be fixed now in git repository.
the same problem in owcc (shared code with wcl)
Please recheck.

**Comment by doctorjei** [comment]
Just FYI, I tested, and everything is working now on the new build. Thanks!
