### ISSUE TITLE
cp command not found in build script, after clean, no rel dir.

### ISSUE THREAD

**Issue by andi8086** [open-watcom/open-watcom-v2#743]
Build scripts are missing important checks!!

If a user has only installed git with git-bash and not integrated the git path, which is recommended by the way, then there is no cp command in windows. A hint is needed to include the C:\program files\git\usr\bin into the path.

Furthermore, there is no "rel" directory after executing clean.bat (or there was none in the beginning), so build also fails because of that.
Maybe this is because I want to build the installers in the first run? This is a lot of guessing here again... Again - missing checks, just wrong assumptions inside the make scripts as well. 
Wrong target dependencies (missing dependencies) in build scripts...
(Confirmed now, set OWDISTRBUILD=0, which was 1 before, did the trick in setvars.bat)

It has to be checked, that this is not evaluated if the user has not build the release files.

**Comment by jmalak** [comment]
cp command is no more used by OW build system, that any similar changes are necessary.
rel directory is not used by default and if it is necessary it is created by builder.
If you specify your own rel directory then you are responsible for it, to be existing directory.

**Comment by jmalak** [comment]
I checked it on fresh system and all is going correctly.
