### ISSUE TITLE
wrc does not include the source directory by default

### ISSUE THREAD

**Issue by ccawley2011** [open-watcom/open-watcom-v2#747]
By default, `wrc` seems to add the current working directory to the include paths, but not the directory containing the source file. This differs from `wcc386`, which does include the source directory by default, as well as both `rc` from MSVC 2019 and `windres` from binutils.

**Comment by jmalak** [comment]
It is known bug in wrc include files processing #680.
It will require rework include path processing in OW C preprocessor which is used by wrc.
I have it on my to-do list but it is not sinple fix.

**Comment by jmalak** [comment]
It should be fixed now
