### ISSUE TITLE
Open Watcom binaries cannot stat() anything on 64-bit Linux (x86_64) on a filesystem with device node numbers higher than 256

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#752]
There seems to be a problem on a newer laptop of mine that is a combination of several factors as far as I can tell:
- The kernel is 64-bit
- Open Watcom compiles itself as i386 32-bit
- Open Watcom tools use stat() to check for the existence of files or examine their status
- The filesystem was mounted from an NVME (Non-Volatile Memory Express) storage device, which has device node numbers higher than 255: (259, 6) in this case.
- stat() for any file fills those device node numbers into st_dev
- The Linux i386 compatibility layer for 64-bit kernels will fail stat() with EOVERFLOW if any member of stat() on return is too large for the structure returned to userspace, including the inode, dev, and rdev fields, and of course the file size. There is code in sys_newstat(), the function behind SYS_stat, to return that error if the device node is "not valid" i.e. either number is 256 or higher.

On my other laptop, Open Watcom works just fine because I am running it off of an SSD connected through a SATA controller, device node numbers (8, 6) which is well below 256.

One symptom of this issue is that wmake acts as if the source file to compile into an object doesn't exist, then complains that it cannot make the target.

In DOSLIB, for bootsect/i13geom/boot1.asm, wmake stat()s the file, but even though the ASM file is well below 2GB (about 4KB in fact!), the stat() call returns EOVERFLOW.

**Comment by joncampbell123** [comment]
This is something to take seriously because it means anyone running Linux on a newer laptop with NVME storage (as most laptops are now) will be unable to do anything with Open Watcom at all.

**Comment by joncampbell123** [comment]
Here is where stat() leads to in the Linux kernel, or rather, what it uses to copy the structure to userspace and validate it before returning to userspace.

https://elixir.bootlin.com/linux/latest/source/fs/stat.c#L337

https://elixir.bootlin.com/linux/latest/source/fs/stat.c#L344

Note the !valid_dev() checks. When compiled again to run in the 32-bit compatibility API, valid_dev leads to old_valid_dev() which leads to a check for whether device numbers are below 256:

https://elixir.bootlin.com/linux/latest/source/include/linux/kdev_t.h#L24

NVME devices end up with major 259, which fails that check.

**Comment by joncampbell123** [comment]
Note that this doesn't affect anything linked against GLIBC because GLIBC will automatically use newer stat functions not limited in this way, whether 32-bit or 64-bit.

**Comment by joncampbell123** [comment]
Here is the behavior seen in "strace" in wmake attempting to determine boot1.asm.

10523 stat("all", 0xff9065d4)           = -1 ENOENT (No such file or directory)
10523 access("all", F_OK)               = -1 ENOENT (No such file or directory)
10523 stat("dos86t/boot1.img", 0xff90658c) = -1 ENOENT (No such file or directory)
10523 access("dos86t/boot1.img", F_OK)  = -1 ENOENT (No such file or directory)
10523 stat("boot1.asm", 0xff906544)     = -1 EOVERFLOW (Value too large for defined data type)
10523 access("boot1.asm", F_OK)         = 0
10523 stat("boot1.asm", 0xff906544)     = -1 EOVERFLOW (Value too large for defined data type)
10523 access("boot1.asm", F_OK)         = 0
10523 stat("boot1.asm", 0xff906544)     = -1 EOVERFLOW (Value too large for defined data type)
10523 access("dos86t/boot1.img", F_OK)  = -1 ENOENT (No such file or directory)

Notice EOVERFLOW for a file that is less than 4KB in size, but the device field major is 103h (259).

  File: boot1.asm
  Size: 3230            Blocks: 8          IO Block: 4096   regular file
Device: 10306h/66310d   Inode: 28443402    Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-11-06 14:15:02.422818193 -0700
Modify: 2021-11-06 14:15:02.422818193 -0700
Change: 2021-11-06 14:15:02.422818193 -0700
 Birth: 2021-11-06 14:15:02.422818193 -0700

crw------- 1 root root 248, 0 Nov  5 23:04 /dev/nvme0
brw-r--r-- 1 root root 259, 0 Nov  5 23:04 /dev/nvme0n1
brw-r--r-- 1 root root 259, 1 Nov  5 23:04 /dev/nvme0n1p1
brw-r--r-- 1 root root 259, 2 Nov  5 23:04 /dev/nvme0n1p2
brw-r--r-- 1 root root 259, 3 Nov  5 23:04 /dev/nvme0n1p3
brw-r--r-- 1 root root 259, 4 Nov  5 23:04 /dev/nvme0n1p4
brw-r--r-- 1 root root 259, 5 Nov  5 23:04 /dev/nvme0n1p5
brw-r--r-- 1 root root 259, 6 Nov  5 23:04 /dev/nvme0n1p6

**Comment by joncampbell123** [comment]
A preliminary solution (that I am testing now) is to use stat64() instead, which does not have the st_dev limit. Note the lack of !valid_dev checking.

https://elixir.bootlin.com/linux/latest/source/fs/stat.c#L487

The idea I have is to change the stat() symbol in Open Watcom's C library to call stat64() instead of the stat() syscall, and return EOVERFLOW only if the file size is too big. I doubt Open Watcom cares about st_dev, st_ino, and st_rdev anyway.

**Comment by joncampbell123** [comment]
Here is the same DOSLIB build script running wmake, now with c/linux/stat.c calling stat64() instead of stat().

14611 stat64("all", 0xff9ad724)         = -1 ENOENT (No such file or directory)
14611 access("all", F_OK)               = -1 ENOENT (No such file or directory)
14611 stat64("dos86t/boot1.img", 0xff9ad6dc) = -1 ENOENT (No such file or directory)
14611 access("dos86t/boot1.img", F_OK)  = -1 ENOENT (No such file or directory)
14611 stat64("boot1.asm", {st_mode=S_IFREG|0644, st_size=3230, ...}) = 0
14611 ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
14611 write(1, "mkdir -p dos86t\n", 16) = 16
14611 mkdir("dos86t", 0777)             = -1 EEXIST (File exists)
14611 write(1, "nasm -o dos86t/boot1.img -f bin boot1.asm\n", 42) = 42
14611 fork()                            = 14612
14611 wait4(14612,  <unfinished ...>
14612 execve("/bin/sh", ["sh", "-c", "nasm -o dos86t/boot1.img -f bin boot1.asm"], 0x9570040 /* 27 vars */) = 0

**Comment by jmalak** [comment]
Thanks. It is submitted into git repository.
