### ISSUE TITLE
Missing fdivrp instruction with inline assembly

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#755]
When writing inline assembly FPU code the fdivrp instruction does not exist. Consider the example:

```c
static float test_fdivrp(float a, float b);
#pragma aux test_fdivrp parm [ 8087 ] [ 8087 ] = \
  "fdivrp" \
  value [ 8087 ]

void main() {
  test_fdivrp(0, 1);
}
```

I get this error

```bash
$ wcc386 -q -s test.c
test.c(3): Error! E1156: Assembler error: 'Invalid instruction operands'
```

**Comment by jmalak** [comment]
It is correct because [8087] register (long double) is incompatible with float.
If you want to operate on float then you need to load float to [8087] register before fdivrp.
Anyway fdivrp instruction is supported but it have only [8087] operands and result that you must ensure loading of float on 8087 stack and removing result from stack.

Anyway read documentation about #pragma aux and [8087] registers passing values
below is example how C fpu in-line your function with appropriate interface for input/output of C variables can looks.

```
/* 32-bit version */

extern  void    test_fdivrp( float *a, float *b, float *out );
  #pragma aux  test_fdivrp = \
        float_fixup "fld dword ptr [eax]" \
        float_fixup "fld dword ptr [edx]" \
        float_fixup "fdivrp" \
        float_fixup "fstp dword ptr [ebx]" \
        __parm __caller [__eax] [__edx] [__ebx]

```

**Comment by jmalak** [comment]
Sorry my fault.
I will review why it is not working.

Please what compiler options you use?

**Comment by negge** [comment]
Hi @jmalak, I show the compiler options I'm using above `wcc386 -q -s test.c`. Thanks for looking into this.

**Comment by negge** [comment]
I can make this example work by explicitly specifying the parameters:

```c
static float test_fdivrp(float a, float b);
#pragma aux test_fdivrp parm [ 8087 ] [ 8087 ] = \
  "fdivrp st(1),st" \
  value [ 8087 ]

void main() {
  test_fdivrp(0, 1);
}
```

However, just specifying `fdivrp` should use the default `DE F1`. See the documentation here:

https://www.felixcloutier.com/x86/fdivr:fdivrp:fidivr

**Comment by jmalak** [comment]
It is fixed in git repository.
There were a mistake in definition for FPU instruction FDIVRP without operands.
It was incorrectly defined as FPU instruction FDIVR without operands.
New OW build will be available after rebuild by Azure Pipelines.

**Comment by negge** [comment]
Excellent, thank you. I only use the release builds so I am not able to verify this.

**Comment by jmalak** [comment]
you can download latest CI build (full binary contents) and simply copy contens over your installation, it replaces all files by new version. Or you can wait for Release build (is is build after this UTC midnight) and install it.
