### ISSUE TITLE
Fails to build under Ubuntu 20.04

### ISSUE THREAD

**Issue by robertapengelly** [open-watcom/open-watcom-v2#759]
Get the following error when trying to build under Ubuntu 20.04:

===== 13:59:01 /home/user/Downloads/open-watcom-v2/bld/wsample =====
= 13:59:01 /home/user/Downloads/open-watcom-v2/bld/wsample/dosi86 ==
cl wsample.exe
Error! E2028: __EPI is an undefined reference
file realmode.obj(/home/user/Downloads/open-watcom-v2/bld/wsample/c/realmode.c): undefined symbol __EPI
file sample.obj(/home/user/Downloads/open-watcom-v2/bld/wsample/c/sample.c): undefined symbol __EPI
Error(E42): Last command making (wsample.exe) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed

**Comment by jmalak** [comment]
It looks like some misconfiguration of OW build system.
__EPI symbol is not used by sampler for 16-bit DOS, it is used only by 32-bit code.
do you have your own copy of setvars.sh properly configured?
try to do full cleanup by `sh clean.sh` in OW root directory.

**Comment by robertapengelly** [comment]
I did git pull, tried building and got that error.  The only thing I've ever altered is for it to use dosbox.
I'm in the process of re-building now I'll let you know what happens once its finished.

**Comment by jmalak** [comment]
Please read description of basic configuration and comment in setvars.sh script.
create your own copy of this script and change a few parameters.
[OW Build](https://github.com/open-watcom/open-watcom-v2/wiki/Build)

**Comment by robertapengelly** [comment]
Done as you said and ran clean.sh then rebuild and it appears to have worked.  Don't know how it got messed up as it was working before.

**Comment by jmalak** [comment]
It is OK

**Comment by robertapengelly** [comment]
Yes, after running clean.sh everything has compiled fine.

**Comment by jmalak** [comment]
If you will have any problems or need more info then create a issue here.
