### ISSUE TITLE
Add support for builtin __COUNTER__

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#766]
Both gcc and clang support the `__COUNTER__` language extension

```C
#include <stdio.h>

void main() {
  printf("%i\n", __COUNTER__);
  printf("%i\n", __COUNTER__);
}
```

This produces the following output
```
$ gcc count.c -o count
$ ./count
0
1
```

**Comment by jmalak** [comment]
I don't want to add any similar extensions which are not portable (not defined by C standard).
It is similar like request for **`#warning`** pre-processor directive.
It is not standardized anywhere each vendor can implement it or not by its own method.
It is not this case, but by example it should start on 0 or 1?
We have no plan to be clone of MS or GCC.
They have plenty of extensions which is not implemented in OW.
If we start add such non-standard extensions then it will be never-ending story.
