### ISSUE TITLE
Versioninfo has wrong language ID

### ISSUE THREAD

**Issue by danielmarschall** [open-watcom/open-watcom-v2#768]
I am not sure if this bug has been fixed, since I am using a very old build of OpenWatcom 2.0 (1 Nov 2017 beta).

I have a version.rc file with the following contents

```
LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US
LANGUAGE 0x09, 0x01
VS_VERSION_INFO  VERSIONINFO
 FILEVERSION     VI_VERS_NUM
 PRODUCTVERSION  VI_VERS_NUM
 FILEFLAGSMASK   VS_FFI_FILEFLAGSMASK /*0x3fL*/
 FILEFLAGS       VI_FLAGS
 FILEOS          VOS__WINDOWS32
 FILETYPE        VFT_DLL
 FILESUBTYPE     VFT2_UNKNOWN
BEGIN
....
END
```

When I compile it using Visual Studio, then the resource is visible as "Version Info  1 : 1033"  (En-US) in a resource editor.

When I compile it using OpenWatcom 2.0 , it is visible as "Version Info 1 : 0" (= Neutral).

Is there any newer Windows build available? I only found the 2017 beta build on SourceForge!

**Comment by jmalak** [comment]
OW resource compiler ignore language and use "neutral" no-language definition.

Anyway sourceforge is not used for distribution of OW 2
you can use [regular release builds](https://github.com/open-watcom/open-watcom-v2/releases).

**Comment by jmalak** [comment]
It is real bug in OW resource compiler.
It has hard-coded neutral language for VERSIONINFO resource.
I will fix it ASAP.

**Comment by LowLevelMahn** [comment]
> I am not sure if this bug has been fixed, since I am using a very old build of OpenWatcom 2.0 (1 Nov 2017 beta).
 btw: 

you can always grab a freshly build version here: https://github.com/open-watcom/open-watcom-v2/releases/tag/Current-build
no need for installation just use the new version of the compiler and test if the issue still occures

**Comment by danielmarschall** [comment]
> you can always grab a freshly build version here: https://github.com/open-watcom/open-watcom-v2/releases/tag/Current-build no need for installation just use the new version of the compiler and test if the issue still occures

Thank you for the hint! I didn't see it when I was searching for a new version, and Google only showed me SourceForge. I think it would be good if there was a large download-button at https://open-watcom.github.io/ which would redirect to the release page. When I was at the GitHub repo, I have read the README file but it didn't mention about downloads and so I thought I need to compile the IDE myself. I didn't see that there is a "Releases" link at the right side.

**Comment by jmalak** [comment]
I little rework main readme page to be Releases download more transparent

**Comment by jmalak** [comment]
It is fixed now in git repository

**Comment by danielmarschall** [comment]
I can verify that it now works with the latest build. Thank you for the bugfix!
