### ISSUE TITLE
IDE log bug when lines are too long

### ISSUE THREAD

**Issue by danielmarschall** [open-watcom/open-watcom-v2#769]
Hello,

after updating from the 2017 version to the newest build, I noticed a bug in the "IDE Log" window.

My project has very long lines during build.

See the log file here:
[filterfoundry.txt](https://github.com/open-watcom/open-watcom-v2/files/7621079/filterfoundry.txt)

When the project is building, the IDE log will scroll to the bottom right corner (instead of just scrolling down). When I scroll left again, the view is very broken. It is hard to explain. The texts are refreshing in the moment you click them and everything is glitched. I could make a video of it, if it helps.

**Comment by jmalak** [comment]
Thanks for your bug report.

**Comment by jmalak** [comment]
#721

**Comment by nathanpc** [comment]
This bug is even more noticeable in the Debugger, where every control has this issue.

**Comment by jmalak** [comment]
Yes, it is scrolling bug in gui subproject which is used by Debugger, IDE and Profiler projects.
I will fix it ASAP.

**Comment by jmalak** [comment]
fixed by commit 12afe6e22d09473ac3ddb69abf699cbb1945c844
