### ISSUE TITLE
wcc does not allow unnamed structs, any other way to have as static_assert feature?

### ISSUE THREAD

**Issue by LowLevelMahn** [open-watcom/open-watcom-v2#776]
im using a macro to get some sort of static assert - break compilation if fails
with Borland C++ 3.1, but i want to switch over my code to OpenWatcomV2 - way better and easier to handler under linux/windows :)

```
#define STATIC_ASSERT(COND) struct{char static_assertion[(COND)?1:-1];};
STATIC_ASSERT(sizeof(char)==1)
STATIC_ASSERT(sizeof(int8)==1)
STATIC_ASSERT(sizeof(int16)==2)
```

gives an Error! E1026: Invalid declarator on line 2 - i think because of the unnamed struct

any idea how to have something like a static assert with OpenWatcom?

**Comment by jmalak** [comment]
I don't think it is valid code.
Anyway OW support unnamed structures but structure prototype can not be without name.
Unnamed structure can be only as member of other structure.

For static assert you can ask google for sample code and try what will be suitable.
If you will rely to C99 then you must use -za99 option.

**Comment by LowLevelMahn** [comment]
> For static assert you can ask google for sample code and try what will be suitable for you.

most of the google examples are ugly - adding the message to the assertion struct - but its ok

thx
