### ISSUE TITLE
I am planning to remove all references to Discord server

### ISSUE THREAD

**Issue by jmalak** [open-watcom/open-watcom-v2#783]
I want remove all references to Open Watcom V2 discord server from Open Watcom V2 site for reason which I describe in [issue](https://github.com/open-watcom/open-watcom-v2/issues/462). I asked owner of this server to remove any references to Open Watcom V2 because it doesn't serve its original purpose.
May be I am only more sensitive to such attacks against Open Watcom V2.
Please comment this in [issue](https://github.com/open-watcom/open-watcom-v2/issues/462) what you think about it.

**Comment by jmalak** [comment]
I created the new Discord Server "Open Watcom 2.0" to help OW2 users and developers and not confuse them with personal attacks against Open Watcom 2.0 like now on the unmanaged Discord Server, which was created for OW2 in the past but does not serve the purpose for which it was created.
I removed the link to existing Discord server from the Open Watcom 2 site and replaced it with a new [invitation link] (https://discord.gg/39w5wZM89p) for the new Discord server, which is under the control of the Open Watcom 2.0 development group on Github. It will be monitored and moderated for any attempts to use damage and any actions against Open Watcom 2.
Open Watcom 2.0 is not ideal, but there are people who use it or want to use it.
I understand that some people need to express their negative views on OW2.
I don't want to stop them, but they shouldn't do it on servers that support Open Watcom 2.0 users.

You can send this invitation link to anyone who is interested in OW 2.
The server has well-defined rules for use (I hope) and each user must confirm that accepts them.

**Comment by jmalak** [comment]
I finished creation of new Discord server which is fully configured and running.
Use new [invitation link](https://discord.gg/39w5wZM89p) to get access to this Discord server.

**Comment by SeanRamey** [comment]
I have complied with renaming the server to "Open Watcom" and made an announcement to the community. No other changes will be made.

**Comment by jmalak** [comment]
OK, Thanks.

**Comment by jmalak** [comment]
The Discord Server was renamed from temporary name "Open Watcom 2.0" to "Open Watcom V2".
