### ISSUE TITLE
Bug in <graph.h>'s cursor-drawing code causes program crash

### ISSUE THREAD

**Issue by tkchia** [open-watcom/open-watcom-v2#785]
The following simple program weirds out during the `_outtext(.)` call, and before the `getch()`:
```
#include <conio.h>
#include <graph.h>

int main(void)
{
	_setvideomode(_VRES16COLOR);
	_displaycursor(_GCURSORON);
	_outtext("Hello world!");
	getch();
	_setvideomode(_DEFAULTMODE);
	return 0;
}
```
(The program works properly if I say `_displaycursor(_GCURSOROFF)` instead of `_displaycursor(_GCURSORON)`.)

The crash is apparently caused by a glitch in [the `_L0DrawLine` routine](https://github.com/open-watcom/open-watcom-v2/blob/23e69f020221d1d8269c4dd0a0b1229d4d424d8f/bld/graphlib/c/l0drwlin.c#L80) which tries to compile code at runtime to draw a line.  The code produced at runtime turns out to be bogus.  Specifically,
```
#define OutInt( p )     *(unsigned int COMP_FAR *)stack = p; p += sizeof( int )
```
should most probably be
```
#define OutInt( p )     *(unsigned int COMP_FAR *)stack = p; stack += sizeof( int )
```

Thank you!

**Comment by jmalak** [comment]
Thanks for fix, submitted.

**Comment by tkchia** [comment]
Thank you!
