### ISSUE TITLE
Command line output should go to stdout not stderr

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#786]
When redirecting output from `wcc386` to a file, the command line parameters are not captured but instead just the copyright info. In linux:

```
$ wcc386 > out.txt
[... all of help text ...]
$ cat out.txt
Open Watcom C x86 32-bit Optimizing Compiler
Version 2.0 beta Dec  1 2021 00:27:52 (32-bit)
Copyright (c) 2002-2021 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
```

Instead it would be better to write the help text to stdout so it can be used with other tools like `less` `grep` etc.

**Comment by jmalak** [comment]
Now all main tools use non-paging help output to stdout.

**Comment by jmalak** [comment]
it is fixed now in git repository.
