### ISSUE TITLE
inttypes.h broken in c++ mode (stdint.h is OK)

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#794]
```c
//#include <stdint.h>	/* <-- this is good */
#include <inttypes.h>	/* <-- this is bad. */

uintptr_t mem;
```

```
$ wpp386 -zq -fo=1.obj 1.c
1.c(4): Error! E498: col(11) syntax error before 'mem'; probable cause: incorrectly spelled type name
```

**Comment by sezero** [comment]
This is with CI build from git commit f9712045118b7ce67ee6a533bc24b08b57d62dca

**Comment by sezero** [comment]
Obviously the `using std::XXX` stuff are missing if `inttypes.h` is included alone.
If `inttypes.h` and `stdint.h` are included both, things work, because, well see the
diff between preprocesor outputs:
```diff
--- 1.i~
+++ 1.i
@@ -149,3 +149,32 @@
 using std::strtoumax;
 using std::wcstoimax;
 using std::wcstoumax;
+ #pragma read_only_file
+using std::int8_t;
+using std::uint8_t;
+using std::int16_t;
+using std::uint16_t;
+using std::int32_t;
+using std::uint32_t;
+using std::int64_t;
+using std::uint64_t;
+using std::int_least8_t;
+using std::uint_least8_t;
+using std::int_least16_t;
+using std::uint_least16_t;
+using std::int_least32_t;
+using std::uint_least32_t;
+using std::int_least64_t;
+using std::uint_least64_t;
+using std::int_fast8_t;
+using std::uint_fast8_t;
+using std::int_fast16_t;
+using std::uint_fast16_t;
+using std::int_fast32_t;
+using std::uint_fast32_t;
+using std::int_fast64_t;
+using std::uint_fast64_t;
+using std::intptr_t;
+using std::uintptr_t;
+using std::intmax_t;
+using std::uintmax_t;
```

So: `inttypes.h` seem to need an explicit inclusion of `stdint.h`
even in c++ mode,  like below, and things do work with that:
```diff
--- inttypes.h~
+++ inttypes.h
@@ -26,6 +26,10 @@
 
 #include <cinttypes>
 
+#ifndef _STDINT_H_INCLUDED
+ #include <stdint.h>
+#endif
+
 // C99 types in inttypes.h.
 using std::imaxdiv_t;
 
```

**Comment by jmalak** [comment]
Thanks for your bug report.
C++ Compiler for some reason ignores command `using std::uintptr_t` in `stdint.h` therefore `uintptr_t` is not visible in global namespace.
The same problem is probably with all data types defined in `stdint.h`.
I will fix it.

**Comment by sezero** [comment]
>  C++ Compiler for some reason ignores command `using std::uintptr_t` in `stdint.h` therefore `uintptr_t` is not visible in global namespace.

The problem is `using std::uintptr_t` never gets into `inttypes.h`,
because they are only in `stdint.h` and inttypes.h does not include
stdint.h. Explicitly including `stdint.h` from `inttypes.h` as I
suggested above fixes things for me.

**Comment by jmalak** [comment]
It looks like stdint.h is included for some reason, I tried to preprocess your sample code.
I will review my test environment setup i looks like it is somehow damaged.

**Comment by jmalak** [comment]
Sorry I didn' refresh WEB page that I answered much earlier entry and it looks as nonsense.
Yo are right, the problem is inclusion as you describe.
It is from Microsoft, not necessary for C/C++ standards.
Such inclusions cause similar problems, backward compatibility versus standards.
I will fix inclusions to use correct files.
