### ISSUE TITLE
No return statement

### ISSUE THREAD

**Issue by maddin200** [open-watcom/open-watcom-v2#796]
[/bld/src/old_win/edit/efont.c line 159
Code 👍   switch( (WORD) data ) {
    case FONT_DATA:
        curr = MemAlloc( sizeof( font_info ) );
        if( curr == NULL ) return( FALSE );
        farfont = MK_FP32( logfont );
        curr->charset = farfont->lfCharSet;
        curr->pitch_family = farfont->lfPitchAndFamily;
        _fstrcpy( curr->name, farfont->lfFaceName );
        if( FontTail == NULL ) {
            FontHead = FontTail = curr;
            curr->index = 0;
        } else {
            FontTail->next = curr;
            curr->index = FontTail->index + 1;
            FontTail = curr;
        }
        return( curr->index + 1 );

    case FONT_SIZES:
        newsize = MemRealloc( CurrFont->sizes,
                sizeof( short ) * (CurrFont->size_count+1 ) );
        if( newsize == NULL ) return( 0 );
        CurrFont->sizes = newsize;
        farfont = MK_FP32( logfont );
        CurrFont->sizes[ CurrFont->size_count ] = farfont->lfHeight;
        CurrFont->size_count++;
        return( CurrFont->size_count );
    }
 // <- no return in default

**Comment by jmalak** [comment]
Thanks for your bug report.
It is fixed now.
