### ISSUE TITLE
Watcom Resource Editor

### ISSUE THREAD

**Issue by HnkGitHub** [open-watcom/open-watcom-v2#808]
Platform: NT64
Version: Git February 4, 2022

The menu section of the resource editor is not restoring the values
for the menu IDs. It saves the values in a header file, requests that
the header file be loaded, and then it puts the wrong IDs in for the 
menus.

Here's a simple menu that the IDE cannot handle correctly

```
#include "main.h"
MENU_1   MENU
BEGIN
       POPUP    &File
       BEGIN
             MENUITEM    E&xit,    IDM_EXIT
`      END
END
```

Main.h just has one #define statement: #define IDM_EXIT   101
When the user clicks on the Menu item in the ide, the ide 
puts an arbitrary value in for IDM_EXIT. This takes place 
after the file has been saved. It happens whether you are 
using the IDE directly to create the Resource menu, or whether
you use a resource script file (.rc). I believe the other resource
editors handle this correctly and save the ID numbers on 
returning to edit the resource. I checked the behavior on Watcom 1.9
and the Menu Resource Editor handled the IDs correctly 
restoring the correct values which were entered and saved
from a previous session.

Thanks,

Henry

**Comment by jmalak** [comment]
Thanks for problem report.
Please could you give me compilable resource source file for your problem to be able check resource editor over .res file or you can add here appropriate compiled .res file.

**Comment by jmalak** [comment]
I checked this functionality with some other sample and the behavior is real strange.
I will review menu support generally because there is some odd saving to file, somehow broken.

**Comment by jmalak** [comment]
Anyway there are several possible saves.
- save on menu resource level (only menu resource in one file)
- save on resources level (all resources in one resource file)
- save on executable level (save to executable image)

there is problem with passing user menu changes between these levels

**Comment by jmalak** [comment]
This is first fix for incorrect read data from resource file.
Second fix is necessary for saving result file (for overwite existing resource file).

**Comment by jmalak** [comment]
Now it should be OK.
There were old double bugs and first hide second. All older OW versions including 1.9 didn't do backup of original file before apply changes.
Please could you recheck your issue with latest CI build.

**Comment by HnkGitHub** [comment]
Thanks. It's refreshing to not have to resave your  original settings every time your update the menu.

Another bug in this I didn't mention. But I believe it's also present in version 1.9: An odd message pops up after the original file has been saved. It says the Input Files were not loaded. And then it loads whatever information I put in before and I have no idea as to what Input files it refers.

But at least now I don't have to resave the Menu ID values for the menu to keep the menu functioning in the program. If you want, I'll post a screenshot of the message. It appears with the icon warning symbol in a Message Box: MB_ICONWARNING.  It does not appear on creation of a menu resource, just after you open the resource editor again to update or edit the file. 

It's kind of disconcerting to see a warning and have no idea as to how to remedy the situation. I don't think there is a problem. I don't believe I've done anything incorrectly. But the program keeps on warning me about some input files that did not load.

THanks,  this is a different bug.

**Comment by jmalak** [comment]
Thanks for testing.
If you put here some sample code which exhibit the problem it simplify resolution.
It could be a problem with loading header files for resources. OW resource editor use the same name for header file as resource or executable and with extension is .h  It could be a problem or any other related to input source of resource which you edited.

**Comment by HnkGitHub** [comment]
Here's a simple project. When prompted for the header file, use the "sysmets1.h" file
[report.zip](https://github.com/open-watcom/open-watcom-v2/files/8066387/report.zip)
.

**Comment by jmalak** [comment]
Wha you open as first *.exe or *.res?

**Comment by jmalak** [comment]
Please could you record steps how reproduce it.
If I open *.exe or *.res I didn't do any prompt or message.

**Comment by jmalak** [comment]
What path you use for your project?
contains spaces or some special characters?

**Comment by HnkGitHub** [comment]
You can just erase the wpj file and create a new one.  Just copy the .c, and .rc file, and the .h files into a directory of your choosing and create a new project file from your directory and add those files to the project.  I purposely don't use spaces, because the build system has problems handling them in certain situations.

It's a 32-bit  nt windows exe project type.

**Comment by jmalak** [comment]
Thanks for your description.
It looks like IDE related issue.
IDE use DDE to comunicate with resource editor that it could be issue in DDE interface.
If I run resource editor as standalone application I can not reproduce it.
I will check it from IDE.

**Comment by HnkGitHub** [comment]
That's correct. This bug only appears while using the IDE. I confirmed that it does not appear when calling the editor directly.  The fixes that were put in appear also to have fixed an intermittent crash  (about 50% of the time) when closing the resource editor to return back to the IDE.

**Comment by jmalak** [comment]
There is a few problem with structures alignment, that I will fix them.
It is mainly issue in menu accelerators.
Also some prototype mismatches that I will unify types used globaly in wr and related projects (wde, wre, wresedit).
After that I will return to your problem with IDE

**Comment by jmalak** [comment]
There were a problems with command line processing.
Resource tools were using '/' switch characters but IDE used '-' switch character.
Now all tools are accepting both switch characters '/' and '-'.
I hope all problems are resolved.
Please recheck.

**Comment by HnkGitHub** [comment]
Seems to be working fine. Don't have any issues with the message popping up anymore. Seems that you've fixed and tidied up some of the other code and it hasn't been crashing on exit as before. Much easier to work with now.

Thanks
