### ISSUE TITLE
Tab completion - bug in vi editor

### ISSUE THREAD

**Issue by Gavin-Holt** [open-watcom/open-watcom-v2#813]
Hi,

When I try to use tab completion at the vi.exe command line my selected filename is appended to the end of the current string. e.g. typing

	:edit v
	
once I hit tab the selector finds the first match `vi.exe` and the command line reads:
	
	:edit vvi.exe
	
If I press tab again the next match `vi.his` is found and the command line reads 
	
	:edit vvi.his
	
If I press the arrow keys each highlighted filename is appended to the command line:
	
	:edit vvi.exevi.hisvi.txt
	

I am using character mode binnt64 vi.exe and Microsoft Windows. 

This behaviour is the same in normal and modeless mode.

Sorry I don't have the skills to explore/fix this issue.

Kind Regards Gavin Holt

**Comment by jmalak** [comment]
how you deduce that something like tab completion should be supported?

**Comment by Gavin-Holt** [comment]
Hi

Because its in the documentation: 

![image](https://user-images.githubusercontent.com/5831149/154570997-126aaaa6-e504-423d-9221-c9647698a566.png)

and nearly works on my machine!

![image](https://user-images.githubusercontent.com/5831149/154571217-b3780aef-d51b-4660-a5d9-65e1b479cdc3.png)

Kind Regards Gavin Holt

**Comment by Gavin-Holt** [comment]
Hi

My issue is the coding that handles selection of a filename when the "File Completion List" (FCL) is displayed. 

*  Before calling the FCL

![image](https://user-images.githubusercontent.com/5831149/154583750-fec01c91-276c-4977-928b-7de27e514f25.png)

*  The first "TAB" does not replace the seed string used to filter the FCL - note the extra **v**

![image](https://user-images.githubusercontent.com/5831149/154583542-c9eb1fef-49c2-4471-8ac7-2c48b8638e15.png)

*  Subsequent "TAB" does not replace the seed string used to filter the FCL - note the extra **v**

![image](https://user-images.githubusercontent.com/5831149/154583799-b15376d0-3fc9-4815-adb0-351a29d8ba95.png)

*  Any "Arrow keys" appends to the proposed  filename making a long useless string.

![image](https://user-images.githubusercontent.com/5831149/154583421-5b482354-a178-4717-947b-65f2f466c52d.png)


Kind Regards Gavin Holt

**Comment by jmalak** [comment]
What you expected?

**Comment by Gavin-Holt** [comment]
Hi

From my experience elsewhere I would expect the code for the FCL to replace the seed string with the selected filename. Tab completion of file names is not designed to select multiple files, so returning just one file name once `ENTER` is pressed.

In my example `:e v` followed by `TAB` then `TAB` and `ENTER` should return me to the command window with `:e vi.his` such that another `ENTER` will edit vi.his.

Kind Regards Gavin Holt

**Comment by jmalak** [comment]
It looks like typo fix fix both problems.
Please re-check after new build will be available.

**Comment by Gavin-Holt** [comment]
Hi Jiří 

Many thanks for taking the time to fix this issue. I have tested binnt64/vi.exe it on my Windows machines and all works perfectly.

Kind Regards Gavin Holt
