### ISSUE TITLE
Used variables deemed unused and removed at compilation-time

### ISSUE THREAD

**Issue by DADi590** [open-watcom/open-watcom-v2#825]
Hi. It seems I have to attempt some kinds of dark magic to get Watcom to understand that a variable is being used. By the way, this only happens with inline-assembler.
Example code:
```c
int main(void) {
    ...
    {
        volatile uint32_t str = getRealBlockAddrData("File size: "NL); (void) str;
        __asm {
            push    ecx
            push    dword ptr [str]
        }
        printf(1) // This is a macro with inline-assembler on it too
    }
    ...
}
```
On that sample code, the magic I used to make it not delete entirely str is to put there the `volatile` keyword. It will still complain of not being used (full warnings and warnings as errors), so `(void) str` on the end of the line. Though, Watcom seems now to be doing its best by completely deleting the 2nd push from the generated code 😂. Is this a bug? Or I messed up somewhere? If it's a bug, can it be fixed? (Can Watcom understand that C variables can be used in inline-assembler? Or I'm messing up there too?)

It's the first time I'm compiling with this so old compiler and using inline-assembler and other things, so if I messed up anywhere I'll be glad to know where and why. If not, a fix would be cool. I'm not sure what to do with this push removal now. Had not happened before in other cases.

PS: the compilation flags are `-bt=DOS -l=dos4g -fpd -mf -oi -ol+ -oneatx -ot -we -wx -za`.

**EDIT:** I just went on Google... Seems that `str` is a x86 instruction... I've been an hour on this or more trying to see why the other macros worked and this didn't. Can the syntax errors be improved on the assembler? MASM reports `push dword ptr [str]` as a syntax error instantly. Would be more helpful than compiling without errors, which is what happened here for some reason.

This happened another time when I use `ptr`, and then I realized ptr is a MASM keyword (which I use normally, so it was easy to notice). But `str` I never used, like infinite others. Took me hours to think that could be the issue again. If possible, please improve the syntax error checking. Thank you.

**Comment by jmalak** [comment]
don't expect that in-line assembler is capable to do such diagnostics if it is valid assembly statement.
It is your responsibility to understand what you are doing, especially in-line assembly code is not for beginners.
It requires knowledge of assembly language and read documentation about interfacing C and assembly code in OW documentation. Each compiler use its own specific method, it is absolutely non-portable approach.

**Comment by DADi590** [comment]
For example I just deleted the `str` variable but kept the push with `str` there. It still doesn't complain and compiles without any errors. I thought that it would complain like normal Assembly code would and would tell me right away that I'm messing up (because `str` doesn't exist on C code and is an instruction on x86, which would make the push invalid). But this is my first time with inline-assembly anyway, so there's that too.

So, ok, interesting to know all you said. Thank you!

[Btw, this will really only be used in specific conditions (this is a patch that will run inside an old game for MS-DOS, so I'm even creating standard C functions with Assembly implementation to call the game's functions) and must always be compiled with this compiler, so no problems with not being portable at all, even though I'm following the C90 standard strictly to somewhat improve that.]

**Comment by jmalak** [comment]
anyway in-line assembly has minimal error checking, it is design to be simple as fall down table until some combination of instruction parameters match with current ones. It is expected that it is simple code not too complex. Designer should understand what is doing. Any mistake on stack and program is not working properly.
