### ISSUE TITLE
how to force segment ordering with equally named segments?

### ISSUE THREAD

**Issue by LowLevelMahn** [open-watcom/open-watcom-v2#838]
thanks to your help before i've got a more or less pure C version of my test program that works as expected without any tricks
and instead of posting long blocks of code i created a small test-repo: 

https://github.com/LowLevelMahn/misc_link_tests

for the background code - if its relevant at all

my next problem is that i need to change my segment ordering
i think the ORDER directive could be of help 
https://open-watcom.github.io/open-watcom-v2-wikidocs/lguide.html#The_ORDER_Directive

why on earth do i want that?

due to how the reversed and not fully ported code works in my target reversing project works
(creates code on the fly at the end of the com program, wich is also self-modifying etc.)
i need to keep the part_2.obj code+data at the end of the main.com - not as the ultimate/clean solution 
but to ease the step-by-step porting

this is the current state

| file       | info               |                                                  
| :--------- | :----------------- |
| part_0.asm | startup code       |   
| part_1.c   | some C code        | 
| part_2.asm | some asm code/data | 
| build.bat  | build script       | 

build.bat creates the main.com

defined segments in obj files (veryfied with dmpobj output)

| obj-file   | segment  | class  | content                    |
| :--------- | :------- | :----- | :------------------------- |
| part_0.obj |  seg000  | CODE   | code + asm0_hello string   |
|            |  _DATA   | DATA   | empty                      |
| part_1.obj |  seg000  | CODE   | code                       |
|            |  CONST   | DATA   | hello from c code2 string  |
|            |  CONST2  | DATA   | hello from c code1 string  |
|            |  _DATA   | DATA   | offset var to code2 string |
| part_2.obj |  seg000  | CODE   | code + asm2_hello string, nothing behind string   |
|            |  _DATA   | DATA   | empty                      |

currently the segments gets merged this way into the single resulting main.com segment

| obj-file   | segment  | class  | content                    |
| :--------- | :------- | :----- | :------------------------- |
| part_0.obj |  seg000  | CODE   | code + asm0_hello string   |
| part_1.obj |  seg000  | CODE   | code                       |
| part_2.obj |  seg000  | CODE   | code + asm2_hello, nothing behind string   |
| part_1.obj |  _DATA   | DATA   | offset var to code2 string |
| part_1.obj |  CONST   | DATA   | hello from c code2 string  |
| part_1.obj |  CONST2  | DATA   | hello from c code1 string  |

this segment ordering is my goal - keeping the code and data of part1_.c at the same position as obj file ordering in wlink command line

| obj-file   | segment  | class  | content                    |
| :--------- | :------- | :----- | :------------------------- |
| part_0.obj |  seg000  | CODE   | code + asm0_hello string   |
| part_1.obj |  seg000  | CODE   | code                       |
| part_1.obj |  _DATA   | DATA   | offset var to code2 string |
| part_1.obj |  CONST   | DATA   | hello from c code2 string  |
| part_1.obj |  CONST2  | DATA   | hello from c code1 string  |
| part_2.obj |  seg000  | CODE   | code + asm2_hello, nothing behind string   |

if've read about the ORDER directive that seems to help in that case

https://open-watcom.github.io/open-watcom-v2-wikidocs/lguide.html#The_ORDER_Directive

but i think that my equal segment names makes it hard to use the ORDER directive
and DOSSEG seems not to fit my needs

so the question is: 

do i need to rename my segments to be able to order them or is there a more natural way doing it or a better suited directive

i think renaming my segments will cause the need to someway merge the segments
but i can't find such directive in the wlink documentation - but the whole idea could be bullshit again

**Comment by groessler** [comment]
I'd put part2.obj code into a class DATA segment.

**Comment by jmalak** [comment]
if you need order segment fragment for the same segment then it is depend on modules link order.
anyway it is not good practice to have a code depending on same segment fragments order.
Correct is to use different segments and they can be ordered transparently.

**Comment by LowLevelMahn** [comment]
> I'd put part2.obj code into a class DATA segment.

that works - and i think its good enough for a temporary solution while porting the program fully to C

> if you need order segment fragment for the same segment then it is depend on modules link order. anyway it is not good practice to have a code depending on same segment fragments order. Correct is to use different segments and they can be ordered transparently.

in the end it will be all pure C - its just keeps the original reversed code running while porting function per function

thanks
