### ISSUE TITLE
Wasm: size/sizeof Operator resolves to wrong size

### ISSUE THREAD

**Issue by LowLevelMahn** [open-watcom/open-watcom-v2#841]
im not able to reproduce the problem in a smaller szenario but its just one line in my real project

source: https://github.com/LowLevelMahn/alpha_waves_loader/blob/main/loader.asm
(simple dos com program - one asm file - based on disassembling)

in this line:
https://github.com/LowLevelMahn/alpha_waves_loader/blob/4db9166a69fbcab4e5929f5a7e2bd69a2e6bb0f1/loader.asm#L1179
cx gets set with the size of a 10 far-ptr variable - normaly 28h (10*4 bytes) - but wasm stores 78h in cx

the variable is this one: https://github.com/LowLevelMahn/alpha_waves_loader/blob/4db9166a69fbcab4e5929f5a7e2bd69a2e6bb0f1/loader.asm#L84

`maybe_10_ptr	ptr16 0Ah dup(<0>)`
so 28h is the correct value for size

build with:

```
wasm.exe -wx loader.asm
wlink.exe name loader.com format dos com file loader.obj
```

you can easily see the difference by building with IF 0 - and IF 1 and comparing the resulting com files - just one byte change

i've checked against UASM64 and MASM and both putting the value 28h into cx

**Comment by jmalak** [comment]
Thanks for your bug report.
It is old WASM bug (OW 1.9 has it too).

**Comment by LowLevelMahn** [comment]
thats my reason for always doing parallel builds with other MASM-style able assemblers
but at least UASM(a Wasm->JWasm fork) and wasm are competing for the fewest errors :)

**Comment by jmalak** [comment]
it is fixed now in git repository.
Please check with new version after rebuild.

**Comment by LowLevelMahn** [comment]
works!
