### ISSUE TITLE
32-bit GUI Programs Fail to Launch on Windows 9x

### ISSUE THREAD

**Issue by vweisner** [open-watcom/open-watcom-v2#853]
I tried to run the 32-bit Open Watcom installer on Windows 98 SE, however instead of opening, I got this error:
![OLE Error](https://user-images.githubusercontent.com/75249009/164293935-5205cef8-e30f-4920-a29a-059004321055.jpg)
I ran the latest version of the installer as of this post. I tried this program on a real computer and two different virtual machines running the OS. I did try to find any dependencies that could be an issue with no results. It runs on Windows XP Professional without this error.

My thought of where the problem could be are:
- A configuration setting for building the installer
- Broken code that calls OLE32.DLL
- The library file used to link OLE32.DLL
- Or a bug in the 32-bit development tools

I did find a workaround to install Open Watcom from the 16-bit Windows installer and install the 32-bit executables from there. The good news is I could only get the 32-bit console programs to work. The bad news is the 32-bit graphical programs (IDE for example) do not work with the same error code.

Is there any way this could be fixed so I can use the 32-bit GUI programs on Windows 98 SE and any other Windows 9x OS?

**Comment by jmalak** [comment]
#852

**Comment by jmalak** [comment]
This should be fixed now, see issue #852
