### ISSUE TITLE
Resource compiler cannot produce UTF-16 / UNICODE

### ISSUE THREAD

**Issue by danielmarschall** [open-watcom/open-watcom-v2#863]
Hello,

I need to build an ANSI DLL which contains native German characters as well as English characters. (Dialogs and StringTable resource)

The Windows Resource format requires all string to be stored as UTF-16, but OpenWatcom produces UTF-8 characters for German Umlauts (äöüß), which are then converted to UTF-16. Therefore, none of the Windows APIs can work with these strings.

Example:

Word "Vergrößerung"
Correct UTF-16 :  `56 00 65 00 72 00 67 00 72 00 F6 00 DF 00 65 00 72 00 75 00 6E 00 67 00`   ( Vergrößerung )
OpenWatcom:  `56 00 65 00 72 00 67 00 72 00 C3 00 B6 00 C3 00 78 01 65 00 72 00 75 00 6E 00 67 00`  ( VergrÃ¶Ãxerung )
Note that both "ö" and "ß" are Unicode code points <255

In Visual C++, the issue can be solved with the following code in the .rc file:
`#pragma code_page(65001)`
This gets ignored by OpenWatcom.

---

By the way, there is another problem I found while I played around with the wrc.exe settings:
If you replace `-ad` with `-zm`, then OpenWatcom produces an corrupted .res file, which crashes tools like ResourceHacker.

**Comment by jmalak** [comment]
what command line options you are using and what host system you use?

**Comment by jmalak** [comment]
Options -ad and -zm is unrelated. Only -ad can not be used with -zm.
I will check -zm option processing if something wrong.
It is not tested regularly because OW uses Watcom resource format instead of Microsoft.

**Comment by danielmarschall** [comment]
Thank you for your quick reply.

The command-line (ide2make) is:

```
d:\SVN\FilterFoundry\trunk\wpj\win_res.res : d:\SVN\FilterFoundry\trunk\win_&
res.rc .AUTODEPEND
 @d:
 cd d:\SVN\FilterFoundry\trunk\wpj
 *wrc ..\win_res.rc -bt=nt -dWIN32 -d_WIN32 -d__NT__ -dWIN_ENV=1 -dINSIDE_PH&
OTOSHOP=1 -dMSWindows=1 -i=$[:;C:\WATCOM\h;C:\WATCOM\h\nt;$(%PSAPI)\Photosho&
p;$(%PSAPI)\Pica_sp;.\ -q -ad -r -fo=win_res.res
```

The operating system is Windows 10 x64.

My code looks like this:

"language.h"

```
#define MSG_PREMIERE_COMPAT_ID 1
#define MSG_PREMIERE_COMPAT_ENUS "Test 123";
#define MSG_PREMIERE_COMPAT_DEDE "Test äöüß "
```


"win_res.rc"

```
#pragma code_page(65001)

#include "language.h"

LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US
STRINGTABLE
{
	MSG_PREMIERE_COMPAT_ID, MSG_PREMIERE_COMPAT_ENUS
	// ...
}

LANGUAGE LANG_GERMAN, SUBLANG_GERMAN
STRINGTABLE
{
	MSG_PREMIERE_COMPAT_ID, MSG_PREMIERE_COMPAT_DEDE
	//...
}
```

---

I found the reason for the problem:

My source file (language.h) is UTF-8 encoded, but without BOM.

Visual C++ automatically noticed that it is UTF-8 and handled it correctly. I understand that this auto-detection is hard (and sometimes risky), though.

If I save the file as UTF-8 with BOM, then OpenWatcom cannot read it (unexpected character).  Also UTF-16 won't work work.

```
..\language.h(1): Error! E1061: Expecting data or function declaration, but found ' '
..\language.h(1): Error! E1026: Invalid declarator
..\language.h(1): Error! E1009: Expecting ';' but found '╗'
..\language.h(1): Error! E1061: Expecting data or function declaration, but found ' '
..\language.h(1): Error! E1026: Invalid declarator
..\language.h(1): Error! E1009: Expecting ';' but found '┐'
..\language.h(1): Error! E1061: Expecting data or function declaration, but found ' '
..\language.h(250): Error! E1026: Invalid declarator
..\language.h(250): Error! E1009: Expecting ';' but found 'void'
```

---

**But I found a solution for my particular case:**
Since I just want to have English and German language, I can save "language.h" in the German ANSI character set. Then OpenWatcom can handle it correctly.

Since all German special characters ( äöüÄÖÜß ) are in the Unicode code point 0..255 , the conversation from ANSI to UTF-16 is very easy.

Other foreign languages (or having to compile multiple different code pages) won't work. I don't know if It would work if my ANSI source code could be compiled on a non-German system, though.

**Comment by danielmarschall** [comment]
Note:
After saving the files as ANSI , OpenWatcom can handle them, but now Visual C++ can't handle them anymore :(

**Comment by jmalak** [comment]
BOM is not supported yet by OW, that you must save file as pure UTF-8.
With ANSI code page it works only on Windows systems not on DOS or OS/2 or on Linux.

**Comment by danielmarschall** [comment]
Yes, in my initial setup, the file was UTF-8, without BOM.
But then, OpenWatcom saved the UTF-8 encoded string directly into UTF-16, without first decoding it

**Comment by jmalak** [comment]
Are you using -zku8 option?

**Comment by danielmarschall** [comment]
Thank you for this hint!
Indeed it works!
It is weird, I tried "-zku8" earlier this day, but it didn't work. I must have done something wrong.


About Visual Studio:
If `#pragma code_page(65001)` is existing, then the input files are expected as UTF-8 without BOM  (so, not auto-detection).
If `#pragma code_page` is set to something different, then the input files will be interpreted as this particular ANSI code page.
If `#pragma code_page` is missing, then the input files will be interpreted using the local ANSI code page.

So, to conclude, these two cases work:

If input files are German ANSI:
- For, MSVC++ "#pragma code_page" must be missing
- OpenWatcom requires "Single character set"

If input files are UTF-8 without BOM:
- For MSVC++ `#pragma code_page(65001)` must exist.
- OpenWatcom requires "-zku8"

**Comment by jmalak** [comment]
Don't forgot use -bt=nt if you generate .res for WIN32 or WIN64, it uses unicode encoding for .res file.

**Comment by danielmarschall** [comment]
Yes, I'm only deploying Win32 DLL, so -bt=nt is always set.
Thank you for your help.

The only problem remaining is `-zm` generating corrupt .res files. It is low priority, as the bug was just accidental discovery. Should I open a new bug report instead?

**Comment by jmalak** [comment]
Yes please.
If possible then give there some .res sample with the problem.

**Comment by danielmarschall** [comment]
Ok, I have posted #865
