### ISSUE TITLE
Got 'Invalid instruction with current CPU setting' trying to use shl with open-watcom.owcc-dos

### ISSUE THREAD

**Issue by DenisSalem** [open-watcom/open-watcom-v2#864]
Hello I'm new to open-watcom and I may have missed something in documentation. Sorry for that.

So I'm trying to perform binary shift with SHL instruction which I believe is a common x86 instruction. 

I'm running the following command from a xubuntu box, compiler has been installed with snap

```
open-watcom.owcc -bdos -march=i486 -O2 0x02.c -o 0x02.EXE

```

for the following code 

```
int main(int argc, char** argv) {  
    _asm {
        MOV CX, 200;
        YLOOP:
        MOV DX, 320;
        XLOOP:
        /* DOUBLE LOOP BODY */
        MOV AX, CX;
        MOV BX, CX;
        SHL AX, 8;
        SAL BX, 6;
        ADD AX, BX;
        ADD AX, DX;
        /* DOUBLE LOOP END BODY */
        DEC DX;
        JNZ XLOOP;
        DEC CX;
        JNZ YLOOP;
    };
    return 0;
}

```

Throwing

```
0x02debug.c(10): Error! E1156: Assembler error: 'Invalid instruction with current CPU setting'
0x02debug.c(11): Error! E1156: Assembler error: 'Invalid instruction with current CPU setting'
Error: Compiler returned a bad status compiling '0x02debug.c'
```

Look's like something is off with CPU type but I assumed that I was already targeting x86 CPU with -bdos and -march argument ... I'm having hard time figuring out what's wrong or what should I do. Help would be strongly appreciated.

---

Used version of open watcom

```
name:      open-watcom
summary:   Open Watcom
publisher: Zygmunt Krynicki (zygoon)
store-url: https://snapcraft.io/open-watcom
license:   Watcom-1.0
description: |
  The Open Watcom compiler suite
commands:
  - open-watcom.owcc
  - open-watcom.owcc-dos
  - open-watcom.owcc-dos4g
  - open-watcom.owcc-linux
  - open-watcom.owcc-os2
  - open-watcom.owcc-os2v2
  - open-watcom.owcc-win16
  - open-watcom.owcc-win32
  - open-watcom.wmake
snap-id:      eiCtVLtdT2PGDQTNxEX8xuNwbdL0qCSq
tracking:     latest/beta
refresh-date: 14 days ago, at 01:41 CEST
channels:
  latest/stable:    –                       
  latest/candidate: –                       
  latest/beta:      2.0 2020-03-22 (2) 90MB -
  latest/edge:      2.0 2020-04-28 (4) 89MB -
installed:          2.0            (2) 90MB -
```

**Comment by jmalak** [comment]
I am sorry it is not our distribution that I cannot to help much.
It looks like your commands
  - open-watcom.owcc
  - open-watcom.owcc-dos
  - open-watcom.owcc-dos4g
  - open-watcom.owcc-linux
  - open-watcom.owcc-os2
  - open-watcom.owcc-os2v2
  - open-watcom.owcc-win16
  - open-watcom.owcc-win32
  - open-watcom.wmake
are some aliases and probably contains some parameters.
I can only estimate what it could be and we can try to identify why it doesn't work as expected.
Try to add -v option to command line to see what options are send to compiler.

**Comment by DenisSalem** [comment]
I just suspected that indeed so I'm compiling from source to give another try.

In the mean time, I'm trying with the -v :

```
Open Watcom C/C++ x86 32-bit Compiler Driver Program
Version 2.0 beta Mar 22 2020 00:34:33 (64-bit)
Copyright (c) 2002-2020 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
	wcc -bt=dos -onatx -0 -fo=.o -fr 0x02debug.c 
Open Watcom C x86 16-bit Optimizing Compiler
Version 2.0 beta Mar 22 2020 00:26:51 (64-bit)
Copyright (c) 2002-2020 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
0x02debug.c(10): Error! E1156: Assembler error: 'Invalid instruction with current CPU setting'
0x02debug.c(11): Error! E1156: Assembler error: 'Invalid instruction with current CPU setting'
0x02debug.c: 21 lines, included 48, 0 warnings, 2 errors
Error: Compiler returned a bad status compiling '0x02debug.c'

```

So the given option would be

```
wcc -bt=dos -onatx -0 -fo=.o -fr 0x02debug.c 
```

Thank you very much for the quick reply :)

**Comment by jmalak** [comment]
I see now what problem is.
The problem is that instructions
SHL AX, 8
SAL BX, 6;
don't exist for 16-bit CPU 
valid is only forms
SHL AX, 1
SAL BX, 1
or
SHL AX, CL
SAL BX, CL

**Comment by DenisSalem** [comment]
So I need to store shift number in CL ? Damn ... That sux x)

Thank you very much !
