### ISSUE TITLE
"(" unexpected

### ISSUE THREAD

**Issue by startpimp** [open-watcom/open-watcom-v2#879]
Hey, when I'm trying to execute the following command, I got this error:
`/usr/bin/watcom/binl/wcc: 1: Syntax error: "(" unexpected`

The command:
`sudo /usr/bin/watcom/binl/wcc -4 -d3 -s -wx -ms -zl -zq -fo=/mnt/c/Users/XXXX/Desktop/XXXXX/build/stage2/c/main.obj main.c`

I don't why I got this problem, but I hope you can help me ^^

**Comment by jmalak** [comment]
Try to use following command
`/usr/bin/watcom/binl/wcc -4 -d3 -s -wx -ms -zl -fo=/mnt/c/Users/XXXX/Desktop/XXXXX/build/stage2/c/main.obj main.c`
What is content of main.c?

**Comment by startpimp** [comment]
Result of `/usr/bin/watcom/binl/wcc -4 -d3 -s -wx -ms -zl -fo=/mnt/c/Users/XXXX/Desktop/XXXXX/build/stage2/c/main.obj main.c`: `-bash: /usr/bin/watcom/binl/wcc: cannot execute binary file: Exec format error`

And here is the content of main.c:
```c
#include "stdint.h"

void _cdecl cstart_(uint16_t bootDrive)
{

}
```

**Comment by jmalak** [comment]
It looks like wrong installation.
What setup for WATCOM environment variable?
What you get by command
`/usr/bin/watcom/binl/wcc`

**Comment by jmalak** [comment]
Next potential problem can be that you use 32-bit version of executable.
If you have 64-bit version of Operating system then use 64-bit tools from `/usr/bin/watcom/binl64` directory
