### ISSUE TITLE
wcl386 linker options extended syntax.

### ISSUE THREAD

**Issue by adamyg** [open-watcom/open-watcom-v2#891]
Please consider adding an additional option to wcl386 to pass linker options,  ````"-Wl,<option>".```` and/or ````"-Xlinker option"````

The current syntax ````-"linker_directives"```` due to the use of embedded quotes can present issues when using gmake and others shells which may (dependent on the version) add quotes/escapes invalidating the argument.

Note: one of the main options passed is LIBPATH, possibility an explicit option like ````-fl=libpath```` should also be suitable.

**Comment by jmalak** [comment]
OW linker use single quotes that you don't need embeded double quotes.
