### ISSUE TITLE
gcc47 invoked explicitly on FreeBSD ?

### ISSUE THREAD

**Issue by DanPartelly** [open-watcom/open-watcom-v2#9]
Is gcc47 hard coded somewhere in the make files as a C compiler  now ? After wmake is built , the compilations stops complaining I don't have gcc47.  (I use clang as a system compiler. Anyway, FreeBSD phases out GCC and land the GNU C++ lib starting with 10.0 which will be released in a couple of months.

**Comment by ytrezq** [comment]
I would add that support for old platforms isn’t only something for legacy hardware and software.

With the embedded market there is resurgence in old instructions sets from the 80’s.
This is true for the x86 instruction set where many FPGA codes feature compatibility below the  80386.

This is also not something for guys who ant to have fun. I have a commercial device featuring a NEC SOC which provide compatibility with the 80286 and it is using ROM-DOS from datalight : a specialized version of DOS targeting embedded systems.

OS/2 is more developed than openwatcom if you look at eComStation which got the original OS/2 source code from IBM.
