### ISSUE TITLE
The -"-i" option of the DOS installer does not work as advertized

### ISSUE THREAD

**Issue by volkertb** [open-watcom/open-watcom-v2#918]
I tried this with the following build: https://github.com/open-watcom/open-watcom-v2/releases/download/2022-07-01-Build/open-watcom-2_0-c-dos.exe

When you run this executable with the `/?` parameter, it lists a number of supported options, including the following two:

- `-i` : invisible: shows no dialogs; infers -s
- `-s` : skips dialogs but shows install progress

However, when running the installer with the `-i` option, it does show dialogs, and in fact works exactly the same as `-s`.

This might not be a big deal in most situations, but I'm trying to run the installer in a non-interactive mode as part of a CI/CD pipeline, in which case noisy console output is not desirable.

Also a minor nitpick: using the letter I for this option is a bit counterinuitive, since it is often associated with the word "interactive", which is exactly the opposite of what it's supposed to do in this context. But I guess it would probably not be desirable to change the letter for this option, for historic reasons.

**Comment by jmalak** [comment]
Thanks for your report.
Please, on which platform and which installer exhibit this behavior?
Option `-i` automatically setup `-s` option, all option assignments were done by Watcom in the past and we didn't have any reason to change it.

**Comment by jmalak** [comment]
I look into code and it looks like if you use -i or -s option it doesn't show dialogs except progress bar.
It is how it was designed in the past by Watcom.
It will require to modify -i option to suppress also progress bar.
I will change the code to -i option suppress all output.

**Comment by volkertb** [comment]
Sorry for the late reply. This was with the DOS installer. See the installer executable that I linked to in my initial post above.

**Comment by jmalak** [comment]
No problem.
I did check and it is general problem common for all installers.

**Comment by jmalak** [comment]
Please could you check it in your environment if it is usable, because full display initialization is done and it only suppresses any output to display.
