### ISSUE TITLE
64bit bwasm fails to reliably build causeway\asm\cw32.asm

### ISSUE THREAD

**Issue by ABratovic** [open-watcom/open-watcom-v2#92]
For a while now I have had win7 vc2010 64bit builds stop when building cw32.asm. If I 
cd bld\causeway and run builder build it takes 3 or 4 goes to succeed.
My 32 bit build tree using OW1.9 to bootbuild builds causeway reliably.
The issue is not the N594 :Extending jump msg as I edited cw32.asm and raw_vcpi.asm to get rid of the Notes (which are not considered warnings or errors) and it still takes 3 or 4 goes to build correctly.
I also just pulled the minor wasm checkin and confirmed it does not alter the situation.

================= 21:46:47 D:\abr_apps\OW20_NTX\bld\causeway ==================
=========== 21:46:47 D:\abr_apps\OW20_NTX\bld\causeway\cw32\dosi86 ============
bwasm -q -we -d1 -DNDEBUG -fo=cw32.obj -w8 -bt=dos -DENGLISH=1 -I"../../inc"      -I"D:\abr_apps\OW20_NTX\bld/hdr/dos"  -I"D:\abr_apps\OW20_NTX\bld/watcom/h" ....\asm\cw32.asm
....\asm\raw_vcpi.asm(359): Note! N604: Far call is converted to near call.
....\asm\raw_vcpi.asm(364): Note! N604: Far call is converted to near call.
....\asm\raw_vcpi.asm(369): Note! N604: Far call is converted to near call.
....\asm\raw_vcpi.asm(374): Note! N604: Far call is converted to near call.
....\asm\cw32.asm(941): Note! N594: Extending jump
....\asm\cw32.asm(956): Note! N594: Extending jump
....\asm\cw32.asm(975): Note! N594: Extending jump
....\asm\cw32.asm(4511): Note! N594: Extending jump
....\asm\cw32.asm(4520): Note! N594: Extending jump
....\asm\cw32.asm(4522): Note! N594: Extending jump
....\asm\cw32.asm(4524): Note! N594: Extending jump
....\asm\cw32.asm(941): Note! N594: Extending jump
....\asm\cw32.asm(956): Note! N594: Extending jump
....\asm\cw32.asm(975): Note! N594: Extending jump
....\asm\cw32.asm(4511): Note! N594: Extending jump
....\asm\cw32.asm(4520): Note! N594: Extending jump
....\asm\cw32.asm(4522): Note! N594: Extending jump
....\asm\cw32.asm(4524): Note! N594: Extending jump
....\asm\cw32.asm(941): Note! N594: Extending jump
....\asm\cw32.asm(956): Note! N594: Extending jump
....\asm\cw32.asm(975): Note! N594: Extending jump
....\asm\cw32.asm(4511): Note! N594: Extending jump
....\asm\cw32.asm(4520): Note! N594: Extending jump
....\asm\cw32.asm(4522): Note! N594: Extending jump
....\asm\cw32.asm(4524): Note! N594: Extending jump
....\asm\cw32.asm(941): Note! N594: Extending jump
....\asm\cw32.asm(956): Note! N594: Extending jump
....\asm\cw32.asm(975): Note! N594: Extending jump
....\asm\cw32.asm(4511): Note! N594: Extending jump
....\asm\cw32.asm(4520): Note! N594: Extending jump
....\asm\cw32.asm(4522): Note! N594: Extending jump
....\asm\cw32.asm(4524): Note! N594: Extending jump
....\asm\cw32.asm(941): Note! N594: Extending jump
....\asm\cw32.asm(956): Note! N594: Extending jump
....\asm\cw32.asm(975): Note! N594: Extending jump
....\asm\cw32.asm(4511): Note! N594: Extending jump
....\asm\cw32.asm(4520): Note! N594: Extending jump
....\asm\cw32.asm(4522): Note! N594: Extending jump
....\asm\cw32.asm(4524): Note! N594: Extending jump
Error: Cannot Open File - cw32.obj
Error(E42): Last command making (cw32.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build         -h> => non-zero return: 2
Build failed

**Comment by jmalak** [comment]
I didn't observed it and nobody report similar problem. Close this issue.
