### ISSUE TITLE
#pragma data_seg() behaves differently than in OW 1.9 (DOS 16bit Target)

### ISSUE THREAD

**Issue by eduardocasino** [open-watcom/open-watcom-v2#925]
When developing a DOS TSR using OW 1.9 C compiler, in order to keep all the resident part (code and data) at the beginning and in the same segment, I make use of `data_seg()` and `code_seg()` pragmas in the corresponding C sources:
```
#pragma data_seg("BEGTEXT", "CODE");
#pragma code_seg("BEGTEXT", "CODE");
```
This puts all the code and data into `BEGTEXT` segment.

In OW 2.0, the `data_seg()` behaviour has changed. If I use the exact same pragmas, the compiler generates **two** `BEGTEXT` segment records, one for the code and another one for the data, and adds the latter to the `DGROUP` group, so effectively placing the code and data in different segments. Is this the expected behaviour?

**Comment by jmalak** [comment]
please could you give here compilable sample code and commands you use for compilation and linking.

**Comment by eduardocasino** [comment]
Sorry, on further inspection, I realised I got it slightly wrong. Both OW 1.9 and 2.0 generate two `BEGTEXT` segment records, one word aligned, the other byte aligned. With OW 2.0, the word aligned one is added to the `DGROUP` group, which seems to be the only difference. I'm including a very simple, useless code example with a makefile.

[test.zip](https://github.com/open-watcom/open-watcom-v2/files/9087581/test.zip)

**Comment by jmalak** [comment]
I did investigation and behavior of OW 2.0 is different from 1.9.
The problem is that in some earlier version was crippled C compiler to not include data segment created by pragma data_seg into DGROUP. It is totaly inconsistent with C++ and Fortran compilers which add these data segments to the DGROUP. OW 2.0 return to consistent behavior as original WATCOM compilers.
Anyway you can not use same segment for code and data. Best solution is to ensure that all segments (code and data) are part of DGROUP then all segments have the same base otherwise you need special startup code which do initialization of segments to be same. Other solution is to put data into code segment with __based operator.

**Comment by jmalak** [comment]
I looked on your code and I don't see any problem with OW 2.0.
Segment BEGTEXT is part of DGROUP that it is addressable by DGROUP and by segment itself.
What behavior is correct OW1.9 or OW 2.0?

**Comment by eduardocasino** [comment]
OK, the code was an oversimplification. What I expected is what OW 1.9 does: That BEGTEXT is left out of DGROUP. In the real program, I'm mixing memory models: I keep all the resident code and data in the BEGTEXT segment (tiny model) and I place it at the beginning of the final executable. The transient part (the installation and managing part) uses the small model and I place the _TEXT segment after BEGTEXT and all the DGROUP after that, so I can remove that part from memory after TSR installation. Here it is a link to the program: [vmsmount](https://sourceforge.net/p/vmsmount/code/ci/master/tree/)

**Comment by jmalak** [comment]
Don't expect the same behavior on strange code.
Anyway BEGTEXT is OW internal segment for NULL pointer check.
Standard segment order is exactly what you need that segment jiggery-pokery is not needed.
Do you know option `-nt=<code segment name>` which can define multiple near segments and doesn't use default one.
below is map for your sample which use natural segment ordering and different segment for each part.

```
Open Watcom Linker Version 2.0 beta Jul  8 2022 11:52:00 (32-bit)
Copyright (c) 2002-2022 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
Created on:       22/07/12 00:35:42
Executable Image: t1.exe
creating a DOS executable


                        +------------+
                        |   Groups   |
                        +------------+

Group                           Address              Size
=====                           =======              ====

DGROUP                          0161:0000            0000ffe0



                        +--------------+
                        |   Segments   |
                        +--------------+

Segment                Class          Group          Address         Size
=======                =====          =====          =======         ====

BEGTEXT                CODE           AUTO           0000:0000       00000007
_TEXT_TSR              CODE           AUTO           0000:0007       00000419
_TEXT_MAIN             CODE           AUTO           0000:0420       00000018
_TEXT                  CODE           AUTO           0000:0440       000011c2
FAR_DATA               FAR_DATA       AUTO           0160:0002       00000000
_NULL                  BEGDATA        DGROUP         0161:0000       00000020
_AFTERNULL             BEGDATA        DGROUP         0163:0000       00000002
CONST                  DATA           DGROUP         0163:0002       0000003c
CONST2                 DATA           DGROUP         0166:000e       00000000
_DATA                  DATA           DGROUP         0166:000e       00000196
XIB                    DATA           DGROUP         0180:0004       00000000
XI                     DATA           DGROUP         0180:0004       0000000c
XIE                    DATA           DGROUP         0181:0000       00000000
YIB                    DATA           DGROUP         0181:0000       00000000
YI                     DATA           DGROUP         0181:0000       0000000c
YIE                    DATA           DGROUP         0181:000c       00000000
STRINGS                DATA           DGROUP         0181:000c       00000000
DATA                   DATA           DGROUP         0181:000c       00000000
_BSS                   BSS            DGROUP         0181:000c       0000f5d2
STACK                  STACK          DGROUP         10df:0000       00000800
```

**Comment by jmalak** [comment]
This ordering is achived by

```
wcc -bt=dos -ms -s ... -nt=_TEXT_TSR tsr.c
wcc -bt=dos -ms -s ... -nt=_TEXT_MAIN main.c
wlink sys dos name t1 file tsr.obj, main.obj
```

**Comment by eduardocasino** [comment]
Thank you very much. So I was achieving what I wanted just because a bug in OW 19 favoured me. I wish there would be a way to put data in code segment without using the __based() modifier for each and every variable declaration, though. :smiley:

**Comment by jmalak** [comment]
Problem is not with data segment but with access to this segment if it is near segment.
OW uses DGROUP to access near data segments otherwise data segment must be far then you need to use far pointers and relocation.

**Comment by eduardocasino** [comment]
Thanks again. I can't use tiny model for the whole program because data + code exceeds 64kB. I just need data and code to be in the same segment for the resident part, so I think I'll go for the __based() way.

**Comment by jmalak** [comment]
Yes, if you have such requirements then it is best to place appropriate data into TSR segment and you can access data in TSR segment by far pointers from application which has no limitation for single segment.

**Comment by jmalak** [comment]
Try to use #pragma data_seg("_CODE") to place data to code segment it should work.
But take into account it is against current code segment it is equivalent to use __based(__segname("_CODE")), but don't required to use it for all variables explicitly.
