### ISSUE TITLE
Text Editor crashes in Win98SE

### ISSUE THREAD

**Issue by AngieAndretti** [open-watcom/open-watcom-v2#927]
I've tried the latest "open-watcom-2_0-c-win-x86.exe" 7/20/22 build, and one from 6/02/22.  When I launch the text editor from the IDE, it crashes right away.  If I change the text editor option within the IDE from the DLL to the EXE, I can edit code but the editor still crashes when I click Save.

I've also noticed the system isn't handling newline characters in the Watcom ASCII files correctly - for example the readme.txt file shows block characters where newlines should start.  Not sure if that's related in any way but it makes me think this isn't really configured ideally for Win9x.

I'd really like to write code on my Retro Win98SE PC for Win9x and DOS.  Is there a workaround for this, or perhaps an alternate/older build that would work for me right now?

![watcom_fail](https://user-images.githubusercontent.com/77195600/180073198-4ea1b618-2c79-4ba5-bacc-aaf28dc97c70.jpg)

**Comment by jmalak** [comment]
Thanks for bug report.
I will fix ASAP.
