### ISSUE TITLE
Use Clang's LibCXX as standard C++ library?

### ISSUE THREAD

**Issue by 3oheicrw** [open-watcom/open-watcom-v2#929]
And drop your own incomplete one?

https://github.com/open-watcom/open-watcom-v2/issues/892

This is a clever choice. The OrangeC project also did the same.

https://github.com/LADSoft/OrangeC

**Comment by pchapin** [comment]
This idea has been discussed before. It's harder to do than it sounds. Open Watcom can't compile a conformant Standard C++ 98 library, so a third-party library will need some adjustments before it can work with Open Watcom. This introduces the issue of how to stay synchronized with the upstream library. It's possible to do this, of course, but adding missing methods to existing OWSTL classes might be easier. Once the Open Watcom compiler can process all of C++ 98, OWSTL could be finished.

It's also a matter of what interests the contributors. Personally, I'm not interested in adapting a third-party library to work with Open Watcom. Of course, I haven't contributed much in recent years, so in that respect my opinion doesn't matter. If someone else wants to adapt an existing library to Open Watcom, that's fine. It's not something I would work on, however... for what that's worth.

**Comment by 3oheicrw** [comment]
> This idea has been discussed before. It's harder to do than it sounds. Open Watcom can't compile a conformant Standard C++ 98 library, so a third-party library will need some adjustments before it can work with Open Watcom. This introduces the issue of how to stay synchronized with the upstream library. It's possible to do this, of course, but adding missing methods to existing OWSTL classes might be easier. Once the Open Watcom compiler can process all of C++ 98, OWSTL could be finished.
> 
> It's also a matter of what interests the contributors. Personally, I'm not interested in adapting a third-party library to work with Open Watcom. Of course, I haven't contributed much in recent years, so in that respect my opinion doesn't matter. If someone else wants to adapt an existing library to Open Watcom, that's fine. It's not something I would work on, however... for what that's worth.

You don't have to use the latest LibCXX and play the catch up with upstream game. You could use any previous version of LibCXX you want. In other words, fork an old version of LibCXX.

**Comment by pchapin** [comment]
That doesn't change the fact that, at this point, limitations in the compiler are what is primarily holding back OWSTL. Sure, there are areas that could be filled in now, such as what is mentioned in issue #892, but the major missing parts are due to missing language features in the compiler. Using a third-party library won't help with that. The compiler needs updating first in either case.

**Comment by 3oheicrw** [comment]
> That doesn't change the fact that, at this point, limitations in the compiler are what is primarily holding back OWSTL. Sure, there are areas that could be filled in now, such as what is mentioned in issue #892, but the major missing parts are due to missing language features in the compiler. Using a third-party library won't help with that. The compiler needs updating first in either case.

Update the compiler is definitely needed. But I suggest follow the OrangeC project's way. Constantly testing compliant with LibCXX and improve the compiler accordingly to the final goal is able to compile LibCXX and pass all tests of LibCXX, after that the compiler is almost standard compliant.

**Comment by jmalak** [comment]
I agree with Peter, main issue is compiler C++ language features.
There is also other limitations taken from 16-bit segmented area.
Most of new implementation is not supporting segmented architectures and limited size of single segment to 64kB.
As soon as C++ compiler has implemented missing features then no problem implement more up-to-date features to STL.

**Comment by pchapin** [comment]
@jmalak brings up a good point also. Open Watcom has some unique features, such as targeting 16-bit DOS, that can cause some special concerns not shared by other C++ library implementations. The limitations on file names is one issue, for example. I'm not saying that porting another STL implementation is impossible, or even that it's a bad idea. I only caution that it will be harder to do than it might sound like. I know this from experience when I attempted to use STLport with Open Watcom a number of years ago.

In any case, adapting a third party library to use with Open Watcom isn't mutually exclusive with continuing to develop the current library (OWSTL). Anyone interested in doing that can certainly work on it.

@3oheicrw you mentioned the idea of testing standards compliance by compiling LibCXX as the Open Watcom evolves. Be aware that compliance testing is a separate issue from just compiling some particular library. LibCXX may not comply to the standard itself, or (perhaps more likely) it may contain extensions or rely on unspecified behavior that are not required by the standard. Compliance testing is tricky and generally requires tests that are specifically designed for that goal.

**Comment by rdos314** [comment]
Libraries that are linked to compilers that primarily target Unix-compatible environments have many issues when ported to other architectures. The libraries have complex dependences on the compiler, but also on the target OS and Posix. To fix this is far from trivial. In fact, I managed to create a port for RDOS for OpenWatcom, but failed with GCC. The latter failure in part was based on being unable to get patches into the system. However, if you port one of these libraries to OW, then you will need to update the compiler bindings regularly as the compiler & library evolves. This is major problem if you cannot get patches accepted for GCC / CLang.

I'm dependent on the C++ compiler, but I don't use much of the standard library, so standard compatibility is not an issue for me.

**Comment by 3oheicrw** [comment]
> I'm dependent on the C++ compiler, but I don't use much of the standard library, so standard compatibility is not an issue for me.

So you have no business here at all. Why are you here?

**Comment by 3oheicrw** [comment]
> @jmalak brings up a good point also. Open Watcom has some unique features, such as targeting 16-bit DOS, that can cause some special concerns not shared by other C++ library implementations. The limitations on file names is one issue, for example. I'm not saying that porting another STL implementation is impossible, or even that it's a bad idea. I only caution that it will be harder to do than it might sound like. I know this from experience when I attempted to use STLport with Open Watcom a number of years ago.
> 
> In any case, adapting a third party library to use with Open Watcom isn't mutually exclusive with continuing to develop the current library (OWSTL). Anyone interested in doing that can certainly work on it.
> 
> @3oheicrw you mentioned the idea of testing standards compliance by compiling LibCXX as the Open Watcom evolves. Be aware that compliance testing is a separate issue from just compiling some particular library. LibCXX may not comply to the standard itself, or (perhaps more likely) it may contain extensions or rely on unspecified behavior that are not required by the standard. Compliance testing is tricky and generally requires tests that are specifically designed for that goal.

Want to keep 16 bit? Too simple. Creating a new branch. OpenWatcom-legacy for your 16 bit stuffs and OpenWatcom-current that moving forward. Don't want to have two compilers? Well, just one compiler is also OK. Then creating a new branch too. STL-legacy for 16 bit stuffs and STL-libcxx for anything other. Easy peasy.

You know it or you don't, aren't you? GCC's libstdc++ and Clang's libcxx are desgined to use by other projects, too. LibCXX has it own tests. You don't have to create your own tests. First, use a LibCXX compiled by Clang and make sure you could compile application uses this LibCXX with OpenWatcom (link with it, include headers from it). Again, just try to pass LibCXX's own tests. Later, try to compile LibCXX by OpenWatcom itself. After that, your are pretty much standard compliant.

**Comment by 3oheicrw** [comment]
I'm out. I have nothing to say anymore. Bye.
