### ISSUE TITLE
What about become a C only compiler?

### ISSUE THREAD

**Issue by 3oheicrw** [open-watcom/open-watcom-v2#930]
If C++ is too hard, what about becoming a C only compiler and try your best to catch up to the latest C standard (which is much easier to keep up with C++ standard)? Let me clarify I didn't propose to drop C++. Only split it as an extension and temporily focus only on the plain C part. When you got the plain C part working and you are a decent standard compliant C compiler, you could back to work at C++.

**Comment by pchapin** [comment]
I'm not sure I understand what you are proposing. There is no reason resources can't be put into the C compiler now. Are you suggesting the C++ compiler be removed from the codebase? If you aren't suggesting that, then what change to the codebase are you suggesting?

**Comment by 3oheicrw** [comment]
> I'm not sure I understand what you are proposing. There is no reason resources can't be put into the C compiler now. Are you suggesting the C++ compiler be removed from the codebase? If you aren't suggesting that, then what change to the codebase are you suggesting? I am unclear about what you mean when you say "split it as an extension."

I suggest improving the plain C support to be decent enough and standard compliant (the reference for this could be Pelles C) before wasting time with C++. C++ part is on hold but doesn't get removed. Working on C++ part will be resumed when the C part was done.

**Comment by pchapin** [comment]
The C compiler has good conformance to C89/90 already. Are you finding areas where it is lacking? The C99 support is weak. Are you saying we should prioritize C99 over C++98?

In any case, the work that is done depends on what the contributors want to do. If you value C99 support, or fixing bugs in the current C89/90 compiler, I don't think anyone would discourage you from assisting with that.

**Comment by 3oheicrw** [comment]
> The C compiler has good conformance to C89/90 already. Are you finding areas where it is lacking? The C99 support is weak. Are you saying we should prioritize C99 over C++98?

Do you know the current C standard is C18 and most projects have switched to C11 already?

**Comment by jmalak** [comment]
Yes, there is more new standards, but my personal opinion is that it is problematic complex features.
All peoples are chasing new features in new standards without needing them, and subsequently a problem arises due to the portability of such applications to older standards. It's a never-ending vicious circle, put in place by Microsoft to get money for necessary upgrades. What brought such revolutionary of new versions C standards, only problems with frequent changes?

**Comment by groessler** [comment]
I fully agree!

**Comment by rdos314** [comment]
No, the C++ compiler certainly cannot be removed.

**Comment by 3oheicrw** [comment]
> No, the C++ compiler certainly cannot be removed.

Bravo to the one only read the title and comment.

**Comment by 3oheicrw** [comment]
> I fully agree!

You agreed with me or @jmalak and @pchapin ?

**Comment by 3oheicrw** [comment]
> Yes, there is more new standards, but my personal opinion is that it is problematic complex features. All peoples are chasing new features in new standards without needing them, and subsequently a problem arises due to the portability of such applications to older standards. It's a never-ending vicious circle, put in place by Microsoft to get money for necessary upgrades. What brought such revolutionary of new versions C standards, only problems with frequent changes?

The first part looks reasonable but the remaining part is problematic. Are you serious? Are you just misinformed or you are paranoid? Pushing the standard is not Microsoft. MSVC is the worst when talking about standard support among the three mainstream compilers. It's GCC and Clang that implement the latest standard and many features of the standard are actually taken from GCC and Clang extensions.

**Comment by 3oheicrw** [comment]
BTW, you need to support the standards when projects out there started to use the features from the standards! Talking about later C standards, they may not be needed now. But even C99 support is lacking is ridiculous. You should stop talking about porting to Linux. Because most of the software comprise a Linux distro will not compile if you don't at least support C99. What's the point of porting a useless compiler?

**Comment by groessler** [comment]
On 7/24/22 16:23, 3oheicrw wrote:
>
>     I fully agree!
>
> You agreed with me or @jmalak <https://github.com/jmalak> and @pchapin 
> <https://github.com/pchapin> ?
>

With @jmalak. About people running to the latest standard without need. 
(Do they know why they are adopting the latest standard?)

**Comment by 3oheicrw** [comment]
> On 7/24/22 16:23, 3oheicrw wrote: I fully agree! You agreed with me or @jmalak <https://github.com/jmalak> and @pchapin <https://github.com/pchapin> ?
> With @jmalak. About people running to the latest standard without need. (Do they know why they are adopting the latest standard?)

The purpose of a compiler is to compile code. If developers write code using features from the standards, then the compiler has to support said standard or at least that features. What is the point of a compiler can't compile code?

Why the developers write code require features from new standards? Because these features make their life easier and help they write more quality code. From what you said I know you have no knowledge of modern C++ at all.

**Comment by 3oheicrw** [comment]
I'm out. I have nothing to say anymore. Bye.
