### ISSUE TITLE
Creating a static library with a too big response fails with UB

### ISSUE THREAD

**Issue by madebr** [open-watcom/open-watcom-v2#937]
When the total size of a response file is too big, the library manger silently cuts off after around 10240 characters.
This can create either wrong arguments, or simply cuts of the trailing arguments.
It depends on where the 10240th character lies.

I can reliably reproduce this issue on Windows.

Reproducer:

The following CMake script creates 181 dummy sources, and creates a static library containing them.
```cmake
cmake_minimum_required(VERSION 3.15)
project(longlib C)
execute_process(COMMAND "${CMAKE_COMMAND}" -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/some/long/artificial/directory")

add_custom_command(OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/somelib.c"
    COMMAND "${CMAKE_COMMAND}" -E echo "int somefunc(void) { return 42; }" >"${CMAKE_CURRENT_BINARY_DIR}/somelib.c")
add_library(longlib STATIC "${CMAKE_CURRENT_BINARY_DIR}/somelib.c")
set(I 0)
while(I LESS 180)
    math(EXPR "I" "${I}+1")
    add_custom_command(OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/some/long/artificial/directory/source${I}.c"
        COMMAND "${CMAKE_COMMAND}" -E echo "int func${I}(void) { return ${I}; }" >"${CMAKE_CURRENT_BINARY_DIR}/some/long/artificial/directory/source${I}.c")
    target_sources(longlib PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/some/long/artificial/directory/source${I}.c")
endwhile()
```

Use as:
```
cmake .. -DCMAKE_C_COMPILER=wcl386 -G "Watcom WMake"
wmake
```
On my system, the error is then:
```
Error! Cannot find file 'CMakeFiles/longlib.d'
```

CMake calls the library manager using the following command:
```
wlib.exe -q -c -n -b "longlib.lib" @CMakeFiles\longlib.dir\objects1.rsp
```

When I remove some files from `CMakeFiles\longlib.dir\objects1.rsp` such that the file size dips below 10240, wlib.exe finishes successfully.

Alternatively, adding spaces to the beginning of the response file, changes the error message because the 10240 cutoff happens elsewhere.
In the example above, adding 20 spaces (=length of the path in the error message) at the beginning of the response file makes the error go away.
Too bad the library will not contain all library objects... (=UB)

**Comment by jmalak** [comment]
now no limit for file size and organization of response file (line length and line count)

**Comment by jmalak** [comment]
Please check with latest release version build.

**Comment by madebr** [comment]
Using the latest open watcom build, SDL builds find with CMake (using the `Watcom WMake` generator)
https://github.com/madebr/SDL/actions/runs/2769853592

Thank you very much!
