### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by Zopolis4** [open-watcom/open-watcom-v2#940]
While trying to build open watcom on Debian sid using gcc 12, compilation fails on the following error:
```
**** Building the dlgprs bootstrap
========== 21:10:25 /home/zopolis4/open-watcom-v2/bld/browser/dlgprs ==========
===== 21:10:25 /home/zopolis4/open-watcom-v2/bld/browser/dlgprs/binbuild ======
cl dlgprs.exe
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
Error(E42): Last command making (dlgprs.exe) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 512
Build failed
builder bootstrap build error
```
I have `build-essential` and `g++` and so on installed, so I'm not sure what the issue is here.

**Comment by jmalak** [comment]
You need to install C++ static libraries for g++

**Comment by Zopolis4** [comment]
I'm pretty sure I have them installed, there is a `libstdc++.a` file in `/usr/lib/gcc/x86_64-linux-gnu/12`.

**Comment by jmalak** [comment]
The message is transparent.
To get full command go to the bld/browser/dlgprs and run commands
```builder bootclean OWVERBOSE=1```
```builder boot OWVERBOSE=1```
You should get linking command like
```
gcc -pipe -D_BLDVER=1300 -D_CYEAR=2022 -fno-asm -fno-common -fsigned-char   -I"../../../../bld/watcom/h" -D__UNIX__ -D__FLAT__ -D__LINUX__ -D_M_X64 -D__LINUX_X64__ -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -O -g -o dlgprs.exe  -Wl,-Map,dlgprs.map bind.obj dialog.obj main.obj scanner.obj styles.obj bndytab.obj dlgytab.obj chfile.obj chbffile.obj mempool.obj  ../../../../bld/watcom/binbuild/clibext.lib  -lstdc++
```

**Comment by Zopolis4** [comment]
The linker map file is empty, and I get `fish: Unknown command: builder` when trying to run the command suggested.

**Comment by jmalak** [comment]
in this case you have wrong OW build configuration
do you have created your configuration script from  setvars.sh (template) and run it before building?

**Comment by Zopolis4** [comment]
Ah-- I think it is because my shell is not POSIX compatible when it comes to exporting variables.

**Comment by jmalak** [comment]
Yes, you need to use POSIX shell because build system is designed to use POSIX things.

**Comment by Zopolis4** [comment]
Using bash dosen't change anything.

**Comment by jmalak** [comment]
Did you tried command `builder boot OWVERBOSE=1` to check full command line?

**Comment by Zopolis4** [comment]
That still fails with `bash: builder: command not found`

**Comment by jmalak** [comment]
You have not setup OW build environment correctly.
On our build server is used GCC version 9 and it works without problem.
**`Open Watcom build environment (GCC version=9, CYEAR=2022)`**

How you start OW build?

**Comment by Zopolis4** [comment]
What's the OW build system initialization script filename?

**Comment by jmalak** [comment]
default (template) is setvars.sh
You can run it from OW tree root, but you should create your own copy and modify it for your OW location.

**Comment by Zopolis4** [comment]
Ah. Yeah that's how I've been starting the build, no luck.

**Comment by jmalak** [comment]
It is what I get after running my own configuration ow2.sh script
![ow-script-start](https://user-images.githubusercontent.com/2017260/183061178-faaf8b4a-b914-4125-87f6-bab4fe304435.png)
You should get line with configured toolchain and compiler version and current year

**Comment by Zopolis4** [comment]
Yeah, I get that (with `Open Watcom build environment (GCC version=12, CYEAR=2022)`).

**Comment by jmalak** [comment]
Then if you run builder command then it must work otherwise it it is not building anything.
builder command is control all build steps.
try to run
sh build.sh preboot
it should re-build wmake and builder, check build/binbuild/bootx.log file for problem
if it is going OK then builder must exist in build/binbuild sub-folder
run builder -? and you should get builder help page
next go to bld sub-folder and run
builder boot

**Comment by Zopolis4** [comment]
`./builder -?` works in build/binbuild, but builder boot again throws `bash: builder: command not found` in the bld subfolder.

**Comment by jmalak** [comment]
why you run ./builder it is wrong, because you refer current working directory and builder is not there.
it is reason for problems, simply run 
builder

**Comment by jmalak** [comment]
I install Debian 11 in minimal version and I tested to build OW on this installation. I did following changes.
- latest available gcc and g++ version 10
- latest available make utility
- install dosbox
- switch to bash shell
- correct sudo setup
OW build run without problem.

Your problem is somehow related to linking that it could be misconfigured linker or libraries processing.
I think it is not OW issue.

**Comment by Zopolis4** [comment]
If you still have the debian system, could you try installing fish and setting it to the default shell? Then still switching to /bin/bash and proceeding as normal.

**Comment by jmalak** [comment]
I install fish and setup it as default login shell.
After re-login I get fish as current shell then I run bash to switch to bash shell.
I run OW build in bash without any problem even if my default is fish.

**Comment by Zopolis4** [comment]
I've successfully compiled tons of other things tho, I think it has something to do with OW's curious build system.

**Comment by jmalak** [comment]
Sorry failing is gcc/g++ call of linker it is outside OW control.
My testing installation is standard Debian with standard installation of gcc/g++ and other tools.
Anyway it is issue only on your box related to your changes on the system.
You have some changes on your system that Linux linker can not find standard static libraries, why is not capable?
It has nothing to do with "OW's curious build system" we don't change anything on your system, we simply use what is install and how it is install is your business.
You need fix issue with your Linux linker and its configuration.
How linker can not see standard static libraries if you say that you have install them ????

**Comment by jmalak** [comment]
Do you think that the claim that there is a bug in OW on an unstable version of Debian is a serious approach?
