### ISSUE TITLE
Sizeof in macro causes crash

### ISSUE THREAD

**Issue by turbocat2001** [open-watcom/open-watcom-v2#941]
`#if sizeof(int)` сauses a compiler crash.

$ cat test.c
#if sizeof(int)

$ owcc -std=c99 -bdos -mcmodel=s test.c
The instruction at 0x6946642d referenced memory at 0x00000000.
The memory could not be read.
Exception fielded by 0x00403250
EAX=0x00000000 EBX=0x0019fa28 ECX=0x69450b20 EDX=0x00000000
ESI=0x69450b20 EDI=0x00000000 EBP=0x0241f948 ESP=0x0019f814
EIP=0x6946642d EFL=0x00010246 CS =0x00000023 SS =0x0000002b
DS =0x0000002b ES =0x0000002b FS =0x00000053 GS =0x0000002b
Stack dump (SS:ESP)
0x0019f840 0x0019f820 0x00000002 0x00000045 0x0019f898 0x00000002
0x0019f898 0x00000002 0x00000000 0x00000000 0x00000000 0x0019f870
0x755964a6 0x00000400 0x00000010 0x0019fac8 0x00000002 0x00000002
0x0019f8a0 0x00c80000 0x0019faa0 0x755ebe90 0x00000000 0x00000002
0x69457ecc 0x00000000 0x6944f095 0x0019f8ed 0x0019f868 0x6947567b
0x0019fa28 0x00000000 0x0019f8e1 0x0000012c 0x69450b87 0x0019f8e1
0x0000012b 0x00000001 0x0019f8d0 0x6940b8d9 0x0019f8e1 0x0019fa28
0x00000000 0x0019fe48 0x0019fa94 0x694b9fd4 0x6940bb95 0x00190005
0x0019f920 0x00000000 0x00000000 0x0019fa02 0x778dcf2a 0x00000001
0x00000240 0x778dcf46 0x69456831 0x001e0810 0x00000000 0x69410000
0x69450000 0x00000000 0x00000000 0x69450000 0x0019fdb4 0x0019fde4
0x756463e8 0x00000000 0x00000000 0x694abd60 0x75646ce8 0x00000028
Error: Unable to invoke "C:\WATCOM\BINNT\wcc.exe"`

**Comment by turbocat2001** [comment]
Sorry I'm using Cygwin.  But I think similar behavior will be if you work from cmd.

**Comment by jmalak** [comment]
Sorry do you want to say that cygwin is Windows native environment?
did you test OW in real Windows environment, because OW is native Windows application and don't use any emulation etc.

**Comment by jmalak** [comment]
There was mistake in used kind of Error message ID (out of range) for ERR_UNDEFD_MACRO_IS_ZERO used by compiler for your incorrect code. It is fixed now.

**Comment by turbocat2001** [comment]
Thanks for the solution. In the future, I will only talk about native environments. Sorry again

**Comment by jmalak** [comment]
No problem.
