### ISSUE TITLE
Problem with symbols and windows 10

### ISSUE THREAD

**Issue by Nightshades1** [open-watcom/open-watcom-v2#943]
Hello, long time ago (in 2021) i gave a try to mortal kombat trilogy, super old windows game, you can see the image of it when i used open watcom 1.9 https://user-images.githubusercontent.com/19496833/133936231-1cc1ff1a-03df-4618-8536-97163ed9d9a7.png

After many windows 10 updates, and after trying very old version of Watcom 1.5 and such, i wanted to give them a try (i always cleaned my variables environment by the way) old version up to open watcom 1.9 when using wdw.exe it will show an error that it can't find "cpp.prs" file even though all environment variable are correctly set on WINDOWS or simply by using a temporary .bat in the "game" folder, to then pass "wdw.exe mktrilw.exe"

It seem that as of now, Open Watcom 2.0 (your last build) work, but it have so much issue on windows 10, UI issue, the scrollbar doesn't show the correct position when scrolling inside window (for instance globals/modules) etc.

The Symbol parsing is bugged ? This game have embed symbols, now the "local" view show nothing when the breakpoint is hit inside a function,even clicking from the "global" window on a global variable that have TYPE, it does nothing and every variable show "0", using 'show typed' will make everything disappear like the debugger failed to parse all types.

I uploaded you MKTrilogy both Windows and DOS version, not sure if they both have the same symbol table, the dos executable is bigger somehow, MKTRILW.EXE is the one i currently try to debug without success as the local types doesn't appear while they should.

Also i tried to debug the dos game with Dosbox (and watcom installed in dosbox) and it crash with an "illegal reading",looks like Dosbox is fucked up as well 😂 

Thanks for reading 😎 
[MKT.zip](https://github.com/open-watcom/open-watcom-v2/files/9332413/MKT.zip)

**Comment by jmalak** [comment]
OW 2.0 debugger is work-in-progress (there are known problems) that if you have any problems then used OW 1.9  Debugger with OW 2.0.
Anyway if you have no local info in some module then it looks like you have not compiled appropriate module with **`-d2`** option which include "local variable" info.
For local variable may be used **`-d1+`** compiler option (C compiler only)

**Comment by Nightshades1** [comment]
> 

Hello, locals and globals shows on OW 1.9 and before, as for debugging i always use local debugging, using environment variable, then in the game folder i use from Windows Terminal wdw MKTRILW.EXE, it doesnt have any issue on OpenWatcom and launch, but the locals arent showing, and when using 'show typed' it make things dissapear.

You can use wdump you'll see that you have all, i think i'll work on a python script to analyze wdump output and apply function prototype/name for funcs/global in IDA, too much struggle with OpenWatcom, not having the source code of the program the debugger isn't that user friendly, it doesn't show the assembly as C pseudo code, so for my need i'll stick with ida for sure.

**Comment by Nightshades1** [comment]
I also wanted to mention that the game since it was basically a game made from assembler with .s mixed of .c files, for instance from the leaked source code (that is horrible to read) mkutils.h/.c have a lot of "extern" pointing to the address assembled on the executable from (.s) assembly files and much more, they are seen as a "module" .i386 from open watcom, can see the functions/globals but there's no type being shown or wdump just show the address but there's no types ? from those "assembly module" even though the mkutils.c file like others have referrence to these .i386 assembly module(s), is this normal ?

You can download the game folder here https://mega.nz/file/sjRDyTra#z5MHDbPB-qDVG1VpNEk7RcxlSeNhKiBoTZJB3BVVeyE all patches are applied and the installation is by default

Maybe i will just parse the address of globals/funcs name as i have the shitty leaked source code if we can call such mess a source code 😂  which have the types used, I uploaded you the full game folder you can find "MKTRILW.EXE" it's the windows 95 game, and MKTRIL.EXE the dos version, in the "BIN" folder.

**Comment by jmalak** [comment]
I did a small investigation with your game.
- DOS version is using DOS4G V2.01, but Open Watcom use DOS4GW V1.97, there is some problem for debugger which can not run with DOS4G V2.01 for some reason, if I run game with DO4GW V1.97 then it is failing to start again
- Windows version is using Visual studio redistributable components (I don't know which one), that it fails due to missing appropriate Microsoft DLLs

I am not sure what you want to achive. If it it is reverse engineering of this game then OW debugger is not good tool for such thing.

**Comment by jmalak** [comment]
I will look on debug info processing for **Watcom** formatm in Open Watcom V2.0, it is not used by default that it can be broken.
Open Watcom use **DWARF** format by default.

**Comment by Nightshades1** [comment]
> I will look on debug info processing for **Watcom** format in Open Watcom V2.0, it is not used by default that it can be broken somehow. Open Watcom use **DWARF** format by default.

My goal is to understand how the game work (so yes reverse engineering), this game is complicated as it was assembled with *.s gcc assembled file that contain characters palette, a custom 256bytes dictionary, and pointer to animation table, then all of this were linked on the windows game, i believe the same thing happen on the dos game, so i have to reverse engine the game and understand how they handled the "characters" sprite sheet, decompression, ideally, would be good to have all the types dumped in a "easy readable" form, so i can write a small python script and apply all in Ida Pro.

I can also tweak open watcom source and modify wdump tool too 🤔 One thing that would be really great from Open Watcom (i'm surprised that it doesn't exist) is that when we have the "local" windows, we could export the "type" inside a ".H" Header, i understand that Open Watcom debugger feature is surely not made for reverse engineering 😂 but could be an interesting feature.

Hello, nice finding, i did not know that and dipdump seem interesting, thanks for your answer.

**Comment by jmalak** [comment]
I think the best wil be using dipdump utility. It is sample application to demonstrate DIP API processing.
You can adopt it and create your own utility which will create some file with any format useful for you.
DIP modules do low-level processing of debug info (you should use WATCOM DIP module) which read
appropriate info and you get high level form and do only output formatting.
I enclosed DIP API documentation that you can use any info which you will need.
[doc.zip](https://github.com/open-watcom/open-watcom-v2/files/9338175/doc.zip)

**Comment by Nightshades1** [comment]
> I think the best will be using dipdump utility. It is sample application to demonstrate DIP API processing. You can adopt it and create your own utility which will create some output files with any format useful for you. By example all variable types, structures members, function parameter types etc. DIP modules do low-level processing of debug info (you should use WATCOM DIP module) which read appropriate info and you get high level form and do only output formatting. I enclosed DIP API documentation that you can use any info which you will need. [doc.zip](https://github.com/open-watcom/open-watcom-v2/files/9338175/doc.zip) next documentation about WATCOM debug format is first section in document [Watcom Debug Format](https://open-watcom.github.io/open-watcom-v2-wikidocs/wddoc.html#Debugging_Information_Format)

Thank you, i'll see that
