### ISSUE TITLE
W007 warning

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#965]
The `W007: &array may not produce intended result` warning is useful
but is only available in C++ mode. Is there a specific reason that it is not
available with the C compiler?

**Comment by jmalak** [comment]
Thanks for your report.
No, there is no reason to not be detected by C compiler.
I think it is mainly due to different technology of C compiler parser then for C++ compiler.

**Comment by jmalak** [comment]
C compiler should detect this issue.
Please, could you give me your sample code which exhibit this issue.

**Comment by sezero** [comment]
```c
#include <string.h>
char foo[4096];
void bar(void) {
    memset(&foo, 0, sizeof(foo));
}
void har(void) {
    memset(&foo, 0, sizeof(&foo));
}
```
Build with e.g. `wcc386 -bt=os2 -wx -bm -d0 -q -5s -fp5 -fpi87 -sg -oeatxhn -ei`
wcc386 doesn't warn, but wpp386 does emit the following as it should:
```
1.c(4): Warning! W007: col(12) '&array' may not produce intended result
1.c(7): Warning! W007: col(12) '&array' may not produce intended result
1.c(7): Warning! W007: col(28) '&array' may not produce intended result
```

**Comment by jmalak** [comment]
C++ compiler code is more transparent one test routine for every address operator on array, but C compiler has not such code, scanner is hand created that I need to check more path.
This check is only on expression such "&array + constant" or "&array - constant".
It will require to add this check to construct as in your example, may be more or if possible to rework code to check every "address of" operator on array.

**Comment by jmalak** [comment]
Now C compiler should report this issue similar then C++ compiler.

**Comment by sezero** [comment]
Will test as soon as I can, thanks.

**Comment by sezero** [comment]
I took [Last-CI-build](https://github.com/open-watcom/open-watcom-v2/releases/tag/Last-CI-build) of https://github.com/open-watcom/open-watcom-v2/commit/92ba08a948a341724dbb35308852c58bc9efe, it works, thanks. Closing the ticket.

**Comment by sezero** [comment]
Re-opening the issue: Now the C++ compiler does _not_ emit the warning, only the C compiler does.

**Comment by sezero** [comment]
> Re-opening the issue: Now the C++ compiler does _not_ emit the warning, only the C compiler does.

Ah, sorry, I was mistaken: C++ compiler does emit the warning. I just missed
using a proper warning switch. Very sorry for the noise, closing again.
