### ISSUE TITLE
c++ name mangling changed?

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#966]
A c++ library built by ow19 can't be linked to a program built by ow20.
Disassembly of the program's c++ object shows the following for example
among others:
```diff
-		EXTRN	`W?$ct:GUI_TermWin$n(iiiipn$SDL_Surface$$pn($$TE$$us)vi)_`:BYTE
+		EXTRN	`W?$CT:GUI_TermWin$N(IIIIPN$SDL_Surface$$PN($$TE$$US)VI)_`:BYTE
```

As far as I can see, some cases changed to uppercase leading to a link
failure because of missing symbols.

Was this really intended? (This isn't actually important to my use, but
wanted to report / ask anyway.)

**Comment by sezero** [comment]
Note: Linkage surely succeeds if I use `OP NOCaseexact` on the wlink command line,
but that is something I _specifically_ avoid and not do (for good reason..)

**Comment by jmalak** [comment]
Yes, mangling of C++ names were changed by upper-casing all special mangling characters and extending maximal length of mangled symbols encoding.
Take into account that generally you cannot mix OW versions of C++ generated code.

**Comment by sezero** [comment]
OK then, closing ticket.
