### ISSUE TITLE
[new user] too many of bin folders!

### ISSUE THREAD

**Issue by 44iCdnz** [open-watcom/open-watcom-v2#968]
I'm a hobbyist wanted to play with this compiler. I downloaded open-watcom-2_0-c-win-x64.exe since I wanted to build 64 bit binaries. I opened the file in 7z and I saw too many bin folders! binl, binl64, binnt, binnt64, binp, binw. What is the different between them? Which bin folder should I use for my purpose (build 64 bit binaries on windows 64 bit)? Thanks.

**Comment by 44iCdnz** [comment]
btw, is there a way to use it portable (not installing the exe)? I found it's a 7z file so I could extract it and set the env vars myself. It's school machine I shouldn't install third party program. Thanks again.

**Comment by jmalak** [comment]
Take into account that OW compilers still not support to create 64-bit code only 16-bit or 32-bit code.
OW is by nature cross-compiler that you can compile on any supported platform for any supported target.
Each of these binary directories is per one host system and contains all binaries for any supported target.
You simply select bin directory for your host system (you can simply switch it by setup of PATH environment variable).
OW support following hosts: DOS, OS/2, Windows 16/32/64-bit, Linux 32/64-bit, Netware, RDOS etc.

**Comment by jmalak** [comment]
For setup OW you can read readme.txt in OW root directory.
It describe setup after copying OW to your disk drive in directory which you prefere.

**Comment by 44iCdnz** [comment]
@jmalak done setting it up. but which compiler to use? there are so many of them. they seems to emulate popular compilers. I'm familiar with gcc. which one i should choose?

**Comment by 44iCdnz** [comment]
I ended up using the msvc clone cl.exe. Compiler seems not usable for my project: Error! E1145: Internal compiler limit exceeded, break module into smaller pieces
