### ISSUE TITLE
Build error - "encode56 should not return a value"

### ISSUE THREAD

**Issue by doehrm** [open-watcom/open-watcom-v2#969]
**** Building the mkdisk bootstrap
========= 12:33:24 /sources/watcom/open-watcom-v2/bld/setupgui/mkdisk =========
==== 12:33:24 /sources/watcom/open-watcom-v2/bld/setupgui/mkdisk/binbuild =====
bld_cl mkinf.exe
../mkinf.c:1179:5: error: void function 'encode36' should not return a value [-Wreturn-type]
    return( buffer );
    ^     ~~~~~~~~~~
1 error generated.
Error(E42): Last command making (mkinf.exe) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 512
Build failed
builder bootstrap build error

**Comment by jmalak** [comment]
it is fixed now
