### ISSUE TITLE
Build failure 

### ISSUE THREAD

**Issue by andreshs** [open-watcom/open-watcom-v2#970]
Ubuntu - have build OW2 before in the same system but now - latest master - fails as follows:

c++ brmem.obj
c++ debuglog.obj
cl wbrg.exe
= 07:26:40 /home/aschafhauser/open-watcom-v2/bld/browser/nt386 =
%make prepare_gendev_tmp_batch
gendev mono01.cop
Error(E42): Last command making (gencop;mono01.cop) returned a bad status
Error(E02): Make execution terminated
Error(E42): Last command making (../../../docs/nt/wbrw.gh) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed

**Comment by andreshs** [comment]
Closing - feel free to reopen if dosemu should work on linux?

**Comment by jmalak** [comment]
In the past was a problem with dosemu on various Linux distributions.
It was not working that we prefere to use DOSBOX which works with wgml tool anywhere also on OSX and 64-bit Windows.
Probably I will remove dosemu stuff to prevent this problem.
