### ISSUE TITLE
Unable to use tinyfiledialogs

### ISSUE THREAD

**Issue by alter-ego-of-3oheicrw** [open-watcom/open-watcom-v2#972]
Project link: https://sourceforge.net/projects/tinyfiledialogs

This is tinyfiledialogs.err: [tinyfiledialogs.err.txt](https://github.com/open-watcom/open-watcom-v2/files/9858047/tinyfiledialogs.err.txt)

**Comment by jmalak** [comment]
in this project is no any example compilable by OW.
What target platform and what host you use.
Please could you give here how you compile it and what command line you use.
Could you give here content of following environment variable.
PATH
WATCOM
INCLUDE
LIB

**Comment by alter-ego-of-3oheicrw** [comment]
> in this project is no any example compilable by OW. What target platform and what host you use. Please could you give here how you compile it and what command line you use. Could you give here content of following environment variable. PATH WATCOM INCLUDE LIB

I run OpenWatcom as portable. No installation, extract from installer .exe and use with this watcom.bat:

```
@ECHO OFF
SET WATCOM=%~dp0
SET PATH=%WATCOM%\BINNT;%WATCOM%\BINW;%PATH%
SET EDPATH=%WATCOM%\EDDAT
SET INCLUDE=%WATCOM%\H;%WATCOM%\H\NT
REM SET LIB=
REM SET WWINHELP=D:\BINW
```

**Comment by alter-ego-of-3oheicrw** [comment]
This is open-watcom-2_0-c-win-x64.exe and Windows 8.1 64 bit.

**Comment by alter-ego-of-3oheicrw** [comment]
I upgraded to latest build and incorporated your hack, now tinyfiledialogs.c compiled fine.

**Comment by alter-ego-of-3oheicrw** [comment]
I should let the maintainer to decide to close it or not. He only provided a hack but not yet implement the missing structures and functions.
