### ISSUE TITLE
Unable to build cish

### ISSUE THREAD

**Issue by alter-ego-of-3oheicrw** [open-watcom/open-watcom-v2#977]
Source code: https://github.com/TheRealMichaelWang/cish/tree/main/src

Use my build.bat:

```
@ECHO OFF

cl /nologo /c ast.c
cl /nologo /c compiler.c
cl /nologo /c debug.c
cl /nologo /c error.c
cl /nologo /c ffi.c
cl /nologo /c file.c
cl /nologo /c hash.c
cl /nologo /c machine.c
cl /nologo /c postproc.c
cl /nologo /c scanner.c
cl /nologo /c source.c
cl /nologo /c stdlibf.c
cl /nologo /c type.c
```

**Comment by jmalak** [comment]
The most of files have not EOL on last line, C non conforming files that you get appropriate messages.
You use C99 source code that you need to add appropriate switch to cl command.
Next a few mistake in your code.
Also definition if you compile for near(single-byte) or wide version is missing and code is little buggy.
Try to fix and compile with command
`cl /nologo /passwopts:-za99 /DUNICODE /c <source file>
`

**Comment by alter-ego-of-3oheicrw** [comment]
> The most of files have not EOL on last line, C non conforming files that you get appropriate messages.

How to turn off the warnings regarding that?

**Comment by alter-ego-of-3oheicrw** [comment]
> You use C99 source code that you need to add appropriate switch to cl command.

Does the compiler support C11 or later C versions? How could I compile with C11? Thanks.

**Comment by alter-ego-of-3oheicrw** [comment]
> The most of files have not EOL on last line, C non conforming files that you get appropriate messages. You use C99 source code that you need to add appropriate switch to cl command. Next a few mistake in your code. Also definition if you compile for near(single-byte) or wide version is missing and code is little buggy. Try to fix and compile with command `cl /nologo /passwopts:-za99 /DUNICODE /c <source file> `

The warnings about not EOL on last line added so much noise. BTW, it's not my code. I didn't write it. I'm trying to compile someone else's code. The code compiled out of the box on MinGW.

Please have a look at `ast.c`, `compiler.c` and `scanner.c`

**Comment by alter-ego-of-3oheicrw** [comment]
> OpenWatcom doesn't support C11. It doesn't even fully support C99. What are the errors when you compile? Maybe post those?

This zip contains the err files: [cish_err.zip](https://github.com/open-watcom/open-watcom-v2/files/9870431/cish_err.zip)

**Comment by ArmstrongJ** [comment]
Just post the text of the error in the issue.  Nobody should be downloading random zip archives.  You can post the compiler output in the issue as preformatted text pretty easily so it can just be viewed.

**Comment by alter-ego-of-3oheicrw** [comment]
> Just post the text of the error in the issue. Nobody should be downloading random zip archives. You can post the compiler output in the issue as preformatted text pretty easily so it can just be viewed.

I have done the best I can. Don't ask me more. The zip file contains the err files produced by the compiler. They are plain text, contains only compiler warnings and errors, so no unwanted software possible. You should have an antimalware software on your computer anyway. This is enough. My interest in this compiler is gone. Goodbye.
