### ISSUE TITLE
open watcom does not compile itself in a Windows XP command prompt

### ISSUE THREAD

**Issue by gfernval** [open-watcom/open-watcom-v2#984]
I don´t know why it happens, but if in the file cmnvars.bat you change only the line:

if not '%OWDEFPATH%' == '' goto skip1

by

if not "%OWDEFPATH%" == "" goto skip1

then Open Watcom sources compiles succesfully (using the latest binaries of Open Watcom 2.0) in a cmd DOS prompt of Windows XP (no other changes needed)

**Comment by jmalak** [comment]
Please, what exactly fail?

**Comment by gfernval** [comment]
Strange, now with the latest sources it works well without any changes in cmnvars.bat, but (don´t know exactly the release) with a source release from past May if I didn´t make the above change it did not compile. You can close the case.

**Comment by jmalak** [comment]
OK, if a problem occurs again then reopen the issue and add more info about what is failing.
