### ISSUE TITLE
Running build.sh crashes in `make prepare_gendev_tmp_batch`

### ISSUE THREAD

**Issue by Code-Sploit** [open-watcom/open-watcom-v2#986]
Hi,

When i run: `./build.sh` everything compiles as it should but after around 1 hour it crashes. I have included a screenshot.

OS: Kali linux 6.0.3 (self-built)
GCC: (Debian 11.3.0-5) 11.3.0

![Screenshot from 2022-10-31 12-28-45](https://user-images.githubusercontent.com/64798467/199071357-bdc07611-583b-452c-a556-387b9df075cc.png)

If you need anything else please let me know.

**Comment by jmalak** [comment]
It looks like you use dosemu, there is sometimes a problems related to 32-bit DOS wgml/gendev applications.
Try to use DOSBOX, it is supported for all OW build platforms (64-bit Windows, Linux, OSX).
It is necessary to setup DOSBOX environment variable in your configuration script.

**Comment by Code-Sploit** [comment]
I will try that thanks!

**Comment by Code-Sploit** [comment]
After trying this i got the following error. (Screenshot included)
I set DOSBOX env variable in setvars.sh to `/usr/bin/dosbox` where my program is located and it starts when i run $DOSBOX in my terminal. After that i sourced setvars.sh and ran it to be sure. Then it crashed in the build.

After this happened i tried reinstalling dosemu so i would have dosbox and dosemu on my system but that just resulted to the original crash.


![Screenshot from 2022-11-01 02-06-19](https://user-images.githubusercontent.com/64798467/199178244-03b1c4fc-2f39-4d9d-ae20-76f1d4fa982c.png)

Regards.

**Comment by jmalak** [comment]
Check if DOSBOX environment variable is set before you run OW build, because it looks like you have not setup it, because dosemu is still called.
Below is copy of my OW configuration script on Linux.
```
#!/bin/sh
# *****************************************************************
# setvars - Linux version
# *****************************************************************
# NOTE: Do not use this script directly, but copy it and
#       modify it as necessary for your own use!!

# Change this to point your Open Watcom source tree
#
# Note: '=' sign in path is not allowed (build will fail).
# Try to keep a OWROOT path short and simple like
# /tmp/ow There is dosemu used to build some parts
# of the software. dosemu can hang if OWROOT is long
# or contain long names of the directories.

export OWROOT=/home/jiri/ow2

# Set this entry to identify your toolchain used by build process
# supported values are WATCOM GCC CLANG
export OWTOOLS=GCC

# Build control related variables
##################################

# Set this variable to 1 to enable documentation build
export OWDOCBUILD=0

# Set this variable to 1 to suppress tools GUI version build
# If it is used then only tools character mode version is build
# export OWGUINOBUILD=1

# Set this variable to list of OW projects to suppress their build
# Example export OWNOBUILD=ide browser dlgprs
# export OWNOBUILD=

# Set this variable to 1 to enable build all installers
export OWDISTRBUILD=0

# Documentation related variables
##################################

# Change this to the PATH required by GhostScript for PDF creation on used host OS (optional)
# export OWGHOSTSCRIPTPATH=:

# Set appropriate variables to point to Windows help compilers which you 
# have installed
#
# OWWIN95HC specifies the Microsoft compiler used to build 32-bit ".hlp" 
#    files, common on Win 95/98/ME
# OWHHC specifies the Microsoft HTML Help Workshop compiler used to build 
#    Compressed HTML help ".chm" files, common on Win2k and later
# OWCHMCMD specifies the Free Pascal HTML Help compiler, an alternative 
#    compiler that can also build Compressed HTML help ".chm" files, 
#    available natively on non-Windows OSes
#export OWWIN95HC=hcrtf
#export OWHHC=hhc
#export OWCHMCMD=chmcmd

# build process requires WGML utility which is available only as DOS executable
# it is necessary to have some DOS emulator installed
# DOSBOX emulator is available on most platforms
# DOSEMU emulator is available on Linux (Intel platform)
# if DOSBOX emulator is used then OWDOSBOX variable must be set
# Uncoment and set OWDOSBOX variable bellow to point to DOSBOX emulator executable

export OWDOSBOX=dosbox

##################################

# Subdirectory to be used for building OW build tools
export OWOBJDIR=binbuild

export OWTOOLROOT=/home/jiri/tools

# Invoke the script for the common environment
. $OWROOT/cmnvars.sh

cd $OWROOT

```

**Comment by Code-Sploit** [comment]
That fixed the original bug but now 5 minutes after passing the section of the original bug i get the following error. (screenshot included).

![Schermafdruk van 2022-11-01 22-30-49](https://user-images.githubusercontent.com/64798467/199345683-bcc6b7a4-9518-4b02-8d36-6690f90bf85e.png)

**Comment by doehrm** [comment]
`mkdir rel`

..and then try again to build (I have the same error too).

**Comment by doehrm** [comment]
`cd bld
builder rel`

after that try again, that did it for me.

**Comment by Code-Sploit** [comment]
I get the exact same errors telling me it can't find the files in the rel directory.

**Comment by jmalak** [comment]
Oh sorry you are trying to build OW installers.
It is not supported on any platforms only on Windows, because it requires full documentation build.
Doc full set is created by Microsoft Help compilers which cannot work on Linux therefore it is possible only on Windows.
It looks like you setup OWDISTRBUILD=1 but it can not be run on Linux.

**Comment by jmalak** [comment]
You can build OW installers on Linux but can not be done directly.
You need build documentation on Windows and then copy it to Linux box.
It is how OW installers are build in Azure pipeline.
There is two independent builds, one on Windows with full documentation build and second on Linux without documentation.
Next step is merge both builds to one rel directory on Linux and build all installers on Linux from this rel directory.

**Comment by jmalak** [comment]
Anyway I checked it on my Linux box.
If subdirectory exists but is blank it reports
```
=============== 15:20:05 /home/jiri/ow2bisec/distrib/ow/dos386 ================
langdat -l filelist -k lx64 -r 20 -c ../files.dat c
mkinf -i.. -i../../include -dBldVer=2.0 -dDstDir=C:\\WATCOM -dIncl64=0  c filelist "/home/jiri/ow2bisec/rel"
Reading Info File...
Checking files...
'/home/jiri/ow2bisec/rel/h/assert.h' does not exist
'/home/jiri/ow2bisec/rel/h/complex.h' does not exist
'/home/jiri/ow2bisec/rel/h/ctype.h' does not exist
'/home/jiri/ow2bisec/rel/h/errno.h' does not exist
'/home/jiri/ow2bisec/rel/h/fenv.h' does not exist
'/home/jiri/ow2bisec/rel/h/float.h' does not exist
'/home/jiri/ow2bisec/rel/h/inttypes.h' does not exist
'/home/jiri/ow2bisec/rel/h/iso646.h' does not exist
'/home/jiri/ow2bisec/rel/h/limits.h' does not exist
'/home/jiri/ow2bisec/rel/h/locale.h' does not exist
```

If rel directory doesn't exist then it reports
```
=============== 15:19:31 /home/jiri/ow2bisec/distrib/ow/dos386 ================
langdat -l filelist -k lx64 -r 20 -c ../files.dat c
mkinf -i.. -i../../include -dBldVer=2.0 -dDstDir=C:\\WATCOM -dIncl64=0  c filelist "/home/jiri/ow2bisec/rel"

Directory '/home/jiri/ow2bisec/rel' does not exist
Error(E42): Last command making (../bin/open-watcom-2_0-c-dos.exe) returned a bad status

```

**Comment by jmalak** [comment]
It looks like you create **`rel`** subdirectory in **`bld`** , but it must be created in **OW tree root**.
Other possibility is to setup **`OWRELROOT`** environment variable which point to your preffered directory.
