### ISSUE TITLE
Bad relocation type specified

### ISSUE THREAD

**Issue by rdos314** [open-watcom/open-watcom-v2#989]
I have another file in  the OpenSSL project that the 32-bit segmented compiler struggles with. It's a huge static initialization that seems to break the 64k barrier. However, the memory model uses 32-bits, and so shouldn't emit incorrect relations for the linker. 

The source is too large to copy here, so I've uploaded an example that only requires a single source file  to build here: http://rdos.net/vc/viewvc.cgi/rdos/trunk/classlib/ssl/error/

It's the ASN1_OBJECT part that creates the problem. If I cut-off a lot of it, the errors disappears.

Of note is that the code compiles & links fine with the flat memory model, and so it is an issue with the 32-bit compact memory model only.

**Comment by jmalak** [comment]
Please, could you put here Linker MAP file to see how it looks like.
Did you check to use dmpobj tool to check relocation type in object file if it is correct 48-bit?
We need to identify if it is compiler or Linker problem.

**Comment by rdos314** [comment]
I've added all files now. You can build it from the IDE or with the makefiles created in the build process.

**Comment by jmalak** [comment]
It looks like linker problem.
There is RDOS comparison with default code and data segment if any other or zero segment then report bad relocation.
In case of compact model it report all far pointers because they are far pointers which is not one of near segments (DGROUP or code). it will require to modify code to not check for far segments.
I don't know under which condition should be segments checked and for which value.

**Comment by rdos314** [comment]
That's possible, but the data should not be far in the first place since DGROUP and code (near segments) should be 32-bit in the 32-bit compact memory model. It seems like the linker uses 16-bit offsets even when it is processing a 32-bit near segment. Alternatively, that the compiler emits code in another segment when it should use the near segment.

This is not so important as I can remove this particular code, and there is only one instance of it. OTOH, it should work and other future code might run into the same problem.

In the full OpenSSL driver, _TEXT is 0x2CC6A5, _DATA is 0x48C0, CONST is 0x1C305 and CONST2 is 0x3BBA0. IOW, both code and const segments are larger than 64k, and so the linker is able to produce combined segments that are considerably larger than 64k. The issue seems to be when one particular object file has a const segment larger than 64k.

**Comment by jmalak** [comment]
But this issue is reported only for far pointers for items from err13_DATA far segment.
It is not due to wrong fixup type. 
DUMPOBJ doesn't report any 16-bit fixup only 48-bit pointer or segment and 32-bit offset that it doesn't look as Code generator problem. It is reported from this wlink code in obj2supp.c (segment relocation)
```
#ifdef _RDOS
        if( FmtData.type & MK_RDOS ) {
            segval = fix->tgt_addr.seg;
            if( segval == FmtData.u.rdos.code_seg ) {
                segval = FmtData.u.rdos.code_sel;
            } else if( segval == FmtData.u.rdos.data_seg ) {
                segval = FmtData.u.rdos.data_sel;
            } else {
                LnkMsg( LOC+ERR+MSG_BAD_RELOC_TYPE, NULL );
            }
            if( segval == 0 ) {
                LnkMsg( LOC+ERR+MSG_BAD_RELOC_TYPE, NULL );
            }
            PUT_U16( data, segval );
            return;
        }
#endif
```

**Comment by rdos314** [comment]
If you cut-off a lot of the lines in the ASN1_OBJECT entry and reduce the size of the vector, the FAR_DATA segment no longer is created, and the driver builds just fine. 

I checked in this change, including all the new files. 

So, I would say it is a compiler issue, and not a linker issue. The compiler emits constants in a FAR_DATA segment when DGROUP exceeds 64k, which causes the linker to fail.

**Comment by jmalak** [comment]
It looks like the source of problem are debug data emitting.
All tools suppose debug data in flat 32-bit segment, but for 32-bit compact model it is created as far segment and all references are far pointers and it causes this problem.
Anyway it is two problems, first one is far segment for debug data (Code generator) and second one that wlink RDOS stuff check and remap only code and dgroup near segments even if there can be also multiple far segments.

**Comment by rdos314** [comment]
By placing debug info in a sym file, the problem is reduced, but not eliminated. The number of wrong relocations decrease when symbol data is placed in a sym file.

As for RDOS linking, code must be in a single segment and data in a single segment. I suppose that if there are FAR_DATA segments, those cannot be combined with DGROUP to form a single segment?

**Comment by rdos314** [comment]
Because I want separate code and data segments. Small model combines code & data, which is no good for protection purposes.

**Comment by jmalak** [comment]
Unfortunate we are talking about protected mode application, which can not combine such segments.
If it doesn't work then it is bug in wlink for RDOS executable segments attributes or grouping.

**Comment by rdos314** [comment]
Will the 32-bit small memory model assume that pointers are always far? That's a requirement since external pointers will not be near pointers. I think that is the reason why compact memory model must be used.

**Comment by jmalak** [comment]
If you need far pointers by default then compact model is necessary.
you should use -zt option with bigger size limit (default is 32767) to not create far data.

**Comment by jmalak** [comment]
I fixed zt option for 32-bit Intel target
for 32-bit target default value is 2147483647
for 16-bit target default value is 32767 (as before)

**Comment by jmalak** [comment]
It looks like fixed by change of zt option default value for 32-bit target
