### ISSUE TITLE
printf segmentation faults on linux

### ISSUE THREAD

**Issue by sparky4** [open-watcom/open-watcom-v2#990]
i have this code for othello
and the line printf(" %d |", j+1); crashes the program
j is an int inside a for loop

compiled with latest release on 64 bit and 32 bit linux
both times crashes

the linux version of the program crashes while the dos version works perfectly

http://4ch.mooo.com/4/C_code_1.zip
here is the code

**Comment by jmalak** [comment]
Thanks for your report.
Please, what compiler options you use?

**Comment by sparky4** [comment]
default ones

**Comment by sparky4** [comment]
np <3

**Comment by sparky4** [comment]
found another issue...
cannot compile johncampbell123's doslib

**Comment by jmalak** [comment]
Thanks

**Comment by sparky4** [comment]
np

**Comment by jmalak** [comment]
Build problem is due to mistake in doslib make files. I created pull request with fix.
https://github.com/joncampbell123/doslib/pull/59#:~:text=fix%20Watcom%20wmake%20make%20files%20%2359

**Comment by jmalak** [comment]
I cannot reproduce your issue.
What command line you use to compile?
I used latest version of OW build (64-bit version) and when run program I got 4 matrixes without any problem.

**Comment by sparky4** [comment]
let me give you the files

**Comment by sparky4** [comment]
https://4ch.mooo.com/4/C_code_1.zip i just did wcl386 on linux and completed a game and it seg faults

**Comment by sparky4** [comment]
using  November 24th version

**Comment by jmalak** [comment]
I tried your last sample and I run game, no any core dump etc.
Please check following Environment variables setup:
**`WATCOM`**=        it should be root of OW, my setup is **`/home/jiri/watcom`**
**`INCLUDE`**=         it should be OW Linux header path, my setup is **`/home/jiri/watcom/lh`**
**`PATH`**=               it should be OW Linux binaries path, my setup is **`/home/jiri/watcom/binl64`**

Mainly **`INCLUDE`** directory is important to point to target related subdirectory (**`lh`** for Linux)
I am using Ubuntu 22.04 box.

**Comment by jmalak** [comment]
I enclosed compiled game (Linux version).
[Othello.zip](https://github.com/open-watcom/open-watcom-v2/files/10095308/Othello.zip)

**Comment by sparky4** [comment]
lets see

**Comment by sparky4** [comment]
!! it works... okay let me update the thing

**Comment by sparky4** [comment]
hmmm it works now thanks!
INCLUDE only had $watcom/h not $watcom/lh

**Comment by sparky4** [comment]
got the old code of the othello program?

**Comment by jmalak** [comment]
Yes, I tested both your samples old and new with same results.
Be careful about INCLUDE environment variable, it must be setup for appropriate target.
Mostly it compiles without problem, but on runtime problems appears.
By example on Linux different default alignment then on DOS or other platforms (it is in header files).
If you compile for multiple platform frequently you can use another trick with OW.
Don't setup INCLUDE environment variable and setup target specific environment variable.
By example for DOS, Windows and Linux you can setup
```
DOS_INCLUDE=.../h
LINUX_INCLUDE=.../lh
NT_INCLUDE=.../h;.../h/nt
```
look into section about [-bt option](https://open-watcom.github.io/open-watcom-v2-wikidocs/cguide.html#btUEXosYV) in OW documentation

**Comment by sparky4** [comment]
thanks <3
