### ISSUE TITLE
Fails to build in wtypes.h

### ISSUE THREAD

**Issue by miffe** [open-watcom/open-watcom-v2#992]
Building either with gcc 12.2.0 or clang 14.0.6 fails on git commit 1ac96da41cdab01260a4b92829cd0adad8677eba with the following message:

============ 23:43:22 /home/miffe/open-watcom-v2/bld/w32api/nt386 =============
mkdir lib
mkdir lib/ddk
mkdir lib/directx
mkdir ddk
mkdir directx
lib lib/aclui.lib
cc adsiid.obj
../../../bld/w32api/nt/h/wtypes.h(129): Error! E1128: Enum constant is out of range 4294967168 to 127
../../../bld/w32api/nt/h/wtypes.h(130): Error! E1128: Enum constant is out of range 4294967168 to 127
Error(E42): Last command making (adsiid.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed

**Comment by jmalak** [comment]
it should be fixed now.

**Comment by miffe** [comment]
Yes, now it builds. Thanks!
