### ISSUE TITLE
wlib generates empty import lib if lbc file starts with a comment line

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#999]
The following is the iconv2.lbc file:
```
# OpenWatcom exports file for libiconv
++'libiconv'.'ICONV2'..'_libiconv'
++'libiconv_close'.'ICONV2'..'_libiconv_close'
++'libiconv_open'.'ICONV2'..'_libiconv_open'
```

Running `wlib -q -b -n -c -pa -s -t -zld -ii -io iconv2.lib @iconv2.lbc`
emits no errors or warning but generates an empty import lib.

Removing the comment line makes it output the expected import lib.

This was not an issue with wlib from e.g. ow-1.9.

**Comment by jmalak** [comment]
It is fixed now.
Please check.

**Comment by sezero** [comment]
Thanks - will check as soon as a CI build is available.

(BTW: Was it broken by https://github.com/open-watcom/open-watcom-v2/commit/ba0d6aca94041995491cb9caf5a547b880b65590 ?)

**Comment by sezero** [comment]
I confirm that https://github.com/open-watcom/open-watcom-v2/commit/30562d56dd546b2af240525a44439cdb39304f28 fixed the issue: thanks. Closing the ticket.
